### ISSUE TITLE
Snap to grid

### ISSUE THREAD

**Issue by cammace** [mapbox/mapbox-navigation-android#100]
https://github.com/mapbox/mapbox-navigation-android/pull/97 unblocks the possibility to implement different snap to route logics (although an API needs to be exposed to switch these out). With this possibility, we can add snap to grid/road logic inside the navigation-ui SDK which snaps the user puck to the road grid even when the users off route or no routes drawn but they are just driving around.

**Comment by danesfeder** [comment]
This work is no longer to our current pipeline - can re-open if this is something we want to pursue in the future.
