### ISSUE TITLE
No Internet connection crash when RE-CENTER  is clicked

### ISSUE THREAD

**Issue by dahu3291** [mapbox/mapbox-navigation-android#1002]
If you are unable to get directionsRoute and startNavigation for what ever reason the app will crash if you click recenter cause the camera wasn't initialized.

**Android API:** 27
**Mapbox Navigation SDK version:** 0.14.0

### Steps to trigger behavior

 1. Either turn off internet connection or comment out navigationView.startNavigation(options);
 2. Pan around map and click re-center
 3. 

### Expected behavior
Either prevent RE-CENTER button from appearing or do nothing
### Actual behavior
Crash: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.mapbox.services.android.navigation.ui.v5.camera.NavigationCamera.resetCameraPosition()' on a null object reference

**Comment by danesfeder** [comment]
Hey @dahu3291, thanks for your feedback here - we saw this bug in `0.14.0` and have addressed it in [`master`](https://github.com/mapbox/mapbox-navigation-android/blob/master/libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/NavigationView.java#L498).  Stay tuned for the upcoming `0.15.0` release and thanks for checking out the SDK!

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/8434572/41174966-9d5325c0-6b29-11e8-828b-89cc0eb3d0f4.gif)
