### ISSUE TITLE
Adding markers while Navigation in NavigationActivity

### ISSUE THREAD

**Issue by Bharathjh614** [mapbox/mapbox-navigation-android#1008]
Hey @danesfeder i used as suggested by you which is producing java null pointer exception
Icon icon = IconFactory.getInstance(NavigationActivity.this)
.fromResource(R.mipmap.ic_action_green_bike);

navigationView.getMapboxMap(map.addMarker(new MarkerOptions()
.position(new LatLng(latitude, longitude))
.icon(icon) ));
java.lang.NullPointerException: Attempt to invoke virtual method 'com.mapbox.mapboxsdk.annotations.Marker com.mapbox.mapboxsdk.maps.MapboxMap.addMarker(com.mapbox.mapboxsdk.annotations.MarkerOptions)' on a null object reference

this is the error i am getting as soon as the navigation starts

**Comment by danesfeder** [comment]
Hey @Bharathjh614, to clarify, you need to wait for the `OnNavigationReadyCallback` to fire before you can use `getMapboxMap` https://github.com/mapbox/mapbox-navigation-android/blob/master/libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/NavigationView.java#L369

I'm having a tough time seeing the issue from your code.  `navigationView.getMapboxMap(map.addMarker(new MarkerOptions()`   > `getMapboxMap()` does not take any parameters.  

In the future, please direct these types of implementation questions to https://stackoverflow.com/questions/tagged/mapbox - that way, other developers can see the issues you've run into.  We (Mapbox) keep an eye on those issues as well, so don't worry, your questions will still be answered.

**Comment by Bharathjh614** [comment]
Hey @danesfeder since navigationview extends coordinator layout i cannot extend AppcompactActivity there so i am trying to add the marker from navigation activity itself which gives me default marker
this is my navigation activity:


import android.Manifest;
import android.content.Context;
import android.content.pm.PackageManager;
import android.location.Location;
import android.media.MediaPlayer;
import android.os.AsyncTask;
import android.os.Bundle;
import android.support.annotation.Nullable;
import android.support.v4.app.ActivityCompat;
import android.support.v4.content.ContextCompat;
import android.support.v7.app.AppCompatActivity;
import android.view.LayoutInflater;
import android.widget.ImageView;
import android.widget.RelativeLayout;

import com.mapbox.android.core.location.LocationEngine;
import com.mapbox.android.core.location.LocationEngineListener;
import com.mapbox.geojson.Point;
import com.mapbox.mapboxsdk.annotations.Annotation;
import com.mapbox.mapboxsdk.annotations.Marker;
import com.mapbox.mapboxsdk.maps.MapboxMap;
import com.mapbox.services.android.navigation.ui.v5.listeners.NavigationListener;
import com.mapbox.services.android.navigation.v5.commonutilities.GPSTracker;
import com.mapbox.services.android.navigation.v5.commonutilities.JSONParser;
import com.mapbox.services.android.navigation.v5.commonutilities.PreferenceManager;
import com.mapbox.services.android.navigation.v5.commonutilities.Utilities;
import com.mapbox.services.android.navigation.v5.navigation.MapboxNavigationOptions;
import com.mapbox.services.android.navigation.v5.navigation.NavigationConstants;

import org.apache.http.NameValuePair;
import org.apache.http.message.BasicNameValuePair;
import org.json.JSONArray;
import org.json.JSONException;
import org.json.JSONObject;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Timer;
import java.util.TimerTask;

/**
 * Serves as a launching point for the custom drop-in UI, {@link NavigationView}.
 * <p>
 * Demonstrates the proper setup and usage of the view, including all lifecycle methods.
 */
public class NavigationActivity extends AppCompatActivity implements OnNavigationReadyCallback, NavigationListener, LocationEngineListener {
    private MapboxMap map;
    Annotation annotation;
    private static final String EMPTY_STRING = "";
    JSONArray Alllocations = null;
    private NavigationView navigationView;
    private boolean isRunning;
    RelativeLayout SetcustomView;
    PreferenceManager prefManger;
    private GPSTracker gpsTracker;
    private Marker marker;
    private LocationEngine locationEngine;
    boolean isTripStarted, isbikeVoice, iscycleVoice, isLastTrip;
    MediaPlayer cyclistmediaPlayer, MotorcyclistmediaPlayer;
    String tripAddress, tripType, gettripType, dType;
    Timer timer = new Timer();
    TimerTask timertask;

    @Override
    protected void onCreate(@Nullable Bundle savedInstanceState) {
        setTheme(R.style.Theme_AppCompat_NoActionBar);
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_navigation);
        navigationView = findViewById(R.id.navigationView);
        navigationView.onCreate(savedInstanceState);
        navigationView.initialize(this);
        prefManger = new PreferenceManager(this);
        tripType = getIntent().getStringExtra("rideType");
   
        gpsTracker = new GPSTracker(this);

  
    }

    @Override
    public void onStart() {
        super.onStart();
        navigationView.onStart();
    }

    @Override
    public void onResume() {
        super.onResume();
        navigationView.onResume();
    }

    @Override
    public void onLowMemory() {
        super.onLowMemory();
        navigationView.onLowMemory();
    }

    @Override
    public void onBackPressed() {
        if (timer != null) {
            timer.cancel();
            timer = null;
        }

        stopMediaPlayer();
        // If the navigation view didn't need to do anything, call super
        if (!navigationView.onBackPressed()) {
            super.onBackPressed();
        }

    }

    @Override
    protected void onSaveInstanceState(Bundle outState) {
        navigationView.onSaveInstanceState(outState);
        outState.putBoolean(NavigationConstants.NAVIGATION_VIEW_RUNNING, isRunning);
        super.onSaveInstanceState(outState);
    }

    @Override
    protected void onRestoreInstanceState(Bundle savedInstanceState) {
        super.onRestoreInstanceState(savedInstanceState);
        navigationView.onRestoreInstanceState(savedInstanceState);
        isRunning = savedInstanceState.getBoolean(NavigationConstants.NAVIGATION_VIEW_RUNNING);
    }

    @Override
    public void onPause() {
        super.onPause();
        navigationView.onPause();
    }

    @Override
    public void onStop() {
        super.onStop();
        navigationView.onStop();
    }

    @Override
    protected void onDestroy() {
        super.onDestroy();
        navigationView.onDestroy();
    }

    @Override
    public void onNavigationReady() {
        MapboxNavigationOptions.Builder navigationOptions = MapboxNavigationOptions.builder();
        NavigationViewOptions.Builder options = NavigationViewOptions.builder();
        options.navigationListener(this);
        if (!isRunning) {
            extractRoute(options);
            extractCoordinates(options);
        }


        options.navigationOptions(navigationOptions.build());
        navigationView.startNavigation(options.build());
        isRunning = true;
    }


    @Override
    public void onCancelNavigation() {
        // Navigation canceled, finish the activity
        finish();
    }

    @Override
    public void onNavigationFinished() {
        // Navigation finished, finish the activity
        finish();
    }


    private void addAllAnnotaton(int annotationId, float radius, String typeName, final double latitude, final double longitude) {

       

                navigationView.addMarker(Point.fromLngLat(longitude, latitude));

         
    }

    @Override
    public void onConnected() {
        if (ActivityCompat.checkSelfPermission(this, Manifest.permission.ACCESS_FINE_LOCATION) != PackageManager.PERMISSION_GRANTED && ActivityCompat.checkSelfPermission(this, Manifest.permission.ACCESS_COARSE_LOCATION) != PackageManager.PERMISSION_GRANTED) {
            // TODO: Consider calling
            //    ActivityCompat#requestPermissions
            // here to request the missing permissions, and then overriding
            //   public void onRequestPermissionsResult(int requestCode, String[] permissions,
            //                                          int[] grantResults)
            // to handle the case where the user grants the permission. See the documentation
            // for ActivityCompat#requestPermissions for more details.
            return;
        }
        locationEngine.requestLocationUpdates();
    }

    @Override
    public void onLocationChanged(Location location) {
        double currentLatitude = location.getLatitude();
        double currentLongitude= location.getLongitude();

        new GetAllUserLocations().execute(prefManger.getMemberInfo(Utilities.MEMBERID),""+currentLatitude,""+currentLongitude,"150",prefManger.gettriptype(Utilities.TRIPTYPE));
    }

    private class GetAllUserLocations  extends AsyncTask<String, String, JSONObject> {
    @Override
    protected JSONObject doInBackground(String... args) {
      JSONParser jParser = new JSONParser();
      List<NameValuePair> params = new ArrayList<NameValuePair>();
      params.add(new BasicNameValuePair("user_id", args[0]));
      params.add(new BasicNameValuePair("latitude", args[1]));
      params.add(new BasicNameValuePair("longitude", args[2]));
      params.add(new BasicNameValuePair("radius", args[3]));
      params.add(new BasicNameValuePair("vehicle_type", args[4]));
      JSONObject json = jParser.getJSONFromUrl(Utilities.UPDATELOCATION,params);
      return json;
    }

    @Override
    protected void onPostExecute(JSONObject json) {
      if(json != null){
        try {
          if(json.getString("status").equalsIgnoreCase("success")) {
            Alllocations = json.getJSONArray("locations");
            for (int i = 0; i < Alllocations.length(); i++) {
              JSONObject LocInfo = Alllocations.getJSONObject(i);

       addAllAnnotaton(LocInfo.getInt("id"), LocInfo.getLong("distance"), LocInfo.getString("vehicle_type"), LocInfo.getDouble("latitude"), LocInfo.getDouble("longitude"));
            }
              if(prefManger.gettriptype(Utilities.TRIPTYPE).equalsIgnoreCase("car") || prefManger.gettriptype(Utilities.TRIPTYPE).equalsIgnoreCase("truck")) {

                      if (json.getInt("cycleVoice") == 1) {
                          //     Toast.makeText(NavigationActivity.this, "Play CYcle Audio", Toast.LENGTH_SHORT).show();
                          iscycleVoice = true;
                          prefManger.StoreTripcycleVoice(true);
                          startMediaPlayer("cycle");
                          //   Intent CycleAudioServicesvc = new Intent(NavigationActivity.this, CycleAudioService.class);
                          // startService(CycleAudioServicesvc);

                      } else {
                          iscycleVoice = false;
                          prefManger.StoreTripcycleVoice(false);
                          // stopMediaPlayer();
                      }

                      if (json.getInt("bikeVoice") == 1) {
                          //       Toast.makeText(NavigationActivity.this, "Play Bike Audio", Toast.LENGTH_SHORT).show();
                          //new CustomToast().DisplayToast(MakeRide.this,"Play Bike Audio","short");
                          isbikeVoice = true;
                          prefManger.StoreTripbikeVoice(true);
                          startMediaPlayer("bike");
                          //Intent MotorBikeAudioServicesvc = new Intent(NavigationActivity.this, MotorBikeAudioService.class);
                          //startService(MotorBikeAudioServicesvc);
                      } else {
                          isbikeVoice = false;
                          prefManger.StoreTripbikeVoice(false);
                          //stopMediaPlayer();
                      }
                  }     // }
              }

        } catch (JSONException e) {
          e.printStackTrace();
        }
      }
    }
  }
    private void startMediaPlayer(String audioType){
       cyclistmediaPlayer = MediaPlayer.create(getApplicationContext(), R.raw.cycle);
        //MotorcyclistmediaPlayer = MediaPlayer.create(getApplicationContext(), R.raw.ic_motorcyclist);

       //    cyclistmediaPlayer.setLooping(true); // Set looping
           //cyclistmediaPlayer.reset();
           cyclistmediaPlayer.setVolume(100,100);
           cyclistmediaPlayer.start();

    }
    private void stopMediaPlayer(){

      //  Intent CycleAudioServicesvc=new Intent(MakeRide.this, CycleAudioService.class);
        //stopService(CycleAudioServicesvc);

//        Intent MotorBikeAudioServicesvc=new Intent(MakeRide.this, MotorBikeAudioService.class);
  //      stopService(MotorBikeAudioServicesvc);
        if(cyclistmediaPlayer!=null){
            if(cyclistmediaPlayer.isPlaying()){
                cyclistmediaPlayer.stop();
                cyclistmediaPlayer.reset();
                cyclistmediaPlayer.release();
                cyclistmediaPlayer=null;

            }
        }


    }
    @Override
  public void onNavigationRunning() {
     double currentLatitude = gpsTracker.getLatitude();
      double currentLongitude= gpsTracker.getLongitude();

      new GetAllUserLocations().execute(prefManger.getMemberInfo(Utilities.MEMBERID),""+currentLatitude,""+currentLongitude,"150",prefManger.gettriptype(Utilities.TRIPTYPE));
  }

  private void extractRoute(NavigationViewOptions.Builder options) {
    options.directionsRoute(NavigationLauncher.extractRoute(this));

  }

  private void extractCoordinates(NavigationViewOptions.Builder options) {
    HashMap<String, Point> coordinates = NavigationLauncher.extractCoordinates(this);
    if (options.build().directionsRoute() == null && coordinates.size() > 0) {
      options.origin(coordinates.get(NavigationConstants.NAVIGATION_VIEW_ORIGIN));
      options.destination(coordinates.get(NavigationConstants.NAVIGATION_VIEW_DESTINATION));
    }
  }


}

since i cannot extend AppcompactActivity i cannot call preferencemanager oncreate in navigationview as prefmanager = new PreferenceManager(this);
this is the only error i am getting if i try to do adding markers in navigation view rather than navigationactivity

**Comment by Bharathjh614** [comment]
to use preference manager i badly need to extend appcompactactivity in navigationview how can i be done?

**Comment by danesfeder** [comment]
@Bharathjh614 yeah you don't need to change the `Activity` you're using (`AppCompatActivity` is actually recommended).

The method `getMapboxMap()` gives you access to the `MapboxMap` used in `NavigationView`.  Like I said, you can use it after `OnNavigationReadyCallback` is called.  In your example:
```
private void addAllAnnotaton(int annotationId, float radius, String typeName, final double latitude, final double longitude) {
    // navigationView.addMarker(Point.fromLngLat(longitude, latitude));

   navgiationView.getMapboxMap().addMarker(YOUR_MARKER_HERE);
}
```

If you need help on how to create a custom marker, check out our docs [here](https://www.mapbox.com/android-docs/map-sdk/overview/annotations/#markers)

**Comment by Bharathjh614** [comment]
@danesfeder thanks for your help and it worked for me
can we change the default arrow which appears while navigation in navigation view and current position in mapview how can it be done?
