### ISSUE TITLE
NavigationMapRoute upcoming arrow is drawn over the destination marker

### ISSUE THREAD

**Issue by danesfeder** [mapbox/mapbox-navigation-android#1015]
The arrow layers should be shown / added underneath the marker so it doesn't become obscured:

![device-2018-06-11-165232](https://user-images.githubusercontent.com/8434572/41256645-3da9cac2-6d98-11e8-8ac8-ec0f34979ce6.png)

**Comment by Guardiola31337** [comment]
I've also noticed 

![arrow_on_top_of_puck](https://user-images.githubusercontent.com/1668582/41371233-01abec9a-6f4a-11e8-9d57-d41d05473db4.png)

when running [`MockNavigationActivity`](https://github.com/mapbox/mapbox-navigation-android/blob/master/app/src/main/java/com/mapbox/services/android/navigation/testapp/activity/MockNavigationActivity.java) from the test app.
