### ISSUE TITLE
Question: Using KML To Plot Route

### ISSUE THREAD

**Issue by Danny-James** [mapbox/mapbox-navigation-android#1019]
We use MapBox to direct our Cranes down an authorised route, this route cannot change due to the authorities approving this route, our 3rd party system generates a KML file (see attached example) how would I transfer this so the `NavigationLauncher` is able to read the data and plot the route indentically?

[Test_Haulier_3_255N180611111845RTN.txt](https://github.com/mapbox/mapbox-navigation-android/files/2094463/Test_Haulier_3_255N180611111845RTN.txt)

**Comment by Danny-James** [comment]
Could someone please help with this, or if i'm asking in the wrong place point me in the right direction? @danesfeder @Guardiola31337 ?

**Comment by danesfeder** [comment]
@Danny-James Have you tried using the `<LineString><coordinates>` and inputting those into the `MapMatching` API as we discussed in #873?

**Comment by danesfeder** [comment]
@Danny-James yeah if you are over the 100 point limit, you are going to need to update your implementation to the `NavigationView` without `NavigationLauncher`.  `NavigationView` allows multiple routes to be passed during one navigation session.  [See this example](https://github.com/mapbox/mapbox-navigation-android/blob/master/app/src/main/java/com/mapbox/services/android/navigation/testapp/activity/navigationui/WaypointNavigationActivity.java)

**Comment by Danny-James** [comment]
@danesfeder Thanks, do you have any working examples of the NavigationView, or would i need to create this from scratch? Or is their a simple copy i can use and push into my Application.

What i think i mean is the `NavigationLauncher.startNavigation` loads up the actual Navigation UI will i need to create this from Scratch?

**Comment by danesfeder** [comment]
@Danny-James https://www.mapbox.com/android-docs/navigation/overview/navigation-ui/#navigationview-activity-example would be a good place to begin

**Comment by Danny-James** [comment]
Issue Found Using Multiple `MapMatching` Requests with `NavigationView`

**Comment by danesfeder** [comment]
Thanks @Danny-James
