### ISSUE TITLE
Turn lane icons are spaced incorrectly when shown

### ISSUE THREAD

**Issue by danesfeder** [mapbox/mapbox-navigation-android#1023]
The `straight` turn lane icons are being rendered with incorrect padding (see screenshot).  These views are rendered via [`LaneStyleKit`](https://github.com/mapbox/mapbox-navigation-android/blob/master/libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/instruction/turnlane/LanesStyleKit.java).  I'm not sure how we'd like to attack this - if the stylekit code should be updated or if we should just replaced with vector assets (would be easier imo).  I'm not familiar with stylekit, but happy to try to dig with someone that can hold my hand.  

![device-2018-06-13-104129](https://user-images.githubusercontent.com/8434572/41359275-1fcf1c1c-6ef8-11e8-8ec0-ce2e3f0b73fc.png)

cc @frederoni @Cjballard

**Comment by Cjballard** [comment]
@danesfeder Just so I'm familiar - so LaneStyleKit is the library we use to render vector assets through paintcode in native format, and iOS uses the same library? Would there be a cost in replacing it with vector assets?

**Comment by danesfeder** [comment]
@Cjballard yeah that's correct https://www.paintcodeapp.com/ > generated the `LaneStyleKit.java` code.  I don't think there's a huge cost in efficiency either way here.  Optimized vector assets (like the ones you provided for the route overview button) are pretty much standard for Android at this point and imo, would be fine to be used as replacement.

**Comment by danesfeder** [comment]
@Cjballard https://github.com/mapbox/navigation-ui-resources is where the paintcode work resides.  I don't think there are any `.svg`s floating around though for vectors unfortunately.

**Comment by frederoni** [comment]
@danesfeder I think you can only style the vector icons with a single solid color so moving away from PaintCode to static vector icons would break stylable lane icons. Also, the second lane in https://github.com/mapbox/mapbox-navigation-android/issues/1023#issue-332032639 looks like it's incorrectly set up. The straight ahead icons and the left turns are mutually exclusive.

**Comment by danesfeder** [comment]
@frederoni would we be able to use attributes from the custom themes inside the vector drawables? 
 For example https://medium.com/@emmaguy/dynamically-changing-svg-colours-on-android-b026a99137ad

**Comment by frederoni** [comment]
Cool. This is a very tedious process on the iOS side so we'd still have to maintain the PaintCode files though.

**Comment by Cjballard** [comment]
@frederoni Is the spacing for turn lane icons also inconsistent/needs addressing in iOS? Would it be easier for everyone if I dove in and see if I can fix the root cause with the padding on those icons? @danesfeder

**Comment by danesfeder** [comment]
Yeah also, I remember now why we didn't do this on Android: `Additionally, this is v21+ only — the backwards compatibility support for VectorDrawables before 21 creates static pngs, so changing the theme at runtime will have no effect.` 👎  We support API 15+ so this dynamic coloring isn't an options for us unfortunately.
