### ISSUE TITLE
Custom Instructions for a given milestone

### ISSUE THREAD

**Issue by danesfeder** [mapbox/mapbox-navigation-android#103]
Right now if the user wants to add an instruction they'd need to implement their own instruction engine or handle the string building inside MilestoneEvent callback.  We should provide a way for a user to subclass Instruction and give it to their milestone builder

**Comment by danesfeder** [comment]
Discussed this with @cammace and we came up with the idea that the SDK could provide an `abstract` `Instruction` class that would require `setInstruction(RouteProgress progress)` which would return a `String` -- this would ultimately be the `String instruction` passed in the `MilestoneEventLisenter`

A user of the SDK would be able to create custom instructions like this
``` java
public class CustomInstruction extends Instruction {

  @Override
  public String setInstruction(RouteProgress progress) {
    return "Turn in " + progress.getDistanceRemaining();
  }
}
```

And then you'd be able to pass this to your custom `StepMilestone`
``` java
navigation.addMilestone(new StepMilestone.Builder()
      .setIdentifier(BEGIN_ROUTE_MILESTONE)
      .setInstruction(new CustomInstruction());
      .setTrigger(
        Trigger.all(
          Trigger.lt(TriggerProperty.STEP_INDEX, 3),
          Trigger.gt(TriggerProperty.STEP_DISTANCE_TOTAL_METERS, 200)
        )
      ).build());
```

At the time the `StepMilestone` is triggered, on the SDK side, if we see the `StepMilestone` has an included `Instruction` we will pass the `RouteProgress` to the given `Instruction` at the time of the trigger event.


Looking for some thoughts on this @ericrwolfe @zugaldia @Guardiola31337 @langsmith @tobrun 
cc: @cammace

**Comment by zugaldia** [comment]
Would/could this be used to implement OSRM Text Instructions too?

**Comment by cammace** [comment]
As far as I understand, OSRM Text Instructions serve little need since `languages` is [now a parameter](https://github.com/mapbox/mapbox-java/issues/474) for the directions API. iOS is keeping it around on their side since it is still useful to insert SSML into the instruction (something this API could handle). I'd like to remove the OSRM dependency if possible thus removing the need to maintain an additional project.

**Comment by 1ec5** [comment]
> iOS is keeping it around on their side since it is still useful to insert SSML into the instruction (something this API could handle).

It’s the responsibility of the client library to insert SSML into the instruction, since the specific SSML tags may vary by text-to-speech engine. The server API needs to be TTS vendor-neutral.

**Comment by cammace** [comment]
Right, in that case, since the instructions are being implemented in the core navigation SDK (not UI) it doesn't make sense to mark up the text since we don't know what engine they are using. 

Eventually, this can be handled inside the Navigation UI SDK when we add support for polly.

**Comment by 1ec5** [comment]
Another reason to use OSRM Text Instructions on the client side is to omit certain details in order to make the instruction fit in the allotted time: mapbox/mapbox-navigation-ios#331.
