### ISSUE TITLE
Mapbox Accept null for Api Key , but navigation sdk is not supported yet

### ISSUE THREAD

**Issue by AliKhoshraftar** [mapbox/mapbox-navigation-android#1033]
How We Can Pass Null Api Key To Mapbox ?
In Mapbox Android SDK 6.2.0-beta.2 it's resolved that when no api service needed it can accept null api key.
i'm using this version of mapbox Android SDK 6.2.0-beta.2 , but navigation SDK 0.15.0 beta2 uses 6.1.3 of mapbox SDK.
When you use 6.2.0 ?

**Comment by danesfeder** [comment]
Hey @AliKhoshraftar, we are using stable releases of the Maps SDK in the navigation UI library.  Once `6.2.0` lands, we will update our dependencies with the new release.  Thank you!
