### ISSUE TITLE
Instructions rounded to the mile

### ISSUE THREAD

**Issue by danesfeder** [mapbox/mapbox-navigation-android#104]
We currently provide mile instructions like "In 3.2 miles...." 
Would be a better UX to say "In 3 miles...."

**Comment by cammace** [comment]
Gave this more thought and realized that if a user wants the announcement to be 3 miles, they'd set the milestone to trigger at that exact moment rather then rounding an uncertain value. Thus this ticket isn't needed, the milestone just needs to be set properly.
