### ISSUE TITLE
Can we change the size of navigation icon or replace it with other icon?

### ISSUE THREAD

**Issue by Bharathjh614** [mapbox/mapbox-navigation-android#1040]
can i know is there any function to change the size of default navigation icon or replace with other icons since it is too large some markers which i have added to the navigation view are invisible navigation icon covers the markers which is big some times markers i have manually added are partially visible. So can i know to reduce the size of navigation icon or replace that with the smaller icon or any function to display the marker above navigation icon

**Comment by Bharathjh614** [comment]
![screenshot_20180620-172228 1](https://user-images.githubusercontent.com/25934993/41657003-6e605122-74af-11e8-93b3-1c5ac8bf3d7a.png)

**Comment by Guardiola31337** [comment]
Hey @Bharathjh614 👋 thanks for reaching out and report your question.

You need to follow the instructions in our docs to use the `NavigationView` which holds all of the turn-by-turn UI logic / setup https://www.mapbox.com/android-docs/navigation/overview/navigation-ui/#navigationview

You're interested in overriding https://github.com/mapbox/mapbox-navigation-android/blob/master/libandroid-navigation-ui/src/main/res/values/styles.xml#L38 so I also encourage you to 👀 https://github.com/mapbox/mapbox-plugins-android/blob/master/plugin-locationlayer/src/main/res/values/styles.xml

In any case, this issue tracker is only for bug reports with test cases and feature requests. In the future, please direct these kind of questions to https://stackoverflow.com/questions/tagged/mapbox. We keep an eye on those questions as well and it helps bring visibility to other developers that may be facing similar issues. Thanks again!
