### ISSUE TITLE
Black route lines when using Maps SDK 6.2.0

### ISSUE THREAD

**Issue by Guardiola31337** [mapbox/mapbox-navigation-android#1045]
Refs. https://github.com/mapbox/mapbox-navigation-android/pull/1044 👀 

![black_route](https://user-images.githubusercontent.com/1668582/41740577-b74edd2e-7598-11e8-91e0-80895c4a3429.png)

**Comment by danesfeder** [comment]
Arrow also missing when navigating: 
![device-2018-06-21-155114](https://user-images.githubusercontent.com/8434572/41742095-fb0e7516-756a-11e8-8175-fa0ebf1c6c55.png)

**Comment by Guardiola31337** [comment]
Tracking fix in https://github.com/mapbox/mapbox-gl-native/pull/12210
