### ISSUE TITLE
Upcoming maneuver arrow disappears after screen rotation

### ISSUE THREAD

**Issue by Guardiola31337** [mapbox/mapbox-navigation-android#1047]
Noticed that if you're stale when rotating the screen the upcoming maneuver arrow disappears 👀 

![theme_night_mode_working](https://user-images.githubusercontent.com/1668582/41745185-6f4c67c2-75a6-11e8-9fdd-305790b50a9f.gif)

**Comment by danesfeder** [comment]
This should actually no longer be an issue with #1336 landed, as we consistently call for status updates / provide `RouteProgress` now
