### ISSUE TITLE
Route instructions (overview) not correct with one waypoint

### ISSUE THREAD

**Issue by P-Zenker** [mapbox/mapbox-navigation-android#1061]
Hey,

**Android API:** 7.1.1 (Google Nexus 6)

**Mapbox Navigation SDK version:** com.mapbox.mapboxsdk:mapbox-android-navigation-ui:0.15.0

### Steps to trigger behavior

```
NavigationRoute.builder(this)
        .accessToken(Mapbox.getAccessToken())
        .origin(Point.fromLngLat(10.699819, 53.836633))
        .destination(Point.fromLngLat(10.705201, 53.834687))
        .voiceUnits(DirectionsCriteria.METRIC)
        .language(Locale.GERMAN)
        .profile(DirectionsCriteria.PROFILE_WALKING)
        .addWaypoint(Point.fromLngLat(10.700795, 53.837458))
        .build()
        .getRoute(new Callback<DirectionsResponse>() {
            @Override
            public void onResponse(Call<DirectionsResponse> call, Response<DirectionsResponse> response) {
	            directionsRoute = response.body().routes().get(0);
	            //...
	        }
	    });

 
NavigationLauncherOptions options = NavigationLauncherOptions.builder()
            .directionsRoute(directionsRoute)
            .shouldSimulateRoute(true)
            .enableOffRouteDetection(true)
            .lightThemeResId(R.style.CUNavigationViewLight)
            .build();

NavigationLauncher.startNavigation(this, options);
```

### Expected behavior
The navigation instruction overview should show the overview from second route-part after reaching first waypoint to.

### Actual behavior
Banner and voice instructions are correct. But there is no refresh in the overview - the old instructions are still displayed. 
After reaching the waypoint at "Universitätsstraße" the next overview should contain something like "Marie-Curie-Straße"

![ezgif com-video-to-gif-2](https://user-images.githubusercontent.com/23097192/41911776-dda5b8d6-794d-11e8-845d-e2cb6e5de934.gif)

**Comment by danesfeder** [comment]
@P-Zenker we will check out our logic around populating the list of these instructions, thanks for pointing this out!
