### ISSUE TITLE
Feature Request: Show alert to user when we can't find accurate location of user

### ISSUE THREAD

**Issue by siavashabdoli** [mapbox/mapbox-navigation-android#1062]
Hi all,

I want to add some functionality to Navigation for our project so we decided maybe we can contribute that on original project.

in some cases that user have bad accuracy for his location we want to disable some parts and show alert in screen for user ; something like that is already exist in waze -> a red bar appear in top of the page in case of bad GPS data. maybe we want to also disable some milestones and avoid voice instruction for example in some ranges.
so let's just start with show alert: we can categorized low accuracy 2 or 3 mode. `ok_accuracy` `bad_accuracuy` `very_bad_accuracy` (just for example :D ) if you want it can be configurable so if someone wants, can show an alert in navigation view or activity for low accuracy.

do you have any suggestion about this? I started to do this in `onProgressChange` method of `NavigationViewModel` but then I realized some low accurate locations are already filtered in `NavigationService` -> `if (isValidLocationUpdate(location))` so seems I should somehow propagate event from `NavigationService`. if I write this with considering Mapbox architecture and guidelines can we merge it? do I need to make it configurable or we can add this as permanent feature?

about milestone disabling and other parts our team is not sure yet so I can create another issue for that later. but briefly one of them is like: maybe sometimes it would be good if we cancel VoiceInstruction milestone when we have bad accuracy.

**Comment by danesfeder** [comment]
Ah okay yeah I see what you're saying now.  I feel this setup would be fine as well.  If we provide these accuracy types (`ACCURACY_POOR`, `ACCURACY_ACCEPTABLE`, `ACCURACY_GOOD` for example) then we should make sure that we define in the javadoc what exactly they mean to developers using the listener (like the meter ranges).  

> is this type enough or should I attach and dispatch location object itself for other purpose

I don't think it hurts to send the `Location` object itself as well.  This will give the developer more insight into why the `Location` fell into the given type if they choose to do so.

**Comment by siavashabdoli** [comment]
Sorry for delay we have some other priority right now So I ignored it. I will continue and develop this as soon as we need it again :) btw one question should this one is also working on `RouteProcessorBackgroundThread` ? I can handle the message with `message.what` but it's somehow against OCP; I can't find better solution.
 should I create another thread for that? this one is also may have performance problem and I can't find any threadpool in the code. any suggestion on this problem?

**Comment by danesfeder** [comment]
No problem with the delay!

> I can handle the message with message.what but it's somehow against OCP; I can't find better solution.

I'm not completely following your issue here.  Would you mind providing a code example or snippet to clarify?  Sending the accuracy type from a listener for this ticket shouldn't require any thread-related work.

**Comment by Guardiola31337** [comment]
Is this something we want to support in the `1.0` @asinghal22?

**Comment by LukasPaczos** [comment]
Closing as stale.
