### ISSUE TITLE
feature request: support custom directions objects

### ISSUE THREAD

**Issue by carocad** [mapbox/mapbox-navigation-android#107]
I dont know if this is already supported but I guess not since in the documentation it says only car, bicycle and foot. 

My question/feature request is: would it be possible for the mapbox navigation engine to accept a `directions` object that has the same shape as that of Mapbox but that provides a custom routing? 

For example:
- multi-modal routing (foot + public transport)
- route based on scenery (beauty of the path) not on time

**Comment by cammace** [comment]
You can indeed build your own `DirectionsRoute` and pass it into the navigation SDK using `mapboxNavigation.startNavigation(myRoute);`. As for supporting other means of transportation, this is more directions based rather than navigation. I'll be sure to pass along the suggestions though. Going ahead and closing but feel free to comment on this issue if you have any additional questions.

**Comment by carocad** [comment]
> You can indeed build your own DirectionsRoute and pass it into the navigation SDK using mapboxNavigation.startNavigation(myRoute);.

That is great to hear/read !

> As for supporting other means of transportation, this is more directions based rather than navigation.

Here is where I am rather concerned. The response that you get from the Mapbox directions API specifies a `mode` parameter. The `cycling` mode seems to be the more fitting one here since it contains `train` option. My question is rather, what happens if I pass an option that is not supported in the mode, for example `bus` for `walking` mode? Or should I simply pass the `unaccesible` value?

Sorry if there is a misunderstanding here. I just want to make sure that I get what you mean :)

Thanks in advance for your help

**Comment by cammace** [comment]
Tagging @danpat since he would know much more about the directions API itself.

**Comment by errazkisibawaih** [comment]
Hello everyone,
I have the same issue , I use options.directionsProfile(DirectionsCriteria.PROFILE_WALKING) but the route is not a path for walking profite.
Here is my code 
> 
NavigationViewOptions.Builder options = NavigationViewOptions.builder();
        options.origin(origin);
        options.destination(destination);
        options.awsPoolId(awsPoolId);
        options.shouldSimulateRoute(simulateRoute);
        options.directionsProfile(DirectionsCriteria.PROFILE_WALKING);
NavigationLauncher.startNavigation(this, options.build());
>
