### ISSUE TITLE
Lifecycle issues around Recenter, Route overview and Camera functionalities

### ISSUE THREAD

**Issue by Guardiola31337** [mapbox/mapbox-navigation-android#1072]
Noticed some issues around _Recenter_, _Route overview_ and _Camera_ functionalities.

- The `Recenter` button and the `SummaryBottomSheet` disappear after rotating the screen if you swipe the map and click on the top banner (show the list of instructions). Noting that the camera continues tracking the progress even if you swipe the map 👀 

![recenter_summarybottomsheet_disappear_after_instructions_list_plus_rotation](https://user-images.githubusercontent.com/1668582/42168012-1e06afc2-7e10-11e8-83db-ad53cd4619b7.gif)

- The `Recenter` button disappears after hiding the list of instructions if click on the overview button and click on the top banner (show the list of instructions). Noting that after swiping and clicking on the `Recenter` button, it comes back to normal 👀 

![recenter_disappears_after_instructions_list_plus_overview](https://user-images.githubusercontent.com/1668582/42168593-b47db102-7e11-11e8-9ca7-27c960ef3318.gif)

- The camera continues tracking after clicking on the overview button and rotating the screen 👀 

![camera_continues_tracking_after_overviewed_plus_screen_rotation](https://user-images.githubusercontent.com/1668582/42169125-294d71f6-7e13-11e8-9d06-ac5e99aa7c66.gif)

- Recenter functionality disappears after backgrounding and resuming the app. Noting that the camera continues tracking the progress even if you swipe the map 👀 

![recenter_functionality_disappears_after_backgrounding_resuming_app](https://user-images.githubusercontent.com/1668582/42169550-53062a5a-7e14-11e8-99cd-cf14ed0c42fe.gif)

I've reported all of them in the same ticket because I believe all are related - we're not dealing with the lifecycle in those situations properly.

**Comment by devotaaabel** [comment]
Also, if you rotate after creating a route but before launching navigation, it loses the route

**Comment by Guardiola31337** [comment]
Noticed that in some situations the `RECENTER` button doesn't hide when instruction view list is showing.

![recenter_button_does_not_hide_instruction_list](https://user-images.githubusercontent.com/1668582/42373640-d85348f6-8115-11e8-8299-8d68eeabf6cf.png)

Refs. https://github.com/mapbox/mapbox-navigation-android/issues/714#issuecomment-393977027 - Not completely fixed by https://github.com/mapbox/mapbox-navigation-android/pull/988

Hard to say how I got it though (because I was driving 😬). Will report extra info if seen again.

**Comment by Guardiola31337** [comment]
> Will report extra info if seen again.

Found a way of reproducing the issue. If you scroll the map and quickly click on the top banner (while the animation to hide the recenter button is happening) the recenter button appears on top of the instructions list 👀 

![recenter_on_top_of_instructions_list](https://user-images.githubusercontent.com/1668582/42646693-ed4aac36-8601-11e8-815b-7ed9fc505872.gif)

cc @devotaaabel

**Comment by Guardiola31337** [comment]
While testing the [`EmbeddedNavigationActivity`](https://github.com/mapbox/mapbox-navigation-android/blob/master/app/src/main/java/com/mapbox/services/android/navigation/testapp/activity/navigationui/EmbeddedNavigationActivity.java) from the test app noticed that the map gets automatically recentered after clicking on the overview button and then reload the style (clicking on the FAB). Also, the `RECENTER` button is still shown after that 👀 

![recentered_after_reloading_style](https://user-images.githubusercontent.com/1668582/43005973-b69939e4-8c34-11e8-9f12-e9a4eceb9c5d.gif)

**Comment by Guardiola31337** [comment]
Another OP-related issue was reported by @siavashabdoli 

> **Mapbox Navigation SDK version:0.16.0
>
> ### Steps to trigger behavior
>
> Start navigation Activity in Portrait(Landscape) mode.
> do not move to avoid new RouteProgress
> change the orientation to Landscape(Portrait)
> click on overview button in summary bottom sheet
>
> ### Expected behavior
>
> show OverView state and change camera
>
> ### Actual behavior
>
> Camera still remain on marker because RouteProgress is null in NavigationCamera

**Comment by P-Zenker** [comment]
Another issue related to recenter:

**Android API:** 25 (Google Nexus 5) &  26 (Samsung A6)
**Mapbox Navigation SDK version:0.18.0**

### Steps to trigger behavior
1. Use NavigationLauncher.startNavigation
``` 
NavigationLauncherOptions options = NavigationLauncherOptions.builder()
        .directionsRoute(directionsRoute)
        .shouldSimulateRoute(false)
        .enableOffRouteDetection(true)
        .waynameChipEnabled(true)
        .build();

NavigationLauncher.startNavigation(getActivity(), options);
```
2. Press 'Home'-Button
3. Go back to App

### Expected behavior
Recenter available

### Actual behavior
The recenter button is not available

![ezgif com-video-to-gif-2](https://user-images.githubusercontent.com/23097192/45210424-d8132180-b28f-11e8-99db-44f5dad3abfe.gif)

**Comment by Guardiola31337** [comment]
We should revisit which issues are still present.

**Comment by Guardiola31337** [comment]
@abhishek1508 are these still issues in the `1.0` UI SDK?

Definitely some of them, so the question here would be, is this something we want to prioritize?

**Comment by abhishek1508** [comment]
Let's verify
cc @JunDai @cafesilencio @langsmith

**Comment by JunDai** [comment]
This isn't an issue any more per my testing of `NavigationViewActivity` in `1.0`
