### ISSUE TITLE
Developers should be able to customize written and spoken instructions

### ISSUE THREAD

**Issue by akitchen** [mapbox/mapbox-navigation-android#1074]
See: https://github.com/mapbox/mapbox-navigation-ios/issues/637 

The aim is to provide functional parity for enabling customization of banner instructions and spoken instructions

See also: https://github.com/mapbox/mapbox-navigation-ios/issues/1503

**Comment by danesfeder** [comment]
For voice / banner instructions, we'd implement something similar to [`NavigationViewEventDispatcher#allowRerouteFrom`](https://github.com/mapbox/mapbox-navigation-android/blob/master/libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/NavigationViewEventDispatcher.java#L124-L126), where the developer would implement the listener, we would send the voice instructions / banner instructions objects and the developer would return the same type of object, modified if they choose to do so.
