### ISSUE TITLE
Android APIs compatibility (API 21-) and low screen resolutions/densities issues

### ISSUE THREAD

**Issue by Guardiola31337** [mapbox/mapbox-navigation-android#1075]
Noticed some issues while testing in a Samsung Galaxy S (GT-I9000) Android 4.1.1 with regard to Android APIs compatibility (especially API 21-) and low screen resolutions/densities 👀 

- Elevation is not supported causing the buttons in front of the list 👇
- Second instruction banner doesn’t disappear when opening the list of instructions 👇 

![buttons_in_front_of_instructions_list](https://user-images.githubusercontent.com/1668582/42177158-0a6983ce-7e2c-11e8-871c-c216eff91fc7.png)

- `RECENTER` looks weird (elevation/shadow) 👇 

![recenter_button_elevation_shadow](https://user-images.githubusercontent.com/1668582/42177389-e6e3d318-7e2c-11e8-8a52-19c168f80116.png)

- Distance between sound and feedback buttons is not optimal (too long) 👇 

![sound_feedback_long_distance](https://user-images.githubusercontent.com/1668582/42177555-707a37ac-7e2d-11e8-8b36-9b9e1404f1a7.png)

**Comment by Guardiola31337** [comment]
@abhishek1508 is this still an issue in the `1.0` UI SDK?

I believe so, so the question here would be, is this something we want to prioritize?

cc @JunDai

**Comment by abhishek1508** [comment]
Let's verify
cc @JunDai @cafesilencio @langsmith

**Comment by JunDai** [comment]
> Elevation is not supported causing the buttons in front of the list

It has been fixed by #3047 

>  Second instruction banner doesn’t disappear when opening the list of instructions

I believe this is fixed now. I verified it on a API 19 emulator and it's gone. Please check the screenshot below.
<img width="1481" alt="Screen Shot 2020-07-29 at 23 13 18" src="https://user-images.githubusercontent.com/3918950/88887362-1e115f80-d1f1-11ea-862c-83c8da09c0a8.png">

> `RECENTER` looks weird (elevation/shadow)

There is a UX change of the `RECENTER` button, to use an icon to replace the `RECENTER` text. Please refer to #3374

**Comment by JunDai** [comment]
> Distance between sound and feedback buttons is not optimal (too long) 👇

This is a valid issue, I will create a new issue to track this. And put a fix of it.
