### ISSUE TITLE
Update description_navigation_view_ui key in Transifex

### ISSUE THREAD

**Issue by Guardiola31337** [mapbox/mapbox-navigation-android#1077]
In https://github.com/mapbox/mapbox-navigation-android/pull/1076 we've changed one of the keys of an already translated string. In order to avoid the community to translate the "new" string again we should update it in Transifex somehow.

Old key 👉 `description_navigation_view_ui`
New key 👉 `description_navigation_launcher`

I know that it's possible to sync up Transifex uploading the different `strings.xml` but I also guess that should be an easier way for this kind of situations (like updating the key through the Transifex UI so it gets populated through the already translations). Do you know @1ec5? Could you help here?

cc'ing @danesfeder and @langsmith that have also worked with Transifex

**Comment by 1ec5** [comment]
> I know that it's possible to sync up Transifex uploading the different strings.xml but I also guess that should be an easier way for this kind of situations (like updating the key through the Transifex UI so it gets populated through the already translations).

Renaming a key effectively clears the translation status for that key across all languages. Translators are then responsible for manually accepting the 💯 match provided by Transifex via translation memory. Sometimes after I rename a key, I’ll go in and accept these matches for translators if I’m feeling confident about the continued accuracy of the translations.

**Comment by Guardiola31337** [comment]
Going to reopen here until we ensure that we only have two strings in Transifex - `title_navigation_launcher` needing translations and `description_navigation_launcher` accepting the matches because old and new translations haven't changed at all.

**Comment by 1ec5** [comment]
`title_navigation_launcher` and `description_navigation_launcher` are both present. `description_navigation_view_ui` is not. (In Transifex, go to the translation page for a particular localization’s “Test App Strings” resource and search for `key:title_navigation_launcher` or `key:description_navigation_launcher`.)

**Comment by Guardiola31337** [comment]
@1ec5 
> `title_navigation_launcher` and `description_navigation_launcher` are both present. `description_navigation_view_ui` is not.

This makes sense because we removed `description_navigation_view_ui` (replaced by `description_navigation_launcher`) and add `title_navigation_launcher`.

The problem is that now we need to "accept" all the new "suggested" translations for `description_navigation_launcher` (when those values haven't changed) and I was wondering if there was an easier way of updating keys in Transifex rather than going one by one accepting the match. Does that make sense?

**Comment by 1ec5** [comment]
Since files such as values-id/strings.xml were updated to assign the new key to the existing value, it is possible to upload each translated file to Transifex, and the `tx` command line tool can help with that. However, I think uploading a partially translated file would cause untranslated strings to be marked as translated.

Generally, resetting translation status is an opportunity for translators to rereview their work for accuracy. In the case where we know there’s no change in meaning from what was there before, the best option is to manually approve 100% matches for translators. If that’s too tedious, consider it a reason to keep the keys stable.

**Comment by Guardiola31337** [comment]
> it is possible to upload each translated file to Transifex, and the `tx` command line tool can help with that.

Correct, that's what I thought.

> However, I think uploading a partially translated file would cause untranslated strings to be marked as translated.

Could be (I don't know either), we'd need to 🕵️ 

> Generally, resetting translation status is an opportunity for translators to rereview their work for accuracy.

Yeah, good point 💯 

> In the case where we know there’s no change in meaning from what was there before, the best option is to manually approve 100% matches for translators.

I see.

Thanks for clarifying @1ec5

**Comment by Guardiola31337** [comment]
Ok. I went ahead and approved 100% matches manually. As soon as https://github.com/mapbox/mapbox-navigation-android/pull/1088 lands we're good here.
