### ISSUE TITLE
Engine consider end of first leg as arrival (multi-legs navigation doesn't work)

### ISSUE THREAD

**Issue by Grsmto** [mapbox/mapbox-navigation-android#108]
**Platform:** Android 7.1.2
**SDK version:** Latest SNAPSHOT

### Steps to trigger behavior

 1. Set a route with more than 1 leg
 2. Navigation stops at the end of the first leg

This is closely related to the PR I sent about waypoint support, as multi-legs routes are often routes with waypoints (but I believe there is other scenarios where a route can have multiple legs).
I will soon land a PR for this.

### Expected behavior
Navigation should not end until the last leg.

### Actual behavior
Navigation stops at leg index 0.

**Comment by 1ec5** [comment]
Duplicate of #27.
