### ISSUE TITLE
General rerouting detection issue

### ISSUE THREAD

**Issue by richjhart** [mapbox/mapbox-navigation-android#1082]
**Android API:** N/A
**Mapbox Navigation SDK version:** 0.15.0

### Steps to trigger behavior

 1. Navigate as normal, typically slowly
 2. Trigger a "turn" more than 25 metres before an intersection. This is a bit random but not uncommon
 3. Wait for next location update without moving closer to the intersection

### Expected behavior

- Navigation continues as normal

### Actual behavior

- Rerouting is triggered

As far as I can tell, there are two issues going on here that contribute to this.

- The first is that's it possible to trigger a turn with up to 40 metres left by default. This can easily leave you more than 25 metres from the current step now that the step has moved on. (and 25 metres seems to be the default distance that it compares)
- The second is that the Navigation options secondsBeforeReroute() and maximumDistanceOffRoute() don't seem to do anything - so the off-route detection can't be made less sensitive.

**Comment by Guardiola31337** [comment]
Hey @richjhart and @siavashabdoli 👋 would you mind testing again with [`0.22.0`](https://github.com/mapbox/mapbox-navigation-android/releases/tag/v0.22.0)? A lot of our underlying route-following logic has been updated. Thanks in advance!

**Comment by Guardiola31337** [comment]
Hey @richjhart and @siavashabdoli I'm going to go ahead and close this as stale - please feel free to cut a new ticket if you're experience OP again.
