### ISSUE TITLE
Map Matching Issue

### ISSUE THREAD

**Issue by jackhd1** [mapbox/mapbox-navigation-android#1085]
**Android API: 7.0
**Mapbox Navigation SDK version:6.1.3

### Steps to trigger behavior

 1. Request a route using Mapbox map matching builder with specified waypoints
 2. No matches are found

I want to request custom routes using Mapbox map matching but I only want the first and last (origin and destination) coordinates to be displayed as "waypoints" in the matched DirectionsRoute. When I request a route with these two coordinates specified as waypoints I do not receive a match. However, when I do not specify waypoints in my request I receive an accurate DirectionsRoute response.   

Builder with waypoints specified(no matched route):

 MapboxMapMatching.builder()
                .coordinates(coordinateList)
                .steps(true)
                .waypoints(0, coordinateList.size()-1)
                .accessToken(MAPBOX_ACCESS_TOKEN)
                .voiceInstructions(true)
                .bannerInstructions(true)
                .profile(DirectionsCriteria.PROFILE_WALKING)
                .build()

Builder with no waypoints specified(correct matched directions route):

 MapboxMapMatching.builder()
                .coordinates(coordinateList)
                .steps(true)
                .accessToken(MAPBOX_ACCESS_TOKEN)
                .voiceInstructions(true)
                .bannerInstructions(true)
                .profile(DirectionsCriteria.PROFILE_WALKING)
                .build()

**Comment by danesfeder** [comment]
Thanks for bringing this to us @jackhd1 - I'm going to move this issue to https://github.com/mapbox/mapbox-java, as it seems to be an issue with the map matching API.  Please see https://github.com/mapbox/mapbox-java/issues/849

cc @osana
