### ISSUE TITLE
New nullReferenceException in checkForArrivalEvent

### ISSUE THREAD

**Issue by richjhart** [mapbox/mapbox-navigation-android#1086]
**Android API:**N/A
**Mapbox Navigation SDK version:** 0.15.0

```
Fatal Exception: java.lang.NullPointerException
Attempt to invoke interface method 'void com.mapbox.services.android.navigation.v5.navigation.b.c.b(com.mapbox.services.android.navigation.v5.f.i)' on a null object reference
com.mapbox.services.android.navigation.v5.navigation.NavigationEventDispatcher.checkForArrivalEvent (NavigationEventDispatcher.java:177)
com.mapbox.services.android.navigation.v5.navigation.NavigationEventDispatcher.onMilestoneEvent (NavigationEventDispatcher.java:135)
com.mapbox.services.android.navigation.v5.navigation.NavigationService.onMilestoneTrigger (NavigationService.java:125)
com.mapbox.services.android.navigation.v5.navigation.NavigationEngine$1.run (NavigationEngine.java:93)
```

#1022 added a number of null checks for metricEventListener, but removed the null check from checkForArrivalEvent(). I guess there's an assumption that "isArrivalEvent" should only be true once - apparently that's not always true.

**Comment by danesfeder** [comment]
Hey @richjhart, another good catch here - being working in https://github.com/mapbox/mapbox-navigation-android/pull/1070.  Will close when the PR lands - thank you for reporting!

**Comment by richjhart** [comment]
Ah yeah, I had a look for a previous report but missed #1070.
