### ISSUE TITLE
Time remaining in SummaryBottomSheet is always in English

### ISSUE THREAD

**Issue by cmahopper** [mapbox/mapbox-navigation-android#1097]
**Android API:** 27
**Mapbox Navigation SDK version:** 0.16.0-beta.1

Time remaining is not localized, it seems. It is always "X day(s) Y hr Z min" no matter what language is set on the device. This seems to be hardcoded in [TimeUtils.java](https://github.com/mapbox/mapbox-navigation-android/blob/master/libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/utils/time/TimeUtils.java#L23).

Maybe I've misunderstood something.

**Comment by danesfeder** [comment]
Hey @cmahopper 👋 you're correct here - these `String`s need to be extracted into our resources and then uploaded to Transifex for translation via contributors.  Thanks for pointing this out!

**Comment by danesfeder** [comment]
@P-Zenker there's another method in `TimeFormatter` that should help > https://github.com/mapbox/mapbox-navigation-android/blob/master/libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/utils/time/TimeFormatter.java#L25-L30

Example usage: https://github.com/mapbox/mapbox-navigation-android/blob/master/libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/summary/SummaryModel.java#L29-L31

**Comment by P-Zenker** [comment]
Well, I don't want the arrival time. I want the time remaining, like you can see in the screenshot

![2018-09-04 19 39 21](https://user-images.githubusercontent.com/23097192/45047762-3ff01f00-b07a-11e8-8ae5-763ab043749d.jpg)

But as you can see the time format is english and not german (5 Std., 12 Min.). On the other hand distance and arrivial time are correct.

**Comment by danesfeder** [comment]
Ah I see now sorry about that @P-Zenker - we source those strings from `Transifex` https://www.transifex.com/mapbox/mapbox-navigation-sdk-for-android/ and it doesn't look like they have been translated for German just yet.  Please feel free to contribute those translations and we will update them in the SDK!

**Comment by P-Zenker** [comment]
No problem - thanks. Translations done ;)

**Comment by danesfeder** [comment]
@P-Zenker awesome thanks, I'll tag you in the PR that updates them
