### ISSUE TITLE
Navigation notification is only in 12-hour format

### ISSUE THREAD

**Issue by cmahopper** [mapbox/mapbox-navigation-android#1098]
**Android API:** 27
**Mapbox Navigation SDK version:** 0.16.0-beta.1

The arrival time in the MapboxNavigationNotification is always in 12-hour format. I would expect that it should also accept 24-hour format. This happens in [TimeUtils.java](https://github.com/mapbox/mapbox-navigation-android/blob/master/libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/utils/time/TimeUtils.java#L22).

**Comment by danesfeder** [comment]
Hey @cmahopper 👋 yeah you're correct here as well - this is something we are actively working.  If it helps, in the meantime, you can implement your own custom notification and provide it to the SDK https://www.mapbox.com/android-docs/navigation/overview/navigation-options/#creating-a-custom-notification

**Comment by chrisalbinus** [comment]
@danesfeder Ah, good call, I'm glad that's an option!
