### ISSUE TITLE
Question: Consuming milestones

### ISSUE THREAD

**Issue by richjhart** [mapbox/mapbox-navigation-android#1099]
We have some instances where we don't want to quit navigation, but want to temporarily stop voice and banner milestones from being handled (routeprogress, etc, still need to work).

https://www.mapbox.com/android-docs/navigation/overview/milestones/ states "You can use your text-to-speech engine of choice and have it consume the instruction."

However, I don't see that this would actually "consume" the instruction - as NavigationViewModel.milestoneEventListener will still fire.

Is there a way to truly consume the event to prevent any other engine from playing the instruction, and updating the banner?

**Comment by danesfeder** [comment]
Hey @richjhart, you're right, this is a good point - with the `NavigationView` there is currently no way `to temporarily stop voice and banner milestones from being handled`.  

You can initialize the view with the milestones disabled via `MapboxNavigationOptions#defaultMilestonesEnabled(false)` passed to `NavigationViewOptions`.  But this would disable our Directions API instructions altogether.  

Seeing as how the only two options here are essentially on or off, I think it makes sense to expose a listener that would fire when we are about to voice an announcement or display banner instructions.  You'd look at the instruction and your given progress if needed and then return a modified version (in your case maybe `""` or `null`) and we'd use this instead.  See here https://github.com/mapbox/mapbox-navigation-android/issues/1074#issuecomment-403540646.

Would that sound okay?

**Comment by richjhart** [comment]
Hi @danesfeder yeah that sounds like the best way of doing it. Happy to close this if it's better to track in #1047

**Comment by danesfeder** [comment]
@richjhart yeah that would be great, thank you.  Also noting, this work started moving last week in #1107
