### ISSUE TITLE
Request: Be able to remove feedback related UI

### ISSUE THREAD

**Issue by cmahopper** [mapbox/mapbox-navigation-android#1100]
I would like to be able to remove any UI related to the feedback stuff. That includes the Feedback fab and the AlertView in order to prevent the feedbackBottomSheet from ever being shown.

Is this something that is possible now, without copying over a bunch of the sdk classes? Otherwise I would like to request it.

**Comment by Guardiola31337** [comment]
Hey @cmahopper 👋 Thanks for your question.

This is being tracked in #634

Closing here as duplicate.

Let us know if you have any other feature requests or if you find any bugs.
