### ISSUE TITLE
Camera doesn't center properly after expanding

### ISSUE THREAD

**Issue by Guardiola31337** [mapbox/mapbox-navigation-android#1103]
Refs.: https://github.com/mapbox/mapbox-navigation-android/pull/1092#issuecomment-403090661
- Noticed that the camera doesn't center properly after expanding when running the [`DualNavigationMapActivity`](https://github.com/mapbox/mapbox-navigation-android/blob/master/app/src/main/java/com/mapbox/services/android/navigation/testapp/activity/navigationui/DualNavigationMapActivity.java) example from the test app 👀

![camera_not_centered](https://user-images.githubusercontent.com/1668582/42391084-719c21bc-814e-11e8-8a35-ef5c1aa79b4b.png)

**Comment by danesfeder** [comment]
The map padding for `NavigationView` can now be adjusted with the API #1473, I don't think we should look into "automatically" adjusting this based on the height of the `View` as this could introduce unexpected behavior.  

If the developer wants to do something like shrink / expand the view, they can now do it themselves with the new API.
