### ISSUE TITLE
Sound and feedback buttons don't scale

### ISSUE THREAD

**Issue by Guardiola31337** [mapbox/mapbox-navigation-android#1104]
Refs.: https://github.com/mapbox/mapbox-navigation-android/pull/1092#issuecomment-403091142
- Noticed that the sound and feedback buttons don't scale when running the [`DualNavigationMapActivity`](https://github.com/mapbox/mapbox-navigation-android/blob/master/app/src/main/java/com/mapbox/services/android/navigation/testapp/activity/navigationui/DualNavigationMapActivity.java) example from the test app 👀

![feedback_and_sound_buttons](https://user-images.githubusercontent.com/1668582/42391125-a08e880c-814e-11e8-86d9-12d390d2a4b4.png)

**Comment by Guardiola31337** [comment]
@abhishek1508 is this still an issue in the 1.0 UI SDK?

I believe so, so the question here would be, is this something we want to prioritize?

cc @JunDai

**Comment by abhishek1508** [comment]
Let's verify
cc @JunDai @cafesilencio @langsmith

**Comment by abhishek1508** [comment]
@Guardiola31337 I am closing this as this more than a year old. We have removed legacy code and are not supporting `DualNavigationActivity` anymore. Please open a new issue if you still find it in the soon to be available version `1.0`
