### ISSUE TITLE
can mapbox direction api make query of route at a given historical time period? 

### ISSUE THREAD

**Issue by wzy221** [mapbox/mapbox-navigation-android#1105]
Hi, I just use the mapbox direction api to make a query of the route. However,i am not clear whether it is possible to make query of a route at a given historical period. For example, will the result differ in the morning or in the midnight?

I searched the mapbox api direction documentaion. however, i can not find detailed explanation of driving-traffic. is it possible to set up the historical time period for the query?

This API supports four different routing profiles:
mapbox/driving-traffic for automotive routing. This profile factors in current and historic traffic conditions to avoid slowdowns. Traffic is available in these supported geographies. 
Otherwise, if it is necessary, can the pricing strategy support such application? I am currently a Ph.D student in university, and i am use the free version mapbox now. just want to know if it is possible for the comerical version for such usage?

**Comment by danesfeder** [comment]
Hey @wzy221, we do not offer the ability to call the directions API based on a point in past time if I'm understanding your question correctly.  The API only supports getting directions based on _current_ traffic conditions.  Sorry we couldn't help you out with this! 

cc @coxchapman if I'm mistaken here

**Comment by wzy221** [comment]
hi, I think you get my idea. I originally want to see if it is possible to get directions based on historical traffic conditions. 
thanks for the reply~
