### ISSUE TITLE
Further zoom out enabled

### ISSUE THREAD

**Issue by alisonZhangthu** [mapbox/mapbox-navigation-android#1110]
**Android API:** 19+
**Mapbox Navigation SDK version:** 6.2.1

Currently cameraZoom must be a float >= 0.0. However, the world map is not small enough for my use case. It'd be nice if user could further zoom out from the map. 

If anyone knows a way of achieving the same goal, your help is appreciated!

**Comment by danesfeder** [comment]
Hey @alisonZhangthu 👋 thanks for the feedback here.  Unfortunately, our [Maps SDK](https://www.mapbox.com/android-docs/maps/overview/) doesn't support this request and this ticket is not workable in the Navigation SDK repository.  Going to go ahead and close this, but feel free to open tickets here regarding navigation-related feature requests / bugs in the future.  Thanks!
