### ISSUE TITLE
Speedometer and Speed Limit Feature

### ISSUE THREAD

**Issue by Alibmn** [mapbox/mapbox-navigation-android#1111]
Are you guys planning to develop a feature to show speed and get an alert when they pass  speedometer and speed limit in driving mode?

Below we have designed some concepts.
![image](https://user-images.githubusercontent.com/41232488/42725818-9678e72a-879f-11e8-81c5-a8a067b26097.png)

In case we develop such a feature would you be willing to merge it to the SDK?

**Comment by akitchen** [comment]
Hi @Alibmn - thank you for inquiring! Yes, this is a feature we've been discussing and yes it is in the pipeline, however we do not have a time estimate at the moment.

We would absolutely welcome a pull request to help enable such a feature, however it would need to "degrade gracefully" when in areas/locales where data is not available, or if an app developer has not integrated their own data source for speed limits. It is also possible that we would need to rework it a bit to make it work in a general way with our default drop-in UI before we could include it in an official release.

**Comment by Alibmn** [comment]
> however it would need to "degrade gracefully" when in areas/locales where data is not available, or if an app developer has not integrated their own data source for speed limits.

No Problem!

>  It is also possible that we would need to rework it a bit to make it work in a general way with our default drop-in UI before we could include it in an official release.

From perspective of UI and codes, what would be your set of constraints limitations so that we start from that point and consider them while working on developing it?

**Comment by akitchen** [comment]
> From perspective of UI and codes, what would be your set of constraints limitations so that we start from that point and consider them while working on developing it?

I was mostly thinking that this is something which may need to show & hide optionally based on the availability of data, as you might imagine. 

We're looking forward to see what you're building; please let us know if you have other questions or feedback!
