### ISSUE TITLE
GPS Not Enabling + Not finding Location

### ISSUE THREAD

**Issue by jethro-2018** [mapbox/mapbox-navigation-android#1121]
I have since updated our project to the latest version of the SDK, 0.15 and maps sdk to the latest versions. I have now run into the issue that my GPS is not being enabled anymore since the update, which was working fine before the update. I'm not sure if i am maybe missing something now or the docs have excluded something.

`import com.mapbox.mapboxsdk.plugins.locationlayer.LocationLayerPlugin;
 import com.mapbox.android.core.location.LocationEngine;
 import com.mapbox.mapboxsdk.plugins.locationlayer.LocationLayerPlugin;
 import com.mapbox.android.core.location.LocationEngineListener;
 import com.mapbox.android.core.location.LocationEnginePriority;
 import com.mapbox.android.core.location.LocationEngineProvider;
 import com.mapbox.android.core.permissions.PermissionsListener;
 import com.mapbox.android.core.permissions.PermissionsManager;

     public class MainActivity extends AppCompatActivity
        implements NavigationView.OnNavigationItemSelectedListener, LocationEngineListener, PermissionsListener {

    public static LocationEngine locationEngine;
    private LocationLayerPlugin locationPlugin;
    Location lastLocation;
    private PermissionsManager permissionsManager;

        @Override
    protected void onCreate(Bundle savedInstanceState) {
      enableLocationPlugin();
   }

            @SuppressWarnings({"MissingPermission"})
    private void enableLocationPlugin() {

        Log.e("LOC", "ENABLE");

        // Check if permissions are enabled and if not request
        if (PermissionsManager.areLocationPermissionsGranted(this)) {
            // Create an instance of LOST location engine

            initializeLocationEngine();

        } else {

            permissionsManager = new PermissionsManager(this);
            permissionsManager.requestLocationPermissions(this);
        }
    }

    @SuppressLint("MissingPermission")
    private void initializeLocationEngine() {
        LocationEngineProvider locationEngineProvider = new LocationEngineProvider(this);
        locationEngine = locationEngineProvider.obtainBestLocationEngineAvailable();
        locationEngine.setPriority(LocationEnginePriority.HIGH_ACCURACY);

        Location lastLocation = locationEngine.getLastLocation();
        if (lastLocation != null && lastLocation.getLongitude() != 0 && lastLocation.getLatitude() != 0) {
            originLocation = lastLocation;
            setCameraPosition(lastLocation);
        } else {
            locationEngine.addLocationEngineListener(this);
            locationEngine.activate();
            Log.e("LOCATION", "NULL LOCATION");
        }
    }

    @Override
    public void onRequestPermissionsResult(int requestCode, @NonNull String[] permissions, @NonNull int[] grantResults) {
        permissionsManager.onRequestPermissionsResult(requestCode, permissions, grantResults);
    }

    public void onExplanationNeeded(List<String> permissionsToExplain) {

    }

    @Override
    public void onPermissionResult(boolean granted) {
        if (granted) {
            enableLocationPlugin();
        } else {
            finish();
        }
    }

    @Override
    public void onConnected() {

        if (locationEngine != null) {
            locationEngine.requestLocationUpdates();
                lastLocation = locationEngine.getLastLocation()
    }

`

I noticed in the onConnected() method it is now saying it now requires permission which may be rejected by the user on both the requestLocationUpdates and getLastLocation(). This was never underlined previously.

My lastLocation is always coming back as null since the update and the gps doesn't seem to get enabled. What have i missed?

I added only the necessary code as an example.

**Comment by wbearand** [comment]
@jethro-2018 : I think I had a similar issue... ah I just searched for it and saw that you also found it:
[Current Location Cannot be found,shows wrong location near Nigeria. #158](https://github.com/mapbox/mapbox-events-android/issues/158)

It seems to me that we all follow some old samples which don't work anymore.

I think on onCreate, just calling enableLocationPlugin does not work. I had to call it in onMapReady().

```
public MapView getView() {
        return navigationView.getRootView() instanceof MapView ? (MapView) navigationView.getRootView() : null;
    }
```

and then later (I think it also works in onCreate):

```
if (getView() != null) {
            getView().getMapAsync(new OnMapReadyCallback() {
                @Override
                public void onMapReady(MapboxMap mapboxMap) {
                    Timber.d("onCreate - onMapReady");
                    enableLocationPlugin();
                }
            });
        } else {
            Timber.w("onCreate - getView() is null");
        }
```

The dialog asking for the permission is shown, and location worked for me afterwards.

**Comment by jethro-2018** [comment]
Full code which sits in my onCreate method:

`        mapView.getMapAsync(new OnMapReadyCallback() {
            @Override
            public void onMapReady(final MapboxMap mapboxMap) {
                map = mapboxMap;

                enableLocationPlugin();
                originCoord = new LatLng(originLocation.getLatitude(), originLocation.getLongitude());
                originPosition = Point.fromLngLat(originCoord.getLongitude(), originCoord.getLatitude());

                oLat = originCoord.getLatitude();
                oLon = originCoord.getLongitude();

                if (destinationMarker != null) {
                    mapboxMap.removeMarker(destinationMarker);
                }

                destinationCoord = new LatLng(dlon, dlat);

                Log.e("destinationCoord", destinationCoord.toString());

                destinationMarker = mapboxMap.addMarker(new MarkerOptions()
                        .position(destinationCoord)
                );

                destinationPosition = Point.fromLngLat(dlon, dlat);

                getRoute(originPosition, destinationPosition);
            }
        });`

So i'm also enabling it in my onMapReady method like you and its still not working, this is quite a frustrating issue :/

**Comment by jethro-2018** [comment]
Interestingly enough i downloaded the mapbox demo app and on a few different devices, the user location example doesnt work.

@danesfeder @Guardiola31337

**Comment by danesfeder** [comment]
@jethro-2018 @wbearand we are looking into this, thank you for the context / updates.  It looks to be related to upstream location services dependency updates.  Will follow up here once we get to the bottom of it.

**Comment by jethro-2018** [comment]
Thanks @danesfeder, side note i experienced this in 0.14 too.

**Comment by danesfeder** [comment]
@jethro-2018 when you are testing this, are you in a building?

**Comment by jethro-2018** [comment]
Not all the time, it happens outside too.

No I'm currently not including the Google play services but I will try that. Looking forward to the update, eta of when it will be released? @Guardiola31337

**Comment by danesfeder** [comment]
@jethro-2018 we are looking to release a patch hopefully this week

**Comment by danesfeder** [comment]
@jethro-2018 `LocationLayerPlugin` `0.7.1` has been released - can you confirm this solves your issue?  Thanks!

https://github.com/mapbox/mapbox-plugins-android/releases/tag/v0.7.1

**Comment by jethro-2018** [comment]
I will test this tomorrow and let you know, thanks

**Comment by jethro-2018** [comment]
@danesfeder my issue has been fixed. Thank you!

**Comment by jethro-2018** [comment]
It seemed to work once but then reverted back to the same issue with no other code changes.

`    implementation 'com.mapbox.mapboxsdk:mapbox-android-plugin-locationlayer:0.7.1'
    implementation('com.mapbox.mapboxsdk:mapbox-android-sdk:6.3.0@aar') {
        transitive = true
    }
    implementation 'com.mapbox.mapboxsdk:mapbox-android-navigation:0.16.0'
    implementation('com.mapbox.mapboxsdk:mapbox-android-navigation-ui:0.16.0') {
        transitive = true
    }`

**Comment by jethro-2018** [comment]
![screenshot_20180731-135601](https://user-images.githubusercontent.com/6702147/43458252-d7212cce-94c9-11e8-9417-975db421e86c.png)
![screenshot_20180731-135745](https://user-images.githubusercontent.com/6702147/43458258-dc39a74a-94c9-11e8-8e46-59e22e9beff3.jpg)

**Comment by jethro-2018** [comment]
It only works on Huawei if i add:

`implementation 'com.google.android.gms:play-services-location:15.0.1'`

However will i still be able to get all of the regular navigation functionality working with that? As previously navigation didn't work when i added that.

**Comment by jethro-2018** [comment]
Switching from High Accuracy to Balanced_Power_Accuracy fixed it for Huawei devices. 

`    private void initializeLocationEngine() {
        LocationEngineProvider locationEngineProvider = new LocationEngineProvider(this);
        locationEngine = locationEngineProvider.obtainBestLocationEngineAvailable();
        locationEngine.setPriority(LocationEnginePriority.BALANCED_POWER_ACCURACY);
        locationEngine.activate();

        Location lastLocation = locationEngine.getLastLocation();
        if (lastLocation != null) {
            originLocation = lastLocation;
            setCameraPosition(lastLocation);
            Log.e("LAST LOCATION", lastLocation.toString());
        } else {
            locationEngine.addLocationEngineListener(this);
            Log.e("Add Listener", "Location Null");
        }
    }`

**Comment by danesfeder** [comment]
@jethro-2018 so it seems to be an issue with the location request parameters?

**Comment by jethro-2018** [comment]
Seems so, it also doesn't seem to be a very reliable fix.

**Comment by Guardiola31337** [comment]
@jethro-2018 
> No I'm currently not including the Google play services but I will try that.

> It seems to work fine on Nokia, however it isn't working on Huawei P8 Lite or Huawei P Smart. Can't seem to track down what the problem is, the location is reported as null every time.

We're tracking that issue in https://github.com/mapbox/mapbox-events-android/issues/187 - which seems a device specific issue (based on your findings) when using the Android APIs (`AndroidLocationEngine`).

Could you confirm that if you're not stale this is not a problem in those devices? Also, have you had the chance to test including Google Play Services (`GoogleLocationEngine`)?

Thanks!

**Comment by jethro-2018** [comment]
I have tested with GoogleLocationEngine and it does seem to work much better!

**Comment by Guardiola31337** [comment]
Hey 👋 @jethro-2018 
> I have tested with GoogleLocationEngine and it does work more accurately

Awesome, glad to hear!

> is there an example activity showing the GoogleLocationEngine implementation with Mapbox that i could use for now?

What do you mean? If you include the dependency, `GoogleLocationEngine` is used by default, you don't normally need to do anything else. It's all managed by the SDK behind the scenes. In any case, you can 👀 further information on how to use the APIs in https://github.com/mapbox/mapbox-java/pull/502#issuecomment-332457176 Noting that we no longer support [`LOST`](https://github.com/lostzen/lost) due to a lack of support on their end.

> Could you confirm that if you're not stale this is not a problem in those devices?

Could you test ☝️? When I say stale, I mean moving and getting more than one location update (e.g. going on a test drive). That'd help us on finding the root cause of https://github.com/mapbox/mapbox-events-android/issues/187 (from our tests is only a problem for the first location fix).

Thanks again 🙏

**Comment by jethro-2018** [comment]
Great thanks for the link.

> Could you test ☝️? When I say stale, I mean moving and getting more than one location update (e.g. going on a test drive). That'd help us on finding the root cause of mapbox/mapbox-events-android#187 (from our tests is only a problem for the first location fix).

I will test that over the weekend and get back to you!

**Comment by Guardiola31337** [comment]
> I will test that over the weekend and get back to you!

Awesome! Thanks @jethro-2018

**Comment by jethro-2018** [comment]
Sorry for the delay @Guardiola31337, i haven't had chance to test this yet again but it is on my agenda!

**Comment by Guardiola31337** [comment]
Awesome! Thanks for the update @jethro-2018 🙏

**Comment by danesfeder** [comment]
@jethro-2018 any updates here?

**Comment by jethro-2018** [comment]
We are in the process of rebuilding our app with the updated SDK, so i should have feedback in the next week or two. Sorry for the delay in my reply @danesfeder

**Comment by Guardiola31337** [comment]
Nice @jethro-2018 Looking forward to it. Thanks again!

**Comment by jethro-2018** [comment]
I have tested the new SDK's and the issue seems to be resolved on most Huawei devices apart from my device the P Smart, however i'm not sure if this is a device issue because the GPS works in every other GPS application without an issue. The above mentioned fixes that i used for testing are not needed anymore, however when using Google Location Engine on my P Smart it doesn't see the location as null but it doesn't return a location. It jumps to the below method successfully:

 `locationEngine.addLocationEngineListener(this);`

**Comment by jethro-2018** [comment]
I have since switched out the location engine logic for the new location component and it does not return a location, because it sees the location as null it stops the map from rendering.

![mapactivity-error](https://user-images.githubusercontent.com/6702147/48613803-634a1b00-e995-11e8-8322-d470c7c6396b.png)

**Comment by EverSinceWWI** [comment]
> 
> 
> I have since switched out the location engine logic for the new location component and it does not return a location, because it sees the location as null it stops the map from rendering. It breaks on the originCoord line in onMapReady();
> 
> ![mapactivity-error](https://user-images.githubusercontent.com/6702147/48613803-634a1b00-e995-11e8-8322-d470c7c6396b.png)
> 
> ` @override
> protected void onCreate(Bundle savedInstanceState) {
> super.onCreate(savedInstanceState);
> setContentView(R.layout.activity_map);
> 
> ```
>     mapView = findViewById(R.id.mapView);
>     mapView.onCreate(savedInstanceState);
>     mapView.getMapAsync(this);
> }
> 
> @Override
> public void onMapReady(MapboxMap mapboxMap) {
> 
>     this.mapboxMap = mapboxMap;
>     enableLocationComponent();
> 
>     originCoord = new LatLng(originLocation.getLatitude(), originLocation.getLongitude());
>     mapboxMap.addOnMapClickListener(this);
> 
>     button = findViewById(R.id.startButton);
>     button.setOnClickListener(new View.OnClickListener() {
>         public void onClick(View v) {
> 
>             Intent mIntent = new Intent(MapActivity.this, NavigationActivity.class);
>             startActivity(mIntent);
>         }
>     });
> }
> 
> @Override
> public void onMapClick(@NonNull LatLng point) {
>     if (destinationMarker != null) {
>         mapboxMap.removeMarker(destinationMarker);
>     }
>     destinationCoord = point;
>     destinationMarker = mapboxMap.addMarker(new MarkerOptions()
>             .position(destinationCoord)
>     );
> 
>     destinationPosition = Point.fromLngLat(destinationCoord.getLongitude(), destinationCoord.getLatitude());
>     originPosition = Point.fromLngLat(originCoord.getLongitude(), originCoord.getLatitude());
>     getRoute(originPosition, destinationPosition);
>     button.setEnabled(true);
>     button.setBackgroundResource(R.color.mapboxBlue);
> }
> 
> @SuppressWarnings( {"MissingPermission"})
> private void enableLocationComponent() {
>     // Check if permissions are enabled and if not request
>     if (PermissionsManager.areLocationPermissionsGranted(this)) {
>         // Activate the MapboxMap LocationComponent to show user location
>         // Adding in LocationComponentOptions is also an optional parameter
>         LocationComponent locationComponent = mapboxMap.getLocationComponent();
>         locationComponent.activateLocationComponent(this);
>         locationComponent.setLocationComponentEnabled(true);
>         // Set the component's camera mode
>         locationComponent.setCameraMode(CameraMode.TRACKING_GPS);
>         originLocation = locationComponent.getLastKnownLocation();
> 
>         if (originLocation != null) {
>             originLocation = locationComponent.getLastKnownLocation();
>         } 
> 
>     } else {
>         permissionsManager = new PermissionsManager(this);
>         permissionsManager.requestLocationPermissions(this);
>     }
> }`
> ```

same problem as yours...it breaks exactly at originCoord...does anyone have a solution to that?

**Comment by jethro-2018** [comment]
Still facing the same issue here @EverSinceWWI, no resolution on my side.

**Comment by danesfeder** [comment]
@EverSinceWWI @jethro-2018 `LocationComponent#getLastKnownLocation()` is `nullable` - if you're testing this indoors or with areas of bad GPS, there is a greater chance it will return `null`.  

Noting that there are some location service updates coming from our upstream `core-location` library, which may help here.

**Comment by billyking991** [comment]
I've created a hybrid implementation that uses both LocationComponent to show the dot on the map and the LocationEngine to get the originLocation/originPosition.  It isn't ideal, but it seems to work in the short term.  The one thing that doesn't seem to be working properly is the getLastKnownLocation function, even though the map focuses on my current location after initializing LocationComponent.

**Comment by jethro-2018** [comment]
@billyking991 do you mind sharing how you achieved that?

**Comment by billyking991** [comment]
Keep everything else from the sample project the same, but change enableLocationComonent and retain initializeLocationEngine from SDK 0.19.  It's a mess, but here is how I did it:

@SuppressWarnings( {"MissingPermission"})
    private void enableLocationComponent() {
        if (PermissionsManager.areLocationPermissionsGranted(this)) {
            // Activate the MapboxMap LocationComponent to show user location
            // Adding in LocationComponentOptions is also an optional parameter
            LocationComponent locationComponent = mapboxMap.getLocationComponent();
            locationComponent.activateLocationComponent(this);
            locationComponent.setLocationComponentEnabled(true);
            // Set the component's camera mode
            locationComponent.setCameraMode(CameraMode.TRACKING);
            // Always null
            //originLocation = locationComponent.getLastKnownLocation();

            // Create an instance of LOST location engine
            initializeLocationEngine();

            Location lastLocation = locationEngine.getLastLocation();

            if (lastLocation != null) {
                originLocation = lastLocation;
                setCameraPosition(lastLocation);
                //locationEngine.removeLocationEngineListener(MainActivity.this);
                //Point originPoint = Point.fromLngLat(originLocation.getLongitude(), originLocation.getLatitude());

                Map<String,String> currentLocation = new HashMap<>();
                currentLocation.put("lat", Double.toString(originLocation.getLatitude()));
                currentLocation.put("long", Double.toString(originLocation.getLongitude()));

                Gson gson = new Gson();
                String json = gson.toJson(currentLocation);

                SharedPreferences.Editor editor = preferences.edit();
                editor.putString("currentLocation", json);
                editor.apply();
            }
        } else {
            permissionsManager = new PermissionsManager(this);
            permissionsManager.requestLocationPermissions(this);
        }
    }

@SuppressWarnings( {"MissingPermission"})
    private void initializeLocationEngine() {
        locationEngine = new LocationEngineProvider(this).obtainBestLocationEngineAvailable();
        locationEngine.setPriority(LocationEnginePriority.HIGH_ACCURACY);
        locationEngine.activate();
        locationEngine.addLocationEngineListener(new LocationEngineListener() {
            @Override
            public void onConnected() {
                locationEngine.requestLocationUpdates();
            }

            @Override
            public void onLocationChanged(Location location) {
                originLocation = location;
                if (!mCameraPositionSet) {
                    setCameraPosition(location);
                    mCameraPositionSet = true;
                }
                //locationEngine.removeLocationEngineListener(this);

                originCoord = new LatLng(originLocation.getLatitude(), originLocation.getLongitude());

                Map<String,String> currentLocation = new HashMap<>();
                currentLocation.put("lat", Double.toString(originLocation.getLatitude()));
                currentLocation.put("long", Double.toString(originLocation.getLongitude()));

                Gson gson = new Gson();
                String json = gson.toJson(currentLocation);

                SharedPreferences.Editor editor = preferences.edit();
                editor.putString("currentLocation", json);
                editor.apply();
            }
        });
    }

    private void setCameraPosition(Location location) {
        mapboxMap.animateCamera(CameraUpdateFactory.newLatLngZoom(
                new LatLng(location.getLatitude(), location.getLongitude()), 12));
    }

If you need more detail, just let me know.  I'm testing now.  I can't promise it works 100% of the time, but my initial tests look good.  I'm able to use SDK 0.23.

**Comment by jethro-2018** [comment]
Can confirm that is retrieving a location for me too!

**Comment by danesfeder** [comment]
I'd recommend adding the listener before activating to prevent a race condition:

```
private void initializeLocationEngine() {
    locationEngine = new LocationEngineProvider(this).obtainBestLocationEngineAvailable();
    locationEngine.setPriority(LocationEnginePriority.HIGH_ACCURACY);
    locationEngine.addLocationEngineListener(new LocationEngineListener() {
        @override
        public void onConnected() {
            locationEngine.requestLocationUpdates();
        }
    ...
    locationEngine.activate();
}
```

**Comment by billyking991** [comment]
Good catch.  I've updated my code and am testing it today.  Thank you for the help!

**Comment by jethro-2018** [comment]
`I've created a hybrid implementation that uses both LocationComponent to show the dot on the map..`

What did you do to achieve this? My initial tests with this are proving to be semi-reliable, it doesn't always return a location but its definitely progress.

**Comment by danesfeder** [comment]
This may also help until our services are updated https://github.com/mapbox/mapbox-navigation-android/issues/1469#issuecomment-442450591

**Comment by jethro-2018** [comment]
Thanks @danesfeder !

**Comment by jethro-2018** [comment]
Has there been any progress on when this fix may be pushed?

**Comment by danesfeder** [comment]
@jethro-2018 moving in #1615
