### ISSUE TITLE
ui.v5.route.NavigationMapRoute.onProgressChange(NavigationMapRoute.java:1009)outofbounds

### ISSUE THREAD

**Issue by mingxin-yang** [mapbox/mapbox-navigation-android#1129]
**Android API:**21
**Mapbox Navigation SDK version:**com.mapbox.mapboxsdk:mapbox-android-navigation-ui:0.15.0

### Steps to trigger behavior
 1.When I use version 0.13.0, there is no problem, I can navigate normally, but after updating to version 0.15.0, the following error will be reported.
 2.
`                    if (response.body().routes().size() > 0) {
                        route = response.body().routes().get(0);
                        if (destLoation != null) {
                            mapboxMap.removeAnnotation(destLoation);
                        }
                        destLoation = mapboxMap.addMarker(new MarkerOptions()
                                .position(point)
                                .icon(IconFactory.getInstance(activity)
                                        .fromResource(R.drawable.ic_location_point)));
                        if (isNav) {
                            if (locationEngine != null) {
                                locationEngine.deactivate();
                            }
                            mapRoute.addRoute(route);
                            routes.addAll(response.body().routes());
                            mapboxMap.removeAnnotations(markers);
                            startNavigation();
                        } else if (route.distance() != null &&
                                route.distance() > 25d) {
                            mapRoute.addRoutes(response.body().routes());
                            routes.addAll(response.body().routes());
                            boundCameraToRoute();
                            activity.addMapBoxRouteListFragment();
                            reSizeMap(240);
                            mapboxMap.removeAnnotations(markers);
                            trafficPlugin.setVisibility(false);
                        } else {
`
 3.
`            navigation.startNavigation(route);
            if (SharedPreferenceUtil.getAppSettingStr(activity,
                    AppConfig.SP_SETTING_LU, "1").equalsIgnoreCase("0")) {
                setMuted(false);
            } else {
                setMuted(true);
            }
            camera.start(route);
            isNav = true;
            activity.setNavi(isNav);
            trafficPlugin.setVisibility(false);
            currentRoad = "Start";
            mapRoute.removeRoute();
            mapRoute.addRoute(this.route);`

### Actual behavior

java.lang.IndexOutOfBoundsException: Invalid index 0, size is 0
	at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
	at java.util.ArrayList.get(ArrayList.java:308)
	at com.mapbox.services.android.navigation.ui.v5.route.NavigationMapRoute.onProgressChange(NavigationMapRoute.java:1009)
	at com.mapbox.services.android.navigation.v5.navigation.NavigationEventDispatcher.onProgressChange(NavigationEventDispatcher.java:144)
	at com.mapbox.services.android.navigation.v5.navigation.NavigationService.onNewRouteProgress(NavigationService.java:113)
	at com.mapbox.services.android.navigation.v5.navigation.NavigationEngine$1.run(NavigationEngine.java:92)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:145)
	at android.app.ActivityThread.main(ActivityThread.java:5938)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1400)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1195)

**Comment by Guardiola31337** [comment]
Hey @mingxin-yang 👋 thanks for reaching out and report your problem.

I guess this should be fixed now (https://github.com/mapbox/mapbox-navigation-android/pull/1093 landed a couple of weeks ago) and it'll be available in the next release. In the meantime, could you please retest this using `0.16.0-SNAPSHOT` and report back if it's still an issue?

Following you can find installation instructions for `SNAPSHOT`s:

```java
repositories {
    jcenter()
    maven { url "http://oss.sonatype.org/content/repositories/snapshots/" }
    // ...
}

dependencies {
    // ...
    implementation 'com.mapbox.mapboxsdk:mapbox-android-navigation-ui:0.16.0-SNAPSHOT'
    // ...
}
```

Thanks again.

Closing as answered.
