### ISSUE TITLE
InstructionList flashes half of the list

### ISSUE THREAD

**Issue by Guardiola31337** [mapbox/mapbox-navigation-android#1136]
Noticed that the list of instructions (accessible by clicking the top banner) flashes half of the list in certain scenarios 👀 

![instructions_list_flash](https://user-images.githubusercontent.com/1668582/43018454-ff9c84be-8c59-11e8-9c5a-02c89294e510.gif)

Could be related to the update to push data as soon as the list is shown
re: empty list on startup 👀 

cc @danesfeder

**Comment by Guardiola31337** [comment]
Noting that instructions are not removed after completed 👀

![instructions_list_flash](https://user-images.githubusercontent.com/1668582/43018454-ff9c84be-8c59-11e8-9c5a-02c89294e510.gif)

The instructions update logic is currently messed up.

👀 https://github.com/mapbox/mapbox-navigation-android/issues/1137

cc @danesfeder

**Comment by Guardiola31337** [comment]
@abhishek1508 is this still an issue in the `1.0` UI SDK?

**Comment by Guardiola31337** [comment]
> is this still an issue in the `1.0` UI SDK?

I believe it is 😬 So the question here would be, is this something we want to prioritize?

**Comment by abhishek1508** [comment]
Let's verify
cc @JunDai @cafesilencio @langsmith

**Comment by cafesilencio** [comment]
I was able to reproduce this once so far. It's not easy.  I also noticed that the text in the first item in the list is the same as the banner but the distance is different.  It looks a little strange.

![Screenshot_20200723-142402](https://user-images.githubusercontent.com/2249818/88340504-cbb3d880-ccf0-11ea-8ffd-9312a0b9c1f6.png)

**Comment by cafesilencio** [comment]
I was able to reproduce this more consistently with very little effort.

Using the NavigationViewFragment example replace the hard coded route with a longer route. Mine was about a 30 min. drive.  Let the navigation run for a couple minutes and occasionally  tap the top banner once. Sometimes a partial list will appear then disappear and a moment later the full list will appear.  Wait 30 seconds or so and repeat. The partial list doesn't show every time but often enough.

**Comment by JunDai** [comment]
thanks @cafesilencio , the reproduce steps is very useful.

**Comment by cafesilencio** [comment]
While under extreme conditions the issue might appear on some devices, the consensus is the issue is significantly improved and wouldn't likely appear under normal usage conditions.  The modifications were included in PR #3378.
