### ISSUE TITLE
DefaultInstructionEngine is unlocalizable

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-navigation-android#114]
#98 adds some hard-coded format strings such as `MILES_STRING_FORMAT` in `DefaultInstructionEngine`. These strings should be extracted into strings.xml so that translators can access them on [Transifex](https://www.transifex.com/mapbox/mapbox-navigation-sdk-for-android/). As it is, the user could hear [code-switching](https://en.wikipedia.org/wiki/Code-switching) involving [OSRM Text Instructions](https://www.transifex.com/project-osrm/osrm-text-instructions/), for example:

> Rẽ phải vào Quốc lộ 1A then in 3 miles đi vào bùng binh.

Moreover, this would be a good opportunity to ensure that the metric system is a first-class citizen in this library.

/ref #28
/cc @langsmith @danesfeder

**Comment by cammace** [comment]
duplicate ticket to https://github.com/mapbox/mapbox-navigation-android/issues/101, closing that one since this one provides more information. I recall the issue with placing the strings inside the `string.xml` was the lack of `Context` need to acquire the string from the resources. While we continue efforts towards making a clean instruction API (see https://github.com/mapbox/mapbox-navigation-android/issues/103) for developers, we will need to keep this in mind.

**Comment by davols** [comment]
Not sure about the best place to document this (another issue, PR, email?). The v5 text instructions in Swedish are somewhat incorrect, mostly found in terms of prepositions like on a tunnel instead of through/in a tunnel.

**Comment by 1ec5** [comment]
@davols, the localized instructions themselves are part of the [OSRM Text Instructions](https://github.com/Project-OSRM/osrm-text-instructions/) project. Please feel free to help maintain the Swedish translations [in Transifex](https://www.transifex.com/project-osrm/osrm-text-instructions/). If there are any systemic issues that require software changes, the cross-platform [osrm-text-instructions repository](https://github.com/Project-OSRM/osrm-text-instructions/) is a good place to report them.

That said, the Java port of OSRM Text Instructions that’s included in this project is considerably outdated: https://github.com/mapbox/mapbox-navigation-android/issues/82#issuecomment-314981391.

**Comment by danesfeder** [comment]
Closing - instructions are now provided by the directions API
