### ISSUE TITLE
Crash with SDK 6.3.0

### ISSUE THREAD

**Issue by vincent-caron** [mapbox/mapbox-navigation-android#1142]
**Android API: 26**
**Mapbox Navigation SDK version:**
  implementation 'com.mapbox.mapboxsdk:mapbox-android-sdk:6.3.0'
    implementation 'com.mapbox.mapboxsdk:mapbox-android-navigation:0.15.0'
    implementation('com.mapbox.mapboxsdk:mapbox-android-navigation-ui:0.15.0') {
        transitive = true
    }
### Steps to trigger behavior

 1. Uses this implementation
 2. launch
 3. try with ui and navigation 0.16.0 and 0.15.0
works fine with older version

### Expected behavior
No crash, the map appears
### Actual behavior
Crash : excerpt 
/AndroidRuntime: FATAL EXCEPTION: main
                  Process: com.bankl.xaronv.traceandrun, PID: 11034
                  java.lang.RuntimeException: Unable to get provider android.arch.lifecycle.ProcessLifecycleOwnerInitializer: java.lang.ClassNotFoundException: Didn't find class "android.arch.lifecycle.ProcessLifecycleOwnerInitializer" on path: DexPathList[[zip file "/data/app/com.bankl.xaronv.traceandrun-uJPV1Kuy5qNekp4rq9Yqdw==/base.apk", zip file "/data/app/com.bankl.xaronv.traceandrun-uJPV1Kuy5qNekp4rq9Yqdw==/split_lib_dependencies_apk.apk", zip file "/data/app/com.bankl.xaronv.traceandrun-uJPV1Kuy5qNekp4rq9Yqdw==/split_lib_resources_apk.apk", zip file "/data/app/com.bankl.xaronv.traceandrun-uJPV1Kuy5qNekp4rq9Yqdw==/split_lib_slice_0_apk.apk", zip file "/data/app/com.bankl.xaronv.traceandrun-uJPV1Kuy5qNekp4rq9Yqdw==/split_lib_slice_1_apk.apk", zip file "/data/app/com.bankl.xaronv.traceandrun-uJPV1Kuy5qNekp4rq9Yqdw==/split_lib_slice_2_apk.apk", zip file "/data/app/com.bankl.xaronv.traceandrun-uJPV1Kuy5qNekp4rq9Yqdw==/split_lib_slice_3_apk.apk", zip file "/data/app/com.bankl.xaronv.traceandrun-uJPV1Kuy5qNekp4rq9Yqdw==/split_lib_slice_4_apk.apk", zip file "/data/app/com.bankl.xaronv.traceandrun-uJPV1Kuy5qNekp4rq9Yqdw==/split_lib_slice_5_apk.apk", zip file "/data/app/com.bankl.xaronv.traceandrun-uJPV1Kuy5qNekp4rq9Yqdw==/split_lib_slice_6_apk.apk", zip file "/data/app/com.bankl.xaronv.traceandrun-uJPV1Kuy5qNekp4rq9Yqdw==/split_lib_slice_7_apk.apk", zip file "/data/app/com.bankl.xaronv.traceandrun-uJPV1Kuy5qNekp4rq9Yqdw==/split_lib_slice_8_apk.apk", zip file "/data/app/com.bankl.xaronv.traceandrun-uJPV1Kuy5qNekp4rq9Yqdw==/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/com.bankl.xaronv.traceandrun-uJPV1Kuy5qNekp4rq9Yqdw==/lib/arm64, /data/app/com.bankl.xaronv.traceandrun-uJPV1Kuy5qNekp4rq9Yqdw==/base.apk!/lib/arm64-v8a, /data/app/com.bankl.xaronv.traceandrun-uJPV1Kuy5qNekp4rq9Yqdw==/split_lib_dependencies_apk.apk!/lib/arm64-v8a, /data/app/com.bankl.xaronv.traceandrun-uJPV1Kuy5qNekp4rq9Yqdw==/split_lib_resources_apk.apk!/lib/arm64-v8a, /data/app/com.bankl.xaronv.traceandrun-uJPV1Kuy5qNekp4rq9Yqdw==/split_lib_slice_0_apk.apk!/lib/arm64-v8a, /data/app/com.bankl.xaronv.traceandrun-uJPV1Kuy5qNekp4rq9Yqdw==/split_lib_slice_1_apk.apk!/lib/arm64-v8a, /data/app/com.bankl.xaronv.traceandrun-uJPV1Kuy5qNekp4rq9Yqdw==/split_lib_slice_2_apk.apk!/lib/arm64-v8a, /data/app/com.bankl.xaronv.traceandrun-uJPV1Kuy5qNekp4rq9Yqdw==/split_lib_slice_3_apk.apk!/lib/arm64-v8a, /data/app/com.bankl.xaronv.traceandrun-uJPV1Kuy5qNekp4rq9Yqdw==/split_lib_slice_4_apk.apk!/lib/arm64-v8a, /data/app/com.bankl.xaronv.traceandrun-uJPV1Kuy5qNekp4rq9Yqdw==/split_lib_slice_5_apk.apk!/lib/arm64-v8a, /data/app/com.bankl.xaronv.traceandrun-uJPV1Kuy5qNekp4rq9Yqdw==/split_lib_slice_6_apk.apk!/lib/arm64-v8a, /data/app/com.bankl.xaronv.traceandrun-uJPV1Kuy5qNekp4rq9Yqdw==/split_lib_slice_7_apk.apk!/lib/arm64-v8a, /data/app/com.bankl.xaronv.traceandrun-uJPV1Kuy5qNekp4rq9Yqdw==/split_lib_slice_8_apk.apk!/lib/arm64-v8a, /data/app/com.bankl.xaronv.traceandrun-uJPV1Kuy5qNekp4rq9Yqdw==/split_lib_slice_9_apk.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64, /product/lib64]]
                      at android.app.ActivityThread.installProvider(ActivityThread.java:7110)

**Comment by danesfeder** [comment]
Hey @vincent-caron 👋 thanks for the feedback here - this looks like a dependency conflict.  Which app-compat version are you using?  Are you also bringing in `android.arch.lifecycle`?  Thanks!

**Comment by vincent-caron** [comment]
thanks for the answer but i do not understand what you mean :(
here my gradle file, if it's what you need  

apply plugin: 'com.android.application'

android {
    compileSdkVersion 27
    defaultConfig {
        applicationId "com.bankl.xaronv.traceandrun"
        minSdkVersion 24
        targetSdkVersion 27
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

repositories {
    mavenCentral()
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'com.android.support:appcompat-v7:27.1.1'
    implementation 'com.android.support:design:27.1.1'
    implementation 'com.android.support.constraint:constraint-layout:1.1.2'
    implementation 'com.android.support:support-v4:27.1.1'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.2'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'
    implementation 'com.mapbox.mapboxsdk:mapbox-android-sdk:6.2.0'
    implementation 'com.mapbox.mapboxsdk:mapbox-android-navigation:0.16.0-beta.1'
    implementation('com.mapbox.mapboxsdk:mapbox-android-navigation-ui:0.16.0-beta.1') {
        transitive = true
    }
    implementation 'com.squareup.retrofit2:retrofit:2.3.0'
    implementation 'com.squareup.retrofit2:converter-gson:2.3.0'
    implementation 'com.squareup.okhttp3:okhttp:3.10.0'
}

**Comment by danesfeder** [comment]
Have you looked at https://stackoverflow.com/questions/46304196/unable-to-get-provider-android-arch-lifecycle-lifecycleruntimetrojanprovider-ja?

Looks like it could possibly be an environment issue related to instant run / multi-dexing

**Comment by vincent-caron** [comment]
i've tried both solutions with no success, same crash on launch

**Comment by danesfeder** [comment]
Can you just try:
```
implementation 'com.mapbox.mapboxsdk:mapbox-android-navigation-ui:0.16.0'
```

The UI library brings in `mapbox-android-sdk` and `mapbox-android-navigation`, so no need to add those as well.

**Comment by vincent-caron** [comment]
already done that it crashes the same with ;
dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'com.android.support:appcompat-v7:27.1.1'
    implementation 'com.android.support:design:27.1.1'
    implementation 'com.android.support.constraint:constraint-layout:1.1.2'
    implementation 'com.android.support:support-v4:27.1.1'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.2'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'
    implementation 'com.mapbox.mapboxsdk:mapbox-android-sdk:6.3.0'
    implementation 'com.mapbox.mapboxsdk:mapbox-android-navigation:0.16.0'
    implementation('com.mapbox.mapboxsdk:mapbox-android-navigation-ui:0.16.0') {
        transitive = true
    }
    implementation 'com.squareup.retrofit2:retrofit:2.3.0'
    implementation 'com.squareup.retrofit2:converter-gson:2.3.0'
    implementation 'com.squareup.okhttp3:okhttp:3.10.0'
}

**Comment by danesfeder** [comment]
Could be a caching issue - have you tried https://stackoverflow.com/questions/13565082/how-can-i-force-gradle-to-redownload-dependencies?

**Comment by vincent-caron** [comment]
after erasing the .gradle/caches directory and tried the other solution you gave me before ( https://stackoverflow.com/questions/46304196/unable-to-get-provider-android-arch-lifecycle-lifecycleruntimetrojanprovider-ja), no more succes. It crashes with the same error.

It's getting late here in france, so i'll see that tomorrow. If you have other ideas, i'll be glad to try..

**Comment by danesfeder** [comment]
Hey @vincent-caron 👋 - I was able to set up a test project with your dependencies and didn't seem to run into issue.  Here are my files:

Project `build.gradle`:
```
buildscript {
    
    repositories {
        google()
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.1.3'
    }
}

allprojects {
    repositories {
        google()
        jcenter()
        maven { url "https://oss.sonatype.org/content/repositories/snapshots/" }
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
```

App `build.gradle`:
```
apply plugin: 'com.android.application'

android {
    compileSdkVersion 27

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    defaultConfig {
        applicationId "com.mapbox.navigationuitest"
        minSdkVersion 21
        targetSdkVersion 27
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        debug {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation 'com.android.support:appcompat-v7:27.1.1'
    implementation 'com.android.support:design:27.1.1'
    implementation 'com.android.support.constraint:constraint-layout:1.1.2'
    implementation 'com.android.support:support-v4:27.1.1'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'
    implementation 'com.mapbox.mapboxsdk:mapbox-android-navigation-ui:0.16.0'
    implementation 'com.squareup.retrofit2:retrofit:2.3.0'
    implementation 'com.squareup.retrofit2:converter-gson:2.3.0'
    implementation 'com.squareup.okhttp3:okhttp:3.10.0'
}
```

Do you see any differences or anything missing on your end from these two files?

**Comment by vincent-caron** [comment]
Hourra, 
it was those lines which were missing :

 compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

I've also changed the mindSDK to 21 (before that it was asking for 26 min).

And it works now perfectly, I can continue my project now

Many many thanks for you help !!! You saved my day, really.

I've another problem but i've a few tests to do before reporting it in another thread

**Comment by danesfeder** [comment]
@vincent-caron glad we could help!
