### ISSUE TITLE
Feature request: custom milestones: allow location as trigger property

### ISSUE THREAD

**Issue by wbearand** [mapbox/mapbox-navigation-android#1161]
There are already trigger properties like STEP_INDEX which allow triggering custom milestone events, is it possible or planned to pass-in locations as custom milestones (eg. LOCATION)? Would probably be achievable using GeoFencing.

> We are actively adding more and more trigger properties every day while we continue building out the milestones API. Please open an issue on GitHub if you feel a trigger property is missing and include the use-case.

It would allow to play custom instructions near locations along the route.

https://www.mapbox.com/android-docs/navigation/overview/milestones/#building-a-custom-milestone

**Comment by hmkum** [comment]
Any news for this one? Receiving current location(lat ,lng) as a TriggerProperty would be nice. Not just step information for remaining distance and duration, also TOTAL_DISTANCE_REMAINING_METERS, TOTAL_DURATION_REMAINING_SECONDS would be nice too.

**Comment by Guardiola31337** [comment]
Hey @wbearand @hmkum 👋 thanks for checking out the SDK.

Want to note that milestones is not going to be a feature of the upcoming `1.0` SDK. Stay tuned for the upcoming beta release and let us know if you have any problems implementing OP's feature.

Closing here.

**Comment by Guardiola31337** [comment]
Hey @wbearand @hmkum we've just released [`release_core_1.0.0-rc.1`](https://github.com/mapbox/mapbox-navigation-android/releases/tag/release_core_1.0.0-rc.1) 🎉 🚀 

Please review the [developer documentation](https://docs.mapbox.com/android/beta/navigation/overview/#installation) to start building with the Mapbox core Navigation SDK v1.0 for Android and if you already use an older version of the Navigation SDK, check out [the migration guide](https://github.com/mapbox/mapbox-navigation-android/wiki/1.0-Navigation-SDK-Migration-Guide) to transition your project from the "legacy" core Navigation SDK to the 1.0 version and let us know if you have any questions or run into issues and please open tickets in https://github.com/mapbox/mapbox-navigation-android/issues/new and we will take it from there! We would love your feedback.

Thanks again!
