### ISSUE TITLE
Why api_token is mandatory ?

### ISSUE THREAD

**Issue by AliKhoshraftar** [mapbox/mapbox-navigation-android#1164]
hi , we are using mapbox navigation , mapbox map SDK solved the mandatory api_token bug in V6.2.x , the new navigation sdk ( V0.16.0 ) is using mapbox map V6.3.0 , but NavigationRoute Builder needs NonNull api_token.
We have all of route , geoCode , reverseGeoCode & etc related to map and no need any apis from mapbox, in our base mapview we using mapbox map 6.3.0 without api_token perfectly. now we need navigation sdk without api_token.
Is it in your plan to make it Nullable ?

**Comment by danesfeder** [comment]
Hey @AliKhoshraftar 👋 thanks for your feedback here.  I'm a bit confused by your question, so bear with me as I clarify.  

> We have all of route , geoCode , reverseGeoCode & etc related to map

> but NavigationRoute Builder needs NonNull api_token

If you have your own route API, then you wouldn't need to use `NavigationRoute`?  So you're asking this with regard to the constructor of `MapboxNavigation`?

**Comment by danesfeder** [comment]
Hey @AliKhoshraftar following up here, do my questions make sense?

**Comment by AliKhoshraftar** [comment]
Hi , thanks for your answer.
As i understood i need only navigation-ui module right ?
I'm using NavigationRoute because of our models are different , so i changed DirectionService and MapboxDirections classes to my requirements and call it again after draw route at the first time.
You mean if i use same response like DirectionsResponse i don't need to initialize NavigationRoute right ?

Thanks in advanced

**Comment by AliKhoshraftar** [comment]
@danesfeder Hey , i'm waiting , i forgot to tag you.
thanks.

**Comment by danesfeder** [comment]
When you say `We have all of route , geoCode , reverseGeoCode & etc related to map`, I'm assuming this means you have all data needed without our APIs.  So you already have a `DirectionsRoute` to be used with the SDK, and you are wondering why you need an access token to create an instance of `MapboxNavigation`?

**Comment by danesfeder** [comment]
@AliKhoshraftar are you able to speak to any of the questions above? ^

**Comment by danesfeder** [comment]
@AliKhoshraftar going to close as stale here - if you have other questions regarding this, let us know.  Thanks!
