### ISSUE TITLE
NullPointerException when using MapMatching Route

### ISSUE THREAD

**Issue by riastrad** [mapbox/mapbox-navigation-android#1169]
**Android API:** 
**Mapbox Navigation SDK version:** 0.16.0

### Steps to trigger behavior

 1. Use MapMatching.builder() to generate a custom route
 2. Pass that route to `navigation.startNavigation(route);`
 3. App crashes with a NullPointerException

### Expected behavior

MapMatching route is successfully passed to `.startNavigation()` and a turn-by-turn navigation session begins.

### Actual behavior

Crash:
<img width="1680" alt="ekran resmi 2018-07-27 09 50 18" src="https://user-images.githubusercontent.com/16272584/43484881-a0c0cbbc-94dd-11e8-8207-14ed5564f135.png">

**Comment by headbanggg** [comment]
```
.voiceUnits("metric")
.language("fr-FR")

```
Thanks a lot for your help. It worked 👍

**Comment by danesfeder** [comment]
Noting here that updating the requests will fix this - but we are also addressing the internal crash with #1174.
