### ISSUE TITLE
DirectionsRoute Request

### ISSUE THREAD

**Issue by jethro-2018** [mapbox/mapbox-navigation-android#1171]
Is it possible to send the route retrieved from the DirectionsResponse to another activity through an Intent? The one method i did have some luck with was using the Gson library, i could retrieve it in the second activity but it is obviously not usable in .directionsRoute(route)

`Intent intent = new Intent(mContext, SecondActivity.class);
                intent.putExtra("Route", gson.toJson(currentRoute));
                startActivity(intent);

        Gson gson = new Gson();
        String strObj = getIntent().getStringExtra("Route");
        DirectionsRoute src = gson.fromJson(strObj, DirectionsRoute.class);
`

So that the next activity could receive that route and make use of it in the NavigationViewOptions.builder()?

`NavigationViewOptions options = NavigationViewOptions.builder()
                        .navigationListener(DriveActivity.this)
                        .progressChangeListener(DriveActivity.this)
                        .directionsProfile(DirectionsCriteria.PROFILE_DRIVING)
                        .directionsRoute(route)
                        .build();`

However it returns the following error:

` Failed to invoke public com.mapbox.api.directions.v5.models.DirectionsRoute() with no args`

**Comment by danesfeder** [comment]
Hey @jethro-2018, yeah it's possible to convert a `DirectionsRoute` to a `String` json and then back to a `DirectionsRoute`.

You need to do this with a DirectionsRoute type adapter like we are doing in [`NavigationLauncher`](https://github.com/mapbox/mapbox-navigation-android/blob/master/libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/NavigationLauncher.java#L66-L67).  To convert back, you can use `DirectionsRoute.fromJson(String json)`.

As you've already found in our java library repository, there is ticketed work to make this more straightforward.  

I will also note, be weary of packaging the `String` json in an `Intent`.  Some routes can be very big and there is a size limit to what you can package in an `Intent`.  `SharedPreferences` may be another option you can use here. 

Closing as answered.

**Comment by jethro-2018** [comment]
The Shared Preference was a great suggestion and worked perfectly, for anyone else who runs into this issue:

I stored the route with:

`SharedPreferenceUtil.getInstance(App.getContext()).setValue("Route", new GsonBuilder()
                                .registerTypeAdapterFactory(DirectionsAdapterFactory.create()).create().toJson(currentRoute));`

Retrieved it with:

`        String directionsRouteJson = SharedPreferenceUtil.getInstance(App.getContext()).getStringValue("Route", "");
`

Then passed it into NavigationViewOptions with:

`                        .directionsRoute(DirectionsRoute.fromJson(directionsRouteJson))
`
