### ISSUE TITLE
The embedded example's current speed widget goes on top of the recenter button when viewing overview

### ISSUE THREAD

**Issue by devotaaabel** [mapbox/mapbox-navigation-android#1176]
![device-2018-08-01-175434](https://user-images.githubusercontent.com/14295757/43551166-098e73ca-95b4-11e8-8ee0-c1ed00bf46dc.png)

**Comment by danesfeder** [comment]
I was not able to reproduce this:

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/8434572/48079086-a0a1f200-e1b8-11e8-9add-e7530b70293c.gif)

Overview:

![device-2018-11-06-113915](https://user-images.githubusercontent.com/8434572/48079108-a697d300-e1b8-11e8-94c5-5fc5c3af50f9.png)

If we run into this again, we can re-open.
