### ISSUE TITLE
NavigationView - Allow Hide/Remove NavigationMapRoute

### ISSUE THREAD

**Issue by Danny-James** [mapbox/mapbox-navigation-android#1177]
I'm currently using `NavigationView` with `MapMatching`, the route which is overlayed onto the map seems to cut allot of corners, so I have plotted a `Polyline` over the top of the map.

I would like to hide/remove the `NavigationMapRoute` i can see `navigationView.drawRoute()` however, I don't believe `navigationView.removeRoute()` is available.

Is their anyway to hide this or if i could make the colour of the line `Transparent` (this will allow me to keep the route turn arrows on the map.

**Comment by Danny-James** [comment]
![screenshot_20180802-104636_route info](https://user-images.githubusercontent.com/32104383/43576489-06ff7552-9639-11e8-9bd2-ff2c64be90e6.jpg)

**Comment by danesfeder** [comment]
Hey @Danny-James this is a valid issue - we currently don't allow access to our Map APIs for adding / removing the route.  Stay tuned as we work this into our pipeline (it should be a pretty minor change).

**Comment by Danny-James** [comment]
@danesfeder would it be possible to allow me not only to Add/Remove but also modify, for example i would like to keep the turn arrows but i'd like to make the NavigationMapRoute line `transparent`.

Do you understand what i mean?
