### ISSUE TITLE
Feedback FAB language issue

### ISSUE THREAD

**Issue by P-Zenker** [mapbox/mapbox-navigation-android#1193]
**Android API:** 26 (8.0 Oreo)
**Mapbox Navigation SDK version:** 16.0

### Steps to trigger behavior

```
NavigationRoute.builder(this)
        .voiceUnits(DirectionsCriteria.METRIC)
        // ...
        .language(Locale.GERMAN)
        .build()
        .getRoute(new Callback<DirectionsResponse>() {
	    	// ...    
	}
);

NavigationLauncherOptions options = NavigationLauncherOptions.builder()
        .directionsRoute(directionsRoute)
        .build();

NavigationLauncher.startNavigation(this, options);
```
My DirectionsRoute.voiceLanguage() and Smartphone default language is de-DE. 

### Expected behavior

If I open the feedback FAB the text-language should be de-DE too, not english.

### Actual behavior
![screenshot_20180806-162453_uksh](https://user-images.githubusercontent.com/23097192/43722968-d4e8e4d4-9996-11e8-853e-354c301925c6.jpg)

**Comment by danesfeder** [comment]
Hey @P-Zenker 👋 this is a valid issue.  We have the localized `String`s via Transifex, but fail to retrieve them.  Thanks for bringing this to us - PR incoming.
