### ISSUE TITLE
Version 17 SNAPSHOT

### ISSUE THREAD

**Issue by Danny-James** [mapbox/mapbox-navigation-android#1198]
I'm now using Version 17 SNAPSHOT, However I've also updated Android Studio.

Since changing **from**
```java
implementation('com.mapbox.mapboxsdk:mapbox-android-navigation-ui:0.16.0') {
        transitive = true
        changing = true
    }
```
**to**
```java
implementation('com.mapbox.mapboxsdk:mapbox-android-navigation-ui:0.17.0-SNAPSHOT') {
        transitive = true
        changing = true
    }
```
I'm now getting the following message(s).
![android support error](https://user-images.githubusercontent.com/32104383/43780654-9956ed44-9a4a-11e8-9fc5-9bbdb4eb6625.png)

I'm also getting multiple errors for `cannot resolve method`.

The app is still compiling however, it's making it difficult to develop.

I don't believe the `cannot resolve method` is anything to do with Version 17 as when reverting back to Version 16 i'm still getting the issue, could this be since the update of Android Studio?

**Comment by Guardiola31337** [comment]
Hey @Danny-James 👋 thanks for reaching out and report your question.

> I don't believe the `cannot resolve method` is anything to do with Version 17 as when reverting back to Version 16 i'm still getting the issue, could this be since the update of Android Studio?

Yeah, that sounds like a dependency conflict to me although unrelated to the SDK.

Please feel free to reopen if you find a conflict with the SDK. Thanks again!

Closing as non actionable.
