### ISSUE TITLE
Abbreviations not working properly in landscape mode

### ISSUE THREAD

**Issue by devotaaabel** [mapbox/mapbox-navigation-android#1201]
The same phone actually shows more text in portrait than in landscape, as you can see in the screenshots. These were taken on a Pixel 2 XL.

**Comment by devotaaabel** [comment]
![device-2018-08-09-102712](https://user-images.githubusercontent.com/14295757/43905431-12f48eb6-9bbf-11e8-848e-3f5844e56893.png)
![device-2018-08-09-102902](https://user-images.githubusercontent.com/14295757/43905433-130082a2-9bbf-11e8-8946-ca3905094895.png)

**Comment by Guardiola31337** [comment]
@abhishek1508 is this still an issue in the `1.0` UI SDK?

Refs. https://github.com/mapbox/mapbox-navigation-android/issues/3060
