### ISSUE TITLE
Add generic traffic circle icon for roundabout maneuver types with null angle

### ISSUE THREAD

**Issue by Guardiola31337** [mapbox/mapbox-navigation-android#1202]
When populating the data for the `ROUNDABOUT_MANEUVER_TYPES` there are still situations in which the `roundaboutAngle` is not provided (`null`) and those are drawn as follows 👀 

_Banner instruction_

![roundabout_angle_not_provided_instruction](https://user-images.githubusercontent.com/1668582/43900210-75712c00-9be4-11e8-8b36-589704adf22a.png)

_Then banner instruction_

![roundabout_angle_not_provided_then_instruction](https://user-images.githubusercontent.com/1668582/43900273-a18cad00-9be4-11e8-9980-def11ca54f49.png)

_Instructions list_

![roundabout_angle_not_provided_instruction_list](https://user-images.githubusercontent.com/1668582/43900281-a5b8ca80-9be4-11e8-8244-00fb2d15258a.png)

which is confusing from a user point of view.

We should have a generic traffic circle icon without a maneuver as discussed in https://github.com/mapbox/mapbox-navigation-android/pull/1064

cc @Cjballard @danesfeder

**Comment by Danny-James** [comment]
@Guardiola31337  I've been seeing the same issue see here #396

**Comment by danesfeder** [comment]
@Cjballard 👋 if you have any questions about the above, let us know.  I think a simple vector asset should do for now.  Ideally we would do this in the `PaintCode` code but this has proven difficult to update 😆

**Comment by Cjballard** [comment]
@danesfeder @Guardiola31337 On it — remind me, did we settle on this icon but in our style? 
![rdb-icon](https://user-images.githubusercontent.com/7535952/45043249-a8b7a700-b03a-11e8-962e-1170fd587b1f.png)

**Comment by danesfeder** [comment]
@Cjballard I don't recall completely, but that looks good to me - @Guardiola31337?

**Comment by Cjballard** [comment]
More accurately:
![screen shot 2018-09-04 at 12 12 57 pm](https://user-images.githubusercontent.com/7535952/45043749-0dbfcc80-b03c-11e8-8323-3fe59b7bf23d.png)

@danesfeder @Guardiola31337

**Comment by Guardiola31337** [comment]
@Cjballard @danesfeder 
I personally like the design of the first icon more than the more accurately version. But, that's my opinion. Going to hand it over to you on taking the final decision 😅 Either way sounds good 🚀

**Comment by danesfeder** [comment]
We are able to achieve https://github.com/mapbox/mapbox-navigation-android/issues/1202#issuecomment-418428558 with the current PaintCode setup.  Rather than adding the extra logic for an asset outside of PaintCode, my suggestion is let's just go with this for now - default `180`

**Comment by Guardiola31337** [comment]
> We are able to achieve https://github.com/mapbox/mapbox-navigation-android/issues/1202#issuecomment-418428558 with the current PaintCode setup.  Rather than adding the extra logic for an asset outside of PaintCode, my suggestion is let's just go with this for now - default `180`

Of course! Didn't know that you were generating that icon using PaintCode. As that's the case, yeah I agree, let's :shipit:

**Comment by Guardiola31337** [comment]
@JunDai look this as it refs https://github.com/mapbox/mapbox-navigation-android/pull/2516

Also, it'd be 💯 if we can get input from the design team @designevokes @map-angela @noracalabrese

**Comment by Guardiola31337** [comment]
@asinghal22 is this something that we want to support in `1.0`?

cc @abhishek1508 @JunDai

**Comment by noracalabrese** [comment]
Thanks @Guardiola31337, we can sync up to understand this better / if any assets are needed that we can help with. Thanks

**Comment by Guardiola31337** [comment]
@noracalabrese 
> we can sync up to understand this better / if any assets are needed that we can help with.

That'd be 💯 Let's coordinate internally 👍

**Comment by RingerJK** [comment]
@Guardiola31337 A solution was merged https://github.com/mapbox/mapbox-navigation-android/pull/3867. Should we close the ticket?

**Comment by Guardiola31337** [comment]
> Should we close the ticket?

Sure thing 🚀 

Thanks for taking care of this @RingerJK 

Closing.
