### ISSUE TITLE
NavigationView - Orientation Change

### ISSUE THREAD

**Issue by Danny-James** [mapbox/mapbox-navigation-android#1210]
When changing from `Landscape` or `Portrait` I seem to loose my route, is their anything i need to do to prevent this?

It seems like the Navigation is still running as their are still `VoiceInstructions`

See example GIF below.

![orientation_change](https://user-images.githubusercontent.com/32104383/44024971-4d9070e0-9ede-11e8-9076-5aba248c5078.gif)

**Comment by Guardiola31337** [comment]
Hey @Danny-James 👋 thanks for reaching out and report your question.

I believe this relates to https://github.com/mapbox/mapbox-navigation-android/issues/1177 and I imagine you're using [`NavigationView#retrieveNavigationMapboxMap`](https://github.com/mapbox/mapbox-navigation-android/blob/master/libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/NavigationView.java#L379-L390) to access to our Map APIs for adding / removing the route. If so, as you can imagine this is something that we don't track because you explicitly added so you'd need to manage it from your side. I guess you could take advantage of `onSaveInstanceState` / `onRestoreInstanceState` methods to restore the route when an orientation change occurs. Does that make sense or I'm missing something?

**Comment by Danny-James** [comment]
@Guardiola31337 I've not currently done anything with #1177 this has been happening for some time but was in my list of things to investigate.

**Comment by Guardiola31337** [comment]
> I imagine you're using [`NavigationView#retrieveNavigationMapboxMap`](https://github.com/mapbox/mapbox-navigation-android/blob/master/libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/NavigationView.java#L379-L390) to access to our Map APIs for adding / removing the route.

Are you interacting directly with the `MapboxMap` to add / remove the route?

As explained above

> If so, as you can imagine this is something that we don't track because you explicitly added so you'd need to manage it from your side.

To double check that the default behavior was working 👌 I run a quick test and as you can see below the route survives rotation 👀 

![orientation_change_ok_route](https://user-images.githubusercontent.com/1668582/44090848-d8f44628-9fcb-11e8-925a-18eb435ad8bb.gif)

**Comment by Danny-James** [comment]
@Guardiola31337 I'm using `NavigationView` and I'm doing the following; 

```java
@SuppressLint("MissingPermission")
    @Override
    protected void onCreate(@Nullable Bundle savedInstanceState) {
        setTheme(R.style.Theme_AppCompat_NoActionBar);
        super.onCreate(savedInstanceState);

        // Create CrashLytics.
        final Fabric fabric = new Fabric.Builder(this)
                .kits(new Crashlytics())
                .debuggable(true)
                .build();
        Fabric.with(fabric);

        // Retrieve Coordinates From File.
        getCoordinatesData();

        setContentView(R.layout.activity_navigation);

        navigationView = findViewById(R.id.navigationView);
        navigationView.onCreate(savedInstanceState);
        navigationView.initialize(this);

    }
@Override
    public void onNavigationReady(boolean isRunning) {
        if (!isRunning) {

            // Hide Feedback Button And Summary Sheet.
            navigationView.findViewById(R.id.feedbackFab).setVisibility(View.GONE);
            navigationView.findViewById(R.id.summaryBottomSheet).setVisibility(View.GONE);

            navigationMapboxMap = navigationView.retrieveNavigationMapboxMap();
            mapboxMap = navigationMapboxMap.retrieveMap();

            // Set Default Starting Location
            mapboxMap.setCameraPosition(new CameraPosition.Builder()
                    .target(new LatLng(53.481215, -2.244063))
                    .zoom(6)
                    .build());

            // Add Polyline onto NavigationMap.
            if (points.size() > 1) {

                List<LatLng> polylinePoints = new ArrayList<>();

                // Add Points To LatLng Array
                for (int i = 0; i < points.size(); i++) {
                    polylinePoints.add(new LatLng(points.get(i).latitude(), points.get(i).longitude()));
                }

                // Remove Any Existing Polyline.
                if(plottedRoute != null){
                    mapboxMap.removePolyline(plottedRoute);
                }

                // Add New Route Polyline
                plottedRoute = mapboxMap.addPolyline(new PolylineOptions()
                        .addAll(polylinePoints)
                        .color(R.color.colorPrimary)
                        .width(14)
                        .alpha(1));
            }else{
                showUnableToRouteDialog("There has been an issue plotting the route line.");
            }

            // Display Prompt To User To Check If Starting Partway Through Route.
            showStartOfJourneyDialog();
        }else{
            Log.d(TAG, "Navigation Is Already Running - isRunning = TRUE");
        }

    }

```

I'm getting my route using the `MapMatching` and starting the navigation like so;
```java
private void startNavigation(DirectionsRoute directionsRoute) {
        Log.d(TAG, "StartNavigation");
        NavigationViewOptions navigationViewOptions = setupOptions(directionsRoute);
        navigationView.startNavigation(navigationViewOptions);
        navigationView.findViewById(R.id.feedbackFab).setVisibility(View.GONE);
        //navigationMapboxMap.removeRoute();

        // Create Origin and Destination Markers
        createMarkers();
    }
```

**Comment by danesfeder** [comment]
@Danny-James when you rotate the phone, you need to cache your route / options to repopulate the UI.  Like we do [here](https://github.com/mapbox/mapbox-navigation-android/blob/master/libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/MapboxNavigationActivity.java#L95-L101) for example.  We opted to store the route JSON in `SharedPreferences`.  Please confirm this fixes your issue and we can close this ticket.

**Comment by Danny-James** [comment]
@danesfeder as i'm using `NavigationView` would i do the following;

```java
navigationView.extractRoute(this);
```

instead of [this ](https://github.com/mapbox/mapbox-navigation-android/blob/master/libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/MapboxNavigationActivity.java#L122)

I'm not sure which would be the best way to do this, at what point do i cache the route? `NavigationLauncher.extractRoute(this)` returns a `DirectionsRoute` do you have any examples of caching this?

As i see you only seem to be saving the `Route Options` to `SharedPreferences` like below;

```java
  private void extractConfiguration(NavigationViewOptions.Builder options,
                                    MapboxNavigationOptions.Builder navigationOptions) {
    SharedPreferences preferences = PreferenceManager.getDefaultSharedPreferences(this);
    options.shouldSimulateRoute(preferences
      .getBoolean(NavigationConstants.NAVIGATION_VIEW_SIMULATE_ROUTE, false));
    options.directionsProfile(preferences
      .getString(NavigationConstants.NAVIGATION_VIEW_ROUTE_PROFILE_KEY, DirectionsCriteria.PROFILE_DRIVING_TRAFFIC));
    navigationOptions.enableOffRouteDetection(preferences
      .getBoolean(NavigationConstants.NAVIGATION_VIEW_OFF_ROUTE_ENABLED_KEY, true));
    navigationOptions.snapToRoute(preferences
      .getBoolean(NavigationConstants.NAVIGATION_VIEW_SNAP_ENABLED_KEY, true));
  }
```

**Comment by Guardiola31337** [comment]
@Danny-James as @danesfeder mentioned
> when you rotate the phone, you need to cache your route / options to repopulate the UI.  Like we do [here](https://github.com/mapbox/mapbox-navigation-android/blob/master/libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/MapboxNavigationActivity.java#L95-L101) for example.  We opted to store the route JSON in `SharedPreferences`.

☝️is only an example showing how we handle a similar problem in the SDK i.e. it doesn't mean you need cache the same options nor use the commented APIs but you get the idea on how to implement it yourself.

Going to go ahead and close this as answered - please let us know if you find any other bugs!

Thanks Danny as always 🙏

**Comment by hardikJoshi123** [comment]
> @Danny-James when you rotate the phone, you need to cache your route / options to repopulate the UI. Like we do [here](https://github.com/mapbox/mapbox-navigation-android/blob/master/libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/MapboxNavigationActivity.java#L95-L101) for example. We opted to store the route JSON in `SharedPreferences`. Please confirm this fixes your issue and we can close this ticket.

404 page not found!
