### ISSUE TITLE
how to move multiple markers simultaneously by the jsonarray result

### ISSUE THREAD

**Issue by Bharathjh614** [mapbox/mapbox-navigation-android#1211]
android application which shows the near by vehicles for which latlng will be saved to server on locationchanged which will be the jsonarray result from which i will be able to add the markers on mapbox map through animation i am able to move the single marker to the next updated latlng values. I am not able to move all the markers displayed on the navigation view of the map simultaneously as they are updated. Marker moves one by one to the updated location
here is the code used to add all markers in navigation view of mapbox.

```
HashMap<Integer, Marker> markerhash = new HashMap<Integer, Marker>();
    if (json.getString("status").equalsIgnoreCase("success")) {
      Alllocations = json.getJSONArray("locations");
      for (int i = 0; i < Alllocations.length(); i++) {
        JSONObject LocInfo = Alllocations.getJSONObject(i);
        int id = LocInfo.getInt("user_id");
        if (markerhash.containsKey(id)) {
          marker = markerhash.get(id);
          marker.setIcon(icon);
          ValueAnimator markerAnimator = ValueAnimator.ofObject(new LatLngEvaluator(), (Object[]) new LatLng[] {marker.getPosition(), new LatLng(LocInfo.getDouble("latitude"), LocInfo.getDouble("longitude"))});

          markerAnimator.setDuration(2000);
          markerAnimator.setInterpolator(new AccelerateDecelerateInterpolator());
          markerAnimator.addUpdateListener(new ValueAnimator.AnimatorUpdateListener() {
            @Override
            public void onAnimationUpdate(ValueAnimator animation) {
              if (marker != null) {
                marker.setPosition((LatLng) animation.getAnimatedValue());
              }
            }
          });
          markerAnimator.start();

        } else {
          marker = navigationView.getMapboxMap().addMarker(new MarkerOptions()
            .position(new LatLng(LocInfo.getDouble("latitude"), LocInfo.getDouble("longitude")))
            .snippet(String.valueOf(LocInfo.getInt("user_id")))
            .icon(icon)
          );
          markerhash.put(id, marker);

        }
      }
    }
```
since the json array iterates through for loop i am not able to animate all the markers continuously it is being updated one by one. Sometimes the marker flickers since other json array result come fast by the time the marker completes it animation

**Comment by danesfeder** [comment]
Hey @Bharathjh614 👋 thanks for your feedback here.  At first glance, this doesn't look like an issue with the Navigation SDK.

It looks like your issue is exactly how you described:
> since the json array iterates through for loop i am not able to animate all the markers continuously it is being updated one by one. Sometimes the marker flickers since other json array result come fast by the time the marker completes it animation

You need to update the markers in a way that isn't iterative if you want them to move all at the same time. 

Going to close here as non-actionable.

**Comment by Bharathjh614** [comment]
yeah there is no issue with navigation sdk but i want to know is ther any method to update all markers at a time from json array without using iterative loops since it updates one by one

**Comment by Yogesh9900** [comment]
I also have the same issue. Anyone have any solution on it? Please let me know.

**Comment by akbarattar3** [comment]
This issue is not resolved till now , how did you close this issue ?
