### ISSUE TITLE
Allow developers to replace built-in buttons

### ISSUE THREAD

**Issue by akitchen** [mapbox/mapbox-navigation-android#1216]
Allow developers to provide their own buttons for sound, feedback, map re-center as the view is created.

cc @cmahopper @hurrba @LindaRosa

**Comment by Guardiola31337** [comment]
Refs. https://github.com/mapbox/mapbox-navigation-android/issues/1746

**Comment by Guardiola31337** [comment]
This is going to be superseded by https://github.com/mapbox/mapbox-navigation-android/pull/2824

Closing here.

cc @abhishek1508
