### ISSUE TITLE
Add compass view to turn-by-turn UI

### ISSUE THREAD

**Issue by akitchen** [mapbox/mapbox-navigation-android#1218]
We would like to add a compass to the UI that is adjusted based on bearing/course. Further design consideration may be needed when it comes to reflecting the user's heading vs. bearing.

Clicking the compass would adjust the map camera to track while always "facing north"

See also https://github.com/mapbox/mapbox-navigation-ios/issues/1217

cc @cmahopper @hurrba @LindaRosa

**Comment by Guardiola31337** [comment]
Closing this in favor of #1977 

cc @andrlee @abhishek1508
