### ISSUE TITLE
Unable to overwrite BannerInstruction

### ISSUE THREAD

**Issue by Danny-James** [mapbox/mapbox-navigation-android#1224]
I am unable to get the BannerInstruction to overwrite based on the PR [#1107](https://github.com/mapbox/mapbox-navigation-android/pull/1107)
```java
@Override
    public BannerInstructions willDisplay(BannerInstructions instructions) {
        if (instructions.primary().text().contains("arrive") && points.size() > 1){
            BannerText bannerText = new BannerText() {
                @Nullable
                @Override
                public String text() {
                    return "Continue on route.";
                }

                @Nullable
                @Override
                public List<BannerComponents> components() {
                    return instructions.primary().components();
                }

                @Nullable
                @Override
                public String type() {
                    return "continue";
                }

                @Nullable
                @Override
                public String modifier() {
                    return instructions.primary().modifier();
                }

                @Nullable
                @Override
                public Double degrees() {
                    return instructions.primary().degrees();
                }

                @Nullable
                @Override
                public String drivingSide() {
                    return instructions.primary().drivingSide();
                }

                @Override
                public Builder toBuilder() {
                    return instructions.primary().toBuilder();
                }
            };
            return instructions.toBuilder().primary(bannerText).build();
        }
        return instructions;
    }
```

The BannerInstruction is still displaying `You will arrive`, also when I tap the BannerInstruction it shows me a list of upcoming Instructions, how would I overwrite these also?

Forgive me as I may be doing the BannerInstruction wrong.

**Comment by Danny-James** [comment]
@danesfeder @Guardiola31337 is there any chance somebody could look into this please as this is the only issue preventing me from releasing my app :)

Just to clarify, the main banner instruction states `you have arrived` and the intruction list also states `you have arrived` i need to overwrite the current instruction and also overwrite or remove the instruction list item.

Many Thanks.

**Comment by Guardiola31337** [comment]
Hey @Danny-James 👋 this is being discussed in https://github.com/mapbox/mapbox-navigation-android/pull/1233

Feel free to add your comments / thoughts there as we decide how to address / fix this issue.

Thanks as always!

**Comment by Guardiola31337** [comment]
Questions / points to consider before implementing a solution that covers all the cases / scenarios for solving OP:

- Overwrite / hide the list of instructions (accessible by clicking the top banner) 👉 https://github.com/mapbox/mapbox-navigation-android/pull/1233#issuecomment-417641978
- What to do with the "then" banner instruction when clients override the banner 👉 https://github.com/mapbox/mapbox-navigation-android/pull/1233#issuecomment-417644127
- Overwrite notification text 👉 https://github.com/mapbox/mapbox-navigation-android/pull/1233#issuecomment-421355115

**Comment by Danny-James** [comment]
Any news on overwriting upcoming instruction list?

**Comment by Danny-James** [comment]
@Guardiola31337  did this issue ever become resolved;

- Overwrite / hide the list of instructions (if no overwrite prevent user from viewing upcoming list)
- Overwrite notification text

**Comment by Guardiola31337** [comment]
@asinghal22 is this something we want to support in `1.0`?

cc @abhishek1508

**Comment by Guardiola31337** [comment]
Is this the same as https://github.com/mapbox/mapbox-navigation-android/issues/3300? Could you verify @abhishek1508?

**Comment by abhishek1508** [comment]
Yes it is the same
cc @Guardiola31337

**Comment by abhishek1508** [comment]
Closing this one in favor of https://github.com/mapbox/mapbox-navigation-android/issues/3300
