### ISSUE TITLE
RouteProgress.getDistanceTraveled() returns length of first step in first leg.

### ISSUE THREAD

**Issue by mecoFarid** [mapbox/mapbox-navigation-android#124]
Whichever step I am in along the route, `RouteProgress.getDistanceTraveled()` returns length of first step of first leg. 
P.S. even I'm on route `userOffRoute()` being called.
NOTE: I'm not testing in real world, using Fake GPS (App) instead.

**Comment by cammace** [comment]
[This test](https://github.com/mapbox/mapbox-navigation-android/blob/master/navigation/libandroid-navigation/src/test/java/com/mapbox/services/android/navigation/v5/routeprogress/RouteProgressTest.java#L123-L130) is currently passing on master confirming that `routeProgress.getDistanceTraveled()` is working as expected. Many of the issues you are running into have been resolved on master and are currently available in the `0.4.0-SNAPSHOT`.
