### ISSUE TITLE
Navigation session is not restored properly when screen rotation

### ISSUE THREAD

**Issue by Guardiola31337** [mapbox/mapbox-navigation-android#1240]
Noticed that we're not managing the lifecycle (nav session restoration) properly when rotating the screen 👀 

![lifecycle_issue_screen_rotation](https://user-images.githubusercontent.com/1668582/44668388-97104700-aa1d-11e8-85c5-751387a08d32.gif)

 1. Run a navigation session
 2. Rotate the screen (landscape)
 3. Put the app in background
 4. Restore the app from _Recent apps_ while still in landscape
 5. OK
 6. Put the app in background again
 7. Restore the app from _Recent apps_ in portrait mode
 8. A new session is launched (not desired)

Steps 4 to 6 are not needed to reproduce the issue. I added those to remark that when putting the app in foreground maintaining the screen mode (landscape or portrait) the session is restored 👌

Also a new notification is created. After doing this you're unable to close the second session (only _Force closing_ the app from the app settings). This is noticeable too because voice instructions are voiced twice.

👀 https://github.com/mapbox/mapbox-navigation-android/issues/1190

**Comment by danesfeder** [comment]
@Guardiola31337 do you mind re-testing this now that https://github.com/mapbox/mapbox-navigation-android/pull/1247 has landed?  I'm wondering if this helps here.

**Comment by Guardiola31337** [comment]
@danesfeder 
> do you mind re-testing this now that https://github.com/mapbox/mapbox-navigation-android/pull/1247 has landed?  I'm wondering if this helps here.

Nah, I've retested it and still the same behavior described in OP 😥 You know, _Lifecycle_ / _Configuration changes_ on Android are hard 😬

**Comment by cmahopper** [comment]
Do you have an update on the progress of this?
