### ISSUE TITLE
Duplicated voice instructions after screen rotation in WaypointNavigationActivity

### ISSUE THREAD

**Issue by Guardiola31337** [mapbox/mapbox-navigation-android#1242]
Noticed that sometimes voice instructions are duplicated after rotating the screen while navigating. Found when running the [`WaypointNavigationActivity`](https://github.com/mapbox/mapbox-navigation-android/blob/master/app/src/main/java/com/mapbox/services/android/navigation/testapp/activity/navigationui/WaypointNavigationActivity.java) example from the test app.

**Comment by Guardiola31337** [comment]
@JunDai could we check if this would be an issue in `1.0`?

**Comment by abhishek1508** [comment]
Let's verify.
cc @JunDai @cafesilencio @langsmith 
For this issue let's not worry about the WaypointNavigationActivity as specified in the comment. We need to confirm if we can reproduce this in v1.0

**Comment by JunDai** [comment]
I tested this with `NavigationViewActivity` in `V1.0` SDK, it's gone. And for the developer who only uses the `SpeechPlayer`, they have the responsibility to maintain the speech player status.

Close this for now, feel free to create new one or reopen it if you still see this issue in `V1.0` @Guardiola31337
