### ISSUE TITLE
Initial camera position

### ISSUE THREAD

**Issue by Christophe668** [mapbox/mapbox-navigation-android#1245]
The initial camera position is not placed on user location when starting a route.
I tried several things and I was able to make the camera start at a fixed location.
Currently, the camera seems to sometimes start from coordinates 0, 0 and animate itself to the user location in a few seconds. 
This behavior is seen as a bug by some users. I attached a Gif of the issue and a test project.

Please note that for the test project, I remove the access token in the "App" class and location permission is not asked by default but can be allowed manually.

https://im4.ezgif.com/tmp/ezgif-4-aa2e2f9603.gif

[NavigationIncorrectInitialZoomSample.zip](https://github.com/mapbox/mapbox-navigation-android/files/2328890/NavigationIncorrectInitialZoomSample.zip)

Thank you for the feedback in advance !

**Comment by danesfeder** [comment]
Hey @Christophe668 👋 thanks a lot for the feedback here.  You're correct here > `the camera seems to sometimes start from coordinates 0, 0 and animate itself to the user location in a few seconds`.  

This UX isn't ideal and the solution here I believe is initializing the map with the coordinates from the start of the route passed to start navigation. 

To achieve this, we will need to re-work how the `NavigationView` is initialized.  But I think it's technically feasible.  We will prioritize internally and discuss a solution for this and then report back here on this ticket.  Thanks again!

**Comment by Christophe668** [comment]
@danesfeder Perfect, thanks !

**Comment by Christophe668** [comment]
Hi @danesfeder any news on this? Users are also complaining that the initial zoom stops during the animation as well. 
I can see this also myself. The zoom animation seems to start from 0.0, zooms then to the current location, but then stops in the middle of the animation.

**Comment by Christophe668** [comment]
@danesfeder this seems simple and perfect to me. Let me know when I can test it in a snapshot :)
