### ISSUE TITLE
Add nav event creation code from the mapbox-events-android library

### ISSUE THREAD

**Issue by lilykaiser** [mapbox/mapbox-navigation-android#1246]
Per internal conversation, step 4 in the effort to streamline tracking event ingestion is to refactor event creation code (classes, factories, test, etc...) into the nav SDK and [out of](https://github.com/mapbox/mapbox-events-android/issues/204#issue-354922476) mapbox-android-events. Creating this ticket as a placeholder.

**Comment by akitchen** [comment]
Given the many changes that have happened since this ticket was opened, I don't think we'll be proceeding with this as described. Closing as stale.
