### ISSUE TITLE
Unable to place request on backend

### ISSUE THREAD

**Issue by soumyay** [mapbox/mapbox-navigation-android#1248]
when origin location changed by moving marker position and called getroute() to redraw route from this new origin its moving to Onfailure() callback with exception "Unable to place request on backend"

my code:

mapView.getMapAsync(new OnMapReadyCallback() {
@override
public void onMapReady(final MapboxMap mapboxMap) {

            map = mapboxMap;
            enableLocationPlugin();

            map.setOnCameraIdleListener(new MapboxMap.OnCameraIdleListener() {
                @Override
                public void onCameraIdle() {
                    LatLng midLatLng = map.getCameraPosition().target;
                    originCoord=midLatLng;

                    if(sourceMarker!=null) {
                        map.removeMarker(sourceMarker);
                        sourceMarker=map.addMarker(new MarkerOptions()
                                .position(map.getCameraPosition().target));
                        Point pointorigin=Point.fromLngLat(originCoord.getLatitude(),originCoord.getLongitude());
                        Point pointdestination=Point.fromLngLat(destinationCoord.getLatitude(),destinationCoord.getLongitude());

                        //getRoute(pointorigin, pointdestination);

                       // locationEngine.removeLocationEngineListener(MainActivity.this);
                        // getRoute(midLatLng,destinationPosition);

                        NavigationRoute.builder(MainActivity.this)
                                .accessToken(Mapbox.getAccessToken())
                                .origin(pointorigin)
                                .destination(pointdestination)
                                .build()
                                .getRoute(new Callback<DirectionsResponse>() {
                                    @Override
                                    public void onResponse(Call<DirectionsResponse> call, Response<DirectionsResponse> response) {
                                        // You can get the generic HTTP info about the response

                                        Log.d(TAG, "Response code: " + response.code());
                                        if (response.body() == null) {
                                            Log.e(TAG, "No routes found, make sure you set the right user and access token.");
                                            return;
                                        } else if (response.body().routes().size() < 1) {
                                            Log.e(TAG, "No routes found");
                                            return;
                                        }

                                        currentRoute = response.body().routes().get(0);

                    /*DirectionsRoute route = response.body().getRoutes().get(0);
                    int distance = route.getDistance();

                    if (currentRoute.isOffRoute(originLocation)) {
                        Toast.makeText(this, "You are off-route.", Toast.LENGTH_SHORT).show();
                    }*/

                                        // Draw the route on the map
                   /* if (navigationMapRoute != null) {
                        navigationMapRoute.removeRoute();
                    } else {
                        navigationMapRoute = new NavigationMapRoute(null, mapView, map, R.style.NavigationMapRoute);
                    }
                    navigationMapRoute.addRoute(currentRoute);*/

                                    }

                                    @Override
                                    public void onFailure(Call<DirectionsResponse> call, Throwable throwable) {
                                        Log.e(TAG, "Error: " + throwable.getMessage());
                                    }
                                });
                    }
                }
            });

            map.addOnMapClickListener(new MapboxMap.OnMapClickListener() {
                @Override
                public void onMapClick(@NonNull LatLng point) {

                }
            });

        }

        ;
    });

**Comment by danesfeder** [comment]
Hey @soumyay, it looks like you opened a ticket already in our Java repo > https://github.com/mapbox/mapbox-java/issues/878.  

Anyways, it looks like your origin / destination coordinates (`Point#fromLngLat`) are reversed in:
```
Point pointorigin=Point.fromLngLat(originCoord.getLatitude(),originCoord.getLongitude());
Point pointdestination=Point.fromLngLat(destinationCoord.getLatitude(),destinationCoord.getLongitude());
```
