### ISSUE TITLE
MileStone-Trigger conditions is not met

### ISSUE THREAD

**Issue by Ohemgi** [mapbox/mapbox-navigation-android#1249]
**Android API:27**
**Mapbox Navigation SDK version:6.01**

### Steps to trigger behavior

 1. new MapboxNavigation
 2. No default milestones
 3. adding custom milestone with the following implementations

Version 1:
```
BannerInstructionMilestone.Builder builder = new BannerInstructionMilestone.Builder();
builder.setTrigger(
             Trigger.all(
                        Trigger.eq(TriggerProperty.NEW_STEP, TriggerProperty.TRUE),
                        Trigger.eq(TriggerProperty.FIRST_STEP, TriggerProperty.FALSE)
              )
).setIdentifier(MilestoneIdentifiers.NEW_BANNER_INSTRUCTION);
return builder.build();
```
Version 2:
```
BannerInstructionMilestone.Builder builder = new BannerInstructionMilestone.Builder();
builder.setTrigger(
             Trigger.all(
                        Trigger.eq(TriggerProperty.NEW_STEP, TriggerProperty.TRUE),
                        Trigger.neq(TriggerProperty.FIRST_STEP, TriggerProperty.TRUE)
              )
).setIdentifier(MilestoneIdentifiers.NEW_BANNER_INSTRUCTION);
return builder.build();
```
### Expected behavior

No BannerInstructionMileStone-Event for the first step (but fo all FIRST_STEP + N)

### Actual behavior

BannerInstructionMileStone-Event for the first step

**Comment by danesfeder** [comment]
Hey @Ohemgi 👋 the `BannerInstructionMilestone` is a custom milestone we use to trigger new banner instructions in the `InstructionView`.  

We override `isOccuring` with set logic [here](https://github.com/mapbox/mapbox-navigation-android/blob/master/libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/milestone/BannerInstructionMilestone.java#L20-L30) that will ultimately mean any other triggers set to the `Milestone` will be ignored.  What behavior are you trying to achieve here? 

> BannerInstructionMileStone-Event for the first step

This should actually already be happening.  Do you mean you _only_ want the first instruction?

**Comment by Ohemgi** [comment]
Hey @danesfeder thanks for the reply on this. I tried to ignore certain steps from raising these milestone events. Like "give me standard bannerinstruction milestone behaviour BUT leave out these which come from the step XY" (where XY could be for an example the first and the last step).

**Comment by danesfeder** [comment]
@Ohemgi we pass the `RouteProgress` with the `BannerInstructionMilestone` in the event listener:
`void onMilestoneEvent(RouteProgress routeProgress, String instruction, Milestone milestone);`

Would adding logic based on the `RouteProgress` data help here?  Like the step index?

**Comment by Ohemgi** [comment]
@danesfeder yes that is my approach here :smile:  I just thought, that it would be a nice and lean solution, to use the custom milestone and its triggers. Since the milestone triggers behaved not like i expected them to do, i thought this might be an issue with the navigation sdk. But if this is the expected behaviour we can just close this one :+1:

**Comment by danesfeder** [comment]
@Ohemgi yeah we should be more clear on our side that this is the case - thanks for keeping us honest here.  Will update some of the javadoc to close this.  Thanks again!
