### ISSUE TITLE
Allow To update new Route in navigation view once navigation is started.

### ISSUE THREAD

**Issue by Siddiqa** [mapbox/mapbox-navigation-android#1259]
Cant able to change directions route once navigation is started in navigation view.

**Comment by danesfeder** [comment]
Hey @Siddiqa 👋 thanks for the feedback here!  You're actually able to change the route while the `NavigationView` is inflated.  See [this example](https://github.com/mapbox/mapbox-navigation-android/blob/master/app/src/main/java/com/mapbox/services/android/navigation/testapp/activity/navigationui/WaypointNavigationActivity.java#L182-L207) where we are fetching new routes and giving them to the view when the dialog is clicked.

**Comment by Siddiqa** [comment]
Thanks for the quick help but I want to update new route when reroute is occurring.
I want to update new route directions when reroute occurs. Currently when reroute is occurring the new route is already set  I am not able to update/change that route.

**Comment by danesfeder** [comment]
@Siddiqa Oh I see now, my apologies - you should be able to use the [`RouteListener#allowRerouteFrom`](https://www.mapbox.com/android-docs/navigation/overview/navigation-ui/#routelistener) - you'll return false and use the `Point` provided to make your own request, which you can then provide to the `NavigationView` with `startNavigation` once you have a response.  

We do something similar for map matching, except your request will be a normal Directions API request.  https://www.mapbox.com/android-docs/navigation/overview/map-matching/#map-matching-with-navigationview

**Comment by Siddiqa** [comment]
Hey@danesfeder  thanks i will try this.
