### ISSUE TITLE
Footer informations are sometimes not visible via fake GPS

### ISSUE THREAD

**Issue by P-Zenker** [mapbox/mapbox-navigation-android#1270]
**Android API: 25 (Google Nexus 5, used for development since 3 years - maybe a bit slow now?)**
**Mapbox Navigation SDK version:0.18.0**

### Steps to trigger behavior

 1. Start NavigationView inside of a Fragment
 2. Use fake GPS a few times

### Expected behavior
Update footer informations

### Actual behavior
Sometimes the footer informations are not visible. I couldn't reproduce this behaviour on a brand new Samsung A6 with API 26 (Oreo) and I don't know if that also happens in a real use case.

Example 1:
![ezgif com-video-to-gif-3](https://user-images.githubusercontent.com/23097192/45170063-4cea4b00-b1ff-11e8-9884-670a75fd0ca8.gif)

Example 2:
![ezgif com-video-to-gif-5](https://user-images.githubusercontent.com/23097192/45170106-64293880-b1ff-11e8-87d1-f5fed4e5b2b8.gif)

**Comment by danesfeder** [comment]
@P-Zenker can you re-test with `0.20.0`?  This should be resolved in that version.

**Comment by P-Zenker** [comment]
Great, it seems to be solved - I couldn't reproduce it with 0.21.0

**Comment by danesfeder** [comment]
Thanks @P-Zenker, going to go ahead and close here as resolved 👍
