### ISSUE TITLE
Make all NavigationConstants public

### ISSUE THREAD

**Issue by P-Zenker** [mapbox/mapbox-navigation-android#1272]
Hey,

is there a reason why those constants aren't public?

`
NavigationConstants.MAXIMUM_ALLOWED_DEGREE_OFFSET_FOR_TURN_COMPLETION
NavigationConstants.MAXIMUM_DISTANCE_BEFORE_OFF_ROUTE
NavigationConstants.DEAD_RECKONING_TIME_INTERVAL
NavigationConstants.MAX_MANIPULATED_COURSE_ANGLE
NavigationConstants.USER_LOCATION_SNAPPING_DISTANCE
NavigationConstants.SECONDS_BEFORE_REROUTE
NavigationConstants.ONE_HUNDRED_METER_ACCEPTABLE_ACCURACY_THRESHOLD`

If not, I (maybe) would like to use them too.

**Comment by danesfeder** [comment]
Hey @P-Zenker, these are the default values we use for `MapboxNavigationOptions`, so there shouldn't be a need to expose them, as they will already be set when you create the object ([see here](https://github.com/mapbox/mapbox-navigation-android/blob/master/libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/MapboxNavigationOptions.java#L100-L120)).  Hope this provides some clarity.
