### ISSUE TITLE
navigationView.startNavigation() not updating current DirectionsRoute

### ISSUE THREAD

**Issue by skienzl** [mapbox/mapbox-navigation-android#1276]
Updating a new DirectionsRoute via `navigationView.startNavigation()` does not update the navigationView

**Android API:**  8.1.0
**Mapbox Navigation SDK version:** 0.19.0-SNAPSHOT

### Steps to trigger behavior

 1. start navigation with route
 2. request new route with map matching api
 3. call `navigationView.startNavigation(option)` with new route

### Expected behavior
Update to new route 

### Actual behavior
Still old route

**Comment by danesfeder** [comment]
Great catch @skienzl and thanks for the quick report using the `SNAPSHOT`.  I opened https://github.com/mapbox/mapbox-navigation-android/pull/1277 to address.
