### ISSUE TITLE
Sound and Recenter buttons not reset after closing and launching a navigation session

### ISSUE THREAD

**Issue by Guardiola31337** [mapbox/mapbox-navigation-android#1278]
Cross posting from https://github.com/mapbox/mapbox-navigation-android/pull/1241#issuecomment-419837473

Noticed that the sound button is still "muted" after closing + launching a navigation session but voice instructions are announced 👀

![end_navigation_voice_instructions_when_muted](https://user-images.githubusercontent.com/1668582/45286838-22daa680-b4e7-11e8-988b-3c926e74fd05.gif)

Found this when running the [`EndNavigationActivity`](https://github.com/mapbox/mapbox-navigation-android/blob/master/app/src/main/java/com/mapbox/services/android/navigation/testapp/activity/navigationui/EndNavigationActivity.java) example from the test app.

Shouldn't we initialize the state after relaunching a navigation session? The same thing happened with the `RECENTER` button 👀 

![end_navigation_recenter_button_restored](https://user-images.githubusercontent.com/1668582/45286905-49004680-b4e7-11e8-93db-42e42f27c26c.gif)

**Comment by Guardiola31337** [comment]
@abhishek1508 Is this still an issue in the `1.0` UI SDK / `examples` test app?

cc @JunDai

**Comment by abhishek1508** [comment]
Let's verify
cc @JunDai @cafesilencio @langsmith

**Comment by JunDai** [comment]
can't reproduce this in `1.0`
