### ISSUE TITLE
NavigationService leak

### ISSUE THREAD

**Issue by Guardiola31337** [mapbox/mapbox-navigation-android#1279]
Cross posting from https://github.com/mapbox/mapbox-navigation-android/pull/1241#issuecomment-419839829

Run into the following leak when running the [`EndNavigationActivity`](https://github.com/mapbox/mapbox-navigation-android/blob/master/app/src/main/java/com/mapbox/services/android/navigation/testapp/activity/navigationui/EndNavigationActivity.java) example from the test app 👀 

![end_navigation_activity_leak](https://user-images.githubusercontent.com/1668582/45287395-74cffc00-b4e8-11e8-8e77-0a6125cbd260.png)

**Comment by danesfeder** [comment]
@Guardiola31337 did you have any reproducible steps for this?

**Comment by Guardiola31337** [comment]
@danesfeder 
> did you have any reproducible steps for this?

Yeah, I was able to reproduce 👀

![end_navigation_activity_navigation_service_leak](https://user-images.githubusercontent.com/1668582/45317993-eb4a1980-b53b-11e8-8322-af823cce9ae9.gif)

[`EndNavigationActivity`](https://github.com/mapbox/mapbox-navigation-android/blob/master/app/src/main/java/com/mapbox/services/android/navigation/testapp/activity/navigationui/EndNavigationActivity.java)
1. launch
2. close
3. launch
4. close
5. exit
6. leak
