### ISSUE TITLE
Reroute with MapMathching

### ISSUE THREAD

**Issue by vincent-caron** [mapbox/mapbox-navigation-android#1280]
Android API: all
Mapbox Navigation SDK version: 0.18.0

I have created a route with mapmatching points and 4 mandatory waypoints (with the .waypoints property). When my user get the wrong route, the application reroute to the next waypoint (that's ok) but also recalculate a complete route using the others waypoints, losing the matching route. (that's not ok)

### Expected behavior

The api calculate a new route to the next mandatory waypoint and keep the matching route beetween the other

### Actual behavior
The api calculate a new route for all the waypoints

Hope i'm clear.

Thanks for any help

Vincent

**Comment by Guardiola31337** [comment]
Hey @vincent-caron 👋 thanks for reaching out and report your issue.

Could you add some more information for reproducing the issue (minimal example) or any other specifics around your test setup? If there is any sample or pseudo code you can provide, that would be really helpful. This will give us better insight into your implementation and what could be causing your problem.

**Comment by vincent-caron** [comment]
here the code :

private void StartMatchingNavigation(){
        mapUtil.set_parcoursChoisi(parcoursChoisi);
        List<Point> liste = mapUtil.ConvertParcours(); //**Get the points for the matching calculation**

        MapboxMapMatching.builder()
                .accessToken(Mapbox.getAccessToken())
                .coordinates(liste)
                .waypoints(0,liste.size() / 4, liste.size() / 2, (3 * liste.size()) / 4 ,liste.size()-1 ) ** Keep only 4 mandatories waypoint to avoid a lot of the message "you're arrived at the nth destination ...**
                .steps(true)
                .bannerInstructions(true)
                .roundaboutExits(true)
                .voiceInstructions(true)
                .voiceUnits("metric")
                .language("fr-FR")
                .profile(DirectionsCriteria.PROFILE_CYCLING)
                .build()
                .enqueueCall(new Callback<MapMatchingResponse>() {

                    @Override
                    public void onResponse(Call<MapMatchingResponse> call, Response<MapMatchingResponse> response) {
                        if (response.isSuccessful()) {
                             DirectionsRoute currentRoute = response.body().matchings().get(0).toDirectionRoute();

                           NavigationLauncherOptions options = NavigationLauncherOptions.builder()
                                    .directionsRoute(currentRoute)
                                    .shouldSimulateRoute(false)
                                    .build();

                            NavigationLauncher.startNavigation(MainActivity.this, options);
                        }
                    }

                    @Override
                    public void onFailure(Call<MapMatchingResponse> call, Throwable throwable) {

                    }
                });
    }

So when the navigation begins, it follows the route correctly, but as soons as the user quit the route and a reroute is trigerred, the route is calculated with all the waypoints beside being calculated to the next waypoint and use the rest of the point given

hope this make sense ... :)

**Comment by danesfeder** [comment]
Hey @vincent-caron 👋 unfortunately, in order to re-route successfully with `MapMatching`, you'll need to update your code to use the `NavigationView` (not the `NavigationLauncher`).  

The reason behind this is because with the `NavigationView` implementation, you're able to add a listener to hook into re-route events.  In your case, you are going to disallow re-route events and make a map-matching request to restart navigation along the new route.  

We have some documentation regarding this - I hope this helps https://www.mapbox.com/android-docs/navigation/overview/map-matching/#map-matching-with-navigationview

Thanks for checking out the SDK!

**Comment by danesfeder** [comment]
No problem @vincent-caron - unfortunately, we don't have a proven example of this, but I do believe there are a few users of the SDK doing similar logic.  

We include a suite of static `Turf` methods that can be used for calculations.  For example `TurfMisc#nearestPointOnLine(@NonNull Point pt, @NonNull List<Point> coords)` may be able to help find at which point you are closest to in that 100 point list (and then chop off the front of the list).  

I'd snoop around some of the issues like https://github.com/mapbox/mapbox-navigation-android/issues/875 or maybe open a new question on https://stackoverflow.com/questions/tagged/mapbox.
