### ISSUE TITLE
Custom navigation notification is not told when to shut down, or given a MapboxNavigation when created

### ISSUE THREAD

**Issue by cmahopper** [mapbox/mapbox-navigation-android#1282]
**Android API:** 27
**Mapbox Navigation SDK version:** 0.18

In NavigationNotificationProvider, in the method shutdown(...), the MapboxNavigationNotification is told to unregister its receiver, which shuts down the notification. This is not broadcast to a custom notification, but it could be implemented in the interface. I don't know what consequences this has, but I guess it could result in a memory leak from not unregistering the receiver. I also don't know if it sometimes could mean that the notification is not cancelled, since this is done here in the native notification.

Additionally, in buildNotificationFrom(...), a MapboxNavigation is supplied, but this is only passed to the native notification, not a custom notification. I managed to supply it to the notification after navigation is started, but it would still be nice if this was possible here, since it seems messy otherwise.

**Comment by danesfeder** [comment]
Thanks for the feedback here @cmahopper - I opened https://github.com/mapbox/mapbox-navigation-android/pull/1283 as a possible solution to this.  Do you mind taking a look / reviewing?  I'm happy to update further based on your feedback.

**Comment by cmahopper** [comment]
Hey @danesfeder, thanks for the quick reply! I'm not sure how to test this to be honest, but it looks exactly as imagined, with a method in the interface :) That fixes the first point at least; the second point is not as important, but it is another case where the MapboxNavigationNotification is handled in a special way.

**Comment by danesfeder** [comment]
> Additionally, in buildNotificationFrom(...), a MapboxNavigation is supplied, but this is only passed to the native notification, not a custom notification. I managed to supply it to the notification after navigation is started, but it would still be nice if this was possible here, since it seems messy otherwise.

No problem @cmahopper - speaking to the above, was there other data you were looking to get from `MapboxNavigation` that isn't provided by the `RouteProgress`?  Just trying to understand your use case for this, thanks!

**Comment by cmahopper** [comment]
@danesfeder I want to call stopNavigation on the MapboxNavigation, but that is the only thing I want from it. The same thing done in the native notification. Can it be done without it?

**Comment by danesfeder** [comment]
@cmahopper would you be able to use a `BroadcastReceiver` like we are in `MapboxNavigationNotification`?  

With a receiver setup like ours, I'm wondering if whenever you stop navigation or the app is destroyed, you'd unregister the receiver or do any shutdown work for the notification without the need for the callback?

**Comment by danesfeder** [comment]
I updated the repository test app in https://github.com/mapbox/mapbox-navigation-android/pull/1283/ to demonstrate what I'm saying - using the `BroadcastReceiver` to stop navigation when the notification is clicked.  Would this work for your use-case?

**Comment by cmahopper** [comment]
@danesfeder Ah yes, that is perfect, I will do that instead :)

**Comment by Guardiola31337** [comment]
Hey @cmahopper 👋 
> I will do that instead

I'm curious 😅, instead of what?
