### ISSUE TITLE
Gas stations/ Petrol pumps

### ISSUE THREAD

**Issue by rishabhsri20** [mapbox/mapbox-navigation-android#1284]
Can we show gas stations on our route?

**Comment by danesfeder** [comment]
Hey @rishabhsri20, we don't have any default "option" to enable / disable POIs such as gas stations along a route.  But you'd definitely be able to use a combination of our geocoder > https://www.mapbox.com/geocoding/ and https://www.mapbox.com/android-docs/maps/overview/annotations/#markers to draw your own gas station markers on the map we use for navigation. 

In the future, please ask questions like these on https://stackoverflow.com/questions/tagged/mapbox

Thanks, hope this helps!

**Comment by rishabhsri20** [comment]
Thanks a lot @danesfeder
