### ISSUE TITLE
As an end developer I want to choose between online and offline routing in the Navigation View

### ISSUE THREAD

**Issue by mcwhittemore** [mapbox/mapbox-navigation-android#1285]
The PR that closes this ticket should add a configuration option to the Navigation View and a new public method so the end developer can switch between online and offline routing.

The configuration option should be called something like `offlineRoutingData` and is a file path where the unpacked routing tiles are located.

The public api should be called something like `shouldRouteOffline` and will take a boolean. When `true` is passed the offline router will be used and when `false` is passed the online router will be used. Moving between offline and online should not interupt the current session but when the next routing request is made the correct routing option should be used.

**Comment by mcwhittemore** [comment]
cc @devotaaabel @danesfeder @akitchen

**Comment by akitchen** [comment]
This will get picked up after https://github.com/mapbox/mapbox-navigation-android/pull/1398 lands, which is dependent on https://github.com/mapbox/mapbox-java/issues/900 / https://github.com/mapbox/mapbox-java/pull/901

More recent discussions around field naming involving @coxchapman @kevinkreiser should also be taken into account.

/cc @taraniduncan

**Comment by devotaaabel** [comment]
Next and currently in progress is adding the ability to download tiles:
- [ ] Add APIs to mapbox-java 
- [ ] Create UI for downloading tiles

Here's the related iOS PR: https://github.com/mapbox/MapboxDirections.swift/pull/303

cc. @akitchen 

Also, on another note, did we ever come to a resolution for this:
https://github.com/mapbox/mapbox-java/pull/901
@mcwhittemore does the directions API support or plan on supporting bicycle costing options?

**Comment by akitchen** [comment]
@devotaaabel can you break this out a bit differently, perhaps into multiple PRs/tickets?

 - Add APIs to mapbox-java

similar to https://github.com/mapbox/MapboxDirections.swift/pull/303 as you mentioned. How about a new supporting ticket in mapbox-java for that?

 - UI for downloading (routing) tiles

similar to https://github.com/mapbox/mapbox-navigation-ios/pull/1803 . An example is important to have, but we don't want to block availability of the overall feature if we can avoid it. We also want to separate out the downloading of routing tiles from the consumption of them for routing, which is what this ticket is meant to be about.

**Comment by devotaaabel** [comment]
@akitchen I updated the above comment.

**Comment by danesfeder** [comment]
@devotaaabel are we still working on APIs for this work?  Or as we holding for the implementation currently used in our docs https://www.mapbox.com/android-docs/navigation/overview/offline-routing/#example-re-route-scenario-with-navigationview

**Comment by devotaaabel** [comment]
@danesfeder We are not. This was put in the icebox because the benefit did not make the complexity worth it, since there are workarounds.

**Comment by danesfeder** [comment]
Going to go ahead and close this for now, let's open a new ticket if something different is needed in the future (from the current recommendation in our docs https://github.com/mapbox/mapbox-navigation-android/issues/1285#issuecomment-451534590).
