### ISSUE TITLE
Navigation View cursor not locating on current location

### ISSUE THREAD

**Issue by priyankjain28** [mapbox/mapbox-navigation-android#1288]
**Problem Statement**
I drawn the custom route by using MapMatchingAPI. I used NavigationView to navigate user on given route.
The Problem was cursor navigator denote on the starting point of route which came from map matching api, not on my current location. Here not required reroute to draw the route i just want to denote cursor on my current location

**Android API:**
NavigationView
MapboxNavigationOptions
NavigationViewOptions

**Mapbox Navigation SDK version:**
implementation 'com.mapbox.mapboxsdk:mapbox-android-navigation:0.13.0'
implementation('com.mapbox.mapboxsdk:mapbox-android-navigation-ui:0.13.0')

### Steps to trigger behavior
 1.  MapboxNavigationOptions 
MapboxNavigationOptions mapboxNavigationOptions = MapboxNavigationOptions.builder()
                .manuallyEndNavigationUponCompletion(true)
                .enableOffRouteDetection(true)
                .build();
 2. NavigationViewOptions 
NavigationViewOptions options = NavigationViewOptions.builder()
                .navigationListener(this)
                .routeListener(this)
                .feedbackListener(this)
                .directionsRoute(currentRoute)
                .shouldSimulateRoute(false)
                .navigationOptions(mapboxNavigationOptions)
                .build();

  @Override
    public boolean allowRerouteFrom(Point offRoutePoint) {
        return false;
    }

 3. navigationView.startNavigation(options);

### Actual behavior
![screenshot_2018-09-13-15-25-21-94 1](https://user-images.githubusercontent.com/5296931/45482510-ec618d80-b76b-11e8-9d9b-ad4addb046ff.png)

### Expected Behavior
![screenshot_2018-09-13-15-25-21-94](https://user-images.githubusercontent.com/5296931/45482772-96411a00-b76c-11e8-8770-3fb165957b51.png)

**Comment by danesfeder** [comment]
Hey @priyankjain28 👋 judging from your screenshots, the SDK looks to be working as designed.  

The SDK is going to "snap" you to the closest coordinate on the route.  So if the route isn't starting at your current location, you'd have to disable snapping via `MapboxNavigationOptions` I guess until it's time to begin navigation.  

I will say, if you removed the `RouteListener`, we'd send an off-route event pretty quickly because the current location is far enough from the start of the route.  

I hope this helps a bit, thanks!

**Comment by priyankjain28** [comment]
Thanks, @danesfeder for your quick response!!
![screenshot_2018-09-14-11-02-49-24](https://user-images.githubusercontent.com/5296931/45531589-11a6d800-b80e-11e8-872e-c68ccdaa599b.png)
Problem resolved but if the user is off route at some point in that case instruction message was stuck at that particular point and speaking continuously, how to stop that.

**Comment by priyankjain28** [comment]
> Hey @priyankjain28 👋 judging from your screenshots, the SDK looks to be working as designed.
> 
> The SDK is going to "snap" you to the closest coordinate on the route. So if the route isn't starting at your current location, you'd have to disable snapping via `MapboxNavigationOptions` I guess until it's time to begin navigation.
> 
> I will say, if you removed the `RouteListener`, we'd send an off-route event pretty quickly because the current location is far enough from the start of the route.
> 
> I hope this helps a bit, thanks!

Thanks very much!! 
Problem resolved but if the user is off route at some point in that case instruction message was stuck at that particular point and speaking continuously, how to stop that.
Is there any way we can track each and every step of the user taken here.
