### ISSUE TITLE
Question: NavigationMapRoute Line

### ISSUE THREAD

**Issue by Danny-James** [mapbox/mapbox-navigation-android#1293]
I'm sorry if this has already been answered, however, I'm looking at a solution to hide the Navigation Route Line, whether this is by physically hiding it or if possible to set the opacity to `ZERO`.

The reason i would like to do this is i'm using the `MapMatching` and the Line is visually cutting corners, With the coordinates i'm passing in I've been able to plot an accurate poly line on the `NavigationView` but this means i now have two lines.

If possible i would like to hide the `NavigationMapRoute` Line but if possible to keep turn arrows visible.

Is their anything available for me to do this currently and if so could someone provide me with a code example.

Many Thanks.

**Comment by Danny-James** [comment]
#1177 I've managed to find my initial question which was closed but i never got an answer on how to implement hiding the Route Line and keeping turn arrows.

**Comment by Danny-James** [comment]
@danesfeder is their any chance of having a look into this or if possible point me in the right direction of hiding the NavigationLine? 

What I would really like to do as explained is; 

 - Hide Navigation Line
 - Keep Navigation Turn Arrows

**Comment by Danny-James** [comment]
I've tried the following `navigationView.retrieveNavigationMapboxMap().removeRoute();` but this doesn't seem to do anything.

```
private void startNavigation(DirectionsRoute directionsRoute) {
        Log.d(TAG, "StartNavigation");
        NavigationViewOptions navigationViewOptions = setupOptions(directionsRoute);
        navigationView.startNavigation(navigationViewOptions);
        navigationView.findViewById(R.id.feedbackFab).setVisibility(View.GONE);
        //navigationMapboxMap.removeRoute();

        // Create Origin and Destination Markers
        createMarkers();

        // Hide Navigation Line;
        navigationView.retrieveNavigationMapboxMap().removeRoute();
    }
```

**Comment by Danny-James** [comment]
My users are getting confused with the MapMatching Returned Line So I'd Like To Hide/Remove It.

See Below;
![screenshot_20181015-152805_route_info 1](https://user-images.githubusercontent.com/32104383/46957241-0e15a380-d08f-11e8-96aa-fe0925309d5a.jpg)

**Comment by danesfeder** [comment]
@Danny-James dug into this and cut a PR to fix https://github.com/mapbox/mapbox-navigation-android/pull/1482

**Comment by Danny-James** [comment]
@danesfeder will this allow me to hide the line but keep the turn arrows?

**Comment by danesfeder** [comment]
@Danny-James no, but the turn lanes will be incorrectly positioned as well?  We are thinking about adding turn arrow APIs in https://github.com/mapbox/mapbox-navigation-android/pull/1387 which is a larger refactor

**Comment by Danny-James** [comment]
@danesfeder surprisingly the turn arrows are actually correct when the Navigation Line cuts across roads.
