### ISSUE TITLE
WaypointNavigationActivity does not handle rotation lifecycle

### ISSUE THREAD

**Issue by danesfeder** [mapbox/mapbox-navigation-android#1295]
Capturing from https://github.com/mapbox/mapbox-navigation-android/pull/1289#pullrequestreview-155825263

The `WaypointNavigationActivity` does not currently handle rotation, always starting from the first `DirectionsRoute` fetched from the first set of coordinates.

**Comment by Guardiola31337** [comment]
This example is not available anymore.

Closing here.

cc @abhishek1508
