### ISSUE TITLE
How can I set visibility of SummaryBottomSheet and InstructionView?

### ISSUE THREAD

**Issue by zeallat** [mapbox/mapbox-navigation-android#1301]
I want to create custom SummaryBottomSheet and InstructionView, but it seems no features are provide for this. So I want to hide original SummaryBottomSheet and InstructionView and generate other.

How can I set visibility(especially View.GONE) of SummaryBottomSheet and InstructionView?
Many thanks for read this issue.

**Comment by Guardiola31337** [comment]
Hey @zeallat 👋 Thanks for your question.

This is being tracked in #634 and we're actively working on it to make it happen in https://github.com/mapbox/mapbox-navigation-android/pull/1251

For now you can workaround it as suggested in https://github.com/mapbox/mapbox-navigation-android/issues/634#issuecomment-403847843 but stay tuned because we're going to release a new version including #1251 next week.

Closing here as duplicate.

Let us know if you have any other feature requests or if you find any bugs.

**Comment by Guardiola31337** [comment]
cc @devotaaabel who is actively working on that PR

**Comment by Guardiola31337** [comment]
@zeallat 
> What I intend to do is set visibility View.GONE for whole SummaryBottomSheet and InstructionView and I don't think #1251 make this possible.

Yeah, you're right here. My idea was to add those missing options as part of #1251 

Is it feasible @devotaaabel? If not, yeah we should re-open here and fix OP in a different PR. What do you think @devotaaabel?

Going to comment in #1251

**Comment by Guardiola31337** [comment]
Hey @zeallat after thinking about this deeper and discussing internally, we believe that we don't need to add support for the use case you described. Basically, if you want to "remove" `SummaryBottomSheet` and `InstructionView` completely, what's the purpose of using `NavigationView` at all? The point here is that if we just add the option to hide the instruction view (for example), it's still going to be doing all the updating and everything in the background (which doesn't make any sense).

We guess that the best approach for your use case is to build your custom components up using the “core” module capabilities. For reference, to get an idea on how to implement that "custom" experience, you can 👀 [`ComponentNavigationActivity`](https://github.com/mapbox/mapbox-navigation-android/blob/master/app/src/main/java/com/mapbox/services/android/navigation/testapp/activity/navigationui/ComponentNavigationActivity.java) which showcases `MapboxNavigation` setup / updating an `InstructionView` + `NavigationMapboxMap`. Does that make sense? Am I missing something? 

Hope this helps. Please let us know if you find any other bugs and thanks for checking out the SDK!

cc @devotaaabel
