### ISSUE TITLE
Release v0.19.0

### ISSUE THREAD

**Issue by devotaaabel** [mapbox/mapbox-navigation-android#1304]
### Release checklist @devotaaabel

- [x] Run through testapp/demo app and test all activities
- [x] Change version name to `0.19.0` in `gradle.properties`
- [x] Publish `0.19.0` artifact to Maven Central
- [x] Change version name back to `0.20.0-SNAPSHOT`
- [x] Update `CHANGELOG.md`
- [x] Tag `v0.19.0` in GitHub

### Post-release @langsmith 
- [x] Update `README.md`
- [x] Update `constants.js` file in `android-docs` repo
- [x] Generate `navigation` and `navigation-ui` javadocs and add to `android-docs` repo
- [x] Update https://www.mapbox.com/help/android-navigation-sdk/ 
  - @colleenmcginnis should be good on this one 👍 
- [x] Update config files in /help repo _after_ tutorial (☝️) update is finished.

/cc: @mapbox/navigation

**Comment by langsmith** [comment]
All done on my end @devotaaabel 🎉
