### ISSUE TITLE
Puck move ahead of actual location on turns

### ISSUE THREAD

**Issue by navdeepg** [mapbox/mapbox-navigation-android#1314]
I’ve noticed that sometime puck is moving ahead of actual current location. 
For example if driver is on intersection, puck auto moves to next point after intersection. If driver follows a different route after intersection then puck goes back to new route after navigation triggers reroute event.  But in meantime onProgressChanged callback triggers new location as puck was ahead of actual position. 
You can see image wrong_point_reroute.png for this. Dark blue line shows points provided by onProgressChange listener. Here driver is actually moving from left to right in straight line, but puck moved left on previous route. Where actually driver never went on that route and moved straight and reroute evnt triggered. You can see new route started on same path in light blue color. Is there any way we can avoid this.
![wrong_point_reroute](https://user-images.githubusercontent.com/17833396/46044762-86acc400-c0d0-11e8-967a-b2fe9edf0227.png)

**Comment by danesfeder** [comment]
Hey @navdeepg 👋 do you mind re-testing with `0.20.0` here?  

We made some significant changes to our route-following logic that should help with the issue you're seeing here.  Please report back and we can troubleshoot as needed.  

cc @kevinkreiser

**Comment by navdeepg** [comment]
Sure Dan, I’ll update the latest version and run a test trip. Will let you know the results once I am done with it.

Thanks,
Navdeep

**Comment by danesfeder** [comment]
@navdeepg any updates on testing here?  Thanks!

**Comment by danesfeder** [comment]
@navdeepg this should be resolved with our latest version `0.22.0`.  If you're still able to reproduce.  Please feel free to re-open this issue, thanks!
