### ISSUE TITLE
UX improvement for example activity

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-navigation-android#1330]
We launch the mapview at LatLng=0,0 and zoom 0, once we get a location fix we animate to that position. For me this results into a UX of flying over water until I see my actual location. To improve this UX I'm suggesting the following flow:
 - decouple requesting location permissions in a separate splash activity
 - if granted, request last know location 
 - provide this location data to the ExampleActivity through an Intent
 - startup the MapView with camera position set to this location and eg. zoomlevel = 12
 - request location updates and once you receive an initial fix, zoom in a bit more eg. zoomlevel = 16

cc @danesfeder

**Comment by Guardiola31337** [comment]
This example is not available anymore.

Closing here.

cc @abhishek1508
