### ISSUE TITLE
Invaid reroute on intersection and traffic congestions

### ISSUE THREAD

**Issue by navdeepg** [mapbox/mapbox-navigation-android#1338]
Navigation triggers invalid reroute when driver is waiting on intersection. I've attached the video where navigation triggered reroute as U turn, where driver was not moving at all. Puck seemed to go reverse a little and then reroute triggered. Where it corrected itself when i driver started moving and crossed the intersection. You can check all this in attached video. 
Android API: 27
Mapbox navigation sdk: 0.19.0

Steps to trigger behavior:
Start a real trip and if driver is stuck on intersection waiting for traffic light, wrong reroute gets triggered.
[reroute_error_new.zip](https://github.com/mapbox/mapbox-navigation-android/files/2425321/reroute_error_new.zip)

### Expected behavior
Navigation should not trigger wrong reroute on intersection and traffic congestions.

Also let me know how we can dynamically change time and distance for reroute event to get triggered.

**Comment by danesfeder** [comment]
@navdeepg would you mind testing again with `0.20.0`?  A lot of our underlying route-following logic has been updated.  Thanks!
