### ISSUE TITLE
Add better review process inside CI

### ISSUE THREAD

**Issue by cammace** [mapbox/mapbox-navigation-android#134]
As part of the circle ci transition, I'd like to implement some of the suggestions inside [this article](https://medium.com/square-corner-blog/surfacing-hidden-change-to-pull-requests-6a371266e479) to assist in the review process. Highly recommend reading it @mapbox/android.

**Comment by zugaldia** [comment]
Love it - and it'd definitely apply to other projects too.

**Comment by Guardiola31337** [comment]
cc @RingerJK

**Comment by Guardiola31337** [comment]
@mapbox/navigation-android Is there anything from OP we'd like to add to the current process? If we're OK with what we have at the moment, let's close here and re-open / create a new ticket in the future.

**Comment by zugaldia** [comment]
OP is not very actionable - I suggest we close this ticket and open separate tickets for concrete actions.
