### ISSUE TITLE
Coordinate is invalid

### ISSUE THREAD

**Issue by pmsferreira** [mapbox/mapbox-navigation-android#1341]
Hello!

I have probably the craziest error until today.
I add this library into my project and works just fine... on emulator.
In real device don't work, because I get this error:
 "**message":"Coordinate is invalid: -9,201676,38,662510","code":"…]**"

But I sent the waypoint origin and destination values correctly:

- Waypoint origin = new Waypoint(userLatLng.longitude, userLatLng.latitude);
- Waypoint destination = new Waypoint(latLng.longitude, latLng.latitude);

![screen shot 2018-09-28 at 15 58 17](https://user-images.githubusercontent.com/16557512/46216380-5adf4780-c337-11e8-81b3-209cfdf1b574.png)

I don't why but this only happens in real device. On emulator works just fine.

Best regards,
Pedro Ferreira

**Comment by pmsferreira** [comment]
Resolved!

**Comment by DeveloperLifestylehearing** [comment]
How did you resolved it as I am getting same issue?

**Comment by pmsferreira** [comment]
> How did you resolved it as I am getting same issue?

I don't remember but I think that a library update resolved this.
