### ISSUE TITLE
Navigation Launcher mute button doesn't work

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-navigation-android#1350]
While testing out 772ea4a with #1348. the onscreen mute button isn't muting the navigation sound.

**Comment by Guardiola31337** [comment]
I was able to reproduce when testing / running [`ComponentNavigationActivity`](https://github.com/mapbox/mapbox-navigation-android/blob/master/app/src/main/java/com/mapbox/services/android/navigation/testapp/activity/navigationui/ComponentNavigationActivity.java) from the test app.

Reopening.

cc @danesfeder

**Comment by danesfeder** [comment]
`ComponentNavigationActivity` should not have any buttons showing by default now in the `InstructionView`
