### ISSUE TITLE
MapMatching API Question - Android

### ISSUE THREAD

**Issue by Danny-James** [mapbox/mapbox-navigation-android#1378]
I am in need of some help in regards to the MapMatching API, I understand you can pass in a Maximum of 100 Coordinates per request, this is fine, All my routes have much more than 100 Coordinates which is fine as i then call 

```java
fetchRoute(List<Point> coordinates, boolean showProgress, boolean routeFromCurrentLocation) 
```

Each time this is called and a route is returned i remove 100 coordinates from my Master List, so when the `onArrival();` event is triggered I check to see if the master list still has coordinates to be routed if so, re call `fetchRoute();` and so on.

However, with this i've come across some routes where the last coordinate in the route lands on a Intersection or Traffic Island which is then not giving correct voice instructions.

What i would like to do is still pass in 100 coordinates but reroute when the user arrives at coordinate 90 of the plotted route, i will then remove those 90 from the master list and pass in an additional 90 coordinates.

However, i'm not able to see anything which will tell me when the user has reached the 90th Coordinate passed into the MapMatching API.

**Comment by Danny-James** [comment]
@danpat so is their no way of knowing when the user has reached the 90th coordinate in the navigation?

What are the maximum requests if i signup for the enterprise on average our KML files contain around 1500 coordinates.

**Comment by Danny-James** [comment]
@danpat I'm not to bothered about the distance/time as i'm not showing the bottom banner, i'm only showing the top banner which shows turn icons and street names etc.

So i believe if i know when the user reaches the 90th coordinate or what ever i choose to set as the fetch next lot of coordinates i will be able to workaround the issue where a set of 100 coordinates lands on a intersection or traffic island.

**Comment by danpat** [comment]
@Danny-James You'd have to do some of the math there yourself.  I believe the Android SDK has `durationRemaining` and `distanceRemaining` properties on the route you're following.  You can do some calculations on your original data to figure out the point where your 90th coordinate resides, the compare to the progress updates from the SDK itself.

Maximum limits for Enterprise accounts can be negotiated.  1500 coords is definitely something we can technically do, but I'm just a lowly engineer, I don't actually know how much our sales folks would try to charge for that capability.

**Comment by Danny-James** [comment]
I will look at doing some calculations with disatance remaining as this seems to be the only option here, i did try adding an additional Waypoint into the request but this basically causes the same problem.

@danpat I don't know whether you could help with the NavigationMap Route Line, i plot a Polyline on the map of the whole route (1500 coordinates) when i run the navigation i get a darker blue line for the 100 coordinates.

This darker blue line i believe is the NavigationMapRoute, this line also contains Turn arrows which i would like to keep however i would like to hide the NavigationMapRoute.

I do have an issue open but don't seem to have had a response for some time. #1293

**Comment by danpat** [comment]
@Danny-James Sorry - I don't know that much about the Nav SDK itself - I work primarily on the backend algorithms related to routing and matching - UI stuff is not my forté.

Can this ticket be closed?

**Comment by Danny-James** [comment]
@danpat yes go ahead and close this ticket, my plan of action is to have a variable of which Coordinate i want to initiate the new route fetch `varX`.

I will then calculate the distance from the Last Coordinate in the map matching to the `varX` when the users `remainingDistance` lands within `X` distance force a refetch.

Thanks, for your input on this @danpat
