### ISSUE TITLE
Failed to resolve: com.mapbox.navigator:mapbox-navigation-native:3.1.3

### ISSUE THREAD

**Issue by Kahtaf** [mapbox/mapbox-navigation-android#1381]
Hello, 

My gradle build is failing to sync with the following dependencies: 

```
implementation 'com.mapbox.mapboxsdk:mapbox-android-sdk:6.5.0@aar'
implementation 'com.mapbox.mapboxsdk:mapbox-android-navigation:0.20.0'
implementation 'com.mapbox.mapboxsdk:mapbox-android-plugin-locationlayer:0.9.0'
```

The error is: `Failed to resolve: com.mapbox.navigator:mapbox-navigation-native:3.1.3`. I have mavenCentral() in my repositories, however I can't find the mapbox-navigation-native package in maven central. Do I need to add another repository? Or has the artifact not been published to maven central yet? 

Let me know if you need any more information, thanks!

**Comment by typebrook** [comment]
have the same issue, just following the tutorial in https://www.mapbox.com/help/android-navigation-sdk/

```
 implementation('com.mapbox.mapboxsdk:mapbox-android-sdk:6.5.0@aar') {
        transitive = true
 }
implementation('com.mapbox.mapboxsdk:mapbox-sdk-services:4.0.0')
implementation 'com.mapbox.mapboxsdk:mapbox-android-navigation:0.20.0'
implementation ('com.mapbox.mapboxsdk:mapbox-android-navigation-ui:0.20.0') {
       transitive = true
}
```

**Comment by Guardiola31337** [comment]
As noted in [`v0.20.0` release notes](https://github.com/mapbox/mapbox-navigation-android/releases/tag/v0.20.0)

> **Important Note**: With this release, you _must_ include the following snippet in your project’s `build.gradle`:
>```
>repositories {
>    maven { url 'https://mapbox.bintray.com/mapbox' }
>}
>```
>
>This will ensure the `mapbox` dependency is properly downloaded.  We will be adding a snippet regarding this in the repo `README` and in Android docs site as well. 

Thanks for checking out the SDK @Kahtaf and @typebrook 🙏 

Closing as answered.

**Comment by Hashir524** [comment]
Still Not Working.
repositories {
        google()
        jcenter()
        maven { url 'https://mapbox.bintray.com/mapbox' }
    }
dependencies
   implementation 'com.mapbox.mapboxsdk:mapbox-android-sdk:6.5.0'
    implementation 'com.mapbox.mapboxsdk:mapbox-android-plugin-locationlayer:0.8.2'
    implementation 'com.mapbox.mapboxsdk:mapbox-android-navigation:0.20.0'
    implementation ('com.mapbox.mapboxsdk:mapbox-android-navigation-ui:0.20.0'){
        transitive = true
    }

**Comment by danesfeder** [comment]
@Hashir524 full example, please make sure it's in the right spot:

```
buildscript {
    repositories {
        google()
        mavenCentral()
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.2.0'
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
        jcenter()
        maven { url 'https://mapbox.bintray.com/mapbox' }
    }
}
```

**Comment by didiramzi** [comment]
Thank you @danesfeder for the full example it works for me, indeed following the official tutorial I put `maven {url 'https://mapbox.bintray.com/mapbox'}` in the `buildscript` section and moving it in the `allprojects` section all works well.

**Comment by Guardiola31337** [comment]
Glad to hear @didiramzi Thanks for the update!

**Comment by syiam** [comment]
@Guardiola31337 Hi its not working for me even If I put in the repository as you described

**Comment by andrewharvey** [comment]
Ran into the same problem, fixed by .https://github.com/mapbox/mapbox-navigation-android/issues/1381#issuecomment-428654714

Ideally the tutorial at https://docs.mapbox.com/help/tutorials/android-navigation-sdk/#install-the-navigation-sdk could be updated to be a bit clearer on where the lines need to go.

**Comment by danesfeder** [comment]
Hey @andrewharvey 👋 thanks for the feedback.  Do you mean with regard to `buildscript` vs. `allprojects` with the bintray URL placement?

**Comment by andrewharvey** [comment]
Yeah, with regards to placing the line in `allprojects` instead of `buildscript` at https://docs.mapbox.com/help/tutorials/android-navigation-sdk/#install-the-navigation-sdk.

When you create a new project in Android Studio you get two build.gradle files (one for the Project, and one for the Module) so for someone completely new to Android development it's unclear which one to place these lines into, and then if it goes into the repositories section in buildscript or allprojects.

**Comment by danesfeder** [comment]
@andrewharvey totally, thanks for clarifying!  I just opened a documentation PR to address this https://github.com/mapbox/android-docs/pull/906.

**Comment by andrewharvey** [comment]
Thanks, I didn't realise the docs were open source!

**Comment by radeshf** [comment]
i have same problem and by adding mapbox maven into allproject in build.gradle project level problem solved.

`allprojects {
    repositories {
        google()
        jcenter()
        maven { url 'https://mapbox.bintray.com/mapbox' } //add this line
    }
}`

**Comment by saddahussain** [comment]
Yes, it does fix the issue.

**Comment by Wesleywie** [comment]
> @Hashir524 full example, please make sure it's in the right spot:
> 
> ```
> buildscript {
>     repositories {
>         google()
>         mavenCentral()
>         jcenter()
>     }
>     dependencies {
>         classpath 'com.android.tools.build:gradle:3.2.0'
>     }
> }
> 
> allprojects {
>     repositories {
>         google()
>         mavenCentral()
>         jcenter()
>         maven { url 'https://mapbox.bintray.com/mapbox' }
>     }
> }
> ```

THANK YOU OMG!!!!

**Comment by Kay-Hen** [comment]
Hi 
 i am also having the same error even after checking different threads.

**No cached version of com.mapbox.navigator:mapbox-navigation-native:7.0.0 available for offline mode.**

This is the error I keep getting. Can anyone help??

**Comment by minhaj5693** [comment]
Hi,
I am using

**Comment by Ohior** [comment]
Remove every navigation dependencies, solved the issues for me
```
implementation 'com.mapbox.mapboxsdk:mapbox-android-navigation-ui:0.26.0'
implementation 'com.mapbox.mapboxsdk:mapbox-android-navigation:0.26.0'
```
All you need to do is use  `    implementation ('com.mapbox.mapboxsdk:mapbox-android-sdk:<version>')`

**Comment by ehtshamaziz** [comment]
> Remove every navigation dependencies, solved the issues for me
> 
> ```
> implementation 'com.mapbox.mapboxsdk:mapbox-android-navigation-ui:0.26.0'
> implementation 'com.mapbox.mapboxsdk:mapbox-android-navigation:0.26.0'
> ```
> 
> All you need to do is use ` implementation ('com.mapbox.mapboxsdk:mapbox-android-sdk:<version>')`



> Remove every navigation dependencies, solved the issues for me
> 
> ```
> implementation 'com.mapbox.mapboxsdk:mapbox-android-navigation-ui:0.26.0'
> implementation 'com.mapbox.mapboxsdk:mapbox-android-navigation:0.26.0'
> ```
> 
> All you need to do is use ` implementation ('com.mapbox.mapboxsdk:mapbox-android-sdk:<version>')`

for navigation u need navigation dependency to implement map box navigation
I am still having the problem when i import any navigation dependency
Only the following dependency work for me:
    implementation 'com.mapbox.mapboxsdk:mapbox-android-sdk:9.2.1'
