### ISSUE TITLE
navigationView.onStart() causes progressChangedListener to be overriden 

### ISSUE THREAD

**Issue by hurrba** [mapbox/mapbox-navigation-android#1385]
**Mapbox Navigation SDK version: 0.20.0**

Calling `navigationView.onStart()` in your activity will override any logic in your custom `progressChangedListener` when leaving/re-entering the app. 
This is because at the end of the call-chain, you add a default `progressChangedListener` to the `MapboxNavigation` object. 

### Steps to trigger behavior

 1. Init navigation with a custom `progressChangedListener` that sets `bearing` and `tilt` to `0`.
 2. Start navigation
 3. Leave/minimize app 
 4. Enter app again

### Expected behavior
`bearing` and `tilt` should always be set to `0`

### Actual behavior
`bearing` and `tilt` are set according to the default listener: `NavigationCamera.progressChangeListener`

**Comment by danesfeder** [comment]
Hey @hurrba, are you speaking to the camera behavior you're seeing with `NavigationView`?  By default, we provide a [`DynamicCamera`](https://github.com/mapbox/mapbox-navigation-android/blob/master/libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/camera/DynamicCamera.java), but you can provide your own `CameraEngine` > see here https://www.mapbox.com/android-docs/navigation/overview/camera/ that modifies the existing camera behavior (which I believe is what you're trying to do).

If you want to stop our camera changes altogether you can stop tracking with [`NavigationView#retrieveMap#updateCameraTrackingEnabled(false)`](https://github.com/mapbox/mapbox-navigation-android/blob/master/libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/map/NavigationMapboxMap.java#L297).

Let us know if this helps - a code snippet would help us out here as well and get a better idea of the issue you're facing . Thanks!

**Comment by hurrba** [comment]
@danesfeder 
yes I know, I've gotten it to work the way I want now, but it took a while to figure out what was going on since both `progressChangedListeners` were running. 

The point with this issue was to make you aware that you have some undocumented side-effects in the lifecycle callbacks. It should either be made very explicit that you add a default listener in the `onStart` method or, preferably, not be there at all if you have set your own listener. your listener will always be called as the last one, which is what causes the unexpected behavior.

**Comment by danesfeder** [comment]
@hurrba okay I think I'm following - you're saying the listener we add [here](https://github.com/mapbox/mapbox-navigation-android/blob/master/libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/map/NavigationMapboxMap.java#L395) is causing the camera to start updating again based on progress, before you'd like it to (before your listener)?

**Comment by hurrba** [comment]
no it's actually being run **after** my own listener. When starting the navigation [this](https://github.com/mapbox/mapbox-navigation-android/blob/master/libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/NavigationViewEventDispatcher.java#L45) is called to set the `progressListener` based on the passed `NavigationViewOptions`. Since `NavigationEventDispatcher.progressChangeListeners` is just a list of listeners that are processed in order, the listener you add will always be the last one. So even though my own listener is called on changes, your listener will override any logic in my own listener. 

does it make sense?

**Comment by hurrba** [comment]
@danesfeder any updates on this?

**Comment by danesfeder** [comment]
Hey @hurrba sorry for the delay here - I definitely see the problem as far as order of listeners.  We are thinking about a suitable solution for this.  Re-ordering the listeners on our side seems like it could introduce further unexpected behavior in different lifecycle scenarios, so we are trying to think of something that fits.  If you have any ideas / suggestions, please feel free to drop them here.

**Comment by danesfeder** [comment]
@hurrba I just opened https://github.com/mapbox/mapbox-navigation-android/pull/1473, please take a look at the changes in that PR and let me know what you think.  I'm wondering if accounting for the centering behavior during rotation helps fix this.  

Would it be possible to post a gif of the behavior described in this ticket?  I want to make sure as we debug this that we are addressing your issue completely here. Thanks!

**Comment by Guardiola31337** [comment]
Hey @hurrba 👋 #1473 landed. Would you mind testing with `0.23.0-SNAPSHOT` and report back if it solves OP? Thanks in advance!

**Comment by hurrba** [comment]
@Guardiola31337 thanks! quickly re-tested, and still works :+1:

**Comment by Guardiola31337** [comment]
Awesome! Thanks for confirming @hurrba 🙇 

Closing as solved.
