### ISSUE TITLE
Navigation Text Size

### ISSUE THREAD

**Issue by monikarora** [mapbox/mapbox-navigation-android#1389]
Hey guys , Please let me know how to change street line text size & text color 

![device-2018-10-04-142139](https://user-images.githubusercontent.com/17878500/46463915-bd768e80-c7e2-11e8-8c60-cbca97e8a8f1.jpg)

Navigation xml : 

<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    xmlns:app="http://schemas.android.com/apk/res-auto">
<com.mapbox.services.android.navigation.ui.v5.NavigationView
    android:id="@+id/navigation"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    app:navigationLightTheme="@style/NavigationViewLight"
    app:navigationDarkTheme="@style/NavigationViewDark"/>

</RelativeLayout>

Thanks!

**Comment by danesfeder** [comment]
Hey @monikarora 👋 the size and style of the text is determined by the provided map style URL ([see default here pictured in your screenshot](https://github.com/mapbox/mapbox-navigation-android/blob/master/libandroid-navigation-ui/src/main/res/values/styles.xml#L44)).  

If you'd like to make updates to the style, you can customize your own style with [Mapbox Studio](https://www.mapbox.com/mapbox-studio/) and then provide your custom style URL to the navigation SDK.  

Hope this helps!  Thanks for checking out the SDK.

**Comment by monikarora** [comment]
Hey @danesfeder  mapbox provide golf type ?
