### ISSUE TITLE
Change audio instruction language runtime.

### ISSUE THREAD

**Issue by Xgamefactory** [mapbox/mapbox-navigation-android#1390]
How to change language voice during navigation process ?
When using Heremaps sdk we could switch language after navigation has been started.

Currently the only way is to restart navigation rebuilding **NavigationRoute**.

**Comment by danesfeder** [comment]
Hey @Xgamefactory 👋

> Currently the only way is to restart navigation rebuilding NavigationRoute.

You're correct here - voice instructions (provided via [OSRMTI](https://github.com/Project-OSRM/osrm-text-instructions)) are given to the SDK via the `DirectionsRoute` passed through `MapboxNavigation#startNavigation`, we you need to re-retrieve a route with the updated language.  

I will note, you should be able to do this pretty seamlessly, as `MapboxNavigation` and the `NavigationView` accept routes _while_ navigating.  

Going to close here as non-actionable on our part, but feel free to follow up with questions.

**Comment by Xgamefactory** [comment]
ok. thanks !
