### ISSUE TITLE
License of closed source library libandroid-navigation

### ISSUE THREAD

**Issue by karussell** [mapbox/mapbox-navigation-android#1391]
Thanks a lot @danesfeder & others for pushing forward such an amazing open source library. We (as GraphHopper) appreciate that Mapbox invests into the open source community.

Now that the libandroid-navigation is merged into master this creates uncertainty regarding trust and license. What is the license of the closed source library and which (distribution etc) rights does one have? What actually does it do? Does it use the internet or "just" for offline purposes.

Why not add this library for commercial distribution later in the pipeline and use an open source replacement with the functionality from before the merge of this library? 

I'm not saying that you should open source this library. Furthermore we are open to contributions. (already contributed some tiny things like #1108)

What can we do that you re-evaluate your current strategy :) ?

Initially asked at #1265

**Comment by danesfeder** [comment]
Hey @karussell 👋sorry for the delayed response here. 

> What actually does it do? Does it use the internet or "just" for offline purposes.

The shared `Navigator` library and functionality added in #1265 serves to bring many improvements to our core routing / processing logic.  Its core functionality is written in `C++` similar to our Maps SDK, which provides major performance enhancements.  

Outside of performance and reliability, it makes it much easier to align platforms (iOS v. Android for example), where previously we were in a constant state of flux for platform parity.  @mcwhittemore outlined a similar explanation in https://github.com/mapbox/mapbox-navigation-android/pull/1265#issuecomment-424387187.

I hope this helps provide some context into the benefits of this library.

**Comment by karussell** [comment]
Thanks for the answer. I understand the intent. Is the library using the internet or does it collect data that is then send over the internet?

What about the usage and distribution license? And would you accept contributions to make the library optional?

**Comment by karussell** [comment]
Oh, wow. Really unexpected and unusual way for a repository on Github and especially for Mapbox. Not unrightful, please don't get me wrong, but hugely disappointed. Time for an open source fork. Please do not trick anyone again with such a pseudo open source philosophy to invest time in your work.
