### ISSUE TITLE
In Nougat devices cannot detect current location

### ISSUE THREAD

**Issue by shrutiWV** [mapbox/mapbox-navigation-android#1399]
hey ! i am facing some trouble getting user current location in nougat & marshmallow devices where as it is working fine below of it. also in marshmallow and above device crashes due to mapbox it uses upto  62% of CPU.

 implementation 'com.mapbox.mapboxsdk:mapbox-android-navigation:0.20.0'
 implementation 'com.mapbox.mapboxsdk:mapbox-android-navigation-ui:0.20.0'

**Comment by shrutiWV** [comment]
i don't know how but now it is working fine. now it is giving me my current location with same code that was not giving me before

**Comment by Guardiola31337** [comment]
Awesome! Glad to hear @shrutiWV 

Thanks for the update.

Closing.
