### ISSUE TITLE
Custom "sub"-value of a BannerInstruction gets ignored

### ISSUE THREAD

**Issue by Gadda27** [mapbox/mapbox-navigation-android#1416]
**Android API:**
**Mapbox Navigation SDK version:**

### Steps to trigger behavior

I changed the "sub"-value of a Mapbox Directions API response which should be responsible for extra info below the primary banner. 

### Expected behavior
A customized sub-info should display what and when I tell it to display
### Actual behavior
Somehow the info is ignored and overwritten and the sub-info-box only shows when the next step is a short one e.g (as explained in the [documentation](https://www.mapbox.com/android-docs/api/mapbox-java/libjava-services/4.0.0/com/mapbox/api/directions/v5/models/BannerInstructions.html#sub--))

_Sample Code of BannerInstructions with sub-info that is ignored:_

`bannerInstructions": [
{
"distanceAlongGeometry": 1317.175,
"primary": {
"text": "East 8th Street",
"type": "text",
"modifier": "right",
"components": [
{
"text": "East 8th Street",
"type": "text"
}
]
},
"sub": {
"text": "Sample Text",
"type": "text",
"modifier": "right",
"components": [
{
"text": "Sample Text",
"type": "text"
}
]
}
}
]
}`

**Comment by Guardiola31337** [comment]
Hey @Gadda27 👋 thanks for reaching out and report your issue.

Could you add some more information about the Mapbox Navigation SDK version used here? This will give us better insight into your implementation and what could be causing your problem.

**Comment by danesfeder** [comment]
Hey @Gadda27 👋 as of `0.21.0`, the `InstructionView` was not considering the `sub()` `BannerText` and we were creating the data in our own models.  

But the good news is https://github.com/mapbox/mapbox-navigation-android/pull/1408 just landed that should fix your issue here.  Do you mind retesting with `0.22.0-SNAPSHOT`?  This will be in the next release.  Thanks!

**Comment by danesfeder** [comment]
Going to go ahead and close here as resolved - please feel free to re-open if you still find issue with this.  Thanks!

**Comment by Guardiola31337** [comment]
Hey @Gadda27 👋 friendly reminder that [`0.22.0`](https://github.com/mapbox/mapbox-navigation-android/releases/tag/v0.22.0) version of the SDK was released yesterday 🎉 

Thanks for bringing this to us!
