### ISSUE TITLE
NavigationView cursor is not centered 

### ISSUE THREAD

**Issue by hussi1** [mapbox/mapbox-navigation-android#1419]
I am using NavigationView inside a fragment, Navigation cursor inside NavigationView is aligned to top. Is there any way i can move that cursor to center of window or adjust its position programmatically. 

![cursor](https://user-images.githubusercontent.com/17702218/46956147-00bbe180-d0ae-11e8-9075-af704791789f.png)

**Android API: 27**
**Mapbox Navigation SDK version: com.mapbox.mapboxsdk:mapbox-android-navigation-ui:0.18.0**

### Steps to trigger behavior

 1. Add NavigationView in fragment

### Expected behavior
Cursor should be in center

### Actual behavior
Cursor is aligned to top

**Comment by danesfeder** [comment]
Hey @hussi1 👋 you'd be able to adjust this with `NavigationView#retrieveNavigationMapboxMap()#retrieveMap()#setPadding()`.   You can adjust the top padding of the map to determine where the cursor is placed.  You can also cache our calculated padding with ``NavigationView#retrieveNavigationMapboxMap()#retrieveMap()#getPadding()` prior to setting it to something else (so it can be reset once the `View` is expanded or something.  

Hope this helps, thanks for checking out the SDK!

**Comment by hussi1** [comment]
Just tried setting top padding to 1300, Still no effect on cursor
