### ISSUE TITLE
Create reroute Milestone

### ISSUE THREAD

**Issue by cammace** [mapbox/mapbox-navigation-android#142]
Currently, no announcement happens when a reroute occurs.

**Comment by ericrwolfe** [comment]
Is this something that's compatible with the concept of milestones since they're predictive?

Do we need a separate reroute announcement after a reroute occurs, or should we rather reuse the departure step of the new route?

**Comment by cammace** [comment]
Stale, closing since you can now just listen to the off route listener and force an announcement when rerouting if desired.
