### ISSUE TITLE
Just tried setting top padding to 1300, Still no effect on cursor @danesfeder

### ISSUE THREAD

**Issue by hussi1** [mapbox/mapbox-navigation-android#1420]
_Originally posted by @hussi1 in https://github.com/mapbox/mapbox-navigation-android/issues/1419#issuecomment-429895639_

**Comment by Guardiola31337** [comment]
Please @hussi1 👀 the issue tracker before opening new issues 🙏 

This is duplicate of https://github.com/mapbox/mapbox-navigation-android/issues/1419 and https://github.com/mapbox/mapbox-navigation-android/issues/1421

Closing.
