### ISSUE TITLE
No resource found that matches the given name (at 'layout_anchor' with value '@id/summaryBottomSheet

### ISSUE THREAD

**Issue by Xgamefactory** [mapbox/mapbox-navigation-android#1424]
Hi
we have apk build error

Do you have any idea 

`mapbox-android-navigation-ui-0.21.0-res\layout\navigation_view_layout.xml:25: error: Error: No resource found that matches the given name (at 'layout_anchor' with value '@id/summaryBottomSheet').`

SummaryBottomSheet class already exists in ui sdk 
```

 <com.mapbox.services.android.navigation.ui.v5.summary.SummaryBottomSheet
        android:id="@+id/summaryBottomSheet"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        app:layout_behavior="android.support.design.widget.BottomSheetBehavior"/>
```

**Comment by danesfeder** [comment]
Hey @Xgamefactory 👋 are you using the `SummaryBottomSheet` outside of the `NavigationView`?

**Comment by Xgamefactory** [comment]
no i am just trying to build with simple examples.

this code block is from ui sdk layout **navigation_view_layout.xml**

 ```
<com.mapbox.services.android.navigation.ui.v5.summary.SummaryBottomSheet
        android:id="@+id/summaryBottomSheet"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        app:layout_behavior="android.support.design.widget.BottomSheetBehavior"/>
```

**Comment by Xgamefactory** [comment]
after swapping order RecenterButton with SummaryBottomSheet inside navigation_view_layout.xml
the error gone.

  ```
 <com.mapbox.services.android.navigation.ui.v5.summary.SummaryBottomSheet
        android:id="@+id/summaryBottomSheet"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        app:layout_behavior="android.support.design.widget.BottomSheetBehavior"/>    

    <com.mapbox.services.android.navigation.ui.v5.RecenterButton
        android:id="@+id/recenterBtn"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_gravity="top"
        android:layout_margin="16dp"
        android:visibility="invisible"
        app:layout_anchor="@id/summaryBottomSheet"
        app:layout_anchorGravity="top|left"/>
```

**Comment by danesfeder** [comment]
@Xgamefactory can you point to the example code so we can fix this?  Thanks!

**Comment by Xgamefactory** [comment]
what example code  ?
this is apk build error and this error has gone after swapping elements inside layout see above example.
RecenterButton should be defined after element that it referenced via   app:layout_anchor="@id/summaryBottomSheet"
