### ISSUE TITLE
please provide example with only navigation sdk (without navigation ui)

### ISSUE THREAD

**Issue by Xgamefactory** [mapbox/mapbox-navigation-android#1430]
Hi
if it is possible to achieve turn by turn navigation with just navigation sdk wihout using NavigationView which part of navigation ui sdk, please provide an example.

**Comment by Xgamefactory** [comment]
at least instructions how to change transform center point of NavigationCamera to bottom aligned not center. we did not found any transform center property or methods. for mapview mapboxmap of NavigationCamera class.

**Comment by Guardiola31337** [comment]
Hi @Xgamefactory 👋 thanks for reaching out and report your question.

Yeah, it's definitely possible. You can use the `mapbox-android-navigation` core module 👀 https://www.mapbox.com/android-docs/navigation/overview/#install-the-navigation-sdk for further details. Also you can check the [`RerouteActivity`](https://github.com/mapbox/mapbox-navigation-android/blob/master/app/src/main/java/com/mapbox/services/android/navigation/testapp/activity/RerouteActivity.java) example from the test app - removing the `InstructionView` UI component from it makes it a good example on how to use the core module to get turn by turn navigation without the UI SDK.

Hope this helps a bit.

In any case, this issue tracker is only for bug reports with test cases and feature requests. In the future, please direct these kind of questions to https://stackoverflow.com/questions/tagged/mapbox. We keep an eye on those questions as well and it helps bring visibility to other developers that may be facing similar issues. Thanks again!
