### ISSUE TITLE
Use @CameraMode.Mode instead of @NavigationCamera.TrackingMode

### ISSUE THREAD

**Issue by Guardiola31337** [mapbox/mapbox-navigation-android#1431]
Follow up ticket from https://github.com/mapbox/mapbox-navigation-android/pull/1373#issuecomment-428525554

> @Guardiola31337 
> Also, while debugging this I noticed that [`NavigationMapboxMap#updateCameraTrackingMode`](https://github.com/mapbox/mapbox-navigation-android/blob/master/libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/map/NavigationMapboxMap.java#L302-L310) requests a [`@NavigationCamera.TrackingMode`](https://github.com/mapbox/mapbox-navigation-android/blob/master/libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/camera/NavigationCamera.java#L68-L71). Wouldn't be a good idea to request a [`@CameraMode.Mode`](https://github.com/mapbox/mapbox-plugins-android/blob/master/plugin-locationlayer/src/main/java/com/mapbox/mapboxsdk/plugins/locationlayer/modes/CameraMode.java#L23-L31) instead - removing the necessity of having to implement [`@NavigationCamera.TrackingMode`](https://github.com/mapbox/mapbox-navigation-android/blob/master/libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/camera/NavigationCamera.java#L68-L71) and the extra logic in [`NavigationCamera#setCameraMode`](https://github.com/mapbox/mapbox-navigation-android/blob/master/libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/camera/NavigationCamera.java#L343-L361) from our side? Am I missing something? @danesfeder @LukasPaczos 

> @LukasPaczos 
> The idea of exposing and requiring [@NavigationCamera.TrackingMode](https://github.com/mapbox/mapbox-navigation-android/blob/master/libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/camera/NavigationCamera.java#L68-L71) instead of [@CameraMode.Mode](https://github.com/mapbox/mapbox-plugins-android/blob/master/plugin-locationlayer/src/main/java/com/mapbox/mapboxsdk/plugins/locationlayer/modes/CameraMode.java#L23-L31) was to limit available camera mode options to those that are tested and well coordinated with the rest of the navigation UI/UX. Exposing the rest of camera tracking modes would generate another set of paths to maintain and wasn't in the scope of the original PR, but that's definitely an option we can explore going forward.

> @Guardiola31337 
> > Exposing the rest of camera tracking modes would generate another set of paths to maintain and wasn't in the scope of the original PR
>
> Makes sense. Thanks for clarifying @LukasPaczos 
>
> > but that's definitely an option we can explore going forward.
>
> Yeah, let's revisit this in a follow up PR. It seems like we're duplicating logic unnecessarily. While testing OP I tried to set the camera mode to `NONE` and I wasn't able to. I know that we already have the `updateCamerarTrackingEnabled` API to achieve that but I guess we could use the options from LLP and remove that "duplicated" behavior. What do you think @danesfeder @LukasPaczos?

> @LukasPaczos 
> Adding the support for `NONE` sounds like a great first step to me.

**Comment by danesfeder** [comment]
> Wouldn't be a good idea to request a @CameraMode.Mode instead - removing the necessity of having to implement @NavigationCamera.TrackingMode and the extra logic in NavigationCamera#setCameraMode from our side?

Yeah I'd say just exposing the `NONE` option here makes sense, keeping the options scoped.  

I don't think it's necessary to expose all possible modes - doing so would allow developers to introduce new behavior that we may not account for / handle correctly in the `NavigationView`.  As Lukas put, this wasn't in the scope of the PR.

**Comment by Guardiola31337** [comment]
> Yeah I'd say just exposing the `NONE` option here makes sense, keeping the options scoped.  

Sounds good 👍 In this case, we'd be able to remove / not expose [`NavigationMapboxMap#updateCameraTrackingEnabled`](https://github.com/mapbox/mapbox-navigation-android/blob/master/libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/map/NavigationMapboxMap.java#L291-L301) right?

> I don't think it's necessary to expose all possible modes - doing so would allow developers to introduce new behavior that we may not account for / handle correctly in the `NavigationView`. 

Makes sense 👍
