### ISSUE TITLE
Footer information - duration ui

### ISSUE THREAD

**Issue by P-Zenker** [mapbox/mapbox-navigation-android#1445]
**Android API:**  27 (Samsung A6)
**Mapbox Navigation SDK version:** 0.21.0

### Steps to trigger behavior
 1. Receive a long route
 2. Start navigation ui

### Actual behavior
With the given layout distance remaining and arrival time are not visible.

![2018-10-22 11 16 33](https://user-images.githubusercontent.com/23097192/47285637-f2a91c00-d5eb-11e8-8284-848b2d29c860.jpg)

**Comment by P-Zenker** [comment]
Hey @danesfeder, I don't manipulate the bottom sheet view. 

These are the system settings from my Samsung A6.
![2018-10-23 10 29 08](https://user-images.githubusercontent.com/23097192/47346967-8d6a2f00-d6ae-11e8-8715-e6cc41a34497.jpg)
On that basis, I say that "large text" is not enabled. I think the aspect ratio 18.5:9 of the display is problematic.

**Comment by danesfeder** [comment]
> I think the aspect ratio 18.5:9 of the display is problematic.

@P-Zenker yeah thank you for the context here.  We will look to reproduce with the same aspect ratio and report back here.
