### ISSUE TITLE
com.mapbox.mapboxsdk.style.layers.CannotAddLayerException: Layer mapbox-navigation-route-shield-layer-1 already exists #13156

### ISSUE THREAD

**Issue by Xgamefactory** [mapbox/mapbox-navigation-android#1448]
we are getting crash on rerouting using mapbox android navigation core. no NavigationView class

there is no autoreroting logic in core navigation so we are doing rerouting after triggering
**userOffRoute** event loading new directionsRoute and adding new route
as in reroute and mocknavigation activity.

crash happens in base case with simulation mode and not.

Are we missing something ? 

`navigationMapRoute.addRoutes(response.body().routes());`

```
com.mapbox.mapboxsdk.style.layers.CannotAddLayerException: Layer mapbox-navigation-route-shield-layer-1 already exists
        at com.mapbox.mapboxsdk.maps.NativeMapView.nativeAddLayer(Native Method)
        at com.mapbox.mapboxsdk.maps.NativeMapView.addLayerBelow(NativeMapView.java:676)
        at com.mapbox.mapboxsdk.maps.MapboxMap.addLayerBelow(MapboxMap.java:332)
        at com.mapbox.services.android.navigation.ui.v5.utils.MapUtils.addLayerToMap(MapUtils.java:63)
        at com.mapbox.services.android.navigation.ui.v5.route.NavigationMapRoute.addRouteShieldLayer(NavigationMapRoute.java:480)
        at com.mapbox.services.android.navigation.ui.v5.route.NavigationMapRoute.drawRoutes(NavigationMapRoute.java:324)
        at com.mapbox.services.android.navigation.ui.v5.route.NavigationMapRoute.onProgressChange(NavigationMapRoute.java:734)
        at com.mapbox.services.android.navigation.v5.navigation.NavigationEventDispatcher.onProgressChange(NavigationEventDispatcher.java:157)
        at com.mapbox.services.android.navigation.v5.navigation.NavigationService.onNewRouteProgress(NavigationService.java:114)
        at com.mapbox.services.android.navigation.v5.navigation.NavigationEngine$1.run(NavigationEngine.java:123)
        at android.os.Handler.handleCallback(Handler.java:733)
```

**Comment by danesfeder** [comment]
Hey @Xgamefactory 👋 do you mind sharing more of your `NavigationMapRoute` code?  Like how it's constructed and used within your `Activity` or `Fragment`?  Thanks!

**Comment by Xgamefactory** [comment]
navigationMapRoute property is mapbox core navigationMapRoute object. 
`import com.mapbox.services.android.navigation.ui.v5.route.NavigationMapRoute;`

**Comment by danesfeder** [comment]
@Xgamefactory I mean in terms of how you're instantiating the object / implementing it's methods (other than `navigationMapRoute.addRoutes(response.body().routes());`)

**Comment by Xgamefactory** [comment]
after mapview instantied with ready event

navigation MapboxNavigation
nativeMap MapboxMap
`navigationMapRoute = new NavigationMapRoute(navigation, mapView, nativeMap);`

then after route resulting adding DirectionsRout with method addRoute

**Comment by danesfeder** [comment]
Can you implement the lifecycle methods seen [here](https://github.com/mapbox/mapbox-navigation-android/blob/master/libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/route/NavigationMapRoute.java#L1032-L1052)?  I think this may help you.

**Comment by Xgamefactory** [comment]
thans @danesfeder we will try it.

**Comment by Xgamefactory** [comment]
unfotunatly we are using navigation sdk 0.11.0 your navigationmaproute class is from 0.15 version and has related with MapRouteProgressChangeListener which also related to classes that much more different from 0.11.0 one.

**Comment by Xgamefactory** [comment]
mapbox anroid navigaiton depends on maps sdk that uses java8 futures thats is why we have to use old 0.11.0 navigation sdk with maps sdk 5.5.2 which dont have jdk8 dependencies.

**Comment by danesfeder** [comment]
@Xgamefactory we actually reverted these changes for customers that were running into the same issue https://github.com/mapbox/mapbox-java/issues/868

Is it possible for you to update to `0.20.0` which includes the revert?

**Comment by danesfeder** [comment]
@Xgamefactory any updates here?

**Comment by Xgamefactory** [comment]
it was impossible to use that version we need jdk7 downgraded mapbox sdk we had to switch back to heremaps sdk

**Comment by danesfeder** [comment]
Hey @Xgamefactory I'm going to close here as resolved / non-actionable on our part per https://github.com/mapbox/mapbox-navigation-android/issues/1448#issuecomment-432332837.

**Comment by Xgamefactory** [comment]
you can close we switched back to heremaps navigation which don't have such unresolved issues.

**Comment by jay23794** [comment]
Note: id is comming from for loop index

I haven't found the solution but the hack is
 Future<void> _addSourceAndLineLayer(List<SearchByLocation> selection,
      String id, List<RoutingModel> routingDetails_1) async {
    try {
      var num = DateTime.now().millisecondsSinceEpoch;
      isLineMapped = true;

      final _fills = {
        "type": "FeatureCollection",
        "features": [
          {
            "type": "Feature",
            "id": num.toString(),
            "properties": <String, dynamic>{},
            "geometry": routingDetails_1[0].geometry,
            "image": "Home"
          },
        ],
      };

      await _controller.addSource(
          num.toString(), GeojsonSourceProperties(data: _fills));
      ////log(id + "line");
      lineData.add([
        await _controller.addLineLayer(
          num.toString(),
          id,
          LineLayerProperties(
            lineColor: Colors.indigo.toHexStringRGB(),
            lineCap: "round",
            lineJoin: "round",
            lineWidth: 3,
          ),
        )
      ]);
      
      adding layer with new ID . i will raise the error but not gonna kill the app
