### ISSUE TITLE
"Report problem" not translated

### ISSUE THREAD

**Issue by P-Zenker** [mapbox/mapbox-navigation-android#1462]
**Mapbox Navigation SDK version:** 0.22.0

### Steps to trigger behavior
 1. Force the "Report Problem" popup

### Expected behavior
In my case: "Problem melden" (german)

### Actual behavior
It's still in english while everything else is translated to german.

![2018-10-25 11 51 12](https://user-images.githubusercontent.com/23097192/47491979-49149580-d84c-11e8-8c57-a335bc552996.jpg)

I didn't find a translatable string on transifex.

**Comment by Guardiola31337** [comment]
Hey @P-Zenker 👋 thanks for reporting!

Yeah, you're completely right here. We're using a hardcoded text in [`NavigationAlertView`](https://github.com/mapbox/mapbox-navigation-android/blob/master/libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/instruction/NavigationAlertView.java) 🤦‍♂️ https://github.com/mapbox/mapbox-navigation-android/blob/d1c2f4f077203669b63106a6b8faf70563f2d035/libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/instruction/NavigationAlertView.java#L61 https://github.com/mapbox/mapbox-navigation-android/blob/d1c2f4f077203669b63106a6b8faf70563f2d035/libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/NavigationConstants.java#L123

We will prioritize localizing this text and then report back here on this ticket. Great catch by the way 💪

Thanks again!
