### ISSUE TITLE
Is it possible to do AR Navigation uisng mapbox?

### ISSUE THREAD

**Issue by Parameshvadivel** [mapbox/mapbox-navigation-android#1464]
I am trying to develop and ar navigation using mapbox direction api. How to draw route in AR using arcore or another AR SDK in android?

**Comment by BenDenen** [comment]
Hey @Parameshvadivel 👋 it is really interesting question.  You could find the best answer to it here https://vision.mapbox.com/. Please request beta accsse to Vision SDK. Some more details and documentation https://www.mapbox.com/android-docs/vision-ar/overview/.  Best regard!

**Comment by Guardiola31337** [comment]
Thanks @Parameshvadivel for your interest and @BenDenen for jumping in here.

Closing as answered.
