### ISSUE TITLE
Custom map padding is overridden by MapPaddingAdjustor

### ISSUE THREAD

**Issue by hurrba** [mapbox/mapbox-navigation-android#1465]
**Mapbox Navigation SDK version: 0.22.0**

`MapPaddingAdjustor` overrides any custom padding set in `onProgressChange()` if `wayname` is visible and `wayname.isAutoQueryEnabled == true`.  

### Steps to trigger behavior

 1. Start navigation
 2. Set custom padding in `onProgressChange()`. E.g. `{0,0,0,0}` to center the puck.

### Expected behavior
 1. Puck should be centered when setting padding to `{0,0,0,0}`

### Actual behavior
 1. Puck keeps flickering between custom padding and default padding in `MapPaddingAdjustor`

![mappaddingadjustor](https://user-images.githubusercontent.com/2956036/47506697-e71a5700-d870-11e8-8e2e-6e6a3e219655.gif)

**Comment by danesfeder** [comment]
@hurrba Yeah this makes total sense - we need to come up with a better way of padding adjustment when custom padding is already set.  Stay tuned here and thank you for your patience.
