### ISSUE TITLE
Enable more extensive customization of the bottom banner in the drop-in navigation UI

### ISSUE THREAD

**Issue by akitchen** [mapbox/mapbox-navigation-android#1468]
It should be possible for developers to supply their own view and related components to populate and manage the bottom banner for more complicated/customized use cases.

In order to do this, our default bottom banner should be contained within a `FrameLayout` which will wrap the content area, giving adjacent views something persistent to be positioned against. Ideally developers would be able to resize this content area or container view, and adjacent "sibling views" in the navigation UI would reposition accordingly. We may want to explore enforcing a max height for this.

**Comment by Guardiola31337** [comment]
Is this something we want to prioritize / support in the `1.0` UI SDK @asinghal22?

cc @abhishek1508

**Comment by Guardiola31337** [comment]
Friendly ping @asinghal22

If we're not going to support this for now, feel free to close here.

cc @abhishek1508

**Comment by LukasPaczos** [comment]
Closing as stale.
