### ISSUE TITLE
syncing between cameraview and marker

### ISSUE THREAD

**Issue by siavashabdoli** [mapbox/mapbox-navigation-android#1472]
**Android API: android 9
**Mapbox Navigation SDK version:16

### Steps to trigger behavior

 1. weak GPS!
 2. during navigation click on home or change foreground app
 3. open app later after you move to another location
4. marker is update but recenter and tracking is focusing on the location that we have before send app to background
5.after next location update it tracking focus on correct location but in some situation it can take 10 seconds!

### Expected behavior
sync between marker and camera. they can both use location from livedata to handle location update.
right now progressChangeListener delete in onStop for cameraNavigation so currentRouteInformation is outdated, but the marker listen from LiveData in NavigationViewModel

**Comment by danesfeder** [comment]
Hey @siavashabdoli 👋 you're definitely correct here - in `0.16.0` the camera / marker were not synchronized causing the UX behavior you're describing.  

Fortunately, this worked just moved in https://github.com/mapbox/mapbox-navigation-android/pull/1372, so the map camera and marker use the same animation.  If you're able to update to the latest SDK, you'll see improved behavior around this.  Thanks!
