### ISSUE TITLE
Filter inaccurate GPS

### ISSUE THREAD

**Issue by ericrwolfe** [mapbox/mapbox-navigation-android#148]
GPS locations are not guaranteed to be accurate. We should filter out any locations with poor accuracy (>= 100m horizontal, <= 0m horizontal, >= 30m vertical, <= 0m vertical).

cc @mapbox/navigation-android

**Comment by ericrwolfe** [comment]
Additional discussion/context over in https://github.com/mapbox/mapbox-navigation-ios/issues/433

**Comment by danesfeder** [comment]
@ericrwolfe First pass of this is only to consider horizontal accuracy (as discussed in mapbox/mapbox-navigation-ios#433 just want to confirm).  

And also to be clear, this filter means we are looking at location updates and checking to see if they are accurate (based on your criteria above) - if they are, we are using them for calculation and acting on them as we normally would.  If not, we just ignore?  

cc @cammace

**Comment by ericrwolfe** [comment]
Yeah, so we should factor them out for things like off-route detection/rerouting and distance remaining calculations, but we should still keep the raw locations around for metrics.

**Comment by cammace** [comment]
I added several checks in the thread PR I have open. For your suggestions, accuracy is required to be a value below 100 meters. Vertical accuracy doesn't exist for Android API levels below 26 nor do I think it's that critical to include in this check.

**Comment by daniel-j-h** [comment]
Related: slack conversation about location jumping around because of same ssids:
https://mapbox.slack.com/archives/C21AYEN5N/p1502138791745705

**Comment by cammace** [comment]
Merged the thread PR which I mentioned above, you can see the [check here](https://github.com/mapbox/mapbox-navigation-android/blob/master/navigation/libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/NavigationService.java#L174) which causes us to ignore the raw location if the accuracy is above 100 meters. Closing.
