### ISSUE TITLE
Crash on Navigation on 6.0.1 OnePlus One

### ISSUE THREAD

**Issue by Christophe668** [mapbox/mapbox-navigation-android#1480]
Hi, a user is getting this crash. It seems that it's caused by the default notification created by Mapbox.
By the way, is it possible to disable the notification?

```
Fatal Exception: android.app.RemoteServiceException: Bad notification posted from package bike.cowboy.app: Couldn't expand RemoteViews for: StatusBarNotification(pkg=bike.cowboy.app user=UserHandle{0} id=5678 tag=null score=20 key=0|bike.cowboy.app|5678|null|10222: Notification(pri=2 contentView=bike.cowboy.app/0x7f0c0053 vibrate=null sound=null defaults=0x0 flags=0x62 color=0x00000000 category=service vis=PRIVATE))
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1526)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5461)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Android API:** 6.0.1
**Mapbox Navigation SDK version:** 22
**Device:** OnePlus One

### Steps to trigger behavior

 1. Launch navigation
 2. App crashes

Cheers

**Comment by danesfeder** [comment]
Hey @Christophe668, we are working through some issues with the default notification.  We can't disable the notification because we run a `ForegroundService` that requires a notification Oreo+.  

You can create your own those and the SDK will use that instead of the default: https://www.mapbox.com/android-docs/navigation/overview/navigation-options/#creating-a-custom-notification

**Comment by Guardiola31337** [comment]
@abhishek1508 could this be an issue in `1.0`?

BTW with the new modularization approach in `1.0` clients can provide their own notification implementation and might solve your issue @Christophe668 Stay tuned for the upcoming beta release 🚀

**Comment by Guardiola31337** [comment]
Hey @Christophe668 we've just released [`release_core_1.0.0-rc.1`](https://github.com/mapbox/mapbox-navigation-android/releases/tag/release_core_1.0.0-rc.1) 🎉 🚀 

Please review the [developer documentation](https://docs.mapbox.com/android/beta/navigation/overview/#installation) to start building with the Mapbox core Navigation SDK v1.0 for Android and if you already use an older version of the Navigation SDK, check out [the migration guide](https://github.com/mapbox/mapbox-navigation-android/wiki/1.0-Navigation-SDK-Migration-Guide) to transition your project from the "legacy" core Navigation SDK to the 1.0 version and let us know if you have any questions or run into issues and please open tickets in https://github.com/mapbox/mapbox-navigation-android/issues/new and we will take it from there! We would love your feedback.

Thanks for checking out the SDK!

**Comment by abhishek1508** [comment]
Let's verify
cc @JunDai @cafesilencio @langsmith

**Comment by abhishek1508** [comment]
Closing it as this is not an issue with 1.0
