### ISSUE TITLE
Add options wrapper workaround for bicycle costing options

### ISSUE THREAD

**Issue by devotaaabel** [mapbox/mapbox-navigation-android#1486]
As discussed with @Guardiola31337 and @danesfeder , until the directions API implements bicycle options (which will not be before offline needs to ship), a workaround needs to be implemented to allow the use of the options in the case of offline routing.

**Comment by Guardiola31337** [comment]
Hey @devotaaabel I believe this was done / implemented in https://github.com/mapbox/mapbox-navigation-android/pull/1398 and https://github.com/mapbox/mapbox-navigation-android/pull/1516

Are we good to close here?

**Comment by devotaaabel** [comment]
Yup
