### ISSUE TITLE
Unable to click myLocation button after i closed the NavigationLauncherOptions

### ISSUE THREAD

**Issue by kensou123** [mapbox/mapbox-navigation-android#1489]
After I closed the NavigationLauncher my myLocation button not working anymore. I have to close my application before it work again. This always happens after I closed the NavigationLauncher. Sorry for my English. Heres my entire code. 

package com.android.thesis.gofit.RideMonitor;

import android.app.Activity;
import android.content.Intent;
import android.graphics.Color;
import android.location.Location;
import android.os.Bundle;
import android.support.annotation.NonNull;
import android.support.design.widget.FloatingActionButton;
import android.support.v7.app.AppCompatActivity;
import android.support.v7.widget.PopupMenu;
import android.util.Log;
import android.view.MenuItem;
import android.view.View;
import android.widget.Button;
import android.widget.ProgressBar;
import android.widget.Toast;

import com.android.thesis.gofit.R;
import com.google.gson.JsonObject;
import com.mapbox.android.core.location.LocationEngine;
import com.mapbox.android.core.location.LocationEngineListener;
import com.mapbox.android.core.location.LocationEnginePriority;
import com.mapbox.android.core.location.LocationEngineProvider;
import com.mapbox.android.core.permissions.PermissionsListener;
import com.mapbox.android.core.permissions.PermissionsManager;
import com.mapbox.api.directions.v5.DirectionsCriteria;
import com.mapbox.api.directions.v5.models.DirectionsResponse;
import com.mapbox.api.directions.v5.models.DirectionsRoute;
import com.mapbox.api.geocoding.v5.models.CarmenFeature;
import com.mapbox.geojson.Feature;
import com.mapbox.geojson.FeatureCollection;
import com.mapbox.geojson.Point;
import com.mapbox.mapboxsdk.Mapbox;
import com.mapbox.mapboxsdk.annotations.Marker;
import com.mapbox.mapboxsdk.annotations.MarkerOptions;
import com.mapbox.mapboxsdk.camera.CameraPosition;
import com.mapbox.mapboxsdk.camera.CameraUpdateFactory;
import com.mapbox.mapboxsdk.constants.Style;
import com.mapbox.mapboxsdk.geometry.LatLng;
import com.mapbox.mapboxsdk.maps.MapView;
import com.mapbox.mapboxsdk.maps.MapboxMap;
import com.mapbox.mapboxsdk.maps.OnMapReadyCallback;
import com.mapbox.mapboxsdk.plugins.locationlayer.LocationLayerPlugin;
import com.mapbox.mapboxsdk.plugins.locationlayer.modes.CameraMode;
import com.mapbox.mapboxsdk.plugins.locationlayer.modes.RenderMode;
import com.mapbox.mapboxsdk.plugins.places.autocomplete.PlaceAutocomplete;
import com.mapbox.mapboxsdk.plugins.places.autocomplete.model.PlaceOptions;
import com.mapbox.mapboxsdk.plugins.traffic.TrafficPlugin;
import com.mapbox.mapboxsdk.style.layers.PropertyFactory;
import com.mapbox.mapboxsdk.style.layers.SymbolLayer;
import com.mapbox.mapboxsdk.style.sources.GeoJsonSource;
import com.mapbox.services.android.navigation.ui.v5.NavigationLauncher;
import com.mapbox.services.android.navigation.ui.v5.NavigationLauncherOptions;
import com.mapbox.services.android.navigation.ui.v5.route.NavigationMapRoute;
import com.mapbox.services.android.navigation.v5.navigation.NavigationRoute;

import java.util.List;

import retrofit2.Call;
import retrofit2.Callback;
import retrofit2.Response;

public class RideTracking extends AppCompatActivity implements
        OnMapReadyCallback, LocationEngineListener, PermissionsListener, MapboxMap.OnMapLongClickListener, PopupMenu.OnMenuItemClickListener {

    private static final String TAG = "RideTracking";
    private static final int REQUEST_CODE_AUTOCOMPLETE = 1;
    private PermissionsManager permissionsManager;
    private MapboxMap map;
    private MapView mapView;
    private TrafficPlugin trafficPlugin;
    private FloatingActionButton myLocation, myStyles;
    private Button startButton;
    private LocationEngine locationEngine;
    private LocationLayerPlugin locationLayerPlugin;
    private Location lastlocation;
    private Location originLocation;
    private Point originPosition;
    private Point destinationPosition;
    private Marker destinationMarker;
    private NavigationMapRoute navigationMapRoute;
    private DirectionsRoute currentRoute;
    private CarmenFeature school;
    private CarmenFeature selectedCarmenFeature;
    private CameraPosition newCameraPosition;
    private String geojsonSourceLayerId = "geojsonSourceLayerId";
    private String symbolIconId = "symbolIconId";
    ProgressBar loading;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        Mapbox.getInstance(this, getString(R.string.mapbox_access_token));
        setContentView(R.layout.activity_ride_tracking);
        mapView = findViewById(R.id.mapView);
        mapView.setStyleUrl(Style.OUTDOORS);
        mapView.onCreate(savedInstanceState);
        loading = findViewById(R.id.loading);
        loading.setVisibility(View.VISIBLE);
        mapView.getMapAsync(this);
        enableLocation();

    }

    @Override
    public void onMapReady(MapboxMap mapboxMap) {
        myLocation();
        map = mapboxMap;

        trafficPlugin = new TrafficPlugin(mapView, map);
        RideTracking.this.trafficPlugin.setVisibility(true);

        initializeLocationLayer();
        hideLoading();
        initSearchFab();
        addUserLocations();
        setUpSource();
        setupLayer();

        startButton = findViewById(R.id.startButton);
        startButton.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                NavigationLauncherOptions options = NavigationLauncherOptions.builder()
                        .directionsRoute(currentRoute)
                        .shouldSimulateRoute(true)
                        .directionsProfile(DirectionsCriteria.PROFILE_DRIVING_TRAFFIC)
                        .build();
                // Call this method with Context from within an Activity
                NavigationLauncher.startNavigation(RideTracking.this, options);

            }
        });

        myStyles = findViewById(R.id.myStyles);
        myStyles.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                PopupMenu popup = new PopupMenu(RideTracking.this, v);
                popup.setOnMenuItemClickListener(RideTracking.this);
                popup.inflate(R.menu.menu_map_style);
                popup.show();
            }
        });

        myLocation();
        myCurrentLocation();

    }

    private void myLocation() {
        myLocation = findViewById(R.id.myLocation);
        myLocation.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                if (map != null) {
                    myCurrentLocation();
                }
            }
        });
    }

    @Override
    public boolean onMenuItemClick(MenuItem menuItem) {
        Toast.makeText(this, "You've Selected: " + menuItem.getTitle() + " Map Style", Toast.LENGTH_SHORT).show();
        switch (menuItem.getItemId()) {
            case R.id.menu_streets:
                mapView.setStyleUrl(Style.MAPBOX_STREETS);
                return true;
            case R.id.menu_dark:
                mapView.setStyleUrl(Style.DARK);
                return true;
            case R.id.menu_light:
                mapView.setStyleUrl(Style.LIGHT);
                return true;
            case R.id.menu_outdoors:
                mapView.setStyleUrl(Style.OUTDOORS);
                return true;
            case R.id.menu_satellite:
                mapView.setStyleUrl(Style.SATELLITE);
                return true;
            case R.id.menu_satellite_streets:
                mapView.setStyleUrl(Style.SATELLITE_STREETS);
                return true;
            case android.R.id.home:
                finish();
                return true;
            default:
                return super.onOptionsItemSelected(menuItem);
        }
    }

    private void enableLocation() {
        if (PermissionsManager.areLocationPermissionsGranted(this)) {
            initializeLocationEngine();

        } else {
            permissionsManager = new PermissionsManager(this);
            permissionsManager.requestLocationPermissions(this);
        }

    }

    @SuppressWarnings({"MissingPermission"})
    private void initializeLocationEngine() {
        locationEngine = new LocationEngineProvider(this).obtainBestLocationEngineAvailable();
        locationEngine.setPriority(LocationEnginePriority.HIGH_ACCURACY);
        locationEngine.setInterval(0);
        locationEngine.setFastestInterval(1000);
        locationEngine.addLocationEngineListener(this);
        locationEngine.activate();

        myLocation();
    }

    @SuppressWarnings({"MissingPermission"})
    private void myCurrentLocation() {

        lastlocation = locationEngine.getLastLocation();
        if (lastlocation != null) {
            originLocation = lastlocation;
            CameraPosition position = new CameraPosition.Builder()
                    .target(new LatLng(originLocation.getLatitude(), originLocation.getLongitude())) // Sets the new camera position
                    .zoom(17) // Sets the zoom
                    .bearing(0)// Rotate the camera
                    .build(); // Creates a CameraPosition from the builder
            map.animateCamera(CameraUpdateFactory
                    .newCameraPosition(position), 4000);
            map.addOnMapLongClickListener(this);
        } else {
            locationEngine.addLocationEngineListener(this);
        }
    }

    @SuppressWarnings({"MissingPermission"})
    private void initializeLocationLayer() {

        locationLayerPlugin = new LocationLayerPlugin(mapView, map, locationEngine);
        locationLayerPlugin.setLocationLayerEnabled(true);
        locationLayerPlugin.setCameraMode(CameraMode.TRACKING);
        locationLayerPlugin.setRenderMode(RenderMode.COMPASS);

    }

    private void setCameraPosition(Location location) {
        map.animateCamera(CameraUpdateFactory.newLatLngZoom(new LatLng(location.getLatitude(),
                location.getLongitude()), 17.0));
    }

    @Override
    public void onMapLongClick(@NonNull LatLng point) {
        if (destinationMarker != null) {
            map.removeMarker(destinationMarker);
        }
        destinationMarker = map.addMarker(new MarkerOptions().position(point));
        destinationPosition = Point.fromLngLat(point.getLongitude(), point.getLatitude());
        originPosition = Point.fromLngLat(originLocation.getLongitude(), originLocation.getLatitude());
        getRoute(originPosition, destinationPosition);

        loading.setVisibility(View.VISIBLE);

    }

    private void getRoute(Point origin, Point destination) {
        NavigationRoute.builder(this)
                .accessToken(getString(R.string.mapbox_access_token))
                .origin(origin)
                .destination(destination)
                .profile(DirectionsCriteria.PROFILE_WALKING)
                .annotations(DirectionsCriteria.ANNOTATION_CONGESTION)
                .annotations(DirectionsCriteria.OVERVIEW_FULL)
                .alternatives(true)
                .voiceUnits(DirectionsCriteria.METRIC)
                .annotations(DirectionsCriteria.ANNOTATION_SPEED)
                .build()
                .getRoute(new Callback<DirectionsResponse>() {
                    @Override
                    public void onResponse(Call<DirectionsResponse> call, Response<DirectionsResponse> response) {
                        if (response.body() == null) {
                            Log.e(TAG, "No routes found, check right user and access token");
                            return;
                        } else if (response.body().routes().size() == 0) {
                            Log.e(TAG, "No routes found.");
                            return;
                        }

                        currentRoute = response.body().routes().get(0);

                        // Draw the route on the map
                        if (navigationMapRoute != null) {
                            navigationMapRoute.removeRoute();
                        } else {
                            navigationMapRoute = new NavigationMapRoute(null, mapView, map);
                        }
                        navigationMapRoute.addRoute(currentRoute);

                        startButton.setEnabled(true);
                        startButton.setBackgroundResource(R.drawable.round_button1);
                        hideLoading();

                    }

                    @Override
                    public void onFailure(Call<DirectionsResponse> call, Throwable t) {
                        Log.e(TAG, "Error:" + t.getMessage());
                    }
                });
    }

    private void initSearchFab() {
        FloatingActionButton searchFab = findViewById(R.id.searchButton);
        searchFab.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                Intent intent = new PlaceAutocomplete.IntentBuilder()
                        .accessToken(Mapbox.getAccessToken())
                        .placeOptions(PlaceOptions.builder()
                                .backgroundColor(Color.parseColor("#FFFFFF"))
                                .limit(10)
                                .addInjectedFeature(school)
                                .build(PlaceOptions.MODE_CARDS))
                        .build(RideTracking.this);
                startActivityForResult(intent, REQUEST_CODE_AUTOCOMPLETE);
            }
        });
    }

    private void addUserLocations() {
        school = CarmenFeature.builder().text("Cavite State University - Bacoor City Campus")
                .geometry(Point.fromLngLat(120.981388, 14.412742))
                .placeName("Sampaguita, Bacoor City, Cavite")
                .id("school")
                .properties(new JsonObject())
                .build();
    }

    private void setUpSource() {
        GeoJsonSource geoJsonSource = new GeoJsonSource(geojsonSourceLayerId);
        map.addSource(geoJsonSource);
    }

    private void setupLayer() {
        SymbolLayer selectedLocationSymbolLayer = new SymbolLayer("SYMBOL_LAYER_ID", geojsonSourceLayerId);
        selectedLocationSymbolLayer.withProperties(PropertyFactory.iconImage(symbolIconId));
        map.addLayer(selectedLocationSymbolLayer);
    }

    @Override
    protected void onActivityResult(int requestCode, int resultCode, Intent data) {
        super.onActivityResult(requestCode, resultCode, data);
        if (resultCode == Activity.RESULT_OK && requestCode == REQUEST_CODE_AUTOCOMPLETE) {

            // Retrieve selected location's CarmenFeature
            selectedCarmenFeature = PlaceAutocomplete.getPlace(data);

            // Create a new FeatureCollection and add a new Feature to it using selectedCarmenFeature above
            FeatureCollection featureCollection = FeatureCollection.fromFeatures(
                    new Feature[]{Feature.fromJson(selectedCarmenFeature.toJson())});

            // Retrieve and update the source designated for showing a selected location's symbol layer icon
            GeoJsonSource source = map.getSourceAs(geojsonSourceLayerId);
            if (source != null) {
                source.setGeoJson(featureCollection);
            }

            // Move map camera to the selected location
            onSearchLocation();

        }
    }

    private void onSearchLocation() {
        newCameraPosition = new CameraPosition.Builder()
                .target(new LatLng(((Point) selectedCarmenFeature.geometry()).latitude(),
                        ((Point) selectedCarmenFeature.geometry()).longitude()))
                .zoom(17)
                .build();
        map.animateCamera(CameraUpdateFactory.newCameraPosition(newCameraPosition), 1);
    }

    @SuppressWarnings({"MissingPermission"})
    @Override
    public void onConnected() {
        locationEngine.requestLocationUpdates();
    }

    @Override
    public void onLocationChanged(Location location) {

    }

    @Override
    public void onExplanationNeeded(List<String> permissionsToExplain) {
        Toast.makeText(this, R.string.user_location_permission_explanation, Toast.LENGTH_LONG).show();
    }

    @Override
    public void onPermissionResult(boolean granted) {
        if (granted) {
            enableLocation();
            initializeLocationLayer();
        } else {
            Toast.makeText(this, R.string.user_location_permission_not_granted, Toast.LENGTH_LONG).show();
        }
    }

    @Override
    public void onRequestPermissionsResult(int requestCode, @NonNull String[] permissions, @NonNull int[] grantResults) {
        permissionsManager.onRequestPermissionsResult(requestCode, permissions, grantResults);
    }

    @SuppressWarnings({"MissingPermission"})
    protected void onStart() {
        super.onStart();
        if (locationEngine != null) {
            locationEngine.requestLocationUpdates();
        }
        if (locationLayerPlugin != null) {
            locationLayerPlugin.onStart();
        }
        mapView.onStart();
    }

    @SuppressWarnings({"MissingPermission"})
    @Override
    protected void onResume() {
        super.onResume();

        mapView.onResume();
    }

    @Override
    protected void onPause() {
        super.onPause();
        mapView.onPause();
    }

    @Override
    protected void onStop() {
        super.onStop();
        if (locationEngine != null) {
            locationEngine.removeLocationUpdates();
            locationEngine.deactivate();
        }
        if (locationLayerPlugin != null) {
            locationLayerPlugin.onStop();
        }
        mapView.onStop();
    }

    @Override
    protected void onSaveInstanceState(Bundle outState) {
        super.onSaveInstanceState(outState);
        mapView.onSaveInstanceState(outState);
    }

    @Override
    protected void onDestroy() {
        super.onDestroy();
        if (locationEngine != null) {
            locationEngine.deactivate();
        }
        mapView.onDestroy();
    }

    @Override
    public void onLowMemory() {
        super.onLowMemory();
        mapView.onLowMemory();
    }

    private void hideLoading() {
        if (loading != null) {
            loading.setVisibility(View.INVISIBLE);
        }
        if (loading == null) {
            loading.setVisibility(View.VISIBLE);
        }
    }

}

**Comment by danesfeder** [comment]
Hey @kensou123 I think the issue here is our deactivation in `onDestroy` of the `MapboxNavigationActivity` where https://github.com/mapbox/mapbox-navigation-android/blob/master/libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/MapboxNavigation.java#L843-L848 is called. 

`LocationEngineProvider#obtainBestLocationEngineAvailable()` returns a singleton instance of the same `LocationEngine` that we use for navigation.  So we are essentially deactivating your engine (I believe).  When `RideTracking` is resumed after `MapboxNavigationActivity` has ended, I'd try called `LocationEngine#activate`.  

Let me know if this helps, I'm going to go ahead and close this as this behavior should be resolved as a result of https://github.com/mapbox/mapbox-events-android/releases/tag/telem-4.0.0-core-1.0.0 as https://github.com/mapbox/mapbox-events-android/blob/master/liblocation/src/main/java/com/mapbox/android/core/location/LocationEngineProvider.java#L31-L53 will return new instances of `LocationEngine` rather than shared singletons.  Correct me if I'm wrong here @andrlee @Guardiola31337
