### ISSUE TITLE
unable to recieve maneuver type arrival from route progress

### ISSUE THREAD

**Issue by navdeepg** [mapbox/mapbox-navigation-android#1501]
Hey Team,

I am unable to receive maneuver type arrival with when driver reaches at destination. I noticed this after updating sdk to 0.22.0. Following is the way i am trying to fetch it:-
 @Override
    public void onProgressChange(Location location, RouteProgress routeProgress) {
        boolean isCurrentStepArrival = routeProgress.currentLegProgress().currentStep().maneuver().type()
                .contains(STEP_MANEUVER_TYPE_ARRIVE);
}

It triggers depart, continue and turn events but not arrived.

Can you please look into this?

**Comment by danesfeder** [comment]
Hey @navdeepg, is the current behavior you're trying to achieve detecting when a user has arrived at the end of their leg?  

I just cut https://github.com/mapbox/mapbox-navigation-android/pull/1502 that explains some of the reasoning behind why this is occurring and provides a more straightforward way to detect when a user has arrived at the end of their route.  Please provide feedback if this is sufficient for your use case, thanks!
