### ISSUE TITLE
DirectionsRoute fromJson

### ISSUE THREAD

**Issue by vadbutSwerve** [mapbox/mapbox-navigation-android#1517]
I'm trying to figure out how to convert DirectionsRoute to json and back. Here is my test code in java:
```
String jsonroute= new GsonBuilder() .registerTypeAdapterFactory(DirectionsAdapterFactory.create()).create().toJson(currentRoute);
currentRoute.fromJson(jsonroute);
```

The currentRoute variable is not null and the string jsonroute seems to have a legit value as well, however fromJson call results in null currentRoute.

Let me know if you can spot what could be the issue.

**Comment by danesfeder** [comment]
Hey @vadbutSwerve 👋 

`DirectionsRoute` has a `toJson` and a `fromJson` method you can use (without having to register a type adapter factory):

```
String currentRouteJson = currentRoute.toJson();
currentRoute = DirectionsRoute.fromJson(currentRouteJson);
```

Hope this helps, thanks!
