### ISSUE TITLE
location.getSpeed() is always 0

### ISSUE THREAD

**Issue by liupeng826** [mapbox/mapbox-navigation-android#1518]
**Mapbox Navigation SDK version:**
implementation 'com.mapbox.mapboxsdk:mapbox-android-navigation:0.23.0'
implementation 'com.mapbox.mapboxsdk:mapbox-android-navigation-ui:0.23.0'

String string = String.format("%d\nMPH", (int) (location.getSpeed() * 2.2369));

here, location.getSpeed() is always 0.
I test when i driving, still 0. But no problem when i use 0.19.0.

**Comment by Thunderlemon** [comment]
I experimented the same issue with :

implementation 'com.mapbox.mapboxsdk:mapbox-android-navigation:0.21.0'
implementation 'com.mapbox.mapboxsdk:mapbox-android-navigation-ui:0.21.0'
