### ISSUE TITLE
com.android.support:appcompat-v7:27.1.1 or 27.0.2 both wrong

### ISSUE THREAD

**Issue by Zebrap** [mapbox/mapbox-navigation-android#1520]
All com.android.support libraries must use the exact same version specification (mixing versions can lead to runtime crashes). Found versions 27.1.1, 27.0.2. Examples include 'com.android.support:animated-vector-drawable:27.1.1' and 'com.android.support:cardview-v7:27.0.2'

com.mapbox.mapboxsdk:mapbox-android-sdk:6.7.0 this version need 27.1.1 but com.mapbox.mapboxsdk:mapbox-android-navigation-ui:0.23.0 need 27.0.2
so there is conflict

**Android API:
**Mapbox Navigation SDK version:**
com.mapbox.mapboxsdk:mapbox-android-sdk:6.7.0 
com.mapbox.mapboxsdk:mapbox-android-plugin-locationlayer:0.11.0
com.mapbox.mapboxsdk:mapbox-android-navigation-ui:0.23.0

### Steps to trigger behavior

 1. try to sync gradle with this 3 new SDK
 2.
 3.

**Comment by danesfeder** [comment]
Hey @Zebrap 👋 I think the issue here is `com.mapbox.mapboxsdk:mapbox-android-plugin-locationlayer:0.11.0`.  The [`0.11.0`](https://github.com/mapbox/mapbox-plugins-android/releases/tag/v0.11.0-location-layer) release deprecated the plugin in favor of the `LocationComponent` [see docs here](https://www.mapbox.com/android-docs/maps/overview/location-component/).  

You can update your `build.gradle` to just:

```
implementation com.mapbox.mapboxsdk:mapbox-android-navigation-ui:0.23.0
```

No need for:

```
com.mapbox.mapboxsdk:mapbox-android-sdk:6.7.0 (included in mapbox-android-navigation-ui)
com.mapbox.mapboxsdk:mapbox-android-plugin-locationlayer:0.11.0 
```

This should ultimately solve your conflict.  Thanks!

**Comment by Zebrap** [comment]
I have this:

`dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation 'com.android.support:appcompat-v7:27.1.1'
    implementation 'com.android.support.constraint:constraint-layout:1.1.3'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.2'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'

    implementation 'com.mapbox.mapboxsdk:mapbox-android-navigation-ui:0.23.0'
}`
and still same problem: 
All com.android.support libraries must use the exact same version specification (mixing versions can lead to runtime crashes). Found versions 27.1.1, 27.1.0. Examples include 'com.android.support:animated-vector-drawable:27.1.1' and 'com.android.support:exifinterface:27.1.0'
