### ISSUE TITLE
Reopen bicycle options in MAS when they are added to the directions API

### ISSUE THREAD

**Issue by devotaaabel** [mapbox/mapbox-navigation-android#1523]
This should be re-opened https://github.com/mapbox/mapbox-java/pull/901 and this should be un-done https://github.com/mapbox/mapbox-navigation-android/issues/1486 once the bicycle options are added to the directions API.

**Comment by Guardiola31337** [comment]
This will be supported out of the box when Directions API is fully migrated, right? Could you confirm @mapbox/navigation-api @danpat @danpaz?

**Comment by danpaz** [comment]
@Guardiola31337 yeah that's right, but we have no plans to migrate the Cycling API anytime soon, and it's unclear what options will be exposed when we do migrate. I think it's fine to close this ticket for now.

**Comment by Guardiola31337** [comment]
Let's revisit in the future then. Thanks for the input @danpaz
