### ISSUE TITLE
Request: Allow change of color for Navigation notification

### ISSUE THREAD

**Issue by cmahopper** [mapbox/mapbox-navigation-android#1527]
The navigation notification's blue color does not fit very nicely with our app, so we made a custom notification. However, the look of the default notification is fine, and it is tedious to change the custom notification to match the default notification on every library update.

Thus, it would be nice if we could just specify background and text colors for the default navigation notification as to avoid having to create a custom one.

**Comment by danesfeder** [comment]
@cmahopper this seems reasonable - because the notification is provided via the core library, I think we'd need to add the options to `MapboxNavigationOptions`, which can still be passed to the `NavigationView.

**Comment by cmahopper** [comment]
Would it not be possible to implement it in styles.xml like NavigationMapRoute for example?

**Comment by danesfeder** [comment]
@cmahopper we could maybe add a style res as a param for the `MapboxNavigationNotification` that you could construct on your side and pass as a "custom notification".  

The core library doesn't have a style setup like `navigation-ui`, so there isn't a "default" style setup like the `NavigationView` or `NavigationMapRoute` have if that makes sense.

**Comment by cmahopper** [comment]
I see, that makes sense.

**Comment by danesfeder** [comment]
@cmahopper moving in https://github.com/mapbox/mapbox-navigation-android/pull/1899
