### ISSUE TITLE
Map-Matching Api 

### ISSUE THREAD

**Issue by DeveloperNetM** [mapbox/mapbox-navigation-android#1531]
Hey @danesfeder  @Guardiola31337 

I am facing issue when we passed above 100 coordinates.it gives error  "Maximum of 100 coordinates are allowed for this API." 
Kindly please let me know how to pass above 100 coordinates in map matching api.
Because i want to draw custom golf cart route. beacuse there is no option for golf cart route.Currently i am using **Customize  Route using OpenStreet Map(GraphHopper API bicycle path)** 
Here is my Code
[navigationCustomRoute.docx](https://github.com/mapbox/mapbox-navigation-android/files/2580570/navigationCustomRoute.docx)

Please share me all proper steps.How to achive this target

[Please also reply this question, its very urgent ](https://github.com/mapbox/mapbox-navigation-android/issues/1497#issuecomment-437759254)

**Comment by danesfeder** [comment]
Hey @DeveloperNetM 👋 we set this initial limit (100) but this is configurable based on your developer account.  

Tagging @coxchapman and @taraniduncan for account limit help here and going to go ahead and close as non-actionable on the SDK.
