### ISSUE TITLE
Traffic in multiple legs

### ISSUE THREAD

**Issue by kozyr** [mapbox/mapbox-navigation-android#1535]
https://github.com/mapbox/mapbox-navigation-android/blob/3d167ac755b263a411b0ddd806cbc0355d09686d/libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/route/NavigationMapRoute.java#L1119

This code doesn't really make sense to me - it builds traffic for multiple route legs, but always looks at the same LineString that covers the entire route?  Meaning that if first route leg doesn't have traffic, but second one does, the traffic will be shown at the beginning of the route, not at the beginning of the second route leg. Maybe I'm missing something though...

**Comment by danesfeder** [comment]
Hey @kozyr, I'm going to go ahead and close this - I'm not sure if you're seeing an actual issue with the map route as it's drawn on the map or not.  Please feel free to open a ticket if you feel you've found a bug.  Thanks!
