### ISSUE TITLE
Question: How is the user location puck defined

### ISSUE THREAD

**Issue by richjhart** [mapbox/mapbox-navigation-android#1538]
I'm just wondering how the location user puck is defined.

As of 0.22.0, it was defined in a drawable "mapbox_user_puck_icon". This seems to have changed in 0.23.0.

Is there a style option for defining the drawable, or to hide it?

**Comment by Guardiola31337** [comment]
Hey @richjhart 👋 thanks for reaching out and report your question.

I believe you're trying to override https://github.com/mapbox/mapbox-navigation-android/blob/e7a9541a21d3ac4dfd303d1abb6d0e1b5f910a5e/libandroid-navigation-ui/src/main/res/values/styles.xml#L38 which now extends from `mapbox_LocationComponent` https://github.com/mapbox/mapbox-navigation-android/blob/e7a9541a21d3ac4dfd303d1abb6d0e1b5f910a5e/libandroid-navigation-ui/src/main/res/values/styles.xml#L77-L79 and yeah you're right per https://github.com/mapbox/mapbox-navigation-android/pull/1438 we're not using the Location Layer Plugin anymore and the new name from the Maps SDK for the puck is `mapbox_user_icon` 👀 https://github.com/mapbox/mapbox-gl-native/blob/8d0b06d5dd73313724bf5186a244f3ad3e7ba85e/platform/android/MapboxGLAndroidSDK/src/main/res/values/styles.xml#L5

Hope this answer your question.

Thanks again!
