### ISSUE TITLE
Turn By Turn Navigation starts automatically

### ISSUE THREAD

**Issue by surabhimindinfo** [mapbox/mapbox-navigation-android#1549]
I am using your latest SDK for turn by turn navigation in android. I need to ask how to navigate in live location. Right now  when I start the turn by turn navigation it goes to the destination automatically but I want when the user moves it should show the navigation according to it. How to do in android app programmatically.
And also I need to find out when the navigation is stopped can I get information about the drive or travel.

Thanks in advance.

**Mapbox Navigation SDK version:**
    implementation 'com.mapbox.mapboxsdk:mapbox-android-sdk:6.7.1'
    implementation 'com.mapbox.mapboxsdk:mapbox-android-navigation:0.23.0'
    implementation 'com.mapbox.mapboxsdk:mapbox-android-navigation-ui:0.23.0'

**Comment by danesfeder** [comment]
Hey @surabhimindinfo 👋 thanks for checking out the SDK, it sounds like you have simulation enabled which would cause the location on the screen to not reflect the actual location of the device.  

In the future, please direct these types of questions to https://stackoverflow.com/questions/tagged/mapbox or https://www.mapbox.com/contact/support/ and our support team will help you out, thanks!

**Comment by surabhimindinfo** [comment]
but when i disabled simulation it's not showing navigation instruction . Everything goes blank

**Comment by surabhimindinfo** [comment]
Hello,
Thanks for reply , i tried disabling simulation, but when i disable
simulation blank map shown in navigation screen.navigation instruction and
other details are not visible.

Attached screenshot
Thanks
