### ISSUE TITLE
locationComponent.getLastKnownLocation() always null

### ISSUE THREAD

**Issue by billyking991** [mapbox/mapbox-navigation-android#1553]
I'm updating the Android Navigation Libraries from 0.21 to 0.23 and I'm unable to get a current location using the new LocationComponent.  Here is the code from your sample project:

@SuppressWarnings( {"MissingPermission"})
    private void enableLocationComponent() {
        if (PermissionsManager.areLocationPermissionsGranted(this)) {
            // Activate the MapboxMap LocationComponent to show user location
            // Adding in LocationComponentOptions is also an optional parameter
            LocationComponent locationComponent = mapboxMap.getLocationComponent();
            locationComponent.activateLocationComponent(this);
            locationComponent.setLocationComponentEnabled(true);
            // Set the component's camera mode
            locationComponent.setCameraMode(CameraMode.TRACKING);
            originLocation = locationComponent.getLastKnownLocation();
        } else {
            permissionsManager = new PermissionsManager(this);
            permissionsManager.requestLocationPermissions(this);
        }
    }

In this function, originLocation is always null.  Any ideas if what I might be doing wrong?  Thank you for your help!

com.mapbox.mapboxsdk:mapbox-android-navigation-ui:0.23.0

### Steps to trigger behavior

 1.   Make sure the map is ready, via the onMapReady callback.
 2.  Makes sure the app has permission to get the current location.
 3.  Call enableLocationComponent() The code I'm using for this function is the exact same that you've provided in the sample navigation project.  

### Expected behavior
originCoord = new LatLng(originLocation.getLatitude(), originLocation.getLongitude()) should produce an origin coordinate once the LocationComponent gets the last known location.

### Actual behavior
originCoord = new LatLng(originLocation.getLatitude(), originLocation.getLongitude()) crashes the app because originLocation is always null.

**Comment by danesfeder** [comment]
Thanks @billyking991 @jethro-2018 let's continue to track in #1121.  

Updating our services as I pointed out in https://github.com/mapbox/mapbox-navigation-android/issues/1121#issuecomment-441663888 is on our roadmap to be done soon (we have to align with the Maps SDK upstream), thanks for your patience!

**Comment by billyking991** [comment]
Sorry about that!  I had searched to see if other people were having the same issue.  I had missed #1121.  I will follow that one from now on.  I appreciate the update.
