### ISSUE TITLE
Line-join value must be a valid enumeration value

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-navigation-android#156]
A user reported in gl-native that he is seeing:

```
E/mbgl: {APP_PACKAGE_NAME}[JNI]: Error setting property: line-join value must be a valid enumeration value`
```

Since he is not using this property himself, the root cause can be found in this repo.

Original ticket [here](https://github.com/mapbox/mapbox-gl-native/issues/9684)

**Comment by slm** [comment]
I tried with 5.1.2v mapbox and navigation plugin 0.4.0v and got this error again.
