### ISSUE TITLE
Wrong Reroute and invalid location data on onProgressChange

### ISSUE THREAD

**Issue by navdeepg** [mapbox/mapbox-navigation-android#1568]
Hello Team,
 We are facing reroute and wrong location reported issue while testing in downtown. Sometime navigation sdk does unnecessry reroute even if car is moving on original route. Also locations reported by onProgressChange are way off as compare to original location. I've attached csv file for route data reported by onProgressChange function.

My actual route was from 401 W Georgia street to Stanley Park. Original route that navigation sdk provided me was using W. Georgia Street all the way to Stanley Park. I was moving on W. Georgia Street during entire trip. But you can see in data file that navigation reported wring points close to Hornby street and it was off for almost a block from Bute st to Broughton Street. Location is showing up on Alberni street where i was allways driving on W Georgia street.

[39c74939-78c8-4f51-84f0-2dbdd7502c10.xlsx](https://github.com/mapbox/mapbox-navigation-android/files/2630592/39c74939-78c8-4f51-84f0-2dbdd7502c10.xlsx)
  

Android api :27
Mapbox sdk version: 0.23.0

I am using FusedLocationEngine as i was having trip initiation issue. This is something you suggested me earlier. And after navigation view gets initialized i disable Fused location engine. Let me know if i am doing anything wrong here.

Thanks,
Navdeep

**Comment by danesfeder** [comment]
Hey @navdeepg thanks for reporting this, we will look into it on our side and report back.  In the meantime:

> . And after navigation view gets initialized i disable Fused location engine. 

Can you provide some code snippets outlining this implementation?  It sounds like it shouldn't be an issue but it doesn't hurt to double check.  Thanks!

**Comment by danesfeder** [comment]
@navdeepg any updates here with some code snippets?  Thanks!

**Comment by navdeepg** [comment]
Hey Dan,

I am using the FusedLocationEngine.java provided in your GitHub project. I am attaching the sample of EmbeddedNavigationActivity we are using at our end.

Thanks.

**Comment by danesfeder** [comment]
Hey @navdeepg thanks for the code snippet, it helps us dig a bit better.  It sounds like this may be an issue of poor GPS in urban canyons?  Your code snippet looks fine to me - the behavior you're describing happens after driving for a while right, not at the beginning of navigation?  

One thing we can do here to help debug is enable our debug history tracking - this allows us to replay the issues you're seeing.  We created a [`HistoryActivity`](https://github.com/mapbox/mapbox-navigation-android/blob/master/app/src/main/java/com/mapbox/services/android/navigation/testapp/activity/HistoryActivity.java#L28) in our test app that records debug information during a drive with [`StoreHistoryTask`](https://github.com/mapbox/mapbox-navigation-android/blob/master/app/src/main/java/com/mapbox/services/android/navigation/testapp/activity/StoreHistoryTask.java).  

You can pretty much copy this code if you'd like then provide us the `.json` that is outputted onto the device during the drive (note `EXTERNAL_STORAGE` permissions must be enabled).  We will then be able to confirm this is an issue on our side with poor GPS in urban canyons.  

Please respond here with any further questions moving this along and thank you for your patience debugging this issue. 

cc @kevinkreiser

**Comment by danesfeder** [comment]
@navdeepg any updates here?  Anything we can do to help debug?  Do you have the `DirectionsRoute` json used with https://github.com/mapbox/mapbox-navigation-android/files/2630592/39c74939-78c8-4f51-84f0-2dbdd7502c10.xlsx?  We can run the GPX trace against the route and see what kind of behavior we see.

**Comment by navdeepg** [comment]
@danesfeder I don't have DirectionRoute json for the provided gpx file. Although we are planning to use HistoryActivity on same spot and provide you the data. I'll send you the files once I get it.

**Comment by danesfeder** [comment]
@navdeepg awesome thank you - that would be huge to help us debug

**Comment by Guardiola31337** [comment]
Hey @navdeepg 👋 were you able to reproduce using `HistoryActivity`? This will give us better insight into your use case and what could be causing your problem.

**Comment by Guardiola31337** [comment]
Closing as stale.

Thanks for checking out the SDK @navdeepg feel free to cut a new ticket if you can still reproduce OP. In any case, I believe this shouldn't be a problem anymore in `1.0`. Stay tuned for the upcoming beta release 🚀

**Comment by Guardiola31337** [comment]
Hey @navdeepg we've just released [`release_core_1.0.0-rc.1`](https://github.com/mapbox/mapbox-navigation-android/releases/tag/release_core_1.0.0-rc.1) 🎉 🚀 

Please review the [developer documentation](https://docs.mapbox.com/android/beta/navigation/overview/#installation) to start building with the Mapbox core Navigation SDK v1.0 for Android and if you already use an older version of the Navigation SDK, check out [the migration guide](https://github.com/mapbox/mapbox-navigation-android/wiki/1.0-Navigation-SDK-Migration-Guide) to transition your project from the "legacy" core Navigation SDK to the 1.0 version and let us know if you have any questions or run into issues and please open tickets in https://github.com/mapbox/mapbox-navigation-android/issues/new and we will take it from there! We would love your feedback.

Thanks again!
