### ISSUE TITLE
Coverage job may fail due to exit code 127

### ISSUE THREAD

**Issue by springmeyer** [mapbox/mapbox-navigation-android#1598]
I noticed that recent builds on circle have failed like https://circleci.com/gh/mapbox/mapbox-navigation-android/8400 with:

```
:libandroid-navigation:testDebugUnitTest FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':libandroid-navigation:testDebugUnitTest'.
> Process 'Gradle Test Executor 1' finished with non-zero exit value 137
  This problem might be caused by incorrect test process configuration.
  Please refer to the test execution section in the user guide at https://docs.gradle.org/4.6/userguide/java_plugin.html#sec:test_execution
```

I think this might be because the circle machines are low on memory and the test target uses a lot. Perhaps?

I see that `JVM_OPTS: -Xmx3200m` exists in the circle.yml from the beginning: https://github.com/mapbox/mapbox-navigation-android/commit/0725c3b7671584541eafa2e4b4986fe18f16138b#diff-29944324a3cbf9f4bd0162dfe3975d88R15.

Perhaps that amount should be lowered?

**Comment by Guardiola31337** [comment]
@springmeyer not sure if I follow. If we're running into low memory issues, why would we want to lower the `JVM_OPTS` value? Could you clarify?

**Comment by springmeyer** [comment]
@Guardiola31337 exit code 137 is the KILL signal:

```
$ kill -l 137
KILL
```

So, something killed the process. I figure this could either be the operating system OOM killer. Or it could be the java runtime itself. If it were the OOM killer then the cause would be that the process was using enough memory that the system decided to stop it. In this case I think reducing the allowed value could avoid the OOM killer stopping the process.

Now, your question makes me wonder if the JVM itself is detecting that we reached `3200m` of used memory and the JVM itself is killing its own process. In that case we should raise the limit to avoid that.

Do you have a hunch which is happening?

**Comment by andrlee** [comment]
@Guardiola31337 @springmeyer do you want to try running builds with `gradlew --no-daemon` option and check if error persists?
