### ISSUE TITLE
Non-determinate tests of RouteProcessorRunnable.java

### ISSUE THREAD

**Issue by springmeyer** [mapbox/mapbox-navigation-android#1607]
I noticed that the coverage of `RouteProcessorRunnable.java` may flap: meaning that it can differ unpredictably between test runs. This is not ideal: unit tests should run the same code, predictably, ever time.

I noticed this since it failed in a recent coverage job: https://github.com/mapbox/mapbox-navigation-android/pull/1601#issuecomment-444700688

**Comment by danesfeder** [comment]
@springmeyer wow totally, thanks for pointing this out.  Is there a way for us to check the reliability of all of our tests?  How did you narrow down to `RouteProcessorRunnable`?  Thanks!

**Comment by Guardiola31337** [comment]
Is this still an issue in `1.0`?

Closing for now but please @springmeyer feel free to re-open or cut a new ticket if you think this could still be a problem.
