### ISSUE TITLE
Question/Suggestion: Waypoints

### ISSUE THREAD

**Issue by richjhart** [mapbox/mapbox-navigation-android#1613]
Thanks for the new release. Seems to be working for normal circumstances, but we have two edge(ish) cases that potentially prevents from updating just yet, and I wanted to check what the plans are going forward.

If the user follows the correct route to the waypoint, it works fine and skips to the next leg.

The first issue occurs if the user skips part of the route, which is not (necessarily) not allowed for us. In this case, `isValidDistanceRemaining` stays false because the `currentStatus.getRemainingLegDistance()` in `RouteProcessorRunnable.checkForNewLegIndex()` is too high (I'm not quite sure what happens to `currentState`).

The second issue occurs if the user does not hit the waypoint exactly. Again, this is not necessarily a problem for us.

In both cases, the ideal solution for us would be some way of having public access to `MabpoxNavigator.updateLegIndex()` - so we can use our own algorithm to work out whether skipping to the next leg is OK.

There should be other possibilities I can suggest if that is not possible, but I would have thought that might actually be the simplest and most flexible method anyway.

**Comment by danesfeder** [comment]
Hey @richjhart 👋 - yeah you're right here.  `isValidDistanceRemaining` is not a great setup and can definitely cause the issues you're describing.  #1604 was implemented so way points would no longer be broken completely.  

We are working on some refactoring to our route-following logic that would address the scenarios you described and then, once this is ready, we would provide a callback to you that, when implemented, would basically keep asking you if you want to advance the index (return `true` or `false`).  

So for example if we detect arrival, and you want to _not_ "auto-increment" the index like for some sort of UI / UX, you can return `false` until your UI / UX has finished, etc. 

Thanks for your patience while we iterate on these APIs - I know you've stuck it out for a while now 😄 We appreciate the feedback! 

cc @kevinkreiser

**Comment by richjhart** [comment]
@danesfeder The true/false callback would certainly be great and as long as it gets called - at a minimum - whenever the user hits a waypoint, then that should allow us to upgrade to it.

But it would be ideal if we could unilaterally call it at any point (we might detect that the user has missed the waypoint, but that that's OK).

Or are you saying the callback would be continually called (similar to or part of the `ProgressChangeListener`)? Just thinking aloud, that would actually be really useful - continual callback that provides a hint of whether the Navigator thinks the leg should progress or not, but that can be overridden by us.

**Comment by danesfeder** [comment]
> continual callback that provides a hint of whether the Navigator thinks the leg should progress or not, but that can be overridden by us.

@richjhart yeah we can still decide on a final interface, but this sounds along the lines of what I was thinking.  

```
  private class ExampleLegIndexUpdateListener implements LegIndexUpdateListener {
    @Override
    public boolean shouldUpdate(RouteProgress routeProgress, boolean hasArrived) {
      return hasArrived && routeProgress.distanceRemaining() < 15;
    }
  }

  public interface LegIndexUpdateListener {
    boolean shouldUpdate(RouteProgress routeProgress, boolean hasArrived);
  } 
```

Given `shouldUpdate` is called every time we update progress (every second currently, same as `ProgressChangeListener`).

**Comment by richjhart** [comment]
@danesfeder Yep that looks like pretty much exactly what we're after. I assume hasArrived would be referring to the current leg, rather than the overall route?

I would just wonder if the location would be useful as well (I'm not sure though, routeProgress should probably be enough)

**Comment by danesfeder** [comment]
>  I assume hasArrived would be referring to the current leg

@richjhart correct, we can be more specific in the final API with something like `hasArrivedAtWayPoint`.  And yeah `Location` info (snapped or raw?) wouldn't hurt to include either.

**Comment by richjhart** [comment]
@danesfeder sounds good! In terms of snapped or raw location, we tend to use the raw location more often, but we do it via a listener on our custom location engine anyway. Since we have that via other means, the snapped location might be more useful as that way we actually have both. Not sure which one other people would consider most useful.

**Comment by danesfeder** [comment]
@richjhart the callback / listener setup we originally discussed #1613 proved to be a bit messier than I originally anticipated.  Aligned with the original setup you described in the OP, I cut #1643.  Let me know what you think and we can discuss further.

**Comment by richjhart** [comment]
@danesfeder On the surface, that option looks fine - we were going to implement our own algorithm regardless, and this idea works with that.

I won't actually be working on this until the new year, so I wouldn't be able to test it just yet, but would be looking to do so very soon after I get back if it's available then.
