### ISSUE TITLE
Offline Route in Mapbox navigation 0.24.0 -  Error occurred downloading tiles: null file

### ISSUE THREAD

**Issue by YingInfo** [mapbox/mapbox-navigation-android#1618]
I couldn't download offline routes in local storage. 

Access token and boundingBox variables are  correct, but failed to download and I got this message.

*Error occurred downloading tiles: null file*

BoundingBox boundingBox = BoundingBox.fromLngLats(bounds.getLonWest(), bounds.getLatSouth(), bounds.getLonEast(), bounds.getLatNorth());
        OfflineTiles.Builder builder = OfflineTiles.builder().version(offlineVersions.get(0)).accessToken(Mapbox.getAccessToken()).boundingBox(boundingBox);
        MapboxOfflineRouter offlineRouter = new MapboxOfflineRouter("");
        offlineRouter.downloadTiles(builder.build(), new RouteTileDownloadListener() {

            @Override
            public void onError(@NonNull OfflineError error) {
                endProgress(error.getMessage());
            }

            @Override
            public void onProgressUpdate(int percent) {
                setPercentage(percent);
            }

            @Override
            public void onCompletion() {
                endProgress(getString(R.string.end_progress_success));
            }
        });

**Comment by danesfeder** [comment]
Hey @YingInfo @ngtrunghieu 👋 some of our error reporting was improved in #1620 - to download offline tiles, you need an upgraded access token as this is a paid feature.  You can contact support@mapbox.com to talk about the cost associated with this.  Thanks for understanding!  Going to close here as non-actionable on our part.

**Comment by ngtrunghieu** [comment]
Thank you sir. 👍

**Comment by YingInfo** [comment]
Thank you for your help @danesfeder
