### ISSUE TITLE
Implement parceable in options and routeProgress

### ISSUE THREAD

**Issue by cammace** [mapbox/mapbox-navigation-android#162]

**Comment by cammace** [comment]
Note that this is blocked until MAS 3.0 gets released with support for autovalues and parcelable

**Comment by danesfeder** [comment]
Not seeing this as a current requirement or issue within the SDK.  Going to close - can reopen if needed in the future.

**Comment by cammace** [comment]
This is actually super simple to add support for since both classes use AutoValue. Just use [this library](https://github.com/rharter/auto-value-parcel) and slap `implements Parcelable` on both classes.

**Comment by danesfeder** [comment]
I don't think this will work if we are using objects that aren't Parcelable within the object that we are trying to make Parcelable (like the interface for the [custom notification]( https://github.com/mapbox/mapbox-navigation-android/blob/master/libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/MapboxNavigationOptions.java#L54-L57)).  We would have to write custom TypeAdapters to address this or ensure that all objects in the classes are Parcelable.
