### ISSUE TITLE
Feature request: make directions profiles adaptable

### ISSUE THREAD

**Issue by wbearand** [mapbox/mapbox-navigation-android#1623]
I am working on a prototype which retrieves directions and also uses map matching. In both cases you have to pass a profile (driving-traffic, driving, walking, cycling) as in here:
https://www.mapbox.com/api-documentation/#directions

Is there any way to adapt those rules defined in the profiles, eg. tell the router to route against a one-way? A workaround would be to use the walking profile I think, but that of course has side effects like different instructions.. . Or is the only way to use a custom router?

**Comment by danesfeder** [comment]
Hey @wbearand I don't believe this type of functionality is currently available, but will defer to @coxchapman to see if he has any other thoughts on the matter.  Thanks!

**Comment by danesfeder** [comment]
@wbearand because this isn't a feature we currently support, I'm going to go ahead and close this.  We are noting this internally as a feature request with our routing team (we don't have a public forum for this at the moment).  Thank you for your understanding!
