### ISSUE TITLE
Upgrade to Mapbox Streets source v8

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-navigation-android#1624]
mapbox/mapbox-gl-native#13481 adds support for [Mapbox Streets source v8](https://www.mapbox.com/vector-tiles/mapbox-streets-v8/), which is currently in beta. By the time map SDK v7.0.0 comes out, we’ll need to add corresponding support for Streets source v8; otherwise, anyone using a v8-dependent style will incur twice as much overhead from vector tile downloading and processing, while map labels and the current road name label will go blank. We’ll want to retain support for v7 for the time being, since some popular navigation styles still use v7.

As far as I can tell, here are the changes we’ll need to make to accommodate both v7 and v8:

* [x] Add Streets source v8 instead of v7: https://github.com/mapbox/mapbox-navigation-android/blob/4ab858b4cad93b0abfa64b9074e38281787b97c8/libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/map/NavigationMapboxMap.java#L69
* [x] Check if Streets source v8 is already part of the style, if so don't add: https://github.com/mapbox/mapbox-navigation-android/blob/4ab858b4cad93b0abfa64b9074e38281787b97c8/libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/map/NavigationMapboxMap.java#L601-L602
* [x] If Streets source v7 is already part of the style, add v7 instead: https://github.com/mapbox/mapbox-navigation-android/blob/4ab858b4cad93b0abfa64b9074e38281787b97c8/libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/map/NavigationMapboxMap.java#L601-L602
* [x] Use the `road` layer instead of `road_label` when the style contains Streets source v8: https://github.com/mapbox/mapbox-navigation-android/blob/4ab858b4cad93b0abfa64b9074e38281787b97c8/libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/map/NavigationMapboxMap.java#L71

Unlike in mapbox/mapbox-navigation-ios#1896, it looks like the Android navigation SDK always adds a vector tile source for Streets source v8, without checking whether Streets source is already part of the style. That’s a problem because the SDK would end up downloading tiles for two different versions of the Streets source simultaneously, significantly increasing bandwidth consuption.

Does the Android navigation SDK automatically localize labels like on iOS? If so, there may need to be some changes to account for different language fallback mechanisms between v7 and v8.

/cc @mapbox/navigation-android @mapbox/maps-android @brsbl @taraniduncan

**Comment by danesfeder** [comment]
@1ec5 thanks for cutting this / setting up the checklist - I edited the second task to include: 

> it looks like the Android navigation SDK always adds a vector tile source for Streets source v8, without checking whether Streets source is already part of the style

I don't think we do any automatic localization.  If we need to add this, I think we should cut a new ticket for that effort.

**Comment by 1ec5** [comment]
Yeah, localization is a separate feature (and a separate plugin on Android). The tasks above are relevant because of how we’re adding the source unconditionally for the road name label.

**Comment by 1ec5** [comment]
> anyone using a v8-dependent style will incur twice as much overhead from vector tile downloading and processing, while map labels and the current road name label will go blank

This would become more likely in v4.7.0, once mapbox/mapbox-gl-native#13585 adds easily discoverable accessors for v8-powered styles.
