### ISSUE TITLE
VoiceInstructionCache does not get initialized with injected Speechplayer 

### ISSUE THREAD

**Issue by skienzl** [mapbox/mapbox-navigation-android#1625]
**Mapbox Navigation SDK version:** 0.24.1

### Steps to trigger behavior

 1. inject Speechplayer in NavigationViewOptions
 2. startNavigation on NavigationView
 3. crash

As far as i can tell crash happens because of injecting a speechplayer in the NavigationViewOptions in [NavigationViewModel:271](https://github.com/mapbox/mapbox-navigation-android/blob/07c853d5a4145a4ae8c77af5095e12982ca76380/libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/NavigationViewModel.java#L271). 
If speechplayer is not null the `voiceInstructionCache` does not get initialized and therefore crashes in  [NavigationViewModel:412](https://github.com/mapbox/mapbox-navigation-android/blob/07c853d5a4145a4ae8c77af5095e12982ca76380/libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/NavigationViewModel.java#L412).

**Comment by Guardiola31337** [comment]
Hey @skienzl 👋 thanks for bringing this to us, great catch!

Fix for OP in https://github.com/mapbox/mapbox-navigation-android/pull/1627

Thanks for your patience!

**Comment by skienzl** [comment]
@Guardiola31337 thx for fixing :)

**Comment by skienzl** [comment]
Fixed it. Thank you for the quick support!

**Comment by Guardiola31337** [comment]
> Fixed it. Thank you for the quick support!

Awesome! Thanks for the update!
