### ISSUE TITLE
Get route without map

### ISSUE THREAD

**Issue by alvaromarco** [mapbox/mapbox-navigation-android#1632]
Is it possible to obtain a route and use the callbacks to perform a navigation **WITHOUT** a map (NavigationView)? That is, I want turn by turn navigation instructions and route information to make my custom view.

In the example: 
`
val options = NavigationViewOptions.builder()
            .navigationListener(this)
            .directionsRoute(directionsRoute)
            .shouldSimulateRoute(true)
            .progressChangeListener { location, routeProgress ->
                setSpeed(location)
            }
            .instructionListListener { visible ->
                instructionListShown = visible
                speed_limit.visibility = if (visible) View.GONE else View.VISIBLE

            }
            .speechAnnouncementListener { announcement ->
                "All announcements will be the same."
            }
            .bannerInstructionsListener { announcement ->
                announcement
            }
navigationView.startNavigation(options.build())`

But I don't need a navigationView, it is possible?

**Comment by danesfeder** [comment]
@alvaromarco yeah definitely!  Check out this example https://github.com/mapbox/mapbox-navigation-android/blob/master/app/src/main/java/com/mapbox/services/android/navigation/testapp/activity/navigationui/ComponentNavigationActivity.java

Thanks for checking out the SDK!
