### ISSUE TITLE
Navigation View Start showing You will arrive without additional info

### ISSUE THREAD

**Issue by navdeepg** [mapbox/mapbox-navigation-android#1633]
Navigation view start showing "You will Arrive" close to end to destination and does not give additional information on UI.

Android API : 27
Mapbox : 0.23.0

Steps. Book a trip using embedded navigation and check top bar when trip is about to complete.

**Comment by danesfeder** [comment]
Hey @navdeepg, if you are looking to provide further information about your destination in the arrival UI, check out "waypoint names" when requesting a `DirectionsRoute` 

https://github.com/mapbox/mapbox-navigation-android/blob/master/libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/NavigationRoute.java#L469-L482

Thanks!
