### ISSUE TITLE
Get image from InstructionView

### ISSUE THREAD

**Issue by alvaromarco** [mapbox/mapbox-navigation-android#1641]
I use MapboxNavigation with milestoneEventListener and ProgressChangeListener. Not use a map view, only InstructionView to show instructions from the route. 

I need the image about maneuver but I can't find this image. I try from components in primary instruction but always is null.  Where I can find the image?

`override fun onMilestoneEvent(routeProgress: RouteProgress, instruction: String, milestone: Milestone) {
       val bannerInstructionMilestone = milestone as BannerInstructionMilestone
       val instructions = bannerInstructionMilestone.bannerInstructions
       val primary = instructions.primary()

       if (primary?.components()?.isNotEmpty() == true) {
            primary.components()?.forEach { bannerComponent ->
                if (!bannerComponent.imageBaseUrl().isNullOrEmpty()) {
                    val image = bannerComponent.imageBaseUrl()

                }
            }
        }

}
`

**Comment by danesfeder** [comment]
Hey @alvaromarco 👋 we used the `ManeuverView` custom `View` to dynamically draw the icon based on the `StepManeuver` type + modifier.  Check out that code and see if it helps!  Thanks for checking out the SDK, going to go ahead and close here as non-actionable on our part.
