### ISSUE TITLE
Problem with recenter animation duration

### ISSUE THREAD

**Issue by siavashabdoli** [mapbox/mapbox-navigation-android#1648]
**Mapbox Navigation SDK version:23.0.0**

### Steps to trigger behavior

 1. swipe on map and change zoom and location of camera in navigation page
 2. click on recenter
 3. it takes almost 4 seconds for camera to get stable state on target.

### Expected behavior
change animation time and avoid the slow animate part in end of animation(just for recenter! or at least make it faster)
### Actual behavior
it sometime takes 4 seconds and user may miss the exit.

I couldn't find any attribute related to this animation. as I can see the code it should maximum take 1500 millisecond but I test it with stopwatch and it takes more than that

**Comment by siavashabdoli** [comment]
there's a architecture decision that I can't understand here. I would be happy if someone can explain it. why lots of logic that belongs to navigation must be in `LocationComponent`  and that class is placed in mapbox sdk. seems the locationComponent have lot to do in different context and it violate SRP in both class level and module level.

**Comment by zeallat** [comment]
I have same problem

**Comment by Guardiola31337** [comment]
Hey @siavashabdoli and @zeallat thanks for reaching out and report this.

Current release version is [`0.26.0`](https://github.com/mapbox/mapbox-navigation-android/releases/tag/v0.26.0). To confirm that the issue is still present in the latest version, would you mind retesting it using `0.26.0` version?

Also it'd be 💯 if you could provide a video reproducing OP. This will give us better insight into what could be causing your problem. Thanks in advance!

**Comment by danesfeder** [comment]
@siavashabdoli @zeallat are either of you able to capture this unwanted behavior with a `.gif`?  It will help us with reproducing / addressing, giving us a better idea of what's going on here.  Thanks!

**Comment by siavashabdoli** [comment]
I changed my tilt and zoom level and camera position and then click on recenter. as you can see it takes about 5 seconds.
[video_2019-01-08_12-01-48.mp4.zip](https://github.com/mapbox/mapbox-navigation-android/files/2735805/video_2019-01-08_12-01-48.mp4.zip)

**Comment by danesfeder** [comment]
Thanks @siavashabdoli, we can work off of that.  We will update this ticket once we find a solution.

**Comment by siavashabdoli** [comment]
@danesfeder you're welcome. one reason that we find recently is `mapbox_trackingAnimationDurationMultiplier` and the default value is 2. I try 0.5 for this but then I had problem with smoothness of animations. also 1.5 seconds (the max duration limit of animation) multiply 2 can't be equal 5 seconds :D

**Comment by danesfeder** [comment]
Yeah I think this has something to do with incoming `Location` updates "resetting" the recenter animation somehow.  If you look closely, there are several "bumps" in the animation as it happens.  I believe these are interruptions, like the duration being reset.  I need to dig further. 

On a side note, the UI customizations you've done look great.  Awesome work!

**Comment by siavashabdoli** [comment]
Yeah I know; It cause some other bug in zoom level; we have changed `isForceUpdate` logic for that because the animation is not completed and `isForceUpdate` is false sometimes it stuck on high level. My colleague supposed to report that but as we have some deadlines now, we fix that temporarily in our code.
The logic is: if difference between calculated target zoom and current zoom is greater than 0.5 then update zoom level. I think this is somehow naive but it avoid zoom level bug for now and it's on production.
