### ISSUE TITLE
Can't recenter map before receive new location

### ISSUE THREAD

**Issue by zeallat** [mapbox/mapbox-navigation-android#1649]
**Android API: 28
**Mapbox Navigation SDK version: 0.26.0

### Steps to trigger behavior

 1. Run Navigation with route
 2. Modify map padding (with MapboxMap::setPadding())
 3. recenter map
(call NavigationCamera::resetCameraPositionWith() or NavigationMapboxMap::resumeCamera(). I have tried two of both.)
(with mode tracking gps)
4. weak gps.(new gps location is not received.)

### Expected behavior
Recenter map asap.(with last known location)

### Actual behavior
Recenter map after new gps location received.

**Comment by Guardiola31337** [comment]
Hey @zeallat 👋 Thanks for reaching out and report your issue.

Would you mind providing a video reproducing OP? This will give us better insight into what could be causing your problem. Also if there is any sample or pseudo code you can provide, that would be really helpful. Thanks in advance!

**Comment by zeallat** [comment]
Thanks for response @Guardiola31337 .
Then I will close this issue until I can produce what you request.
Thanks!
