### ISSUE TITLE
Mapbox NavigationView Lagging at Start of Navigation

### ISSUE THREAD

**Issue by billyking991** [mapbox/mapbox-navigation-android#1650]
I've created a NavigationView in an Activity using this tutorial:

https://www.mapbox.com/android-docs/navigation/overview/navigation-ui/#navigationview-activity-example

However, I'm getting complaints from users who say the navigation is lagging and it takes a while for the app to catch up after they start the navigation (i.e. Start navigation and then wait up to 2 minutes for the app to actually start giving directions, often after driving for a while).  I've found, through testing, that if I start navigation while I'm driving and on a road, it catches up quickly and starts giving voice instructions, but if I start in a parking lot, often times the navigation instructions won't start playing until I'm as mile or so down the road.  It's almost like the NavigationView has frozen.  This happens across all of my devices running different Android SDKs from 7.0 - 9.0.

My code looks exactly like what you have listed for the Activity tutorial except for a few differences:

@Override
    public void onNavigationReady(boolean isRunning) {
        getRoute(originPoint, destinationPoint);
}

private void getRoute(Point origin, Point destination) {
        String navTypeFormat = getNavigationType();
        String unitsFormat = getUnits();

        progressBar.setVisibility(View.VISIBLE);
        loadingText.setVisibility(View.VISIBLE);

        NavigationRoute.builder(mContext)
                    .accessToken(Mapbox.getAccessToken())
                    .origin(origin)
                    .destination(destination)
                    .profile(navTypeFormat)
                    .language(Locale.ENGLISH)
                    .voiceUnits(unitsFormat)
                    .build()
                    .getRoute(new Callback<DirectionsResponse>() {
                        @Override
                        public void onResponse(Call<DirectionsResponse> call, Response<DirectionsResponse> response) {
                            Timber.d("Response code: %s", response.code());
                            if (response.body() == null) {
                                showNoResponseAlert();
                                return;
                            } else if (response.body().routes().size() < 1) {
                                showNoRoutesAlert();
                                return;
                            }

                            currentRoute = response.body().routes().get(0);

                            NavigationViewOptions.Builder navigationViewOptions = NavigationViewOptions.builder();
                            navigationViewOptions.directionsRoute(currentRoute);
                            navigationViewOptions.navigationListener(NavigationActivity.this);
                            navigationViewOptions.milestoneEventListener(NavigationActivity.this);
                            navigationViewOptions.speechAnnouncementListener(NavigationActivity.this);
                            navigationViewOptions.bannerInstructionsListener(NavigationActivity.this);
                            navigationViewOptions.routeListener(NavigationActivity.this);
                            navigationViewOptions.shouldSimulateRoute(false);

                            progressBar.setVisibility(View.INVISIBLE);
                            loadingText.setVisibility(View.INVISIBLE);

                            navigationView.startNavigation(navigationViewOptions.build());
                        }

                        @Override
                        public void onFailure(Call<DirectionsResponse> call, Throwable throwable) {

                            progressBar.setVisibility(View.INVISIBLE);
                            loadingText.setVisibility(View.INVISIBLE);

                            showNoRoutesAlert();
                        }
                    });
}

It is calculating the route just fine, but doesn't start navigating for a while after the NavigationView appears.  It's almost like the NavigationView is frozen if I start the navigation in a parking lot and off a main road.  iOS doesn't do this.  Any ideas why it might be happening on Android?  Please let me know what you need from me.  I'd love to get this fixed because it is one issue that users are noticing.

**Android API:**
This happens on Android 8 and 9.
**Mapbox Navigation SDK version:**
implementation 'com.mapbox.mapboxsdk:mapbox-android-navigation-ui:0.26.0' (Also happens on all previous versions of the Android Nav SDK)

### Steps to trigger behavior

 1.  Open the app in a parking lot.
 2.  Choose an address to navigate to.
 3.  Allow the NavigationView to appear and calculate the route.
4.  Start driving.

### Expected behavior
I should start seeing the map orient to the direction I'm heading when I start driving.  The voice instructions should either start immediately or as soon as I hit the main road.

### Actual behavior
The app seems to freeze if I start navigating in a parking lot, driveway, or off a main road.  Sometimes I have to drive a mile or two before it wakes up and catches up to where I am.

**Comment by Guardiola31337** [comment]
Hey @billyking991 👋 thanks for reaching out and report your issue.

In [`v0.20.0`](https://github.com/mapbox/mapbox-navigation-android/releases/tag/v0.20.0) we introduced a new route-following library and I believe the issue you're describing is caused because it needs to be "exactly" on the route for navigation to begin i.e. navigation is started after getting some confidence that you're moving forward a "valid" route. We are working on a solution that handles the scenarios you are encountering here, it's definitely on our radar!

For debugging / testing purposes, would you mind sharing coordinates that reproduce the above-mentioned scenarios? That would be really helpful.

Thanks for your understanding and patience! We appreciate the feedback!

cc @kevinkreiser

**Comment by billyking991** [comment]
I appreciate the response.  I believe what I'm seeing is definitely what you are describing.  Unfortunately, once I'm on the actual route, it is taking a minute or two to wake up and catch up to where I'm going.  The two devices I'm using are the Samsung Note 8 (OS 8.0.0) and the Google Pixel (OS 9.0), so fairly powerful devices.  The two coordinates I've been mainly testing are:

My driveway: (41.283138, -72.501848)
The YMCA parking lot: (41.294355, -72.434617)

This has happened in other locations as well, as long as I've started the navigation in a parking lot.  The app always catches up after a minute or two, but I'm navigating blindly until the app finally catches up.  

Thank you so much for responding and looking into this.  I will keep developing other features while you are looking into this.  I look forward to getting this figured out.  Please let me know if you need anything else.

**Comment by danesfeder** [comment]
@billyking991 this could be related to a delay of location updates from the device - please see https://github.com/mapbox/mapbox-navigation-android/issues/1469#issuecomment-442450591.

Would you be able to initialize a `FusedLocationEngine` and pass it to `NavigationViewOptions#locationEngine`?  That may help with the initial delay here. Thanks!

**Comment by Guardiola31337** [comment]
@danesfeder you beat me to follow up here 😅 

> Unfortunately, once I'm on the actual route, it is taking a minute or two to wake up and catch up to where I'm going.

> The app always catches up after a minute or two

Although the new route-following library waits to get confidence about where you are in the world, it wouldn't wait 2 minutes so it seems that you're definitely experiencing the same issue seen in https://github.com/mapbox/mapbox-navigation-android/issues/1469#issuecomment-442450591 as @danesfeder pointed out.

> Our team that works on this library has already done some refactoring to address this, but the Navigation SDK is blocked at the moment while these changes land in the Maps SDK upstream first.

For extra context ☝️ is moving in https://github.com/mapbox/mapbox-navigation-android/pull/1615

@billyking991 could you please retest using the above-mentioned [`FusedLocationEngine`](https://github.com/mapbox/mapbox-navigation-android/blob/master/app/src/main/java/com/mapbox/services/android/navigation/testapp/activity/location/FusedLocationEngine.java) and report back if it solves your issue? Thanks again!

**Comment by billyking991** [comment]
Hey Guys,  Thank you for the responses.  I see the FusedLocationEngine in the test app.  Is the FusedLocationEngine part of the mapbox libraries?  I may be getting confused with Google's FusedLocationProviderClient.  Is there an example somewhere demonstrating the use of the Mapbox FusedLocationEngine?

**Comment by billyking991** [comment]
From the link above, it looks like I can just create a FusedLocationEngine like you have in the test app, correct?  I just want to make sure I'm doing it correctly.  Android is not my main platform, so changes are slower for me than on iOS.  I apologize for that.

**Comment by Guardiola31337** [comment]
> Is the FusedLocationEngine part of the mapbox libraries?

Not yet, as commented

> Our team that works on this library has already done some refactoring to address this, but the Navigation SDK is blocked at the moment while these changes land in the Maps SDK upstream first.

and the work on our side is moving in https://github.com/mapbox/mapbox-navigation-android/pull/1615

> Is there an example somewhere demonstrating the use of the Mapbox FusedLocationEngine?

Yeah, you can 👀 [`ComponentNavigationActivity`](https://github.com/mapbox/mapbox-navigation-android/blob/master/app/src/main/java/com/mapbox/services/android/navigation/testapp/activity/navigationui/ComponentNavigationActivity.java) from the test app (especially 👀 [`initializeLocationEngine()`](https://github.com/mapbox/mapbox-navigation-android/blob/3fbb8c988faf5c4bccc11ed7b01c49ce08f14ce1/app/src/main/java/com/mapbox/services/android/navigation/testapp/activity/navigationui/ComponentNavigationActivity.java#L329).

> it looks like I can just create a FusedLocationEngine like you have in the test app, correct? 

Yeah, you can create [`FusedLocationEngine`](https://github.com/mapbox/mapbox-navigation-android/blob/master/app/src/main/java/com/mapbox/services/android/navigation/testapp/activity/location/FusedLocationEngine.java) and [`ForwardingLocationCallback`](https://github.com/mapbox/mapbox-navigation-android/blob/master/app/src/main/java/com/mapbox/services/android/navigation/testapp/activity/location/ForwardingLocationCallback.java) equivalent classes and include them into your project, then is as simple as grabbing the new engine, configuring it and setting it via `NavigationViewOptions#locationEngine`.

> I just want to make sure I'm doing it correctly. Android is not my main platform, so changes are slower for me than on iOS. I apologize for that.

No worries at all! I hope this helps a bit, thanks!

**Comment by billyking991** [comment]
It definitely does.  Thank you so much for the update and additional details.  I've found the classes and have added them to my project.  I can report that, with some initial testing, I'm seeing no lag and much better results.  I really appreciate the help.  Once I do some more testing, I'll get the app updated in the store.  Thank you!!

**Comment by Guardiola31337** [comment]
Nice, glad to hear that's working better now @billyking991 Thanks for the update!

I'm going to close here now as resolved. Thanks for the feedback and stay tuned for when https://github.com/mapbox/mapbox-navigation-android/pull/1615 lands and gets released so you will be able to use the standalone engine from the upstream library and not rely on the this workaround anymore.
