### ISSUE TITLE
Compilation issue with navigation 26 and mapbox core 1.1.0

### ISSUE THREAD

**Issue by Christophe668** [mapbox/mapbox-navigation-android#1656]
Depedencies versions : 

<img width="618" alt="screen shot 2019-01-09 at 18 05 42" src="https://user-images.githubusercontent.com/1552554/50915503-3a944e00-1439-11e9-86e1-38bf87cc03fa.png">

Error : 
`com.mapbox.android.core.location.LocationEngine(classpath class)` used as super class of `com.mapbox.services.android.navigation.v5.location.replay.ReplayRouteLocationEngine`

In the core library `LocationEngine` in an interface and apparently in navigation 26, the class `ReplayRouteLocationEngine`seems to try to extend from it. Making it impossible to compile.

*LocationEngine*
```
public interface LocationEngine {

```

*ReplayRouteLocationEngine*
```
public class ReplayRouteLocationEngine extends LocationEngine implements Runnable {
```

**Comment by danesfeder** [comment]
Hey @Christophe668 👋 we are not compatible with Maps SDK 7.0 Events 4.0 at this time, but are actively working on this in https://github.com/mapbox/mapbox-navigation-android/pull/1615 please keep an eye on this / our next release and thank you for your patience!
