### ISSUE TITLE
Request: Time labels on routes

### ISSUE THREAD

**Issue by cmahopper** [mapbox/mapbox-navigation-android#1664]
It would be great to have labels on all routes shown on the map (current and alternatives) like in other navigation apps (like Google Maps) that shows the time the route will take in little "speech bubbles". Of course, this should probably be an option to disable.

**Comment by Guardiola31337** [comment]
Hey @cmahopper 👋 thanks for reaching out.

We are working on a solution for supporting "callouts", it's definitely on our radar! You can 👀 https://github.com/mapbox/mapbox-navigation-android/issues/1358 https://github.com/mapbox/mapbox-navigation-android/issues/1359 https://github.com/mapbox/mapbox-navigation-android/issues/1360 https://github.com/mapbox/mapbox-navigation-android/issues/1383

In the meantime, feel free to test out https://github.com/mapbox/mapbox-navigation-android/pull/1339 (at the moment part of the test app) and provide any feedback.

Thanks again!

Closing here as duplicated.

**Comment by cmahopper** [comment]
@Guardiola31337 Damn, I tried searching for it because I remembered seeing it somewhere, I just didn't think of "callouts". Well, at least now someone else may find this issue through searching :)

Thanks!
