### ISSUE TITLE
ExampleActivity CompassView leak

### ISSUE THREAD

**Issue by Guardiola31337** [mapbox/mapbox-navigation-android#1671]
Run into the following leak when running the [`ExampleActivity`](https://github.com/mapbox/mapbox-navigation-android/blob/master/app/src/main/java/com/mapbox/services/android/navigation/testapp/example/ui/ExampleActivity.kt) from the test app 👀 

![example_activity_leak_1](https://user-images.githubusercontent.com/1668582/51180951-1ec1f980-18ca-11e9-98e1-ebb254fa98f9.png)

![example_activity_leak_2](https://user-images.githubusercontent.com/1668582/51180956-22ee1700-18ca-11e9-92d5-1cf80cf241d2.png)

**Comment by danesfeder** [comment]
The `CompassView` is in the Maps SDK 🤔

**Comment by Guardiola31337** [comment]
> The `CompassView` is in the Maps SDK 🤔

You're completely right. Could you take a look at it @LukasPaczos? It seems the `ViewPropertyAnimator` linked to `CompasView` is causing leaks in some scenarios.

I'll cut a ticket in [`mapbox-gl-native`](https://github.com/mapbox/mapbox-gl-native) and close here.

**Comment by Guardiola31337** [comment]
Following up in https://github.com/mapbox/mapbox-gl-native/issues/13742

Closing here.
