### ISSUE TITLE
0.5.0 snapshot not uploaded

### ISSUE THREAD

**Issue by davols** [mapbox/mapbox-navigation-android#168]
The README mentions `  compile 'com.mapbox.mapboxsdk:mapbox-android-navigation:0.5.0-SNAPSHOT'` for the latest release. 
0.5.0 isn't uploaded on sonatype so the gradle sync fails.

**Comment by langsmith** [comment]
Hi @davols , thanks for bringing this to our attention. The nightly build failed to upload to Maven and we need to tweak some things so that keys are correctly fetched for upload. We should be good to go by next Mon/Tues.

**Comment by dgadelha** [comment]
@langsmith isn't navigation-ui also supposed to be uploaded? so we can access the resources without duplicating them? also, when turn-by-turn will be available for android?

**Comment by davols** [comment]
Uploaded now on sonatype. Closing.
