### ISSUE TITLE
Custom LocationEngine is not always respected

### ISSUE THREAD

**Issue by richjhart** [mapbox/mapbox-navigation-android#1694]
**Android API:** 28 (Android 9)
**Mapbox Navigation SDK version:** 0.27.0

### Steps to trigger behavior

 1. Provide a custom location engine (in this case based off a ReplayRouteLocationEngine) in the NavigationViewOptions options
 2. Begin navigation (using the custom LocationEngine)

### Expected behavior

At all times, the route position is based on the locations provided by the custom LocationEngine. In our case it should exactly follow the route provided

### Actual behavior

At the start of navigation, and on a few occasions throughout the route, the "route" location suddenly jumps to the user's real physical location before jumping back to the simulated position.

In general, this doesn't cause us too much problem as it's only very brief, but it is very strange and suggests that somehow the real GPS location is getting to the Navigation Engine, even though it should never be provided by a ReplayRouteLocationEngine.

I'm still in the process of putting some logging it to try to "catch" where it comes from.

**Comment by richjhart** [comment]
Update: It seems in might only be a visual thing.

I have setup some logging to make it clear if the snapped location (in `ProgressChangeListener.onProgressChange()`), or the "real" location (from `LocationEngineCallback<LocationEngineResult>.onSuccess(LocationEngineResult result)` ever gives a value that doesn't match the route. (I have deliberately provided a route which is only in positive longitudes, while I'm in a negative longitude).

At the start, and a couple of times during the simulated route, the snapped location puck jumped back to my real location, but the locations seen by our code never did.

I've looked in the latest mapbox code and I notice that the layers that contain the snapped location puck (mapbox-location-shadow, etc), don't seem to appear in the code. Is this now handled elsewhere?

**Comment by richjhart** [comment]
@danesfeder I will try to capture it when I get a chance - though it's possible it's the same as #1678 and maybe I just had something wrong with the debug code so missed it, or in our setup it behaves a bit differently.

The reason we're doing it this way is that we have three modes for development: normal, simulated, and manual. In both normal and simulated we want to be able to switch to manual so our LocationEngine is a wrapper which then either uses a real location engine or a replay engine. At any point we can shut down and ignore that one and use our own manual location.

**Comment by danesfeder** [comment]
@richjhart As of #1615, the `NavigationView` just decides which `LocationEngine` to give to `MapboxNavigation` https://github.com/mapbox/mapbox-navigation-android/blob/master/libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/location/LocationEngineConductor.java

Although maybe in this case, re-assigning the route (for replay) or some of that logic is throwing something off.

**Comment by richjhart** [comment]
Of course now that I've tried to record the issue, it hasn't been happening. I'll keep an eye on it.

Nope that I am still just providing a single LocationEngine at the start. It's just that that LocationEngine may have another one underneath it.

**Comment by danesfeder** [comment]
@richjhart this ticket got me thinking and sure enough I believe I found a bug.  In `NavigationMapboxMap` we were allowing the `LocationComponent` to activate a default `LocationEngine` in the background.  So what seems to be happening here is with the replay engine, your phone is obviously sitting in the same spot.  

This means we have competing updates from the default engine in the component and the replay engine that you're providing.  And _sometimes_ the actual GPS update hits the component, causing the quick map movement back to your position.  

In the `NavigationMapboxMap`, we should only ever use `LocationComponet#forceLocationUpdate`.
