### ISSUE TITLE
Update ManeuverView to use VectorDrawables from PaintCode 

### ISSUE THREAD

**Issue by danesfeder** [mapbox/mapbox-navigation-android#1697]
Similar to #1695, we should remove `ManeuverStyleKit.java` and replace each method with a `VectorDrawable` generated by PaintCode file https://github.com/mapbox/navigation-ui-resources/blob/master/Maneuvers.pcvd.

**Comment by Guardiola31337** [comment]
Is this going to be addressed by https://github.com/mapbox/mapbox-navigation-android/pull/2516 @JunDai?

**Comment by JunDai** [comment]
well, I think that we discussed this when I started working on #2516 and later we decided to use the `ManeuverStyleKit.java` code to draw the maneuver image to replace the vector drawables which were previously used in the Notification.
So I think this issue will not be fixed by #2516 .

**Comment by abhishek1508** [comment]
Let's verify/fix
cc @JunDai @cafesilencio @langsmith

**Comment by abhishek1508** [comment]
As per discussion we are going to revisit this in next major release.
cc @Guardiola31337

**Comment by LukasPaczos** [comment]
Closing in favor of https://github.com/mapbox/mapbox-navigation-android/issues/4513 as the `ManeuverView` already uses the resources.
