### ISSUE TITLE
Support lib 28.0.0 > AndroidX Migration

### ISSUE THREAD

**Issue by danesfeder** [mapbox/mapbox-navigation-android#1702]
As mentioned in https://github.com/mapbox/mapbox-navigation-android/pull/1690:

> This is the stable release of Support Library 28.0.0 and is suitable for use in production. This will be the last feature release under the android.support packaging, and developers are encouraged to migrate to AndroidX.

We should start thinking about the right time to do this migration.  Mainly, what kind of impact does this have on our developers?  Does it mean that users of the SDK _must_ also use `x`?

**Comment by Guardiola31337** [comment]
This happened in https://github.com/mapbox/mapbox-navigation-android/pull/1999 and will be available in `1.0`.

Closing here.
