### ISSUE TITLE
Make exit signs stylable

### ISSUE THREAD

**Issue by devotaaabel** [mapbox/mapbox-navigation-android#1705]
This relates to https://github.com/mapbox/mapbox-navigation-android/issues/972 . There are issues with the background color rendering on pre-API 21 devices.

**Comment by Guardiola31337** [comment]
@abhishek1508 @JunDai is this supported in the `1.0` UI SDK?

**Comment by abhishek1508** [comment]
Let's verify.
cc @JunDai @cafesilencio @langsmith

**Comment by abhishek1508** [comment]
After internal discussion with @asinghal22 we will not be prioritizing this work for v1.0. I am going to close this for now.
cc @Guardiola31337
