### ISSUE TITLE
Navigator Module

### ISSUE THREAD

**Issue by siavashabdoli** [mapbox/mapbox-navigation-android#1719]
Hi again :D 
From version 19 you've decided to introduce new cpp module named Navigator for offline routing but as I see you moved lots of other logic in it and it's not only for offline routing. with this new strategy we can't debug or develop some part of code anymore. The question here is what is your exact strategy here? Do you want to make that module open source later? Do you want to move more logic to that module with every release? That would be great if you share what is your plan because we have to make decision here to either stop updating mapbox navigation and try to write our Navigator or wait for open source navigator.

**Comment by Guardiola31337** [comment]
Hey @siavashabdoli 👋 thanks for reaching out and report your questions.

> From version 19 you've decided to introduce new cpp module named Navigator for offline routing but as I see you moved lots of other logic in it and it's not only for offline routing.

As pointed out in https://github.com/mapbox/mapbox-navigation-android/issues/1391#issuecomment-431493121

> The shared `Navigator` library and functionality added in #1265 serves to bring many improvements to our core routing / processing logic.  Its core functionality is written in `C++` similar to our Maps SDK, which provides major performance enhancements.  
>
> Outside of performance and reliability, it makes it much easier to align platforms (iOS v. Android for example), where previously we were in a constant state of flux for platform parity.  @mcwhittemore outlined a similar explanation in https://github.com/mapbox/mapbox-navigation-android/pull/1265#issuecomment-424387187.

For further details you can read the whole thread in https://github.com/mapbox/mapbox-navigation-android/issues/1391 

I hope this helps provide some context into the benefits of this library.

**Comment by danesfeder** [comment]
Hey @siavashabdoli 👋 I'm going to go ahead and close this as non-actionable for the moment.  As our plan unfolds, we will be sure to update here.  Sorry for the confusion or inconvenience these changes have caused you.
