### ISSUE TITLE
SnapToRoute.getSnappedLocation only modifies input Location

### ISSUE THREAD

**Issue by P-Zenker** [mapbox/mapbox-navigation-android#172]
Hey,

in v0.4.0 new SnapToRoute(routeProgress).getSnappedLocation returns a modified input Location object. It would be better if you make a copy of the object and return it - maybe someone would like to further process the location himself.

Otherwise it is not necessary to return a object or to check if the result is null (like in your [SnapToRouteActivity](https://github.com/mapbox/mapbox-navigation-android/search?utf8=✓&q=SnappedLocation&type=)  ).

**Comment by cammace** [comment]
> It would be better if you make a copy of the object and return it

You should still be able to get the raw location object from a location engine listener which you can then alter however you'd like. Taking this a step further, in 0.5.0, you'll be able to implement your own SnapToRoute logic by extending the Snap class and building out your own logic for this.

**Comment by cammace** [comment]
Stale, closing.
