### ISSUE TITLE
 WaypointNavigationActivity example activity stops after first waypoint

### ISSUE THREAD

**Issue by neonef** [mapbox/mapbox-navigation-android#1721]
**Android API: 28**
**Mapbox Navigation SDK version: 7.1.0**
**Mapbox Navigation UI 0.28.0**

### Steps to trigger behavior

 1. Copy [WaypointNavigationActivity example activity](https://raw.githubusercontent.com/mapbox/mapbox-navigation-android/master/app/src/main/java/com/mapbox/services/android/navigation/testapp/activity/navigationui/WaypointNavigationActivity.java) into my app without changes.
 2. Run

### Actual behavior

After first waypoint, the simulated car stops.

![navi1](https://user-images.githubusercontent.com/16475904/52267536-8ef7f400-2939-11e9-9e28-3f14749384c8.gif)

**Comment by danesfeder** [comment]
@neonef nice catch, fix moving in https://github.com/mapbox/mapbox-navigation-android/pull/1724
