### ISSUE TITLE
OnRouteSelectionChangeListener not called when tapping alternative routes

### ISSUE THREAD

**Issue by cmahopper** [mapbox/mapbox-navigation-android#1723]
**Android API:** 28
**Mapbox Navigation SDK version:** 0.28.0

### Steps to trigger behavior

Using the following code after a succesful `navigationRoute.getRoute(...)` where `alternatives(true)` is set in its builder:

```
val routes = directionsResponse.routes()
if (navigationMapRoute == null)
    navigationMapRoute = NavigationMapRoute(navigation, mapView, map, R.style.CustomNavigationMapRoute)
navigationMapRoute?.showAlternativeRoutes(true)
navigationMapRoute?.addRoutes(routes)

navigationMapRoute?.setOnRouteSelectionChangeListener { directionsRoute -> onRouteSelected(routes, directionsRoute) }
```

### Expected behavior
When we were on 0.26, tapping the alternative routes would call the OnRouteSelectionChangeListener, and make that route the new primary route.

### Actual behavior
Tapping the alternative routes does nothing.

I've not been able to find anything in the release notes regarding this. Did something else change in Mapbox 7.0?

**Comment by danesfeder** [comment]
Hey @cmahopper 👋 yeah this was a bug introduced by the integration of the annotation plugin in #1706.  The Maps team actually just introduced the fix in `0.5.0`, which we are pulling in #1722.  I'll close this ticket when that PR lands.  Thanks for your patience!

**Comment by cmahopper** [comment]
@danesfeder I'm afraid I'm still not able to tap alternative routes in 0.29.0. Has something else changed since 0.26?

**Comment by cmahopper** [comment]
@danesfeder Ah thanks, that was it!
