### ISSUE TITLE
"You have arrived" text translation

### ISSUE THREAD

**Issue by kiskunk** [mapbox/mapbox-navigation-android#1727]
I am using the NavigationLauncher component in my app and If I set the locale to Hungarian, everything works fine, except when the header says "You have arrived", its still in english. I tried to find where to contribute for that, but the navigation SDK doesn't even have an option for hungarian on the transifex site, which is weird, because the app could translate the word "min" into hungarian.

Android API: 4.1-8.1
Mapbox Navigation SDK version: 0.27.0

Steps to trigger behavior:
1. set locale to hungarian
2. start a navigation by calling NavigationLauncher.startNavigation

Expected behavior:
"You have arrived" should say: "Érkezés a célhoz"

Actual behavior:
"You have arrived" says: "You have arrived"

**Comment by danesfeder** [comment]
Hey @kiskunk 👋 our voice instructions are provided by the Directions API.  Unfortunately, at this time, it doesn't look like we support Hungarian 😞 https://docs.mapbox.com/api/navigation/#instructions-languages.  Please check out https://github.com/Project-OSRM/osrm-text-instructions/blob/master/CONTRIBUTING.md for contributing to OSRMTI localization efforts.  Going to close here as non-actionable on the SDK side.  Thanks!

**Comment by kiskunk** [comment]
> Hey @kiskunk 👋 our voice instructions are provided by the Directions API. Unfortunately, at this time, it doesn't look like we support Hungarian 😞 https://docs.mapbox.com/api/navigation/#instructions-languages. Please check out https://github.com/Project-OSRM/osrm-text-instructions/blob/master/CONTRIBUTING.md for contributing to OSRMTI localization efforts. Going to close here as non-actionable on the SDK side. Thanks!

Hi, thanks. Another question, I saw a blog page which stated that the new IOS SDK has both voice and UI translations for hungarian. Can you give any estimations on when those will be available on Android? Thank you :)
