### ISSUE TITLE
RouteTileDownloadListener#onProgressUpdate gives progress for TAR extraction not download

### ISSUE THREAD

**Issue by mcraz** [mapbox/mapbox-navigation-android#1741]
`RouteTileDownloadListener#onProgressUpdate` should update with percentage progress of download. Rather it updates progress for TAR extraction.

**Android API:** 23
**Mapbox Navigation SDK version:** v0.25.0

### Steps to trigger behavior

 1. Download navigation using `MapboxOfflineRouter#downloadTiles`
 2. Implement `RouteTileDownloadListener#onProgressUpdate`

### Expected behavior
`RouteTileDownloadListener#onProgressUpdate` should be called with progress of the nav download request.
### Actual behavior
Progress is emitted for TAR extraction and not for the actual request.

Is there a way to retrieve nav download request progress ?

**Comment by danesfeder** [comment]
Hey @mcraz 👋 thank you for your feedback here.  This listener is behaving as expected / designed as you have described it.  Unfortunately, it's not straightforward to achieve the behavior you're describing.  We use `Retrofit` to make the TAR request and it returns all at once.

If you have any suggestions on proper implementation of monitoring this progress, please feel free to drop them here.  For now, going to close this as non-actionable on our part.

**Comment by akitchen** [comment]
Hi everyone - 

@mcraz thanks for opening this issue. I'm going re-open it while we investigate what it might take to separate out the download progress from the unpacking progress. Thanks for your patience!

**Comment by danesfeder** [comment]
@mcraz I apologize for closing this prematurely.  After digging further, it looks like we may be able to hook into `OkHttp` functionality to monitor network progress combined with the actual TAR unpacking progress that we are giving updates on today.

**Comment by danesfeder** [comment]
@mcraz three parts moving to fix this outlined in #1753

**Comment by Guardiola31337** [comment]
Closing here as _Offline_ feature is going to be re-implemented. Let's make sure the new version includes support for this.

cc @kkaefer @mskurydin
