### ISSUE TITLE
Simplify route geometry for map route display

### ISSUE THREAD

**Issue by danesfeder** [mapbox/mapbox-navigation-android#1743]
Currently, the `NavigationRoute`, by default, makes Directions API request with `DirectionsCriteria.OVERVIEW_FULL`.  The `DirectionsRoute` returned, is usually then rendered with `NavigationMapRoute`.  

The coordinate / traffic data can be quite big with larger routes.  When setting these `FeatureCollections` to the `GeoJsonSource`, we sometimes see UI thread freezing and or lag thereafter as the Maps SDK processes these massive datasets.  If for example we simplified the geometry point data before rendering and or only displayed traffic in the immediate vicinity, we would tax the map renderer much less.  

cc @LukasPaczos @kevinkreiser

**Comment by 1ec5** [comment]
>  When setting these FeatureCollections to the GeoJsonSource, we sometimes see UI thread freezing and or lag thereafter as the Maps SDK processes these massive datasets.

The map SDK simplifies and tiles any geometry that you put into a GeoJSON source. In principle, there should be no continuing lag associated with a large route on the map. So I think the freezing and lagging needs to be profiled before we jump to the conclusion of pre-simplifying the route geometry.

**Comment by RingerJK** [comment]
By default the SDK requests [Most detailed geometry](https://github.com/mapbox/mapbox-navigation-android/blob/master/libdirections-offboard/src/main/java/com/mapbox/navigation/route/offboard/RouteBuilderProvider.kt#L23). We might replace it by `DirectionsCriteria.OVERVIEW_SIMPLIFIED` and anyway a user can replace it by own option via `RouteOptions`

**Comment by LukasPaczos** [comment]
@RingerJK We still need to be able to have a fully detailed route by default, for when the user is zoomed in.

**Comment by Guardiola31337** [comment]
Where are we here @RingerJK @LukasPaczos? Is this still an issue in `1.0`?

cc @abhishek1508 @cafesilencio

**Comment by cafesilencio** [comment]
(On Android) Until recently a feature collection was created for each leg of the route, representing the traffic congestion for each leg. The current implementation creates only one feature collection to draw the route and the traffic is represented with a gradient line. The performance has improved a lot. It takes ~70ms to draw a route from San Francisco to Los Angeles on my phone.

**Comment by LukasPaczos** [comment]
Adding to what @cafesilencio mentioned, the parsing of the geometries has been moved to a worker thread upstream in the Maps SDK, which means that UI freezes reported in the OP are not an issue anymore.
