### ISSUE TITLE
InstructionView refactor for modularization

### ISSUE THREAD

**Issue by devotaaabel** [mapbox/mapbox-navigation-android#1746]
The scope of this ticket is an overhaul of the InstructionView, resulting in modular custom views controlled by a `InstructionDelegator`, which can be re-arranged and replaced for customization. This refactor will also improve code organization and readability, and make debugging instruction issues easier, as well as helping identify current instruction bugs and fixing them.  All custom views should implement interfaces so that if developers want, they can create their own custom `InstructionView` but still get the benefits of the data being updated by the `InstructionDelegator`.

- [ ] Extract mute and feedback buttons into the `NavigationView` (custom view button dashboard?)

- [ ] Extract `NavigationAlertView` into the `NavigationView`

- [ ] Create `InstructionDelegator` to subscribe to `NavigationViewModel.BannerInstructionModel` and to update instruction views

- [ ] Extract instruction list layout into a custom view

- [ ] Create custom view containing primary and secondary step text views (possibly separate ones for portrait vs. landscape)

- [ ] Determine desired behavior for abbreviations of primary and secondary step in landscape orientation (hopefully with the help of some design resources)

- [ ] Create custom view containing substep and turn lane views

- [ ] Create custom view containing `ManeuverView` and step distance text

- [ ] Make sure https://github.com/mapbox/mapbox-navigation-android/issues/1672 is addressed

- [ ] xml attribute for `NavigationView` which specifies a layout to inflate for the `InstructionView`? Or some other way of allowing devs to replace the `InstructionView` with their custom implementation OR explore options for accessing views with the same parent as `NavigationView`

**Comment by Guardiola31337** [comment]
This is going to be superseded by https://github.com/mapbox/mapbox-navigation-android/pull/2824

Closing here.

cc @abhishek1508
