### ISSUE TITLE
Continue Straight restriction

### ISSUE THREAD

**Issue by brentnd** [mapbox/mapbox-navigation-android#1747]
Is it possible in a future release to remove the restriction on the `continueStraight` parameter in the `NavigationRoute` builder?

We're specifically looking to have this set to `false` for offline navigation.

**Comment by danesfeder** [comment]
Hey @brentnd yeah sure thing - we will add it as a default that you can override to `false`.  PR incoming.

**Comment by danesfeder** [comment]
Moving https://github.com/mapbox/mapbox-navigation-android/pull/1748

**Comment by brentnd** [comment]
Thanks @danesfeder.
