### ISSUE TITLE
Error: While calling Mapview Activity again and again

### ISSUE THREAD

**Issue by sagarlotus** [mapbox/mapbox-navigation-android#1751]
Added below dependencies in application,

1. Mapbox-Navigation
implementation 'com.mapbox.mapboxsdk:mapbox-android-navigation:0.18.0'
implementation 'com.mapbox.mapboxsdk:mapbox-android-navigation-ui:0.18.0' 

2. Mapbox-SDK
'com.mapbox.mapboxsdk:mapbox-android-sdk:6.8.1'

Workflow:
1. Calling map fragment from home screen.(Mapview is created inside DialogFragment)
2. Press back and again calling Map fragment.
Repeating above steps again and again, application produces below error,

Error:  Fatal signal 11 (SIGSEGV), code 1, fault addr 0x0 in tid 8500 (FinalizerDaemon)

Devices Used: Motorola Nexus with OS version 7.1 and Lenovo(V-5.0)

**Comment by danesfeder** [comment]
Hey @sagarlotus 👋 it looks like you're using an old version of our SDK.  Last week, we released `0.29.0`.  Also, we do not recommend changing the Maps SDK version - we bring in the latest Maps SDK dependency in the UI library.  Please update and try to reproduce with the latest - hope this helps clarify things a bit.

**Comment by sagarlotus** [comment]
Hey @danesfeder As per your suggestions, I have implement version 0.29.0 in application and remove Maps SDK version dependency. But still I am facing same issue ( Fatal signal 11 (SIGSEGV), code 1, fault addr 0x0 in tid 8500 (FinalizerDaemon)).
Kindly look into same.
Appreciate quick reply.

**Comment by BenF99** [comment]
@sagarlotus Any update with this error? I'm encountering exactly the same issue
