### ISSUE TITLE
NavigationView Location Indicator Disappears on 0.28.0

### ISSUE THREAD

**Issue by billyking991** [mapbox/mapbox-navigation-android#1759]
When I updated to 0.28.0, the location indicator disappears/reappears, but mostly it disappears, showing only a white dot where it should be.  This did not happen on 0.27.0 or any previous version of the Android SDK.  I have attached screenshots of it happening on Android 7 and 8. 

Please let me know if you need more info from me.

This is how I start the NavigationView:

NavigationViewOptions.Builder navigationViewOptions = NavigationViewOptions.builder();
                           navigationViewOptions.directionsRoute(currentRoute);
                            navigationViewOptions.navigationListener(NavigationActivity.this);
                            navigationViewOptions.milestoneEventListener(NavigationActivity.this);
                            navigationViewOptions.speechAnnouncementListener(NavigationActivity.this);
                            navigationViewOptions.bannerInstructionsListener(NavigationActivity.this);
                            navigationViewOptions.routeListener(NavigationActivity.this);
                            navigationViewOptions.shouldSimulateRoute(false);
                            navigationViewOptions.locationEngine(locationEngine);

                            navigationView.startNavigation(navigationViewOptions.build()); 

![missinglocationindicator2](https://user-images.githubusercontent.com/5864607/53026267-8ec72080-3430-11e9-91f5-6f867d059ed9.png)
![missinglocationindicator](https://user-images.githubusercontent.com/5864607/53026278-95ee2e80-3430-11e9-8a56-7da8d96edc0b.jpg)

Mapbox Navigation SDK version: 0.28.0

Android OS versions: 7, 8, 9

### Steps to trigger behavior

 1.  Create NavigationVieweOptions
 2. Launch NavigationView with options
 3.  Wait for the nav indicator to disappear.  This usually happens within 2 seconds after it zooms in on the current location.

### Expected behavior
White and blue navigation indicator should be over the user's current location.

### Actual behavior
There is a white spot in the users location after the navigation indicator disappears.

**Comment by danesfeder** [comment]
Hey @billyking991 👋 yeah great catch, this was a bug fixed upstream in the Maps SDK (it was occurring when the map was tilted to its limits) https://github.com/mapbox/mapbox-gl-native/pull/13888.  

This was fixed in `0.29.0` by us updating our Maps SDK dependency in https://github.com/mapbox/mapbox-navigation-android/pull/1728.  Please note, our current version is `0.30.0`.  

As always, thank you for the feedback - closing here as resolved.

**Comment by billyking991** [comment]
Oh, yeah.  You're right.  The last time I checked 28 was the most recent.  You all work fast!  Thank you for fixing this.
