### ISSUE TITLE
Translation issue - Ignoring instructions (Exit numbers)

### ISSUE THREAD

**Issue by davols** [mapbox/mapbox-navigation-android#176]
I'll start with a 'sorry'. I scratched my head a bit on where to report this issue but ended up with this repo since it uses all of the services that are related.

Using 0.5.0-SNAPSHOT and translating to Swedish. 

**Issue** While the legstep.maneuver have `instructions` in the response from the directions API. (Like "Take exit 113") but that is ignored when compiling a translated instruction based on the legstep.

`osrm-text-instructions` is compiled by the maneuver its modifier. OSRM does not have exit instructions on highways today. So it's understandable that it's ignored. 

Mapbox-Directions have instructions with exit numbers. And translate that instruction is much better for user experience. It also has more information. 

Example:
Mapbox-Directions says 

> Take exit 113. 

OSRM says 

> Take the ramp on the right onto E 4.21

And compiling in the app gives a similar text in Swedish as OSRM with E 4.21. 

OSRM-example route: http://map.project-osrm.org/?z=18&center=58.434130%2C15.683310&loc=58.434458%2C15.685558&loc=58.428825%2C15.669004&hl=en&alt=0

Pinging @mapbox/android

edit: 
Right, OSRM demo page does not currently have the re-write. So that's why you get that english string like that. But taking the same route within our android app also gives the incorrect (without exit info, just the way_name) translation.

**Comment by davols** [comment]
Right, OSRM demo page does not currently have the re-write. So that's why you get that english string like that. But taking the same route within our android app also gives the incorrect (without exit info, just the way_name) translation.

**Comment by cammace** [comment]
> I scratched my head a bit on where to report this issue

This is the perfect place for OSRM questions, well for now :)

To make things more consistent across platforms (iOS, Javascript, and Android) I'm actually in the process of porting OSRM-Text-Instructions over to https://github.com/Project-OSRM/osrm-text-instructions.java where it will permanently live. I'm also currently working on updating the text instructions to match the behavior iOS and Javascript has (specifically around these exit instructions you mention). Once this is done, I plan to then add it as a dependency to the navigation SDK and expose an object (still thinking about how best to do this) inside the [instructions interface](https://github.com/mapbox/mapbox-navigation-android/blob/master/navigation/app/src/main/java/com/mapbox/services/android/navigation/testapp/activity/MockNavigationActivity.java#L320-L326) where you can build instructions however you'd like, including translations. 

I'll keep this ticket open to track project on this work.

**Comment by davols** [comment]
Could just give a brief update. Updated the strings in transifex and got it merged last week. Which have proper handling (at least in transifex and testing) for exits et al. 
https://github.com/Project-OSRM/osrm-text-instructions/pull/138
