### ISSUE TITLE
Navigation Events onRunning won't trigger when navigation starts

### ISSUE THREAD

**Issue by hmkum** [mapbox/mapbox-navigation-android#1762]
**Android API:** 
Android 9 
Test device: Samsung S9+

**Mapbox Navigation SDK version:**
0.31.0-SNAPSHOT

### Steps to trigger behavior

 1.  Follow 'Embedded Navigation' tutorial https://docs.mapbox.com/android/navigation/examples/embedded-navigation/#
 2. Wait until route simulation finishes

### Expected behavior
Navigation events shall be called when navigation starts and finishes

- onRunning
- onCancelNavigation
- onNavigationFinished
- onNavigationRunning

### Actual behavior
Navigation SDK does not trigger the events when navigation starts or finishes.

onCancelNavigation and onNavigationFinished are triggered when user presses the 'X' icon on bottom & right corner of the screen.

Also, routeProgress#currentState returns LOCATION_STALE when user arrives his/her destination. If I change the destination, sometimes I can see the state ROUTE_ARRIVED but still no navigation events.

### Logcat output;
  D/HMK: OnNavigationReady
  D/HMK: State: ROUTE_INITIALIZED Distance: 535.696044921875 Duration: 100.0
  D/HMK: State: ROUTE_INITIALIZED Distance: 535.696044921875 Duration: 100.0
  D/HMK: State: LOCATION_TRACKING Distance: 510.5815124511719 Duration: 95.56083083152771
  ...
  D/HMK: State: LOCATION_TRACKING Distance: 5.520622730255127 Duration: 1.0332465171813965
  D/HMK: State: LOCATION_STALE Distance: 5.520622730255127 Duration: 1.0332465171813965
  D/HMK: State: LOCATION_STALE Distance: 5.520622730255127 Duration: 1.0332465171813965

### MainActivity.java
        package de.kayten.mapboxnavdemo;
    
        import android.app.Activity;
        import android.location.Location;
        import android.os.Bundle;
    
        import java.util.Locale;
    
        import android.support.v7.app.AppCompatActivity;
        import android.support.v7.app.AppCompatDelegate;
    
        // classes needed to initialize map
        import com.mapbox.api.directions.v5.DirectionsCriteria;
        import com.mapbox.mapboxsdk.Mapbox;
        import com.mapbox.mapboxsdk.camera.CameraPosition;
    
        // classes needed to add a marker
        import com.mapbox.geojson.Point;
        import com.mapbox.mapboxsdk.geometry.LatLng;
    
        // classes to calculate a route
        import com.mapbox.services.android.navigation.ui.v5.NavigationView;
        import com.mapbox.services.android.navigation.ui.v5.NavigationViewOptions;
        import com.mapbox.services.android.navigation.ui.v5.OnNavigationReadyCallback;
        import com.mapbox.services.android.navigation.ui.v5.listeners.NavigationListener;
        import com.mapbox.services.android.navigation.v5.navigation.NavigationEventListener;
        import com.mapbox.services.android.navigation.v5.navigation.NavigationRoute;
        import com.mapbox.api.directions.v5.models.DirectionsResponse;
        import com.mapbox.api.directions.v5.models.DirectionsRoute;
    
        import retrofit2.Call;
        import retrofit2.Callback;
        import retrofit2.Response;
        import android.util.Log;
    
        // classes needed to launch navigation UI
        import com.mapbox.services.android.navigation.v5.routeprogress.ProgressChangeListener;
        import com.mapbox.services.android.navigation.v5.routeprogress.RouteProgress;
    
    
        public class MainActivity extends AppCompatActivity implements OnNavigationReadyCallback, NavigationEventListener, NavigationListener, ProgressChangeListener {
            private static final double MIN_SECONDS = 1.0;
            private static final double MIN_DISTANCE = 3.0;
            private static final int INITIAL_ZOOM = 16;
    
            NavigationView navigationView;
            Point mOrigin;
            Point mDestination;
    
            @Override
            protected void onCreate(Bundle savedInstanceState) {
                setTheme(R.style.Theme_AppCompat_Light_NoActionBar);
                AppCompatDelegate.setDefaultNightMode(AppCompatDelegate.MODE_NIGHT_NO);
    
                super.onCreate(savedInstanceState);
    
                Mapbox.getInstance(getApplicationContext(), getString(R.string.access_token));
    
                setContentView(R.layout.activity_navigation);
    
                mOrigin = Point.fromLngLat(-77.03194990754128, 38.909664963450105);
                mDestination = Point.fromLngLat(-77.0270025730133, 38.91057077063121);
    
                navigationView = findViewById(R.id.navigationView);
    
                CameraPosition initialPosition = new CameraPosition.Builder()
                    .target(new LatLng(mOrigin.latitude(), mOrigin.longitude()))
                    .zoom(INITIAL_ZOOM)
                    .build();
                navigationView.onCreate(savedInstanceState);
                navigationView.initialize(this, initialPosition);
            }
    
            @Override
            public void onNavigationReady(boolean isRunning) {
    
                Log.d("HMK", "OnNavigationReady");
                fetchRoute();
            }
    
            @Override
            public void onProgressChange(Location location, RouteProgress routeProgress) {
    
                Log.d("HMK", "State: " + routeProgress.currentState().name() + " Distance: " + routeProgress.distanceRemaining() + " Duration: " + routeProgress.durationRemaining());
                switch (routeProgress.currentState())
                {
                    case ROUTE_ARRIVED:
                    case LOCATION_STALE: {
                        if((routeProgress.distanceRemaining() <= MIN_DISTANCE) || (routeProgress.durationRemaining() <= MIN_SECONDS)) {
                            Log.d("HMK", "Distance: " + routeProgress.distanceRemaining() + " Duration: " + routeProgress.durationRemaining());
                            navigationView.stopNavigation();
                        }
                    } break;
                }
            }
    
            @Override
            public void onRunning(boolean running) {
                Log.d("HMK", "onRunning: " + running);
            }
    
            @Override
            public void onCancelNavigation() {
                Log.d("HMK", "onCancelNavigation");
                finish();
            }
    
            @Override
            public void onNavigationFinished() {
                Log.d("HMK", "onNavigationFinished");
                setResult(Activity.RESULT_OK);
                finish();
            }
    
            @Override
            public void onNavigationRunning() {
                Log.d("HMK", "onNavigationRunning");
            }
    
    
            private void startNavigation(DirectionsRoute directionsRoute) {
                NavigationViewOptions options =
                    NavigationViewOptions.builder()
                        .directionsProfile(DirectionsCriteria.PROFILE_CYCLING)
                        .navigationListener(this)
                        .directionsRoute(directionsRoute)
                        .shouldSimulateRoute(true)
                        .progressChangeListener(this)
                        .build();
    
                navigationView.startNavigation(options);
            }
    
            private void fetchRoute() {
                NavigationRoute.builder(this)
                    .accessToken(Mapbox.getAccessToken())
                    .origin(mOrigin)
                    .destination(mDestination)
                    .alternatives(true)
                    .language(Locale.GERMAN)
                    .voiceUnits(DirectionsCriteria.METRIC)
                    .build()
                    .getRoute(new Callback<DirectionsResponse>() {
                        @Override
                        public void onResponse(Call<DirectionsResponse> call, Response<DirectionsResponse> response) {
                            DirectionsRoute directionsRoute = response.body().routes().get(0);
                            startNavigation(directionsRoute);
                        }
    
                        @Override
                        public void onFailure(Call<DirectionsResponse> call, Throwable t) {
    
                        }
                    });
            }
    
            @Override
            public void onStart() {
                super.onStart();
                navigationView.onStart();
            }
    
            @Override
            public void onResume() {
                super.onResume();
                navigationView.onResume();
            }
    
            @Override
            public void onLowMemory() {
                super.onLowMemory();
                navigationView.onLowMemory();
            }
    
            @Override
            public void onBackPressed() {
                // If the navigation view didn't need to do anything, call super
                if (!navigationView.onBackPressed()) {
                    super.onBackPressed();
                }
            }
    
            @Override
            protected void onSaveInstanceState(Bundle outState) {
                navigationView.onSaveInstanceState(outState);
                super.onSaveInstanceState(outState);
            }
    
            @Override
            protected void onRestoreInstanceState(Bundle savedInstanceState) {
                super.onRestoreInstanceState(savedInstanceState);
                navigationView.onRestoreInstanceState(savedInstanceState);
            }
    
            @Override
            public void onPause() {
                super.onPause();
                navigationView.onPause();
            }
    
            @Override
            public void onStop() {
                super.onStop();
                navigationView.onStop();
            }
    
            @Override
            protected void onDestroy() {
                super.onDestroy();
                navigationView.onDestroy();
                if (isFinishing()) {
                    //saveNightModeToPreferences(AppCompatDelegate.MODE_NIGHT_AUTO);
                    AppCompatDelegate.setDefaultNightMode(AppCompatDelegate.MODE_NIGHT_AUTO);
                }
            }
    
        }

### activity_main.xml
    <?xml version="1.0" encoding="utf-8"?>
    <android.support.constraint.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
        xmlns:mapbox="http://schemas.android.com/apk/res-auto"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        xmlns:app="http://schemas.android.com/tools">
    
        <com.mapbox.services.android.navigation.ui.v5.NavigationView
            android:id="@+id/navigationView"
            android:layout_width="match_parent"
            android:layout_height="0dp"
            app:layout_constraintBottom_toBottomOf="parent"
            app:layout_constraintEnd_toEndOf="parent"
            app:layout_constraintStart_toStartOf="parent"
            app:layout_constraintTop_toTopOf="parent" />
    
        </android.support.constraint.ConstraintLayout>

**Comment by danesfeder** [comment]
> Navigation SDK does not trigger the events when navigation starts or finishes.

Which events?

 > onCancelNavigation and onNavigationFinished are triggered when user presses the 'X' icon on bottom & right corner of the screen.

This sounds like correct behavior no?

> Also, routeProgress#currentState returns LOCATION_STALE when user arrives his/her destination. If I change the destination, sometimes I can see the state ROUTE_ARRIVED but still no navigation events.

If you're simulating, this sounds like correct behavior.  The simulation will run out and the route-following logic will determine stale location because it hasn't received anything new.

**Comment by hmkum** [comment]
> 
> 
> > Navigation SDK does not trigger the events when navigation starts or finishes.
> 
> Which events?
> 

- onRunning
- onNavigationFinished
- onNavigationRunning

When I call NavigationView#startNavigation, I expect that onRunning and onNavigationRunning events will be triggered however they don't. 


> > onCancelNavigation and onNavigationFinished are triggered when user presses the 'X' icon on bottom & right corner of the screen.
> 
> This sounds like correct behavior no?
> 

Right, this behavior is correct. I just want to say here, if I press X button, necessary events are triggered and works perfectly however when I reach the destination (routeProgress#currentState = ROUTE_ARRIVED),  the Navigation SDK does not fire any event except onProgressChange with outeProgress#currentState = ROUTE_ARRIVED.

> > Also, routeProgress#currentState returns LOCATION_STALE when user arrives his/her destination. If I change the destination, sometimes I can see the state ROUTE_ARRIVED but still no navigation events.
> 
> If you're simulating, this sounds like correct behavior. The simulation will run out and the route-following logic will determine stale location because it hasn't received anything new.

Right, I am simulating. I am just assuming that we should get onNavigationFinished when the state is ROUTE_ARRIVED. Is this wrong assumption?

**Comment by danesfeder** [comment]
> When I call NavigationView#startNavigation, I expect that onRunning and onNavigationRunning events will be triggered however they don't.

Yeah this sounds like a bug on our end, I agree.  We will look into this. 

> onNavigationFinished when the state is ROUTE_ARRIVED

`onNavigationFinished` fires when the navigation session has been stopped (i.e. - the `ForegroundService` running navigation is no longer active).  You need to explicitly call `NavigationView#stopNavigation` if you want to stop navigation when you see `ROUTE_ARRIVED`, otherwise navigation will continue even if you're at the end of the route.

**Comment by hmkum** [comment]
> > onNavigationFinished when the state is ROUTE_ARRIVED
> 
> `onNavigationFinished` fires when the navigation session has been stopped (i.e. - the `ForegroundService` running navigation is no longer active). You need to explicitly call `NavigationView#stopNavigation` if you want to stop navigation when you see `ROUTE_ARRIVED`, otherwise navigation will continue even if you're at the end of the route.

Now, everything is clear for me. Thank you for the explanation.
