### ISSUE TITLE
Navigation craches 

### ISSUE THREAD

**Issue by tokaaliamien** [mapbox/mapbox-navigation-android#1769]
Navigation just crashes without any change in code, and I'm not getting anything in the logcat about it.
Any idea what's going on?
I'm using 'com.mapbox.mapboxsdk:mapbox-android-navigation:0.27.0' and 'com.mapbox.mapboxsdk:mapbox-android-navigation-ui:0.27.0'

**Comment by danesfeder** [comment]
Hey @tokaaliamien 👋 thanks for the feedback - I'd encourage you to try our latest version `0.30.0`.  This could also be related to https://github.com/mapbox/mapbox-navigation-android/issues/1752#issuecomment-464746035.  Please try this solution.  Thanks!
