### ISSUE TITLE
Failed to resolve: com.mapbox.navigator:mapbox-navigation-native:5.0.0

### ISSUE THREAD

**Issue by Girrajjangid** [mapbox/mapbox-navigation-android#1770]
**Android API:** 28
**Mapbox Navigation SDK version:** 7.1.2

### Steps to trigger behavior
 1. Want to get navigation route
Dependency doesn't download it shows this error

### Actual behavior
Failed to resolve: com.mapbox.navigator:mapbox-navigation-native:5.0.0 Open FileShow in Project Structure dialog |  
-- | --

**Comment by danesfeder** [comment]
Per our `Getting Started` guide https://github.com/mapbox/mapbox-navigation-android#getting-started, you need to add:

```
repositories {
    ...
    maven { url 'https://mapbox.bintray.com/mapbox' }
}
```
