### ISSUE TITLE
SpeechAnnouncement willVoice is called after muting the speech

### ISSUE THREAD

**Issue by kiskunk** [mapbox/mapbox-navigation-android#1771]
In the NavigationView there is a sound button to mute/unmute speech, but either way the method willVoice will still fire. If this is really an expected behavior, then how can I check if its muted or not in an if statement?

**Android API:** 28
**Mapbox Navigation SDK version:** 0.28.0

### Steps to trigger behavior

 1. Create a navigationViewOptions with speechAnnouncementListener
 2. start navigation
 3. mute/unmute speech with the provided soundButton

### Expected behavior

When muted, SpeechAnnouncementListener should not be fired

### Actual behavior

When muted, SpeechAnnouncementListener is fired

     private void startNavigation(DirectionsRoute directionsRoute) {
        NavigationViewOptions.Builder options =
                NavigationViewOptions.builder()
                        .navigationListener(this)
                        .directionsRoute(directionsRoute)
                        .shouldSimulateRoute(true)
                        .progressChangeListener(this)
                        .instructionListListener(this)
                        .milestoneEventListener(this)
                        .speechAnnouncementListener(this)
                        .bannerInstructionsListener(this);
        setBottomSheetCallback(options);
        setupNightModeFab();

        navigationView.startNavigation(options.build());
    }

    @Override
    public SpeechAnnouncement willVoice(SpeechAnnouncement speechAnnouncement) {
     ttsReader(TranslatorUtil.getTranslationV2(speechAnnouncement.announcement().toLowerCase()));
     return null;
    }

**Comment by devotaaabel** [comment]
Hi @kiskunk , is your goal to use a custom speech player? If so, it might suit your needs better to implement `SpeechPlayer` and set it in the `NavigationViewOptions`. Let me know if this helps.

https://github.com/mapbox/mapbox-navigation-android/blob/master/libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/voice/SpeechPlayer.java

https://github.com/mapbox/mapbox-navigation-android/blob/master/libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/NavigationViewOptions.java#L102

**Comment by kiskunk** [comment]
Thanks but I do not need a custom speech player, I would just like to know if the default one is in muted state or not.

**Comment by devotaaabel** [comment]
To answer your original question @kiskunk, this is the expected behavior of the `SpeechAnnouncementListener`. I suggest adding a listener to the mute button and keeping track of the muted state locally.
