### ISSUE TITLE
Silent waypoints lost when rerouting

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-navigation-android#1781]
Silent waypoints (#1733) are lost when the user is rerouted. `RouteFetcher.buildRequestFromLocation()` and `RouteUtils.calculateRemainingWaypoints()` come up with a set of waypoints that consists of the user’s current location and any remaining waypoints:

https://github.com/mapbox/mapbox-navigation-android/blob/8d2ceeb842b0a923824cf13713c0521782d585df/libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/route/RouteFetcher.java#L122-L129 https://github.com/mapbox/mapbox-navigation-android/blob/927e923441efa049d49a6057a2e3cacf7fbf036b/libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/utils/RouteUtils.java#L73-L77

But that only considers explicit waypoints that separate legs, not via points:

https://github.com/mapbox/mapbox-navigation-android/blob/927e923441efa049d49a6057a2e3cacf7fbf036b/libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/routeprogress/RouteProgress.java#L122-L124

We’ll need to figure out which waypoints in the original route options are along the remaining route. One edge case to consider is a route that doubles back on itself; we’ll need to preserve the order in that case.

The iOS equivalent to this issue is mapbox/mapbox-navigation-ios#2003.

/cc @mapbox/navigation-android

**Comment by Guardiola31337** [comment]
@korshaknn @RingerJK could we make sure this is addressed in `1.0`?

**Comment by korshaknn** [comment]
@Guardiola31337 don't know if it was addressed. Was working on `1Tap` and have not seen this issue before.

**Comment by RingerJK** [comment]
I'll take a look

**Comment by RingerJK** [comment]
@Guardiola31337 `WaypointIndices` includes as sublist of original list([link](https://github.com/mapbox/mapbox-navigation-android/blob/master/libnavigation-core/src/main/java/com/mapbox/navigation/core/directions/session/AdjustedRouteOptionsProvider.kt#L60)) of indices and it's not right behaviour I think. Logic is broken. Correct me if I'm wrong.

**Comment by Guardiola31337** [comment]
Is this addressed in `1.0` @RingerJK?

**Comment by RingerJK** [comment]
@Guardiola31337 I think it's not resolved
