### ISSUE TITLE
Question : is it possible to record a navigation ?

### ISSUE THREAD

**Issue by anthony-skr** [mapbox/mapbox-navigation-android#1784]
Hello,

I would like to record a navigation session and be able to replay it, like it's done here https://labs.mapbox.com/bites/00095/

1) I can record GPS activity (basically list of location) but I won't be able to play it via ReplayRouteLocationEngine. It seems the code is ready but there is no public method to pass a list of (timestamped) locations.

2) I can use MapMatching to convert list of location to a Mapbox route, but timestamps, speed and basically all the real activity is lost.

3) Is there such a thing like a recorded version of DirectionsRoute (progress saved every X ms) ?

Thanks,
Anthony.

**Comment by danesfeder** [comment]
> It seems the code is ready but there is no public method to pass a list of (timestamped) locations.

Yeah this is your best [solution](https://github.com/mapbox/mapbox-navigation-android/blob/master/libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/location/replay/GpxParser.java), using a GPX `.xml` - you should be able to just copy this code and use it with [`ReplayLocationDispatcher`](https://github.com/mapbox/mapbox-navigation-android/blob/master/libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/location/replay/ReplayLocationDispatcher.java)

**Comment by anthony-skr** [comment]
For now classes are package-private only. However I would prefer not to use GPX as I'm not using XML at all.

Do you plan to release those classes in the future, to allow to replay GPX, JSON (better for me) or list of timestamped location (even better for me) ?
Or it was only for internal/testing use only maybe ?

Thanks!

**Comment by danesfeder** [comment]
@anthony-skr we don't have JSON parsing / replay on our timeline currently and you're correct, we were using those classes internally for testing (although you're still able to use the open-source code if you'd like).

**Comment by Guardiola31337** [comment]
Closing here as workaround suggested.

Thanks @anthony-skr for checking out the SDK!
