### ISSUE TITLE
How to swap out Mapbox Navigator?

### ISSUE THREAD

**Issue by lozanicia** [mapbox/mapbox-navigation-android#1797]
I'd like to use your navigation sdk, but mapbox navigator is a private binary, and it is seemed not really easy to swap out. I want to use a totally open source sdk, what should I do?

**Comment by danesfeder** [comment]
Hey @lozanicia 👋 thanks for your feedback here.  Unfortunately, there isn't currently a way to completely remove the `Navigator` dependency from the SDK.  We understand the frustration with current hybrid open / closed source setup of this repository and are working towards a more clear setup for developers.  Thank you for understanding.
