### ISSUE TITLE
Add an option to turn of abbreviations completely

### ISSUE THREAD

**Issue by kiskunk** [mapbox/mapbox-navigation-android#1798]
Users should be able to turn on/off abbreviations.

**Android API:**
28
**Mapbox Navigation SDK version:**
28
### Steps to trigger behavior

 1. implement navigationView
 2. start navigation
 3. see unwanted abbreviations on bannerInstruction

### Expected behavior
disableAbbr(true)

### Actual behavior
disabbleAbbr function does not exist

**Comment by 1ec5** [comment]
> see unwanted abbreviations on bannerInstruction

Would all abbreviations be unwanted always, or are there particular situations where you would want abbreviations? #1201 and #3097 are tracking situations where the banner is abbreviating inappropriately; would a method to disable abbreviations be necessary once these issues are resolved?

**Comment by kiskunk** [comment]
Since we would like to use our translated texts and more control over the design, it would be a complete turn off.

**Comment by Guardiola31337** [comment]
@asinghal22 is this something we want to support in `1.0`?

cc @abhishek1508

**Comment by LukasPaczos** [comment]
Closing as stale.
