### ISSUE TITLE
Navigation marker rotate each time the car stop

### ISSUE THREAD

**Issue by ben-j69** [mapbox/mapbox-navigation-android#1806]
**Android API:**
 minSdkVersion 16
targetSdkVersion 28
**Mapbox Navigation SDK version:**
    implementation 'com.mapbox.mapboxsdk:mapbox-android-sdk:7.1.2'
    implementation 'com.mapbox.mapboxsdk:mapbox-sdk-services:4.5.0'
    implementation 'com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v7:0.5.0'
    implementation 'com.mapbox.mapboxsdk:mapbox-android-navigation:0.30.0'
    implementation 'com.mapbox.mapboxsdk:mapbox-android-navigation-ui:0.30.0'

### Steps to trigger behavior

 1. I have implemented a navigation activity that work well to go from a place to another by car
 2. When I drive the location of the car is displayed correctly on the navigation interface
 3. When the car stop the marker in arrow shap, representing the car is turning.

### Expected behavior
When the car stop the marker should keep the precedent direction

### Actual behavior
When the car stop the marker is turning.
It looks like the marker is turning to the north always. I had the same issue on a custom navigation made by me. It was because the display was receiving 2 times the same position (because the car has stopped) and then the calculated bearing calculated was 0 so it headed north, maybe it is the same issue ?

My configuration 
`  val options = MapboxNavigationOptions.builder()
                .isDebugLoggingEnabled(KlaxitApp.isDebugEnabled())
                .enableAutoIncrementLegIndex(true)
                .build()
        navigation = MapboxNavigation(this, Mapbox.getAccessToken()!!, options)`

`navigation?.addProgressChangeListener { location, routeProgress ->
                val legProgress = routeProgress.currentLegProgress()
                text_banner_secondary.text = distanceFormatter!!.formatDistance(legProgress.currentStepProgress().distanceRemaining())
                updateETA(legProgress.durationRemaining(), legProgress.distanceRemaining())

            }
            navigation?.addMilestoneEventListener(this)
            navigation?.addOffRouteListener(this)
            mMapboxMap.locationComponent.isLocationComponentEnabled = true
            navigation?.startNavigation(directionsRoute)`

**Comment by danesfeder** [comment]
@ben-j69 are you able to capture this unwanted behavior in a `.gif` and attach to this ticket?  Thanks!

**Comment by ben-j69** [comment]
I did not have time to reproduce this issue sorry.

**Comment by Guardiola31337** [comment]
Hey @ben-j69 
> I did not have time to reproduce this issue sorry.

Letting you know that should be fixed in the upcoming release `v0.33.2` 🎉
