### ISSUE TITLE
ERROR: The Android Gradle plugin supports only Kotlin Gradle plugin version 1.3.0 and higher.

### ISSUE THREAD

**Issue by rommansabbir** [mapbox/mapbox-navigation-android#1821]
I cloned the project from github repo. Now it's showing this error 
`ERROR: The Android Gradle plugin supports only Kotlin Gradle plugin version 1.3.0 and higher`

**Comment by danesfeder** [comment]
Hey @rommansabbir 👋 not sure what's going on here with your Android Studio setup, but we are using `1.2.61` in the test app so a more recent version
