### ISSUE TITLE
Create efficient settings profile

### ISSUE THREAD

**Issue by devotaaabel** [mapbox/mapbox-navigation-android#1823]
This task involves adding an efficiency profile to the `NavigationViewOptions`, where a developer can get a set of settings defaults which result in an efficient navigation build. Part of this task will involve talking to the maps team about ways we can make the profile more efficient.

**Comment by akitchen** [comment]
Do we have more of a sense of what this profile would entail?

**Comment by devotaaabel** [comment]
@akitchen I'm hoping to open a WIP PR today. The profile will include adjustments to FPS of the map and the location component which sacrifice a little bit of performance for a better battery life. The existing throttling for the map uses a few mechanisms including a camera tracking mode change listener, while the throttling for the location component uses the new zoom changed listener. These can be combined to reduce overhead and complexity, which I am considering a necessary piece of tech debt to include in this task. 

Most of the complexity of this task is (1) combining the throttling mechanism of the map throttling with the location throttling to use the zoom change listener (necessary tech debt) and (2) allowing the customization of the throttling levels to allow different profiles per the zoom while still allowing customization by the developer (which we know has already been requested and has been added). I have what I consider to be a graceful solution using an array of integer values to specify the FPS per each zoom level threshold, I just need to tie up some loose ends to open a PR.

**Comment by devotaaabel** [comment]
If needed, developers can do this manually themselves, so there's not a compelling need for this feature. Closing for now.
