### ISSUE TITLE
RefreshRoute not working properly 

### ISSUE THREAD

**Issue by msh91** [mapbox/mapbox-navigation-android#1828]
Refresh route feature does not work properly. We have our own implementation of refresh-route api and it returns a refreshed route with new traffic data and instructions, and the Sdk updates the traffic lines properly but route summary remains unchanged based on previous route instance

**Android API: All**
**Mapbox Navigation SDK version:0.30.0**

### Steps to trigger behavior

 1. Call to RouteRefresh in our navigation activity after onProgressChanged
 2. Refreshed route received from our api (not mapbox)
 3. Traffic lines will be updated, but summary model will remain unchanged.

**Comment by devotaaabel** [comment]
@msh91 When you say `route summary`/`summary model`, are you referring to the `SummaryBottomSheet`?

**Comment by msh91** [comment]
@devotaaabel  yes. The remaining time, arrival time not changed after route successfully refreshed

**Comment by danesfeder** [comment]
> have our own implementation of refresh-route api and it returns a refreshed route with new traffic data and instructions

@msh91 because this is your own implementation, we need more detail to determine if this is a bug on our end.  Maybe you can provide the stale vs. refreshed `DirectionsRoute` JSON?  Also, how are you passing the refreshed route to navigation?  Thank you.

**Comment by msh91** [comment]
@danesfeder Thank you for your response.
We use the same implementation as yours in the `MockNavigationActivity` of the test app.
I’ll send you JSON of a sample route and resfreshed route for better understanding.

**Comment by danesfeder** [comment]
@msh91 in #1819 we added a new `MapboxNavigation` API `#startNavigation(DirectionsRoute, DirectionsRouteType`.  Example usage:

```
navigation.startNavigation(freshRoute, DirectionsRouteType.FRESH_ROUTE)
```

Can you test this and confirm you're still seeing this issue?  Thanks!

**Comment by msh91** [comment]
@danesfeder I didn’t see this new, let me merge our base code with version 33 and I’ll let you know about the results. Thanks again for the response 🙏

**Comment by danesfeder** [comment]
@msh91 any updates here?

**Comment by msh91** [comment]
@danesfeder hi again. It’s our holiday and I can’t work on it until next week. I close the issue now and notify you later. Thanks again
