### ISSUE TITLE
Route not rendering on mapbox-native-gl 5.1.3

### ISSUE THREAD

**Issue by K-Leon** [mapbox/mapbox-navigation-android#183]
I tried running NavigationMapRoute but i couldn't manage getting it rendering the route at all. Is there some kind of regression that prevents rendering this layer? The actual function in NaviagationMapRoute gets called, but nothing is rendered. I'm running latest Location Provider - it's more or less the same setup like in DemoApp

**Comment by cammace** [comment]
I'll need more information to help you debug this issue such as the map style you are using, navigation version, and a snippet of code where you are initializing and/or passing in the route geometry into the NavigationMapRoute object.

**Comment by K-Leon** [comment]
I just found the reason - i passed a tour requested with polyline and not polyline6. Causing a route that was on the wrong location.
