### ISSUE TITLE
onProgressChange  getManeuver().getInstruction() wrong instructions

### ISSUE THREAD

**Issue by samvgorode** [mapbox/mapbox-navigation-android#184]
In onProgressChange method `routeProgress.currentLegProgress().currentStep().getManeuver().getInstruction()` and `routeProgress.currentLegProgress().upComingStep().getManeuver().getInstruction()` on circle traffic give me wrong info. "At the roundabout turn left" instead of "At the roundabout turn right" there LAT 48.60834754947365 LON 22.26712001255102. Please check this.

**Comment by ericrwolfe** [comment]
@samvgorode thanks for the feedback. 

This is an upstream issue in either the Directions API or in OpenStreetMap with this particular roundabout. I looked at other roundabouts in the area and they seem to be correct. 

I've reached out to our directions team and will post back with an update when we have a fix on our end.

**Comment by cammace** [comment]
https://github.com/mapbox/mapbox-navigation-android/pull/242 adds the fix which was introduced upstream.
