### ISSUE TITLE
NavigationCamera zoom level does not change before user change it

### ISSUE THREAD

**Issue by ben-j69** [mapbox/mapbox-navigation-android#1840]
Hello,
I noticed that since 0.32 some work have been done on camera animation.
I update from 0.30 to 0.32 or 0.33 dans my NavigationCamera behaviour is broken.

When I start navigation and call         camera?.resetCameraPositionWith(NavigationCamera.NAVIGATION_TRACKING_MODE_GPS) my camera was zooming on my position. 
Since 0.32 if the user has not changed the zoom level with his fingers this line has no effect.
Not sure if it is a bug or a feature..

**Android API:28**
**Mapbox Navigation SDK version:0.33.2**

### Steps to trigger behavior

 1.Start navigation
2.navigationCamera?.resetCameraPositionWith(NavigationCamera.NAVIGATION_TRACKING_MODE_GPS) 

### Expected behavior
The camera zoom on the user position to start the navigation
### Actual behavior
The camera is far from earth and does not move

**Comment by danesfeder** [comment]
@ben-j69 if you can reproduce this every time navigation starts, do you mind recording a `.gif` so we can get a better sense of the unwanted camera behavior?  Also, more complete code snippets that reproduce this behavior / give more context into your entire application code would be great.  Thank you

**Comment by ben-j69** [comment]
@danesfeder I solved my issue by changing the calls to my camera.

I was starting it and resetting it too fast.

You can close this issue.

**Comment by danesfeder** [comment]
Thanks @ben-j69 do you mind sharing the code that was called too fast?  We are always looking for ways to improve our SDK and developer experience.  Seeing your usage that produced undesired behavior would be helpful insight.

**Comment by ben-j69** [comment]
@danesfeder 

I was calling useless code

```
camera = NavigationCamera(mMapboxMap, navigation!!, locationComponent)
camera?.updateCameraTrackingMode(NavigationCamera.NAVIGATION_TRACKING_MODE_GPS)
camera?.resetCameraPositionWith(NavigationCamera.NAVIGATION_TRACKING_MODE_GPS)
navigation?.startNavigation(directionsRoute)
camera?.start(directionsRoute)
```

And to keep the same behaviour on 0.33.2

```
camera = NavigationCamera(mMapboxMap, navigation!!, locationComponent)
navigation?.startNavigation(directionsRoute)
camera?.start(directionsRoute)
```

Just a bit disappointed to not have found the way to set the zoom level I want on the camera at start.
