### ISSUE TITLE
https://github.com/mapbox/mapbox-navigation-android/issues/1751#issuecomment-464737928_

### ISSUE THREAD

**Issue by sagarlotus** [mapbox/mapbox-navigation-android#1846]
Hey @danesfeder As per your suggestions, I have implement version 0.29.0 in application and remove Maps SDK version dependency. But still I am facing same issue ( Fatal signal 11 (SIGSEGV), code 1, fault addr 0x0 in tid 8500 (FinalizerDaemon)).
Kindly look into same.
Appreciate quick reply.

**Comment by danesfeder** [comment]
Hey @sagarlotus unfortunately, we need more context / a code snippet to reproduce your error here.  If you're able to provide this, please comment on this thread and we will reopen the ticket once we are able to reproduce as well.  Thank you for understanding
