### ISSUE TITLE
Navigation SDK for Android failed linking references

### ISSUE THREAD

**Issue by athmane2197** [mapbox/mapbox-navigation-android#1853]
Hello, 
I tried to add Navigation SDK but a got an error and can't solved it.
I am using  compileSdkVersion 27 ('com.android.support:appcompat-v7:27.1.1').

Android resource linking failed
/Users/athmaneben/Desktop/android/PaniBusDriver/app/build/intermediates/incremental/mergeDebugResources/merged.dir/values-v28/values-v28.xml:7: error: resource android:attr/dialogCornerRadius not found.
/Users/athmaneben/Desktop/android/PaniBusDriver/app/build/intermediates/incremental/mergeDebugResources/merged.dir/values-v28/values-v28.xml:11: error: resource android:attr/dialogCornerRadius not found.
/Users/athmaneben/Desktop/android/PaniBusDriver/app/build/intermediates/incremental/mergeDebugResources/merged.dir/values/values.xml:2832: error: resource android:attr/fontVariationSettings not found.
/Users/athmaneben/Desktop/android/PaniBusDriver/app/build/intermediates/incremental/mergeDebugResources/merged.dir/values/values.xml:2833: error: resource android:attr/ttcIndex not found.
error: failed linking references.

**Comment by danesfeder** [comment]
Hey @athmane2197 👋 going to go ahead and close this.  As I said, updating to API 28 should resolve this.  Feel free to open another ticket if you see the same issue
