### ISSUE TITLE
Initial camera for turn-by-turn nav is way too zoomed out

### ISSUE THREAD

**Issue by tomrom95** [mapbox/mapbox-navigation-android#1854]
When I initialize the `NavigationView` and start navigating, the initial view is consistently far too zoomed out. This zoom level doesn't change until I start moving. Here are two screen shots of what I've experienced:

<img width="419" alt="Screen Shot 2019-04-01 at 3 15 10 PM" src="https://user-images.githubusercontent.com/7095894/55363313-7e737e00-5491-11e9-94b6-920587ac52de.png">
<img width="421" alt="Screen Shot 2019-04-01 at 3 13 58 PM" src="https://user-images.githubusercontent.com/7095894/55363317-803d4180-5491-11e9-858b-c586e7eecb1e.png">

Is it possible to set the initial zoom level to something different so that the roads around the user are more detailed and visible?

**Android API:** 28
**Mapbox Navigation SDK version:** v0.30.0

### Steps to trigger behavior
Initialize `NavigationView` and start navigation. Do not move the current location. The initial camera should be pretty far away from the user location.

### Expected behavior
Start the camera more zoomed into the user's location. After moving, this zoom level can change accordingly. It would also be helpful to just set this value directly.

### Actual behavior
Camera is far too zoomed out. See screen shots above.

**Comment by danesfeder** [comment]
Hey @tomrom95, you can [`initialize`](https://github.com/mapbox/mapbox-navigation-android/blob/master/libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/NavigationView.java#L417-L438) the `NavigationView` with a `CameraPosition` set to whatever parameters you'd like.  Does that help out here?  An example use would be a position set to the origin coordinate of the route with desired zoom and tilt.

**Comment by tomrom95** [comment]
@danesfeder That will work for now. Thank you! Although, it would be nice to have a `setCameraPosition` method exposed so that the position can be updated after or in a separate manner from initialization.

**Comment by danesfeder** [comment]
@tomrom95 once the `NavigationView` is initialized you can animate the camera via `NavigationView#retrieveNavigationMap#retrieveCamera#update`.  Note the documentation regarding how these updates play with our current tracking modes.  If we are tracking, we need to stop in order to allow your animate to fire correctly.

I'm going to go ahead and close this here as resolved.  If you have a feature request around this, please feel free to open a ticket.

**Comment by imaxkhan** [comment]
hi we are using latest mapbox android sdk for navigation
the camera view wont change at turning point
any idea?
