### ISSUE TITLE
Navigation between places in Indoor Map

### ISSUE THREAD

**Issue by Sadmansamee** [mapbox/mapbox-navigation-android#1856]
We building an app for Indoor Map, We'll add indoor map via shapefile or geojson now How would we add the functionality for Navigation between Places

**Comment by danesfeder** [comment]
Hey @Sadmansamee 👋 unfortunately, we currently don't support indoor routing / navigation but it's something we've had requests for in the past and are thinking about.  I cannot provide a rough timeline as that feature isn't on our roadmap.  Should this change, we can follow up here.  Thanks for understanding!
