### ISSUE TITLE
Fatal Exception: java.lang.IllegalAccessError when proguarded (R8)

### ISSUE THREAD

**Issue by hrach** [mapbox/mapbox-navigation-android#1857]
> Method 'java.lang.String c.e.c.a.a()' is inaccessible to class 'c.e.b.a.a.e' (declaration of 'c.e.b.a.a.e' appears in /XXX-Fa8I9XMskRAXduIQ2mvFCg==/base.apk

**Android API:** 29
**Mapbox Navigation SDK version:** 0.33.2

### Steps to trigger behavior

 1. Proguard app with R8 (1.4.77)
 2. Run a directions fetch

### Expected behavior

No crash.

### Actual behavior

```
Fatal Exception: java.lang.IllegalAccessError
Method 'java.lang.String c.e.c.a.a()' is inaccessible to class 'c.e.b.a.a.e' (declaration of 'c.e.b.a.a.e' appears in /XXX-Fa8I9XMskRAXduIQ2mvFCg==/base.apk)
com.mapbox.api.directions.v5.DirectionsResponseFactory.generateRouteOptions (DirectionsResponseFactory.java:75)
com.mapbox.api.directions.v5.DirectionsResponseFactory.a (DirectionsResponseFactory.java:28)
com.mapbox.api.directions.v5.MapboxDirections$1.onResponse (MapboxDirections.java:128)
retrofit2.ExecutorCallAdapterFactory$ExecutorCallbackCall$1$1.run (ExecutorCallAdapterFactory.java:71)
android.os.Handler.handleCallback (Handler.java:873)
```

**Comment by danesfeder** [comment]
Thanks for the report @hrach.  We will look into this and report back.  From first glance, it looks like a possible issue in our upstream [Java SDK](https://github.com/mapbox/mapbox-java).  Will move the ticket there if we deem this is the case.  

cc @osana

**Comment by hrach** [comment]
Thanks, I'm not sure it I can somehow mitigate this with additional rule, so if there is a way, I would be glad to know :)

**Comment by utersdev** [comment]
i have the same problem

**Comment by pmsferreira** [comment]
same here

**Comment by JPSiller** [comment]
This works with proguard without R8 (same rules). Is this an issue in the mapbox side or something to be reported to Xamarin.Android project?

**Comment by freszu** [comment]
This seems like a bug in R8 i did some investigation and actually ended up opening an issue on R8 tracker 🙈 lets see what they say : https://issuetracker.google.com/issues/136195382

Until it's resolved i have reverted to using proguard

**Comment by freszu** [comment]
Issue was confirmed as a bug in R8 shrinker and received a fix - we will need to wait till its listed in new build tools release or specify r8 version manually until then. 
cc @danesfeder

**Comment by hrach** [comment]
Closing. Fix is on the way and workaround is possible ^^^.

**Comment by schmem55** [comment]
any news?
