### ISSUE TITLE
Styling instruction view at runtime.

### ISSUE THREAD

**Issue by ManojMM026** [mapbox/mapbox-navigation-android#1863]
**Android API: Android Pie** 
**Mapbox Navigation SDK version: 0.33.2**

Hey, I am using **NavigationFragment** (Example from SDK) to show turn by turn navigation. It is working great, What I am looking here is to customize banner (instruction view).

Find the Image attached. 

![navigation_fragment](https://user-images.githubusercontent.com/2713390/55545282-7cf0c280-56ea-11e9-804d-473dbc0ce856.png)

I am aware that I can do this using style but instead, I want to do it programmatically. I tried with `val instruction=navView.findViewById<ManeuverView>(R.id.subManeuverView)
                    instruction.setPrimaryColor(Color.GREEN)
                    instruction.setSecondaryColor(Color.BLACK)`
did not worked for me. 
### Steps to trigger behavior

 1. Load Navigation view.
 2. Customize navigation view in onNavigationReady
 

### Expected behavior
Should change the color of banner background and text.

### Actual behavior
Nothing is getting change. 

It should have been straight forward api's provided by SDK. I don't want to create style every time I want to customize the map marker or any other control. 
@danesfeder please help me with this.

**Comment by danesfeder** [comment]
Hey @ManojMM026 👋 thanks for the feedback here.  The `NavigationView` used inside of the `NavigationFragment` is looking for style attributes to color the different aspects of the view.  We have some [documentation](https://docs.mapbox.com/android/navigation/overview/map-styling/#style-the-navigationview) around this, I hope it helps.  Given the amount of customization points for the UI, we didn't feel it was feasible to have separate APIs for each color.

**Comment by ManojMM026** [comment]
@danesfeder Maybe I should tell you more what I want to do here. So I load the map and I customize the toolbar and other colors according to the user.  Color values come to me from the server. I already visited doc which says you have to create a style which I think for me is not possible as it's dynamic.
