### ISSUE TITLE
Limite waypoints navegation

### ISSUE THREAD

**Issue by andemcdo** [mapbox/mapbox-navigation-android#1868]
**Android API:**
**Mapbox Navigation SDK version:**

I would like to use navigation sdk, but I need to send more than 23 waypoints to the browser, is it possible?

**Comment by Guardiola31337** [comment]
Hey @andemcdo 👋 thanks for reaching out and report your question.

We set this initial limit (25) as indicated in the documentation https://docs.mapbox.com/api/navigation/#directions but this is configurable based on your developer account. You can reach out to help@mapbox.com for account limit help here.

Going to go ahead and close as non-actionable on the SDK.

cc @coxchapman @taraniduncan
