### ISSUE TITLE
Allow for custom SymbolManager in NavigationMapboxMap

### ISSUE THREAD

**Issue by clj0020** [mapbox/mapbox-navigation-android#1870]
**Android API: 28**
**Mapbox Navigation SDK version: 0.34.0 **

Using NavigationMapboxMap, I would like to be able to use the SymbolManager directly. It would be nice if less things were private in the NavigationMapboxMap class so that devs could override it and add functionality. Currently, while trying to do something as simple as changing the icon of the map marker, I had to do this:

`mapboxMap.style?.addImage("mapbox-navigation-marker", context.getDrawable(R.drawable.ic_drop_off_primary))`

This is super hacky because it overrides the image that NavigationMapboxMap added by itself. Why not let devs create custom symbol managers and extend NavigationMapboxMap? I understand that I could do what NavigationMapboxMap does by myself, but I like that there's already something I can use with easy functions. It would be awesome if it was more extensible though.

Thanks

**Comment by danesfeder** [comment]
@clj0020 yeah definitely, moving in #1891

**Comment by clj0020** [comment]
Thanks @danesfeder
