### ISSUE TITLE
Puck and camera stuttering after 0.33.0

### ISSUE THREAD

**Issue by cmahopper** [mapbox/mapbox-navigation-android#1872]
**Android API:** Android 9
**Mapbox Navigation SDK version:** 0.33.0 and 0.34.0

From 0.33.0 and later, the puck and the camera seems to lag/stutter a lot.

Comparison recordings:
0.32.0: https://i.imgur.com/6G9prf7.gifv
0.33.0 and later: https://i.imgur.com/e8VKvPv.gifv

As you can see, the initial zoom to location is stuttering a lot, as is every camera update afterwards.
The initial zoom is created through `NavigationView#initialize(OnNavigationReadyCallback, CameraPosition)`.

I noticed this PR in 0.33.0: https://github.com/mapbox/mapbox-navigation-android/pull/1815, but setting `updateLocationFpsThrottleEnabled(false)` had no effect.

**Comment by Guardiola31337** [comment]
Hey @cmahopper 👋 thanks for reaching out and report your issue.

Could you add some more information around your test setup and used device?

Have you tried 👇? https://github.com/mapbox/mapbox-navigation-android/blob/605d491832c8df165583fe96ce22cefb884a8093/libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/map/NavigationMapboxMap.java#L193-L202

If there is any sample or pseudo code you can provide, that would be really helpful and it'll give us better insight into your implementation and what could be causing your problem.

**Comment by cmahopper** [comment]
@Guardiola31337 After some debugging it turns out that `NavigationMapboxMap#updateLocationFpsThrottleEnabled` was the solution! However, I had only called it in `onCreate` of the Activity, where it had no effect, even after initializing the `NavigationView`. Fortunately, it worked when I called it in `onNavigationReady`.

I gotta say, I'm not crazy about how this was implemented. The lagging is very noticeable if it's enabled, and I'm running a new Oneplus 6 with 100% battery, so I don't understand why I would want to enable it.

I tried the method you mentioned as well, but that didn't seem to have any effect. But maybe that one is only noticeable when the device is low on battery.

**Comment by Guardiola31337** [comment]
> However, I had only called it in `onCreate` of the Activity, where it had no effect, even after initializing the `NavigationView`. Fortunately, it worked when I called it in `onNavigationReady`.

That's weird, we're storing a flag https://github.com/mapbox/mapbox-navigation-android/blob/605d491832c8df165583fe96ce22cefb884a8093/libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/map/LocationFpsDelegate.java#L49 that we use afterwards. Could you share a sample / snippet of code of your setup?

> I gotta say, I'm not crazy about how this was implemented. The lagging is very noticeable if it's enabled, and I'm running a new Oneplus 6 with 100% battery, so I don't understand why I would want to enable it.

For implementations details you can check https://github.com/mapbox/mapbox-navigation-android/pull/1815 and https://github.com/mapbox/mapbox-navigation-android/pull/1669 Please provide any feedback / comments / suggestions 🙏, that'd be 💯 

We've tested both broadly and saw great performance improvements without hurting user experience. In any case, we're constantly keeping an eye on this and tweaking it - trying to provide a good balance between good performance (low battery drainage, etc.) and good user experience and of course trying to accommodate to the vast majority of devices. But yeah, that's great feedback will 👀 

That being said, if you think your users will be somehow affected by these additions, we'd recommend you to disable throttling altogether with the above-mentioned APIs.

> I tried the method you mentioned as well, but that didn't seem to have any effect. But maybe that one is only noticeable when the device is low on battery.

Yeah, you're right, we're checking if the device is plugged in, you can 👀 the Maps FPS throttling logic here https://github.com/mapbox/mapbox-navigation-android/blob/605d491832c8df165583fe96ce22cefb884a8093/libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/map/MapFpsDelegate.java#L100-L111

Thanks a lot and again, if you think this could be improved somehow, please let us know., feedback is more than welcome!

**Comment by devotaaabel** [comment]
@cmahopper another solution is following how animations were dealt with in `ComponentNavigationActivity` in https://github.com/mapbox/mapbox-navigation-android/pull/1849 if you are interested in the performance improvements. Closing this for now.
