### ISSUE TITLE
Multiple issues with example activity

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-navigation-android#1874]
I'm easily able to produce multiple issues with the example activity. They range from not being able to close the activity to incorrect placement of UI elements:

![ezgif com-video-to-gif (57)](https://user-images.githubusercontent.com/2151639/55943530-0f431a00-5c47-11e9-9376-5a378f84f47d.gif)

**Comment by Guardiola31337** [comment]
We should revisit which issues are still present at this point.

**Comment by Guardiola31337** [comment]
This example is not available anymore.

Closing here.

cc @abhishek1508
