### ISSUE TITLE
Way name outdated after resuming navigation

### ISSUE THREAD

**Issue by Guardiola31337** [mapbox/mapbox-navigation-android#1886]
After integrating https://github.com/mapbox/mapbox-navigation-android/pull/1880 we've noticed that the way name sticks outdated after resuming a navigation session 👀

![way_name_outdated](https://user-images.githubusercontent.com/1668582/56142392-9dcbda00-5f6c-11e9-974f-0a7f69802c57.jpg)

After debugging it seems https://github.com/mapbox/mapbox-navigation-android/blob/b65953ab9f326f432b8971eef6f5550f93eb9d16/libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/map/WaynameFeatureFinder.java#L19 is always returning an empty list when bringing the app into the foreground after backgrounding it.

Maps SDK upstream ticket https://github.com/mapbox/mapbox-gl-native/issues/14422 and fix https://github.com/mapbox/mapbox-gl-native/pull/14426

cc @tobrun

**Comment by zugaldia** [comment]
Quick update to report that https://github.com/mapbox/mapbox-gl-native/pull/14426 is now reviewed and approved. The current goal is to merge this change in time for the upcoming `beta.1` release of the `mojito` release.

cc: @tobrun @LukasPaczos for confirmation.

**Comment by Guardiola31337** [comment]
@zugaldia 
Could we do a patch release (`v7.3.2`) after confirming the fix solves the regression so we will be able to include it in our next release?

**Comment by tobrun** [comment]
Since the release is still two weeks out, I feel a patch is justified. Need to do some a bit more testing on https://github.com/mapbox/mapbox-gl-native/pull/14426 tomorrow and can work on releasing it after.

**Comment by Guardiola31337** [comment]
Awesome @tobrun thanks for the update! We will test it downstream as well as soon a `SNAPSHOT` including https://github.com/mapbox/mapbox-gl-native/pull/14426 is ready and report back here.

**Comment by Guardiola31337** [comment]
Confirming that testing with `7.4.0-SNAPSHOT` including https://github.com/mapbox/mapbox-gl-native/pull/14426 we're not able to reproduce OP anymore. We're good on doing a patch release 🚀 

cc @tobrun @zugaldia
