### ISSUE TITLE
Option for Navigation Route to follow user

### ISSUE THREAD

**Issue by markspit93** [mapbox/mapbox-navigation-android#1893]
Right now the whole navigation route stays drawn on the map from start to finish unless a reroute happens.

I would like an option where as the user is moving closer to the destination the route's origin is always at the user's current location 
This way the user can see progress easier instead of the whole route with the position in the middle of it.

Another option instead could be to have the route that has already been traveled stylized with another color.

**Comment by danesfeder** [comment]
Hey @markspit93 👋 thank you for this feature request - we are currently tracking this work in https://github.com/mapbox/mapbox-navigation-android/issues/892.  Please follow that ticket for progress as we work with the upstream Maps SDK.  Thanks!   Going to close here as duplicate.
