### ISSUE TITLE
Release 0.36.0

### ISSUE THREAD

**Issue by Guardiola31337** [mapbox/mapbox-navigation-android#1897]
### Release checklist @Guardiola31337   

- [x] Run through testapp/demo app and test all activities
- [x] Change version name to `0.36.0` in `gradle.properties`
- [x] Publish `0.36.0` artifact to Maven Central
- [x] Change version name back to `0.37.0-SNAPSHOT`
- [x] Update `CHANGELOG.md`
- [x] Tag `v0.36.0` in GitHub

### Post-release @langsmith   

- [x] Update `README.md`
- [x] Update `constants.js` file in `android-docs` repo 👀 https://github.com/mapbox/android-docs#updating-for-sdk-releases
- [x] Generate `navigation` and `navigation-ui` javadocs and add to `android-docs` repo
- [x] Update nav dependency used by android-tutorial-demo app.
- [x] Update config files in /help repo _after_ tutorial (☝️) update is finished.
  - @colleenmcginnis @HeyStenson we are good to go for this release 👍 

### Changelog:

Note: This release breaks `SEMVER` / contains API breaking changes. Please consult this [migration guide](https://github.com/mapbox/mapbox-navigation-android/wiki/0.36.0-Migration-Guide) for the necessary updates required.

* Prevent RouteLeg list access for current step creation [#1896](https://github.com/mapbox/mapbox-navigation-android/pull/1896)
* Create NavigationViewRouter timeout to unblock routing state [#1888](https://github.com/mapbox/mapbox-navigation-android/pull/1888)
* Bump mapbox-android-sdk version to 7.3.2 [#1894](https://github.com/mapbox/mapbox-navigation-android/pull/1894)
* Add NavigationMapRoute attribute for styling route line cap expression [#1818](https://github.com/mapbox/mapbox-navigation-android/pull/1818)
* Update navigator to 6.1.3 [#1892](https://github.com/mapbox/mapbox-navigation-android/pull/1892)
* [SEMVER] Add NavigationMapboxMap#addCustomMarker for usage of SymbolManager [#1891](https://github.com/mapbox/mapbox-navigation-android/pull/1891)
* Fix notification and banner ETAs not in sync [#1889](https://github.com/mapbox/mapbox-navigation-android/pull/1889)
* Bump mapbox-navigation-native version to 6.1.2 [#1885](https://github.com/mapbox/mapbox-navigation-android/pull/1885)
* Add offline version check to Navigation View Router [#1864](https://github.com/mapbox/mapbox-navigation-android/pull/1864)
* Add offline options to Navigation Launcher [#1862](https://github.com/mapbox/mapbox-navigation-android/pull/1862)
* [SEMVER] Add dynamic offline routing to NavigationView [#1829](https://github.com/mapbox/mapbox-navigation-android/pull/1829)

/cc: @mapbox/navigation

**Comment by langsmith** [comment]
Done! 🛫
