### ISSUE TITLE
How to modify navigation route view

### ISSUE THREAD

**Issue by rasimmammadoff** [mapbox/mapbox-navigation-android#1900]
How can I modify navigation route view? I display the view with a navigationLauncher and I want to add  textView (during navigating show additional information) to this  activity. Is it possible?

**Comment by danesfeder** [comment]
Hey @rasimmammadoff 👋 unfortunately, not with the `NavigationLauncher`.  You can do this with a `NavigationView` implementation.  Check out [`EmbeddedNavigationActivity`](https://github.com/mapbox/mapbox-navigation-android/blob/master/app/src/main/java/com/mapbox/services/android/navigation/testapp/activity/navigationui/EmbeddedNavigationActivity.java) in our test app that demonstrates code similar to your use-case.  Thanks!
