### ISSUE TITLE
NavigationLauncherOptions has no option for NavigationListener to add

### ISSUE THREAD

**Issue by waris117** [mapbox/mapbox-navigation-android#1902]
Hi
i am using mapbox navigation in react native android app and created native module to call navigation functions. in native module i have
 NavigationLauncherOptions options = NavigationLauncherOptions.builder()
                            .initialMapCameraPosition(position)
                            .directionsRoute(currentRoute)
                            .shouldSimulateRoute(true)
                            .build();
 NavigationLauncher.startNavigation(getCurrentActivity(), options);
When user cancels navigation or user arrives on destination, i want to know, i have seen NavigationListener has following methods but no way to add NavigationListener in NavigationLauncherOptions
   @Override
    public void onCancelNavigation() {
   }
   @Override
    public void onNavigationFinished() {
    }
    @Override
    public void onNavigationRunning() {
    }
How i can achieve that? thanks

**Comment by Guardiola31337** [comment]
Hey @waris117 👋 unfortunately, not with the `NavigationLauncher`.  You can do this with a `NavigationView` implementation. Check out https://docs.mapbox.com/android/navigation/overview/#navigationview Thanks!
