### ISSUE TITLE
onArrival doesn't get called if navigation is started with multiple stops

### ISSUE THREAD

**Issue by hussi1** [mapbox/mapbox-navigation-android#1904]
If i start Navigation with multiple waypoints then onarrival does not get called when a waypoint is reached.
Heres how i am getting route with multiple waypoints : 

NavigationRoute.Builder builder = NavigationRoute.builder(HomeActivity.this)
                    .accessToken(Mapbox.getAccessToken())
                    .origin(originPoint)
                    .destination(destinationPoint);
            if (address_list.size()>2) {
                for (int i=1;i<address_list.size()-1;i++) {
                 builder.addWaypoint(Point.fromLngLat(address_list.get(i).getLongitude(),address_list.get(i).getLatitude()));
                }
            }
    builder.profile(DirectionsCriteria.PROFILE_DRIVING)
                    .annotations(DirectionsCriteria.ANNOTATION_CONGESTION)
                    .alternatives(true);
                builder.build()
                    .getRoute(this);

**Android API:** 28
**Mapbox Navigation SDK version:** com.mapbox.mapboxsdk:mapbox-android-navigation-ui:0.34.0

### Steps to trigger behavior

 1.Start a Navigation with waypoints
 

### Expected behavior
 onArrival should be called at every waypoint

### Actual behavior
 onArrival is only called on destination

**Comment by danesfeder** [comment]
Hey @hussi1 thanks for the report here.  We will look into this! 

@kevinkreiser from a `Navigator` route status standpoint this is unexpected behavior right?

**Comment by asegestam** [comment]
I'm having the same issue, atleast I think so. Im also having the same problem as [https://github.com/mapbox/mapbox-navigation-android/issues/1267](url) so I dont actually know if onArrival is getting called at the destination either.

**Comment by hussi1** [comment]
routeUtils.isArrivalEvent(routeProgress) not working for me either.

**Comment by danesfeder** [comment]
@hussi1 @asegestam this looks like a possible bug on our side that we are looking into.  

In the meantime, can you disable `MapboxNavigationOptions#enableAutoIncrementLegIndex(false)`.  With that option set to false, you will need to increment the leg index manually when you're ready to do so with `MapboxNavigation#updateRouteLegIndex(int legIndex)`.  With this setup, you will be able to receive the complete status and arrival listener callback.  

We will continue to look into the issue with auto-incrementing.  Thanks for your patience!

**Comment by hussi1** [comment]
At what point will in increment legIndex ?

**Comment by danesfeder** [comment]
Hey @hussi1, we just merged a fix for this.

But you would increment in the `ProgressChangeListener` looking at `RouteProgress#currentState()` and then increment when it is `ROUTE_ARRIVED`

**Comment by hussi1** [comment]
Will i have to update version for this ? or its in same version

**Comment by asegestam** [comment]
@hussi1 No, I've tested with the same versions as you. I think this will be released in a future update.

**Comment by Guardiola31337** [comment]
@hussi1 @asegestam that's correct, it'll be included in the upcoming release `v0.37.0`.

In the meantime, as my colleague @danesfeder explained above you could do https://github.com/mapbox/mapbox-navigation-android/issues/1904#issuecomment-486271276 and https://github.com/mapbox/mapbox-navigation-android/issues/1904#issuecomment-486799010 should workaround it. Thanks both for checking out the SDK and helping out troubleshooting the issue.

**Comment by hussi1** [comment]
@danesfeder how can i updateRouteLegIndex ? can't find it in RouteProgress class
