### ISSUE TITLE
Mute Speech button doesn't work in Fragment

### ISSUE THREAD

**Issue by asegestam** [mapbox/mapbox-navigation-android#1911]
**Android API:**
**Mapbox Navigation SDK version:**
This is how I found this bug, I'm not sure if you need to create your own onClickListener for the button but I've tried this and used `retrieveSoundButton().toggleMute()` with no success.
### Steps to trigger behavior

 1. Create a Fragment with NavigationView defined in XML
 2. Start a navigation
 3. Press mute speech button

### Expected behavior
The button changes it's view to a muted button and mutes the speech instructions

### Actual behavior
Nothing happens when clicking the button, sometimes it will work after spam clicking the button enough times.

**Comment by danesfeder** [comment]
Hey @asegestam what is the desired use-case here?  Are you trying to mute the `NavigationView` from another button that isn't the mute button itself?

**Comment by asegestam** [comment]
> Hey @asegestam what is the desired use-case here? Are you trying to mute the `NavigationView` from another button that isn't the mute button itself?

No im simply using the standard mute button in `NavigationView` but it's not muting. I'll provide a Gyazo  GIF showing the issue.

https://gyazo.com/13ae7d09f413ffdc9f3fbdcb827ca02c

**Comment by danesfeder** [comment]
@asegestam you shouldn't need to add any listeners on your end for the mute functionality to work

**Comment by danesfeder** [comment]
@asegestam hey 👋 were you able to resolve this?  Providing some code snippets reproducing your issue as well as the navigation SDK version would also be helpful.

**Comment by asegestam** [comment]
Hey, no the issue is still there for me and im using version 0.37 of the SDK.
Im using the navigation in a fragment and this is how i initialize the navigation view. 
```
    override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
        super.onViewCreated(view, savedInstanceState)
        navigationView = navigation_view_fragment
        navigationView.onCreate(savedInstanceState)
        navigationView.initialize(this)
    }
```
and this is my startNavigation method that gets called when `onNavigationReady` is called. 
```
 private fun startNavigation(route: DirectionsRoute) {
        val options: NavigationViewOptions = NavigationViewOptions.builder()
                .directionsRoute(route)
                .shouldSimulateRoute(true)
                .navigationListener(this)
                .progressChangeListener(this)
                .routeListener(this)
                .waynameChipEnabled(true)
                .build()
        navigationView.startNavigation(options)
    }
```
and this is my XML layout
```
<androidx.constraintlayout.widget.ConstraintLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    tools:context="com.example.smspark.views.NavigationFragment">

    <com.mapbox.services.android.navigation.ui.v5.NavigationView
        android:id="@+id/navigation_view_fragment"
        android:layout_width="0dp"
        android:layout_height="0dp"
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toTopOf="parent"
        app:navigationDarkTheme="@style/NavigationViewDark"
        app:navigationLightTheme="@style/NavigationViewLight"/>

</androidx.constraintlayout.widget.ConstraintLayout>

```
The feedback button works fine though, so it's only affecting thesound button.

**Comment by danesfeder** [comment]
> Nothing happens when clicking the button, sometimes it will work after spam clicking the button enough times.

So you don't have any click listener hooked up to the sound button?  That's the current state of the code and nothing happens to the UI of the button when clicked, including no actual muting of the instructions?

**Comment by asegestam** [comment]
I do not no, but it does react to clicks by doing a ripple but the button never changes it's state to muted nor mutes the instructions.
As you can see in my gif https://gyazo.com/13ae7d09f413ffdc9f3fbdcb827ca02c

**Comment by NitroG42** [comment]
I have exactly the same issue, using a NavigationView in a CustomActivity, the sound button doesn't work at all (no listeners involved). I know that in a session it worked but didn't understand why (and the behavior was erratic). I'll look more into this issue and put my findings here.

**Comment by NitroG42** [comment]
I found why and made a pull request : #1936
