### ISSUE TITLE
Request: Exclude multiple road classes

### ISSUE THREAD

**Issue by cmahopper** [mapbox/mapbox-navigation-android#1912]
Using the `NavigationRoute.builder`, we would like to be able to `exclude` both ferries, toll roads and/or motorways, depending on user preferences. Currently, it is only possible to exclude one of these at a time.

Also requested in https://github.com/mapbox/mapbox-navigation-android/issues/737#issuecomment-470504493

**Comment by danesfeder** [comment]
Hey @cmahopper 👋 thanks for your request here.  Unfortunately, this is a limitation of the Directions API itself.  It currently does not allow multiple `exclude`s per request.  

That said, our directions team is actively thinking about this and we will be sure to update the SDK as soon as that work lands upstream.  I do not have a solid timeline on that work at this time.  Thank you for understanding!  

cc @kevinkreiser @danpat

**Comment by Chrisser000** [comment]
@danesfeder Understood, thank you for your response

**Comment by cmahopper** [comment]
@danesfeder Understood, thank you for the response

**Comment by billyking991** [comment]
I would love this feature as well.  Here's hoping that the directions team can figure it out!!  I'm on the CT shoreline and I would love to be able to exclude ferries and tolls when I go to Long island.
