### ISSUE TITLE
Add custom style parameter to NavigationMapboxMap drawRoute method. 

### ISSUE THREAD

**Issue by clj0020** [mapbox/mapbox-navigation-android#1917]
Would be very useful if there was another version of the drawRoute method that took a custom style as a parameter so that route styles could be changed at run time.

**Comment by clj0020** [comment]
Any update at all?

**Comment by danesfeder** [comment]
Hey @clj0020 I understand your request here.  But this currently would necessitate a good amount of refactoring of the underlying code in `NavigationMapRoute`.  I'll leave this ticket open as a feature request, but we currently have a full work pipeline and are not able to prioritize this request.  Thank you for understanding.

**Comment by clj0020** [comment]
So you could just have it reinitialize a new NavigationMapRoute as the mapRoute, and I tried doing this, but it crashed because MapRouteLine adds layers under the same exact name every time in lines 132-140. If you made it to where you could override sources that had the same name and not crash, then a lot of things would be simpler including doing this very basic customization.

**Comment by danesfeder** [comment]
Yes, thank you @clj0020 - this is likely the kind of approach we will take when the work is done.  In the meantime, if you'd like to submit a PR that addresses this feel free to cut a PR with those changes as you've outlined.  Thanks!

**Comment by Guardiola31337** [comment]
@abhishek1508 is this going to be supported in the `1.0` UI SDK?

cc @cafesilencio

**Comment by cafesilencio** [comment]
I think this is supported 1.0 of the UI SDK by calling NavigationMapboxMap.retrieveMap().setStyle().  Our BasicNavigationActivity example calls this in order to change the map style dynamically. Internally a new instance of the MapRouteLine class is created with the new style so any changes to the route line styles should get picked up.

**Comment by Guardiola31337** [comment]
Thanks for confirming @cafesilencio 

Thanks for checking out the SDK @clj0020 This seems that will be supported in `1.0` so I'm going to go ahead and closing here. Please stay tuned for the upcoming beta release 🚀
