### ISSUE TITLE
setting milestone for every x distance in a STEP using given Trigger Properties

### ISSUE THREAD

**Issue by kamleshsahu** [mapbox/mapbox-navigation-android#1918]
**Android API:**
**Mapbox Navigation SDK version:**

### Steps to trigger behavior

 1. i want to get notified after every x distance in each step.

### Expected behavior
 1.for example : if current STEP distance is 45km.
 and if set X = 10km in my trigger property.
i want to get notified after 10km,20km,30km,40km in the current STEP.

can we do so using given TriggerProperties .how?need help @Guardiola31337 @danesfeder

**Comment by danesfeder** [comment]
Given the current `Milestone` setup, I believe this will only be possible with separate custom `Milestone`s.  So you would need a `StepMilestone` for each trigger distance: 10, 20, 30, etc.

**Comment by Guardiola31337** [comment]
Hey @kamleshsahu 👋 Any updates here? Wondering if https://github.com/mapbox/mapbox-navigation-android/issues/1918#issuecomment-489155794 helped solving your issue and we can close here.

**Comment by Guardiola31337** [comment]
Closing here as stale.

@kamleshsahu thanks for checking out the SDK. Feel free to cut a new ticket if you can still reproduce OP. Also noting that milestones is not going to be a feature of the upcoming `1.0` SDK.
