### ISSUE TITLE
Allow for customization of the LocationComponent's GPS Render Mode

### ISSUE THREAD

**Issue by clj0020** [mapbox/mapbox-navigation-android#1928]
Would be nice to have styling options for the GPS Render mode of the LocationComponent.

**Comment by danesfeder** [comment]
Hey @clj0020, you're able to customize this with `LocationComponent` style that you can provide via your `style.xml`.  Please see our styling [documentation](https://docs.mapbox.com/android/navigation/overview/map-styling/#style-the-navigationview) for more details.  Thanks!

**Comment by clj0020** [comment]
@danesfeder so you just want me to change the drawable every time? All I want to do is change the color of the foreground tint color at runtime which is easily possible using the location component options builder for the normal and compass render modes, but not for the gps render mode for some reason.
