### ISSUE TITLE
About Using Modified Valhalla Engine

### ISSUE THREAD

**Issue by Guo-astro** [mapbox/mapbox-navigation-android#1932]
Hi! Thanks for the amazing product! I would like to ask if we added extra parameters to the valhalla engine so we want to use our own binary source for navigation what is a good solution?

**Comment by danesfeder** [comment]
Hey @Guo-astro thanks! 👋 

> if we added extra parameters to the valhalla engine

Can you clarify or expand on this request?  Maybe with a code snippet illustrating?  I'm not sure I completely follow what you're asking for unfortunately.

**Comment by danpat** [comment]
@Guo-astro The Mapbox Navigation SDKs (iOS and Android) are designed to work with the Mapbox Directions API.  That API has some key elements that aren't present in raw OSRM/Valhalla responses that'll make it challenging to use the SDKs without.

We don't support using the SDK interacting with third-party navigation sources.  If you do this, you're pretty much on your own.

**Comment by Guo-astro** [comment]
@danpat @danesfeder Thanks very much for the response!  Understand the situation! 
We are using it in Japan , the quality of the map required are very high. I can read from your blog that you have contract from Zenrin company. So the question is 
1.tile server under navigation sdk already using zenrin map or still osm?
2. The voice for navigation sdk is very uncomfortable to local Japanese culture any chance to improve that?
3.the instructions for rotary are confusing in Japanese guess lots work need to done here too
4.The driving requirements and security is very strict in Japan so the cost model and lots of graph related restrictions in Valhalla need to be fine tuned a lot. Any plan to support that in business strategy?
5 We acquired traffic networks and large volume of traffic data from other Japan companies and want to use those data in navigation sdk any chance we can corporate ^^
