### ISSUE TITLE
Is there a way to flip the navigation? Like mirrored.

### ISSUE THREAD

**Issue by mickokenter** [mapbox/mapbox-navigation-android#1941]
**Android API:**
**Mapbox Navigation SDK version:**

### Expected behavior

I want to use the Mapbox navigation on a phone but use it as a HUD. Is there any way to flip the navigation map?

### Actual behavior
I tried some ways everything except the map is working as a flipped screen.

**Comment by Guardiola31337** [comment]
@asinghal22 is this something we want to support in `1.0`?

cc @abhishek1508

**Comment by LukasPaczos** [comment]
Closing as stale.
