### ISSUE TITLE
Navigator Module changelog

### ISSUE THREAD

**Issue by msh91** [mapbox/mapbox-navigation-android#1943]
Hi,
Is there any documentation or changelog for `Navigator` module?

**Comment by msh91** [comment]
anything news here?

**Comment by Guardiola31337** [comment]
Hey @msh91 👋 thanks for reaching out and report your question.

Overall, the shared `Navigator` library and functionality added in #1265 serves to bring many improvements to our core routing / processing logic.  Its core functionality is written in `C++` similar to our Maps SDK, which provides major performance enhancements.

Outside of performance and reliability, it makes it much easier to align platforms (iOS v. Android for example), where previously we were in a constant state of flux for platform parity.

In general, it should be transparent to developers (as it's an internal cross platform library used by the SDKs which implements some core features) but what are you missing exactly?

**Comment by msh91** [comment]
Hey @Guardiola31337 thanks for the response. 
I just wanted to know what's happening in that module :)
As far as I understand from the source code, the `Navigator` module performs 2 main jobs: offline routing and processing current navigation status. 
We don't need the first part, offline routing algorithms, because we have our own implementation of it. All we want to do is to change and customize `NavigationStatus` but we cannot do it because the `Navigator` module is closed-source! and also the `Navigator` class in that module is `final` so we cannot even extend it to have our own implementation. For these reasons, this project, Mapbox Navigation, is not open source anymore.
I think it would be great if these 2 different parts were 2 different modules with different accessibility rules.

**Comment by haibthe** [comment]
Hey @msh91, I parse DirectionsRoute from json string, after to launcher Navigation with simluator. But Fakelocation was running, instruction not changed. When I debug source in RouteProcessorRunnable, in process() **NavigationStatus status = mapboxNavigator.retrieveStatus(date,
                    options.navigationLocationEngineIntervalLagInMilliseconds());**
status -> INVALID. I don't know this reason.

**Comment by msh91** [comment]
Hi @haibthe, I think you should ask @Guardiola31337 for further information.

**Comment by haibthe** [comment]
Hi @msh91 , @Guardiola31337 , I fix that bug, DirectionsRoute's json don't have intersections field. Thanks you.
