### ISSUE TITLE
Too many parameters in NavigationMetaData constructor

### ISSUE THREAD

**Issue by JPSiller** [mapbox/mapbox-navigation-android#1945]
This is not a bug but rather a feature request. 

When binding this library to .Net (Xamarin) there is an issue with the NavigationMetaData constructor due to the fact that .Net doesn't allow more than 16 parameters in funcs and action delegates which are used during the binding.

If methods and constructors are kept below 17 parameters, it allows this library to be migrated to other technologies such as Xamarin without having the developer create a wrapper around the android jar. 

If you are interested keeping your number of parameters below 17 help us .Net developers migrate these technologies. Hope you consider it.

Thanks

**Comment by JPSiller** [comment]
Hi @andrlee 

I'm using Mapbox Android Telemetry 4.4.1(referenced through Maven). I'm migrating Mapbox SDK 7.4.0. 

When was that class removed? 

I can see the class no longer exists but I'm concerned then that the Maven Jar is incorrect since the binding generated that constructor.

Thanks!

**Comment by andrlee** [comment]
@JPSiller no worries, the new version of `Mapbox Android Telemetry` has not been released yet, the change is going to be released in `4.5.0` early next week.

**Comment by JPSiller** [comment]
@andrlee Perfect, thanks for the info.
