### ISSUE TITLE
Crash in NavigationEngine for certain routes

### ISSUE THREAD

**Issue by BoD** [mapbox/mapbox-navigation-android#195]
I experience a crash in `NavigationEngine` when trying to navigate to a particular route.

The crash happens here:
https://github.com/mapbox/mapbox-navigation-android/blob/v0.4.0/navigation/libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/NavigationEngine.java#L214

A `TurfException` is thrown with the message `Turf lineSlice requires a LineString made up of at least 2 coordinates.`

The problem is that indeed, `coords` has only one value, and I think this should be handled because the API call can indeed return such routes.

**Comment by cammace** [comment]
This has already been pointed out in https://github.com/mapbox/mapbox-navigation-android/issues/149 and fixed in 0.5.0. I suggest upgrading to the latest version.
