### ISSUE TITLE
Notification roundabout maneuver icon artifact

### ISSUE THREAD

**Issue by Guardiola31337** [mapbox/mapbox-navigation-android#1952]
Found 👇 while testing

![rotarystraight_notification_artifact](https://user-images.githubusercontent.com/1668582/58590773-dd0b6d00-8232-11e9-9746-8c24e780d467.png)

As seen in the screenshot the Notification roundabout maneuver icon presents an artifact.

For extra context this is the code in which the `ic_maneuver_roundabout_straight` `Drawable` is retrieved: https://github.com/mapbox/mapbox-navigation-android/blob/d447d418df8449fbf3aef4d7b6d868498f2de06e/libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/utils/ManeuverMap.java#L156-L157

I was able to reproduce with `rotarystraight` maneuver, it'd be great to double check that is also reproducible for `roundaboutstraight` maneuvers: https://github.com/mapbox/mapbox-navigation-android/blob/d447d418df8449fbf3aef4d7b6d868498f2de06e/libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/utils/ManeuverMap.java#L140-L141

Was able to reproduce in a couple of devices: Nexus 5 running Android 6.0 and CAT S60 running Android 6.0.1

👀 https://github.com/mapbox/mapbox-navigation-android/pull/1946#discussion_r288317754 and #1697

**Comment by Guardiola31337** [comment]
I run into this blog post [Fun with VectorDrawable’s (or: how to make them work everywhere)](https://www.ahunt.org/2017/02/fun-with-vectordrawables/) and apparently found out OP's issue root cause:

> **Android 4 and 6: missing drawable’s on 4, artifacts on 6 (Arc curves)**
>
> On Android 4, drawable’s with arc curves might randomly disappear (this is easy to test if you have a navigationview that you can hide and reopen repeatedly, e.g. in a BottomSheet context menu). On Android 6, such drawable’s can display artifacts (this is a different kind of corruption to what we saw on Android 4: on Android 6, arc curves seem to result in some points in the image being misplaced, as opposed to true corruption).
>
> After some experimenting, I discovered this only happens for Drawable’s with arc curves. You can check if these are present by looking for the letter “a” or “A” being present in the “android:pathData” part of your VectorDrawable. Or within the <path> if you’re looking at the source SVG.
>
> One simple way of getting rid of these is:
> 1. Import the source SVG into an SVG editor
> 2. Perform an “ungroup”
> 3. Export again.
>
> Boxy SVG is fairly lightweight option for doing this. If you’re processing a large number of drawable’s, scripting inkscape might be a more efficient choice. (Make sure to double check the output, there’s no guarantee that any edits will result in purging of arc curves.)

We should regenerate the drawables used for roundabouts and whatever drawable that includes arc curves (an arc curve can be spotted wherever 'a' or 'A' is used in a vector path) and see if the visual artifact is gone.

I also want to note that whereas `vectorDrawables.useSupportLibrary = true` is included for [`libandroid-navigation-ui`](https://github.com/mapbox/mapbox-navigation-android/blob/master/libandroid-navigation-ui/build.gradle#L12) it's not in `libandroid-navigation`. Although I tried this out and didn't solve OP, I think it'd be great to add it and prevent other compatibility issues in the future and for consistency with `libandroid-navigation-ui`.

**Comment by Guardiola31337** [comment]
> We should regenerate the drawables used for roundabouts and whatever drawable that includes arc curves (an arc curve can be spotted wherever 'a' or 'A' is used in a vector path) and see if the visual artifact is gone.

Took ☝️ for a quick spin and I was able to generate a roundabout `VectorDrawable` using [PaintCode](https://www.paintcodeapp.com/):

![paint_code_roundabout](https://user-images.githubusercontent.com/1668582/64440194-8ca97400-d099-11e9-8870-684366d8be43.png)

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by PaintCode - http://www.paintcodeapp.com -->
<!-- roundabout -->
<vector
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:aapt="http://schemas.android.com/aapt"
    android:name="roundabout"
    android:width="32dp"
    android:height="32dp"
    android:viewportWidth="32"
    android:viewportHeight="32">
    <!-- Group 3 -->
    <group
        android:name="group3"
        android:translateX="10"
        android:translateY="15">

        <!-- Bezier -->
        <path
            android:name="bezier"
            android:pathData="M 6.5,1 C 6.5,2.8 5.78,4.42 4.6,5.59 C 3.43,6.77 1.8,7.5 0,7.5 C -1.79,7.5 -3.41,6.78 -4.59,5.61 C -5.77,4.43 -6.5,2.8 -6.5,1 C -6.5,-0.79 -5.77,-2.42 -4.6,-3.59 C -3.42,-4.77 -1.79,-5.5 0,-5.5 C 1.79,-5.5 3.42,-4.77 4.6,-3.59 C 5.77,-2.42 6.5,-0.79 6.5,1 Z"
            android:strokeColor="#FF9E9E9E"
            android:strokeWidth="4"
            android:strokeLineJoin="round" />

        <!-- Rectangle 2 -->
        <path
            android:name="rectangle2"
            android:pathData="M -1.97,17.5 L 2.03,17.5 L 2.03,6.5 C 2.03,5.95 1.58,5.5 1.03,5.5 L -0.97,5.5 C -1.53,5.5 -1.97,5.95 -1.97,6.5 L -1.97,17.5 Z"
            android:fillColor="#FF000000" />

        <!-- Group -->
        <group
            android:name="group">

            <!-- Bezier 2 -->
            <group
                android:name="bezier2-transform"
                android:rotation="-180"
                android:translateY="1">
                <path
                    android:name="bezier2"
                    android:pathData="M -9.47,-7.49 C -9.47,-7.45 -9.49,-7.38 -9.49,-7.38 C -9.57,-6.97 -10.45,-2.64 -10.45,-2.64 C -10.47,-2.59 -10.47,-2.54 -10.47,-2.49 C -10.47,-2.25 -10.09,-2.03 -9.82,-2 L -5.5,-2 C -4.95,-2 -4.5,-1.55 -4.5,-1 L -4.5,1 C -4.5,1.55 -4.95,2 -5.5,2 C -5.5,2 -9.38,2.01 -9.75,2.01 C -10.01,2.01 -10.35,2.24 -10.35,2.51 C -10.35,2.56 -10.41,2.6 -10.39,2.65 L -9.46,7.39 C -9.46,7.39 -9.46,7.47 -9.46,7.51 C -9.46,7.78 -9.69,8.01 -9.97,8.01 C -10.1,8.01 -10.22,7.95 -10.31,7.87 L -20.5,0.01 L -10.31,-7.86 C -10.22,-7.94 -10.11,-7.99 -9.97,-7.99 C -9.7,-7.99 -9.47,-7.77 -9.47,-7.49 Z"
                    android:fillColor="#FF000000" />
            </group>
        </group>

        <!-- Oval -->
        <path
            android:name="oval"
            android:pathData="M 6.5,1 C 6.5,4.59 3.59,7.5 0,7.5 "
            android:strokeColor="#FF000000"
            android:strokeWidth="4" />
    </group>
</vector>
```

It seems that the visual artifact is not visible anymore although now we have another problem 👀 

![notification_instruction_icon](https://user-images.githubusercontent.com/1668582/64442469-deec9400-d09d-11e9-9ae7-22cd00564c90.png)

Notification icons are only white and / or transparent so we might need to keep playing until we get a drawable similar to what we currently have 👇 but without using arc curves.

![current_notification_instruction_icon](https://user-images.githubusercontent.com/1668582/64443119-42c38c80-d09f-11e9-8869-f1e1885da3e9.png)

**Comment by Guardiola31337** [comment]
This was addressed in https://github.com/mapbox/mapbox-navigation-android/pull/2481 Are we missing any follow up work? Are we good to close here? @JunDai 

Refs. https://github.com/mapbox/mapbox-navigation-android/pull/2516

**Comment by JunDai** [comment]
We could close this one.

I have another PR #2516 as an enhancement of this issue but that's been tracking by the issue #2454
