### ISSUE TITLE
Notification instruction not updated for arrive maneuver

### ISSUE THREAD

**Issue by Guardiola31337** [mapbox/mapbox-navigation-android#1956]
Found 👇 while testing

![you_have_arrive_maneuver_banner](https://user-images.githubusercontent.com/1668582/58713519-bc592980-8390-11e9-9544-1d13afa2d871.png)

![you_have_arrived_maneuver_notification_not_updated](https://user-images.githubusercontent.com/1668582/58713526-bf541a00-8390-11e9-9e3c-c979b13dc690.png)

As seen in the screenshots the Notification is displaying `"You will arrive"` when it should be `"You have arrived"`.

**Comment by nesfeder** [comment]
It looks like the `MapboxNavigationNotification` only ever retrieves the first banner instruction from the current `LegStep` > https://github.com/mapbox/mapbox-navigation-android/blob/master/libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/MapboxNavigationNotification.java#L231
