### ISSUE TITLE
0.6.0-Snapshot not uploaded - Don't update README before build

### ISSUE THREAD

**Issue by davols** [mapbox/mapbox-navigation-android#196]
Related to #193 and similar issue that happened to 0.5.0-SNAPSHOT.

The readme is updated now to 0.6.0-SNAPSHOT but it's not uploaded to sonatype. Maybe tweak the release process? Not the biggest issue but at least I got really excited to see a notification with 0.6.0 mentioned and sad when it wasn't uploaded.

cc @langsmith 
Similar to #168

**Comment by cammace** [comment]
Sorry for the confusion, you can always check the snapshot versions on [Sonatype](https://oss.sonatype.org/content/repositories/snapshots/com/mapbox/mapboxsdk/mapbox-android-navigation/). 0.6.0-snapshot is released now.

**Comment by davols** [comment]
@cammace checked the sonatype every day. the issue is that the readme mentions a newer snapshot (it's updated) several days before the actual snapshot is released. Imo it (change readme task) should be done later. So that the readme is updated with sonatype builds. 

(Not sure if it's related to #168 but looks like it)
