### ISSUE TITLE
Potential crash on context#registerReceiver

### ISSUE THREAD

**Issue by andrlee** [mapbox/mapbox-navigation-android#1960]
**Android API:** Android-9
**Mapbox Navigation SDK version:** all where battery level info is accessed

### Steps to trigger behavior
Crash from prod caught by telem team: https://github.com/mapbox/mapbox-events-android/issues/406

### Expected behavior
Should try and catch:
https://github.com/mapbox/mapbox-navigation-android/blob/892a2bfbbb66a65df852000e0d97fcc9e5a24e82/libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/BatteryMonitor.java#L50

### Actual behavior
Unhandled exception will cause a fatal error

**Comment by andrlee** [comment]
solution: https://github.com/mapbox/mapbox-events-android/pull/407

**Comment by Guardiola31337** [comment]
Hey @andrlee thanks for flagging!

Wondering if this is related to the restrictions introduced by Android Pie 9: Some APIs return `SecurityException` if at the moment of calling them the user has location disabled :eyes: https://github.com/mapbox/mapbox-navigation-android/issues/1949

**Comment by Guardiola31337** [comment]
Could this still be an issue in `1.0` @mapbox/navigation-android?

**Comment by RingerJK** [comment]
@Guardiola31337 yes, this is https://github.com/mapbox/mapbox-navigation-android/blob/94c36cdd80514e49fb2d0e293f1e1ef0a182d175/libnavigation-ui/src/main/java/com/mapbox/navigation/ui/map/MapBatteryMonitor.java#L27-L28

**Comment by Guardiola31337** [comment]
@RingerJK any ideas on how to workaround it?

**Comment by RingerJK** [comment]
I didn't catch this kind of exceptions through testing. [Here](https://github.com/mapbox/mapbox-events-android/pull/407/files#diff-b7b67ee516bb62e7449dbb236b8fb77bR235) mentioned that these kind of exceptions appear at Android 4.2 and lower, but we support 4.4+. I think we should be good to close it
