### ISSUE TITLE
Symbols not showing on Mapview when "Mapbox.setConnected(false);"

### ISSUE THREAD

**Issue by virtuoso80** [mapbox/mapbox-navigation-android#1966]
**Android API:** 24
**Mapbox Navigation SDK version:** 7.3.2

### Steps to trigger behavior

 1. Call "Mapbox.setConnected(false);"

### Expected behavior
Stop downloading map tiles and use only cached or offline map tiles.

### Actual behavior
Stops downloading map tiles and uses cached ones.
Also stops showing any Symbols (Icons and text) added  with a SymbolManager. 
If Mapbox.setConnected(true) is called, symbols start showing.

**Comment by tobrun** [comment]
you need to explicitly configure a textfont that is found in your cached or offline tiles to load them. See similar issue in https://github.com/mapbox/mapbox-plugins-android/issues/970.

**Comment by virtuoso80** [comment]
Followed the instructions and problem fixed.

Thanks a lot. Was searching for 3 weeks for a solution

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by virtuoso80** [comment]
Followed instructions and problem fixed. Thanks a lot
