### ISSUE TITLE
How to enable voice announcement button in navigation. I'm unable to find any solution Please help me to get it out.

### ISSUE THREAD

**Issue by AnuragKataria** [mapbox/mapbox-navigation-android#197]
@Override
  public void onMilestoneEvent(RouteProgress routeProgress, String instruction, int identifier) {
    Timber.d("Milestone Event Occurred with id: %d", identifier);

    Log.i("Instruction : " , instruction);
    switch (identifier) {

      case NavigationConstants.URGENT_MILESTONE:

        Toast.makeText(this, "Urgent Milestone", Toast.LENGTH_LONG).show();
        break;
      case NavigationConstants.IMMINENT_MILESTONE:
        Toast.makeText(this, "Imminent Milestone", Toast.LENGTH_LONG).show();
        break;
      case NavigationConstants.NEW_STEP_MILESTONE:
        Toast.makeText(this, "New Step", Toast.LENGTH_LONG).show();
        break;
      case NavigationConstants.DEPARTURE_MILESTONE:
        Toast.makeText(this, "Depart", Toast.LENGTH_LONG).show();
        break;
      case NavigationConstants.ARRIVAL_MILESTONE:
        Toast.makeText(this, "Arrival", Toast.LENGTH_LONG).show();
        break;
      case BEGIN_ROUTE_MILESTONE:
        Toast.makeText(this, "you should reach your destination by", Toast.LENGTH_LONG).show();
        break;
      default:
        Toast.makeText(this, "Undefined milestone event occurred", Toast.LENGTH_LONG).show();
        break;
    }
  }

I'm getting the Instructions but it does not speak that instruction.

**Comment by davols** [comment]
Afaik @AnuragKataria you need to implement this yourself. The navigation sdk is still in progress. And right now, at least in snapshot, the code handles all the under the hood stuff. (Not inputs, gui or voice outputs). You would need to implement that yourself. 

You would need to look at #180 and possibly others if you want the drop in feature.

**Comment by cammace** [comment]
Drop in UI is currently being worked on by @danesfeder in #180 and will be released in the comming weeks. This will add voice announcements as @davols mentions above. Closing.
