### ISSUE TITLE
Release v0.40.0

### ISSUE THREAD

**Issue by abhishek1508** [mapbox/mapbox-navigation-android#1972]
### Release checklist @abhishek1508 

- [x] Run through testapp/demo app and test all activities
- [x] Change version name to `0.40.0` in `gradle.properties`
- [x] Publish `0.40.0` artifact to Maven Central
- [x] Change version name back to `0.41.0-SNAPSHOT`
- [x] Update `README.md`
- [x] Tag `v0.40.0` in GitHub

### Post-release @langsmith   

- [x] Update `constants.js` file in `android-docs` repo 👀 https://github.com/mapbox/android-docs#updating-for-sdk-releases
- [x] Generate `navigation` and `navigation-ui` javadocs and add to `android-docs` repo
- [x] Update nav dependency used by android-tutorial-demo app.
- [x] Update config files in /help repo _after_ tutorial (☝️) update is finished.
  - @colleenmcginnis @HeyStenson we are good to go for this release 👍 

### Changelog:

- Fix notification instruction not updated for arrive maneuver #1959

- Bump mapbox-navigation-native version to 6.2.1 #1955

**Comment by langsmith** [comment]
Done on my end @abhishek1508
