### ISSUE TITLE
Compass to toggle north up vs heading up

### ISSUE THREAD

**Issue by andrlee** [mapbox/mapbox-navigation-android#1977]
The map should show a compass indicating the current direction of travel or current heading (if the user is at rest). For example, if the user is facing south when starting a route, they should see “S” on the map so they know to turn around when the departure step says “Head north”.

This compass could have the same size as the map SDK’s built-in compass view, but it would serve a different purpose. The map SDK’s compass primarily indicates that the map is rotated and offers a way to rotate it back to north. By contrast, this proposal is for a view that bears nothing but a single letter.

There are precedents for this kind of display, both in Apple Maps and even built into rear-view mirrors in some car models. In Google Maps, a similar view serves as a toggle for overview mode. So it may be possible to implement this feature without sacrificing any additional screen real estate.

Link to the iOS feature request as well as design comps: https://github.com/mapbox/mapbox-navigation-ios/issues/1217

/cc @mapbox/navigation-android

**Comment by Guardiola31337** [comment]
What does OP differ from https://github.com/mapbox/mapbox-navigation-android/issues/1218 @andrlee? I believe they're tracking the same work / effort and one of them should be closed as duplicated.

**Comment by andrlee** [comment]
@Guardiola31337 feel free to close one of them, i find that the description of the ticket in iOS repo is much more complete. i just wanted to make sure we prioritize this work as we'd need this feature in the next couple of weeks.

**Comment by Guardiola31337** [comment]
@andrlee closed #1218 in favor of this one.

**Comment by Guardiola31337** [comment]
@abhishek1508 it'd be 💯 if we can add support for this in the `1.0` UI SDK.

**Comment by Guardiola31337** [comment]
@asinghal22 is this something we want to support in `1.0`?

**Comment by LukasPaczos** [comment]
Closing as stale.
