### ISSUE TITLE
Upgrade to AndroidX

### ISSUE THREAD

**Issue by msh91** [mapbox/mapbox-navigation-android#1981]
Hi, 
Can we use NavigationSDK alongside with AndroidX new APIs? or do you have any plan to migrate `navigation-ui` module to AndroidX?

**Comment by Guardiola31337** [comment]
Hey @msh91 :wave: thanks for reaching out and report your question.

We're tracking that effort in https://github.com/mapbox/mapbox-navigation-android/issues/1702

As you may know `navigation-android-ui` includes the Maps SDK and AndroidX is not still supported :eyes: https://github.com/mapbox/mapbox-gl-native/issues/11887

In any case, it seems we can leverage in jetifier https://github.com/mapbox/mapbox-gl-native/issues/11887#issuecomment-438225442 so we're exploring that option in the Navigation SDK. We'll report back in #1702 

Thanks again!

Closing as duplicated.

**Comment by msh91** [comment]
Thanks for the response

**Comment by Guardiola31337** [comment]
@msh91 of course! Thanks for checking out the SDK!
