### ISSUE TITLE
SpeechPlayer does not save state, and does not work with SpeechAnnouncementListener

### ISSUE THREAD

**Issue by kiskunk** [mapbox/mapbox-navigation-android#1989]
Since there is no convenient/proper way to change navigationView to night mode and back, an Activity recreate needs to be called. And since there is no convenient way to tell if the speechAnnouncement is muted or not, I have to define a speechPlayer and lsiten to the mute/unmute changes. I want to save if the speech is muted or not, so after the recreating, the muted button would be set as it was before (I am using navigationView inside a fragment). If I add speechPlayer to the navigationOptionsBuilder, there will be absolutely no voice instruction, regardless of being muted or not. If I create the speechPlayer and set it to muted, when the navigationView loads, the button is still showing Unmuted state.

    speechPlayer = new SpeechPlayer() {

                @Override
                public void play(SpeechAnnouncement speechAnnouncement) {
                    /*if (speechAnnouncementListener != null) {
                        speechAnnouncementListener.willVoice(speechAnnouncement);
                    }*/
                }

                @Override
                public boolean isMuted() {
                    return isMuted;
                }

                @Override
                public void setMuted(boolean mutedState) {
                    isMuted = mutedState;
                }

                @Override
                public void onOffRoute() {

                }

                @Override
                public void onDestroy() {

                }
            };

            //speechPlayer.setMuted(isMuted);

            navigationOptionsBuilder.speechPlayer(speechPlayer);

    speechAnnouncementListener = new SpeechAnnouncementListener() {
                @Override
                public SpeechAnnouncement willVoice(SpeechAnnouncement speechAnnouncement) {
                    if (!isMuted) {      
                            return speechAnnouncement;
                    }
                    return null;
                }
            };
     navigationOptionsBuilder.speechAnnouncementListener(speechAnnouncementListener);

**Android API:** 15-28
**Mapbox Navigation SDK version:** 0.40.0

### Steps to trigger behavior

 1. create a navigationView
 2. add speechPlayer and speechAnnouncementListener
 3. change Muted/Unmuted

### Expected behavior

The voice could be heard if its unmuted, and not heard if its muted. The button shows the correct setting after initializing.

### Actual behavior

With speechPlayer, absolutely no voice can be heard. Without speechPlayer, no way to know if the voice is muted or not. The mute/unmute button always starts unmuted, no matter of settings.

**Comment by Guardiola31337** [comment]
@JunDai could we check if this would be an issue in `1.0`?

**Comment by abhishek1508** [comment]
Let's verify.
cc @JunDai @cafesilencio @langsmith

**Comment by JunDai** [comment]
@kiskunk - the mute/unmute state and the sound icon's state will be saved and restored in our v1.0 sdk. I tested the dark mode switch on our example and it works. The example also uses a `NavigationView` in a Fragment.

Please try our [v1.0 beta release](https://docs.mapbox.com/android/beta/navigation/overview/) and feel free to open a new ticket if you still see this issue.
