### ISSUE TITLE
NavigationView Bottom Layout stays English

### ISSUE THREAD

**Issue by kiskunk** [mapbox/mapbox-navigation-android#1990]
When using navigationView, the bottom layout which shows the ETA minutes, and the remaining distance, stays in english after setting language to Hungarian. I checked it on Transifex, and its translated.

**Android API:** 15-28
**Mapbox Navigation SDK version:** 0.40.0

### Steps to trigger behavior

 1. create a navigationView
 2. set options to have Hungarian language
 3. check bottom layout

### Expected behavior

The bottom layout should show "12 perc" instead of "12 min"

### Actual behavior

The bottom layout shows "12 min" even when the language is set to Hungarian.

**Comment by Guardiola31337** [comment]
Hey @kiskunk 👋 thanks for reaching out and report your problem.

🤔 Are you sure the language is set to Hungarian? Could you share a screenshot in which English and Hungarian is mixed?

`min` Hungarian translation is available in the `values-hu` resources 👀 https://github.com/mapbox/mapbox-navigation-android/blob/713810ec28d235025d0421b610041499fc58f71a/libandroid-navigation/src/main/res/values-hu/strings.xml#L18 and we're generating the `arrivalTime` in the `SummaryModel` (used in `NavigationView` internally) https://github.com/mapbox/mapbox-navigation-android/blob/713810ec28d235025d0421b610041499fc58f71a/libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/summary/SummaryModel.java#L29 which uses the `TimeFormatter`, which retrieves the translation from `R.string.min` 👀 https://github.com/mapbox/mapbox-navigation-android/blob/713810ec28d235025d0421b610041499fc58f71a/libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/utils/time/TimeFormatter.java#L81

Could you add some more information around your test setup? That would be really helpful and it'll give us better insight into your implementation and what could be causing your problem.

**Comment by kiskunk** [comment]
NavigationRoute.Builder builder = NavigationRoute.builder(getActivity())
                    .accessToken(getString(R.string.mapbox_access_token))
                    .origin(origin)
                    .destination(destination)
                    .language(new Locale("hu"))
                    .profile(DirectionsCriteria.PROFILE_DRIVING_TRAFFIC)
                    .voiceUnits(DirectionsCriteria.METRIC)
                    .alternatives(true);

The SpeechAnnouncement voice talks in Hungarian (I cannot create a screenshot about it sorry), and the notification is in Hungarian too, so I assume the navigation module is correctly set to Hungarian. I am using the navigationView inside a fragment.

[Navigation](https://i.ibb.co/FHppX9j/Annotation-2019-07-18-152158.png)
[Notification](https://i.ibb.co/JBYhjtx/Annotation-2019-07-18-152855.png)

**Comment by Guardiola31337** [comment]
`NavigationView` includes `SummaryBottomSheet` which uses the device's locale, you don't need to set anything explicitly for this component. So as soon as you have the language of your device set to Hungarian should work. I've just tested locally and it's working as expected 👀 

![hungarian_min_perc](https://user-images.githubusercontent.com/1668582/61463061-f77cdf80-a973-11e9-8e58-b96bc2f8c165.jpeg)

It displays `perc` instead of `min`.

My guess is that you have the language set to English because as you can see 

![english_bottom_sheet](https://user-images.githubusercontent.com/1668582/61463570-f8624100-a974-11e9-9fa8-545992d84d77.png)

the rest of the translations are also in English (`hr` instead of `óra` for example).

Could you confirm that the language of the device is also Hungarian?

**Comment by kiskunk** [comment]
In our app, users can change the language regardless of the device's language. If the other parts of the SDK use the requested language from the `NavigationRoute.Builder`, the `SummaryBottomSheet` should be able to inherit those settings too, thus making the app not relying on the OS settings.

**Comment by cmahopper** [comment]
Just dropping in to say that I agree with @kiskunk, the text should match what is set in the `NavigationRoute.Builder` and ignore the device language. We have this problem too.

**Comment by kiskunk** [comment]
How can I explicitly change the text of those fields? For example if I would like to show 113 mins instead of 1h 53m? or using 05:14pm. With what name I can access them? Thanks.

**Comment by cmahopper** [comment]
To add to this issue, the "End navigation" string in the navigation notification is also not translated, and only uses the phone's language settings.

**Comment by kiskunk** [comment]
> `NavigationView` includes `SummaryBottomSheet` which uses the device's locale, you don't need to set anything explicitly for this component. So as soon as you have the language of your device set to Hungarian should work. I've just tested locally and it's working as expected 👀
> 
> ![hungarian_min_perc](https://user-images.githubusercontent.com/1668582/61463061-f77cdf80-a973-11e9-8e58-b96bc2f8c165.jpeg)
> 
> It displays `perc` instead of `min`.
> 
> My guess is that you have the language set to English because as you can see
> 
> ![english_bottom_sheet](https://user-images.githubusercontent.com/1668582/61463570-f8624100-a974-11e9-9fa8-545992d84d77.png)
> 
> the rest of the translations are also in English (`hr` instead of `óra` for example).
> 
> Could you confirm that the language of the device is also Hungarian?

Can you provide a way to access those textviews and update them at runtime? Thanks.
