### ISSUE TITLE
MapboxNavigationActivity camera not hooked automatically Maps 8.1.0

### ISSUE THREAD

**Issue by Guardiola31337** [mapbox/mapbox-navigation-android#1992]
When integrating https://github.com/mapbox/mapbox-navigation-android/pull/1890 and testing the test app `NavigationLauncherActivity` (`MapboxNavigationActivity`) using Maps SDK `v8.1.0` we've noticed that the camera is not hooked (tracking) automatically anymore 👀

![mapbox_navigation_activity_camera_not_hooked_8_1_0](https://user-images.githubusercontent.com/1668582/60824868-73a74400-a178-11e9-8e6a-854bfe3e72f4.gif)

This is the upstream PR causing the regression on our side https://github.com/mapbox/mapbox-gl-native/pull/14745

We're probably scheduling a `MapboxMap` animation _after_ setting the tracking mode. We can start debugging by placing a breakpoint here https://github.com/mapbox/mapbox-gl-native/blob/4c896cbb31fcb929b0e57c7bd02e519c267a1be1/platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/location/LocationComponent.java#L1561
this should give us a good idea about where do those updates come from.

cc @andrlee

**Comment by DejanRistic** [comment]
@Guardiola31337 I'm actually still noticing the issue on 0.41.0 and 8.1.0, but manually invoking `callOnClick()` on the recenter button after start navigation seems be a good workaround for me. It could be a result of something else we're doing that's causing it to still be an issue. Just wanted to toss it out in case others still have issues with it.
