### ISSUE TITLE
Cannot create custom voice with SpeechAnnouncement

### ISSUE THREAD

**Issue by kiskunk** [mapbox/mapbox-navigation-android#1994]
I need to inform the users when they go **offroute** by voiceInstuction saying "Recalculating".

Im using navigationView in a fragment, and when the offroute detection fires, Im trying to generate a custom voice instruction. I could not find any documentation on how to generate it correctly, I also looked at custom Milestones, but there is no trigger option for offRoute.

    //.................
    NavigationViewOptions.Builder navigationOptionsBuilder = NavigationViewOptions.builder()
                    .navigationListener(this)
                    .directionsRoute(selectedRoute)
                    .shouldSimulateRoute(isSimulate)
                    .routeListener(new RouteListener() {
                        @Override
                        public boolean allowRerouteFrom(Point offRoutePoint) {
                            return true;
                        }

                        @Override
                        public void onOffRoute(Point offRoutePoint) {
                        
                                willVoice(SpeechAnnouncement.builder().announcement("Recalculating").ssmlAnnouncement("<speak>Recalculating</speak>").build());
                            
                        }

                        @Override
                        public void onRerouteAlong(DirectionsRoute directionsRoute) {

                        }

                        @Override
                        public void onFailedReroute(String errorMessage) {

                        }

                        @Override
                        public void onArrival() {

                        }
                    })
                    .progressChangeListener(this)
                    .instructionListListener(this)
                    .speechAnnouncementListener(this)
                    .bannerInstructionsListener(this);
    //..........

    @Override
    public SpeechAnnouncement willVoice(SpeechAnnouncement speechAnnouncement) {
            return speechAnnouncement;   
    }

**Android API:** 16-28
**Mapbox Navigation SDK version:** 0.40.0

### Steps to trigger behavior

 1. create navigationView
 2. add offroute detection
 3. call willVoice with custom instruction

### Expected behavior

The device plays the custom audio.

### Actual behavior

No audio can be heard.

**Comment by andrlee** [comment]
Entire tts overhaul is expected in 1.0

**Comment by Guardiola31337** [comment]
@JunDai could we check if this would be an issue in `1.0`?

**Comment by abhishek1508** [comment]
Let's verify.
cc @JunDai @cafesilencio @langsmith

**Comment by JunDai** [comment]
@kiskunk - It will still be an issue in our v1.0 release. But you can provide your own `SpeechPlayer` implementation so it can play the speech you want when you override the `onOffRoute()`

I see that you already have provided your own `SpeechPlayer` in #1989 , you can try it and let's know if it matches your requirement.

**Comment by Guardiola31337** [comment]
Is this the same as https://github.com/mapbox/mapbox-navigation-android/issues/3299? Could you confirm @JunDai?

**Comment by JunDai** [comment]
> Is this the same as #3299? Could you confirm @JunDai?

no, I don't think they are relevant.

**Comment by JunDai** [comment]
> @kiskunk - It will still be an issue in our v1.0 release. But you can provide your own `SpeechPlayer` implementation so it can play the speech you want when you override the `onOffRoute()`
> 
> I see that you already have provided your own `SpeechPlayer` in #1989 , you can try it and let's know if it matches your requirement.

@kiskunk - hi 👋  it would be great if you get any chance to give it a try and let's know if still any issues.

**Comment by JunDai** [comment]
@kiskunk - I am closing this ticket for now. You could try my above suggestion about providing your own `SpeechPlayer` implementation for the `onOffRoute()` event.

If you still have issue about this, feel free to open a new ticket with latest info. Thanks!
