### ISSUE TITLE
Release v0.41.0

### ISSUE THREAD

**Issue by abhishek1508** [mapbox/mapbox-navigation-android#1996]
## Release checklist 
 - [x] Run through testapp/demo app and test all activities
 - [x] Change version name to 0.41.0 in gradle.properties
 - [x] Publish 0.41.0 artifact to Maven Central
 - [x] Change version name back to 0.42.0-SNAPSHOT
 - [x] Update README.md
 - [x] Tag v0.41.0 in GitHub

## Post-release 
 - [x] Update `constants.js` file in `/android-docs` repo -> https://github.com/mapbox/android-docs#updating-for-sdk-releases
 - [x] Generate navigation and navigation-ui javadocs and add to `/android-docs` repo
 - [x] Update version # in /help repo's `constants.json` file
@colleenmcginnis @HeyStenson we are good to go for this release 👍

## Changelog:

- Move events from telemetry to nav sdk [#1890](https://github.com/mapbox/mapbox-navigation-android/pull/1890)
- Fix DynamicCamera#CameraPosition.zoom NPE [#1979](https://github.com/mapbox/mapbox-navigation-android/pull/1979)
- Update ComponentNavigationActivity example [#1978](https://github.com/mapbox/mapbox-navigation-android/pull/1978)
- Fix navigation camera tracking the puck [#1995](https://github.com/mapbox/mapbox-navigation-android/pull/1995)

**Comment by langsmith** [comment]
> Update nav dependency used by android-tutorial-demo app. 

I've removed this checklist item because this internal app has been deprecated cc @colleenmcginnis

**Comment by langsmith** [comment]
Done here! 👏 🎬 💯
