### ISSUE TITLE
Improve the monitoring of step progress

### ISSUE THREAD

**Issue by cammace** [mapbox/mapbox-navigation-android#20]
Breakup [monitorStepProgress](https://github.com/mapbox/mapbox-navigation-android/blob/master/navigation/libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/LocationUpdatedThread.java#L137) method into smaller, more testable, methods and easier readability. Currently it is a direct port from the Swift [function found here](https://github.com/mapbox/mapbox-navigation-ios/blob/master/MapboxCoreNavigation/RouteController.swift#L168). Tagging @bsudekum and @1ec5 since this could potentially break parity with the iOS SDK.

cc: @zugaldia @danesfeder

**Comment by 1ec5** [comment]
Sounds great. It’s a sprawling method that should be refactored on the Swift side too.

**Comment by cammace** [comment]
I've been looking over best solutions for splitting up the monitorStepProgress, here are the steps I'm thinking of taking to refactor it.
- [ ] Move logic into it's own class and get rid of `LocationUpdateThread` (see https://github.com/mapbox/mapbox-navigation-android/issues/19).
- [ ] Have routeProgress handle more logic, currently in `monitorStepProgress()` we are doing conversions and calculations that seem fit for handling inside the routeProgress model instead such as calculating the users location `truePosition`, `secondsToEndOfStep`, etc. This would require building a new routeProgress object before determining what alert level the users on and invoking the callbacks appropriately. 
- [ ] Each alert level check moved into separate methods. This can help remove unnecessary checks such as whether the user just departed or not, which only needs to be called once. This also makes testing of each method significantly easier.

**Comment by cammace** [comment]
Refactoring of this took place in https://github.com/mapbox/mapbox-navigation-android/pull/30. Closing.

**Comment by jom0000** [comment]
~~~~

**Comment by jom0000** [comment]
implementation 'com.mapbox.mapboxsdk:mapbox-android-sdk:6.8.1'
