### ISSUE TITLE
Mapbox localization

### ISSUE THREAD

**Issue by toblinkz** [mapbox/mapbox-navigation-android#2000]
Can u please pull in the yoruba language i translated in transifex

**Comment by Guardiola31337** [comment]
@toblinkz Thanks for contributing these Yoruba translations 🙇 

I'll tag you in the PR that updates them and they'll be available in the SDK in the next release.

Thanks again!

**Comment by toblinkz** [comment]
please when is the next SDK release date?

**Comment by Guardiola31337** [comment]
Hey @toblinkz Ideally, it'll be due by July 24, 2019 👀 https://github.com/mapbox/mapbox-navigation-android/milestone/49 although it could be slipped a bit.

In the meantime, you can confirm that Yoruba translations show up using `0.42.0-SNAPSHOT`. Following you can find installation instructions for `SNAPSHOT`s:

```groovy
repositories {
    jcenter()
    maven { url 'https://mapbox.bintray.com/mapbox' }
    maven { url "http://oss.sonatype.org/content/repositories/snapshots/" }
    // ...
}

dependencies {
    // ...
    implementation 'com.mapbox.mapboxsdk:mapbox-android-navigation-ui:0.42.0-SNAPSHOT'
    // ...
}
```

Thanks a lot!

**Comment by toblinkz** [comment]
Thank you very much.... but how do I add the voice instructions for Yoruba

**Comment by 1ec5** [comment]
Hi @toblinkz, thanks again for translating everything into Yoruba – it’s much appreciated. This SDK only contains translations for UI elements, but voice instructions are downloaded from the Directions API. The Directions API is translated as part of the [OSRM Text Instructions](https://github.com/Project-OSRM/osrm-text-instructions/) project. You’ve already translated OSRMTI in Transifex, so the next step is to add those translations to the OSRMTI repository: Project-OSRM/osrm-text-instructions#284. Please have a look at that PR and make any adjustments in Transifex. Once that PR is merged, we can do a release and deployment with the new translations.

Note that the Mapbox Voice API doesn’t support Yoruba speech synthesis, so a user will only hear Yoruba pronunciations if their phone has Yoruba text-to-speech built in or if you add a third-party TTS engine to your application.

**Comment by Guardiola31337** [comment]
@toblinkz 
> but how do I add the voice instructions for Yoruba

https://github.com/Project-OSRM/osrm-text-instructions/pull/284#issuecomment-514356346
> If you need a corresponding hook for Android, I’d suggest following up in the mapbox-navigation-android repository.

For Android, you'd need to create a custom speech player implementing the [`SpeechPlayer`](https://github.com/mapbox/mapbox-navigation-android/blob/master/libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/voice/SpeechPlayer.java) interface and then set it via `NavigationViewOptions` https://github.com/mapbox/mapbox-navigation-android/blob/03b45cf9e5c00738d1245219e97411a167ae3106/libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/NavigationViewOptions.java#L99 and in which `play` would invoke the third-party TTS engine.

We found this http://ttsyoruba.com/ which in the FAQ says that there is an API available which you can ask for access.

> I am building a tech product and I’ll like to use your Text-to-speech API so my product can "speak" Yorùbá to our customers. How do I do that?
>> Send us an email at project@yorubaname.com with "TTS inquiry" in the subject line. If your product is open source and not commercial, you might be able to use our work for free.

Hope this helps.

cc @1ec5

**Comment by toblinkz** [comment]
Thank you very much

**Comment by toblinkz** [comment]
How do I check to see that yoruba has been added as of the languages for
navigation in mapbox
