### ISSUE TITLE
Building layer is hiding location component

### ISSUE THREAD

**Issue by Christophe668** [mapbox/mapbox-navigation-android#2006]
When activating the BuildingPlugin on Mapbox Navigation 41, buildings are hiding the location component despite the opacity set the to building layer.
Tried to set BuildingPlugin constructor parameter "layerBelow" to LocationComponentConstants.SHADOW_LAYER for instance without success

**Android API:**
Android 9

**Mapbox Navigation SDK version:**
41

### Steps to trigger behavior

 1. Update library from 39 to 41
 2. Activate BuidlingPlugin

```	
val buildingPlugin = BuildingPlugin(config.mapView, mapbox, style)
buildingPlugin.setOpacity(0.3f)
```

### Expected behavior
<img width="371" alt="Screenshot 2019-07-22 at 17 18 05" src="https://user-images.githubusercontent.com/1552554/61644313-c0c10500-aca4-11e9-937d-36f10c602224.png">

### Actual behavior
<img width="299" alt="Screenshot 2019-07-22 at 17 18 12" src="https://user-images.githubusercontent.com/1552554/61644301-be5eab00-aca4-11e9-9ec8-55fecc5d5691.png">

**Comment by LukasPaczos** [comment]
Hey @Christophe668, thanks for reporting the bug. This has been resolved upstream in https://github.com/mapbox/mapbox-gl-native/pull/15065 and is most likely going to be a part of the next Nav SDK release, or alternatively upcoming Maps SDK `8.2.0` and patch releases that are going to backport the fix soon as well.
