### ISSUE TITLE
Cannot use combined with mapbox annotation 0.7

### ISSUE THREAD

**Issue by william-reed** [mapbox/mapbox-navigation-android#2008]
**Mapbox Navigation SDK version:**

### Steps to trigger behavior

1. Use the latest version of this library 
```
implementation "com.mapbox.mapboxsdk:mapbox-android-navigation-ui:0.41.0
```
 2. Attempt to upgrade the following
```
implementation "com.mapbox.mapboxsdk:mapbox-android-sdk:8.2.0"
implementation "com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v8:0.7.0"
```

### Expected behavior
Everyone is happy

### Actual behavior
```
Duplicate class com.mapbox.mapboxsdk.plugins.annotation.Annotation found in modules classes.jar (com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v7:0.6.0) and classes.jar (com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v8:0.7.0)
Duplicate class com.mapbox.mapboxsdk.plugins.annotation.AnnotationManager found in modules classes.jar (com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v7:0.6.0) and classes.jar (com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v8:0.7.0)
Duplicate class com.mapbox.mapboxsdk.plugins.annotation.AnnotationManager$1 found in modules classes.jar (com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v7:0.6.0) and classes.jar (com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v8:0.7.0)
Duplicate class com.mapbox.mapboxsdk.plugins.annotation.AnnotationManager$MapClickResolver found in modules classes.jar (com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v7:0.6.0) and classes.jar (com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v8:0.7.0)
...
```

Seems like this library needs to upgrade its version of the annotation plugin

**Comment by elFallino** [comment]
I have the same problem.

**Not-Working**
```
    implementation 'com.mapbox.mapboxsdk:mapbox-android-sdk:8.2.0'
    implementation('com.mapbox.mapboxsdk:mapbox-android-navigation-ui:0.41.0') { transitive = true }
    implementation 'com.mapbox.mapboxsdk:mapbox-android-plugin-places-v8:0.9.0'
    implementation 'com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v7:0.6.0'
    implementation 'com.mapbox.mapboxsdk:mapbox-android-plugin-localization-v8:0.10.0'
```

**Working**
Revert plugin-annotation version to 
`    implementation 'com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v7:0.6.0'`

**Comment by elFallino** [comment]
Still does not work for me.
My current gradle imports:
`dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'androidx.appcompat:appcompat:1.0.2'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.2.0'

    implementation 'com.mapbox.mapboxsdk:mapbox-android-sdk:8.2.1'
    implementation 'com.mapbox.mapboxsdk:mapbox-android-navigation-ui:0.41.0'
    implementation 'com.mapbox.mapboxsdk:mapbox-android-plugin-places-v8:0.9.0'
    implementation 'com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v8:0.7.0'
    implementation 'com.mapbox.mapboxsdk:mapbox-android-plugin-localization-v8:0.10.0'
    implementation 'com.google.android.gms:play-services-location:17.0.0'
    implementation 'androidx.exifinterface:exifinterface:1.0.0'
    implementation 'com.startapp:inapp-sdk:4.0.2'
    implementation 'com.google.android.gms:play-services-maps:17.0.0'
    implementation "com.google.android.material:material:1.0.0"
    implementation 'androidx.recyclerview:recyclerview:1.0.0'
}`

Still getting that _Duplicate class_ error.
