### ISSUE TITLE
Request: Avoid playing overlapping text-to-speech

### ISSUE THREAD

**Issue by cmahopper** [mapbox/mapbox-navigation-android#2009]
**Mapbox Navigation SDK version:** 0.41.0

Would it be possible to create a queue system so that the navigation speeches are not playing on top of each other? It doesn't happen often, but when it happens it is almost impossible to hear what is being said. I'd suggest either having a queue system, or letting the new speech replace the old one, depending on what you believe is the best user experience.

**Comment by Guardiola31337** [comment]
Hey @cmahopper 👋 thanks a lot for the feedback. You're correct here > `navigation speeches are not playing on top of each other? It doesn't happen often, but when it happens it is almost impossible to hear what is being said`. Yeah, this UX isn't ideal.

To achieve this, we will need to re-work how to properly coordinate the transition between the speech engines. But yeah, it's definitely feasible. We will discuss internally the different options and prioritize a solution for this and then report back here on this ticket. Thanks again!

**Comment by andrlee** [comment]
Entire tts feature rework is expected in 1.0

**Comment by cmahopper** [comment]
@Guardiola31337 @andrlee Good to hear, thanks!

**Comment by cmahopper** [comment]
@Guardiola31337 @andrlee As a request for when you discuss the speaks-queue feature: Would it be possible to add our own sounds to this queue?

We have our own warnings we'd like to play while the user is driving. But again, this can be annoying when directions are playing simultaneously. These are not text-to-speech strings, but sound files.

**Comment by Guardiola31337** [comment]
@asinghal22 is this something that we want to support in `1.0`?

cc @abhishek1508 @JunDai

**Comment by abhishek1508** [comment]
@JunDai would you say this is taken care with this [PR](https://github.com/mapbox/mapbox-navigation-android/pull/3297)
cc @Guardiola31337

**Comment by JunDai** [comment]
I believe this is the same issue as #3216 and should be fixed by #3297

**Comment by JunDai** [comment]
Close this since we are tracking it here: #3216 

@cmahopper : feel free to add more details if you feel it's a different issue than #3216
