### ISSUE TITLE
Rerouting using same Profile and Excluding FreeWay in NavigationLauncher.startNavigation()

### ISSUE THREAD

**Issue by vishalkharat** [mapbox/mapbox-navigation-android#2023]
Hello Team,

We are using NavigationLauncher.startNagvigation() to start the navigation. For this we are providing DirectionRoute.
However after starting the navigation, map reroutes to different path.

We generate the NavigationRoutes for our two wheeler vehicle using

     NavigationRoute scooterNavigationRoute = NavigationRoute.builder()
                .accessToken(Mapbox.getAccessToken())
                .origin(origin)
                .profile(DirectionsCriteria.PROFILE_DRIVING)
                .destination(destination)
                .alternatives(true)
                .exclude(EXCLUDE_MOTORWAY)
                .build();

We display route to the user and provides that route for the navigation using below code snippet.
After staring the NavigationLauncher it starts with the correct route that we have provided. 

However after sometime it reroute to the fastest or nearest route. Which takes our two wheeler to the FREEWAY. Is there any way of supporting rerouting using EXCLUDE_MOTORWAY and initial options NavigationLauncher.

         MapboxNavigationOptions mapboxNavigationOptions = MapboxNavigationOptions.builder()
        .enableOffRouteDetection(false)
        .build();        

        NavigationViewOptions options = NavigationViewOptions.builder()
                .origin(origin)
                .navigationOptions(mapboxNavigationOptions)
                .destination(destination)
                .awsPoolId(null)
                .directionsRoute(directionsRoute)
                .shouldSimulateRoute(false)
                .build();

        NavigationLauncher.startNavigation(this, options);

**Android API:**
**
com.mapbox.mapboxsdk:mapbox-android-sdk:8.2.1
com.mapbox.mapboxsdk:mapbox-android-navigation:0.24.0
**

### Expected behavior
Navigation should reroute using profile with which it has been started.
### Actual behavior
Navigation is rerouting using default profile. e.g. If we pass excluding MOTORWAY, it takes user to the expressway.

**Comment by andrlee** [comment]
`NavigationLauncher` will be deprecated in 1.0.

**Comment by Guardiola31337** [comment]
Refs. https://github.com/mapbox/mapbox-navigation-android/issues/3034

**Comment by abhishek1508** [comment]
We are not going to fix this as `NavigationLauncher` is being deprecated in `1.0`
