### ISSUE TITLE
Missing SpeechAnnouncement when user goes off-route/rerouting occurs

### ISSUE THREAD

**Issue by kiskunk** [mapbox/mapbox-navigation-android#2025]
When the user goes off-route, there is no speechAnnouncement for that (all other navigation apps I worked with had this feature, to warn the user verbally, when a rerouting is needed). Currently there is no method to detect if a rerouting appears, other than devining a routeListener, and using a custom written TTS to warn the users verbally when the onOffRoute fires.

**Android API:** 16-28
**Mapbox Navigation SDK version:** 0.40.0

### Steps to trigger behavior

 1. create a navigationView with SpeechAnnouncementListener
 2. start a route
 3. go off-route

### Expected behavior

The speechAnnouncementListener says "Rerouting" or something similar, when a rerouting process occurs.

### Actual behavior

No audio is transmitted about this event.

**Comment by Guardiola31337** [comment]
Hey @kiskunk 👋 thanks a lot for the feedback. You're correct here > `other than devining a routeListener, and using a custom written TTS to warn the users verbally when the onOffRoute fires`. 

To achieve this, we will need to re-work how to connect / link off route events with the speech engine. But I think it's technically feasible. We will prioritize internally and discuss a solution for this and then report back here on this ticket. Thanks again!

**Comment by Guardiola31337** [comment]
@asinghal22 Is this something we want to support in `1.0`?

cc @JunDai @abhishek1508

**Comment by Guardiola31337** [comment]
Friendly ping @asinghal22 

If we're not going to support this for now, feel free to close here.

cc @abhishek1508

**Comment by carstenhag** [comment]
Oh, I think this might be interesting/useful for us as well. Currently we would only show some UI stuff, but it would be helpful to have voice instructions for it (and the other events like faster route etc).
