### ISSUE TITLE
Change release process from Nexus to Bintray

### ISSUE THREAD

**Issue by abhishek1508** [mapbox/mapbox-navigation-android#2028]
Currently Navigation-Android uses Nexus repository to release its SDK.
This issue will use Bintray to maintain the release builds.

**Comment by Guardiola31337** [comment]
For `1.0` this was addressed in https://github.com/mapbox/mapbox-navigation-android/pull/2325 Are we missing any follow up work? Are we good to close here? @abhishek1508 @LukasPaczos

**Comment by LukasPaczos** [comment]
I'm okay with closing this :+1:

**Comment by Guardiola31337** [comment]
Closing here.

cc @abhishek1508
