### ISSUE TITLE
Mute/Unmute NavigationView Sound(Annoucement) Programmatically

### ISSUE THREAD

**Issue by chiragraval23** [mapbox/mapbox-navigation-android#2031]
I am using NavigationView in my fragment and it's works perfectly fine, but in my project there is one requirement without press Mute/Unmute button I want to programatically mute/unmute the sound of navigation view.

Is it possible? If yes, then how can i achieve that functionality?

Can you please guide me on this direction?

**Comment by Guardiola31337** [comment]
Hey @chiragraval23 👋 thanks for reaching out and report your question.

We're tracking that effort in #1965 and https://github.com/mapbox/mapbox-navigation-android/pull/1970

Closing here as duplicated.
