### ISSUE TITLE
Update Danish translations from Transifex

### ISSUE THREAD

**Issue by cmahopper** [mapbox/mapbox-navigation-android#2033]
I've updated a few Danish translations from Transifex.
Can you create a pull request for them?

**Comment by Guardiola31337** [comment]
Hey @cmahopper 👋 

Thanks for contributing these Danish translations 🙇

I'll tag you in the PR that updates them and they'll be available in the SDK in the next release.

Thanks again!

**Comment by Guardiola31337** [comment]
We pulled latest translations from Transifex as part of `v0.42.0` release and updated Danish translations are available https://github.com/mapbox/mapbox-navigation-android/pull/2059/files#diff-e71b0ad30ef376bba85aee0b4d09ec86 https://github.com/mapbox/mapbox-navigation-android/pull/2059/files#diff-8333d88fe0bea5c0776499f80236350b 🎉 

Thanks again @cmahopper for contributing these Danish translations 🙇

Closing as solved.
