### ISSUE TITLE
Remove the logic that hides / removes route layers when the style changes

### ISSUE THREAD

**Issue by Guardiola31337** [mapbox/mapbox-navigation-android#2039]
As seen in https://github.com/mapbox/mapbox-gl-native/pull/15513 the location puck being a runtime layer is added to the style and as a precaution to avoid the possibility of querying any layers while the style is changing, it was hidden.

The same thing happens in the Navigation SDK with the routes (are also runtime layers) and you get a blinking effect if the style is reloaded 👀 

![route_blinking_on_style_reloaded](https://user-images.githubusercontent.com/1668582/64038641-8ad63280-cb26-11e9-97fa-daf802046578.gif)

https://github.com/mapbox/mapbox-gl-native/pull/15513 prevents unnecessary layers blink when the same components are re-added after the style reload. Although, puck is not blinking anymore, the routes still do 👀 

![routes_blinking_8_4_0_SNAPSHOT](https://user-images.githubusercontent.com/1668582/64038725-cec93780-cb26-11e9-9a46-80c61d9fc098.gif)

We need to remove the logic that hides / removes route layers when the style changes, which is not necessary as it's handled upstream by the Maps SDK as part of https://github.com/mapbox/mapbox-gl-native/pull/15513

cc @LukasPaczos

**Comment by Guardiola31337** [comment]
This is unblocked now as was included in https://github.com/mapbox/mapbox-gl-native/releases/tag/android-v8.4.0-alpha.1 and Maps SDK [`v8.4.0`](https://github.com/mapbox/mapbox-gl-native/releases/tag/android-v8.4.0) was released 🎉

**Comment by AnnaStaley** [comment]
Hi @andrlee was looking to close out some tickets in the BMW Collab-repo. 
https://github.com/mapbox/bmw-collab/issues/41
Do you have a timeline for this fix? 
cc @LukasPaczos 
Thank you!

**Comment by andrlee** [comment]
this ticket can be closed as it was fixed with https://github.com/mapbox/mapbox-gl-native/pull/15513

**Comment by LukasPaczos** [comment]
https://github.com/mapbox/mapbox-gl-native/pull/15513 is only a piece of the puzzle. Per voice with @Guardiola31337 and https://github.com/mapbox/mapbox-navigation-android/issues/2039#issuecomment-535968015  the sources/layers setup will have to be also adjusted on the navigation side.
