### ISSUE TITLE
Add Folder Values-Fa

### ISSUE THREAD

**Issue by SaeedHashemi** [mapbox/mapbox-navigation-android#2049]
Please add values-fa in res folder of your project, I want to add the Persian language to it.
Thanks.

**Comment by Guardiola31337** [comment]
Hey @SaeedHashemi 👋 thanks for reaching out!

Doing so would require a custom build of the SDK. I’d recommend contributing Persian language support to the SDK itself by following [these instructions](https://github.com/mapbox/mapbox-navigation-android/blob/master/CONTRIBUTING.md#adding-or-updating-a-localization).

For extra context, we manage translations in two different Transifex projects, one for the server-side guidance instructions and the other for the client-side UI.

Our voice instructions are sourced from https://github.com/Project-OSRM/osrm-text-instructions, so if you can open an issue there, that would be great.  

Specifically, please check out https://github.com/Project-OSRM/osrm-text-instructions/blob/master/CONTRIBUTING.md - if you're able to provide the updated translations, this would speed up the process of getting Persian support.

Note that the Mapbox Voice API doesn’t support Persian speech synthesis, so a user will only hear Persian pronunciations if their phone has Persian text-to-speech built in or if you add a third-party TTS engine to your application.

cc @1ec5

**Comment by SaeedHashemi** [comment]
Hey bro @Guardiola31337 
Thanks for your help.

**Comment by Guardiola31337** [comment]
@SaeedHashemi of course! Thanks for checking out the SDK!
