### ISSUE TITLE
Unable to use OffRouteListener since it uses precision 6 to decode current step

### ISSUE THREAD

**Issue by palto-ccadoret** [mapbox/mapbox-navigation-android#206]
When using the MapboxDirections Api to retrieve a route, the route computed has a precision of 5.

Unfortunately, the OffRouteDetector uses a precision of 6 to decode the current step.
https://github.com/mapbox/mapbox-navigation-android/blob/88b313411ae825c4465e93f1b28ae9914cc22b03/navigation/libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/offroute/OffRouteDetector.java#L68

---> The off route callback is always triggered.

Is there a way to fix this ?

**Comment by cammace** [comment]
You can request precision 6 when making the directions API call using the geometry parameter. If you're on 0.5.0 I'd recommend using the `NavigationRoute` class to get the route which will handle all the required stuff for you.
