### ISSUE TITLE
NavigationRoute.getRoute timeout

### ISSUE THREAD

**Issue by P-Zenker** [mapbox/mapbox-navigation-android#2061]
**Android API:** 28
**Mapbox Navigation SDK version:** 0.41.0

### Steps to trigger behavior

In my app I've got a SocketTimeoutException if our server needs longer than 10 seconds to answer the NavigationRoute.getRoute request.

```
onFailure: Request{method=GET, url=..., tags={}} , Error: java.net.SocketTimeoutException: timeout
```

Is there a way to set the timeout for getRoute?

**Comment by Guardiola31337** [comment]
Is this something we'd like to support in `1.0` @mapbox/navigation-android?

**Comment by LukasPaczos** [comment]
I think we can rely on the default `OkHttp` timeout for now. A user can always retry when failure is reported. This will be automatically addressed when we expose the networking layer as a module in the future.

**Comment by Guardiola31337** [comment]
Refs. https://github.com/mapbox/mapbox-navigation-android/issues/3324

**Comment by P-Zenker** [comment]
Functional with com.mapbox.mapboxsdk:mapbox-sdk-services:5.7.0:
```
MapboxDirections.builder()
[...]
    .interceptor {
        it.withConnectTimeout(30, TimeUnit.SECONDS)
            .withReadTimeout(30, TimeUnit.SECONDS)
            .withWriteTimeout(30, TimeUnit.SECONDS)
            .proceed(it.request().newBuilder().build())
    }
    .build()
    .enqueueCall(callback)
```
