### ISSUE TITLE
MapView will not disappear

### ISSUE THREAD

**Issue by ciaranodc** [mapbox/mapbox-navigation-android#2062]
I have been trying to do something similar to what happens in DualNavigationMapActivity where you have a map view and then you switch to a navigation view once you click the 'start navigation' button. However the map view does not get minimised. The navigation is happening in the background but you cannot see it because it is blocked by the map view which should be gone. I noticed is the same in this app as well so it seems to be a bug.

![Screenshot_20190925-125849](https://user-images.githubusercontent.com/1556467/65599828-a2260580-df96-11e9-899d-149f0965619e.png)

**Android API: 9, Pie**
**Mapbox Navigation SDK version: Latest**

### Steps to trigger behavior

 1. Open app.
 2. Options -> View List of Navigation Examples -> Dual Navigation Map
 3. Long press point on map to generate route.
4. Click arrow button in bottom right to start navigation.

### Expected behavior

Map view should get minimized and navigation view should be displayed fully.

### Actual behavior

Map view stays and blocks the view of the navigation view map.

**Comment by Guardiola31337** [comment]
@abhishek1508 is this still an issue in `1.0`? Could you confirm?

**Comment by abhishek1508** [comment]
Let's verify this.
cc @JunDai @cafesilencio @langsmith

**Comment by abhishek1508** [comment]
We are not supporting `DualNavigationActivity` example anymore. Closing it.
