### ISSUE TITLE
InstructionView.updateDistanceWith(routeProgress) not working

### ISSUE THREAD

**Issue by kiskunk** [mapbox/mapbox-navigation-android#2064]
We are trying to customize the instructionList (mainly for translation reasons). But when I try to use 
`instructionView.updateDistanceWith(routeProgress);`
in the 
`public void onProgressChange(Location location, RouteProgress routeProgress)`
listener, the texts remain unchanged.

Since I could not figure out how to easily access the list's text, I had to use the following code (the routeProgress texts change, but the instructionList items' texts remain unchanged):

      if (instructionView != null && routeProgress != null && routeProgress.directionsRoute() != null && routeProgress.directionsRoute().legs() != null) {
            for (int i = 0; i < routeProgress.directionsRoute().legs().size(); i++) {
                if (routeProgress.directionsRoute().legs().get(i) != null && routeProgress.directionsRoute().legs().get(i).steps() != null) {
                    for (int j = 0; j < routeProgress.directionsRoute().legs().get(i).steps().size(); j++) {
                        if (routeProgress.directionsRoute().legs().get(i).steps().get(j) != null && routeProgress.directionsRoute().legs().get(i).steps().get(j).bannerInstructions() != null) {
                            for (int k = 0; k < routeProgress.directionsRoute().legs().get(i).steps().get(j).bannerInstructions().size(); k++) {
                                if (routeProgress.directionsRoute().legs().get(i).steps().get(j).bannerInstructions().get(k) != null) {
                                    BannerInstructions bannerInstructions = BannerInstructions.fromJson(TranslatorUtil.getTranslationToJSON(routeProgress.directionsRoute().legs().get(i).steps().get(j).bannerInstructions().get(k)));
                                    routeProgress.directionsRoute().legs().get(i).steps().get(j).bannerInstructions().set(k, bannerInstructions);
                                }
                            }
                        }
                    }
                }
            }
            instructionView.updateDistanceWith(routeProgress);
        }

**Android API:** 16-28
**Mapbox Navigation SDK version:** 0.40.0 - 0.42.0-SNAPSHOT

### Steps to trigger behavior

 1. create a navigationView
 2. start a navigation
 3. try to update the instructionList by calling `instructionView.updateDistanceWith()` in `onProgressChange()`

### Expected behavior

The instructionList should change based on the new text values.

### Actual behavior

The instructionList remains unchanged.

**Comment by Guardiola31337** [comment]
@abhishek1508 is this still an issue in `1.0`? Could you confirm?

**Comment by abhishek1508** [comment]
Let's verify this.
cc @JunDai @cafesilencio @langsmith

**Comment by JunDai** [comment]
> We are trying to customize the instructionList (mainly for translation reasons). But when I try to use `instructionView.updateDistanceWith(routeProgress);`

@kiskunk - thanks for reaching out to us. Please refer to the [onBindInstructionListViewAtPosition](https://github.com/mapbox/mapbox-navigation-android/blob/master/libnavigation-ui/src/main/java/com/mapbox/navigation/ui/internal/summary/InstructionListPresenter.java#L38-L43) for details about how the Navigation UI SDK builds the InstructionList view. As you can see from the code, the InstructionList item relies on the `primary text`, 'secondary text` and the `distanceAlongGeometry` of the BannerInstructions.

Back to your question, I would suggest doing below change to make it happen:
```kotlin
    private val routeProgressObserver = object : RouteProgressObserver {
        override fun onRouteProgressChanged(routeProgress: RouteProgress) {
            routeProgress.currentLegProgress?.routeLeg?.steps()?.forEach { step ->
                step.bannerInstructions()?.let {
                    it.forEachIndexed { index, bannerInstructions ->
                        val primary = bannerInstructions.primary()
                        it[index] = bannerInstructions.toBuilder().primary(primary.toBuilder().text("test primary $index").build()).build()
                    }
                }
                instructionView.updateDistanceWith(routeProgress)
            }
        }
    }
```
This way, you can see the instruction list item has been customized.
![image](https://user-images.githubusercontent.com/3918950/88422437-1f7cfb00-cd9f-11ea-8696-231e4c1e79de.png)

Closing this ticket here, feel free to create new ticket if you still have problem. Thanks!
