### ISSUE TITLE
Fix MapboxDirections builder to allow use empty arrays instead of nulls

### ISSUE THREAD

**Issue by Lebedinsky** [mapbox/mapbox-navigation-android#2077]
Fix MapboxDirections.Builder#build() method to allow setting empty arrays (`waypointNames`, `waypointIndices`, `approaches`). Now it cause of throwing exception when we try to call `build()` method. 

[Issue link](https://github.com/mapbox/mapbox-java/issues/1081) in MAS repository.

**Comment by Guardiola31337** [comment]
👀 https://github.com/mapbox/mapbox-java/issues/1081#issuecomment-591996856 @Lebedinsky @korshaknn

**Comment by Guardiola31337** [comment]
Is this still an issue @Lebedinsky @korshaknn? Are we good to close here?

**Comment by Lebedinsky** [comment]
@Guardiola31337 As far as I know, we still didn't handle this case, so we need to address it before close this ticket.

**Comment by korshaknn** [comment]
@Guardiola31337 it was refactored from `array` to `list`
```
if (approaches != null) {
        if (approaches.length != coordinates.size()) {
          throw ...
        }
        ...
      }
```
now:
```
if (!approaches.isEmpty()) {
        if (approaches.size() != coordinates.size()) {
          throw ...
        }
        ...
      }
```

the same with `waypointNames`, `waypointIndices`
we can close it

**Comment by Guardiola31337** [comment]
Thanks for confirming @korshaknn 

Closing here.

cc @Lebedinsky
