### ISSUE TITLE
Navigation UI like in iOS

### ISSUE THREAD

**Issue by LukasStancikas** [mapbox/mapbox-navigation-android#21]
Is there, and/or will there be a separate Activity with a mapview with some style, that would take 'Route' object and show built in navigation with distance,estimated time, next maneuver etc. UI. iOS has NavigationViewController (MBNavigationViewController) that can be easily presented.

**Comment by cammace** [comment]
The idea is to match up with what iOS exposes and eventually release UI elements that can easily be added inside your application. for the map items such as route lines or the user icon/puck we plan to introduce a plugin system for the maps sdk. For other views such as search widgets, instruction cards, etc. they will be located inside the Mapbox-Java `libandroid-ui` dependency.
