### ISSUE TITLE
Build a navogation app for Android crashed

### ISSUE THREAD

**Issue by Jiaminchen0** [mapbox/mapbox-navigation-android#2106]
**Android API:19
**Mapbox Navigation SDK version: com.mapbox.mapboxsdk:mapbox-android-navigation-ui:0.42.0**

### Steps to trigger behavior

After running the application, it crashed.

**Comment by Guardiola31337** [comment]
Hey @Jiaminchen0 👋 thanks for reaching out.

This issue tracker is only for bug reports with test cases and feature requests. Please direct these kind of questions to https://stackoverflow.com/questions/tagged/mapbox. We keep an eye on those questions as well and it helps bring visibility to other developers that may be facing similar issues.

Thanks again!
