### ISSUE TITLE
Version 0.4.0 works smoothly, while on MockLocationEngine(), but fails in real life scenario.

### ISSUE THREAD

**Issue by mecoFarid** [mapbox/mapbox-navigation-android#213]
I've implemented version 0.4.0 that works perfectly when MockLocationEngine() is deployed. When switched to real life, navigation fails ass seen in screenrecord hereunder.
NOTE: I haven't implemented any LocationEnige() while real life navigating, so I believe it would not rise a problem as one below:
**ERRORLOG**
```

> Fatal Exception: java.lang.IndexOutOfBoundsException: Invalid index 3, size is 3
>        at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
>        at java.util.ArrayList.get(ArrayList.java:308)
>        at com.mapbox.services.android.navigation.v5.DefaultMilestones$2.buildInstruction(DefaultMilestones.java:63)
>        at com.mapbox.services.android.navigation.v5.NavigationEngine.buildInstructionString(NavigationEngine.java:129)
>        at com.mapbox.services.android.navigation.v5.NavigationEngine.onLocationChanged(NavigationEngine.java:104)
>        at com.mapbox.services.android.navigation.v5.NavigationService.onLocationChanged(NavigationService.java:243)
>        at com.mapbox.services.android.location.LostLocationEngine.onLocationChanged(LostLocationEngine.java:145)
>        at com.mapzen.android.lost.internal.FusedLocationProviderApiImpl.reportLocation(FusedLocationProviderApiImpl.java:121)
>        at com.mapzen.android.lost.internal.FusionEngine.onLocationChanged(FusionEngine.java:134)
>        at android.location.LocationManager$ListenerTransport._handleMessage(LocationManager.java:286)
>        at android.location.LocationManager$ListenerTransport.access$000(LocationManager.java:215)
>        at android.location.LocationManager$ListenerTransport$1.handleMessage(LocationManager.java:231)
>        at android.os.Handler.dispatchMessage(Handler.java:102)
>        at android.os.Looper.loop(Looper.java:145)
>        at android.app.ActivityThread.main(ActivityThread.java:6939)
>        at java.lang.reflect.Method.invoke(Method.java)
>        at java.lang.reflect.Method.invoke(Method.java:372)
>        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
>        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)
> 
> Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.List com.mapbox.services.api.directions.v5.models.DirectionsRoute.getLegs()' on a null object reference
>        at com.mapbox.services.android.navigation.v5.routeprogress.RouteProgress.create(RouteProgress.java:59)
>        at com.mapbox.services.android.navigation.v5.NavigationEngine.onLocationChanged(NavigationEngine.java:77)
>        at com.mapbox.services.android.navigation.v5.NavigationService.forceLocationUpdate(NavigationService.java:168)
>        at com.mapbox.services.android.navigation.v5.NavigationService.startRoute(NavigationService.java:156)
>        at com.mapbox.services.android.navigation.v5.MapboxNavigation$NavigationServiceConnection.onServiceConnected(MapboxNavigation.java:485)
>        at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1320)
>        at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1337)
>        at android.os.Handler.handleCallback(Handler.java:739)
>        at android.os.Handler.dispatchMessage(Handler.java:95)
>        at android.os.Looper.loop(Looper.java:145)
>        at android.app.ActivityThread.main(ActivityThread.java:6939)
>        at java.lang.reflect.Method.invoke(Method.java)
>        at java.lang.reflect.Method.invoke(Method.java:372)
>        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
>        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)

```
![ezgif com-gif-maker](https://user-images.githubusercontent.com/17815721/30228967-a8ffad3e-94e8-11e7-94dd-583e9c63a3c3.gif)

**Comment by samvgorode** [comment]
Yes, in my case the same situation, when I used fake navigation route everything was great, but while real car driving marker is frozen, it isn't updating at all.

**Comment by samvgorode** [comment]
**Real car navigation experiments**
_version 0.5.0_ 
`locationLayerPlugin.forceLocationUpdate` inside `onMyLocationChange` 
do nothing.
`locationLayerPlugin.forceLocationUpdate` inside `onProgressChange` 
do nothing.
_version 0.6.0-SNAPSHOT_ 
`locationLayerPlugin.forceLocationUpdate` inside `onMyLocationChange` 
works good.
`locationLayerPlugin.forceLocationUpdate` inside `onProgressChange` 
do nothing.

**Comment by danesfeder** [comment]
@samvgorode Thank you for the feedback - in the gif above, that was a recording of a real test drive correct?  Or was it using `MockLocationEngine`?

**Comment by mecoFarid** [comment]
@danesfeder Yes, I recorded it while on real test drive.

**Comment by samvgorode** [comment]
@danesfeder sorry, I cant debug it while real driving.

**Comment by mf-mindcrewtech** [comment]
@samvgorode, i also want real-time navigation from current location to some destination, but i don't know how achieve it. can you please help me in this. Thanks

**Comment by mf-mindcrewtech** [comment]
@samvgorode, i also want real-time navigation from current location to some destination, but i don't know how achieve it. can you please help me in this. Thanks

NOTE :: I follow every single steps from this github demo but this is not working in real-time scenario.

**Comment by samvgorode** [comment]
@mf-mindcrewtech yes I can help you. my skype: samvgorode (Eugene Prokopenko)

**Comment by mf-mindcrewtech** [comment]
@samvgorode thanks, please check your skype, i sent you request

**Comment by cammace** [comment]
Sounds like you guys were able to work together to resolve the issue? It sounds like an issue with your setup for the locationEngine and I haven't observed any issues with navigation during driving.

**Comment by mecoFarid** [comment]
@cammace I believe @samvgorode will just help to achieve real-time simulation not to resolve the issue. Could you reopen the issue, by any chance, please? :)

**Comment by onsceneio** [comment]
we are still following this issue as well and have posted on original thread along with emails.  As noted here, its still not fixed @cammace

**Comment by onsceneio** [comment]
Has anyone been able to fix this?
All those at mapbox are not replying to this or other threads or emails as well? 
The links they provided are now showing 404 errors
