### ISSUE TITLE
Erratic behaviour after arrival on multi-stop route

### ISSUE THREAD

**Issue by aikeda** [mapbox/mapbox-navigation-android#2220]
Using an embedded NavigationView component, there is an erratic behavior on a multi-step (multi waypoints) route. Even when your route is already known and you are in the middle of a trip, when you arrive at any waypoint, a progress change event with ROUTE_ARRIVED state will be broadcasted with the correct user position. The next event will have a ROUTE_INITIALIZED event with 0,0 (lat, lng). But when CameraMode.TRACKING is enabled, the user will briefly be sent to the [Null Island](https://en.wikipedia.org/wiki/Null_Island) and camera zoom will change. If not, your user location marker will blink (~ 1-2 seconds). See gif below.

![Mapbox Navigation Issue GIF](https://user-images.githubusercontent.com/2802548/66888175-e7e15700-efb3-11e9-855b-2655415b73cb.gif)

In a real situation (real device and real trip), although I don't have evidence for now, after that you will also experience a strong user location tracking degradation. Location updates will be delayed and will be snapped not to the right places. If off-route detection is enabled, new directions will be loaded.

**Android API:**
API Level 28 (Android 9)

**Mapbox Navigation SDK version:**
mapbox-android-sdk: 8.4.0
mapbox-android-navigation: 0.42.0

### Steps to trigger behavior

 1. Define a multi-stop route with 1 waypoint and enable Route simulation (it happens with real device too and simulation off). Mount this screen with the embedded NavigationView component;
 2. Wait for the first arrival;
 3. You will see your user location marker disappear and if camera mode is TRACKING you will be sent to the ocean.

### Expected behavior
The last known location should be displayed.

### Actual behavior
Location is ~0,~0 (lat,lng)
Logs from route simulation:
```Log Format: [Tstamp] [Callback Method] @ [Lat, Lng] - [RouteProgressState]```
```
00:30:57.694 onProgressChange() @ -22.952369689941406,-43.18700408935547 - LOCATION_TRACKING
00:30:58.663 onArrival()
00:30:58.698 onProgressChange() @ -22.95238494873047,-43.187049865722656 - ROUTE_ARRIVED
00:30:59.704 onProgressChange() @ 2.2250738585072014E-308,2.2250738585072014E-308 - ROUTE_INITIALIZED
00:31:00.704 onProgressChange() @ -22.952308654785156,-43.18683624267578 - LOCATION_TRACKING
```

**Comment by Guardiola31337** [comment]
Hey @aikeda 👋 thanks for reaching out and report your issue.

The fix for this already landed and was released as part of `v0.42.5` - current version available is [`v0.42.6`](https://github.com/mapbox/mapbox-navigation-android/releases/tag/v0.42.6).

Please re-test with the latest version and feel free to cut a new ticket / reopen here if you're still able to reproduce.

Thanks again!
