### ISSUE TITLE
Release v0.42.1

### ISSUE THREAD

**Issue by olegzil** [mapbox/mapbox-navigation-android#2230]
### Release checklist @olegzil  

- [x] Run through testapp/demo app and test all activities
- [x] Pull in the latest translations from Transifex
- [x] Change version name to `0.42.1` in `gradle.properties`
- [x] Publish `0.42.1` artifact to Maven Central
- [x] Change version name back to `0.43.0-SNAPSHOT`
- [x] Update `README.md`
- [x] Tag `v0.42.1` in GitHub

### Post-release @langsmith   

- [x] Update `constants.js` file in `android-docs` repo 👀 https://github.com/mapbox/android-docs#updating-for-sdk-releases
- [x] Generate `navigation` and `navigation-ui` javadocs and add to `android-docs` repo
~- [ ] Update nav dependency used by android-tutorial-demo app.~
- [x] Update config files in /help repo _after_ tutorial (☝️) update is finished.
  - @colleenmcginnis @HeyStenson we are good to go for this release 👍 

### Changelog:

- Roundabout maneuver icon depicts counterclockwise movement when driving on the left is fixed here: [#2228](https://github.com/mapbox/mapbox-navigation-android/pull/2228)

**Comment by langsmith** [comment]
> - [ ] Update nav dependency used by android-tutorial-demo app.

No longer needed because the app is deprecated

**Comment by langsmith** [comment]
All done here! 🍾  🎊
