### ISSUE TITLE
Converting route data from DirectionsRoute to FeatureCollection takes much time

### ISSUE THREAD

**Issue by pozdnyakov** [mapbox/mapbox-navigation-android#2250]
`mapbox-navigation-android` [converts](https://github.com/mapbox/mapbox-navigation-android/blob/master/libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/route/FeatureProcessingTask.java) the route data from the [DirectionsRoute](https://docs.mapbox.com/android/api/mapbox-java/libjava-services/2.1.0/com/mapbox/services/api/directions/v5/models/DirectionsRoute.html) format to the [FeatureCollection](https://docs.mapbox.com/android/api/mapbox-java/libjava-geojson/2.0.0/com/mapbox/services/commons/geojson/FeatureCollection.html) format each time it takes a new route, and it takes up to few hundreds of millisecond. 

This issue shall ideally be fixed with unification the formats used in both directions and maps API. Maybe, this is something for the core-sdk team to take a look.

cc @chloekraw @mapbox/core-sdk

**Comment by Ranafugaz** [comment]
I'm having the same issue here. Some times it takes up to 20-30 seconds to draw the route on the map.

**Comment by Guardiola31337** [comment]
@abhishek1508 @cafesilencio are we good to close here?

cc @LukasPaczos

**Comment by cafesilencio** [comment]
If I draw a route from SF to LA on my phone it takes ~70ms.

**Comment by abhishek1508** [comment]
Probably a question for @pozdnyakov @brunoabinader

**Comment by cafesilencio** [comment]
One significant change in the 1.0 SDK is the way the route line is drawn. Prior to 1.0 a separate feature was created for each traffic segment. For long routes that resulted in a very large feature collection.  In the 1.0 implementation there is one feature created for the entire route and the traffic congestion is represented by a line gradient. I think we are good to close this ticket.

**Comment by Guardiola31337** [comment]
Where are we here @cafesilencio? Could you provide an update when you have a chance? 🙏

**Comment by cafesilencio** [comment]
I don't believe this is still an issue, closing this.
