### ISSUE TITLE
Could not resolve com.mapbox.mapboxsdk:mapbox-android-navigation-ui:0.42.0.

### ISSUE THREAD

**Issue by BrieucV** [mapbox/mapbox-navigation-android#2264]
**Android API:**
**Mapbox Navigation SDK version:**

Can't resolve dependency to use Mapbox Navigation SDK. Each attempt failed with the same error message...
for information, I added the extra maven {url ...mapbox} in my project's gradle and ask for the version 0.42.0

### Steps to trigger behavior
 1. add parameter to gradle settings 
 2. refresh gradle
 3. fails

### Expected behavior
Should find the dependency

### Actual behavior
ERROR: Unable to resolve dependency for ':app@debug/compileClasspath': Could not resolve com.mapbox.mapboxsdk:mapbox-android-navigation-ui:0.42.0.
Show Details
Affected Modules: app

ERROR: Unable to resolve dependency for ':app@debugAndroidTest/compileClasspath': Could not resolve com.mapbox.mapboxsdk:mapbox-android-navigation-ui:0.42.0.
Show Details
Affected Modules: app

ERROR: Unable to resolve dependency for ':app@debugUnitTest/compileClasspath': Could not resolve com.mapbox.mapboxsdk:mapbox-android-navigation-ui:0.42.0.
Show Details
Affected Modules: app

**Comment by sansumbrella** [comment]
Hi @BrieucV 

You might be running into issues where Android Studio has _two_ `repositories` blocks in the gradle file. I ran into this myself recently. Have you tried setting up your project gradle file so the maven specification is inside the `allprojects { repositories {` block?

```
buildscript {
    ext.kotlin_version = '1.3.50'
    // these repositories are used for something else
    repositories {
        google()
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.5.3'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    // These repositories are used for compiling your module dependencies
    repositories {
        google()
        jcenter()
        mavenCentral()
        maven { url 'https://mapbox.bintray.com/mapbox' }
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
```

**Comment by Guardiola31337** [comment]
Closing as stale.

@BrieucV please check above suggestion https://github.com/mapbox/mapbox-navigation-android/issues/2264#issuecomment-577238983 and feel free to cut a new ticket if you can't still build the project.

Thanks!
