### ISSUE TITLE
OutOfMemoryError Could not allocate JNI Env

### ISSUE THREAD

**Issue by sjd753** [mapbox/mapbox-navigation-android#2271]
**Android API:**
 targetSdkVersion 29

**Mapbox Navigation SDK version: **
 implementation 'com.mapbox.mapboxsdk:mapbox-android-navigation-ui:0.42.1'

### Steps to trigger behavior

 1. Use navigation ui SDK version 0.42.1
 2. Start navigation
 3. Sudden crash

### Expected behavior
Navigation runs smoothly
### Actual behavior
Crashes suddenly

<img width="1346" alt="Screen Shot 2019-11-19 at 6 38 00 AM" src="https://user-images.githubusercontent.com/14920076/69152942-58bfe580-0b03-11ea-9868-706fe411941e.png">

**Comment by Guardiola31337** [comment]
@abhishek1508 @cafesilencio could this be reproducible in `1.0`? Could you confirm?

**Comment by Guardiola31337** [comment]
Duplicated in https://github.com/mapbox/mapbox-navigation-android/issues/2245

Closing here.
