### ISSUE TITLE
Anticipate Movement

### ISSUE THREAD

**Issue by K-Leon** [mapbox/mapbox-navigation-android#228]
While making life runs on real devices I'm seeing a constant lag between the real location and the displayed location ( it's clear that it exists - max update frequency about 1-2 seconds plus processing time ). If your're mvoing fast this can add up to 50 meters and more the UI is lagging behind.

Is there anything that speaks again adding 2*currentspeed to Route snapped location? Is there an easy way to implement this with turf?

**Comment by cammace** [comment]
This sounds like your looking for a user location prediction model. The idea for this is being tracked in https://github.com/mapbox/mapbox-navigation-android/issues/54 using a Kalman filter. Correct me if you meant something else.

**Comment by K-Leon** [comment]
You're right - but I thought about s minimal Version. Going from the current Position n Meter along the route could be nearly enough. But Kalman would be the icing on the take. ;)

**Comment by cammace** [comment]
hmmm, you could try increasing the dead reckoning value inside MapboxNavigationOptions. Otherwise, this will have to wait till the Kalman filter arrives.
