### ISSUE TITLE
Can not run it

### ISSUE THREAD

**Issue by mashihao** [mapbox/mapbox-navigation-android#2283]
when i clone it from github with many errors 

* What went wrong:
Could not determine the dependencies of task ':libnavigation-core:compileDebugJavaWithJavac'.
> Could not resolve all task dependencies for configuration ':libnavigation-core:debugCompileClasspath'.
   > Could not resolve project :annotations.
     Required by:
         project :libnavigation-core
      > Unable to find a matching configuration of project :annotations:
          - Configuration 'errorprone':
              - Other attributes:
                  - Required com.android.build.api.attributes.BuildTypeAttr 'debug' but no value provided.
                  - Required com.android.build.gradle.internal.dependency.AndroidTypeAttr 'Aar' but no value provided.
                  - Required org.gradle.usage 'java-api' but no value provided.
                  - Required org.jetbrains.kotlin.platform.type 'androidJvm' but no value provided.

**Comment by LukasPaczos** [comment]
Hey @mashihao, for the time being, make sure to checkout vendor submodules as mentioned in [the readme](https://github.com/mapbox/mapbox-navigation-android#contributing):
```
git submodule update --init --recursive --remote
```
