### ISSUE TITLE
UK voice with Android Navigation SDK and wrong directions?

### ISSUE THREAD

**Issue by exgonline** [mapbox/mapbox-navigation-android#2298]
Hi everyone.

I have an embedded map in a fragment. All is working except I am unable to get a UK voice for directions. I have set the routebuilder language to: language(Locale.UK), but still American.

Also, I am getting the wrong directions on roundabouts! 

The top maneuver is completely wrong! This is happening on roundabouts but not turns etc ?

![Screenshot_20191210_155311](https://user-images.githubusercontent.com/8041221/70545505-98f41000-1b65-11ea-900b-e4439c6cd175.jpg)

I am using Android SDK 0.42.4

Thanks in advance.

**Comment by Guardiola31337** [comment]
> Also, I am getting the wrong directions on roundabouts!
>
> The top maneuver is completely wrong! This is happening on roundabouts but not turns etc ?

That's expected 👀 https://docs.mapbox.com/api/navigation/#retrieve-directions `roundabout_exits` which is enabled by default.

cc @JunDai

**Comment by Guardiola31337** [comment]
@JunDai could we check if this would be an issue in `1.0`?

**Comment by abhishek1508** [comment]
Let's verify this
cc @JunDai @cafesilencio @langsmith

**Comment by cafesilencio** [comment]
I did some testing with our upcoming 1.0 SDK.

One thing I found is that Locale.UK.language in Android returns "en" which isn't specific enough to get British English. In the RouteOptions.language I used "en-GB" and the resulting route had the same language code embedded in it. 

Also when creating the SpeechPlayer I used the same "en-GB" string when setting the language option. For example:
 ...
val speechPlayerProvider = SpeechPlayerProvider(context, "en-GB", true, voiceInstructionLoader)
val speechPlayer = NavigationSpeechPlayer(speechPlayerProvider)
...

Here's a [link to the example activity](https://github.com/mapbox/mapbox-navigation-android/blob/master/examples/src/main/java/com/mapbox/navigation/examples/core/InstructionViewActivity.kt) I tested with.

The configurations above resulted in voice instructions in British English.  Please look out for the upcoming release of the 1.0 version of the navigation SDK.  If you still experience problems report a bug.

**Comment by exgonline** [comment]
Thanks for the update :-)
