### ISSUE TITLE
MapRouteArrow is not displayed after style change

### ISSUE THREAD

**Issue by LukasPaczos** [mapbox/mapbox-navigation-android#2314]
## Steps to trigger behavior

 1. Run any active guidance example
 2. Change the style

### Actual behavior

![ezgif com-video-to-gif (11)](https://user-images.githubusercontent.com/16925074/70800166-d649df00-1dab-11ea-91fa-13dbfeb8b865.gif)

The arrow does not re-appear after style change.

**Comment by Guardiola31337** [comment]
This seems to be addressed by https://github.com/mapbox/mapbox-navigation-android/pull/2437 

![arrows_survive_style_changes](https://user-images.githubusercontent.com/1668582/75452812-e4d27c00-5940-11ea-9ae0-c841e247e6d6.gif)

Are we missing any follow up work? Are we good to close here? @LukasPaczos

**Comment by LukasPaczos** [comment]
We should be good :+1:
