### ISSUE TITLE
Mapbox cannot comply with Google Play Store's 64bit requirement?

### ISSUE THREAD

**Issue by Slodin** [mapbox/mapbox-navigation-android#2349]
**Android API: min 16, target 28**
**Mapbox Navigation SDK version: 0.42.4**

### Steps to trigger behavior

 1. Install navigation SDK and UI
 2. Generate bundle .aab
 3. Create a release and upload to play store
 4. Press save and then review

### Expected behavior
Able to fully roll out to play store
### Actual behavior
Gets and error from play store stating:

> This release is not compliant with the Google Play 64-bit requirement
>
> The following APKs or App Bundles are available to 64-bit devices,
>  but they only have 32-bit native code: 18.

### Adding Mapbox dependency

> implementation 'com.mapbox.mapboxsdk:mapbox-android-navigation:0.42.4'
> implementation 'com.mapbox.mapboxsdk:mapbox-android-navigation-ui:0.42.4' 

```
allprojects {
    repositories {
        jcenter()
        mavenCentral()
        google()
        maven { url 'https://mapbox.bintray.com/mapbox' }
    }
}
```

### How I think it's a Mapbox problem
At first I thought it might be any other libraries causing this error, but in the end narrowed it down to Mapbox. **Once I remove Mapbox from my dependencies, I can upload and roll out my application**. I have read the documentation over and over but I can't find out why this is happening. I opened the .aab file to inspect the lib CPU architectures and all of them are present for all my libraries including mapbox.  'armeabi-v7a', 'arm64-v8a', 'x86', 'x86_64' are all present, and mapbox .so files are in each one as well. I have tried to disable the 32bit architectures but still get the same error.

However, I don't see anyone mentioning this problem as I search on. Maybe there is something wrongly configuration on my end and I'm not seeing it :/

Don't mind the libjcore, that one can build and roll out with no problem
![image](https://user-images.githubusercontent.com/9064460/71938599-ce8c1900-3164-11ea-8a0a-ee936abd5092.png)

**Comment by Guardiola31337** [comment]
Is this an issue in the `1.0` SDK @mapbox/navigation-android?

**Comment by Lebedinsky** [comment]
@Slodin Thank you for your report! I checked Mapbox Navigation SDK is it compatible with 64-bit devices and looks like it is working for 64-bit devices for both .apk and .aab.
Check please, next line
```
android {
    defaultConfig {
        ...
        ndk.abiFilters 'armeabi-v7a','arm64-v8a','x86','x86_64'
    }
}
```
in your `build.gradle` file. And if you have such, check there is all the architectures are present. If you don't have such line, try to paste it.

Also, check please [this article](https://developer.android.com/distribute/best-practices/develop/64-bit) and make sure you you checked your application by the same instruction.

Feel free to ask anything if you have another questions or in case if you still have this issue)
