### ISSUE TITLE
Navigation with list of Position

### ISSUE THREAD

**Issue by mf-mindcrewtech** [mapbox/mapbox-navigation-android#235]
Hi, how can I add my list of position/coordinates for navigation. I am using
compile 'com.mapbox.mapboxsdk:mapbox-android-navigation:0.6.0-SNAPSHOT'
compile 'com.mapbox.mapboxsdk:mapbox-android-navigation-ui:0.6.0-SNAPSHOT@aar'

the only access for NavigationRoute class is something like this
NavigationRoute.builder()
                .accessToken(Mapbox.getAccessToken())
                .origin(origin)
                .destination(destination)
                .build()
                .getRoute((retrofit2.Callback<DirectionsResponse>) this);

BUT i want to achieve something like this, as I have list of coordinates

NavigationRoute.builder()
                .accessToken(Mapbox.getAccessToken())
                .coordinates(list)// this is not accessible
                .build()
                .getRoute((retrofit2.Callback<DirectionsResponse>) this);

Any help really appreciate. Thanks

**Comment by danesfeder** [comment]
To get a `DirectionsRoute` with multiple legs you can add `Position` waypoints to your builder.  These are considered stops in between the origin and destination `Position`s (in the order that you add them - first waypoint is the first stop):

```
NavigationRoute.builder()
.accessToken(Mapbox.getAccessToken())
.origin(origin)

.addWaypoint(waypoint)
.addWaypoint(waypoint)
.addWaypoint(waypoint)

.destination(destination)
.build()
.getRoute((retrofit2.Callback) this);
```

**Comment by mf-mindcrewtech** [comment]
Hii Thanks @danesfeder , is there any way to add waypoints in for loop? for some size (dynamically) as I don't want to add as hardcoded waypoints

**Comment by danesfeder** [comment]
You can create the builder and then add the waypoints to the builder in a for loop:

```    
NavigationRoute.Builder builder = NavigationRoute.builder()
      .accessToken(Mapbox.getAccessToken())
      .origin(origin)
      .destination(destination);
    
    for (Position waypoint : waypoints) {
      builder.addWaypoint(waypoint);
    }
    
    builder.build().getRoute(this);
```

For better visibility of these questions, in the future, if you don't mind asking them on StackOverflow (rather than raising an issue) we would appreciate it.  That way more developers can more easily find the solution when searching for the same question.

**Comment by mf-mindcrewtech** [comment]
Hi @danesfeder , thanks but this is not giving any route response

My code is as

origin :: Position [longitude=75.891441, latitude=22.742855, altitude=NaN]
destination :: Position [longitude=75.893737, latitude=22.744398, altitude=NaN]
Waypoints Position List
0 = {Position@5519} "Position [longitude=75.892879, latitude=22.743369, altitude=NaN]"
1 = {Position@5548} "Position [longitude=75.894274, latitude=22.747782, altitude=NaN]"
2 = {Position@5549} "Position [longitude=75.895153, latitude=22.751364, altitude=NaN]"
3 = {Position@5550} "Position [longitude=75.895969, latitude=22.751225, altitude=NaN]"
4 = {Position@5551} "Position [longitude=75.895346, latitude=22.749623, altitude=NaN]"

NavigationRoute.Builder builder = NavigationRoute.builder()
      .accessToken(Mapbox.getAccessToken())
      .origin(origin)
      .destination(destination);
    for (Position waypoint : waypoints) {
      builder.addWaypoint(waypoint);
    }
    builder.build().getRoute(this);

When I run above code , i am not getting any route response...

But when i run below code, i am getting route response.
NavigationRoute.Builder builder = NavigationRoute.builder()
      .accessToken(Mapbox.getAccessToken())
      .origin(origin)
      .destination(destination);
    builder.build().getRoute(this);

Can you please let me know, what is the issue??
NOTE :: I tested these points with GoogleDirectionsLibrary and route is create perfectly.
