### ISSUE TITLE
Add updateNotification unit test coverage

### ISSUE THREAD

**Issue by LukasPaczos** [mapbox/mapbox-navigation-android#2389]
https://github.com/mapbox/mapbox-navigation-android/pull/2386 follow up. We should especially include https://github.com/mapbox/mapbox-navigation-android/pull/2385 regression.

/cc @evabishchevich

**Comment by abhishek1508** [comment]
Also the function `buildRemoteViews` is called everytime from `updateNotification()`. It's not needed as the remote views should only be created once. Let's move the `buildRemoteViews` to `init` block

**Comment by evabishchevich** [comment]
PR https://github.com/mapbox/mapbox-navigation-android/pull/2401
/cc @abhishek1508 @LukasPaczos
