### ISSUE TITLE
Map visually resets when navigating through waypoints

### ISSUE THREAD

**Issue by sansumbrella** [mapbox/mapbox-navigation-android#2395]
**Android API:**
min: 24
target: 28
**Mapbox Navigation SDK version:**
`mapbox-android-navigation-ui:0.42.4`

### Steps to trigger behavior

 1. Create a route with at least one waypoint
 2. Simulate route playback (or start traveling for real?)
 3. Arrive at a waypoint

### Expected behavior
The directions pause at the waypoint and the banner continues to display the map at that location.

### Actual behavior
The map flashes to a blue screen and the directions banner text resets to an earlier step. The earlier step seems to be the initial instruction for the entire route. In the sample code in the details, it is "ocelot".

![blue-flash-gif](https://user-images.githubusercontent.com/81553/72849349-7ed54380-3c74-11ea-9dfa-c03054b5ec06.gif)

<details>
<pre>
package com.mapbox.davidwicks.mapboxnavigationdemo

import android.graphics.Path
import androidx.appcompat.app.AppCompatActivity
import android.os.Bundle
import android.util.Log
import com.mapbox.api.directions.v5.models.DirectionsResponse
import com.mapbox.api.directions.v5.models.DirectionsRoute
import com.mapbox.geojson.Point
import com.mapbox.mapboxsdk.Mapbox
import com.mapbox.services.android.navigation.ui.v5.NavigationLauncher
import com.mapbox.services.android.navigation.ui.v5.NavigationLauncherOptions
import com.mapbox.services.android.navigation.v5.navigation.NavigationRoute
import retrofit2.Call
import retrofit2.Response

class MainActivity : AppCompatActivity() {

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)
        requestRoute()
        Log.i("NavigationDemo", "Getting started with the main activity")
    }

    data class Waypoint(val position: Point, val name: String)

    val waypoints = arrayOf(
        Point.fromLngLat(-77.038294672966, 38.91854721860871),
        Point.fromLngLat(-77.03662633895874, 38.91920249133305),
        Point.fromLngLat(-77.03660779663086, 38.9182091456012),
        Point.fromLngLat(-77.03660052546692, 38.91565476415369),
        Point.fromLngLat(-77.03664779663086, 38.91398518410977),
        Point.fromLngLat(-77.03661561012268, 38.913726395687185),
        Point.fromLngLat(-77.03665852546692, 38.91345925826118),
        Point.fromLngLat(-77.03665852546692, 38.91270792885979)
    )
    val names = arrayOf(
        "animal", // origin
        "ocelot",
        "bear",
        "cat",
        "dog",
        "elephant",
        "frog",
        "goat" // destination
    )

    fun requestRoute() {
        val builder = NavigationRoute.builder(this)
            .accessToken(getString(R.string.MAPBOX_ACCESS_TOKEN))
            .origin(waypoints.first())
            .destination(waypoints.last())
            .continueStraight(false)
            .profile("driving")

        for (i in 1 until waypoints.lastIndex) {
            builder.addWaypoint(waypoints[i])
        }
        builder.addWaypointNames(*names)

        val route = builder.build()
        route
            .getRoute(object : retrofit2.Callback<DirectionsResponse> {
                override fun onResponse(
                    call: Call<DirectionsResponse>,
                    response: Response<DirectionsResponse>
                ) {
                    if (response.isSuccessful) {
                        Log.i(
                            "NavigationDemo",
                            "Route generation maybe happened: ${response.body()?.code()}"
                        )
                        val route = response.body()?.routes()?.first()
                        route?.let {
                            startNavigation(route)
                        }
                    } else {
                        Log.e(
                            "NavigationDemo",
                            "Route generation failed: ${response.errorBody()?.string()}"
                        )
                    }

                }

                override fun onFailure(call: Call<DirectionsResponse>, t: Throwable) {
                    Log.e("NavigationDemo", "Unable to generate route ${t.message}")
                }
            })
    }

    fun startNavigation(route: DirectionsRoute) {
        Mapbox.getInstance(this, getString(R.string.MAPBOX_ACCESS_TOKEN))
        val simulateRoute = true

        val options = NavigationLauncherOptions.builder()
            .directionsRoute(route)
            .shouldSimulateRoute(simulateRoute)
            .build()

        NavigationLauncher.startNavigation(this, options)
    }
}
</pre>
</details>

**Comment by sansumbrella** [comment]
I walked the route this morning so I could safely confirm the issues with the visual resetting. What I noticed:

- The instruction banner text displays the first instruction whenever there is no upcoming maneuver. That is, whenever you only need to continue straight to arrive at the next waypoint, the banner displays the name of the first maneuver or waypoint.
- After declaring "you have arrived" at a waypoint, the map view flashes blue and the camera resets to a very zoomed-out view.
- The entire route line is drawn as you progress through waypoints. Once you pass the final waypoint and only have the destination remaining, the historic route is no longer drawn behind you. It would be clearer if the historic route and already-visited waypoints were removed from rendering as navigation progresses.

So this issue seems to be primarily about how _waypoints_ are handled by the navigation UI SDK. I would expect them to be handled similarly to the destination. I didn't notice any strange camera behaviors or instruction text issues when I arrive at the destination.

Screenshots from my walk follow. In images where you can read perpendicular street labels, I manually adjusted the map camera. The zoomed out images are the UI-set camera settings.

<details>
<img alt="Screenshot_20200122-091122" src="https://user-images.githubusercontent.com/81553/72906697-9fe37600-3d00-11ea-84f1-b727d3f6c672.png"/>
<img alt="Screenshot_20200122-091156" src="https://user-images.githubusercontent.com/81553/72906698-9fe37600-3d00-11ea-99aa-fa689019512c.png"/>
<img alt="Screenshot_20200122-091230" src="https://user-images.githubusercontent.com/81553/72906699-9fe37600-3d00-11ea-82ce-6ecefa75ea7d.png"/>
<img alt="Screenshot_20200122-091408" src="https://user-images.githubusercontent.com/81553/72906700-a07c0c80-3d00-11ea-8808-fd77ad4716aa.png"/>
<img alt="Screenshot_20200122-091525" src="https://user-images.githubusercontent.com/81553/72906701-a07c0c80-3d00-11ea-9c4b-c9c96532d884.png"/>
<img alt="Screenshot_20200122-091555" src="https://user-images.githubusercontent.com/81553/72906702-a07c0c80-3d00-11ea-90b6-face80cfb021.png"/>
<img alt="Screenshot_20200122-091620" src="https://user-images.githubusercontent.com/81553/72906704-a07c0c80-3d00-11ea-8fe1-f616104093bf.png"/>
<img alt="Screenshot_20200122-091753" src="https://user-images.githubusercontent.com/81553/72906705-a07c0c80-3d00-11ea-969e-f6f2fdb31dc0.png"/>
<img alt="Screenshot_20200122-091817" src="https://user-images.githubusercontent.com/81553/72906706-a07c0c80-3d00-11ea-81b9-37359c1b82a0.png"/>
<img alt="Screenshot_20200122-091844" src="https://user-images.githubusercontent.com/81553/72906707-a07c0c80-3d00-11ea-9ce9-feeadbbcf1ff.png"/>
<img alt="Screenshot_20200122-091855" src="https://user-images.githubusercontent.com/81553/72906708-a114a300-3d00-11ea-8795-00265a31f9e0.png"/>
<img alt="Screenshot_20200122-091913" src="https://user-images.githubusercontent.com/81553/72906709-a114a300-3d00-11ea-820b-f37ad9aa5a6b.png"/>
<img alt="Screenshot_20200122-091939" src="https://user-images.githubusercontent.com/81553/72906710-a1ad3980-3d00-11ea-91b3-bfb967e1ca84.png"/>
<img alt="Screenshot_20200122-091949" src="https://user-images.githubusercontent.com/81553/72906711-a1ad3980-3d00-11ea-991e-6fed81d241f8.png"/>
<img alt="Screenshot_20200122-092019" src="https://user-images.githubusercontent.com/81553/72906712-a1ad3980-3d00-11ea-9fe0-da0eff456c6a.png"/>
<img alt="Screenshot_20200122-092028" src="https://user-images.githubusercontent.com/81553/72906713-a1ad3980-3d00-11ea-90f7-780e15e0d466.png"/>
<img alt="Screenshot_20200122-092057" src="https://user-images.githubusercontent.com/81553/72906716-a245d000-3d00-11ea-90b6-ca8b912c9634.png"/>
<img alt="Screenshot_20200122-092128" src="https://user-images.githubusercontent.com/81553/72906717-a245d000-3d00-11ea-8ba5-2ad946ac32b5.png"/>
</details>

**Comment by sansumbrella** [comment]
Tagging @tkvalentine56 since I believe this matches an issue you raised with me and @AntJones85

**Comment by Guardiola31337** [comment]
The fix for this is included downstream in `mapboxNavigator` `7.0.0` and will be available in the upcoming Navigation SDK `v0.42.5` 🎉 

Closing here.

cc @sansumbrella @tkvalentine56 @AntJones85 @andrewychen @zugaldia

**Comment by Guardiola31337** [comment]
FYI  `0.42.5` version of the SDK has been released and it's available in Maven Central https://repo1.maven.org/maven2/com/mapbox/mapboxsdk/mapbox-android-navigation/0.42.5/ 🎉

**Comment by sansumbrella** [comment]
Thanks!

Confirmed that the camera reset is fixed by the latest SDK.

The directions banner still seems to be resetting to an earlier instruction. In the simulator I am seeing the camera behave nicely (awesome!), but the directions banner quickly reverts to the first instruction—"ocelot"—after arriving at a waypoint. I still need to test it while actually on the road to confirm.

I will open a separate issue for the banner text.

**Comment by Guardiola31337** [comment]
That's good feedback. Do you have a video reproducing the issue you're seeing? Also a snippet of code of what exactly you're implementing would be really helpful here. We've tested the multi-waypoints use case [`EndNavigationActivity`](https://github.com/mapbox/mapbox-navigation-android/blob/base-v0.42.1/app/src/main/java/com/mapbox/services/android/navigation/testapp/activity/navigationui/EndNavigationActivity.java) from the test app and not experiencing what you're describing so it should be a subtle detail.

In any case, as you mentioned, feel free to cut a separate ticket after your testing. Thanks again for reporting 🙇
