### ISSUE TITLE
Real-time Navigation

### ISSUE THREAD

**Issue by mf-mindcrewtech** [mapbox/mapbox-navigation-android#240]
Hi, from this demo we have navigation from current location to destination (some marker) but not in real-time.

How can I achieve real-time navigation, something like these::
1) Created a route from current location to destination.. DONE
2) Start navigation ** when i actually start moving in car with my phone. (Not like showing in demo)

For this I updated my onLocationChanged to this ::

  if (currentRouteToDestination != null) {
// calling this method
                activateMockLocationEngine(currentRouteToDestination);
            }

private void activateMockLocationEngine(com.mapbox.services.api.directions.v5.models.DirectionsRoute route) {
        locationEngine = new MockLocationEngine(1000, 30, false);
        ((MockLocationEngine) locationEngine).setRoute(route);
        locationEngine.activate();
    }

BUT even when i move with my car nothing happens in my navigation. Can you please let me know, what I still need to add. Thanks

**Comment by davols** [comment]
Are you using the `MockLocationEngine` for real life driving? If so, you need to change it and use another locationengine. `LostLocationEngine` or from Google. 
If you want to use LOST you can use it like so.
`locationEngine = LostLocationEngine.getLocationEngine(this);`

**Comment by mf-mindcrewtech** [comment]
Thanks @davols, for pointing out the correct locationEngine.
Can you please also look at anther issue (https://github.com/mapbox/mapbox-navigation-android/issues/241). I need instructions in my app.

**Comment by davols** [comment]
I don't want to step on any toes, or put words in anyones mouth. (Please reach out if you don't want me to answer low hanging questions @cammace or @danesfeder or anyone else).
But I believe you @mf-mindcrewtech should move these questions to stackoverflow for visibility as mentioned in https://github.com/mapbox/mapbox-navigation-android/issues/235#issuecomment-330548298

**Comment by mf-mindcrewtech** [comment]
okay i will resolved it by myself thanks

**Comment by cammace** [comment]
Thanks for all your help and feedback guys
