### ISSUE TITLE
Improve re-routing logic

### ISSUE THREAD

**Issue by LukasPaczos** [mapbox/mapbox-navigation-android#2404]
The routing logic currently internally retries to fetch a route once and then aborts on failure. Also, when a new route request is made, we're only recalculating origin and bearing, we need to implement waypoints conversion as well.

TODO:
- [ ] By default, implement a re-try logic which will try to request a new route until succeded in fixed, possibly intervals of time. Maybe the `DirectionsSession#requestRoutes` should accept a callback together with options that would allow us to re-do the request.
- [x] Fix options recalculation logic 
  - [ ] Expose extension functions.
- [x] Optionally, can even be done in the future if requested, we can expose an option to overwrite the default rerouting logic with a custom one.

/cc @mapbox/navigation-android

**Comment by Guardiola31337** [comment]
Refs. https://github.com/mapbox/mapbox-navigation-android/issues/2404

**Comment by Guardiola31337** [comment]
> - [ ] Optionally, can even be done in the future if requested, we can expose an option to overwrite the default rerouting logic with a custom one.

This was addressed by https://github.com/mapbox/mapbox-navigation-android/pull/3184 Going to go ahead and check it from OP's list 👍

**Comment by Guardiola31337** [comment]
cc @LukasPaczos @RingerJK

**Comment by LukasPaczos** [comment]
Closing this master ticket in favor of https://github.com/mapbox/mapbox-navigation-android/issues/3223 which tracks the last remaining item which is the retry logic.

**Comment by RingerJK** [comment]
@LukasPaczos we still don't expose extension functions
>  - [ ] Expose extension functions.

**Comment by LukasPaczos** [comment]
Is there an opportunity to extend any with the reroute controller?

**Comment by RingerJK** [comment]
don't think so, but RouteOptionsProvider has it. And still it might be a part of tailwork just after silent waypoints issue be fixed cc @Lebedinsky
