### ISSUE TITLE
Expose NavigationOptions and its factory

### ISSUE THREAD

**Issue by LukasPaczos** [mapbox/mapbox-navigation-android#2405]
Refs https://github.com/mapbox/mapbox-navigation-android/pull/2400/files#r369593015. We need to accept `NavigationOptions` in the `MapboxNavigation` and make sure to offer smart defaults.

/cc @mapbox/navigation-android

**Comment by LukasPaczos** [comment]
This should also expose navigator delay - refs https://github.com/mapbox/mapbox-navigation-android/pull/2400/files#r369595156.

**Comment by evabishchevich** [comment]
PR https://github.com/mapbox/mapbox-navigation-android/pull/2419
