### ISSUE TITLE
Provide different notification UI in free-drive mode

### ISSUE THREAD

**Issue by LukasPaczos** [mapbox/mapbox-navigation-android#2412]
When we start a trip session and subsequently a trip service, we are starting to display a notification that is required by the foreground service. However, when we are in a free-drive mode, there's no route data and the notification UI is stuck with placeholder views.

We should provide separate UI components when there's no route data available, we can use `RouteProgress` for that - if `RouteProgress#route` is null we should replace the UI with something minimalistic that only has a "stop session" (or the likes) button.

/cc @mapbox/navigation-android

**Comment by Guardiola31337** [comment]
WIP in https://github.com/mapbox/mapbox-navigation-android/pull/2450

It'd be 💯 if we can get input from the design team @designevokes @map-angela @noracalabrese

**Comment by abhishek1508** [comment]
I would like to debate as to why do we even need to have a notification in free drive state? 
The notification is handy in `Active Guidance` state as it gives you next instruction. In `Free Drive` there is no instruction. We are basically reading the user's current location and snapping it on the road. If the user happens to background and foreground that would still happen. I guess the question is what are the benefits of having the app running if a user is in free drive.
cc @LukasPaczos @Guardiola31337 @mapbox/navigation-android

**Comment by Guardiola31337** [comment]
#2450 and #2605 landed 🎉 

Closing here.
