### ISSUE TITLE
Audit code seeking leaks

### ISSUE THREAD

**Issue by Guardiola31337** [mapbox/mapbox-navigation-android#2418]
- Audit the code to check that we're not leaking e.g. :eyes: that all of the observers registered get unregistered and any other common sources of leaks.

Follow up from https://github.com/mapbox/mapbox-navigation-android/pull/2413#discussion_r370267878

cc @mapbox/navigation-android

**Comment by Guardiola31337** [comment]
This was addressed in https://github.com/mapbox/mapbox-navigation-android/pull/2443 Are we missing any follow up work? Are we good to close here? @cafesilencio

**Comment by Guardiola31337** [comment]
@cafesilencio where are we here? Good to close?

**Comment by cafesilencio** [comment]
no more work to be done here
