### ISSUE TITLE
NavigationAccounts unit tests

### ISSUE THREAD

**Issue by LukasPaczos** [mapbox/mapbox-navigation-android#2421]
Refs https://github.com/mapbox/mapbox-navigation-android/pull/2410#pullrequestreview-347257616. We need to clear the details and verify that the business logic is correct.

**Comment by Guardiola31337** [comment]
This was addressed in https://github.com/mapbox/mapbox-navigation-android/pull/2457 and https://github.com/mapbox/mapbox-navigation-android/pull/2461 Are we missing any follow up work? Are we good to close here? @JunDai @cafesilencio

**Comment by JunDai** [comment]
@cafesilencio - I remember that you had some unit test codes about `MapboxNavigationAccountsProvider` and/or `MapboxNavigationAccounts`? I am not sure if you got any chance to merge them in?

**Comment by Guardiola31337** [comment]
@cafesilencio @JunDai where are we here? Good to close?

**Comment by Guardiola31337** [comment]
🆗 going ahead and closing here. Feel free to cut a new ticket if there's any missing tailwork here.
