### ISSUE TITLE
Release 1.0.0-beta.1

### ISSUE THREAD

**Issue by LukasPaczos** [mapbox/mapbox-navigation-android#2428]
Today we're excited to announce the first `beta` in a series of releases towards `v1.0` of our Navigation SDK for Android, adding new features like hybrid offline navigation, improved localization, updated UI components, and a new Kotlin-first architecture designed for modularity from the ground up for more flexibility and control.

This is a great opportunity to provide feedback on the new series to help us shape the final release. Please see the [test app](https://github.com/mapbox/mapbox-navigation-android/tree/master/examples) for reference implementations of all components and please [cut a ticket](https://github.com/mapbox/mapbox-navigation-android/issues) with any issues or feedback you have about this beta.

## Mapbox Navigation Core SDK 1.0.0-beta.1
[`MapboxNavigation`](https://github.com/mapbox/mapbox-navigation-android/blob/master/libnavigation-core/src/main/java/com/mapbox/navigation/core/MapboxNavigation.kt) class is an entry point for interacting with and customizing a navigation session.

The SDK can enter into the following internal states:
- `Idle`
- `Free Drive`
- `Active Guidance`

### Location
Whenever the `MapboxNavigation#startTripSession` is called, the SDK will enter the `Free Drive` state starting to request and propagate location updates via the `LocationObserver`.

This observer provides 2 location update values in mixed intervals - either the raw one received from the provided `LocationEngine` or the enhanced one map-matched internally using SDK's native capabilities.

In `Free Drive` mode, the enhanced location is computed using our underlying routing tile data that accurately snaps the vehicle to its current road segment.

If the session is stopped, the SDK will stop listening for raw location updates and enter the `Idle` state.

### Routing
A route can be requested with `MapboxNavigation#requestRoutes`. If the request is successful and returns a non-empty list of routes in the `RouteObserver`, the first route at index 0 is going to be chosen as a primary one.

If the SDK is in an `Idle` state, it stays in this same state even when a primary route is available.

If the SDK is already in the `Free Drive` state or trip sessions is started when a primary route is available, the SDK will enter the `Active Guidance` state instead and propagate actionable `RouteProgress`. Additionally, the enhanced location's map-matching will be more precise and based on the primary route itself.

If the first or any routes request fails, or the route is manually cleared, the SDK will fall back to either `Idle` or `Free Drive` state.

### Modularity
The Navigation Core SDK's initial surface is the `MapboxNavigation` class but it also depends on a base artifact that contains interface definitions and contracts that describe different components of the SDK, as well as numerous other artifacts that contain the concrete implementation of those interfaces.

This type of architecture is created to provide a clean, testable, maintainable public API surface and also unlock modularization capabilities.

All modules are required for the SDK to operate properly, therefore, the library is shipped with a set of default implementations for each of the modules. However, any public module can also be excluded from the build and a custom implementation can be provided by the developer.

![Navigation Modules internal](https://user-images.githubusercontent.com/16925074/73092850-a549e780-3edd-11ea-886f-bd17b99dee3c.png)

If we exclude `MapboxHybridRouter`, we'll have to provide some implementation of the `Router` interface. We could reuse one of `MapboxOnboardRouter`, `MapboxOffboardRouter` or provide a custom one. For example, we could replace the `MapboxHybridRouter` with the default `MapboxOffboardRouter` (because they share the same `Router` interface) to remove native/offline integration:

_build.gradle file_
```
compileOnly("com.mapbox.base:annotations:0.0.1-alpha.2")
kapt("com.mapbox.base:annotations-processsor:0.0.1-alpha.2")

implementation("com.mapbox.navigation:core:1.0.0-beta.1") {
    exclude group: "com.mapbox.navigation", module: "router"
}
implementation("com.mapbox.navigation:router-offboard:1.0.0-beta.1")
```

_MyNavigationActivity.kt file_
```
@MapboxNavigationModule(Router)
class MyRouterProvider

init {
    Mapbox_RouterModuleConfiguration.moduleProvider = object : Mapbox_RouterModuleConfiguration.ModuleProvider {
        override fun createRouter() = MapboxOffboardRouter()
    }
    val navigation = MapboxNavigation(context, token)
}
```

Similarly, if we exclude the `MapboxTripNotification` implementation, we'll still need to provide the `TripNotification` by extending and annotating the interface.

The currently customizable components are:
- `com.mapbox.navigation.notification`, extends `TripNotification` interface
- `com.mapbox.navigation.router`, extends `Router` interface (hybrid, default router)
- `com.mapbox.navigation.router-offboard`, extends `Router` interface
- `com.mapbox.navigation.router-onbaord`, extends `Router` interface

**_Disclaimer:_**
- In `v1.0.0-beta.1` only the online routing and route-based map-matching solutions are available.
- In future iterations, the primary route will be possible to set externally.

### Release checklist @Guardiola31337 
- [x] Run through testapp/demo app and test all activities
- [x] Change version name to `1.0.0-beta.1` in `artifact-settings.gradle`
- [x] Publish `1.0.0-beta.1` artifact to Maven Central
- [x] Change version name back to `1.0.0-SNAPSHOT`
- [x] Update ~`README.md`~ `CHANGELOG.md`
- [x] Tag `v1.0.0-beta.1` in GitHub
- [x] Attach the javadoc to the tag

/cc @mapbox/navigation-android @zugaldia @andrewychen

**Comment by Guardiola31337** [comment]
All done 🎬 🍾

Closing here.
