### ISSUE TITLE
E/UncaughtException: java.lang.IllegalStateException: Calling getSourceAs when a newer style is loading/has loaded

### ISSUE THREAD

**Issue by rajiniyadav** [mapbox/mapbox-navigation-android#2440]
E/UncaughtException: java.lang.IllegalStateException: Calling getSourceAs when a newer style is loading/has loaded

**Comment by Guardiola31337** [comment]
Hey @rajiniyadav 👋 thanks for reaching out and report your issue.

Could you add some more information for reproducing the behavior you're describing or any other specifics around your setup? If there is any sample or pseudo code you can provide, that would be really helpful and it'll give us better insight into your implementation and what could be causing your problem.

**Comment by Guardiola31337** [comment]
Closing this in favor of https://github.com/mapbox/mapbox-navigation-android/issues/2272
