### ISSUE TITLE
Adapt Transifex to 1.0 setup

### ISSUE THREAD

**Issue by Guardiola31337** [mapbox/mapbox-navigation-android#2453]
As noted here https://github.com/mapbox/mapbox-navigation-android/pull/2355#pullrequestreview-341961082

We should create separate Transifex projects and place the translations accordingly to where they will live with the new `1.0` module setup and adapt Transifex configuration accordingly 👀 https://github.com/mapbox/mapbox-navigation-android/blob/master/.tx/config

- Move translations to the module where its translations are going to live from now on (`1.0`)
- Setup / configure Transifex so it points to these new modules and when pulling the translations, they land in their respective modules

cc @mapbox/navigation-android @1ec5 @langsmith

**Comment by Guardiola31337** [comment]
A good starting would be setting up `libtrip-notification` first which is where most of the current translations from `libandroid-navigation` are going to live (currently the translations included in `libtrip-notification` were copied from `libandroid-navigation` but they cannot be pulled out directly into this new module hence the above-mentioned Transifex setup work).

We should repeat the process for other modules if after `libtrip-notification` refactor there are still translations in `libandroid-navigation` which should live under other modules.

**Comment by Guardiola31337** [comment]
This was addressed in https://github.com/mapbox/mapbox-navigation-android/pull/2456 Are we missing any follow up work? Are we good to close here? @langsmith

**Comment by langsmith** [comment]
Good to close
