### ISSUE TITLE
Expose Nav Native options via NavigationOptions

### ISSUE THREAD

**Issue by LukasPaczos** [mapbox/mapbox-navigation-android#2469]
There are a bunch of options in the `NavigatorConfig` class that we can and should expose via the `NavigationOptions`. This includes number of uncertain points, off-route threshold and other. We can take the legacy `MapboxNavigationOptions` for comparison.

/cc @mapbox/navigation-android

**Comment by Guardiola31337** [comment]
Thanks for cutting this ticket @LukasPaczos 🙇 this is definitely needed.

One thing to mention here is that not all the options from `NavigatorConfig` should be exposed, so we should probably create a wrapper around `NavigatorConfig` and expose only some options instead of including `NavigatorConfig` as part of `NavigationOptions`.

**Comment by LukasPaczos** [comment]
Yes agreed. We possibly don't need a wrapper, just expose the required options (using primitives or regular Java types), map them in the `MapboxNavigation` or `MapboxTripSession` to the `NavigatorConfig` class and push to NN.

**Comment by Guardiola31337** [comment]
Yeah, that works too 🚀 although don't want to run into [Primitive Obsession](https://refactoring.guru/smells/primitive-obsession) 😅

**Comment by vmihaylenko** [comment]
@mapbox/navigation-android Hey folks! Could you prioritize this issue? The nav-native team would like to check some cases with the `useEKF` option turned off.

**Comment by zugaldia** [comment]
@kmadsen will be running with implementation per team standup today.

**Comment by mskurydin** [comment]
Which release will we have this in? useEKF (which is true by default) is harmful for BMW and automotive use cases in general. There should be a way to disable it for them. More info about it can be found in the original ticket.

**Comment by Guardiola31337** [comment]
Refs. https://github.com/mapbox/mapbox-navigation-android/pull/2600#issuecomment-600252408

**Comment by SiarheiFedartsou** [comment]
I think the best solution is to think about `setConfig` as if it is a part of constructor. I believe at some point we will move it to constructor as well as `configureRouter`.

**Comment by Guardiola31337** [comment]
Cross posting from https://github.com/mapbox/mapbox-navigation-android/pull/2600#issuecomment-600529354

> @SiarheiFedartsou: I think the best solution is to think about `setConfig` as if it is a part of constructor. I believe at some point we will move it to constructor as well as `configureRouter`.
>> @LukasPaczos: This would mean that the implementation from this PR is already semi-deprecated and will require breaking changes in the near future to remove the introduced here mutability.
>>
>> In this case, I think we should refactor this option and pass it only in the `NavigationOption` when the `MapboxNavigation` is first created.

cc @LukasPaczos @kmadsen

**Comment by zugaldia** [comment]
@kmadsen @Guardiola31337 @LukasPaczos @SiarheiFedartsou could you set up 15 min to voice and debate/decide/commit on an API design for the options object?

**Comment by kmadsen** [comment]
I don't want to expose the raw native configuration. We actually lose flexibility by doing that

> https://mapbox.slack.com/archives/CMY3Y5SQM/p1584555497462800?thread_ts=1584543950.447900&cid=CMY3Y5SQM
> we spend hours tuning each value in this huge list of parameters(and also it can be automated at some moment I think). 

Things like "number of uncertain points and off-route threshold" are numbers that can be automated. If we set those types of things during initialization, we make it unclear why they'd change during runtime. They are also different based on what region you're in.

**Comment by kmadsen** [comment]
We're already talking about bucketing all these configurations under a `mobile`/`auto` umbrella.

I think we want something in between. Not quite as broad as mobile vs auto, and not as specific as uncertain points.
