### ISSUE TITLE
Investigate routes blinking when selecting alternatives

### ISSUE THREAD

**Issue by Guardiola31337** [mapbox/mapbox-navigation-android#2473]
As commented in https://github.com/mapbox/mapbox-navigation-android/pull/2452#pullrequestreview-357761000

Noticed a blinking behavior when switching routes when running the [`SimpleMapboxNavigationKt`](https://github.com/mapbox/mapbox-navigation-android/blob/master/examples/src/main/java/com/mapbox/navigation/examples/activity/SimpleMapboxNavigationKt.kt) example from the `examples` test app 👀 

![simple_mapbox_navigation_kt_leak](https://user-images.githubusercontent.com/1668582/74373872-4aecca00-4dab-11ea-8de0-1b5ff891436a.gif)

Thought that was fixed in https://github.com/mapbox/mapbox-navigation-android/pull/2262

Maybe a different setup for `SimpleMapboxNavigationKt`?

cc @LukasPaczos @kmadsen

**Comment by Guardiola31337** [comment]
Maybe we can fix as part of https://github.com/mapbox/mapbox-navigation-android/pull/2464? cc @RingerJK

**Comment by RingerJK** [comment]
@Guardiola31337 I'll take a look, but if it leads to make huge changes better do fix in separate PR

**Comment by LukasPaczos** [comment]
The issue is with a way we set the `DirectionsRoute` into the legacy `NavigationMapRoute`. Right now, we're calling `navigationMapRoute?.addRoutes(routes)` which is going to completely redraw the layers.

`NavigationMapRoute#addRoutes` should internally check if the provided `DirectionsRoute`s references are the same but the in a different order and only change the underlying `GeoJsonSource`s instead of always redrawing all of the layers.

**Comment by Guardiola31337** [comment]
@RingerJK 
> I'll take a look, but if it leads to make huge changes better do fix in separate PR

Of course! I wanted to put this on your radar so you could 👀 as you're working on https://github.com/mapbox/mapbox-navigation-android/pull/2464 🍍

**Comment by Guardiola31337** [comment]
> The issue is with a way we set the `DirectionsRoute` into the legacy `NavigationMapRoute`. Right now, we're calling `navigationMapRoute?.addRoutes(routes)` which is going to completely redraw the layers.
>
> `NavigationMapRoute#addRoutes` should internally check if the provided `DirectionsRoute`s references are the same but the in a different order and only change the underlying `GeoJsonSource`s instead of always redrawing all of the layers.

That makes sense. Thanks for clarifying @LukasPaczos 🙇
