### ISSUE TITLE
Potential for NPE in RouteLegProgress.kt

### ISSUE THREAD

**Issue by cafesilencio** [mapbox/mapbox-navigation-android#2482]
Looking at RouteLegProgress.kt lines 220 and 221 there's an assumption that two variables won't be null.
...
            currentStepProgress = RouteStepProgress.Builder()
                .step(currentStep!!)
                .distanceRemaining(stepDistanceRemaining!!)
                .build()
...

However since this is a builder there's nothing enforcing those fields to be non-null. They are not required in a constructor for example.

Looking at the RouteProgress class on lines 341 through 351 it can be seen that there's a nonNull check for the currentStep value and if non-null it's added to the RouteLegProgress builder else not. If that variable were to be null then the build() call on line 351 of RouteProgress would result in an NPE.

I don't have enough context to know if the  RouteStepProgress.Builder() actually requires the two fields (step and distanceRemaining) or if it's a typo.  I don't want to just remove the double bang without knowing. Can somebody with more context on the SDK take a look at this?

If "step" and "distanceRemaining" are required values in RouteLegProgress we should not allow them to be nullable in the builder but instead require them as non-null in a constructor.

If I write a test like:

  @Test
  public void build_when_currentStepNull() {
    new RouteProgress.Builder().build();
  }

I get:
kotlin.KotlinNullPointerException
	at com.mapbox.services.android.navigation.v5.routeprogress.RouteLegProgress$Builder.build(RouteLegProgress.kt:220)

**Comment by Guardiola31337** [comment]
Where are we here @cafesilencio?

**Comment by cafesilencio** [comment]
Looking at this closer now, I was looking at the version of this in the legacy code. There is a check in the legacy version of RouteProgress for a null step.

The current version of the RouteLegProgress has a different structure and appears to correctly handle a null condition for the step.
