### ISSUE TITLE
MapboxNavigation. Camera issue

### ISSUE THREAD

**Issue by RingerJK** [mapbox/mapbox-navigation-android#2483]
Navigation Camera [previously](https://github.com/mapbox/mapbox-navigation-android/blob/v0.42.4/libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/MapboxNavigation.java#L62) was stored into `NavigationEngineFactory`. From version 1.0 it's not exist. 

Looks like a camera should exist for each `MapboxNavigation` as 1:1, but it's a part of UI component and implementation should live into _ui module_. So suggestion is make next changes `interface/abstract class Camera` -> `base module` and `implementation of CameraX` -> `ui module`

**cc** @LukasPaczos @Guardiola31337 

will be available after [pr](https://github.com/mapbox/mapbox-navigation-android/pull/2464) will be merged

**Comment by LukasPaczos** [comment]
The camera has nothing to do with core, I think it was just a general technical debt. It shouldn't live in `base`, it should only be a part of UI library, and we'll need to make it happen during the compatibility refactor.

**Comment by Guardiola31337** [comment]
@abhishek1508 @cafesilencio are we good to close here? https://github.com/mapbox/mapbox-navigation-android/pull/2513 landed. Are we missing something?

**Comment by cafesilencio** [comment]
work done in #2513
