### ISSUE TITLE
Test application(app module). NavigationLauncherActivity fix flow

### ISSUE THREAD

**Issue by RingerJK** [mapbox/mapbox-navigation-android#2484]
`NavigationLauncherActivity` is started from `MainActivity`. 
Flow is broken: 
- have possibility to chose 2 _waypoints_ but nothing is happening. No crashes. 
- (if needed) `Milestones` were removed from the SDK. Need change source of data for next maneuver(usually to `RouteProgress`)

will be available after [pr](https://github.com/mapbox/mapbox-navigation-android/pull/2464) will be merged

**Comment by Guardiola31337** [comment]
Closing here as we're going to deprecate `NavigationLauncher` in `1.0`.
