### ISSUE TITLE
[Android UI] Migrate EmbeddedNavigationActivity

### ISSUE THREAD

**Issue by RingerJK** [mapbox/mapbox-navigation-android#2489]
Based on the proposal https://github.com/mapbox/mapbox-navigation-android/pull/2464#pullrequestreview-361299376 and https://github.com/mapbox/mapbox-navigation-android/pull/2500 we need to migrate EmbeddedNavigationActivity from `app` to `examples`.

**Comment by skamal16** [comment]
@abhishek1508 I can't seem to find this file anywhere, has it been migrated? Can someone link me to this?

**Comment by stevenm69** [comment]
--
Sent from Mail.ru app for Android Thursday, 24 December 2020, 06:33AM -05:00 from Syed Anas Kamal  notifications@github.com :
