### ISSUE TITLE
Navigation fails to reroute after a U-Turn

### ISSUE THREAD

**Issue by Snipedown** [mapbox/mapbox-navigation-android#249]
After a U-Turn, the puck continues to point in the old direction and the route just extends back out, when it should reroute now that you are facing a new direction.

Edit: I forgot to mention that it eventually rerouted when I passed over a "possible turn" as in an actual road that can be turned on instead of like a driveway. This may be some NavigationConstant I can change, but I was driving the "wrong" way for 40+ seconds and the puck was backwards, so I figured it may be a bug.

**Comment by Grsmto** [comment]
I can confirm this after some testing in real-world yesterday.
I'm not sure the U-turn case has been handled in the off-route logic.
The puck not rotating is probably not directly related tho.

**Comment by mf-mindcrewtech** [comment]
@Snipedown same issue here, did you find any solution?

**Comment by Snipedown** [comment]
@mf-mindcrewtech Nope, I just informed my users that the possibility was there. It's not often they do U-Turns so it wasn't a super big deal to me.

**Comment by cammace** [comment]
Good news, the u-turn off-route logic has been added in https://github.com/mapbox/mapbox-navigation-android/pull/312 and https://github.com/mapbox/mapbox-navigation-android/pull/302. Let me know if you guys run into issues and I'll reopen this ticket.
