### ISSUE TITLE
[Android UI] Migrate ComponentNavigationActivity

### ISSUE THREAD

**Issue by RingerJK** [mapbox/mapbox-navigation-android#2491]
Based on the proposal https://github.com/mapbox/mapbox-navigation-android/pull/2464#pullrequestreview-361299376 and https://github.com/mapbox/mapbox-navigation-android/pull/2500 we need to migrate ComponentNavigationActivity from `app` to `examples`.

**Comment by JunDai** [comment]
I am looking into this one.

**Comment by JunDai** [comment]
working on some higher priority task. removing this assignment for now.
