### ISSUE TITLE
[Android] Introduce RouteTileDownload API in core

### ISSUE THREAD

**Issue by RingerJK** [mapbox/mapbox-navigation-android#2493]
OfflineRegionDownloadActivity is broken. No Api for this flow. 
Flow should be following: select zone on map and download to device. 
Need to sync with @mapbox/navnative team if we provide(or gonna provide) this opportunity. 

will be available after [pr](https://github.com/mapbox/mapbox-navigation-android/pull/2464) will be merged

**Comment by mskurydin** [comment]
@RingerJK , could you provide more info about which APIs of nav native we are relying on?

**Comment by RingerJK** [comment]
So it's depends of if we'd like to provide this API to customers. I'm not sure about it. Expose smth easier than hide, so may be sdk doesn't need it for v 1.0. wdyt @zugaldia @Guardiola31337 ?

**Comment by zugaldia** [comment]
cc: @Aurora-Boreal

**Comment by JunDai** [comment]
@Guardiola31337 - I checked this issue, it's not something will block #2464 to merge. As @RingerJK mentioned, we just don't have RouteTileDownload api in the core SDK, so this example `OfflineRegionDownloadActivity` flow is broken. Once we have the related api implemented, we could add `OfflineRegionDownloadActivity` back to work.

**Comment by Guardiola31337** [comment]
Are we good to close then @JunDai @RingerJK? Feel free to do so if needed.

**Comment by RingerJK** [comment]
We're good to close it
