### ISSUE TITLE
Directions banner displays initial step after navigating through waypoints

### ISSUE THREAD

**Issue by sansumbrella** [mapbox/mapbox-navigation-android#2495]
**Android API:**
min: 24
target: 28
**Mapbox Navigation SDK version:**
`mapbox-android-navigation-ui:0.42.5`

### Steps to trigger behavior

 1. Create a route with at least one waypoint after an instruction
 2. Simulate route playback (or start traveling for real)
 3. Arrive at a waypoint

Complete application sample code is available in the details pane (omitting gradle config and other project settings):
<details>
<pre>
package com.mapbox.davidwicks.mapboxnavigationdemo

import android.graphics.Path
import androidx.appcompat.app.AppCompatActivity
import android.os.Bundle
import android.util.Log
import com.mapbox.api.directions.v5.models.DirectionsResponse
import com.mapbox.api.directions.v5.models.DirectionsRoute
import com.mapbox.geojson.Point
import com.mapbox.mapboxsdk.Mapbox
import com.mapbox.services.android.navigation.ui.v5.NavigationLauncher
import com.mapbox.services.android.navigation.ui.v5.NavigationLauncherOptions
import com.mapbox.services.android.navigation.v5.navigation.NavigationRoute
import retrofit2.Call
import retrofit2.Response

class MainActivity : AppCompatActivity() {

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)
        requestRoute()
        Log.i("NavigationDemo", "Getting started with the main activity")
    }

    data class Waypoint(val position: Point, val name: String)

    val waypoints = arrayOf(
        Point.fromLngLat(-77.038294672966, 38.91854721860871),
        Point.fromLngLat(-77.03662633895874, 38.91920249133305),
        Point.fromLngLat(-77.03660779663086, 38.9182091456012),
        Point.fromLngLat(-77.03660052546692, 38.91565476415369),
        Point.fromLngLat(-77.03664779663086, 38.91398518410977),
        Point.fromLngLat(-77.03661561012268, 38.913726395687185),
        Point.fromLngLat(-77.03665852546692, 38.91345925826118),
        Point.fromLngLat(-77.03665852546692, 38.91270792885979)
    )
    val names = arrayOf(
        "animal", // origin
        "ocelot",
        "bear",
        "cat",
        "dog",
        "elephant",
        "frog",
        "goat" // destination
    )

    fun requestRoute() {
        val builder = NavigationRoute.builder(this)
            .accessToken(getString(R.string.MAPBOX_ACCESS_TOKEN))
            .origin(waypoints.first())
            .destination(waypoints.last())
            .continueStraight(false)
            .profile("driving")

        for (i in 1 until waypoints.lastIndex) {
            builder.addWaypoint(waypoints[i])
        }
        builder.addWaypointNames(*names)

        val route = builder.build()
        route
            .getRoute(object : retrofit2.Callback<DirectionsResponse> {
                override fun onResponse(
                    call: Call<DirectionsResponse>,
                    response: Response<DirectionsResponse>
                ) {
                    if (response.isSuccessful) {
                        Log.i(
                            "NavigationDemo",
                            "Route generation maybe happened: ${response.body()?.code()}"
                        )
                        val route = response.body()?.routes()?.first()
                        route?.let {
                            startNavigation(route)
                        }
                    } else {
                        Log.e(
                            "NavigationDemo",
                            "Route generation failed: ${response.errorBody()?.string()}"
                        )
                    }

                }

                override fun onFailure(call: Call<DirectionsResponse>, t: Throwable) {
                    Log.e("NavigationDemo", "Unable to generate route ${t.message}")
                }
            })
    }

    fun startNavigation(route: DirectionsRoute) {
        Mapbox.getInstance(this, getString(R.string.MAPBOX_ACCESS_TOKEN))
        val simulateRoute = true

        val options = NavigationLauncherOptions.builder()
            .directionsRoute(route)
            .shouldSimulateRoute(simulateRoute)
            .build()

        NavigationLauncher.startNavigation(this, options)
    }
}
</pre>
</details>

### Expected behavior

The directions banner shows the waypoint information until the next instruction is needed, at which point it shows the following instruction.

### Actual behavior

After briefly displaying the waypoint information, the directions banner reverts to the first instruction in the entire navigation sequence.

[The behavior is demonstrated in this video](https://github.com/mapbox/mapbox-navigation-android/files/4220802/directions-resetting.mp4.zip) and was observed during both actual driving and simulated navigation.

**Comment by AntJones85** [comment]
@andrewychen @zugaldia can we add this to @mapbox/navigation team's focus?

cc' @sansumbrella

**Comment by cafesilencio** [comment]
Using the code provided I can confirm the behavior described. When arriving at a named waypoint the top banner will show the name of the waypoint that is being arrived at. After arriving the top banner will change to the name of the first waypoint arrived at. This is repeated at each waypoint.

**Comment by cafesilencio** [comment]
This looks like an issue in nav. native. I created an issue for them here:  https://github.com/mapbox/mapbox-navigation-native/issues/926

**Comment by Guardiola31337** [comment]
Any updates here @cafesilencio?

cc'ing @RingerJK as he has been working recently on checking waypoints feature.

**Comment by cafesilencio** [comment]
@Guardiola31337 no updates from me. I tested this with the version reported but at the time the feature wasn't ready in the core. Needs testing.

**Comment by cafesilencio** [comment]
Tested this with our soon to be released 1.0 SDK and the banner displays the waypoint name upon arrival and when continuing navigation to the next waypoint the banner displays the next navigation instruction.

**Comment by zugaldia** [comment]
@cafesilencio Thank you for keeping this ticket updated - does that mean that we're good to close here?

**Comment by cafesilencio** [comment]
I believe we're good to close.
