### ISSUE TITLE
Add unit test for MapboxTimer

### ISSUE THREAD

**Issue by Guardiola31337** [mapbox/mapbox-navigation-android#2497]
Follow up from https://github.com/mapbox/mapbox-navigation-android/pull/2462#issuecomment-587169345

> `fasterRoute_timerStartedOnce` should not be concern of `MapboxNavigation` or `MapboxDirectionSession`. All they should do is call `start` on the timer and timer should be responsible to check if it is being started once or multiple times. `MapboxTimerTest` doesn't exist at the moment, hence I am going to cut a ticket for it.

cc @abhishek1508

**Comment by Guardiola31337** [comment]
This was addressed in https://github.com/mapbox/mapbox-navigation-android/pull/2499 Are we missing any follow up work? Are we good to close here? @cafesilencio @abhishek1508

**Comment by cafesilencio** [comment]
I think it's good to close. The work has been merged.

**Comment by Guardiola31337** [comment]
Thanks for confirming @cafesilencio 

Closing.
