### ISSUE TITLE
Examples module. Feedback flow fix

### ISSUE THREAD

**Issue by RingerJK** [mapbox/mapbox-navigation-android#2507]
Provide Feedback through Telemetry Sdk. Now it's at `FeedbackBottomSheet`

Blocked by issue(need link to it), [PR](https://github.com/mapbox/mapbox-navigation-android/pull/2445)

**Comment by Guardiola31337** [comment]
@RingerJK @abhishek1508 where are we here? Events PR already landed unblocking this. I remember that @JunDai worked on Feedback integration, did you also added support to the UI SDK?

**Comment by abhishek1508** [comment]
@JunDai I will let you comment on this

**Comment by Guardiola31337** [comment]
Missing work seems is moving here https://github.com/mapbox/mapbox-navigation-android/pull/2799 right @JunDai?

**Comment by JunDai** [comment]
> Provide Feedback through Telemetry Sdk. Now it's at FeedbackBottomSheet

@RingerJK - what did you mean **Now it's at FeedbackBottomSheet**? 

My understanding is to use the new Telemetry SDK to send Feedback. If so, I think even without #2799 we already sent the feedback through Telemetry SDK. 
See: https://github.com/mapbox/mapbox-navigation-android/blob/master/libnavigation-ui/src/main/java/com/mapbox/navigation/ui/NavigationViewModel.java#L223-L224

Please let me know if I miss something. cc: @Guardiola31337

**Comment by RingerJK** [comment]
@JunDai I think that issue was created because feedback flow on start activity was broken so if it works, issue should be closed

**Comment by Guardiola31337** [comment]
Are we good to close then @JunDai @RingerJK? Feel free to do so if needed.

**Comment by JunDai** [comment]
Now I don't see issue here, let's close it for now.
@RingerJK - feel free to reopen it, if you still see issue.
