### ISSUE TITLE
Zero bearing in freedrive mode without navigation tiles

### ISSUE THREAD

**Issue by kwetril** [mapbox/mapbox-navigation-android#2544]
**Mapbox Navigation SDK version**: commit hash sum - 5435c2d712d4a595fffc2c827a6634f83bb67a3d

### Steps to trigger behavior

 1. Create navigator object
 2. call updateLocation 
 3. call getStatus() - position.bearing is 0

### Expected behavior

When there is no tiles - bearing should be taken from FixLocation provided in update.

**Comment by kwetril** [comment]
![image](https://user-images.githubusercontent.com/3581990/76069270-ab82b780-5fa3-11ea-9ae8-e86d5728e0ca.png)

**Comment by mskurydin** [comment]
@kwetril , we should use mapbox-navigation-native project for these issues.
