### ISSUE TITLE
Sample project outdated

### ISSUE THREAD

**Issue by P-Zenker** [mapbox/mapbox-navigation-android#255]
Hey,

I've downloaded your [sample project](https://github.com/mapbox/mapbox-navigation-android/tree/master/navigation/app/src/main/java/com/mapbox/services/android/navigation/testapp/activity) today. 

There are two outdated methods in NavigationMetricsWrapper:

`Error:(13, 66) error: method buildArriveEvent in class MapboxNavigationEvent cannot be applied to given types;
required: String,String,String,double,double,String,String,int,int,int,Date,int,boolean,String,String,String,int,int,String,int,int
found: String,String,String,double,double,String,String,int,int,int,Date,int,int,int,boolean,<null>,<null>,String,int,int,<null>,int,int
reason: actual and formal argument lists differ in length
Error:(48, 66) error: method buildDepartEvent in class MapboxNavigationEvent cannot be applied to given types;
required: String,String,String,double,double,String,String,int,int,int,boolean,String,String,String,int,int,String,int,int
found: String,String,String,double,double,String,String,int,int,int,boolean,<null>,<null>,String,int,int,<null>,int,int,int,int,int,Date
reason: actual and formal argument lists differ in length`

To run the project I just commended the lines in the two methods out. But this shouldn't be the solution ;) 

Best regards
Patrick

**Comment by cammace** [comment]
Juggling between projects, I made some param changes which broke the methods originally, should be fixed in the latest Snapshot and on the master branch.
