### ISSUE TITLE
com.mapbox.core.exceptions.ServicesException

### ISSUE THREAD

**Issue by JayJiangCT** [mapbox/mapbox-navigation-android#2550]
**Android API:** Samsung Tablet Api 29
**Mapbox Navigation SDK version:** 0.42.3

### Steps to trigger behavior

 1. Open navigation example, input my current location and destination, start navigation.
 2. The App crashed while I was on myu way , I check the crash logs in bugsnag. It occurs more frequently when the distance between the two locations is relatively long.
 3.  I checked the crash logs in bugsnag, it shows: com.mapbox.core.exceptions.ServicesException,
Waypoints must contain indices of the first and last coordinates.

### Expected behavior
The navigation works normally when I was driving to my destination.
### Actual behavior
A crash happened and I check my codes, it is as same as official navigation demo. Using same codes of EmbeddedNavigationActivity.

**Comment by Guardiola31337** [comment]
Hey @JayJiangCT 👋 thanks for reaching out.

Could you add some more information for reproducing the behavior you're describing or any other specifics around your setup? If there is any sample of `EmbeddedNavigationActivity` or stacktrace you can provide, that would be really helpful and it'll give us better insight into your implementation and what could be causing your problem.

Is this an issue in the `1.0` SDK @RingerJK?

**Comment by RingerJK** [comment]
We have similar problem with indices in 1.0 but it doesn't throw exception. Moreover, in examples for `1.0` we don't use `Waypoint Indices` at all. I think current issue is for pre `1.0` only
