### ISSUE TITLE
Real position outside of LatLngBounds after route calculation (Drop-in UI)

### ISSUE THREAD

**Issue by P-Zenker** [mapbox/mapbox-navigation-android#257]
Hey,

I've downloaded your [sample project](https://github.com/mapbox/mapbox-navigation-android/tree/master/navigation/app/src/main/java/com/mapbox/services/android/navigation/testapp/activity) today.

Running on a Google Nexus 6 (Android 7.1.1  | 2560 x 1440 | 5,96 Zoll (large) | 493 (xxxhdpi)) or on a Ulefone Be Touch 2 (Android 5.1 | 1920 x 1080 | 5,5 Zoll (large)) the Navigation View (Drop-in UI) looks like this, after a route is calculated:

![2017-09-21 14 20 10](https://user-images.githubusercontent.com/23097192/30696413-d86fbb8e-9edb-11e7-91b6-219673393083.jpg)

As you can see, the real position is a bit further away:

![2017-09-21 14 20 14](https://user-images.githubusercontent.com/23097192/30696485-09a83e92-9edc-11e7-8fe7-6b5c92f30554.jpg)

My suggestion is to include either the real position (but then the route start position could be outside of the bounding-box) or to add the real position to the bounding-box too.

PS: 
I've made more tests:
Samsung Galaxy S3 (GT-I9300) (Android 4.3 | 1280 x 720 | 4,8 Zoll (large) | 306 (hdpi)) -> bounding box is fine

![2017-09-21 16 32 34](https://user-images.githubusercontent.com/23097192/30701532-c4737698-9eea-11e7-8290-c95e115e99d5.jpg)

MOBISTEL Cynus E4 (Android 5.1 | 800 x 480 | 4 Zoll (normal) | 240 (hdpi)) (similar behaviour with Samsung Galaxy S3 mini (GT-I8200N) | 4.2.2)

![2017-09-21 16 33 03](https://user-images.githubusercontent.com/23097192/30701526-bf3f6362-9eea-11e7-8149-82230c1bc214.gif)

Best regards,
Patrick

**Comment by cammace** [comment]
Hey Patrick, thanks for checking out the testapp sample. I assume you are speaking about the camera zooming in too close? The screen you are referring to wasn't actually built out inside the SDK. In the future, we plan to offer an Overview screen for navigation which will handle viewing the entire route and giving the options one would desire before starting a navigation session.

**Comment by P-Zenker** [comment]
> camera zooming in too close
Yes.

Ok, great!
