### ISSUE TITLE
addProgresChangeListener not working

### ISSUE THREAD

**Issue by andreolikalcopoli** [mapbox/mapbox-navigation-android#2589]
**Android API:**
**Mapbox Navigation SDK version:**

### Steps to trigger behavior

 1. Try to use data from the MapBox site for Route Progress. 
 2. I am using NavigationMapRoute.addProgressChangeListener and every time it displays it cannot be applied

```
navigationMapRoute.addProgressChangeListener(new ProgressChangeListener() {
            @Override
            public void onProgressChange(Location location, RouteProgress routeProgress) {
                
            }
        });
```

my code

### Not getting anything

**Comment by Guardiola31337** [comment]
@abhishek1508 @cafesilencio could we check if this would be an issue in `1.0`?

**Comment by cafesilencio** [comment]
Referring to version 1.0 SDK:

The NavigationMapRoute.addProgressChangeListener takes a MapboxNavigation instance as an argument so I'm going to assume @andreolikalcopoli meant MapboxNavigation.registerRouteProgressObserver ( as it's called in the 1.0 SDK )

I tested with the [NavigationMapRouteActivity](examples/src/main/java/com/mapbox/navigation/examples/core/NavigationMapRouteActivity.java) example. 

If I add the snippet below to that activity I can see the logging message.
`mapboxNavigation.registerRouteProgressObserver(new RouteProgressObserver() {
  @Override
  public void onRouteProgressChanged(@NotNull RouteProgress routeProgress) {
    Timber.e("*** in tunnel " + routeProgress.getInTunnel());
  }
});
`

**Comment by Guardiola31337** [comment]
I think @andreolikalcopoli was referring to

```java
  /**
   * This method will allow this class to listen to new routes based on
   * the progress updates from {@link MapboxNavigation}.
   * <p>
   * If a new route is given to {@link MapboxNavigation#startNavigation(DirectionsRoute)}, this
   * class will automatically draw the new route.
   *
   * @param navigation to add the progress change listener
   */
  public void addProgressChangeListener(MapboxNavigation navigation) {
    this.navigation = navigation;
    navigation.addProgressChangeListener(mapRouteProgressChangeListener);
  }
```

from the legacy which BTW is still available in `1.0`

```java
  /**
   * This method will allow this class to listen to new routes based on
   * the progress updates from {@link MapboxNavigation}.
   * <p>
   * If a new route is given to {@link MapboxNavigation#startTripSession()}, this
   * class will automatically draw the new route.
   *
   * @param navigation to add the progress change listener
   */
  public void addProgressChangeListener(MapboxNavigation navigation) {
    this.navigation = navigation;
    navigation.registerRouteProgressObserver(mapRouteProgressChangeListener);
  }

  /**
   * This method will allow this class to listen to new routes based on
   * the progress updates from {@link MapboxNavigation}.
   * <p>
   * If a new route is given to {@link MapboxNavigation#startTripSession()}, this
   * class will automatically draw the new route.
   *
   * @param navigation to add the progress change listener
   * @param vanishRouteLineEnabled determines if the route line should vanish behind the puck.
   */
  public void addProgressChangeListener(MapboxNavigation navigation, boolean vanishRouteLineEnabled) {
    this.navigation = navigation;
    this.vanishRouteLineEnabled = vanishRouteLineEnabled;
    this.mapRouteProgressChangeListener = buildMapRouteProgressChangeListener();
    navigation.registerRouteProgressObserver(mapRouteProgressChangeListener);
  }
```

**Comment by abhishek1508** [comment]
@cafesilencio Can we verify this since you have already taken a first pass on this.

**Comment by cafesilencio** [comment]
I'm not sure @Guardiola31337 if you look at the code snippet submitted he's instantiating a ProgressChangeListener so it seems like he wants to register his own listener. 

Both NavigationMapRoute.addProgressChangeListener(MapboxNavigation navigation)  and MapboxNavigation.registerRouteProgressObserver(new RouteProgressObserver()) are working when I test with the 1.0 SDK so perhaps  @andreolikalcopoli  can utilize the 1.0 SDK when it's released and provide an update.

**Comment by cafesilencio** [comment]
This issue cannot be reproduced in 1.0. Please be on the lookout for our first public preview of UI SDK v1.0 coming soon. Feel free to create a new issue if you feel it still exists.
