### ISSUE TITLE
Expose automatic reroute NavigationOption

### ISSUE THREAD

**Issue by LukasPaczos** [mapbox/mapbox-navigation-android#2591]
Currently, in the Nav Core 1.0 the reroute request is sent automatically. We should document this and expose an option that disables this feature.

Possibly, we could expose the utilities that parse route options (adjusts waypoints) and do not reroute internally by default. Any thoughts @mapbox/navigation-android?

**Comment by Guardiola31337** [comment]
Has this been addressed by https://github.com/mapbox/mapbox-navigation-android/pull/3184? Good to close here? @LukasPaczos @RingerJK

**Comment by LukasPaczos** [comment]
Yes, the `RerouteController` should do just fine to cover this use-case.
