### ISSUE TITLE
Map not loading in few example activities

### ISSUE THREAD

**Issue by abhishek1508** [mapbox/mapbox-navigation-android#2625]
Map doesn't load in `RerouteActivity` and `GuidanceViewActivity`.

![screen](https://user-images.githubusercontent.com/3021882/78941365-64895580-7a6c-11ea-9841-79dece889066.png)

**Comment by Guardiola31337** [comment]
@abhishek1508 should we close here as #2626 landed?

**Comment by Guardiola31337** [comment]
I'm still getting a blank map when loading [`GuidanceViewActivity`](https://github.com/mapbox/mapbox-navigation-android/blob/master/examples/src/main/java/com/mapbox/navigation/examples/core/GuidanceViewActivity.kt) 👀 

![blank_map_guidance_activity](https://user-images.githubusercontent.com/1668582/77940151-4199bd00-7286-11ea-86de-b3b614b993d8.gif)

Reopening.

cc @abhishek1508

**Comment by Guardiola31337** [comment]
Now it seems it's working, so probably an issue with the Directions endpoint / token used in that example.

In any case, I know this https://github.com/mapbox/mapbox-navigation-android/blob/165b7bcfefb95e9486af6d408abcd6bc3f2e8168/examples/src/main/java/com/mapbox/navigation/examples/core/GuidanceViewActivity.kt#L171-L172 but we shouldn't hardcode any access token in the public repo. Let's remove it.

**Comment by kmadsen** [comment]
Here ya go! https://github.com/mapbox/mapbox-navigation-android/pull/2744
