### ISSUE TITLE
release v0.6

### ISSUE THREAD

**Issue by cammace** [mapbox/mapbox-navigation-android#263]
This ticket tracks the release of Mapbox Android Navigation SDK `v0.6.0`. This brings significant performance improvements, the first iteration of navigation UI, and several bug fixes

### Highlights
* First iteration of the Navigation UI
* Optimized Navigation features which were causing slowdowns on long steps -
 [219](https://github.com/mapbox/mapbox-navigation-android/pull/219)
* Only decode step geometry when needed - [215](https://github.com/mapbox/mapbox-navigation-android/pull/215)
* Introduced metrics
* Cleaned up code and fixed several bugs

### Release checklist @cammace

- [x] Make sure latest translation are added
- [x] Run through testapp/demo app and test all activities
- [x] Change version name to `0.6.0` in `gradle.properties`
- [x] Publish `0.6.0` artifact to Maven Central
- [x] Change version name back to `0.7.0-SNAPSHOT`
- [x] Update `CHANGELOG.md`
- [x] Tag `v0.6.0` in GitHub

### Post-release @langsmith

- [x] Update `README.md`
- [x] Generate Javadoc
- [x] Update `constants.js` file in `android-docs` repo

/cc: @mapbox/navigation

**Comment by Danny-James** [comment]
I'm Now Using The Following Dependencies 
`
compile 'com.mapbox.mapboxsdk:mapbox-android-navigation:0.7.0-SNAPSHOT'
`
`
compile 'com.mapbox.mapboxsdk:mapbox-android-navigation-ui:0.7.0-SNAPSHOT@aar'
`

When i select the recentre button the Navigation UI doesn't change it seems the ReCentre button has broken.

**Comment by zugaldia** [comment]
@Danny-James Thanks for the report and sorry to hear that you're hitting an issue. Would you mind opening a separate ticket (https://github.com/mapbox/mapbox-navigation-android/issues/new)? It'd be helpful if you could also include some code snippet or small example that we could use to reproduce the problem.

**Comment by Danny-James** [comment]
@zugaldia Im hitting all sorts of problems which i have already listed as an issue, but currently had no replies, [#10030](https://github.com/mapbox/mapbox-gl-native/issues/10030).

I'll log the other issues now.
