### ISSUE TITLE
Include 1.0 Codecov reports to Github PR checks

### ISSUE THREAD

**Issue by Guardiola31337** [mapbox/mapbox-navigation-android#2655]
Include `1.0` Codecov reports to Github PR checks as we do in the legacy https://github.com/mapbox/mapbox-navigation-android/blob/a902f4f46bad0c6cefe64d4e9000785ec1f57881/circle.yml#L393

Follow up from https://github.com/mapbox/mapbox-navigation-android/pull/2652#pullrequestreview-381999099

**Comment by Guardiola31337** [comment]
cc @LukasPaczos

**Comment by abhishek1508** [comment]
Not going to address it for now as priorities have been shifted towards refactoring UI
