### ISSUE TITLE
Expose Maps SDK via 1.0.0 Nav UI SDK

### ISSUE THREAD

**Issue by langsmith** [mapbox/mapbox-navigation-android#2656]
### Steps to trigger behavior

 1. Add the 1.0.0 Nav UI SDK
 2. Try to use [the Mapbox Maps SDK for Android](https://docs.mapbox.com/android/maps/overview/)

### Expected behavior

Expected to have access to Maps SDK files.

### Actual behavior

No access to Maps SDK. 

<img width="524" alt="Screen Shot 2020-03-26 at 10 10 48 AM" src="https://user-images.githubusercontent.com/4394910/77675361-16436500-6f4a-11ea-84c3-e0702e9eaf60.png">

<img width="533" alt="Screen Shot 2020-03-26 at 10 11 22 AM" src="https://user-images.githubusercontent.com/4394910/77675419-278c7180-6f4a-11ea-8db8-2e0fe0ea74dc.png">

**Comment by Guardiola31337** [comment]
Fixed in https://github.com/mapbox/mapbox-navigation-android/pull/2831

Closing here.

cc @abhishek1508
