### ISSUE TITLE
Rename updateLocationLayerRenderMode() method?

### ISSUE THREAD

**Issue by langsmith** [mapbox/mapbox-navigation-android#2658]
Ticketing my suggestion that `NavigationMapboxMap`'s `updateLocationLayerRenderMode()` method be renamed: https://github.com/mapbox/mapbox-navigation-android/blob/master/libnavigation-ui/src/main/java/com/mapbox/navigation/ui/map/NavigationMapboxMap.java#L316

The mention of layer in the name probably comes from [the long-deprecated Location Layer plugin](https://docs.mapbox.com/android/plugins/overview/location-layer)

Maybe `updateLocationRenderMode()` or `updateLocationComponentRenderMode()` instead?

**Comment by JunDai** [comment]
@langsmith - although the `location layer plugin` has been deprecated. I looked at the `LocationComponent` code, it's calling a `locationLayerController` inside. Any reason why we want to rename it?
```java
  public void setRenderMode(@RenderMode.Mode int renderMode) {
    checkActivationState();
    locationLayerController.setRenderMode(renderMode);
    updateLayerOffsets(true);
    updateCompassListenerState(true);
  }

**Comment by langsmith** [comment]
Yea, I guess there are leftover remnants even within the `LocationComponent`. Going to close this ticket. It's fine as is.

**Comment by JunDai** [comment]
thanks 👍
