### ISSUE TITLE
Support metric units (meters/kilometers)

### ISSUE THREAD

**Issue by ericrwolfe** [mapbox/mapbox-navigation-android#266]
The SDK should support metric units for distances in meters + kilometers in addition to miles.

Initially, this should be as simple as adding an explicit bool/enum that users can change for metric vs imperial.

Later, the SDK could try to infer units of measure based on the provided locale (but still allow the above unit override).

cc @danesfeder

**Comment by 1ec5** [comment]
Note that the default units should depend on the country code, not the language code, in the locale. Also, the UK uses miles, yards, and feet despite generally being on the metric system. (There doesn't need to be a separate option for yards; just treat the UK like the U.S. but special-case it to use yards.)

**Comment by danesfeder** [comment]
@1ec5 So you guys default to Imperial for US, UK (yards), Liberia, Burma, then every other Locale is metric?  Defaults are ignored when this is set as an option launching the UI

**Comment by 1ec5** [comment]
The iOS navigation SDK relies on the system’s locale (language+script+country) to [tell us](https://developer.apple.com/documentation/foundation/nslocalemeasurementsystem) whether it would naturally use `U.S.` 🇺🇸🇱🇷🇲🇲, `U.K.` 🇬🇧, or `Metric` (everywhere else). mapbox/mapbox-navigation-ios#589 tracks exposing an option that the developer can hook up to a settings UI to override this default behavior.

Under the hood, iOS uses [CLDR](http://cldr.unicode.org/) to determine [which measurement system](https://unicode.org/cldr/trac/browser/trunk/common/supplemental/supplementalData.xml?rev=13744#L4758) to report for a particular locale and [which units to use](https://unicode.org/cldr/trac/browser/trunk/common/supplemental/supplementalData.xml?rev=13744#L4826) when measuring road distances in a particular measurement system.

**Comment by jameslshannon** [comment]
It should always be possible to override the units - for instance cyclists in the UK commonly prefer metric units and navigation instructions. Ideally the locale default could therefore be overridden via MapboxNavigationOptions so the user could configure in their app?

**Comment by 1ec5** [comment]
Agreed. This is what we’re tracking on iOS in mapbox/mapbox-navigation-ios#589, and it would be good to have parity on Android with that feature.

**Comment by danesfeder** [comment]
Support for metric landed for both core navigation and the drop-in UI in #500 and #521
