### ISSUE TITLE
Remove unnecessary NN Proguard rules

### ISSUE THREAD

**Issue by Guardiola31337** [mapbox/mapbox-navigation-android#2663]
Tailwork from https://github.com/mapbox/mapbox-navigation-android/pull/2643#discussion_r398245221

Remove unnecessary NN Proguard rules from `libnavigator/proguard-rules.pro` when added downstream.

cc @mskurydin @SiarheiFedartsou @RingerJK

**Comment by RingerJK** [comment]
Fix will be available in next NN release(`11.0.0`+)
