### ISSUE TITLE
Fix RouteProgress durationRemaining when there are 2 or more legs

### ISSUE THREAD

**Issue by kmadsen** [mapbox/mapbox-navigation-android#2665]
**Mapbox Navigation SDK version:** 1.0.0

https://github.com/mapbox/mapbox-navigation-android/pull/2664#issuecomment-605279689 @Guardiola31337 found that `MapboxNativeNavigatorImpl` will do second arithmetic on millesecond values. 

Note that this issue may include building new examples for creating routes with multiple legs

### Steps to trigger behavior

 1. Create a route with 2 or more legs
 2. Start navigation
 3. Hypothetical, if the first leg is 5 minutes and second leg is 1 minutes

### Expected behavior
Overall durationRemaining will be 5 minutes and 60 milliseconds.

Notice second leg has incorrect units for calculating durationRemaining

### Actual behavior
Overall durationRemaining should be 6 minutes

**Comment by Guardiola31337** [comment]
There's also the inconsistency of `RouteProgress` (milliseconds) / `RouteStepProgress` / `RouteLegProgress` (seconds) `durationRemaining` - independent of the multi-leg use case, we're converting to seconds for `RouteStepProgress` and `RouteLegProgress` while we don't for `RouteProgress` and that could cause confusion to developers accessing those values.

**Comment by kmadsen** [comment]
Yeah did an audit of the different duration and durationRemaining types https://github.com/mapbox/mapbox-navigation-android/issues/2667

**Comment by kmadsen** [comment]
Was fixed by https://github.com/mapbox/mapbox-navigation-android/pull/2669
