### ISSUE TITLE
Remove unnecessary proguard rules 

### ISSUE THREAD

**Issue by RingerJK** [mapbox/mapbox-navigation-android#2674]
Tailwork from [PR](https://github.com/mapbox/mapbox-navigation-android/pull/2643/files#diff-226b34e1fd3bc1d22b5f62b83ae3eba1R26-R31). Remove unnecessary `Proguard rules` when downstream is resolved it by self

**cc** @LukasPaczos

**Comment by RingerJK** [comment]
Seems that we [cannot remove](https://github.com/mapbox/mapbox-base-android/blob/master/MODULARIZATION.md#dependency-injection) `core`'s `proguard`  rules at all so may be we should move all bunch of `keep` rules from dependencies modules to `core` one. Looks that minifying of `offboard`, `onboard` and other modules problem of how `core` requires dependencies(`runtimeOnly`) and rules should be here.
@LukasPaczos @Guardiola31337 wdyt?

**Comment by LukasPaczos** [comment]
Makes sense to me @RingerJK :+1:
