### ISSUE TITLE
Use api instead of implementation for supportDesign dependency

### ISSUE THREAD

**Issue by evabishchevich** [mapbox/mapbox-navigation-android#2682]
UI SDK exposes `RecenterButton` as a public member. This button extends `CardView` so `com.google.android.material:material` should be included via `api`  instead of `implementation`.

**Comment by Guardiola31337** [comment]
Refs. https://github.com/mapbox/mapbox-navigation-android/pull/2831

> We should revisit the rest of the dependencies before releasing `1.0`
