### ISSUE TITLE
Re Centre Issue - Latest 0.7.0 Dependency

### ISSUE THREAD

**Issue by Danny-James** [mapbox/mapbox-navigation-android#270]
I'm Now Using The Latest Navigation UI Dependency, When The 'RE-CENTER' Button Is Clicked, Nothing Happens. The Only Data On The LogCat Is Shown Below.

**Dependencies**
```
compile 'com.mapbox.mapboxsdk:mapbox-android-navigation:0.6.0'
compile 'com.mapbox.mapboxsdk:mapbox-android-navigation-ui:0.7.0-SNAPSHOT@aar'
```
**LogCat**
```
09-26 14:07:14.881 2361-2361/uk.co.ainscough.routeinfo I/chatty: uid=10144(u0_a144) uk.co.ainscough.routeinfo expire 31 lines
09-26 14:07:14.963 2361-2361/uk.co.ainscough.routeinfo W/zygote64: Attempt to remove non-JNI local reference, dumping thread
09-26 14:07:16.723 649-2355/? I/ACDB-LOADER: ACDB AFE returned = -19
09-26 14:07:16.723 649-2355/? D/hardware_info: hw_info_append_hw_type : device_name = speaker
09-26 14:07:16.723 649-2355/? D/audio_hw_primary: enable_snd_device: snd_device(2: speaker)
09-26 14:07:16.723 649-2355/? D/audio_hw_primary: enable_audio_route: usecase(1) apply and update mixer path: low-latency-playback speaker
09-26 14:07:16.724 730-815/? E/ANDR-PERF-OPTSHANDLER: Warning: Resource [2, 0] not supported for core 1. Instead use resource for core 0
09-26 14:07:16.724 730-815/? E/ANDR-PERF-RESOURCEQS: Failed to apply optimization [2, 2, 0]
```

**Comment by danesfeder** [comment]
@Danny-James are you stationary when you start it up and scroll?  This is a bug where the button does nothing at startup because we don't have a location update yet from the `LocationEngine` - on our list to address

**Comment by Danny-James** [comment]
I Will Generate A GIF To Show You What I Experiece.

**Comment by Danny-James** [comment]
Attached Is A Screenshot Of The Issue.

![navigation_ui_re-center](https://user-images.githubusercontent.com/32104383/30863804-dc0c558a-a2c9-11e7-87a3-0f3b7b0bb093.gif)

**Comment by Snipedown** [comment]
It has to do with NavigationCamera within the Navigation module. You need to set the location at the start of the route, as the location only seems to update while the car drives, and onLocationUpdate is called.

To fix this, you just need to add a setLocation inside of NavigationCamera and then call that somewhere where the location is initialize. I think it's inside of NavigationView, but I don't fully remember.

**Comment by Danny-James** [comment]
@Snipedown are your explaining this to me? I'm only using the dependency so i don't seem to have access to any of the NavigationUI classes locally.

**Comment by Snipedown** [comment]
@Danny-James 
I apologize, but yeah I don't think there is anything you can do to fix it currently then. However, once they start moving it should begin to work. It is only broken while they are stationary.

**Comment by Danny-James** [comment]
@danesfeder Any Info On An ETA For This Fix?

**Comment by danesfeder** [comment]
@Danny-James https://github.com/mapbox/mapbox-navigation-android/pull/278

**Comment by Danny-James** [comment]
@danesfeder Cheers Mate, I Just Need To Wait On The Release?

**Comment by Danny-James** [comment]
@danesfeder Cheers, I'm already compiling the following: 
```
compile 'com.mapbox.mapboxsdk:mapbox-android-navigation:0.6.0'
compile 'com.mapbox.mapboxsdk:mapbox-android-navigation-ui:0.7.0-SNAPSHOT@aar'
```

Do I Require `@arr`?
