### ISSUE TITLE
Revisit builders consistency

### ISSUE THREAD

**Issue by Guardiola31337** [mapbox/mapbox-navigation-android#2709]
Follow up ticket from https://github.com/mapbox/mapbox-navigation-android/pull/2460#discussion_r384758312 https://github.com/mapbox/mapbox-navigation-android/pull/2460#discussion_r384789506 https://github.com/mapbox/mapbox-navigation-android/pull/2624#discussion_r402656343

cc @cafesilencio @abhishek1508

**Comment by kmadsen** [comment]
Here is the proposed builder pattern for our domain entities.

**Calling MapboxNavigation**
- [ ] NavigationOptions
- [ ] MapboxDistanceFormatter (rename to DistanceFormatOptions)
- [ ] MapboxOnboardRouterConfig (rename to OnboardRouterOptions)
- [ ] Endpoint (rename to OnboardEndpointOptions)
- [ ] ReplayRouteOptions
- [ ] SensorOptions
- [ ] ArrivalOptions

The domain entities that fall in this category will be "*Options". That way it's easier to find the Mapbox Navigation Options available. For example, MapboxDistanceFormatter will be renamed to DistanceFormattingOptions which can be passed to components requiring distance formatting.

**Receiving MapboxNavigation**
- [ ] RouteProgress
- [ ] RouteStepProgress
- [ ] RouteLegProgress
- [ ] BannerInstructions
- [ ] BannerText
- [ ] BannerComponents
- [ ] VoiceInstructions

``` kotlin
/**
 * Description of the Example. This is a data class because it is responsible for
 * transporting data values. We want to take advantage of kotlin's equals operator on data objects.
 */
data class Example(
  /**
   * Required application context example description
   */ 
   val context: Context,

  /**
   * Description of what to expect when reading foo
   */ 
   val foo: String,

  /**
   * Description of what to expect when reading bar
   */ 
   val bar: Int
) {

  /**
    * Include a toBuilder so this object can be recreated
    */
  fun toBuilder() = builder  

  /**
   * Description for when to use this builder
   *
   * @param context is a required parameter and does not have a default value
   */
  class Builder(
    private val context: Context
  ) {
    private var foo: String = "default foo value"
    private var bar: Int = 23

    /**
      * @param foo description of what to expect when writing this value
      * @return Builder
      */
    fun foo(foo: Int) =
      apply { this.foo = foo }

    /**
      * @param bar description of what to expect when writing this value
      * @return Builder
      */
    fun bar(bar: String) =
      apply { this.bar = bar }

    /**
      * Build new instance of [Example]
      *
      * @return Example
      */
    fun build(): Example {
      return Example(
          context,
          foo,
          bar,
          this,
      )
    }
  }
}
```

**Comment by LukasPaczos** [comment]
I'd like to very briefly revisit this ticket. One concern is mentioned in https://github.com/mapbox/mapbox-navigation-android/issues/3343 and the other is the declaration of the class:
```kotlin
data class Example(
   val required: RequiredExample,
   val foo: String,
   val bar: Int
)
```

By making the constructor of the data class public, whenever we want to add a field, regardless if it's optional or not, we're going to break semver.

Wouldn't using a java-like pattern be easier to maintain in the long run from the versioning perspective?
```kotlin
class Example private constructor(
   val required: RequiredExample,
   val foo: String,
   val bar: Int,
   val biz: Boolean?
) {
fun toBuilder() = Builder(required).apply { non-required }
override fun equals()
override fun hashCode()
class Builder...
}
```

Leaving the builder pattern as is should be fine. If we would add required properties checks in `build` method instead, it would still be breaking change so there's no way around it.

Let me know what you think.

**Comment by cafesilencio** [comment]
Initially I was in favor of using data classes but you make a good point Lukas. I have found recently when I needed to add a field to some options class for example it was easy to add it to the "java style" builder without touching a lot of other files.  However putting required field in the builder is a mistake in my opinion. Required fields should go in the constructor an optional fields in the builder.  Some of our builders throw exceptions at runtime if required fields are left out of the builder. This makes for a bad developer experience in my opinion and results in an API that doesn't accurately describe itself. For required fields lets take advantage of the compiler.

**Comment by LukasPaczos** [comment]
Since this is reopened, let's track https://github.com/mapbox/mapbox-navigation-android/issues/3343 here as well.

The `toBuilder` method would need to look more like this:
```kotlin
fun toBuilder() = Builder(required).apply { non-required }
```
instead of returning the same reference that was used previously because that reference can be reused elsewhere, making test like below fail when it should always pass :
```kotlin
@Test
fun reuseChangedBuilder() {
    val builder = NavigationOptions.Builder(context)
    val options = builder.build()
    builder.accessToken("pk.123")

    assertEquals(options, options.builder.build())
}
```

**Comment by LukasPaczos** [comment]
Adding `release-blocker` label to make sure that we address this discussion before the stable release is out. Modifying the initial idea, my proposal would be:
``` kotlin
/**
 * Description of the RequiredExample. This is a data class because it is responsible for
 * transporting data values. We want to take advantage of kotlin's generated equals.
 *
 * @param required description of what to expect from required
 * @param foo description of what to expect from foo
 * @param bar description of what to expect from bar
 */
class Example private constructor(
    val required: String, // required
    val foo: String, // optional with default value
    val bar: Int? // optional without default value
) {
    /**
     * @return the builder that created the [Example]
     */
    fun toBuilder() = Builder(required).also {
        it.foo(this.foo)
        it.bar(this.bar)
    }

    override fun equals(other: Any?): Boolean {
        if (this === other) return true
        if (javaClass != other?.javaClass) return false

        other as Example

        if (required != other.required) return false
        if (foo != other.foo) return false
        if (bar != other.bar) return false

        return true
    }

    override fun hashCode(): Int {
        var result = required.hashCode()
        result = 31 * result + foo.hashCode()
        result = 31 * result + (bar ?: 0)
        return result
    }

    override fun toString(): String {
        return "Example(required='$required', foo='$foo', bar=$bar)"
    }

    /**
     * Description for when to use this builder
     *
     * @param required does not have a default value
     */
    class Builder(
        private val required: String
    ) {
        private var foo: String = "default foo value"
        private var bar: Int? = null

        /**
         * @param foo description of what to expect when writing foo
         * @return Builder
         */
        fun foo(foo: String) =
            apply { this.foo = foo }

        /**
         * @param bar description of what to expect when writing bar
         * @return Builder
         */
        fun bar(bar: Int?) =
            apply { this.bar = bar }

        /**
         * Build new instance of [Example]
         * @return Example
         */
        fun build(): Example {
            return Example(
                required,
                foo,
                bar
            )
        }

        override fun equals(other: Any?): Boolean {
            if (this === other) return true
            if (javaClass != other?.javaClass) return false

            other as Builder

            if (required != other.required) return false
            if (foo != other.foo) return false
            if (bar != other.bar) return false

            return true
        }

        override fun hashCode(): Int {
            var result = required.hashCode()
            result = 31 * result + foo.hashCode()
            result = 31 * result + (bar ?: 0)
            return result
        }

        override fun toString(): String {
            return "Builder(required='$required', foo='$foo', bar=$bar)"
        }
    }
}
```

Does that look good, or do you see any maintenance issues that we might hit?

**Comment by kmadsen** [comment]
@LukasPaczos yeah I agree with going with class instead of data class. the benefits are lost with our idea to keep the builder with the class. and yes, we'll need to add `equals`, `hashcode`, and `toString`. Will you add the builder to your example object to reflect this?

one change though, is just because a field is required - does not mean it should be in the constructor. it's if the field does _not have a default_ that it needs to be in the constructor.

**Comment by kmadsen** [comment]
> Since this is reopened, let's track #3343 here as well.
The toBuilder method would need to look more like this:
fun toBuilder() = Builder(required).apply { non-required }

Other option is to pass the builder with the object. otherwise we will also need to maintain the `apply { }` scope. history says, devs forget to maintain this type of design. those bugs are difficult to find

**Comment by kmadsen** [comment]
Design looks pretty good. It's almost exactly the alternative we were considering before. Also very close to Jake-Wharton's preference https://jakewharton.com/public-api-challenges-in-kotlin/

> or do you see any maintenance issues that we might hit?

We are introducing a few code generation requirements that are uncaught by tests, so we'll for sure hit them.
- [ ] run code generation for `equals()`, `hashcode()`, and `toString()`
- [ ] add optional field to the `toBuilder().apply { }`

think we're agreeing it's maintenance we'll live with so it's 👍  by me

**Comment by Guardiola31337** [comment]
A couple of comments to the above-suggested idea:

```kotlin
/**
 * @return the builder that created the [Example]
 */
fun toBuilder() = Builder(required).also {
    it.foo(this.foo)
    it.bar(this.bar)
}
```

Do we need `also { }` at all? 🤔 What about 👇?

```kotlin
/**
 * @return the builder that created the [Example]
 */
fun toBuilder() = Builder(required)
    .foo(this.foo)
    .bar(this.bar)
}
```

---

```kotlin
/**
 * @param bar description of what to expect when writing bar
 * @return Builder
 */
fun bar(bar: Int?) =
    apply { this.bar = bar }
```

I believe this should be non-null because if you don't specify, a default `bar` will be created (`null`) but normally the builder "asks" you to provide one if you're interested in doing so, don't you think? I believe that all the options in a `Builder` should be always non-null.

cc @kmadsen @LukasPaczos

**Comment by LukasPaczos** [comment]
> one change though, is just because a field is required - does not mean it should be in the constructor. it's if the field does not have a default that it needs to be in the constructor.

Agreed, that sounds fair.

> Do we need also { } [in the toBuilder] ]at all?

No, I just typed it this way :) The main point is to return a new instance.

> I believe this should be non-null because if you don't specify, a default bar will be created (null) but normally the builder "asks" you to provide one if you're interested in doing so, don't you think? I believe that all the options in a Builder should be always non-null.

By making the setter method match the nullability of the type you have a chance to take the previous builder and reverse the field back to `null`. I think it's a cool little feature that doesn't cost us anything in maintenance.

>  We are introducing a few code generation requirements that are uncaught by tests, so we'll for sure hit them.

We can make them be covered by tests though! An abstract test class with some reflection calls that each implementation test extends should be able to verify this builder schema. I'd like to see this work start with writing this abstract test case and only then apply implementation changes.

Any other concerns or ideas @mapbox/navigation-android?
