### ISSUE TITLE
Directional Images

### ISSUE THREAD

**Issue by Danny-James** [mapbox/mapbox-navigation-android#271]
Since The Change Of Dependency From 0.6.0 to 0.7.0 Navigation UI - Android

The Image For The Left Turn Seem To Have Something Sitting Below It.

See Screen Shot Below.

![screenshot_20170926-141314](https://user-images.githubusercontent.com/32104383/30862190-197133a0-a2c5-11e7-9dc8-4e48715a0c61.png)

**Comment by cammace** [comment]
<img src="https://user-images.githubusercontent.com/5652865/30873007-d95fdace-a2b9-11e7-9ecc-9d5093bac3cd.png" width=360/>

Are you talking about the straight line circled in the screenshot above? This is intended to better represent the intersection.

**Comment by Danny-James** [comment]
I Am Yes, I Just Haven't Noticed It Befor Not Sure Why, Close This Issue Then Please, Thanks For Getting Back To Me :)
