### ISSUE TITLE
Revisit Faster route when NavigationSession.State transitions between states

### ISSUE THREAD

**Issue by Guardiola31337** [mapbox/mapbox-navigation-android#2710]
Follow up from https://github.com/mapbox/mapbox-navigation-android/pull/2668#discussion_r401289148

We should revisit what happens if `NavigationSession.State` transitions from _Active Guidance_ to _Free Drive_ and _Faster Route_ is enabled

https://github.com/mapbox/mapbox-navigation-android/blob/90f4fa7787f2d01dbd6a2ff4a92dd2972f57a362/libnavigation-core/src/main/java/com/mapbox/navigation/core/directions/session/MapboxDirectionsSession.kt#L68-L72

👀 `MapboxDirectionsSessionTest` `TODO`s

https://github.com/mapbox/mapbox-navigation-android/blob/90f4fa7787f2d01dbd6a2ff4a92dd2972f57a362/libnavigation-core/src/test/java/com/mapbox/navigation/core/directions/session/MapboxDirectionsSessionTest.kt#L139-L142

https://github.com/mapbox/mapbox-navigation-android/blob/90f4fa7787f2d01dbd6a2ff4a92dd2972f57a362/libnavigation-core/src/test/java/com/mapbox/navigation/core/directions/session/MapboxDirectionsSessionTest.kt#L177-L180

cc @LukasPaczos @kmadsen @abhishek1508

**Comment by kmadsen** [comment]
I don't think we should tie FasterRoute or RouteRefresh directly to NavigationSession.State. It seems like they should depend on their data dependencies.

FasterRoute is whenever you have a DirectionsRoute. You could in free drive mode, and then add and remove directions. Is this when we're going in and out of free drive? Or is it also when you go into map view?

**Comment by Guardiola31337** [comment]
A client can transition from _Active Guidance_ to _Free Drive_ within the same trip session, as it's possible to set routes externally - that's how states flow, started session and route 👉 _Active Guidance_, started session and no route 👉 _Free Drive_, otherwise 👉 _Idle_. Being in a guided trip session (i.e. route is set) the client could clean it up and the state will go from _Active Guidance_ to _Free Drive_ and as mentioned in OP we're not cleaning up `RouteOptions` when cleaning up `routes` in `MapboxDirectionsSession` so `requestFasterRoute` could still happened (timer and logic is scheduled / handled in `MapboxNavigation`) because the only thing that we're checking is the route options and the route progress (👀 `AdjustedRouteOptionsProvider#getRouteOptions`) but not if there's a route or not.

**Comment by kmadsen** [comment]
OK I see this updateState here.

https://github.com/mapbox/mapbox-navigation-android/blob/ad616d3f187f83627e4c6f8676f902fd057f7b25/libnavigation-core/src/main/java/com/mapbox/navigation/core/NavigationSession.kt#L40-L46

But the request is ok to make when you're transitioning out of active guidance. It's the response that creates the experience. That's where the FasterRouteDetector is listening

https://github.com/mapbox/mapbox-navigation-android/blob/ad616d3f187f83627e4c6f8676f902fd057f7b25/libnavigation-core/src/main/java/com/mapbox/navigation/core/fasterroute/FasterRouteController.kt#L42-L49

But it is only looking at the RouteProgress, we may need to add a test case to make sure the `DirectionsSession` routes are not empty

**Comment by Guardiola31337** [comment]
> But it is only looking at the RouteProgress, we may need to add a test case to make sure the `DirectionsSession` routes are not empty

That's what I was referring to. Sorry if I didn't make myself clear 😅

**Comment by kmadsen** [comment]
> That's what I was referring to. Sorry if I didn't make myself clear 😅

I was also catching up on what the issue is. This may be a straight forward fix. https://github.com/mapbox/mapbox-navigation-android/pull/2712
