### ISSUE TITLE
Re-routes when in simulation mode should not happen

### ISSUE THREAD

**Issue by Guardiola31337** [mapbox/mapbox-navigation-android#2717]
We've noticed re-routes when using `ReplayRouteLocationEngine` lately. Wondering if something from NN (`10.0.3`) recently changed that makes off-routes to happen more often (cc @mskurydin) but this is pretty easy to reproduce when running any example from the `examples` test app with simulation mode enabled 👀 

![replay_route_location_engine_off_route](https://user-images.githubusercontent.com/1668582/78617775-67a2fc80-7846-11ea-99fb-972b92583e91.gif)

cc @kmadsen @JunDai @LukasPaczos

**Comment by kmadsen** [comment]
The right drift at the maneuver is interesting, was that bias in the North direction? I wonder if `ReplayRouteLocationEngine` needs to incorporate bearing

**Comment by kmadsen** [comment]
It's also possible that the default North bearing (0.0) is causing a false bias? The simulator may work better if bearing was `null`?

**Comment by Guardiola31337** [comment]
We're still able to see re-routes after https://github.com/mapbox/mapbox-navigation-android/pull/2802 and https://github.com/mapbox/mapbox-navigation-android/issues/2717 We might need to tweak the default `turnSpeedMps` https://github.com/mapbox/mapbox-navigation-android/blob/master/libnavigation-core/src/main/java/com/mapbox/navigation/core/replay/route2/ReplayRouteOptions.kt#L36 6 Mps seems pretty fast for intersections, I tested with 4 Mps and wasn't able to reproduce the re-route I was 👀 cc @kmadsen
