### ISSUE TITLE
Create a DirectionsResponse from a GeoJSON

### ISSUE THREAD

**Issue by dmateus** [mapbox/mapbox-navigation-android#272]
I found  [this snippet in your test app](https://github.com/mapbox/mapbox-navigation-android/blob/master/navigation/app/src/main/java/com/mapbox/services/android/navigation/testapp/activity/navigationui/NavigationMapRouteActivity.java)

```
DirectionsResponse response = gson.fromJson(loadJsonFromAsset(DIRECTIONS_RESPONSE), DirectionsResponse.class);
navigationMapRoute.addRoute(response.getRoutes().get(0));
```

My questions is: is it possible to feed a GeoJSON formatted object instead of a DirectionsResponse model? If not, is there a way to convert GeoJSON into a DirectionsResponse json?

The reason for this is that I'd like to have turn by turn navigation with my own path.

Thanks

**Comment by cammace** [comment]
Yes, this is possible doing exactly what the test is doing. 

> GeoJSON into a DirectionsResponse json

GeoJSON and the direction response JSON are the same thing.

**Comment by dmateus** [comment]
@cammace 

This is a GeoJSON example:
```
{
    "type": "Feature",
    "geometry": {
        "type": "MultiLineString",
        "coordinates": [
            [
                [
                    -87.6298,
                    41.878113
                ],
                [
                    -87.629697,
                    41.875701
                ],
                [
                    -87.646942,
                    41.875825
                ],
                [
...
```

And this is a DirectionsResponse json:
```
{
    "waypoints": [
        {
            "location": [
                -74.037424,
                40.777247
            ],
            "name": ""
        },
        {
            "location": [
                -73.912029,
                40.680148
            ],
            "name": "MacDougal Street"
        }
    ],
    "routes": [
        {
            "legs": [
                {
                    "steps": [
                        {
                            "intersections": [
                                {
                                    "out": 0,
                                    "entry": [
                                        true
                                    ],
                                    "location": [
                                        -74.037424,
                                        40.777247
                                    ],
                                    "bearings": [
                                        312
                                    ]
                                },
...
```

It doesn't look the same

**Comment by cammace** [comment]
There's no way to just automatically turn GeoJSON into a DIrections Response (otherwise the API would serve no purpose). My suggestion would be to use the Map Matching API passing in the GeoJSON coordinates so that you can get a directions response which can then be used for a navigation session.
