### ISSUE TITLE
snappedLocation missing original location variables

### ISSUE THREAD

**Issue by cammace** [mapbox/mapbox-navigation-android#273]
`snappedLocation` should copy the location instance, currently, speed is not added to the new location object when snapping is enabled.

**Comment by danesfeder** [comment]
Currently copying the raw location attributes in `master` https://github.com/mapbox/mapbox-navigation-android/blob/master/libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/snap/SnapToRoute.java#L50-L61
