### ISSUE TITLE
BasicNavigationActivity doesn't support configuration changes

### ISSUE THREAD

**Issue by Guardiola31337** [mapbox/mapbox-navigation-android#2733]
When testing the `examples` test app noticed that `BasicNavigationActivity` doesn't support configuration changes. Tested in simulation mode putting the app in the background and bringing it back to the foreground from the notification and puck is stuck 👀 Rest of examples work 👌 

![basic_navigation_activity_config_changes_not_supported](https://user-images.githubusercontent.com/1668582/78830838-9b049900-79b6-11ea-8e78-63707444edd1.gif)

**Comment by JunDai** [comment]
reopen it since #2781 did some change which will cause this problem. and now the issue will be also applied to InstructionViewActivity/SummaryBottomSheetActivity etc.

https://github.com/mapbox/mapbox-navigation-android/pull/2781/files#diff-6373cd18e93da78e7620cd513c4f73c1R134-R137
