### ISSUE TITLE
Negative remaining distances

### ISSUE THREAD

**Issue by Guardiola31337** [mapbox/mapbox-navigation-android#2734]
When testing the `examples` test app (`InstructionViewActivity`) noticed that we're pushing negative distances 👀 

![instruction_view_activity_negative_distances](https://user-images.githubusercontent.com/1668582/78832243-e5871500-79b8-11ea-9c03-ceb1d07cac66.gif)

![banner_instruction_negative_distance](https://user-images.githubusercontent.com/1668582/78832426-3ac32680-79b9-11ea-8fed-c15e6658023f.png)

Also noticed that banner instructions and notification units don't match (imperial and metric respectively) 👀 

![notification_negative_distances](https://user-images.githubusercontent.com/1668582/78832582-82e24900-79b9-11ea-907b-04864dbf4f2f.png)

Saw once `1000 ft`, is that a valid imperial value 🤔?

Regression from https://github.com/mapbox/mapbox-navigation-android/pull/2624?

cc @cafesilencio

**Comment by cafesilencio** [comment]
1000 feet seems like a valid value to me because there are 5280 feet in a mile. The only unit between feet and miles is yards but I don't think we support yards. I don't know how widely yards are used outside of the US

**Comment by Guardiola31337** [comment]
@cafesilencio 
> 1000 feet seems like a valid value to me because there are 5280 feet in a mile.

I meant based on the rounding and the rules we apply internally but if you've 👀 and can confirm that is a valid value 👍 I was curious only 😅 Thanks for looking 🙇

**Comment by cafesilencio** [comment]
All of the rounding increments would support a value of 1000 ft.

**Comment by cafesilencio** [comment]
PR merged into master.
