### ISSUE TITLE
Camera in NavigationView zooms from 0 to the desired zoom level when session starts

### ISSUE THREAD

**Issue by Guardiola31337** [mapbox/mapbox-navigation-android#2736]
When testing the `examples` test app (`NavigationViewActivity`) noticed that camera zoom from 0 to the desired zoom level when the session starts 👇 That's not the case in the legacy.

![navigation_view_activity_camera_zero_zoom_level_at_startup](https://user-images.githubusercontent.com/1668582/78835365-10c03300-79be-11ea-9c97-c05e77d46559.gif)

**Comment by JunDai** [comment]
@Guardiola31337 - I think because in this example we don't have the initial camera position. Where do you see the legacy behavior? Are you referring to `Navigation Launcher` in the old `app`?
