### ISSUE TITLE
Guidance-views requires hard-coded access token for demo

### ISSUE THREAD

**Issue by kmadsen** [mapbox/mapbox-navigation-android#2743]
**Mapbox Navigation SDK version:** Examples

### Steps to trigger behavior

 1. Go to Navigation Core SDK > GuidanceViewActivity
 2. Have access_token without guidance-views 

### Observed behavior
Guidance views won't work

### Actual behavior
Give instructions for how to support guidance views

cc: @Guardiola31337 @abhishek1508

**Comment by Guardiola31337** [comment]
Yeah noticed that in the past and apparently @abhishek1508 wasn't able to reproduce 🤔

**Comment by Guardiola31337** [comment]
👀 https://github.com/mapbox/mapbox-navigation-android/issues/2625#issuecomment-606120197 and https://github.com/mapbox/mapbox-navigation-android/issues/2625#issuecomment-606203337 @kmadsen

**Comment by kmadsen** [comment]
https://github.com/mapbox/mapbox-navigation-android/compare/km-guidance-view-use-working-access-token?expand=1

This will fix it, so it's an access token issue. Is this a problem on many map screens? Could we provide a screen that leads people in a direction to fix their access token?

**Comment by kmadsen** [comment]
Ah this is a duplicate of https://github.com/mapbox/mapbox-navigation-android/issues/2625

**Comment by kmadsen** [comment]
Reopened and changed this ticket to resolve access tokens for guidance views before a launch
