### ISSUE TITLE
Rerouting with Navigation UI SDK only works once.

### ISSUE THREAD

**Issue by leirbag3711** [mapbox/mapbox-navigation-android#2747]
**Android API: all**
**Mapbox Navigation SDK version:0.42.6**

Hello guys, I´m using a navigation view where I fetch the route using the function MapboxMapMatching, cuz I´m using a microservice where I calculate the route by my own, so I use MapboxMapMatching to fetch the points of my route. Then as im using Mapbox Navigation UI SDK, I use also the function "allowRerouteFrom" where i call again my microservice and fetch the route again using MapboxMapMatching and finally return false as the Mapbox documentation says (https://docs.mapbox.com/android/navigation/overview/map-matching/#map-matching-with-navigationview).

### Expected behavior
The user can be rerouted the times that he gets lost.
### Actual behavior
The fonction allowReouteFrom only works once, I mean... I can be lost once and the app will reroute you based in you current location (that's great) but if I get lost another time, the application never enter again to allowRerouteFrom function to fetch the new route.

Thank you for any help, if you have any question please ask me. 

Gabriel.

**Comment by Guardiola31337** [comment]
@abhishek1508 could we check if this would be an issue in `1.0`?

**Comment by abhishek1508** [comment]
Let's verify this in v1.0
cc @JunDai @cafesilencio @langsmith

**Comment by cafesilencio** [comment]
There have been significant changes in our upcoming 1.0 version of the SDK. Rerouting is handled very differently as well as the method of fetching a route. Please look for our soon to be released version 1.0 of the navigation SDK and give it a try.  If you still find that you have an issue reopen this ticket or create a new one.
