### ISSUE TITLE
Fix the leak in HybridRouter and NetworkStatusService

### ISSUE THREAD

**Issue by korshaknn** [mapbox/mapbox-navigation-android#2751]
Fix the leak in HybridRouter and NetworkStatusService [#2740 (review)](https://github.com/mapbox/mapbox-navigation-android/pull/2740#pullrequestreview-391545440)

**Comment by Guardiola31337** [comment]
> When testing `HybridRouterActivityJava` and `HybridRouterActivityKt` run into the following leak 👀 
>
> ![hybrid_router_activity_java_leak](https://user-images.githubusercontent.com/1668582/79008997-906c1000-7b2c-11ea-8c15-49c701b2a7bb.png)
>
> ![hybrid_router_activity_kt_leak](https://user-images.githubusercontent.com/1668582/79009006-94982d80-7b2c-11ea-814a-539f5829c312.png)
