### ISSUE TITLE
Camera / location off after running GuidanceViewActivity

### ISSUE THREAD

**Issue by Guardiola31337** [mapbox/mapbox-navigation-android#2769]
When testing the `examples` test app noticed that somehow the location engine is retained causing unexpected behaviors when running other examples 👀 

![camera_off_after_running_guidance_view_activity](https://user-images.githubusercontent.com/1668582/79254387-a8a49d80-7e52-11ea-93f4-5519642541a0.gif)

It seems that something is going on after running `GuidanceViewActivity` - if not launched everything works as expected. Also note that location icon in the status bar is shown i.e. location engine is enabled 🤔

**Comment by cafesilencio** [comment]
Steps to trigger behavior
Start GuidenceView example activity
Start navigation pause for a few seconds
Swipe out of the activity
Start Basic Navigation activity
Long press map to create a waypoint
Click 'Start Navigation'
