### ISSUE TITLE
Add localizations

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-navigation-android#28]
The following files contain translatable messages that should be localized at Transifex:

https://github.com/mapbox/mapbox-navigation-android/blob/master/navigation/app/src/main/res/values/strings.xml
https://github.com/mapbox/mapbox-navigation-android/blob/master/navigation/libandroid-navigation/src/main/res/values/strings.xml

We’ll want to set up a separate project under the Mapbox organization. Though Transifex mostly supports drawing in resources from multiple repositories, the `tx` client works best when a Transifex project is hooked up to a single repository. For convenience, we can share the same translation teams as the iOS navigation SDK and the map SDKs.

`make prepare-osrm` already pulls in translations from the [OSRM Text Instructions](https://www.transifex.com/project-osrm/osrm-text-instructions/) project on Transifex, so guidance instructions should already be localized as long as we’re using `TextInstructions` wherever we need to display an instruction.

/cc @cammace @langsmith @tobrun

**Comment by langsmith** [comment]
thanks @1ec5 . I believe you're the only one who can set up a new project in our Transifex account. Wanna' create `Mapbox Navigation SDK for Android` so that we can take it from there?

**Comment by 1ec5** [comment]
@tobrun is already an administrator, and I’ve added you as well.

**Comment by 1ec5** [comment]
We set up [a Transifex project](https://www.transifex.com/mapbox/mapbox-navigation-sdk-for-android/) and pulled in some initial translations in #61. Next steps in #114.
