### ISSUE TITLE
Notification Navigation Session State not handled when location is disabled

### ISSUE THREAD

**Issue by Guardiola31337** [mapbox/mapbox-navigation-android#2827]
When testing the `examples` test app noticed that the notification is 🤯 if you start a session with location disabled from device settings 👀 

![notification_messed_up_with_location_disabled](https://user-images.githubusercontent.com/1668582/79993618-f2a90700-8482-11ea-8475-0159575d8f5e.gif)

As seen above if you start a _Free Drive_ session with location disabled the notification thinks that you're in _Active Guidance_ (no data 👉 ` . ` and `X END NAVIGATION`) - note how when location is enabled back the notification updates to `Free Drive Session`.

Similarly when you start an _Active Guidance_ session with location disabled the notification shows that you're in _Free Drive_ (`Free Drive Session` and `X` interestingly `STOP SESSION` is not displayed 🤔) - note how when location is regained the notification updates to _Active Guidance_ look and feel.

cc @Lebedinsky @LukasPaczos @abhishek1508

**Comment by JunDai** [comment]
@Guardiola31337 found that `after switching to free drive and starting a guided session, the left image is wrong and the street name is missing`

![image](https://user-images.githubusercontent.com/3918950/80997590-625db100-8df6-11ea-99a9-294cfc4f4cc9.png)

**Comment by Guardiola31337** [comment]
cc @d-prukop for visibility

**Comment by Guardiola31337** [comment]
Refs. https://github.com/mapbox/mapbox-navigation-android/issues/1062 and https://github.com/mapbox/mapbox-navigation-android/issues/774

**Comment by zugaldia** [comment]
This has become a high-priority issue. One recommendation is to initialize the notification with a placeholder text (e.g. "Navigation is starting...") instead of showing an empty notification. Longer term, we can explore other UX options.

@Lebedinsky I see you're assigned to this ticket. Could you run with short-term solution I propose above?
