### ISSUE TITLE
Audit RouteProgressObserver in UI SDK to find out if it is storing the route state

### ISSUE THREAD

**Issue by abhishek1508** [mapbox/mapbox-navigation-android#2861]
Run into the following crash 👇 before https://github.com/mapbox/mapbox-navigation-android/pull/2849

```
04-28 18:35:50.086 24079-24079/com.mapbox.navigation.examples E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.mapbox.navigation.examples, PID: 24079
    kotlin.KotlinNullPointerException
        at com.mapbox.navigation.ui.route.MapRouteProgressChangeListener$updateRoute$1$deferredExpression$1.invokeSuspend(MapRouteProgressChangeListener.kt:53)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

In that PR https://github.com/mapbox/mapbox-navigation-android/blob/7d064e42f35d748399e705e5a4b34611947d0902/libnavigation-ui/src/main/java/com/mapbox/navigation/ui/route/MapRouteProgressChangeListener.kt#L39-L45 was added so we're not crashing anymore but the overall issue is still there (the crash was making it more evident 😅) because an _Active Guidance_ session can be started without a route i.e. it seems there's something that gets retained / not reset in the _Free Drive_ use case in the UI 👀 

![free_drive_navigation_activity_active_guidance](https://user-images.githubusercontent.com/1668582/80647737-fcaba680-8a3c-11ea-8d34-75aaf48ff644.png)

This is the `FreeDriveNavigationActivity` which shouldn't ever start an _Active Guidance_ session.

It can be reproduced going back and forth between other examples in the test app `GuidanceViewActivity` > `FreeDriveNavigationActivity` > `InstructionViewActivity` until you get `FreeDriveNavigationActivity` in an undesired state.

Refs. https://github.com/mapbox/mapbox-navigation-android/pull/2804 and https://github.com/mapbox/mapbox-navigation-android/pull/2698 

cc @cafesilencio @abhishek1508

**Comment by cafesilencio** [comment]
@Guardiola31337 I don't see anywhere the observer is being retained.  Have you been able to recreate this issue recently? I think maybe this issue got taken care of with some of the other recent fixes.

**Comment by cafesilencio** [comment]
I haven't found any cases of inappropriate resource consumption. I haven't been able to reproduce the issue described nor have I been able to find anybody else who has. I believe this issue was resolved with other recent fixes.  I'm closing this ticket.
