### ISSUE TITLE
Puck jumpy when transitioning from Active Guidance to Free Drive

### ISSUE THREAD

**Issue by Guardiola31337** [mapbox/mapbox-navigation-android#2869]
When testing the test app `SimpleMapboxNavigationKt` noticed that when transitioning from _Active Guidance_ to _Free Drive_ the puck becomes jumpy 👀 

![free_drive_puck_jumpy](https://user-images.githubusercontent.com/1668582/80658594-81ee8580-8a54-11ea-8399-759fccbe568d.gif)

This normally happens when having multiple observers enabled sending location updates to the `LocationComponent` so wondering if this is a regression from https://github.com/mapbox/mapbox-navigation-android/pull/2832#discussion_r413495752

We should investigate if this is an issue in the SDK or an issue in the example setup.

cc @JunDai @abhishek1508 @cafesilencio

**Comment by JunDai** [comment]
@LukasPaczos - can you comment on this if you have any related ticket or information about it?

**Comment by LukasPaczos** [comment]
> This normally happens when having multiple observers enabled sending location updates to the LocationComponent

I believe there's a bug in the example activity which makes the puck "jumpy" instead of smoothly animated.

When it comes to the puck flashing, it will also mostly be resolved when ^^^ is handled.

**Comment by JunDai** [comment]
thanks @LukasPaczos . I will check the `jumpy` issue.

**Comment by JunDai** [comment]
@Guardiola31337 - feel free to let me know if you still see this issue.
