### ISSUE TITLE
Navigation notifications persist after stop navigation

### ISSUE THREAD

**Issue by wlTrunks** [mapbox/mapbox-navigation-android#2871]
version com.mapbox.mapboxsdk:mapbox-android-navigation-ui:0.42.5
After taping on notification button to end navigation, notifications reopened and persist. 
This bug found one of my tester, on android 7 and android 10 devices. Sorry for bad quality of gif. 

![gif1](https://user-images.githubusercontent.com/14748323/80730572-6944a500-8b12-11ea-9bde-2caf85d1e8ba.gif)
![gif2](https://user-images.githubusercontent.com/14748323/80731306-66967f80-8b13-11ea-8006-86e80809b8ca.gif)

I tried to replicate it step by step how he describe it, but no luck. 
1. Open incident screen, start navigation
2. Hide application
3. Tap to end navigation 

So I created customNavigationNotification as described in 
[custom notifications](https://docs.mapbox.com/android/navigation/overview/notifications/)
`        val optionsBuilder =
            MapboxNavigationOptions.builder()
                .navigationNotification(CustomNavigationNotification(context))
                .isFromNavigationUi(true)
                .isDebugLoggingEnabled(BuildConfig.DEBUG)
                .roundingIncrement(NavigationConstants.ROUNDING_INCREMENT_TEN)
                .offRouteThreshold(20f)
                .defaultNotificationColorId(R.color.colorPrimary)`
And started debug
So found that the is two notifications running, one is default with id 5678, second custom with id 91234821. 
`                    notificationManager.activeNotifications.forEach {
                        println("NOTIFI ${it.user}")
                        println("NOTIFI ${it.id}")
                        println("NOTIFI ${it.tag}")
                    }`

` I/System.out: NOTIFI UserHandle{0}
 I/System.out: NOTIFI 91234821
 I/System.out: NOTIFI null
 I/System.out: NOTIFI UserHandle{0}
 I/System.out: NOTIFI 42424242
 I/System.out: NOTIFI null
 I/System.out: NOTIFI UserHandle{0}
 I/System.out: NOTIFI 5678
 I/System.out: NOTIFI null`

![gif3](https://user-images.githubusercontent.com/14748323/80732861-95155a00-8b15-11ea-9e16-278b4f936c4a.gif)

on this gif 
I'm tapping on notification and closing notification 91234821, and stoping navigations,
also checking for running service by func
`fun <T : Service> Context.isServiceRunning(serviceClass: Class<T>): Boolean {
    val manager: ActivityManager =
        this.getSystemService(Context.ACTIVITY_SERVICE) as ActivityManager
    return manager.getRunningServices(Integer.MAX_VALUE).filter { s ->
        "isServiceRunning ${s.service}".toLog("SERVICE")
        s.service.className == serviceClass.name
    }.isNotEmpty()
}` 
`D/j: SERVICE isServiceRunning ComponentInfo{com.teamdirector.hero/com.mapbox.services.android.navigation.v5.navigation.NavigationService}
`
and close my app. 
But notification with id 5678 still persist. 

Thanks.

**Comment by Guardiola31337** [comment]
@abhishek1508 could we check if this would be addressed in `1.0`?

**Comment by abhishek1508** [comment]
Let's verify this in v1.0
cc @JunDai @cafesilencio @langsmith

**Comment by cafesilencio** [comment]
This issue cannot be reproduced in 1.0. Please be on the lookout for our first public preview of UI SDK v1.0 coming soon. Feel free to create a new issue if you feel it still exists.
