### ISSUE TITLE
Street names underneath route line

### ISSUE THREAD

**Issue by Guardiola31337** [mapbox/mapbox-navigation-android#2872]
When testing the test app noticed that the street names are now underneath the traffic layer 👀 

![street_names_underneath_traffic_layer_1](https://user-images.githubusercontent.com/1668582/80740467-1f45ca00-8ae6-11ea-8c8f-0cb2d94b874f.png)

![street_names_underneath_traffic_layer_2](https://user-images.githubusercontent.com/1668582/80740479-2240ba80-8ae6-11ea-80e0-ca46f4c5d4fa.png)

Noting that this regression is also reproducible in the legacy SDK.

For reference this is the expected behavior 👀 

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/8434572/41746843-c8237a70-7579-11e8-8b9e-049c4ff45da2.gif)

![upcoming_maneuver_arrow](https://user-images.githubusercontent.com/1668582/40004469-117ea00c-5796-11e8-86c4-cad5c23576ee.gif)

Look at https://github.com/mapbox/mapbox-navigation-android/issues/604 https://github.com/mapbox/mapbox-navigation-android/pull/934 and all the upcoming maneuver arrow old tickets.

cc @cafesilencio @abhishek1508

**Comment by cafesilencio** [comment]
Looking at the 0.42.4 source code the layer ID below which the route line was being drawn was mapbox-location however I don't see that layer when I list all of the layers in the style.  I'm going to instead use the layer "road-label" as the default so that the street names will appear above the route line.

**Comment by Guardiola31337** [comment]
👀 https://github.com/mapbox/mapbox-navigation-android/issues/2865#issuecomment-644167160

cc @cafesilencio

**Comment by Guardiola31337** [comment]
Refs. https://github.com/mapbox/mapbox-navigation-android/issues/1048
