### ISSUE TITLE
Route line doesn't vanish in offline mode and color still remains darker than normal

### ISSUE THREAD

**Issue by abhishek1508** [mapbox/mapbox-navigation-android#2875]

**Comment by cafesilencio** [comment]
Pablo observed this behavior with the comments referenced here:  

https://github.com/mapbox/mapbox-navigation-android/pull/2870#issuecomment-621973316

https://github.com/mapbox/mapbox-navigation-android/pull/2870#issuecomment-621987757

https://github.com/mapbox/mapbox-navigation-android/issues/2859#issuecomment-621489073

**Comment by cafesilencio** [comment]
This was resolved with PR #2876
