### ISSUE TITLE
Fix `CustomUIComponentStyleActivity` SummaryBottomSheet reappearance

### ISSUE THREAD

**Issue by langsmith** [mapbox/mapbox-navigation-android#2917]
A somewhat thin sliver of the the bottom of the `SummaryBottomSheet` is missing when the `NavigationView`'s camera is recentered during turn-by-turn navigation.

<img width="451" alt="Screen Shot 2020-05-06 at 2 11 16 PM" src="https://user-images.githubusercontent.com/4394910/81228777-890d1a80-8fa3-11ea-8668-ec2db5308afc.png">
<img width="448" alt="Screen Shot 2020-05-06 at 2 11 22 PM" src="https://user-images.githubusercontent.com/4394910/81228784-8a3e4780-8fa3-11ea-8cc0-07e88ca0ac46.png">
<img width="455" alt="Screen Shot 2020-05-06 at 2 11 28 PM" src="https://user-images.githubusercontent.com/4394910/81228787-8ad6de00-8fa3-11ea-8551-ff75d7887324.png">
<img width="448" alt="Screen Shot 2020-05-06 at 2 10 59 PM" src="https://user-images.githubusercontent.com/4394910/81228797-8e6a6500-8fa3-11ea-8350-2b59b982f1dd.png">

![ezgif com-resize](https://user-images.githubusercontent.com/4394910/81228630-3b90ad80-8fa3-11ea-808b-bbac0c3772b4.gif)

**Comment by JunDai** [comment]
are you talking about the skinny line at the bottom of SummaryBottomSheet during the transition?
I don't see it after the bottom sheet is fully displayed.

**Comment by langsmith** [comment]
The skinny line (area where you can see the map at the bottom of the `SummaryBottomSheet`) is only visible as the `SummaryBottomSheet` goes through the process of being visible again. Meaning, when it transitions from `BottomSheetBehavior.STATE_HIDDEN` to `BottomSheetBehavior.STATE_EXPANDED`. It's not visible once the sheet's done expanding. Might have to do with the programmatic set up of views in the `NavigationView` class.

I think I might try to tackle this ticket after https://github.com/mapbox/mapbox-navigation-android/issues/2935. I'm close to finishing https://github.com/mapbox/mapbox-navigation-android/issues/2935.

**Comment by Guardiola31337** [comment]
> The skinny line (area where you can see the map at the bottom of the `SummaryBottomSheet`) is only visible as the `SummaryBottomSheet` goes through the process of being visible again. Meaning, when it transitions from `BottomSheetBehavior.STATE_HIDDEN` to `BottomSheetBehavior.STATE_EXPANDED`. It's not visible once the sheet's done expanding. Might have to do with the programmatic set up of views in the `NavigationView` class.

It seems related to how `SummaryBottomSheet` is animated by the system when transitions between `BottomSheetBehavior` states. I believe we're only setting the state of the `SummaryBottomSheet` and letting Android to animate. We can explore managing the animation on our side to fix OP though 🚀

**Comment by langsmith** [comment]
I tried this out on a Pixel 2 (API 26) emulator. Didn't see any bottom sheet issues. Would be helpful if folks on @mapbox/navigation-android would look to see if they see the issue on their device on `master`. Might just be a rendering issue with my specific device.

**Comment by JunDai** [comment]
@langsmith - my Samsung S9+ doesn't have problem.

**Comment by langsmith** [comment]
Thanks @JunDai . Any issues in `CustomUIComponentStyleActivity`? I'm seeing weird bottom sheet issues as seen in the GIF below

![ezgif com-resize (2)](https://user-images.githubusercontent.com/4394910/81743832-2b6f4700-9457-11ea-8490-865ac31b469b.gif)

Now I can't even recreate the original bottom space issue on my physical device 😕 Probably is leftover visual artifact glitch thing with my specific device that was appearing only a handful of times.

Steps to investigate original issue:

1. Open the `examples` test app.
2. Open the `Navigation UI SDK` section
3. Open the `NavigationView` example, which is the 1st example listed. This is `NavigationViewActivity` in Android Studio.
4. Wait for the puck to start moving along the route.
5. Move the map so that the `SummaryBottomSheet` hides.
6. Keep your eyes on the bottom of the device screen and then press the `RE-CENTER` button to go back to tracking the device location.
7. As the `SummaryBottomSheet` re-appears, look for any spaces at the bottom of the `SummaryBottomSheet` and/or any other sheet loading issues.

**Comment by abhishek1508** [comment]
Cannot reproduce the original issue. cc @langsmith

**Comment by langsmith** [comment]
Thanks for looking @abhishek1508. Any issues in `CustomUIComponentStyleActivity` on your device?

**Comment by abhishek1508** [comment]
Yeah I see this behavior in `CustomUIComponentStyleActivity`

**Comment by langsmith** [comment]
@abhishek1508 , you see the same weird loading behavior that is shown in my GIF above?

**Comment by abhishek1508** [comment]
Yes @langsmith

**Comment by JunDai** [comment]
> @abhishek1508 , you see the same weird loading behavior that is shown in my GIF above?

same here 🤔
