### ISSUE TITLE
Navigation drop-In UI (NavigationView.java) as a fragment implementation

### ISSUE THREAD

**Issue by btpasha90** [mapbox/mapbox-navigation-android#292]
According to some application requirements the navigation drop-in ui sometimes requires a fragment implementation. The current implementation is as an activity. Is there any current progress to provide that functionality in the next release? Thanks.

**Comment by danesfeder** [comment]
Landed in #180 - check out https://www.mapbox.com/android-docs/navigation/overview/navigation-ui/#custom-views to see how to do this in a `Fragment` implementation.  Thanks!

**Comment by m-harisqurashi** [comment]
@danesfeder [NavigationView](https://www.mapbox.com/android-docs/navigation/overview/navigation-ui/#navigationview) needs `onCreate`, `onBackPressed `and `onRestoreInstanceState` which doesn't allowed inside fragment implementation. As far as i understand given example is for activity only but for fragment we are unable to use NavigationView life cycle methods. 

As we can not call `navigationView.onCreate` inside Fragment's `onCreate` can we use `navigationView.onCreate(null)` inside `onCreateView `or `onViewCreated` but what about `onBackPressed `and `onRestoreInstanceState` in fragment.
