### ISSUE TITLE
    com.mapbox.mapboxsdk.style.sources.CannotAddSourceException: Source ****  already exists

### ISSUE THREAD

**Issue by abdelkawi** [mapbox/mapbox-navigation-android#2920]
i followed this tutorial to draw lines between two points 
[https://docs.mapbox.com/android/java/overview/directions/]

Code from doc : 
        loadedMapStyle.addSource( GeoJsonSource(ROUTE_SOURCE_ID))
        val iconGeoJsonSource = GeoJsonSource(
            ICON_SOURCE_ID , FeatureCollection.fromFeatures(
                arrayOf(
                    Feature.fromGeometry(
                        Point.fromLngLat(
                            origin.longitude(),
                            origin.latitude()
                        )
                    ),
                    Feature.fromGeometry(
                        Point.fromLngLat(
                            destination.longitude(),
                            destination.latitude()
                        )
                    )
                )
            )
        )
        loadedMapStyle.addSource(iconGeoJsonSource)

Error log : 
 com.mapbox.mapboxsdk.style.sources.CannotAddSourceException: Source Ehdathiat already exists
        at com.mapbox.mapboxsdk.maps.NativeMapView.nativeAddSource(Native Method)
        at com.mapbox.mapboxsdk.maps.NativeMapView.addSource(NativeMapView.java:905)
        at com.mapbox.mapboxsdk.maps.Style.addSource(Style.java:117)
        at com.ehdathiat.features.navigation.Navigation.initSource(Navigation.kt:248)
        at com.ehdathiat.features.navigation.Navigation.onSuccess(Navigation.kt:166)
        at com.ehdathiat.features.navigation.Navigation.onSuccess(Navigation.kt:56)
       

**Android Version : Android 8 
**Mapbox Navigation SDK version: 0.43.0-alpha.1

### Actual behavior
App crash

**Comment by Guardiola31337** [comment]
Closing this in favor of https://github.com/mapbox/mapbox-navigation-android/issues/2272

Thanks for reporting @abdelkawi
