### ISSUE TITLE
Route line and maneuver arrows flash when changing map style

### ISSUE THREAD

**Issue by cafesilencio** [mapbox/mapbox-navigation-android#2922]
**Android API:**
**Mapbox Navigation SDK version:**

### Steps to trigger behavior

 1. Open basic navigation example activity
 2. Long press map to create a route
 3. Start navigating
 4. Press the FAB to change the map style

### Expected behavior

The route line and the maneuver arrows shouldn't blink when the style changes.

### Actual behavior
They blink.  Also when vanish route line is enabled there is a split second when sometimes the line appears behind the puck.

**Comment by Guardiola31337** [comment]
As commented in https://github.com/mapbox/mapbox-navigation-android/pull/2919#pullrequestreview-407080527 this is a regression (fixed in the legacy) 👀 https://github.com/mapbox/mapbox-navigation-android/issues/2039 https://github.com/mapbox/mapbox-navigation-android/pull/2262 for reference.

**Comment by cafesilencio** [comment]
I have a PR to submit for this but it depends on #2938
