### ISSUE TITLE
Roundabout Triggers OffRoute 

### ISSUE THREAD

**Issue by danesfeder** [mapbox/mapbox-navigation-android#293]
We are seeing off-route triggers in roundabouts when the location is not off-route - with `MockLocationEngine`, some different UI thread freezing / other undetermined issues are occurring.

**Comment by Grsmto** [comment]
Hi @danesfeder 
From my understanding of the offRoute logic, the way the `futurePosition` is calculated in `userTrueDistanceFromStep` is that it takes the position + speed to compute the future user location but doesn't take the user direction into account so it looks forward only. That makes sense then that in a roundabout it can lead to an offRoute event as user is constantly turning. Probably related to #274 .

**Comment by danesfeder** [comment]
Awesome, thanks @Grsmto.  We are actively looking into both of these this week - will keep you / these tickets updated!

**Comment by danesfeder** [comment]
@Grsmto We are doing some test driving today with a potential fix for this today - still looking into the next leg issue.  cc @cammace

**Comment by Grsmto** [comment]
@danesfeder sounds cool! Enjoy the ride! :)

**Comment by cammace** [comment]
I've removed this from the 0.6.2 milestone for now but this issue should also have been fixed by resolving some snap to route issues. Can you check and make sure before closing @Grsmto when you get a chance on your next test drive?

**Comment by Grsmto** [comment]
@cammace sure. I'll probably do a test drive on Tuesday.

**Comment by danesfeder** [comment]
Fixed with #629
