### ISSUE TITLE
Camera takes the long way around corner

### ISSUE THREAD

**Issue by kmadsen** [mapbox/mapbox-navigation-android#2930]
Adding this issue for visibility. The new replay creates a bearing profile, but sometimes the bearing takes the long way around.

![output](https://user-images.githubusercontent.com/3021882/81339614-4dd22080-9063-11ea-9204-802217d72b31.gif)

**Comment by kmadsen** [comment]
I'm actually unsure what the bearings should be to fix this. Seems like our camera is taking the long way around

When the spin happens
-121.470011, 38.550903, bear=-70.6583
-121.470121, 38.550933, bear=-70.6583
-121.470231, 38.550964, bear=19.0377
-121.470200, 38.551033, bear=19.0378

My attempt to fix
```
-121.470084, 38.55092 bear=289.34163
-121.470157, 38.55094 bear=289.3415
-121.470231, 38.55096 bear=19.037791
-121.470219, 38.55098 bear=19.037798
```

**Comment by Guardiola31337** [comment]
It seems that https://github.com/mapbox/mapbox-navigation-android/issues/2676 wasn't fully addressed by https://github.com/mapbox/mapbox-navigation-android/pull/2781

cc @cafesilencio @LukasPaczos

**Comment by kmadsen** [comment]
I'm noticing that this issue was improved by
https://github.com/mapbox/mapbox-navigation-android/pull/2936/files#diff-d20a6fd389ed1bc093100e9c547608ecR57

specifically the lookAhead=2. changing back to 1 reproduces easier

**Comment by kmadsen** [comment]
The ReplayHistoryActivity will also reproduce the issue at the beginning, with read data. Here's what it looks like from my phone

![output](https://user-images.githubusercontent.com/3021882/81991592-7f646200-95f6-11ea-8f96-e5d42d51a12e.gif)

**Comment by LukasPaczos** [comment]
A possible fix is moving in https://github.com/mapbox/mapbox-gl-native-android/pull/426.

**Comment by LukasPaczos** [comment]
Maps bump landed, let's reopen if needed.
