### ISSUE TITLE
DirectionsRoute should hold information about request

### ISSUE THREAD

**Issue by cammace** [mapbox/mapbox-navigation-android#294]
For rerouting, we need to have information about the request so that we can unblock work in https://github.com/mapbox/mapbox-navigation-android/issues/129.

**Comment by ericrwolfe** [comment]
https://github.com/mapbox/mapbox-java/pull/580 will unblock this.

**Comment by cammace** [comment]
master now contains the directions 3.0 which adds `RouteOptions` inside the directionsRoute class.
