### ISSUE TITLE
Driving-traffic Api error!

### ISSUE THREAD

**Issue by JayJiangCT** [mapbox/mapbox-navigation-android#2949]
**Android API:** 29
**Mapbox Navigation SDK version:** 0.42.6

### Steps to trigger behavior

 1. When we were fetching a route with NavigationRoute's getRoute(), the response code returned 502.
 2. We check all parameters of this “directions/v5/mapbox/driving-traffic”, we found if we removed “annotations=congestion” and set enable_refresh as false, it'll make success. And also we found this question only happened in USA, the same request if we set coordinates of China, it is also successful.

### Expected behavior
Get the correct information of direction routes.
### Actual behavior
Http 502 happend

**Comment by Guardiola31337** [comment]
Hey @JayJiangCT thanks for the heads up.

This was resolved 👀 https://status.mapbox.com/incidents/8gfblkb9rzqq

Closing here.

**Comment by JayJiangCT** [comment]
Cool, thanks~😊

________________________________
发件人: Pablo Guardiola <notifications@github.com>
发送时间: 2020年5月12日 22:13:25
收件人: mapbox/mapbox-navigation-android <mapbox-navigation-android@noreply.github.com>
抄送: Jay Jiang <jayjiang@chancetop.com>; Mention <mention@noreply.github.com>
主题: Re: [mapbox/mapbox-navigation-android] Driving-traffic Api error! (#2949)


Hey @JayJiangCT<https://github.com/JayJiangCT> thanks for the heads up.

This was resolved 👀 https://status.mapbox.com/incidents/8gfblkb9rzqq

Closing here.
