### ISSUE TITLE
Alternative route traffic congestion applies to all lines

### ISSUE THREAD

**Issue by cafesilencio** [mapbox/mapbox-navigation-android#2953]
Due to the recent changes in the map route line being decorated with traffic congestion using a gradient line the alternative routes get decorated with the same traffic congestion. This is because the gradient line is applied to the layer and all alternative routes are on the same layer. 

A short term fix for this would be to not decorate the alternative route line layer with traffic congestion indicators.

**Comment by abhishek1508** [comment]
As discussed internally, I am closing this issue for the time being. We will discuss with product if this is a behavior we desire and can hook it up accordingly in our carbon based implementation.
cc @cafesilencio @zugaldia @LukasPaczos @Guardiola31337

**Comment by cafesilencio** [comment]
The current implementation does not decorate the alternative route lines with traffic congestion indicators.
