### ISSUE TITLE
Provide a production routing tiles endpoint

### ISSUE THREAD

**Issue by Guardiola31337** [mapbox/mapbox-navigation-android#2982]
Before releasing `1.0` we should provide a production routing tiles endpoint 👀 https://github.com/mapbox/mapbox-navigation-android/blob/43d7e2faa9d482c4c7872d7eab3cccbf2c72ca3b/libnavigation-core/src/main/java/com/mapbox/navigation/core/MapboxNavigation.kt#L697

cc @danpaz @Aurora-Boreal @mskurydin @LukasPaczos @zugaldia @asinghal22

**Comment by danpaz** [comment]
@Guardiola31337 @mskurydin the routing tiles endpoint is now available at `https://api.mapbox.com`.
