### ISSUE TITLE
Move Mock Location logic into Nav SDK

### ISSUE THREAD

**Issue by cammace** [mapbox/mapbox-navigation-android#299]
The `MockLocationEngine` currently lives in the Mapbox-Java repo but with the upcoming 3.0.0 of that release, it will remove the engine. One option and the one that makes the most sense to me is to move mock location logic into the navigation SDK directly for faster iteration and easier testability. I see no issue in moving it here since to my knowledge its only usage is inside this SDK. Thoughts @danesfeder @zugaldia?

**Comment by danesfeder** [comment]
@cammace Yep, makes perfect sense to me.

**Comment by zugaldia** [comment]
Another option is to have it as part of the location logic the upcoming standalone telemetry library is bringing. It already has engines for Play Services and LOST, adding Mock would be a natural fit. Having said that, that doesn't prevent navigation from having a more specialized Mock engine if needed.

cc: @Guardiola31337 @electrostat

**Comment by cammace** [comment]
I was going mainly off the ability to more frequently resolve bugs and improve the mock location. eventually, we will need to add additional features to mock location such as the ability to replay real routes captured during test drives.

**Comment by zugaldia** [comment]
> we will need to add additional features to mock location such as the ability to replay real routes captured during test drives.

Looks like telemetry could host a generic `MockLocationEngine` and navigation could use a separate `MockNavigationLocationEngine` (possibly a subclass) with specialized functionality.

**Comment by cammace** [comment]
Like that idea a lot

**Comment by danesfeder** [comment]
@cammace this landed in #373 right?
