### ISSUE TITLE
Fix MapboxHybridRouterTest#networkStatusService_cleanup_calledOnChannelClose flaky test

### ISSUE THREAD

**Issue by Guardiola31337** [mapbox/mapbox-navigation-android#3014]
`MapboxHybridRouterTest#networkStatusService_cleanup_calledOnChannelClose` is still failing from time to time 👀 

```
> Task :libdirections-hybrid:testDebugUnitTest

com.******.navigation.route.hybrid.MapboxHybridRouterTest > networkStatusService_cleanup_calledOnChannelClose FAILED
    java.lang.AssertionError at MapboxHybridRouterTest.kt:186
https://circleci.com/gh/mapbox/mapbox-navigation-android/26144?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link
```

https://circleci.com/gh/mapbox/mapbox-navigation-android/26144?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

Refs. https://github.com/mapbox/mapbox-navigation-android/pull/2944 https://github.com/mapbox/mapbox-navigation-android/pull/2862/files#diff-2599ac88e0bee88044eeca57cf0e8aa6L193

cc @cafesilencio @korshaknn

**Comment by korshaknn** [comment]
@Guardiola31337 we have the next problem:
when we call `networkStatusChannel.close()` we have the next chain:
`channel.close()` ->  cancel inner `coroutine` -> coroutine launches cancelation lambda -> `networkStatusService.cleanup` -> `context.unregister`

we have the problem with inner coroutine. It is `suspended` when we close a `channel`, so it doesn't have enough time to launch the whole chain above ^^. We call `Verify` too early.

I see here 2 options:
1. add a small delay. Just to give coroutine a time to wake up and launch a chain
```
every { context.unregisterReceiver(any()) } answers {}

(networkStatusService.getNetworkStatusChannel() as Channel).close()

delay(10)

verify { context.unregisterReceiver(any()) }
```

2. 
make `networkStatusJob` in `HybridRouter` `internal`. And wait until it is finished. Only then call `Verify`
```
every { context.unregisterReceiver(any()) } answers {}

(networkStatusService.getNetworkStatusChannel() as Channel).close()

hybridRouter.networkStatusJob.join()
        
verify { context.unregisterReceiver(any()) }
```

does it make sense?
