### ISSUE TITLE
Moving MapboxDistanceFormatter to Options pattern

### ISSUE THREAD

**Issue by kmadsen** [mapbox/mapbox-navigation-android#3016]
Notes while investigating solutions for https://github.com/mapbox/mapbox-navigation-android/issues/2709

MapboxDistanceFormatter is a required option for constructing navigation core. All the places it is needed are for user interfaces. I was wondering where to move the formatting logic code. DistanceFormatter creates dependencies that are not necessary for creating core navigation. Creating this ticket while exploring other possible solutions.

When removing the MapboxDistanceFormatter this is how the SDK crashes.
```
2020-05-21 17:05:37.935 21180-21180/com.mapbox.navigation.examples E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.mapbox.navigation.examples, PID: 21180
    MapboxInvalidModuleException(type=NavigationTripNotification)
        at com.mapbox.common.module.provider.MapboxModuleProvider.createModule(MapboxModuleProvider.kt:88)
```

**places that depend on MapboxDistanceFormatter**
1. [MapboxTripNotification](https://github.com/mapbox/mapbox-navigation-android/blob/cf3695d40b87d6be847c18d59a8696be8b9a19cf/libtrip-notification/src/main/java/com/mapbox/navigation/trip/notification/MapboxTripNotification.kt#L94-L96)
1. [NavigationViewModel](https://github.com/mapbox/mapbox-navigation-android/blob/cf3695d40b87d6be847c18d59a8696be8b9a19cf/libnavigation-ui/src/main/java/com/mapbox/navigation/ui/NavigationViewModel.java#L337-L346)
1. [InstructionView](https://github.com/mapbox/mapbox-navigation-android/blob/cf3695d40b87d6be847c18d59a8696be8b9a19cf/libnavigation-ui/src/main/java/com/mapbox/navigation/ui/instruction/InstructionView.java#L555-L559)
1. [SummaryBottomSheet](https://github.com/mapbox/mapbox-navigation-android/blob/cf3695d40b87d6be847c18d59a8696be8b9a19cf/libnavigation-ui/src/main/java/com/mapbox/navigation/ui/summary/SummaryBottomSheet.java#L252-L256)

**Module dependencies**
MapboxDistanceFormatter is in `core`, DistanceFormatter is in `base`, and `core` depends on `notification`. The dependencies take a significant digging to figure out.

**Conclusions**
Still investigating solutions, this issue served as notes while figuring out what the code is doing.

A couple concerns considered. It will be difficult to customize the MapboxTripNotification. The DistanceFormatter has unclear reasons for being a NavigationOption

**WIP**
Here is a branch that is attempting to remove DistanceFormatter from NavigationOptions
https://github.com/mapbox/mapbox-navigation-android/compare/km-distance-formatter-as-a-feature

**Comment by langsmith** [comment]
If any of this stuff gets changed, please make sure to adjust 1.0 nav docs. Not the IDE kdocs, but our more public 1.0 docs.

**Comment by carstenhag** [comment]
Hello, I am currently trying to integrate the 1.0.0-rc2 version, and am getting this exception. Should I create a new ticket for this or not?

```
     Caused by: MapboxInvalidModuleException(type=NavigationOnboardRouter)
        at com.mapbox.common.module.provider.MapboxModuleProvider.createModule(MapboxModuleProvider.kt:88)
        at com.mapbox.navigation.core.MapboxNavigation.paramsProvider(MapboxNavigation.kt:605)
        at com.mapbox.navigation.core.MapboxNavigation.access$paramsProvider(MapboxNavigation.kt:120)
        at com.mapbox.navigation.core.MapboxNavigation$2.invoke(MapboxNavigation.kt:157)
        at com.mapbox.navigation.core.MapboxNavigation$2.invoke(MapboxNavigation.kt:120)
        at com.mapbox.common.module.provider.MapboxModuleProvider$defaultMapboxModuleCreator$1.getInstance(MapboxModuleProvider.kt:135)
        at com.mapbox.common.module.provider.MapboxModuleProvider.createModule(MapboxModuleProvider.kt:66)
        at com.mapbox.navigation.core.MapboxNavigation.<init>(MapboxNavigation.kt:157)
        at com.mapbox.navigation.core.MapboxNavigation.<init>(MapboxNavigation.kt:128)
        at com.bmw.chargenow.presentation.activities.NavigationActivity.startNavigation(NavigationActivity.kt:145)
        at com.bmw.chargenow.presentation.activities.NavigationActivity.onCreate(NavigationActivity.kt:128)
        at android.app.Activity.performCreate(Activity.java:7955)
        at android.app.Activity.performCreate(Activity.java:7944)
```

The code. Note that I have no clue about the new SDK version and I am not sure if doing this right ;):

```
        val distanceFormatter = MapboxDistanceFormatter.builder()
                .withLocale(Locale.getDefault())
                .withUnitType(VoiceUnit.UNDEFINED)
                .withRoundingIncrement(Rounding.INCREMENT_TWENTY_FIVE)
                .build(this)

        val navigationOptions = NavigationOptions.Builder()
                .accessToken(ResourcesHelper.getString(R.string.mapbox_api_key))
                .distanceFormatter(distanceFormatter)
                .timeFormatType(TimeFormat.NONE_SPECIFIED)
                .build()
        
        mapboxNavigation = MapboxNavigation(
            applicationContext,
            navigationOptions,
            getLocationEngine()
        )
```

**Comment by kmadsen** [comment]
@carstenhag thanks for the issue comment. The [MapboxInvalidModuleException](https://github.com/mapbox/mapbox-navigation-android/issues?q=MapboxInvalidModuleException+) can happen whenever internal dependencies are not satisfied, so I'm also unsure exactly the cause from the stack trace and code snip.

Please try one of the [new beta versions](https://github.com/mapbox/mapbox-navigation-android/releases), will you try `1.1.0-beta.7`? You will need to update the MapboxNavigation constructor with the new version.

> Should I create a new ticket for this or not?

Please do! Also thanks for giving a stack trace, and the code you're using to set up the navigation sdk. It is very helpful 🥳

**Comment by carstenhag** [comment]
Oh, just came across this ticket again. Everything worked out fine, currently using 1.0.0-rc7. I think I had created an issue, but can't find it right now.

**Comment by Guardiola31337** [comment]
@kmadsen @carstenhag Where are we here? Are we good go close?

**Comment by kmadsen** [comment]
MapboxDistanceFormatter is not following the options pattern. This ticket describes all the things we need to to do migrate it

We can close as won't do, but otherwise this ticket is open
