### ISSUE TITLE
Add example of custom vanishing route line color

### ISSUE THREAD

**Issue by cafesilencio** [mapbox/mapbox-navigation-android#3025]
Modify the CustomUIComponentStyleActivity to demonstrate a custom color for the vanishing route line feature implemented in ticket #3021

**Comment by langsmith** [comment]
I'm good with whatever you decide to do. If there's a good amount of code needed to customize the route line, maybe consider making a completely separate example.

**Comment by cafesilencio** [comment]
My initial impression is that it won't be a lot of code. That activity was
suggested by pablo but if it turns out to be a lot I'll create a new
activity.

**Comment by langsmith** [comment]
Sounds good
