### ISSUE TITLE
Session State should be used to store step indices

### ISSUE THREAD

**Issue by cammace** [mapbox/mapbox-navigation-android#304]
To make offRoute increase the indices for step and leg we need a more abstract place to store index information for the remainder of the navigation session. SessionState is the ideal object for doing this and will unblock us here.

**Comment by cammace** [comment]
Moving off of the 0.6.2 release milestone since this will require additional testing and too risky to go into a bug release.

**Comment by danesfeder** [comment]
Closed by #667
