### ISSUE TITLE
Codecov migration to marketplace app

### ISSUE THREAD

**Issue by thomasrockhu** [mapbox/mapbox-navigation-android#3041]
Hi, Tom from [Codecov](https://codecov.io) here.

We noticed that you are using Codecov with fairly high frequency, and we’re so excited to see that! However, because you are not using our app, you may have experienced issues with uploading reports or viewing coverage information. This is due to rate-limiting issues from GitHub.

**In order to prevent any future outages, we ask that you move over to our [GitHub app integration](https://github.com/apps/codecov).**

The process is extremely simple and shouldn’t require more than a few clicks, and you should not expect any downtime. By moving to our app, you will no longer need an admin or separate account to manage the relationship with GitHub as the team bot.

Let me know if you have any questions, or if I can help at all with this process.

**Comment by Guardiola31337** [comment]
At some point we should take a look into this @mapbox/navigation-android 

Refs. https://github.com/mapbox/mapbox-navigation-android/issues/2655

**Comment by kmadsen** [comment]
Thanks @thomasrockhu, we've added the Codecov GitHub App to mapbox-navigation-android

**Comment by kmadsen** [comment]
@thomasrockhu so we have the Codecov app added. But we're not getting any codecov status reports commented on the pull requests. It sounds like it's supposed to work automatically, but there must be a setting that's not working. Would you know what's going on?

Here's a couple pull requests where all we're doing, is adding tests - and would like a codecov generated comment

current try: https://github.com/mapbox/mapbox-navigation-android/pull/3784
after app integration: https://github.com/mapbox/mapbox-navigation-android/pull/3771
before app integration: https://github.com/mapbox/mapbox-navigation-android/pull/3771

https://docs.codecov.io/docs/team-bot
![Screen Shot 2020-11-16 at 5 03 24 PM](https://user-images.githubusercontent.com/3021882/99326917-ab72d100-282d-11eb-983a-100285c4ad07.png)

https://codecov.io/gh/mapbox/mapbox-navigation-android/settings
![Screen Shot 2020-11-16 at 5 00 59 PM](https://user-images.githubusercontent.com/3021882/99326771-60f15480-282d-11eb-802c-c7ae686d7d93.png)

**Comment by thomasrockhu** [comment]
@kmadsen, thanks, we're taking a look to see why this might be. Thanks for your paitence.

**Comment by thomasrockhu** [comment]
Hi @kmadsen, actually it looks like Codecov didn't post because not all CI checks passed. You can bypass this with [this setting](https://docs.codecov.io/docs/codecovyml-reference#codecovrequire_ci_to_pass).

**Comment by kmadsen** [comment]
> Hi @kmadsen, actually it looks like Codecov didn't post because not all CI checks passed. You can bypass this with this setting.

Thanks! Ok closing for good.
