### ISSUE TITLE
Remove method invocation ordering in onboard router builder

### ISSUE THREAD

**Issue by LukasPaczos** [mapbox/mapbox-navigation-android#3049]
Refs https://github.com/mapbox/mapbox-navigation-android/pull/3020.
https://github.com/mapbox/mapbox-navigation-android/blob/526b008dc204e7083d1d01aabcc73be055a85df6/libnavigation-base/src/main/java/com/mapbox/navigation/base/options/OnboardRouterOptions.kt#L57-L69

It's great to see that we want to offer smart defaults! One way this could be improved even further - when exposing 2 separate builder methods that change the same field we are making the builder chain to be dependent on the invocation order, which should always be avoided because it's an easy mistake to make without knowing the internals or documentation of the SDK.
```
...
builder.filePath(...)
builder.internalFilePath(...)
builder.build()
```
```
...
builder.internalFilePath(...)
builder.filePath(...)
builder.build()
```
```
...
builder.internalFilePath(...)
builder.tilesUri(...)
builder.build()
```
```
...
builder.tilesUri(...)
builder.internalFilePath(...)
builder.build()
```
all result in different behavior and that's not what builder's users expect, each operation should be independent. Of course, this usage is incorrect, but at first glance, the `internal` path might be something completely different to an unfamiliar user who might suspect it needs to be provided as well, or that it's related to the tiles endpoint/version.

Instead of exposing `fun internalFilePath(context: Context)`, we should rather aim to expose a helper function that's outside of the builder, or a static extension, so that the user can call:
```
builder.filePath(FileSystemUtil.internalFilePath(context))
```

This way there's no opportunity to run into a mistake and it makes our APIs easier to use. Even better if we add the helper function's reference to the docs of the builder method.

/cc @mapbox/navigation-android

**Comment by Guardiola31337** [comment]
Briefly discussed in https://github.com/mapbox/mapbox-navigation-android/pull/3020#discussion_r429437384 but yeah makes total sense 👍

**Comment by kmadsen** [comment]
Yeah i thought about this too, but it's tricky because the file path depends on the builder options

```
val directoryVersion = "Offline/${tilesUri.host}/$tilesVersion/tiles"
```
^ notice tilesUri and tilesVersion. In this proposal, where does FileSystemUtil.internalFilePath(context) gain access to tilesUri and tilesVersion

I'm not in love with the build order either, but also not seeing how this fixes it

**Comment by kmadsen** [comment]
Another proposal in consideration and is not written. Is building something like a OnboardVersionManager

It would detect latest versions for a tilesUri.host, and would detect new or stale versions. Customers are asking for a way to remove tilesVersion from the request entirely

Something like that would also remove the need for this difficult to use helper function

**Comment by kmadsen** [comment]
maybe we don't need the tilesUri.host and tilesVersion in the path? That would also be nice to have a designated file.

Do we really need to save old versions and hosts forever?

**Comment by kmadsen** [comment]
@LukasPaczos can you clarify this issue? Are we removing `host` and `tilesVersion` from the file path so we can have a helper function like `FileSystemUtil.internalFilePath(context))`?

**Comment by LukasPaczos** [comment]
How about `FileSystemUtil.internalFilePath(context, tilesEndpoint, tilesVer))`? Since the user is setting those values on the builder anyway, they have access to them and can pass them to the factory as well. If they want to use the default endpoint/version values, they can get them from the default options instance.

**Comment by kmadsen** [comment]
> How about FileSystemUtil.internalFilePath(context, tilesEndpoint, tilesVer))? Since the user is setting those values on the builder anyway, they have access to them and can pass them to the factory as well. If they want to use the default endpoint/version values, they can get them from the default options instance.

With a helper function, that approach still requires clients to use the helper function to build default options. Which is against what we're trying to achieve here https://github.com/mapbox/mapbox-navigation-android/issues/3187

What if we put the default file directory inside or near the [MapboxOnboardRouter](https://github.com/mapbox/mapbox-navigation-android/blob/589c5a45a7cccddd6363b436699ccc525389ea2e/libdirections-onboard/src/main/java/com/mapbox/navigation/route/onboard/internal/MapboxOnboardRouter.kt#L65)? It could create a default one when the [OnboardRouterOptions.filePath](https://github.com/mapbox/mapbox-navigation-android/blob/589c5a45a7cccddd6363b436699ccc525389ea2e/libnavigation-base/src/main/java/com/mapbox/navigation/base/options/OnboardRouterOptions.kt#L34) was not set. Considering that a new version will create a stale file, this approach should also consider deleting stale files

@LukasPaczos

**Comment by LukasPaczos** [comment]
We're holding a strong reference to the app context right now, so we can use that to create the default, internal path in the `MapboxOnboardRouter` if there was none provided in the options :+1:
