### ISSUE TITLE
Test example activities for landscape orientation

### ISSUE THREAD

**Issue by abhishek1508** [mapbox/mapbox-navigation-android#3060]

**Comment by cafesilencio** [comment]
Tested the example activities in landscape orientation and created the following tickets: #3064 #3066
One outstanding issue I noticed was the feedback view but there is already a ticket addressing that.

**Comment by cafesilencio** [comment]
Reopening due to some overlooked testing scenarios.

I tested each example activity in landscape orientation looking for layout issues but I did not test the rotation itself.

**Comment by JunDai** [comment]
@cafesilencio - Fwiw, I did the same testing last Friday including the rotation and opened one ticket #3067 
Also, the `NavigationViewActivity` example has a lot of re-route when we rotate the screen. I am not sure if that's caused by the ReplayEngine. Feel free to create a ticket if you think it's an issue.

**Comment by abhishek1508** [comment]
Creating a list of these tailworks registered as separate issues in landscape mode:
- [ ] [#3064](https://github.com/mapbox/mapbox-navigation-android/issues/3064)
- [ ] [#3066](https://github.com/mapbox/mapbox-navigation-android/issues/3066)
- [ ] [#3067](https://github.com/mapbox/mapbox-navigation-android/issues/3067)
- [ ] [#3064](https://github.com/mapbox/mapbox-navigation-android/issues/3064)

**Comment by JunDai** [comment]
#3031
#3069 
were also related to landscape mode and they have been fixed.

**Comment by abhishek1508** [comment]
Closing as all the above mentioned issues are fixed.
