### ISSUE TITLE
Multiple same voice guidances will be played at same time again and again when rotating screen

### ISSUE THREAD

**Issue by JunDai** [mapbox/mapbox-navigation-android#3067]
**Android API:** Any
**Mapbox Navigation SDK version:** UI SDK 1.0

### Steps to trigger behavior

 1. Launch `example` app
 2. Launch `NavigationView` example in `Navigation UI SDK`
 3. Rotate screen when a voice guidance is playing

### Expected behavior
Only the voice guidance which was playing before screen rotation should keeps playing.

### Actual behavior
There will be two same voice guidances playing at the same time.

**Comment by cafesilencio** [comment]
This issue should be resolved in PR. https://github.com/mapbox/mapbox-navigation-android/pull/3124 once it is merged.
