### ISSUE TITLE
Memory leak when call MapboxNavigation.requestRoutes(options, callback)

### ISSUE THREAD

**Issue by evabishchevich** [mapbox/mapbox-navigation-android#3072]
#### Quick summary
User's callback is leaked during a `MapboxNavigation.requestRoutes(options, callback)` call.

#### Description
This callback is referenced [here](https://github.com/mapbox/mapbox-navigation-android/blob/e54d204565126b144c693de68d32b8dabddf1b5c/libdirections-hybrid/src/main/java/com/mapbox/navigation/route/hybrid/MapboxHybridRouter.kt#L82). 
The router is held by `MapboxDirectionSession` -> `RouteRefreshController` -> `MapboxTimer`. 
This timer stops only in the `MapboxNavigation.onDestroy` call, which can be never called by an end client application. In this case the user's callback will be leaked.

**Comment by Guardiola31337** [comment]
cc @kmadsen

**Comment by kmadsen** [comment]
Thanks for reporting! 

> The router is held by MapboxDirectionSession -> RouteRefreshController -> MapboxTimer.
This timer stops only in the MapboxNavigation.onDestroy call, which can be never called by an end client application. In this case the user's callback will be leaked.

What do you mean by "never called by end client application"? Do you mean the application no longer has resources from the Android OS? The purpose of MapboxNavigation.onDestroy is to [prevent memory leaks](https://docs.mapbox.com/android/navigation/overview/#prevent-memory-leaks)

🤔  but am wondering if we have other lifecycle issues here.

**Comment by kmadsen** [comment]
@evabishchevich will you include a sample app that shows MapboxTimer is running even after the app is destroyed? If this is reproducible we can fix or understand it.

But from the description, the behavior should not be possible. Android won't let an app continue to run after it has been destroyed
