### ISSUE TITLE
Route line does not vanish in example activities

### ISSUE THREAD

**Issue by abhishek1508** [mapbox/mapbox-navigation-android#3081]

**Comment by abhishek1508** [comment]
![ezgif com-optimize](https://user-images.githubusercontent.com/9770186/83563922-b7ade080-a4d0-11ea-89e4-379b5f335e0f.gif)

Not sure if it related to vanishing route line feature/replay engine
cc @cafesilencio @kmadsen

**Comment by cafesilencio** [comment]
It's probably just turned off. There was a change to one of the builders merged in today.
