### ISSUE TITLE
Re-route after arrival

### ISSUE THREAD

**Issue by benorgan** [mapbox/mapbox-navigation-android#3087]
**Android API: 29**
**Mapbox Navigation SDK version: 0.23.0**

We are trying to get Mapbox to continue re-routing after the user has arrived at the destination. This is in case they miss the destination and continue driving, we want to re-route them back to the destination. I believe this behaviour was changed in this PR: https://github.com/mapbox/mapbox-navigation-android/pull/667

### Steps to trigger behavior

![image](https://user-images.githubusercontent.com/5031585/83585101-cf4f8e00-a4fd-11ea-8903-572b269fcbd4.png) 
(Ignore the puck image being wrong, this only happens on the emulator for some reason)

To reproduce arrive at the destination (arrival state is triggered) and then continue moving past the destination.

### Expected behavior

Expect that there would be an option to allow re-routing after a user reaches the destination and then leaves, to show them how to get back to the destination. 

We want to be able to continually route to a destination until a new destination is set or the navigation is stopped. 

### Actual behavior

The old route is kept and re-routing does not happen. Additionally the `onArrival` event keeps getting triggered, even though the user has left the destination.

**Comment by benorgan** [comment]
This option seems to be available in iOS via `shouldPreventReroutesWhenArrivingAtWaypoint` (although it doesn't seem to work properly, see https://github.com/mapbox/mapbox-navigation-ios/issues/2346)

**Comment by Guardiola31337** [comment]
Hey @benorgan thanks for reaching out and report your issue.

Noticed from the issue report that you're on a really old version of the SDK (`v0.23.0`). Would you mind re-testing / confirming if OP is still an issue in `1.0.0`? You can review the developer [documentation](https://docs.mapbox.com/android/beta/navigation/overview/) to start building with the Mapbox Navigation SDK v1.0 for Android and check out the [migration guide](https://github.com/mapbox/mapbox-navigation-android/wiki/1.0-Navigation-SDK-Migration-Guide) to transition your project from the "legacy" Navigation SDK to the 1.0 version and let us know if you have any questions or run into issues. We would love your feedback.

**Comment by benorgan** [comment]
Hi @Guardiola31337 - my understanding is that the Navigation UI SDK is not yet available in `1.0.0` and we are using this too. Is it possible to upgrade the Navigation SDK in isolation?

**Comment by Guardiola31337** [comment]
Sure! First RC was released two weeks ago. Latest release available is `rc.6` https://github.com/mapbox/mapbox-navigation-android/releases/tag/release_ui_1.0.0-rc.6_core_1.0.0-rc.6

We appreciate any feedback you might have so that we can address it before going stable, thanks!

**Comment by sandyscoffable** [comment]
Just to say, this was an issue for me in the latest 2.0.0 beta versions, so doesn't appear to be fixed. 

I worked around it as follows:

```kotlin
    private val arrivalController: ArrivalController = object : ArrivalController {
        override fun arrivalOptions(): ArrivalOptions = ArrivalOptions.Builder()
            .arrivalInMeters(ARRIVAL_THRESHOLD_METRES)
            .build()

        override fun navigateNextRouteLeg(routeLegProgress: RouteLegProgress): Boolean {
            Log.i(TAG, "Mapbox: navigateNextRouteLeg")

            triggerRerouteIfDriverLeftWaypointGeofence()

            // We never skip on to the next waypoint. We always refresh the whole route when orders are marked as delivered.
            return false
        }


    private fun triggerRerouteIfDriverLeftWaypointGeofence() {
        val currentOrderLocation = ...
        val driverLocation = ...
        val distanceToWaypoint = currentOrderLocation?.let { driverLocation?.distanceTo(currentOrderLocation) }

        if(distanceToWaypoint != null && distanceToWaypoint > ARRIVAL_THRESHOLD_REROUTE_METRES){
            // Trigger a reroute so the driver knows how to get back to the waypoint
            MapboxNavigationProvider.retrieve().getRerouteController()?.reroute(object: RerouteController.RoutesCallback {
                override fun onNewRoutes(routes: List<DirectionsRoute>) {
                    viewModel.onRouteUpdate(routes[0])
                }
            })
        }
    }
```

`viewModel.onRouteUpdate(route)` is what we call when a route is originally fetched, or when a reroute occurs.

I've found that setting `ARRIVAL_THRESHOLD_METRES=50.0` and `ARRIVAL_THRESHOLD_REROUTE_METRES=75.0` works well (as I found the arrival was actually being triggered at just over 60 metres to the waypoint so with both variables set to the same value it was rerouting on approach).

HTH
