### ISSUE TITLE
NavigationView ReplayLocationEngine / simulation mode setup

### ISSUE THREAD

**Issue by Guardiola31337** [mapbox/mapbox-navigation-android#3091]
Integrating `ReplayLocationEngine` found:

- If a client wants to use the `ReplayLocationEngine` in the UI needs to enable the simulation mode and forget about adding a `LocationEngine` through the `NavigationViewOptions#locationEngine`. We should be explicit in the docs to avoid confusion as everything (`MapboxReplayer`, `ReplayProgressObserver`, etc.) is handled internally

cc @kmadsen @abhishek1508 @langsmith

**Comment by Guardiola31337** [comment]
Was this addressed already? @kmadsen @abhishek1508

**Comment by kmadsen** [comment]
Yeah this is addressed
