### ISSUE TITLE
Gradle can't resolve Navigation UI SDK beta

### ISSUE THREAD

**Issue by carstenhag** [mapbox/mapbox-navigation-android#3093]
Tried to use the newest beta of the UI SDK, but gradle doesn't find it. Beta:
https://github.com/mapbox/mapbox-navigation-android/releases/tag/prod_release_ui_1.0.0-beta.5_core_1.0.0-beta.5

**Android API:** 29, min API 21
**Mapbox Navigation SDK version:** Previously `"com.mapbox.mapboxsdk:mapbox-android-navigation-ui:0.42.4"`, now `"com.mapbox.mapboxsdk:mapbox-android-navigation-ui:1.0.0-beta.5"`. Also tried out `1.0.0-beta5`, `1.0.0-beta.1` and others.

Gradle config:

```gradle
allprojects {
    repositories {
        google()
        jcenter()
        mavenCentral()
        maven { url "https://jitpack.io" }
        maven { url 'https://mapbox.bintray.com/mapbox' }
        maven { url "http://oss.sonatype.org/content/repositories/snapshots/" }
    }
}
```

### Expected behavior
The lib gets resolved

### Actual behavior
It doesn't get resolved :(. Other beta libraries such as `implementation "com.google.android.material:material:1.2.0-beta01"` work.

**Comment by Guardiola31337** [comment]
Thanks for checking out the SDK @carstenhag 

We've just released [`release_core_1.0.0-rc.1`](https://github.com/mapbox/mapbox-navigation-android/releases/tag/release_core_1.0.0-rc.1) 🎉 🚀 

Please review the [developer documentation](https://docs.mapbox.com/android/beta/navigation/overview/#installation) to start building with the Mapbox core Navigation SDK v1.0 for Android and if you already use an older version of the Navigation SDK, check out [the migration guide](https://github.com/mapbox/mapbox-navigation-android/wiki/1.0-Navigation-SDK-Migration-Guide) to transition your project from the "legacy" core Navigation SDK to the 1.0 version and let us know if you have any questions or run into issues and please open tickets in https://github.com/mapbox/mapbox-navigation-android/issues/new and we will take it from there! We would love your feedback.

Thanks again!

**Comment by carstenhag** [comment]
Ah I see, I had only seen the Readme. Thanks a lot, will perhaps try this out in the next days.

**Comment by carstenhag** [comment]
I am now migrating to 1.0.0-rc2. I was a bit confused about this:

```
Add the following key-value pairs to your gradle.properties file:

MAPBOX_USERNAME=mapbox
MAPBOX_DOWNLOADS_TOKEN=PASTE_YOUR_SECRET_TOKEN_HERE
```

I had thought I would need to use the account's username there, but that gave errors. Not sure how this confusion could be avoided, just wanted to tell you about it.

**Comment by carstenhag** [comment]
This confusion can be avoided by instead of writing
 
```
username = project.properties['MAPBOX_USERNAME'] ?: ""
```

it should be 

```
username = "mapbox"
```
