### ISSUE TITLE
The Navigation voice guidance doesn't support Mandarin Chinese

### ISSUE THREAD

**Issue by JunDai** [mapbox/mapbox-navigation-android#3095]
**Android API:** Any
**Mapbox Navigation SDK version:** UI SDK 1.0

### Steps to trigger behavior

 1. Set device language to `Chinese`
 2. Launch `example` app
 3. Launch `NavigationView` example in the Navigation UI SDK

### Expected behavior

The navigation voice guidance works correctly.

### Actual behavior
The speach text is: `400米后右转，驶入West Las Positas Boulevard` But only played the alphanumeric part: `400 West Las Positas Boulevard`

cc: @Guardiola31337

**Comment by JunDai** [comment]
@chriswu42 : do we have navigation sdk or ui sdk user case in China?

**Comment by JunDai** [comment]
Close it here, since we have Mandarin support discussion somewhere else. I will subscribe that discussion.

**Comment by JunDai** [comment]
Just tested by hard-coding the `language` code to **`cmn-CN`**, Amazon Polly can support Mandarin Chinese.

**Comment by Guardiola31337** [comment]
For reference @JunDai we maintain the following `Supported languages` table https://github.com/mapbox/mapbox-navigation-android/blob/master/localization.md#supported-languages (Spoken instructions Mandarin Chinese is ✅).
