### ISSUE TITLE
LocationEngine is required when setting up the NavigationView

### ISSUE THREAD

**Issue by LukasPaczos** [mapbox/mapbox-navigation-android#3107]
Similarly to https://github.com/mapbox/mapbox-navigation-android/issues/3091, but from a different angle - when we don't want to use route simulation, the `NavigationView` requires us to pass a location engine in the options. If it's not provided, we'll crash with NPE.

Ideally, when the engine is not provided in options, we should just let `MapboxNavigation` use its default one.

@abhishek1508 @JunDai @cafesilencio

**Comment by Guardiola31337** [comment]
cc @kmadsen

**Comment by kmadsen** [comment]
LocationComponent also uses LocationEngine in it's own way https://github.com/mapbox/mapbox-navigation-android/issues/3057

Think we need one source for location engine options. We could add it NavigationOptions make sure the same engine is used everywhere.

**Comment by LukasPaczos** [comment]
> LocationComponent also uses LocationEngine in it's own way

As per https://github.com/mapbox/mapbox-navigation-android/issues/3057#issuecomment-635942564, it never does in the Nav UI SDK setup, so that shouldn't be an issue.

The current setup looks okay for the time being (with 2.0 in mind), the only missing piece is being able to not pass the engine to the `NavigationView` which would default to whatever `MapboxNavigaiton` offers.

**Comment by kmadsen** [comment]
One of the difficult things with LocationEngine, is that can be constructed in a few places. The quick fix is here https://github.com/mapbox/mapbox-navigation-android/pull/3171. But that was what the legacy code was doing and the SDK easily creates multiple LocationEngines (found some dev issues using this [instance counter](https://github.com/mapbox/mapbox-navigation-android/pull/3142/files#diff-4353ea9bfcc0b76a459c8fc841fe1ad3L34))

Similar to how we create multiple instances of MapboxNavigation, we create multiple instances of LocationEngine. An idea would be, force developers to override the LocationEngine using the LocationEngineProvider. That way there is a single source.
