### ISSUE TITLE
Test Drive 10/5

### ISSUE THREAD

**Issue by danesfeder** [mapbox/mapbox-navigation-android#311]
#### Core
- [ ] Bearing 360 intermittent on turns
- [ ] First step milestone urgent not called
- [x] Reroute ring buffer triggering off route every location update

#### UI 
- [ ] Reroute UI not showing 
- [x] LocationViewModel not activating location engine 

Still need to test:
- Roundabout off route & new leg off route scenarios (blocked by ring buffer issue on this drive)

**Comment by Snipedown** [comment]
@danesfeder @cammace 

Hello, as for the LocationViewModel not activating the location engine I believe it has to do with setting the locationEngine value after activating the engine, so the value of locationEngine is null in onConnected. Maybe something like:

      locationEngine.setInterval(0);
      this.locationEngine.setValue(locationEngine);
      locationEngine.activate();

Though not sure if this fully fixes the problem.

**Comment by cammace** [comment]
I've moved these issues into separate tickets for better tracking. Closing.
