### ISSUE TITLE
Research if we need DamerauLevenshteinAlgorithm to find similar routes

### ISSUE THREAD

**Issue by abhishek1508** [mapbox/mapbox-navigation-android#3116]

**Comment by 1ec5** [comment]
Currently, calculating an edit distance over the route summary (such as using the Damerau–Levenshtein algorithm) is the only way we have to efficiently determine similarity between two routes. The iOS navigation SDK calculates similarity to persist the user’s chosen route after a reroute. The edit distance approach is not only more efficient but also more reliable than comparing the geometries, as illustrated in mapbox/mapbox-navigation-ios#818.

**Comment by kmadsen** [comment]
> Could we potentially take advantage of direction response values? What would the results be like if we compared the remaining step in a route?

Responding to myself. Considering the code is already done for this, would be good to port it over and use it as is https://github.com/mapbox/mapbox-navigation-android/pull/808

If we add tests around the service usage of the algorithm, which appears to be [right here](https://github.com/mapbox/mapbox-navigation-android/pull/808/files#diff-8a07cfcf092f6c57fd1f4d0fc1a3016dR123-R128). Then we could verify current usage, and attempt new approaches

**Comment by kmadsen** [comment]
I haven't been able to find a test case where we need to use this algorithm. All the test cases compare the geometry strings https://github.com/mapbox/mapbox-navigation-android/pull/3262

**Comment by kmadsen** [comment]
Here's a draft that describes why this is not effective for comparing similar routes https://github.com/mapbox/mapbox-navigation-android/pull/3306

**Comment by kmadsen** [comment]
A method that appears to be effective, is comparing route step names. As described in this https://github.com/mapbox/mapbox-navigation-android/issues/3116#issuecomment-642077458

DamerauLevenshteinAlgorithm could be effective if we converted step names to a hash, and then compare how many step differences there are. It is a cool algorithm! But not seeing a practical use for it yet

**Comment by 1ec5** [comment]
> Comparing the number of character differences is not more effective

Agreed, it was only meant to be a crude (read: too precise) comparison. If we had a word-by-word comparison algorithm at the ready, we would’ve used it on iOS instead. Comparing the number of similar step names should be fine. We didn’t go with that way back in mapbox/mapbox-navigation-ios#818 because of a potential performance concern (comparing an arbitrary number of strings versus doing an edit distance calculation over a single string).

**Comment by 1ec5** [comment]
> Different streets are different streets. The number of character differences does not appear to add information

I’m pretty sure we were trying to account for cases like “North 1st Street” versus “1st Street”. At least in the U.S. with TIGER-imported data, cardinal directions can pop in and out arbitrarily even though it’s the same street in reality.
