### ISSUE TITLE
Example activities stop navigation when device is rotated

### ISSUE THREAD

**Issue by abhishek1508** [mapbox/mapbox-navigation-android#3117]
## Steps to reproduce:

1. Open the app
2. Go to Settings.
3. Select Simulate route
4. Go back
5. Go to Navigation Core SDK 
6. Click on Basic Navigation
7. Long press to select a destination
8. Start Navigation
9. Rotate the device

## Expected Results
The navigation should resume from where it was.

## Actual Results
The navigation stops and the route line disappears. 

_**Note:** We need to test this with real time location update as well like MockLocationApp. I have also tested `Replay Waypoints` activity and see the same result. We should ensure that all the activities that allow for navigation from source > destination should navigate if the device is rotated in midst of navigation_

Activities to fix:
- [x] SimpleMapboxNavigationKotlin
- [ ] GuidanceView
- [ ] Reroute events
- [x] Basic Navigation
- [ ] Basic Navigation With Fragment
- [ ] Free Drive Navigation
- [ ] Replay Route
- [ ] Replay Waypoints
- [x] Faster Route
- [x] InstructionView
- [x] SummaryBottomSheet
- [ ] Feedback Button
- [ ] Debug MapboxNavigation Kotlin
- [ ] Custom Route Styling Kotlin
- [ ] Navigation Map Route

**Comment by JunDai** [comment]
Since @cafesilencio has a PR to cover this, assign it to him.

**Comment by cafesilencio** [comment]
We decided to support rotation for strategic activities but not in all examples.
