### ISSUE TITLE
Example activities: Route line disappears when rotate device

### ISSUE THREAD

**Issue by abhishek1508** [mapbox/mapbox-navigation-android#3118]
## Steps to reproduce:

1. Open the app
2. Go to Navigation Core SDK 
3. Click on Basic Navigation
4. Long press to select a destination
5. Rotate the device

## Expected Results
The route line should still display from source to destination.

## Actual Results
The route line disappears

All activities has this problem and needs to be fixed. If this is fixed half of the problem in [#3117](https://github.com/mapbox/mapbox-navigation-android/issues/3117) will be fixed.

**Comment by cafesilencio** [comment]
The work was merged in PR https://github.com/mapbox/mapbox-navigation-android/pull/3130
