### ISSUE TITLE
InstructionView requires route progress before banner instructions

### ISSUE THREAD

**Issue by LukasPaczos** [mapbox/mapbox-navigation-android#3121]
When interacting with the `InstructionView`, it requires the `RouteProgress` value to be provided through
https://github.com/mapbox/mapbox-navigation-android/blob/058459d9336a2bd454394ba48732d5e4eb5af921/libnavigation-ui/src/main/java/com/mapbox/navigation/ui/instruction/InstructionView.java#L323

before we can provide banner instructions through
https://github.com/mapbox/mapbox-navigation-android/blob/058459d9336a2bd454394ba48732d5e4eb5af921/libnavigation-ui/src/main/java/com/mapbox/navigation/ui/instruction/InstructionView.java#L330

If not, the `currentStep` is not initialized and we run into:
```
Process: com.mapbox.onetap.app, PID: 4246
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.mapbox.api.directions.v5.models.LegStep.drivingSide()' on a null object reference
    at com.mapbox.navigation.ui.instruction.InstructionView.updateBannerInstructionsWith(InstructionView.java:330)
```

We should preferably remove this dependency, or reshape the `update*` APIs so a developer cannot make this mistake.

/cc @abhishek1508 @JunDai

**Comment by JunDai** [comment]
@LukasPaczos - I checked this issue yesterday.
I understand that it's not clear to developer that the `routeProgress` should be called first. It's something we can improve in the doc to clarify it.

I would think we shouldn't manually set `bannerInstructions` to InstructionView. Ideally we should only pass what ever we get from the `onNewBannerInstructions` callback.

Let me look at it more closely today.

**Comment by LukasPaczos** [comment]
> I understand that it's not clear to developer that the routeProgress should be called first.

Yes, that's the first issue, but the other is a general API design - it requires calling one method before the other, otherwise, we crash. We can document this, but preferably we should look into refactoring the APIs to make them safe.

**Comment by cafesilencio** [comment]
What if InstructionView implemented RouteProgressObserver and BannerInstructionObserver and classes that use InstructionView can register/unregister InstructionView itself as the observer for both event types? This way the instruction view class can handle the possibility of the step being null and the developer doesn't have to think about the underlying implementation.
