### ISSUE TITLE
Username must not be null!, BINTRAY_API_KEY =? BINTRAY_USER=?

### ISSUE THREAD

**Issue by weirenren** [mapbox/mapbox-navigation-android#3132]
**Android API:**
**Mapbox Navigation SDK version:**

### Steps to trigger behavior

 1. git pull latest version from master branch
 2. gradle sync

### Expected behavior
not error after syncing
### Actual behavior

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':examples:compileDebugJavaWithJavac'.
> Could not resolve all task dependencies for configuration ':examples:debugCompileClasspath'.
   > Could not resolve com.mapbox.navigator:mapbox-navigation-native:12.0.3.
     Required by:
         project :examples > project :libnavigator
      > Could not resolve com.mapbox.navigator:mapbox-navigation-native:12.0.3.
         > Could not get resource 'https://mapbox.bintray.com/mapbox_collab/com/mapbox/navigator/mapbox-navigation-native/12.0.3/mapbox-navigation-native-12.0.3.pom'.
            > Username must not be null!
      > Could not resolve com.mapbox.navigator:mapbox-navigation-native:12.0.3.
         > Could not get resource 'https://mapbox.bintray.com/mapbox_private/com/mapbox/navigator/mapbox-navigation-native/12.0.3/mapbox-navigation-native-12.0.3.pom'.
            > Username must not be null!
      > Could not resolve com.mapbox.navigator:mapbox-navigation-native:12.0.3.
         > Could not get resource 'https://oss.jfrog.org/artifactory/oss-snapshot-local/com/mapbox/navigator/mapbox-navigation-native/12.0.3/mapbox-navigation-native-12.0.3.pom'.
            > Could not GET 'https://oss.jfrog.org/artifactory/oss-snapshot-local/com/mapbox/navigator/mapbox-navigation-native/12.0.3/mapbox-navigation-native-12.0.3.pom'. Received status code 409 from server: 
      > Could not resolve com.mapbox.navigator:mapbox-navigation-native:12.0.3.
         > Could not get resource 'https://mapbox.bintray.com/mapbox_internal/com/mapbox/navigator/mapbox-navigation-native/12.0.3/mapbox-navigation-native-12.0.3.pom'.
            > Username must not be null!

**Comment by Guardiola31337** [comment]
Thanks for checking out the SDK @weirenren 

Please review the [developer documentation](https://docs.mapbox.com/android/beta/navigation/overview/#installation) to start building with the Mapbox core Navigation SDK v1.0 for Android. After adding that setup you should be able to build from source.

Let us know if you run into any issues or if you find something missing in the documentation.

Closing as answered.
