### ISSUE TITLE
Sub-banner instruction view with no data

### ISSUE THREAD

**Issue by LukasPaczos** [mapbox/mapbox-navigation-android#3133]
![Screenshot_20200606-155938](https://user-images.githubusercontent.com/16925074/84030400-48cefc80-a994-11ea-8345-d5611ad1aa8f.png)
![Screenshot_20200606-160220](https://user-images.githubusercontent.com/16925074/84030396-479dcf80-a994-11ea-9529-3d0461f9bd37.png)

I don't have any specific reproduction steps.

/cc @abhishek1508 @JunDai

**Comment by JunDai** [comment]
@LukasPaczos - would you mind to share the route info here for more info?
Meanwhile, I will try run some random routes to reproduce.

**Comment by Guardiola31337** [comment]
Some time ago run into a similar situation 👀 

> Run into an issue in which 2 sub-banners are displayed simultaneously when it should be only one 👀 
>
> ![two_sub_banners_displayed](https://user-images.githubusercontent.com/1668582/52738737-4bd2fc00-2f9d-11e9-96e2-f0584b5e2fab.png)
>
> [Route](https://api.mapbox.com/directions/v5/mapbox/driving-traffic/-122.423579,37.761689;-122.424467,37.761027;-122.428604,37.763559;-122.426183,37.760872?access_token=<ACCESS_TOKEN>&alternatives=true&geometries=polyline6&overview=full&steps=true&bearings=%3B%3B%3B&continue_straight=true&annotations=congestion%2Cdistance&language=en&roundabout_exits=true&voice_instructions=true&banner_instructions=true&voice_units=imperial) JSON response 👇 used when 👀 the issue:
>
> ```
> {"routes":[{"geometry":"yax_gA`pcohFRzIL|DzbBgHpCjiAadAfEy]xAvB||@PhHJhElBj|@l@`VpAfe@JfCJrBFfA_CAoBIgh@|BS@kn@jCgCN_DLmc@pB{@DGg@iL}qAmFel@o@gFlXmAr_@cBhVgAj]}AbCKbi@aCzBKdZqA`BI","legs":[{"annotation":{"distance":[15.340494073725246,8.389719258187162,178.2154322692742,104.9556116946616,123.21922079287214],"congestion":["heavy","low","low","heavy","low"]},"summary":"Guerrero Street, 19th Street","weight":214,"duration":121,"steps":[{"intersections":[{"out":0,"entry":[true],"bearings":[266],"location":[-122.423569,37.761581]}],"driving_side":"right","geometry":"yax_gA`pcohFRzI","mode":"driving","maneuver":{"bearing_after":266,"bearing_before":0,"location":[-122.423569,37.761581],"modifier":"right","type":"depart","instruction":"Head west on 18th Street"},"weight":19.7,"duration":7.6,"name":"18th Street","distance":15.3,"voiceInstructions":[{"distanceAlongGeometry":15.3,"announcement":"Head west on 18th Street, then turn left onto Guerrero Street","ssmlAnnouncement":"<speak><amazon:effect name=\"drc\"><prosody rate=\"1.08\">Head west on <say-as interpret-as=\"address\">18th</say-as> Street, then turn left onto Guerrero Street</prosody></amazon:effect></speak>"}],"bannerInstructions":[{"distanceAlongGeometry":15.3,"primary":{"text":"Guerrero Street","components":[{"text":"Guerrero Street","type":"text","abbr":"Guerrero St","abbr_priority":0}],"type":"turn","modifier":"left"},"secondary":null}]},{"intersections":[{"out":3,"in":1,"entry":[true,false,false,true],"bearings":[0,90,180,270],"location":[-122.423743,37.761571]},{"out":2,"in":1,"entry":[false,false,true,true],"bearings":[0,90,180,270],"location":[-122.423838,37.761564]}],"driving_side":"right","geometry":"eax_gA|zcohFL|DzbBgH","mode":"driving","maneuver":{"bearing_after":264,"bearing_before":264,"location":[-122.423743,37.761571],"modifier":"left","type":"turn","instruction":"Turn left onto Guerrero Street"},"weight":113.9,"duration":45.8,"name":"Guerrero Street","distance":186.6,"voiceInstructions":[{"distanceAlongGeometry":186.6,"announcement":"In 700 feet, turn right onto 19th Street","ssmlAnnouncement":"<speak><amazon:effect name=\"drc\"><prosody rate=\"1.08\">In 700 feet, turn right onto <say-as interpret-as=\"address\">19th</say-as> Street</prosody></amazon:effect></speak>"},{"distanceAlongGeometry":61.1,"announcement":"Turn right onto 19th Street, then turn right onto Oakwood Street","ssmlAnnouncement":"<speak><amazon:effect name=\"drc\"><prosody rate=\"1.08\">Turn right onto <say-as interpret-as=\"address\">19th</say-as> Street, then turn right onto Oakwood Street</prosody></amazon:effect></speak>"}],"bannerInstructions":[{"distanceAlongGeometry":186.6,"primary":{"text":"19th Street","components":[{"text":"19th Street","type":"text","abbr":"19th St","abbr_priority":0}],"type":"turn","modifier":"right"},"secondary":null},{"distanceAlongGeometry":61.1,"primary":{"text":"19th Street","components":[{"text":"19th Street","type":"text","abbr":"19th St","abbr_priority":0}],"type":"turn","modifier":"right"},"secondary":null,"sub":{"text":"Oakwood Street","components":[{"text":"Oakwood Street","type":"text","abbr":"Oakwood St","abbr_priority":0}],"type":"turn","modifier":"right"}}]},{"intersections":[{"out":3,"in":0,"entry":[false,true,true,true],"bearings":[0,90,180,270],"location":[-122.42369,37.759966]}],"driving_side":"right","geometry":"{|t_gArwcohFpCjiA","mode":"driving","maneuver":{"bearing_after":264,"bearing_before":175,"location":[-122.42369,37.759966],"modifier":"right","type":"turn","instruction":"Turn right onto 19th Street"},"weight":52.7,"duration":39.9,"name":"19th Street","distance":105,"voiceInstructions":[{"distanceAlongGeometry":39.5,"announcement":"Turn right onto Oakwood Street, then you will arrive at your 1st destination","ssmlAnnouncement":"<speak><amazon:effect name=\"drc\"><prosody rate=\"1.08\">Turn right onto Oakwood Street, then you will arrive at your 1st destination</prosody></amazon:effect></speak>"}],"bannerInstructions":[{"distanceAlongGeometry":105,"primary":{"text":"Oakwood Street","components":[{"text":"Oakwood Street","type":"text","abbr":"Oakwood St","abbr_priority":0}],"type":"turn","modifier":"right"},"secondary":null}]},{"intersections":[{"out":0,"in":1,"entry":[true,false,true],"bearings":[0,90,270],"location":[-122.42488,37.759893]}],"driving_side":"right","geometry":"ixt_gA~afohFadAfE","mode":"driving","maneuver":{"bearing_after":355,"bearing_before":264,"location":[-122.42488,37.759893],"modifier":"right","type":"turn","instruction":"Turn right onto Oakwood Street"},"weight":27.7,"duration":27.7,"name":"Oakwood Street","distance":123.2,"voiceInstructions":[{"distanceAlongGeometry":44.5,"announcement":"You have arrived at your 1st destination, on the right","ssmlAnnouncement":"<speak><amazon:effect name=\"drc\"><prosody rate=\"1.08\">You have arrived at your 1st destination, on the right</prosody></amazon:effect></speak>"}],"bannerInstructions":[{"distanceAlongGeometry":123.2,"primary":{"text":"You will arrive","components":[{"text":"You will arrive","type":"text"}],"type":"arrive","modifier":"right"},"secondary":null},{"distanceAlongGeometry":44.5,"primary":{"text":"You have arrived","components":[{"text":"You have arrived","type":"text"}],"type":"arrive","modifier":"right"},"secondary":null}]},{"intersections":[{"in":0,"entry":[true],"bearings":[176],"location":[-122.42498,37.760998]}],"driving_side":"right","geometry":"k}v_gAfhfohF","mode":"driving","maneuver":{"bearing_after":0,"bearing_before":356,"location":[-122.42498,37.760998],"modifier":"right","type":"arrive","instruction":"You have arrived at your 1st destination, on the right"},"weight":0,"duration":0,"name":"Oakwood Street","distance":0,"voiceInstructions":[],"bannerInstructions":[]}],"distance":430.1},{"annotation":{"distance":[54.9771500790541,87.39563769865288,13.140038246794482,8.906160657314265,86.5655895753425,32.54759440491205,54.00727365480747,6.016506091730257,5.1435369399108195,3.1966662010742297,7.119026275315115,6.244170527296902,73.61808180540797,1.1157333300859715,84.5339198126169,7.596030148810893,8.919367028985352,65.03833790856166],"congestion":["low","low","low","low","low","low","low","low","low","low","moderate","moderate","moderate","unknown","low","low","moderate","moderate"]},"summary":"18th Street, Church Street","weight":241.7,"duration":146.8,"steps":[{"intersections":[{"out":0,"entry":[true],"bearings":[356],"location":[-122.42498,37.760998]}],"driving_side":"right","geometry":"k}v_gAfhfohFy]xA","mode":"driving","maneuver":{"bearing_after":356,"bearing_before":0,"location":[-122.42498,37.760998],"modifier":"right","type":"depart","instruction":"Head north on Oakwood Street"},"weight":50.3,"duration":17.8,"name":"Oakwood Street","distance":55,"voiceInstructions":[{"distanceAlongGeometry":55,"announcement":"Head north on Oakwood Street, then turn left onto 18th Street","ssmlAnnouncement":"<speak><amazon:effect name=\"drc\"><prosody rate=\"1.08\">Head north on Oakwood Street, then turn left onto <say-as interpret-as=\"address\">18th</say-as> Street</prosody></amazon:effect></speak>"},{"distanceAlongGeometry":46.3,"announcement":"Turn left onto 18th Street","ssmlAnnouncement":"<speak><amazon:effect name=\"drc\"><prosody rate=\"1.08\">Turn left onto <say-as interpret-as=\"address\">18th</say-as> Street</prosody></amazon:effect></speak>"}],"bannerInstructions":[{"distanceAlongGeometry":55,"primary":{"text":"18th Street","components":[{"text":"18th Street","type":"text","abbr":"18th St","abbr_priority":0}],"type":"turn","modifier":"left"},"secondary":null}]},{"intersections":[{"out":2,"in":1,"entry":[true,false,true],"bearings":[90,180,270],"location":[-122.425025,37.761491]},{"out":3,"in":1,"entry":[true,false,false,true],"bearings":[0,90,180,270],"location":[-122.426016,37.761431]},{"out":3,"in":1,"entry":[false,false,true,true],"bearings":[0,90,180,270],"location":[-122.426165,37.761422]}],"driving_side":"right","geometry":"e|w_gA`kfohFvB||@PhHJhElBj|@l@`VpAfe@JfCJrBFfA","mode":"driving","maneuver":{"bearing_after":264,"bearing_before":355,"location":[-122.425025,37.761491],"modifier":"left","type":"turn","instruction":"Turn left onto 18th Street"},"weight":114.2,"duration":63.89999999999999,"name":"18th Street","distance":296.9,"voiceInstructions":[{"distanceAlongGeometry":296.9,"announcement":"In 1000 feet, turn right onto Church Street","ssmlAnnouncement":"<speak><amazon:effect name=\"drc\"><prosody rate=\"1.08\">In 1000 feet, turn right onto Church Street</prosody></amazon:effect></speak>"},{"distanceAlongGeometry":69.7,"announcement":"Turn right onto Church Street","ssmlAnnouncement":"<speak><amazon:effect name=\"drc\"><prosody rate=\"1.08\">Turn right onto Church Street</prosody></amazon:effect></speak>"}],"bannerInstructions":[{"distanceAlongGeometry":296.9,"primary":{"text":"Church Street","components":[{"text":"Church Street","type":"text","abbr":"Church St","abbr_priority":0}],"type":"turn","modifier":"right"},"secondary":null}]},{"intersections":[{"out":0,"in":1,"entry":[true,false,true,true],"bearings":[0,90,180,270],"location":[-122.428391,37.761281]},{"out":2,"in":0,"entry":[false,true,true],"bearings":[176,187,355],"location":[-122.428448,37.762061]},{"out":0,"in":1,"entry":[true,false,true],"bearings":[0,180,285],"location":[-122.428449,37.762071]},{"out":0,"in":2,"entry":[true,true,false,true],"bearings":[0,90,180,270],"location":[-122.428527,37.762897]}],"driving_side":"right","geometry":"aow_gAl}lohF_CAoBIgh@|BS@kn@jCgCN_DLmc@pB","mode":"driving","maneuver":{"bearing_after":357,"bearing_before":264,"location":[-122.428391,37.761281],"modifier":"right","type":"turn","instruction":"Turn right onto Church Street"},"weight":77.2,"duration":65.1,"name":"Church Street","distance":254.2,"voiceInstructions":[{"distanceAlongGeometry":254.2,"announcement":"In 900 feet, you will arrive at your 2nd destination","ssmlAnnouncement":"<speak><amazon:effect name=\"drc\"><prosody rate=\"1.08\">In 900 feet, you will arrive at your 2nd destination</prosody></amazon:effect></speak>"},{"distanceAlongGeometry":39,"announcement":"You have arrived at your 2nd destination","ssmlAnnouncement":"<speak><amazon:effect name=\"drc\"><prosody rate=\"1.08\">You have arrived at your 2nd destination</prosody></amazon:effect></speak>"}],"bannerInstructions":[{"distanceAlongGeometry":254.2,"primary":{"text":"You will arrive","components":[{"text":"You will arrive","type":"text"}],"type":"arrive","modifier":"straight"},"secondary":null},{"distanceAlongGeometry":39,"primary":{"text":"You have arrived","components":[{"text":"You have arrived","type":"text"}],"type":"arrive","modifier":"straight"},"secondary":null}]},{"intersections":[{"in":0,"entry":[true],"bearings":[176],"location":[-122.428591,37.76356]}],"driving_side":"right","geometry":"o}{_gA|imohF","mode":"driving","maneuver":{"bearing_after":0,"bearing_before":356,"location":[-122.428591,37.76356],"type":"arrive","instruction":"You have arrived at your 2nd destination"},"weight":0,"duration":0,"name":"Church Street","distance":0,"voiceInstructions":[],"bannerInstructions":[]}],"distance":606.1},{"annotation":{"distance":[3.3471995687676968,1.8139919316933948,119.06288475410283,64.93591606563429,10.543283705561633,45.398804473211,58.22634805717175,41.60799795770504,54.21373206255702,7.359869956670376,75.18409095390943,6.916183264284867,48.51757348320786,5.467793890900337],"congestion":["moderate","unknown","unknown","heavy","heavy","low","low","low","low","low","low","low","low","low"]},"summary":"Chula Lane, Dolores Street","weight":176.7,"duration":125.5,"steps":[{"intersections":[{"out":0,"entry":[true],"bearings":[355],"location":[-122.428591,37.76356]}],"driving_side":"right","geometry":"o}{_gA|imohF{@D","mode":"driving","maneuver":{"bearing_after":355,"bearing_before":0,"location":[-122.428591,37.76356],"type":"depart","instruction":"Head north on Church Street"},"weight":10.9,"duration":2.1,"name":"Church Street","distance":3.3,"voiceInstructions":[{"distanceAlongGeometry":3.3,"announcement":"Head north on Church Street, then turn right onto Chula Lane","ssmlAnnouncement":"<speak><amazon:effect name=\"drc\"><prosody rate=\"1.08\">Head north on Church Street, then turn right onto Chula Lane</prosody></amazon:effect></speak>"}],"bannerInstructions":[{"distanceAlongGeometry":3.3,"primary":{"text":"Chula Lane","components":[{"text":"Chula Lane","type":"text","abbr":"Chula Ln","abbr_priority":0}],"type":"turn","modifier":"right"},"secondary":null}]},{"intersections":[{"out":1,"in":2,"entry":[true,true,false],"bearings":[0,75,180],"location":[-122.428594,37.76359]},{"out":0,"in":2,"entry":[true,true,false],"bearings":[75,180,255],"location":[-122.427247,37.763807]}],"driving_side":"right","geometry":"k_|_gAbjmohFGg@iL}qAmFel@o@gF","mode":"driving","maneuver":{"bearing_after":77,"bearing_before":354,"location":[-122.428594,37.76359],"modifier":"right","type":"turn","instruction":"Turn right onto Chula Lane"},"weight":88.5,"duration":70.4,"name":"Chula Lane","distance":196.4,"voiceInstructions":[{"distanceAlongGeometry":196.4,"announcement":"In 700 feet, turn right onto Dolores Street","ssmlAnnouncement":"<speak><amazon:effect name=\"drc\"><prosody rate=\"1.08\">In 700 feet, turn right onto Dolores Street</prosody></amazon:effect></speak>"},{"distanceAlongGeometry":41.8,"announcement":"Turn right onto Dolores Street","ssmlAnnouncement":"<speak><amazon:effect name=\"drc\"><prosody rate=\"1.08\">Turn right onto Dolores Street</prosody></amazon:effect></speak>"}],"bannerInstructions":[{"distanceAlongGeometry":196.4,"primary":{"text":"Dolores Street","components":[{"text":"Dolores Street","type":"text","abbr":"Dolores St","abbr_priority":0}],"type":"turn","modifier":"right"},"secondary":null}]},{"intersections":[{"out":2,"in":3,"entry":[false,true,true,false],"bearings":[0,75,180,255],"location":[-122.426408,37.76395]},{"out":2,"in":0,"entry":[false,true,true],"bearings":[0,90,180],"location":[-122.426369,37.763543]},{"out":2,"in":0,"entry":[false,true,true,true],"bearings":[0,90,180,270],"location":[-122.426319,37.763021]},{"out":2,"in":0,"entry":[false,true,true],"bearings":[0,75,180],"location":[-122.426236,37.762162]},{"out":2,"in":0,"entry":[false,true,true,true],"bearings":[0,90,180,270],"location":[-122.426165,37.761422]}],"driving_side":"right","geometry":"{u|_gAnaiohFlXmAr_@cBhVgAj]}AbCKbi@aCzBKdZqA`BI","mode":"driving","maneuver":{"bearing_after":174,"bearing_before":77,"location":[-122.426408,37.76395],"modifier":"right","type":"turn","instruction":"Turn right onto Dolores Street"},"weight":77.3,"duration":53,"name":"Dolores Street","distance":342.9,"voiceInstructions":[{"distanceAlongGeometry":342.9,"announcement":"In a quarter mile, you will arrive at your destination","ssmlAnnouncement":"<speak><amazon:effect name=\"drc\"><prosody rate=\"1.08\">In a quarter mile, you will arrive at your destination</prosody></amazon:effect></speak>"},{"distanceAlongGeometry":64.7,"announcement":"You have arrived at your destination, on the right","ssmlAnnouncement":"<speak><amazon:effect name=\"drc\"><prosody rate=\"1.08\">You have arrived at your destination, on the right</prosody></amazon:effect></speak>"}],"bannerInstructions":[{"distanceAlongGeometry":342.9,"primary":{"text":"You will arrive","components":[{"text":"You will arrive","type":"text"}],"type":"arrive","modifier":"right"},"secondary":null},{"distanceAlongGeometry":64.7,"primary":{"text":"You have arrived","components":[{"text":"You have arrived","type":"text"}],"type":"arrive","modifier":"right"},"secondary":null}]},{"intersections":[{"in":0,"entry":[true],"bearings":[355],"location":[-122.426113,37.760876]}],"driving_side":"right","geometry":"wuv_gA`ohohF","mode":"driving","maneuver":{"bearing_after":0,"bearing_before":175,"location":[-122.426113,37.760876],"modifier":"right","type":"arrive","instruction":"You have arrived at your destination, on the right"},"weight":0,"duration":0,"name":"Dolores Street","distance":0,"voiceInstructions":[],"bannerInstructions":[]}],"distance":542.6}],"weight_name":"routability","weight":632.4,"duration":393.3,"distance":1578.8000000000002,"voiceLocale":"en-US"}],"waypoints":[{"distance":12.01923082964461,"name":"18th Street","location":[-122.423569,37.761581]},{"distance":45.310961127107014,"name":"Oakwood Street","location":[-122.42498,37.760998]},{"distance":1.1506955205190237,"name":"Church Street","location":[-122.428591,37.76356]},{"distance":6.183122158692856,"name":"Dolores Street","location":[-122.426113,37.760876]}],"code":"Ok","uuid":"cjs3lp2lc0aju77o6oin301h6"}
> ```
>
> After some 🕵️ we found that these instructions are in different banner instructions i.e. step 3 has the line guidance with those 4 different lanes and step 4 has `GWMP`.
>
> So it seems we’re not removing / updating the first instruction somehow.

cc @JunDai @LukasPaczos @mskurydin

**Comment by JunDai** [comment]
@LukasPaczos - this ticket has two issues. The first screenshot with blank sub instruction is caused by an `attr` missing issue. The second screenshot is same issue as @Guardiola31337 mentioned, I have a PR #3137 to fix the second one. 

The first issue might takes me some times to fix it. I will create a temporary workaround PR in 1TAP before I completely fix it in UI SDK side.
