### ISSUE TITLE
Enable congestion for alternative routes

### ISSUE THREAD

**Issue by LukasPaczos** [mapbox/mapbox-navigation-android#3147]
https://github.com/mapbox/mapbox-navigation-android/issues/3146 follow up. We generate the alternative layers dynamically (or add a number of empty alternative layers that match the Directions API's limit of alternative routes) and style the congestion gradient separately.

/cc @cafesilencio @coxchapman @AnnaStaley

**Comment by Guardiola31337** [comment]
Is https://github.com/mapbox/mapbox-navigation-android/pull/3203 solving / addressing this @cafesilencio? It seems so 😅

**Comment by cafesilencio** [comment]
It could, I'll test it.

**Comment by cafesilencio** [comment]
@Guardiola31337 No that ticket you refer to won't take care of this one. The route coloring is data driven so I can set properties on the lines to change their colors but the gradient which is used to color traffic congestion is NOT data driven.  Either the maps team needs to make the gradient data driven or we need to put each alternative route on its own layer.

**Comment by LukasPaczos** [comment]
If we're planning to address this issue in 1.0, we'll face a challenge with the current implementation of the `RouteLineLayerIds` used for the `MapRouteLineInitializedCallback`:
https://github.com/mapbox/mapbox-navigation-android/blob/14b836dcdecf23a50d5d46ae8de9a7a75329f8fb/libnavigation-ui/src/main/java/com/mapbox/navigation/ui/route/RouteLineLayerIds.kt#L10-L14

Modifying this data class to expose a list of alternative layers will be a breaking change. @cafesilencio would you be able to refactor this data class now, to make it extensible/modifiable in the future?

**Comment by LukasPaczos** [comment]
Actually, I tried to address above in https://github.com/mapbox/mapbox-navigation-android/pull/3436 by simply making the alternative IDs a list. Let me know if there's a better way though.

**Comment by cafesilencio** [comment]
I think what you did in #3436 would be enough.

**Comment by Guardiola31337** [comment]
Where are we here @cafesilencio? Good to close?

**Comment by cafesilencio** [comment]
The functionality exists for 2.x but not for 1.x.

**Comment by Guardiola31337** [comment]
Good to close @cafesilencio?

**Comment by cafesilencio** [comment]
Closing this as 2.x displays traffic congestion for alternative routes.
