### ISSUE TITLE
Can't install the latest version of the library

### ISSUE THREAD

**Issue by Babich-anton** [mapbox/mapbox-navigation-android#3148]
**Android API:** min: 21, target: 29
**Mapbox Navigation SDK version:** com.mapbox.navigation:core:1.0.0-rc.1

### Steps to trigger behavior

 1. Use documentation to configure library: https://docs.mapbox.com/android/beta/navigation/overview/
 2. Created secret code
 3. Unable to resolve dependency for ':app@debug/compileClasspath': Could not resolve com.mapbox.navigation:core:1.0.0-rc.1.

### build.gradle:

buildscript {
    ext.kotlin_version = '1.3.72'
    repositories {
        google()
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:4.0.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath "androidx.navigation:navigation-safe-args-gradle-plugin:2.3.0-beta01"

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        google()
        jcenter()
        maven {
            url "https://maven.google.com"
        }
        maven {
            url 'https://api.mapbox.com/downloads/v1/navigation/android/maven'
            authentication {
                basic(BasicAuthentication)
            }
            credentials {
                username = project.properties['MapboxUsername'] ?: ""
                password = project.properties['MapboxSecretAccessToken'] ?: ""
            }
        }
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}

### build.gradle (:app)

apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply plugin: 'kotlin-android-extensions'
apply plugin: 'kotlin-kapt'
apply plugin: 'androidx.navigation.safeargs.kotlin'

android {
    compileSdkVersion 29
    buildToolsVersion "29.0.2"

    defaultConfig {
        applicationId "by.sqilsoft.avedi.navigation.android"
        minSdkVersion 21
        targetSdkVersion 29
        versionCode 2
        versionName "0.0.2"
    }

    buildTypes {
        debug {
            buildConfigField 'String', "MapboxSecretAccessToken", MAPBOX_DOWNLOADS_TOKEN
            buildConfigField 'String', "MapboxUsername", MAPBOX_USERNAME
        }
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            buildConfigField 'String', "MapboxSecretAccessToken", MAPBOX_DOWNLOADS_TOKEN
            buildConfigField 'String', "MapboxUsername", MAPBOX_USERNAME
        }
    }

    buildFeatures {
        dataBinding = true
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    kotlinOptions {
        jvmTarget = "1.8"
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    implementation 'androidx.core:core-ktx:1.3.0'
    implementation 'androidx.lifecycle:lifecycle-extensions:2.2.0'
    implementation 'androidx.lifecycle:lifecycle-viewmodel-ktx:2.2.0'

    // UI
    implementation 'androidx.appcompat:appcompat:1.1.0'
    implementation 'androidx.constraintlayout:constraintlayout:1.1.3'
    implementation 'com.google.android.material:material:1.1.0'
    implementation 'androidx.legacy:legacy-support-v4:1.0.0'
    implementation 'androidx.navigation:navigation-fragment:2.3.0-beta01'
    implementation 'androidx.navigation:navigation-ui:2.3.0-beta01'
    implementation 'androidx.navigation:navigation-fragment-ktx:2.3.0-beta01'
    implementation 'androidx.navigation:navigation-ui-ktx:2.3.0-beta01'
    implementation "androidx.navigation:navigation-dynamic-features-fragment:2.3.0-beta01"

    // Data binding
    kapt "com.android.databinding:compiler:3.1.4"

    // Requests
    implementation 'com.squareup.retrofit2:retrofit:2.9.0'
    implementation 'com.squareup.retrofit2:converter-gson:2.9.0'

    // Auth
    implementation 'de.adorsys.android:securestoragelibrary:1.2.4'
    implementation 'androidx.biometric:biometric:1.0.1'

    // Barcode
    implementation 'com.google.android.gms:play-services-vision:20.1.0'

    // Mapbox
    implementation 'com.mapbox.navigation:core:1.0.0-rc.1'
}

### gradle.properties

org.gradle.jvmargs=-Xmx1536m
android.useAndroidX=true
android.enableJetifier=true
kotlin.code.style=official
MAPBOX_USERNAME = "login"
MAPBOX_DOWNLOADS_TOKEN = "sk.eyJ1IjoiYW....."

**Comment by abhishek1508** [comment]
Hi @Babich-anton 
We made some changes and think it will work. Could you please let me know if it's working for you now. 

Please **remove** the following lines

`app/build.gradle`
```
debug {
    buildConfigField 'String', "MapboxSecretAccessToken", API_DOWNLOAD_TOKEN_PRODUCTION
    buildConfigField 'String', "MapboxUsername", API_DOWNLOAD_USER
}

release {
    buildConfigField 'String', "MapboxSecretAccessToken", API_DOWNLOAD_TOKEN_PRODUCTION
    buildConfigField 'String', "MapboxUsername", API_DOWNLOAD_USER
}
```

**Comment by abhishek1508** [comment]
This would be the final code for project level and app level build.gradle

`project/build.gradle`

```
// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    ext.kotlin_version = '1.3.72'
    repositories {
        google()
        jcenter()
        
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:4.0.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath "androidx.navigation:navigation-safe-args-gradle-plugin:2.3.0-beta01"
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        google()
        jcenter()
        maven {
            url "https://maven.google.com"
        }
        maven {
            url 'https://api.mapbox.com/downloads/v1/navigation/android/maven'
            authentication {
                basic(BasicAuthentication)
            }
            credentials {
                username = project.properties['API_DOWNLOAD_USER'] ?: ""
                password = project.properties['API_DOWNLOAD_TOKEN_PRODUCTION'] ?: ""
            }
        }
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}

```

`app/build.gradle`

```
apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply plugin: 'kotlin-android-extensions'
apply plugin: 'kotlin-kapt'
apply plugin: 'androidx.navigation.safeargs.kotlin'

android {
    compileSdkVersion 29
    buildToolsVersion "29.0.2"

    defaultConfig {
        applicationId "com.example.mviexample"
        minSdkVersion 21
        targetSdkVersion 29
        versionCode 2
        versionName "0.0.2"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    buildFeatures {
        dataBinding = true
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    kotlinOptions {
        jvmTarget = "1.8"
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    implementation 'androidx.core:core-ktx:1.3.0'
    implementation 'androidx.lifecycle:lifecycle-extensions:2.2.0'
    implementation 'androidx.lifecycle:lifecycle-viewmodel-ktx:2.2.0'

    implementation 'androidx.appcompat:appcompat:1.1.0'
    implementation 'androidx.constraintlayout:constraintlayout:1.1.3'
    implementation 'com.google.android.material:material:1.1.0'
    implementation 'androidx.legacy:legacy-support-v4:1.0.0'
    implementation 'androidx.navigation:navigation-fragment:2.3.0-beta01'
    implementation 'androidx.navigation:navigation-ui:2.3.0-beta01'
    implementation 'androidx.navigation:navigation-fragment-ktx:2.3.0-beta01'
    implementation 'androidx.navigation:navigation-ui-ktx:2.3.0-beta01'
    implementation "androidx.navigation:navigation-dynamic-features-fragment:2.3.0-beta01"

    // Data binding
    kapt "com.android.databinding:compiler:3.1.4"

    // Requests
    implementation 'com.squareup.retrofit2:retrofit:2.9.0'
    implementation 'com.squareup.retrofit2:converter-gson:2.9.0'

    // Auth
    implementation 'de.adorsys.android:securestoragelibrary:1.2.4'
    implementation 'androidx.biometric:biometric:1.0.1'

    // Barcode
    implementation 'com.google.android.gms:play-services-vision:20.1.0'

    // Mapbox
    implementation 'com.mapbox.navigation:core:1.0.0-rc.1'

    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'androidx.test.ext:junit:1.1.1'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.2.0'
}

```

**Comment by Babich-anton** [comment]
@abhishek1508 This works, thank you very much for your help!)
