### ISSUE TITLE
Could not resolve com.mapbox.navigation:core:1.0.0-rc.1.

### ISSUE THREAD

**Issue by peytonwupeixin** [mapbox/mapbox-navigation-android#3155]
**Android API:**
**Mapbox Navigation SDK version:**

### Steps to trigger behavior

 1.Config my Mapbox username ,public access token and secret access token ,as https://docs.mapbox.com/android/beta/navigation/overview/#installation
 2.build my project 
 

### Expected behavior
build success
### Actual behavior
   > Could not resolve com.mapbox.navigation:core:1.0.0-rc.1.
     Required by:
         project :app > project :module_mapbox
      > Could not resolve com.mapbox.navigation:core:1.0.0-rc.1.
         > Could not get resource 'https://api.mapbox.com/downloads/v1/navigation/android/maven/com/mapbox/navigation/core/1.0.0-rc.1/core-1.0.0-rc.1.pom'.
            > Could not GET 'https://api.mapbox.com/downloads/v1/navigation/android/maven/com/mapbox/navigation/core/1.0.0-rc.1/core-1.0.0-rc.1.pom'. Received status code 403 from server: Forbidden

**Comment by abhishek1508** [comment]
Hi @peytonwupeixin 

Thank you for checking out the Navigation SDK v1.0 beta.

We are working to update the docs on this error message you see above. Meanwhile all you need to is the following:

This would be the final code for project level and app level build.gradle

`project/build.gradle`

```
// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    ext.kotlin_version = '1.3.72'
    repositories {
        google()
        jcenter()
        
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:4.0.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        google()
        jcenter()
        maven {
            url 'https://api.mapbox.com/downloads/v1/navigation/android/maven'
            authentication {
                basic(BasicAuthentication)
            }
            credentials {
                username = project.properties['MAPBOX_USER'] ?: ""
                password = project.properties['MAPBOX_TOKEN'] ?: ""
            }
        }
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}

```

`app/build.gradle`

```
apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply plugin: 'kotlin-android-extensions'

android {
    compileSdkVersion 29
    buildToolsVersion "29.0.2"

    defaultConfig {
        applicationId "com.example.example"
        minSdkVersion 21
        targetSdkVersion 29
        versionCode 2
        versionName "0.0.2"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    buildFeatures {
        dataBinding = true
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    kotlinOptions {
        jvmTarget = "1.8"
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"

    // Mapbox
    implementation 'com.mapbox.navigation:core:1.0.0-rc.1'

    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'androidx.test.ext:junit:1.1.1'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.2.0'
}
```

where `MAPBOX_USER=mapbox` and `MAPBOX_TOKEN=sk.something,i.created`

**Comment by Guardiola31337** [comment]
Thanks for checking out the SDK @peytonwupeixin 

Feel free to re-open here if above answered doesn't solve OP and cut new tickets if you have any other questions or run into any other issues 🙇 

Closing as answered.
