### ISSUE TITLE
Status code 403

### ISSUE THREAD

**Issue by Tiraino** [mapbox/mapbox-navigation-android#3158]
Hello!

At first I was trying to follow this tutorial: https://docs.mapbox.com/help/tutorials/android-navigation-sdk/
After having some issues and asking for help, I was told to follow this link: https://docs.mapbox.com/android/beta/navigation/overview/#installation

I followed the installation guide, but when I try to build the project, the build output return this:
>Received status code 403 from server: Forbidden

And there is also a link who give me that message: {"message":"Not Authorized - No Token"}

I've created a token and put it correctly in the project, I don't understand why it doesn't work.

How can I fix this?

**Android API: 26**

**Comment by abhishek1508** [comment]
Hey @Tiraino Thank you for checking out the Navigation SDK v1.0 beta.

We are working to update the docs on this error message you see above. Meanwhile all you need to is the following:

This would be the final code for project level and app level build.gradle

`project/build.gradle`

```
// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    ext.kotlin_version = '1.3.72'
    repositories {
        google()
        jcenter()
        
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:4.0.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        google()
        jcenter()
        maven {
            url 'https://api.mapbox.com/downloads/v1/navigation/android/maven'
            authentication {
                basic(BasicAuthentication)
            }
            credentials {
                username = project.properties['MAPBOX_USER'] ?: ""
                password = project.properties['MAPBOX_TOKEN'] ?: ""
            }
        }
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}

```

`app/build.gradle`

```
apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply plugin: 'kotlin-android-extensions'

android {
    compileSdkVersion 29
    buildToolsVersion "29.0.2"

    defaultConfig {
        applicationId "com.example.example"
        minSdkVersion 21
        targetSdkVersion 29
        versionCode 2
        versionName "0.0.2"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    buildFeatures {
        dataBinding = true
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    kotlinOptions {
        jvmTarget = "1.8"
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"

    // Mapbox
    implementation 'com.mapbox.navigation:core:1.0.0-rc.1'

    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'androidx.test.ext:junit:1.1.1'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.2.0'
}
```

where `MAPBOX_USER=mapbox` and `MAPBOX_TOKEN=sk.something,i.created`

**Comment by Tiraino** [comment]
@abhishek1508 Thank for the answer!
I forgot to mention that I'm working with Java and not kotlin, does it matter?

**Comment by Guardiola31337** [comment]
@Tiraino 
> I forgot to mention that I'm working with Java and not kotlin, does it matter?

Not at all, we do integrate Java compatibility for Java users 🎉 

One thing to note though is that we use Java 8 👀 

Thanks for checking out and let us know if you have any other questions or run into any other issues 🙇 

Closing as answered.

**Comment by Tiraino** [comment]
@abhishek1508 The only difference between the code you sharded and the guide is the "complieOptions". I replicate it in my code (and also I wrote my Username and token access directly in the project/build.gradle), but I still get the error 403.

**Comment by abhishek1508** [comment]
@Tiraino 
This is the key 
`where MAPBOX_USER=mapbox and MAPBOX_TOKEN=sk.something,i.created`
Please make sure that the user is `mapbox`

You can see the updated instructions here https://docs.mapbox.com/android/beta/navigation/overview/#installation

**Comment by Tiraino** [comment]
@abhishek1508 I've tried the change, but it still doesn't work.
Here is the exact message I get:

Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'.
> Could not resolve all task dependencies for configuration ':app:debugCompileClasspath'.
   > Could not resolve com.mapbox.navigation:core:1.0.0-rc.1.
     Required by:
         project :app
      > Could not resolve com.mapbox.navigation:core:1.0.0-rc.1.
         > Could not get resource 'https://api.mapbox.com/downloads/v1/navigation/android/maven/com/mapbox/navigation/core/1.0.0-rc.1/core-1.0.0-rc.1.pom'.
            > Could not GET 'https://api.mapbox.com/downloads/v1/navigation/android/maven/com/mapbox/navigation/core/1.0.0-rc.1/core-1.0.0-rc.1.pom'. Received status code 403 from server: Forbidden

(Sorry for taking a bit of your time)

**Comment by abhishek1508** [comment]
@Tiraino Can you please share your `app/build.gradle` and `project/buid.gradle` here?
Thanks

**Comment by Tiraino** [comment]
Sure, here it is:
project/build.gradle
````
// Top-level build file where you can add configuration options common to all sub-projects/modules.
buildscript {
    repositories {
        google()
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.6.2'
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}
allprojects {
    repositories {
        google()
        jcenter()
        maven{
            url 'https://api.mapbox.com/downloads/v1/navigation/android/maven'
            authentication {
                basic(BasicAuthentication)
            }
            credentials {
                username = project.properties['mapbox'] ?: ""
                password = project.properties['sk.eyJ1IjoidGlyYWlubyIsImEiOiJja2JhemI1cXEwYXIyMzBtYnE3NWhjN3F3In0.ij0fmg_SCYZbqXKYWR9fYg'] ?: ""
            }
        }
    }
}
task clean(type: Delete) {
    delete rootProject.buildDir
}
```
app/build.gradle
```
apply plugin: 'com.android.application'

android {
    compileSdkVersion 29
    buildToolsVersion "29.0.3"

    defaultConfig {
        applicationId "com.example.testnavi"
        minSdkVersion 26
        targetSdkVersion 29
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        debug {
            buildConfigField 'String', "MapboxSecretAccessToken", MAPBOX_DOWNLOADS_TOKEN
            buildConfigField 'String', "MapboxUsername", MAPBOX_USERNAME
        }
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            buildConfigField 'String', "MapboxSecretAccessToken", MAPBOX_DOWNLOADS_TOKEN
            buildConfigField 'String', "MapboxUsername", MAPBOX_USERNAME
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])

    //mapbox dependencies
    implementation 'com.mapbox.navigation:core:1.0.0-rc.1'

    implementation 'androidx.appcompat:appcompat:1.1.0'
    implementation 'androidx.constraintlayout:constraintlayout:1.1.3'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'androidx.test.ext:junit:1.1.1'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.2.0'
}

```
(I will change my access token later)

**Comment by abhishek1508** [comment]
```
credentials {
    username = project.properties['mapbox'] ?: ""
    password = project.properties['sk.something'] ?: ""
}
```

I don't think this is right way to do it. It would be great if you could please follow the instructions closely. 

Thanks. 
@Tiraino

**Comment by Tiraino** [comment]
@abhishek1508 Right, sorry, I was trying some things since putting 
```
username = project.properties['MapboxUsername'] ?: ""
password = project.properties['MapboxSecretAccessToken'] ?: ""
```
also doesn't work.

(with MAPBOX_DOWNLOADS_TOKEN=sk.something; and MAPBOX_USERNAME=mapbox;)

**Comment by abhishek1508** [comment]
@Tiraino 
Since you are using 
`MAPBOX_USERNAME=mapbox`
`MAPBOX_DOWNLOADS_TOKEN=sk.something`
in `gradle.properties` thats the actual parameters you should use below here

```
username = project.properties['MAPBOX_USERNAME'] ?: ""
password = project.properties['MAPBOX_DOWNLOADS_TOKEN'] ?: ""
```

Sorry for the confusion.
