### ISSUE TITLE
Bearing 360 intermittent on turns

### ISSUE THREAD

**Issue by cammace** [mapbox/mapbox-navigation-android#316]
In some occasions, the navigation camera will rotate in the wrong direction causing it to rotate the long way around.

**Comment by danesfeder** [comment]
This is fixed with the recent releases of the LLP, which now uses https://github.com/mapbox/mapbox-plugins-android/blob/master/plugin-locationlayer/src/main/java/com/mapbox/mapboxsdk/plugins/locationlayer/Utils.java#L32-L40 to calculate the bearing of the layer
