### ISSUE TITLE
Telemetry tailwork

### ISSUE THREAD

**Issue by Guardiola31337** [mapbox/mapbox-navigation-android#3164]
Using this ticket to track some telemetry tailwork

A couple of missing `TODO`s

- [ ] https://github.com/mapbox/mapbox-navigation-android/blob/5aac937037e01b23e9b8776f803d1b22d4693064/libnavigation-core/src/main/java/com/mapbox/navigation/core/telemetry/MapboxNavigationTelemetry.kt#L684-L685
- [x] https://github.com/mapbox/mapbox-navigation-android/blob/5aac937037e01b23e9b8776f803d1b22d4693064/libnavigation-core/src/main/java/com/mapbox/navigation/core/telemetry/events/SessionState.kt#L35-L39

> Another open question is, what happens in a guided session in which the destination is raught (arrival event) and right after the client sets a new route externally? Should we send a new departure event and consider that a new "session"?

- [x] Cancel event followed by a new departure event should be sent.

> What happens in that exact situation but before arrival? Should we send a cancel event for the current "session" and a new departure event associated to the new route?

- [x] Same as above. Cancel event followed by a new departure event should be sent.

- [ ] Is the data correct? We should validate the correctness of every field of every event, making sure the values are properly generated and sent over to telemetry

Refs. https://github.com/mapbox/mapbox-navigation-android/pull/2445 https://github.com/mapbox/mapbox-navigation-android/pull/2580 https://github.com/mapbox/mapbox-navigation-android/pull/2616 https://github.com/mapbox/mapbox-navigation-android/pull/2635 https://github.com/mapbox/mapbox-navigation-android/pull/2641 https://github.com/mapbox/mapbox-navigation-android/pull/2637 https://github.com/mapbox/mapbox-navigation-android/pull/2677 https://github.com/mapbox/mapbox-navigation-android/pull/3162

**Comment by Guardiola31337** [comment]
We also need to look into https://github.com/mapbox/mapbox-navigation-android/issues/3486

**Comment by Guardiola31337** [comment]
https://github.com/mapbox/mapbox-navigation-android/pull/3540 landed addressing some OP issues 🎉 

Listing here the current tailwork:

- `voiceIndex` and `bannerIndex`
- add more tests
- add multiple waypoint support
- unreliable distance metrics
- https://github.com/mapbox/mapbox-navigation-android/issues/3682
- https://github.com/mapbox/mapbox-navigation-android/issues/3683

cc @korshaknn

**Comment by Guardiola31337** [comment]
There's also

- _Free Drive_ instrumentation

cc @asinghal22

**Comment by asinghal22** [comment]
Free Drive is very high priority. We should target v1.2

**Comment by asinghal22** [comment]
Context: FreeDrive tracking is being asked by GrubHub - one of key account wins we want during this quarter.

**Comment by LukasPaczos** [comment]
@Guardiola31337 since the addition of free drive events is tracked in https://github.com/mapbox/navigation-sdks/issues/691, are we good to close here? If there are any other follow-ups after recent refactors, let's cut smaller tickets instead and close this one.

**Comment by Guardiola31337** [comment]
Closing here. We have tickets for the remaining points 👍
