### ISSUE TITLE
Vanishing route line stops working after lifecycle stop/start cycle

### ISSUE THREAD

**Issue by LukasPaczos** [mapbox/mapbox-navigation-android#3172]
Whenever an activity/fragment with the map and vanishing route line enabled goes through a lifecycle change (started -> stopped -> started), the route stops vanishing.

/cc @Guardiola31337 @cafesilencio @abhishek1508

**Comment by cafesilencio** [comment]
fixed in PR: https://github.com/mapbox/mapbox-navigation-android/pull/3175
