### ISSUE TITLE
Capturing tailwork on maneuver route arrows

### ISSUE THREAD

**Issue by abhishek1508** [mapbox/mapbox-navigation-android#3176]

**Comment by Guardiola31337** [comment]
From https://github.com/mapbox/mapbox-navigation-android/pull/1053#issuecomment-399441205
> This way the upcoming maneuver arrow will be drawn above shields (as it was) but underneath annotations

Refs. https://github.com/mapbox/mapbox-navigation-android/issues/2865 https://github.com/mapbox/mapbox-navigation-android/issues/2872

cc @abhishek1508 @cafesilencio
