### ISSUE TITLE
Clean up MapboxNavigation init exceptions

### ISSUE THREAD

**Issue by LukasPaczos** [mapbox/mapbox-navigation-android#3182]
When working with `MapboxNavigation` in an empty project, I run into an issue when instantiating the object. In order to be able to create `MapboxNavigation` in the current default config, we need to provide:
- an access token
- onboard router options
- distance formatter

If any of those are not provided, we will crash with an obscure module loading exception.

To address this usability issue, we need to:
- Make sure to print the underlying exception that caused the module loading to fail. This happens as part of https://github.com/mapbox/mapbox-base-android/pull/43.
- When integrating above, we'll need to clear up the exception messages for the required values and point to `MapboxNavigation#defaultNavigationOptions` so that it's easier to discover.

I'm adding a release blocker to make sure this is addressed before GA.

**Comment by Guardiola31337** [comment]
@LukasPaczos 
> - When integrating above, we'll need to clear up the exception messages for the required values and point to `MapboxNavigation#defaultNavigationOptions` so that it's easier to discover.

As discussed internally we should double check if we can provide default navigation options through `MapboxNavigation` constructor so we don't need to point / remind users to call `MapboxNavigation#defaultNavigationOptions`. Could you cut a ticket when you have a chance?

cc @kmadsen

**Comment by kmadsen** [comment]
Yeah I agree with these. 

Would be good to move these things to NavigationOptions, and it fails to build if it's configured incorrectly. For example, an empty accessToken results in a failure right there in the builder.

And then make NavigationOptions the only required parameter to MapboxNavigation
