### ISSUE TITLE
Feedback screenshot quality is low to read

### ISSUE THREAD

**Issue by JunDai** [mapbox/mapbox-navigation-android#3189]
**Android API:** Any
**Mapbox Navigation SDK version:** Navigation UI SDK 1.0

### Steps to trigger behavior

 1. Send feedback with screenshot

### Expected behavior
The screenshot should be clear and readable.

### Actual behavior
The image is scaled to 250px width and compressed to ~20% quality before being serialized. It's not clear enough for reading.
Ref: https://github.com/mapbox/mapbox-navigation-android/blob/master/libnavigation-ui/src/main/java/com/mapbox/navigation/ui/internal/utils/ViewUtils.java#L26

### Suggestion
Can we consider to parameterise the screenshot resolution so developer can take control of it? The developer will balance the image quality versus feedback event data size.

**Comment by abhishek1508** [comment]
@LukasPaczos Could you please list down the options you would want us to parameterize and might probably help you?
cc @JunDai @Guardiola31337

**Comment by LukasPaczos** [comment]
The width and JPEG compression quality parameters should be enough.
