### ISSUE TITLE
Vanishing route line animation from the upcoming step after reroute

### ISSUE THREAD

**Issue by LukasPaczos** [mapbox/mapbox-navigation-android#3197]
After a reroute, the vanishing route line breakpoint doesn't immediately pick up form the puck's position but is animated from the upcoming step (possibly?) back to the puck's position.
![ezgif com-optimize (40)](https://user-images.githubusercontent.com/16925074/85021288-f64ec680-b171-11ea-95fc-44adfbdd9fee.gif)

/cc @abhishek1508 @cafesilencio

**Comment by cafesilencio** [comment]
Where are you seeing this? This condition was recently addressed here:
https://github.com/mapbox/mapbox-navigation-android/commit/4b3d2932c686537966c156257113825d1259937c

**Comment by LukasPaczos** [comment]
This is reproducible with the latest artifact, including https://github.com/mapbox/mapbox-navigation-android/commit/4b3d2932c686537966c156257113825d1259937c.
