### ISSUE TITLE
NavigationMapboxMap progress listener and free drive

### ISSUE THREAD

**Issue by LukasPaczos** [mapbox/mapbox-navigation-android#3198]
`NavigationMapboxMap` exposes an `addProgressChangeListener` which starts to listen to location updates, updates the camera engine, way names, etc.

There are 3 issues when it comes to free drive usage:
1. This method doesn't have an equivalent `removeProgressChangeListener`, so whenever we add it once, it always tries to modify the camera engine, update the location etc. There's no way to stop those updates.
2. If the `addProgressChangeListener` is called before `onStart`, it will for example register 2 location observers and start duplicating location updates.
3. When `addProgressChangeListener` is called, the underlying `MapWayName` initialization changes the padding of the map, pushing the puck down the screen. This is not a desirable effect when initially in free drive.

/cc @abhishek1508 @JunDai @cafesilencio @langsmith

**Comment by cafesilencio** [comment]
@LukasPaczos regarding point 2 you mention above. The location observers in MapboxTripSession is backed by a Set so there shouldn't be any duplicate listeners.

**Comment by LukasPaczos** [comment]
Yes, good point @cafesilencio. I believe the issue we run into is that:
1. we called update location ourselves in free drive
2. when navigation was started we used the progress listener
3. when navigation was finished, we started pushing updates ourselves again which was duplicated with what progress listener was updating as well as we couldn't unsubscribe it
