### ISSUE TITLE
NPE on MapboxNavigationOptions.getMinimumHighAlertDistance() in example

### ISSUE THREAD

**Issue by davols** [mapbox/mapbox-navigation-android#32]
Sometimes while running the demo app and the Navigation example it crashes after you have started a route. Does not happen all the time. I tried 5-10 times without a crash yesterday but later I got 5 crashes in a row. 

Tested on Google Pixel XL running 7.1.2 and navigation 0.1. 

> E  java.lang.NullPointerException: Attempt to invoke virtual method 'double com.mapbox.services.android.navigation.v5.MapboxNavigationOptions.getMinimumHighAlertDistance()' on a null object reference
> E      at com.mapbox.services.android.navigation.v5.LocationUpdatedThread.monitorStepProgress([LocationUpdatedThread.java:158](https://github.com/mapbox/mapbox-navigation-android/blob/master/navigation/libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/LocationUpdatedThread.java#L158))

Should make sure options are not null for that entire method. Seeing that options is used later in that method `(monitorStepProgress)` as well.

**Comment by cammace** [comment]
Thank you for reporting this issue @davols, with the recent refactoring I've been doing in https://github.com/mapbox/mapbox-navigation-android/pull/30, the `LocationUpdateThread` doesn't exist anymore and pretty much the entire navigation internals have been rewritten to make much more sense (also easier to add test). Is there any chance you could check out https://github.com/mapbox/mapbox-navigation-android/pull/30 and see if your issue still exist?

**Comment by cammace** [comment]
Not able to reproduce this, I've added a [test for this](https://github.com/mapbox/mapbox-navigation-android/blob/master/navigation/libandroid-navigation/src/test/java/com/mapbox/services/android/navigation/v5/MapboxNavigationOptionsTest.java#L72) and haven't been running into any issues. Might have indirectly gotten fixed while refactoring `monitorStepProgress`. If this is still an issue, please comment on this ticket.
