### ISSUE TITLE
The puck is not shifted down in landscape

### ISSUE THREAD

**Issue by LukasPaczos** [mapbox/mapbox-navigation-android#3208]
We are calculating the default padding of the camera, that should shift the puck to the bottom of the screen, based on the map view, summary bottom sheet and the way name sizes. The biggest impact has the bottom sheet height, that in both portrait and landscape uses the same multiplier:
https://github.com/mapbox/mapbox-navigation-android/blob/710880445a329feabb35f78a19fa8188d22da3b3/libnavigation-ui/src/main/java/com/mapbox/navigation/ui/map/MapPaddingAdjustor.java#L73

While this calculation is more or less correct for portrait mode, in the landscape configuration the ratio of the summary sheet height to the map height is much greater which after multiplication can actually shift the puck up instead of shifting it down (because the calculated top padding is ending up being negative).

/cc @abhishek1508 @JunDai @cafesilencio @langsmith

**Comment by abhishek1508** [comment]
@LukasPaczos Could you please share a screenshot of how the padding is looking on your end? This is how it is looking for me.

![Screenshot_20200622-090731](https://user-images.githubusercontent.com/9770186/85309837-06172500-b468-11ea-86e5-d1387a97c9ce.png)

**Comment by LukasPaczos** [comment]
Here's my view @abhishek1508:
![device-2020-06-22-181737](https://user-images.githubusercontent.com/16925074/85310833-c7f42280-b4b4-11ea-88d9-1a5cd37ac797.png)

**Comment by evabishchevich** [comment]
I can confirm that it's possible to get negative padding. My setup was:
1) Emulator of Samsung S20 (quite narrow device, 9:20)
2) InstructionView is visible
3) SummaryBottomSheet is visible

**Comment by LukasPaczos** [comment]
@evabishchevich did you reproduce in 1tap or sdk example?

**Comment by evabishchevich** [comment]
1tap. 
I can modify sdk example if needed

**Comment by evabishchevich** [comment]
@LukasPaczos ^^

**Comment by LukasPaczos** [comment]
That'd be great @evabishchevich, easier to fix in place

**Comment by evabishchevich** [comment]
@LukasPaczos @abhishek1508 commit: https://github.com/mapbox/mapbox-navigation-android/commit/414cfb374845988e23522203b3dbd3aa65305641

**Comment by LukasPaczos** [comment]
Thanks @evabishchevich! Moving this back to the backlog to be picked up.

**Comment by cafesilencio** [comment]
Fixed with PR https://github.com/mapbox/mapbox-navigation-android/pull/3319
