### ISSUE TITLE
Nav SDK is not providing location updates to Nav Native

### ISSUE THREAD

**Issue by LukasPaczos** [mapbox/mapbox-navigation-android#3211]
When testing `1.0.0-qa.2020.w25` I run into a situation, where the puck got stuck.

I don't remember interacting with the phone, there was no reroutes involved, the app simply stopped pushing the updates to Nav Native and required a full restart of the app to start reporting the updates again.

After analyzing the history files, we were normally in active guidance when suddenly we stopped calling `updateLocation` but we kept calling `getStatus` every second. The app was still interactive, it just looked like either the coroutine that updates the raw location died or the device stopped reporting location updates that we could push to Nav Native.

@Guardiola31337 @Lebedinsky @mskurydin

**Comment by Guardiola31337** [comment]
Thinking about this wondering if 

> it just looked like either the coroutine that updates the raw location died

may be related to https://github.com/mapbox/mapbox-navigation-android/blob/fcb72496ecfd94acbd352682f37c1c86c4c4f14e/libnavigation-util/src/main/java/com/mapbox/navigation/utils/internal/ThreadController.kt#L50-L55 and actually the coroutine didn't died but was halted somehow waiting for its turn to do their job 🤔

**Comment by Guardiola31337** [comment]
@LukasPaczos have you been able to reproduce OP recently? Wondering if latest changes https://github.com/mapbox/mapbox-navigation-android/pull/3457 https://github.com/mapbox/mapbox-navigation-android/pull/3471 fixed it 🤔

**Comment by LukasPaczos** [comment]
I haven't been able to reproduce recently. Let's close and reopen if needed.
