### ISSUE TITLE
Voice instructions is overlapping

### ISSUE THREAD

**Issue by JunDai** [mapbox/mapbox-navigation-android#3216]
When running the `InstructionViewActivity` in the `example` app, noticed the same voice instructions were played multiple times.

Update: The issue was not about duplicate, but actually it's overlapping. The second voice instruction will be played at the same time while the first voice instruction is still playing. It will be fixed by #3297

**Comment by JunDai** [comment]
@Guardiola31337 has a video where the first voice instruction was played twice.
The first one is played via TTS and the second one is from AWS Polly.

The gif doesn't have audio, so if anyone wants to checkout the video can go here: https://youtu.be/dePNCWU0gr8

**Comment by tkvalentine56** [comment]
I have experienced the same double voice speak/playing.
Current app is using:
        implementation 'com.mapbox.navigation:ui-v1:1.1.0-beta.5'
        implementation 'com.mapbox.navigation:router-offboard:1.1.0-beta.5'
        implementation 'com.mapbox.navigation:router-onboard:1.1.0-beta.5'
        implementation 'com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v9:0.8.0'
I have not been able to determine the cause as of this date.

**Comment by JunDai** [comment]
> I have experienced the same double voice speak/playing.
> Current app is using:
> implementation 'com.mapbox.navigation:ui-v1:1.1.0-beta.5'

@tkvalentine56 - hey, thanks for checking out our sdk.

Would you mind to share what you have seen and if it's possible could you also share which UI SDK component were you using? Any sample code how you are using our code are appreciate too.

**Comment by abhishek1508** [comment]
>When running the InstructionViewActivity in the example app, noticed the same voice instructions were played multiple times.

I cannot reproduce this in `InstructionViewActivity` and `NavigationViewActivity` from examples app.

cc @JunDai

**Comment by JunDai** [comment]
@abhishek1508 - yes, I wasn't able to reproduce it as well. @Guardiola31337 can easily reproduce it and I have gotten the log from him. Checking...
