### ISSUE TITLE
The banner instruction text truncates itself shortly after it's been displayed

### ISSUE THREAD

**Issue by JunDai** [mapbox/mapbox-navigation-android#3217]
**Android API:** Any
**Mapbox Navigation SDK version:** Navigation UI SDK 1.0 

### ScreenShots

![ezgif com-video-to-gif (5)](https://user-images.githubusercontent.com/3918950/85337663-bd766080-b495-11ea-803c-b3177f79eb84.gif)

### Expected behavior
The banner instruction should show the `Exit 9` image at left of the `I-370`text.

### Actual behavior
The `Exit 9` image dismissed shortly after it's been displayed. You can see the Notification still show the text `Exit 9`

cc: @abhishek1508 / @mapbox/navigation-android

**Comment by JunDai** [comment]
Noticed the similar behavior below:
![ezgif com-video-to-gif (6)](https://user-images.githubusercontent.com/3918950/85347046-3f718400-b4ac-11ea-8d8c-b5ac7728ec5f.gif)

The `I-66 West` truncates itself to `I-66` shortly after it's been displayed, same as `US 50 West`

**Comment by JunDai** [comment]
@Guardiola31337 , do you have any insight of this issue?

**Comment by JunDai** [comment]
so the text quickly changes is a logic that we handle the ImageBitmap downloads failed.
For example when we request the icon for `US-66` by using url: https://s3.amazonaws.com/mapbox/shields/v3/us-66@3x.png

We get below error:

<img width="974" alt="Screen Shot 2020-06-23 at 12 11 26" src="https://user-images.githubusercontent.com/3918950/85447662-b52c2d00-b54a-11ea-937b-56633c21f677.png">

```xml
    <Error>
        <Code>AccessDenied</Code>
        <Message>Access Denied</Message>
        <RequestId>B950A16018CBF3E4</RequestId>
        <HostId>G4opgCf/eb5a9Ez2YDulwSqGe9FPJQnohCtU3Y5Cf70HALRcfojDScEjMMJ5yhA7UHq5Ss5BEzw=</HostId>
    </Error>
```

**Comment by JunDai** [comment]
@Guardiola31337 - do we need any access token or credential to visit this URL?

**Comment by zugaldia** [comment]
> For example when we request the icon for US-66 by using url: https://s3.amazonaws.com/mapbox/shields/v3/us-66@3x.png

I believe these shields are expected to be missing (temporarily) and we should have logic in place that manages that possibility.

@1ec5 how does iOS manages this scenario today?
