### ISSUE TITLE
Fix mutable issues in AutoValue classes

### ISSUE THREAD

**Issue by cammace** [mapbox/mapbox-navigation-android#322]
We are currently using primitive arrays in some cases inside our auto value classes which are potentially mutable, we should look further into this and resolve the issue or suppress the warnings.

**Comment by Guardiola31337** [comment]
Hey @cammace could you clarify what this means in terms of AutoValue when you have a chance?

**Comment by cammace** [comment]
> resolve the issue or suppress the warnings

In our model classes which use AutoValue, some of the methods use arrays which are by nature mutable in Java after the instance is built. To resolve this issue you have two choices, inside the Builder#build method, convert to an immutable list (I think there's a Collections method for this but can't remember off the top of my head) or you can simply suppress the warning so, during compile time, the warning isn't thrown. Check out the AutoValue docs for more info.

See https://github.com/google/auto/blob/master/value/userguide/howto.md#mutable_property

**Comment by Guardiola31337** [comment]
Per Kotlin migration we don't use AutoValue anymore.

Closing here as not actionable.

cc @kmadsen

**Comment by kmadsen** [comment]
The directions api objects still have mutable lists. Another option is to move this ticket to mapbox-java

For example, you can change a BannerText list item because they [have mutable lists](https://github.com/mapbox/mapbox-java/blob/c53f4a076eb50cb6df81837b1e9b432f5ab4004f/services-directions-models/src/main/java/com/mapbox/api/directions/v5/models/BannerText.java#L52)

``` kotlin
val bannerComponents = bannerText?.components()
bannerComponents?.set(0, bannerComponents[0].toBuilder()
    .imageUrl(null)
    .build())
```

**Comment by Guardiola31337** [comment]
> Another option is to move this ticket to mapbox-java

👍
