### ISSUE TITLE
MapboxHybridRouterTest#whenConnectionAppearedRoutersSwitched flaky test

### ISSUE THREAD

**Issue by Guardiola31337** [mapbox/mapbox-navigation-android#3221]
While working on https://github.com/mapbox/mapbox-navigation-android/pull/3204 CI ❌ https://app.circleci.com/pipelines/github/mapbox/mapbox-navigation-android/7383/workflows/0a0563ef-b4a8-4623-95f8-77d096599aa8/jobs/28226/steps because of `MapboxHybridRouterTest#whenConnectionAppearedRoutersSwitched` flaky test 👀 

```
> Task :libdirections-hybrid:testReleaseUnitTest

com.******.navigation.route.hybrid.MapboxHybridRouterTest > whenConnectionAppearedRoutersSwitched FAILED
    java.lang.AssertionError at MapboxHybridRouterTest.kt:158

12 tests completed, 1 failed

> Task :libdirections-hybrid:testReleaseUnitTest FAILED
```

cc @korshaknn

**Comment by Guardiola31337** [comment]
Refs. https://github.com/mapbox/mapbox-navigation-android/issues/3014 and https://github.com/mapbox/mapbox-navigation-android/pull/3019

**Comment by korshaknn** [comment]
@Guardiola31337 
To turn network connection `on/off` we send a value to the `channel`. And we give some time to a coroutine to wake up and to receive a new value from the channel. We give some time to a coroutine with
`delay(10)` 
that test doesn't fail often, right?  Looks like the 10ms delay is enough in the most cases, but you've caught it ))
we can try to increase it to 20ms and check how it works. We can make in even 100ms, it will increase the duration of all tests in `MapboxHybridRouterTest` for 1.3 seconds.

**Comment by Guardiola31337** [comment]
After bumping `targetSdkVersion` and `compileSdkVersion` to `29` in https://github.com/mapbox/mapbox-navigation-android/pull/3230 https://github.com/mapbox/mapbox-navigation-android/issues/3014 is 100% reproducible 👀 https://app.circleci.com/pipelines/github/mapbox/mapbox-navigation-android/7424/workflows/751d9692-f1b3-4f1d-8b93-8c7754cf67fd/jobs/28354/steps

```
> Task :libdirections-hybrid:testDebugUnitTest
Calling mockable JAR artifact transform to create file: /root/.gradle/caches/transforms-2/files-2.1/ccb1c2316b67aafe35bd8db9a6e55c9b/android.jar with input /android/sdk/platforms/android-29/android.jar

com.******.navigation.route.hybrid.MapboxHybridRouterTest > networkStatusService_cleanup_calledOnChannelClose FAILED
    java.lang.AssertionError at MapboxHybridRouterTest.kt:186

12 tests completed, 1 failed
```

Tried `20` and even `100` ms as delay and still fails. Wondering if the problem is with `Robolectric` 🤔 as mentioned here https://github.com/mapbox/mapbox-navigation-android/pull/3230#issuecomment-649081774 tried to force the API level to 28 but there are some messages referencing 29 🤔 

```
Calling mockable JAR artifact transform to create file: /root/.gradle/caches/transforms-2/files-2.1/ccb1c2316b67aafe35bd8db9a6e55c9b/android.jar with input /android/sdk/platforms/android-29/android.jar
```

**Comment by kmadsen** [comment]
@korshaknn can we make MapboxHybridRouterTest assume that NetworkStatusService works as designed? MapboxHybridRouterTest doesn't need to depend on the internal details of NetworkStatusService. This would allow us to remove Roboelectric from MapboxHybridRouterTest right?

And then NetworkStatusServiceTest can have the tests that ensure NetworkStatusService works as designed. Asking this realizing, that we might move the flaky robolectric test to NetworkStatusServiceTest. But, we could also test NetworkStatusService without roboelectric, removing the delay. 

Ideally, unit tests should not have real delays. They should even mock time.

**Comment by Guardiola31337** [comment]
> This would allow us to remove Roboelectric from MapboxHybridRouterTest right?

Actually removing `Robolectric` from `MapboxHybridRouterTest` did the trick 😅 

In https://github.com/mapbox/mapbox-navigation-android/pull/3230 I'm reviewing all tests that use `Robolectric` and 👀 if it can be removed 🚀

**Comment by korshaknn** [comment]
@kmadsen `NetworkStatusService ` is mocked now, but anyway it should return a real coroutine Channel, because inside 
`MapboxHybridRouter` we have a coroutine which listens to this channel. And the only way to change `NetworkStatus` - to pass status values to that channel and to get them with the coroutine.
 as I mentioned, coroutine is suspended waiting for a new value in the channel. It means that we can't
`Verify` the coroutine has a new value immediately after we set the value to the channel, we need a delay to wake up a coroutine and to fetch a new value. And only after that `Verify`

**Comment by kmadsen** [comment]
@korshaknn I recently had this test fail again, this test may be forever flaky or unnecessarily slow when there is a `delay`. There must be a way to test and mock coroutine channels without a delay.

**Comment by korshaknn** [comment]
@kmadsen 
in general it's not a problem to test `coroutine + channel`. To do it, we can just launch a coroutine and `join` it, until it receive a value from the channel. No `delay` is needed. But it's not our case. Our coroutine is `"infinite"` and we can't just `join` it, the only way to finish it - to cancel the channel. But in that case we will stop receiving value from it. It will break our tests.
I see here the only way to remove `delay` - I've added internal fun to set `NetworkStatus` directly. No delays is needed.
#3252 
@Guardiola31337 cc
