### ISSUE TITLE
Unstable location updates break the puck animation

### ISSUE THREAD

**Issue by LukasPaczos** [mapbox/mapbox-navigation-android#3229]
### Problem
When integrating https://github.com/mapbox/mapbox-navigation-android/pull/3199 downstream, I noticed that together with https://github.com/mapbox/mapbox-navigation-android/pull/2719 it uncovers an issue with the puck animation. The location updates interval can be extremely unstable now, and because the puck animation is now solely based on the interval of location updates, this means that the puck/camera animation duration is also unstable.

Let's take a look at this example:
1. `getStatus` is called with 1100ms prediction, updates enhanced location listeners, location is animated downstream with duration X
2. 1000ms passes
3. `getStatus` is called with 1100ms prediction, updates enhanced location listeners, location is animated downstream with duration ~1000ms (the interval)
4. 30ms passes
5. raw location comes in, pushed to nav native, **immediately** `getStatus` is called and updates enhanced location listeners, location is animated downstream. The animation duration is going to be ~30ms, based on the interval.

This means that if the raw location sample update drops in at an unfortunate moment, we will teleport to the predicted location, or the animation duration is going to be extremely small.

The logic of calling `getStatus` immediately after pushing the raw location to Nav Native has been implemented to decrease the possible delay, but because we had if-checks removed in https://github.com/mapbox/mapbox-navigation-android/pull/3199 in place, we haven't noticed other implications of this approach.

There are 2 animation duration calculation models that the puck currently supports:
1. Regular, this is what we're currently using:
```
animDuration = (currentTime - timeWhenAnimateLocationWasLastCalled) * 1.1
```
2. Lookahead:
```
animDuration = (predictedLocationTimestamp - currentTime)
```

Before https://github.com/mapbox/mapbox-navigation-android/pull/3199, the UI SDK has been using an arbitrary threshold to switch between `1.` and `2.` on the fly, which made the puck jump, speed up and slow down unnecessarily.

### Solution
I see a couple of possible solutions:
- Keep the model of requesting a new predicted location immediately after providing a raw location to Nav Native which makes the location updates interval unstable, then we need to:
  1. Keep using the lookahead animation model when the prediction is enabled. This can be defined by the developer, so it has be in sync with the navigation options.
  2. Let the developer define the animation duration when providing the update to the Maps SDK to be animated instead of calculating it internally.
- Rethink the immediate `getStatus` call after providing a raw location to Nav Native and stick to the regular animation duration calculation.
- There are definitely other, any ideas?

As a stopgap, if we won't be able to come up with a proper solution on short notice, we can revert  https://github.com/mapbox/mapbox-navigation-android/pull/3199 and keep the previous imperfect solution until we figure this out.

/cc @abhishek1508 @Guardiola31337 @mskurydin

**Comment by LukasPaczos** [comment]
An example gif:
![ezgif com-optimize (43)](https://user-images.githubusercontent.com/16925074/85615476-91590c00-b65c-11ea-85a3-ace4af8fe40e.gif)
and the history file:
[2020-06-24 17_39_05_2020-06-24 17_43_32_free_drive_0_ac3a12a2-05ad-43f6-8dcf-7bcef07960f5.json.gz](https://github.com/mapbox/mapbox-navigation-android/files/4827336/2020-06-24.17_39_05_2020-06-24.17_43_32_free_drive_0_ac3a12a2-05ad-43f6-8dcf-7bcef07960f5.json.gz)

This isn't completely easily reproducible. There are plenty of happy paths, but the fluctuation of the raw location samples makes us occasionally fall into a wrong sequence that breaks the smoothness of the animation.

**Comment by tkvalentine56** [comment]
I am experiencing the same puck/animation performance as described above. Very choppy, jumpy.
Currently our app is using:
        implementation 'com.mapbox.navigation:ui-v1:1.1.0-beta.5'
        implementation 'com.mapbox.navigation:router-offboard:1.1.0-beta.5'
        implementation 'com.mapbox.navigation:router-onboard:1.1.0-beta.5'
        //this has symbol manager
        implementation 'com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v9:0.8.0'
