### ISSUE TITLE
Release v0.6.2

### ISSUE THREAD

**Issue by cammace** [mapbox/mapbox-navigation-android#323]
This ticket tracks the release of Mapbox Android Navigation SDK `v0.6.2`. Which includes several fixes including:

- Fixed an issue with the Location Engine not being activated correctly inside the Navigation-UI lib [#321](https://github.com/mapbox/mapbox-navigation-android/pull/321)
- Fixed bottom sheet not getting placed correctly when the device is rotated [#320](https://github.com/mapbox/mapbox-navigation-android/pull/320)
- Fixed missing reroute UI when a navigation session reroute occurs [#319](https://github.com/mapbox/mapbox-navigation-android/pull/319)
- Added logic to detect if the user did a u-turn which would require a reroute [#312](https://github.com/mapbox/mapbox-navigation-android/pull/312)
- Revert snap to route logic creating a new Location object which was causing location updates to occasionally get stuck at a maneuver point [#308](https://github.com/mapbox/mapbox-navigation-android/pull/308)
- Restructured the project so the studio projects opened from the root folder rather than having it nested inside the `navigation` folder [#302](https://github.com/mapbox/mapbox-navigation-android/pull/302)
- Notifications fixed for Android Oreo [#298](https://github.com/mapbox/mapbox-navigation-android/pull/298)
- OSRM-text-instructions removed [#288](https://github.com/mapbox/mapbox-navigation-android/pull/288)
- General code cleanup [#287](https://github.com/mapbox/mapbox-navigation-android/pull/287)
- Day and night mode and theme switching functionality added inside the Navigation-UI library [#286](https://github.com/mapbox/mapbox-navigation-android/pull/286)
- Metric reroute added - [#296](https://github.com/mapbox/mapbox-navigation-android/pull/296)

### Release checklist @cammace

- [x] Run through testapp/demo app and test all activities
- [x] Change version name to `0.6.2` in `gradle.properties`
- [x] Publish `0.6.2` artifact to Maven Central
- [x] Change version name back to `0.7.0-SNAPSHOT`
- [x] Update `CHANGELOG.md`
- [x] Tag `v0.6.2` in GitHub

### Post-release @langsmith

- [x] Update `README.md`
- [x] Generate Javadoc
- [x] Update `constants.js` file in `android-docs` repo

/cc: @mapbox/navigation

**Comment by cammace** [comment]
wrapped up this release on my end, over to you @langsmith!

**Comment by langsmith** [comment]
all done 🎆
