### ISSUE TITLE
The feedback screenshot's puck location in the InstructionViewActivity example is away from where it should be.

### ISSUE THREAD

**Issue by JunDai** [mapbox/mapbox-navigation-android#3234]
**Android API:** Any
**Mapbox Navigation SDK version:** UI SDK 1.0

### Steps to trigger behavior

 1. Launch `example` app
 2. Run `InstructionViewActivity`
 3. Submit `Feedback`

### Expected behavior
The puck location in the feedback screenshot should match where when the user presses the FeedbackButton

### Actual behavior
The puck location is away from where it should be, because the screenshot is taken at the end of the whole Feedback flow.

**Comment by evabishchevich** [comment]
The same is applicable for `FeedbackButtonActivity`

**Comment by JunDai** [comment]
> The same is applicable for `FeedbackButtonActivity`, `CustomUIComponentStyleActivity`, `BasicNavigationFragment`

@evabishchevich - thanks, all of them will be addressed in #3273
