### ISSUE TITLE
[Android] RouteOptionsProvider unit tests

### ISSUE THREAD

**Issue by RingerJK** [mapbox/mapbox-navigation-android#3236]
Need unit tests for `RouteOptionsProvider`.
Need test(list might be extended):
- waypoint indices;
- waypoint names;
- waypoint targets.

Tests should fit `MapboxDirections` [rules](https://github.com/mapbox/mapbox-java/blob/6c9bab02e1ca22be82d877bcb4badccd1a8fe9e2/services-directions/src/main/java/com/mapbox/api/directions/v5/MapboxDirections.java#L1114-L1184) 

PR that introduce RouteOptionsProvider https://github.com/mapbox/mapbox-navigation-android/pull/3184

cc @mapbox/navigation-android

**Comment by RingerJK** [comment]
Related to https://github.com/mapbox/mapbox-navigation-android/issues/1781

**Comment by Guardiola31337** [comment]
Where are we here @RingerJK? Could you provide an update when you have a chance? 🙏 

cc @Lebedinsky

**Comment by RingerJK** [comment]
`RouteOptionsProvider` was replaced by [MapboxRouteOptionsUpdater](https://github.com/mapbox/mapbox-navigation-android/blob/master/libnavigation-core/src/main/java/com/mapbox/navigation/core/routeoptions/MapboxRouteOptionsUpdater.kt). Tests are also provided [MapboxRouteOptionsUpdaterTest](https://github.com/mapbox/mapbox-navigation-android/blob/master/libnavigation-core/src/test/java/com/mapbox/navigation/core/routeoptions/MapboxRouteOptionsUpdaterTest.kt). We're good to close it. 
Thanks for flagged 🙇
