### ISSUE TITLE
InstructionView

### ISSUE THREAD

**Issue by tkvalentine56** [mapbox/mapbox-navigation-android#3237]
**Android API:**
21+

**Mapbox Navigation SDK version:**
        implementation 'com.mapbox.navigation:ui-v1:1.1.0-beta.5'
        implementation 'com.mapbox.navigation:router-offboard:1.1.0-beta.5'
        implementation 'com.mapbox.navigation:router-onboard:1.1.0-beta.5'
        implementation 'com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v9:0.8.0'

### Steps to trigger behavior

 1. Call InstructionView.updateBannerInstructionsWith(bannerInstructions)

### Expected behavior
InstructionView text content should be updated with BannerInstructions provided

### Actual behavior
InstructionView text content not updated with BannerInstructions provided and the following exception happens

app log output:

25Jun20-11:59:17 4000 INFO  MyMapboxNavigationActivity$10.onNewBannerInstructions : 630 => $$$ MAPBOX : updating BannerInstructions with = 
{"distanceAlongGeometry":19.799999237060547,"primary":{"text":"delivery at 8016 Station Rd front porch\n","components":[{"text":"8016 Station Rd delivery , front porch","type":"text","abbr":"8016 Sta Rd delivery , front porch","abbr_priority":0,"active":false}],"type":"arrive","modifier":"straight","driving_side":"right"}}

25Jun20-11:59:17 4000 INFO  MyMapboxNavigationActivity$10.onNewBannerInstructions : 643 => $$$ MAPBOX : EXCEPTION = Attempt to invoke virtual method 'java.lang.String com.mapbox.api.directions.v5.models.LegStep.drivingSide()' on a null object reference

**Comment by JunDai** [comment]
@tkvalentine56 - thanks for checking out our UI SDK.

This is duplicate with https://github.com/mapbox/mapbox-navigation-android/issues/3121 
We have fixed it and you should be able to get the fix with our next release.

**Comment by JunDai** [comment]
@tkvalentine56 - In the meantime, if you are using the `InstructionView` component, you should be able to avoid this NPE by adding a `RouteProgress` to InstructionView like this:
```kotlin
    private val routeProgressObserver = object : RouteProgressObserver {
        override fun onRouteProgressChanged(routeProgress: RouteProgress) {
            instructionView.updateDistanceWith(routeProgress)
        }
    }
```

Please checkout our `InstructionViewActivity` example for more information: 
https://github.com/mapbox/mapbox-navigation-android/blob/master/examples/src/main/java/com/mapbox/navigation/examples/core/InstructionViewActivity.kt

**Comment by abhishek1508** [comment]
> This is duplicate with #3121 

As mentioned this has been fixed and released. You can find it in the release `1.1.0-beta.6`
