### ISSUE TITLE
Modifying VoiceInstructions does not seem to work

### ISSUE THREAD

**Issue by tkvalentine56** [mapbox/mapbox-navigation-android#3238]
**Android API:**
21+

**Mapbox Navigation SDK version:**
        implementation 'com.mapbox.navigation:ui-v1:1.1.0-beta.5'
        implementation 'com.mapbox.navigation:router-offboard:1.1.0-beta.5'
        implementation 'com.mapbox.navigation:router-onboard:1.1.0-beta.5'
        implementation 'com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v9:0.8.0'

### Steps to trigger behavior
1. catch and modify VoiceInstructions in onNewVoiceInstructions()
 2. Call NavigationSpeechPlayer.play(newVoiceInstructions )

### Expected behavior
new VoiceInstructions content should be updated and played with NavigationSpeechPlayer

### Actual behavior
New VoiceInstructions  content apparently not updated and NavigationSpeechPlayer plays the original VoiceInstructions delivered in onNewVoiceInstructions()

**Comment by JunDai** [comment]
@tkvalentine56 - hey, thanks for checking out our sdk and the feedback.
Would you mind to share the code how you customize the voiceInstruction so we can take a look?

I tried to customize the voice instruction and it kind of works for me.
Here is the code that works for me:
```kotlin
    private val voiceInstructionsObserver = object : VoiceInstructionsObserver {
        override fun onNewVoiceInstructions(voiceInstructions: VoiceInstructions) {
            speechPlayer.play(
                voiceInstructions.toBuilder().announcement("This is test announcement")
                    .ssmlAnnouncement("This is test").build()
            )
        }
    }
```

Please let's know if this works for you.

**Comment by abhishek1508** [comment]
Closing this as this is not an issue as seen above from the code snippet.
