### ISSUE TITLE
On re-route the full route line is briefly visible.

### ISSUE THREAD

**Issue by cafesilencio** [mapbox/mapbox-navigation-android#3246]
### Steps to trigger behavior

 1. Open BasicNavigationActivity
 2. Select route that will result in a re-route event
 3. Notice route line

### Expected behavior

There should be a redrawing of the new route from the old route without any artifacts.

### Actual behavior

For a brief moment the full original route line is visible before the new route line is drawn.

![Screenshot_20200626-101308](https://user-images.githubusercontent.com/2249818/85883623-227fce00-b796-11ea-8db9-fb8f04d84e22.png)

**Comment by cafesilencio** [comment]
When a new line is drawn the layer source is updated with the new feature collection then the vanishing point of the layer is set to 0 so the new line appears solid. The call sequence is to update the geoJson source then update the layer with a vanishing point of 0. The problem is the call to update the geoJson is asynchronous in the maps SDK so the call to update the vanishing point to 0 actually executes first in most cases. This causes the very brief appearance of the original route line.

**Comment by LukasPaczos** [comment]
@cafesilencio would you be able to try setting an empty GeoJSON before setting the vanishing point to 0 and only then setting a new route? This will clear the old route and give the time for the new one to load before displaying any content.

**Comment by cafesilencio** [comment]
I can try that but I don't think it would resolve it because setting the geoGson is still an asynchronous process so whether I draw a new line or an empty line the next call still sets the vanishing point to 0. Perhaps setting empty geojson will be much faster but there is another consequence of that. It will cause a blinking effect of the line. There was a bug related to that in the past reported by @Guardiola31337.   The line would disappear from the map and reappear.

**Comment by LukasPaczos** [comment]
That's a desirable effect when we're rerouting though. Hopefully setting an empty geometry will be fast enough to avoid displaying historic data.

**Comment by cafesilencio** [comment]
My mistake there's already a call to set empty geojson when a new route is drawn. I'll continue investigating.
