### ISSUE TITLE
Add congestion information into RouteProgress object

### ISSUE THREAD

**Issue by cammace** [mapbox/mapbox-navigation-android#325]
iOS offers a few additional information types related to congestion inside the RouteProgress object, we should port this over to Android. 

https://github.com/mapbox/mapbox-navigation-ios/blob/master/MapboxCoreNavigation/RouteProgress.swift#L122-L135

cc: @danesfeder

**Comment by danesfeder** [comment]
We should do a full audit on any other missing information from our `RouteProgress` object
