### ISSUE TITLE
ETA showing different value in notification vs the one inside the bottom sheet.

### ISSUE THREAD

**Issue by cammace** [mapbox/mapbox-navigation-android#326]
<img src="https://user-images.githubusercontent.com/5652865/31322152-51cc2f30-ac60-11e7-8152-400c7472b554.png" width=360/>

Shown in the image above, the time values are off by two minutes, this difference occurred after a reroute, I'm not sure which one was correct.

cc: @danesfeder

**Comment by danesfeder** [comment]
Should be fixed in `0.7.1` by #564
