### ISSUE TITLE
Wrong package name for TripNotification Module

### ISSUE THREAD

**Issue by 113408** [mapbox/mapbox-navigation-android#3263]
**Android API:29
**Mapbox Navigation SDK version:1.0.0-rc.2
**I can confirm that after recompiling the jar with the correct package name, it worked as expected**
First of all, thanks for the great improvement made on the navigation module. I've been considering to use it for the past months but found that it was quite limiting. With this new version, we have much more features and we are definitely going to use it on our app.

I've been trying to customize the `TripNotification` according to the doc and I reached a point where I'm able to inject my `CustomTripNotification` however I'm not able to compile due to a missing package. When tracking down the issue, I found that the `MapboxModuleType` defines `TripNotifcation` as under packageName **com.mapbox.navigation.base.trip** but the actual location is under **com.mapbox.navigation.base.trip.notification**. The resulting generated class is :
```
package com.mapbox.module

import androidx.annotation.Keep
import com.mapbox.navigation.base.trip.TripNotification
import kotlin.Boolean
import kotlin.jvm.JvmStatic

/**
 * Configuration provider for TripNotification module.
 */
@Keep
object Mapbox_TripNotificationModuleConfiguration {
  @JvmStatic
  val enableConfiguration: Boolean = true

  /**
   * Set this dependency provider before initializing any components of the modularized library.
   *
   * When you're not using the library anymore, you should pass `null` to clean up the provider
   * reference and prevent memory leaks.
   */
  @JvmStatic
  var moduleProvider: ModuleProvider? = null

  interface ModuleProvider {
    fun createTripNotification(): TripNotification
  }
}
```
And of course the IDE complains about not finding `TripNotification` class.

Maybe should be ported to : https://github.com/mapbox/mapbox-base-android ?

**Comment by Guardiola31337** [comment]
Thanks for checking out the SDK @113408 🙇‍♂️ 

This is a great catch! Checking https://github.com/mapbox/mapbox-base-android/blob/e4bd2097713fd6edea1121ef4a18119316ac0c26/annotations/src/main/java/com/mapbox/annotation/module/MapboxModuleType.kt#L63 you're totally right. Could you open a PR in https://github.com/mapbox/mapbox-base-android? You deserve all the credit 😅 If it's too much of an ask we can also do it, let us know when you have a chance 🚀 

cc @LukasPaczos
