### ISSUE TITLE
Investigate if MapboxTripSession status polling thread safe

### ISSUE THREAD

**Issue by korshaknn** [mapbox/mapbox-navigation-android#3265]
`unconditionalStatusPollingJob` has 2 `launch` blocks inside.
```
unconditionalStatusPollingJob = ioJobController.scope.launch {
            while (isActive) {
                launch { updateDataFromNavigatorStatus(Date()) }
                delay(...)
            }
}
```
This is done  to call `updateDataFromNavigatorStatus` at exact `delays` . Check more [details](https://github.com/mapbox/mapbox-navigation-android/pull/3255/files#r447617327)

But we might have issues if `updateDataFromNavigatorStatus()` method is slow.
If it need more time to finish than `delay`, we will have 2 (or more) methods running concurrently. 

Need check any race conditions or shared mutable states.

cc @Guardiola31337 @LukasPaczos @RingerJK @kmadsen

**Comment by korshaknn** [comment]
```
private fun updateDataFromNavigatorStatus(date: Date) {
        mainJobController.scope.launch {
            val status = getNavigatorStatus(date)
            launch {
                updateEnhancedLocation(status.enhancedLocation, status.keyPoints)
                updateRouteProgress(status.routeProgress)
                isOffRoute = status.offRoute
            }
        }
    }
```
we have `main` thread here, do we need 2 `launch` blocks?
@Guardiola31337  @Lebedinsky

**Comment by LukasPaczos** [comment]
I'd suggest removing both second `launch` invocations: 
1. 
```
private fun updateDataFromNavigatorStatus(date: Date) {
        mainJobController.scope.launch {
            val status = getNavigatorStatus(date)
            launch {
                updateEnhancedLocation(status.enhancedLocation, status.keyPoints)
                updateRouteProgress(status.routeProgress)
                isOffRoute = status.offRoute
            }
        }
    }
```
We're delivering the callbacks on the main thread, so it should be understood that if the user is performing heavy operations it will block. They should move the heavy logic to a worker thread/coroutine if that's needed.

2.
```
unconditionalStatusPollingJob = ioJobController.scope.launch {
            while (isActive) {
                launch { updateDataFromNavigatorStatus(Date()) }
                delay(...)
            }
}
```
This is less of an issue, it could stay, but we can remove it as well. If we would deliver the update a couple of milliseconds later due to processing time, it should still be fine. If the operation takes more than the delay time, we have much bigger problems.

**Comment by korshaknn** [comment]
completely agree with @LukasPaczos . We can remove double `launch` blocks to simplify code and (in case of `unconditionalStatusPollingJob `) make it synchronous in the context of inner coroutine.

**Comment by kmadsen** [comment]
+1 to removing nested launches. Once in coroutine scopes, you're free to suspend and change dispatchers. Would be great if the issues could be proven/fixed with tests

**Comment by LukasPaczos** [comment]
@korshaknn would you be able to run with this when you have a chance and add/adjust required tests?

**Comment by korshaknn** [comment]
@LukasPaczos don't know what to test here and what test-cases are.
@Guardiola31337 @kmadsen @Lebedinsky any ideas?

**Comment by Guardiola31337** [comment]
> 2.
>```
>unconditionalStatusPollingJob = ioJobController.scope.launch {
>            while (isActive) {
>                launch { updateDataFromNavigatorStatus(Date()) }
>                delay(...)
>            }
>}
>```
> This is less of an issue, it could stay, but we can remove it as well. If we would deliver the update a couple of milliseconds later due to processing time, it should still be fine. If the operation takes more than the delay time, we have much bigger problems.

This is not completely true because we're calling `updateDataFromNavigatorStatus(Date())` (`1.`) which runs 

```kotlin
updateEnhancedLocation(status.enhancedLocation, status.keyPoints)
updateRouteProgress(status.routeProgress)
```

which depends on the number of `LocationObserver`, `RouteProgressObserver`, `BannerInstructionsObserver` and `VoiceInstructionsObserver` observers the client has registered AND `tripService.updateNotification(progress)` which it takes a bit longer as it's updating the UI (`TripNotification`) which impacts directly to when the `delay` is executed and therefore the overall frequency of the polling / NN. We noticed that in the past (`tripService.updateNotification(progress)` takes some time especially in low-end devices) and added that `launch` explicitly to try respecting the polling time and avoid issues if by any chance these operations take longer than the delay.

For 👇 though

> 1. 
>```
>private fun updateDataFromNavigatorStatus(date: Date) {
>        mainJobController.scope.launch {
>            val status = getNavigatorStatus(date)
>            launch {
>                updateEnhancedLocation(status.enhancedLocation, status.keyPoints)
>                updateRouteProgress(status.routeProgress)
>                isOffRoute = status.offRoute
>            }
>        }
>    }
>```

we're probably good removing that second `launch` as there are no `delay`s involved and these operations are already executed in the main thread `mainJobController.scope.launch` 👍 It'd be great to test with and without the `launch` and confirm that everything keeps working 👌 

cc @korshaknn @kmadsen @LukasPaczos

**Comment by LukasPaczos** [comment]
> We noticed that in the past (tripService.updateNotification(progress) takes some time especially in low-end devices)

I'm wondering whether those pieces of code, especially `updateNotification` in this case, should maintain this async behavior themselves. If updating the notification takes a lot of time, then the `tripService` should be responsible for making it async, not the upstream progress update listener.

**Comment by Guardiola31337** [comment]
That's a fair point. I was also wondering how to split out those responsibilities. Let's explore that option 👍

**Comment by korshaknn** [comment]
@Guardiola31337 @LukasPaczos 
Have spent some time debugging `launch` blocks. Have got the next logs:
`

14:30:20.785 17484-17484/com.mapbox.navigation.examples D/QWERTYUIOP: updateRawLocation
14:30:20.794 17484-17650/com.mapbox.navigation.examples D/QWERTYUIOP: outer launch
14:30:22.773 17484-17484/com.mapbox.navigation.examples D/QWERTYUIOP: updateRawLocation
14:30:22.784 17484-17645/com.mapbox.navigation.examples D/QWERTYUIOP: outer launch
14:30:24.786 17484-17645/com.mapbox.navigation.examples D/QWERTYUIOP: inner launch
14:30:25.790 17484-17645/com.mapbox.navigation.examples D/QWERTYUIOP: inner launch
14:30:26.793 17484-17650/com.mapbox.navigation.examples D/QWERTYUIOP: inner launch
14:30:27.773 17484-17484/com.mapbox.navigation.examples D/QWERTYUIOP: updateRawLocation
14:30:27.782 17484-17645/com.mapbox.navigation.examples D/QWERTYUIOP: outer launch
14:30:29.784 17484-17645/com.mapbox.navigation.examples D/QWERTYUIOP: inner launch
14:30:30.786 17484-17645/com.mapbox.navigation.examples D/QWERTYUIOP: inner launch
14:30:31.789 17484-17650/com.mapbox.navigation.examples D/QWERTYUIOP: inner launch
14:30:32.791 17484-17645/com.mapbox.navigation.examples D/QWERTYUIOP: inner launch
14:30:32.802 17484-17484/com.mapbox.navigation.examples D/QWERTYUIOP: updateRawLocation
14:30:32.810 17484-17645/com.mapbox.navigation.examples D/QWERTYUIOP: outer launch
14:30:34.812 17484-17645/com.mapbox.navigation.examples D/QWERTYUIOP: inner launch
14:30:35.813 17484-17650/com.mapbox.navigation.examples D/QWERTYUIOP: inner launch
14:30:36.818 17484-17645/com.mapbox.navigation.examples D/QWERTYUIOP: inner launch
14:30:37.819 17484-17650/com.mapbox.navigation.examples D/QWERTYUIOP: inner launch
14:30:37.832 17484-17484/com.mapbox.navigation.examples D/QWERTYUIOP: updateRawLocation
14:30:37.838 17484-17650/com.mapbox.navigation.examples D/QWERTYUIOP: outer launch
14:30:39.840 17484-17650/com.mapbox.navigation.examples D/QWERTYUIOP: inner launch
14:30:40.844 17484-17645/com.mapbox.navigation.examples D/QWERTYUIOP: inner launch
14:30:41.847 17484-17650/com.mapbox.navigation.examples D/QWERTYUIOP: inner launch
14:30:42.849 17484-17650/com.mapbox.navigation.examples D/QWERTYUIOP: inner launch
14:30:42.930 17484-17484/com.mapbox.navigation.examples D/QWERTYUIOP: updateRawLocation
14:30:42.938 17484-17650/com.mapbox.navigation.examples D/QWERTYUIOP: outer launch
14:30:43.157 17484-17484/com.mapbox.navigation.examples D/QWERTYUIOP: updateRawLocation
14:30:43.161 17484-17645/com.mapbox.navigation.examples D/QWERTYUIOP: outer launch
14:30:44.127 17484-17484/com.mapbox.navigation.examples D/QWERTYUIOP: updateRawLocation
14:30:44.131 17484-17650/com.mapbox.navigation.examples D/QWERTYUIOP: outer launch
14:30:45.148 17484-17484/com.mapbox.navigation.examples D/QWERTYUIOP: updateRawLocation
14:30:45.153 17484-17645/com.mapbox.navigation.examples D/QWERTYUIOP: outer launch
14:30:46.132 17484-17484/com.mapbox.navigation.examples D/QWERTYUIOP: updateRawLocation
14:30:46.136 17484-17645/com.mapbox.navigation.examples D/QWERTYUIOP: outer launch
14:30:47.120 17484-17484/com.mapbox.navigation.examples D/QWERTYUIOP: updateRawLocation
14:30:47.127 17484-17650/com.mapbox.navigation.examples D/QWERTYUIOP: outer launch
14:30:48.154 17484-17484/com.mapbox.navigation.examples D/QWERTYUIOP: updateRawLocation
14:30:48.159 17484-17650/com.mapbox.navigation.examples D/QWERTYUIOP: outer launch
14:30:49.141 17484-17484/com.mapbox.navigation.examples D/QWERTYUIOP: updateRawLocation
14:30:49.147 17484-17645/com.mapbox.navigation.examples D/QWERTYUIOP: outer launch
14:30:50.162 17484-17484/com.mapbox.navigation.examples D/QWERTYUIOP: updateRawLocation
14:30:50.168 17484-17645/com.mapbox.navigation.examples D/QWERTYUIOP: outer launch
14:30:51.133 17484-17484/com.mapbox.navigation.examples D/QWERTYUIOP: updateRawLocation
14:30:51.137 17484-17650/com.mapbox.navigation.examples D/QWERTYUIOP: outer launch
`

before we call `inner launch`, we have `delay(UNCONDITIONAL_STATUS_POLLING_PATIENCE)`
it means that if we call `updateRawLocation` each second, `inner coroutine` will NOT be launched because of that delay.
at the top of logs you can see `inner launch` calls because interval of `updateRawLocation` is more than 2 seconds
at the bottom there are only `updateRawLocation` and `outer launch`.

is it expected?
and the second question:
do we need to call `updateEnhancedLocation` and `updateRouteProgress` on the `main` thread? or it might be a worker one?

**Comment by LukasPaczos** [comment]
> it means that if we call updateRawLocation each second, inner coroutine will NOT be launched because of that delay.

That's expected behavior. We are waiting at least 2 seconds before firing off the unconditional polling. In all other cases, we poll as soon as get a raw location.

> do we need to call updateEnhancedLocation and updateRouteProgress on the main thread? or it might be a worker one?

If there's no strong reason to do otherwise, it should be on the main thread.

**Comment by korshaknn** [comment]
so, if it works as expected and there are no issues, let's close it.
