### ISSUE TITLE
It is not possible to navigation along a route generated by a separate process

### ISSUE THREAD

**Issue by sansumbrella** [mapbox/mapbox-navigation-android#3272]
**Android API:** 19
**Mapbox Navigation SDK version:** com.mapbox.mapboxsdk:mapbox-android-navigation-ui:0.42.6

### Steps to trigger behavior

 1. Generate a route using mapbox-java's MapboxDirections service (alternatively: use curl and the Directions API)
 2. Save the route as JSON (I printed it to the console and copy-pasted)
 3. Create launcher options using the saved JSON as the directionsRoute (i.e. `DirectionsResponse.fromJson(json)`)
 4. Use NavigationLauncher.startNavigation to begin a navigation session

### Expected behavior
The application provides turn-by-turn directions

### Actual behavior

Application crashes with a null pointer exception.
(alternatively: if using curl to generate the JSON, it crashes with a complaint that there is a missing 'options' object)

[Example application](https://github.com/mapbox/dw-navigation-0.4.x-create-route-from-json)
[direct link to main.kt](https://github.com/mapbox/dw-navigation-0.4.x-create-route-from-json/blob/primary/app/src/main/java/com/example/navigationzerofour/MainActivity.kt)

**Comment by Guardiola31337** [comment]
I think the issue is that 👇 is not a valid `DirectionsResponse`

```kotlin
val javaJSON = """{"routeIndex":"0","distance":9077.039,"duration":1287.733,"geometry":"ictgiAxz||qCvD}@d_@?pa@?xL?vN?vD?hB?nC?t@?vN?zP?lP?vH?dPNdbA?jA?fE?pV?`C?hC?xL?fY?bU?pCLjF?n]?xC?tE?vH?tO?rU?xB?lE?v^?dOM|J?`CLz@NzAOhB?|@N|D?tO?`C?xC?bj@OpWNtD?lE?fwANfSLxMMtD?fN?pC?fSOrdANbG?fH?lA?lYL|E?|c@?nC?rB?|Y?z@?|E?vC?dP?ha@?rA?xM?`GNlJ?lE?`C?`C?n]?zA?bB?rj@?tD?nO?bF?rF?vI?pB?jK?~C?hXNdJ?xL?vS?bL?`C?lE??_TFiMG_S?wc@?yW?eEFwM?}T?gD?sQ?iMDgD?aH?_|@E_J?mI?gY?oS?coA?qG?sG?mTDoS?oI?ya@Em^?{`@?{`@?m^Gse@FsFDib@FaH?iB?}@Fm^l@_J|DoS`I}^|DwMfD}J`CqHjKs[xQyj@hM{`@vDkLrKa\\zZy`ArL}^`BsFdFuOtJeZ|Jc[bAyCvC}I`CqH`Mk`@zAsElEyMd@iB|Ocf@`\\ucAvSco@n]_gAzKq\\~DyMrj@qdBxBaHnNgc@jAuDbGqRbAgDtEwNhGaRpRwm@pHkU`GqRt@gDbBML_@xMgc@pBiBnCm@fD?pMMjB?fXL]s[mEcQsF{UyBmJm@iCku@k{CuZqpAgSsy@aM_h@}I}^uEaR_YmiAwCiM_EuOaRiu@kPsp@w^sxA{d@wkBe@iBwIk`@gDkKyGwXmJ}_@gScz@_YyjAey@ygDs[}qAiRgx@u^ewAqB}JcBqHkAcFcAqGsA}JeAiMUiCe@aROuYUmUOiMGsEGiC?qHMeO|D{A~CuDbBeFbVkVhHiL|S}TfOeP`b@ed@|}@y`AbFsFzAsFvg@l_@|TrPtJ`HjFvCzFxCzAeFl@_]?gOFemA?yjA?aq@?cf@LsFFm@F{@FkBF{@jALhB^??","weight":1287.733,"weight_name":"routability","legs":[{"distance":9077.039,"duration":1287.733,"summary":"16th Street Northwest, US 50","steps":[]}],"routeOptions":{"baseUrl":"https://api.mapbox.com","user":"mapbox","profile":"driving","coordinates":[[-77.0365,38.9392],[-76.9714,38.9125]],"geometries":"polyline6","overview":"full","access_token":"pk.eyJ1IjoiZGF2aWQtd2lja3MiLCJhIjoiY2tiOWx5d251MGY4YjJycDU3bGZ0YmhuMiJ9.fJ_ir1GZT_XYzYfmLxTnsw","uuid":"DAFXYScGrA4Wx8zNoONxXw3RqnV6bgP-S_Wpd363JgPDDLC-85kJkQ\u003d\u003d"}}"""
```

https://github.com/mapbox/dw-navigation-0.4.x-create-route-from-json/blob/b6b2866927fd5dadc4b3335eff5c19071a6b1e48/app/src/main/java/com/example/navigationzerofour/MainActivity.kt#L34

I've just tested 👇 `v0.42.6` [`NavigationLauncherActivity`](https://github.com/mapbox/mapbox-navigation-android/blob/base-v0.42.1/app/src/main/java/com/mapbox/services/android/navigation/testapp/activity/navigationui/NavigationLauncherActivity.java) test `app` example and it's working 👌 

```java
    String response = "{\"code\":\"Ok\",\"waypoints\":[{\"name\":\"Elmcroft Boulevard\",\"location\":[-77.16944,39.11604]},{\"name\":\"Ridgemont Avenue\",\"location\":[-77.174431,39.116626]}],\"routes\":[{\"routeIndex\":\"0\",\"distance\":590.8,\"duration\":106.5,\"geometry\":\"oomriA~p`erCmM~UiGjLaTx`@sBxDa@z@sSra@Yj@yDdI_W`f@y]fq@hCrCzUlWhOlPrB|B~RnSp@r@|N|OnFhFx@v@\",\"weight\":138.6,\"weight_name\":\"routability\",\"legs\":[{\"distance\":590.8,\"duration\":106.5,\"summary\":\"Elmcroft Boulevard, Ridgemont Avenue\",\"steps\":[{\"distance\":375.2,\"duration\":76.5,\"geometry\":\"oomriA~p`erCmM~UiGjLaTx`@sBxDa@z@sSra@Yj@yDdI_W`f@y]fq@\",\"name\":\"Elmcroft Boulevard\",\"mode\":\"driving\",\"maneuver\":{\"location\":[-77.16944,39.11604],\"bearing_before\":0.0,\"bearing_after\":309.0,\"instruction\":\"Head northwest on Elmcroft Boulevard\",\"type\":\"depart\",\"modifier\":\"right\"},\"voiceInstructions\":[{\"distanceAlongGeometry\":375.2,\"announcement\":\"Head northwest on Elmcroft Boulevard, then turn left onto Ridgemont Avenue\",\"ssmlAnnouncement\":\"\\u003cspeak\\u003e\\u003camazon:effect name\\u003d\\\"drc\\\"\\u003e\\u003cprosody rate\\u003d\\\"1.08\\\"\\u003eHead northwest on Elmcroft Boulevard, then turn left onto Ridgemont Avenue\\u003c/prosody\\u003e\\u003c/amazon:effect\\u003e\\u003c/speak\\u003e\"},{\"distanceAlongGeometry\":73.6,\"announcement\":\"Turn left onto Ridgemont Avenue\",\"ssmlAnnouncement\":\"\\u003cspeak\\u003e\\u003camazon:effect name\\u003d\\\"drc\\\"\\u003e\\u003cprosody rate\\u003d\\\"1.08\\\"\\u003eTurn left onto Ridgemont Avenue\\u003c/prosody\\u003e\\u003c/amazon:effect\\u003e\\u003c/speak\\u003e\"}],\"bannerInstructions\":[{\"distanceAlongGeometry\":375.2,\"primary\":{\"text\":\"Ridgemont Avenue\",\"components\":[{\"text\":\"Ridgemont Avenue\",\"type\":\"text\",\"abbr\":\"Ridgemont Ave\",\"abbr_priority\":0}],\"type\":\"turn\",\"modifier\":\"left\"}}],\"driving_side\":\"right\",\"weight\":108.30000000000001,\"intersections\":[{\"location\":[-77.16944,39.11604],\"bearings\":[309],\"entry\":[true],\"out\":0},{\"location\":[-77.169808,39.116271],\"bearings\":[30,135,225,315],\"entry\":[true,false,false,true],\"in\":1,\"out\":3},{\"location\":[-77.170022,39.116404],\"bearings\":[45,135,225,315],\"entry\":[false,false,true,true],\"in\":1,\"out\":3},{\"location\":[-77.171262,39.117159],\"bearings\":[30,135,300],\"entry\":[true,false,true],\"in\":1,\"out\":2},{\"location\":[-77.171425,39.117252],\"bearings\":[120,225,315],\"entry\":[false,true,true],\"in\":0,\"out\":2}]},{\"distance\":215.6,\"duration\":30.0,\"geometry\":\"arqriAjfgerChCrCzUlWhOlPrB|B~RnSp@r@|N|OnFhFx@v@\",\"name\":\"Ridgemont Avenue\",\"mode\":\"driving\",\"maneuver\":{\"location\":[-77.172854,39.118129],\"bearing_before\":307.0,\"bearing_after\":219.0,\"instruction\":\"Turn left onto Ridgemont Avenue\",\"type\":\"end of road\",\"modifier\":\"left\"},\"voiceInstructions\":[{\"distanceAlongGeometry\":195.6,\"announcement\":\"In 700 feet, you will arrive at your destination\",\"ssmlAnnouncement\":\"\\u003cspeak\\u003e\\u003camazon:effect name\\u003d\\\"drc\\\"\\u003e\\u003cprosody rate\\u003d\\\"1.08\\\"\\u003eIn 700 feet, you will arrive at your destination\\u003c/prosody\\u003e\\u003c/amazon:effect\\u003e\\u003c/speak\\u003e\"},{\"distanceAlongGeometry\":35.9,\"announcement\":\"You have arrived at your destination\",\"ssmlAnnouncement\":\"\\u003cspeak\\u003e\\u003camazon:effect name\\u003d\\\"drc\\\"\\u003e\\u003cprosody rate\\u003d\\\"1.08\\\"\\u003eYou have arrived at your destination\\u003c/prosody\\u003e\\u003c/amazon:effect\\u003e\\u003c/speak\\u003e\"}],\"bannerInstructions\":[{\"distanceAlongGeometry\":215.6,\"primary\":{\"text\":\"You will arrive\",\"components\":[{\"text\":\"You will arrive\",\"type\":\"text\"}],\"type\":\"arrive\",\"modifier\":\"straight\"}},{\"distanceAlongGeometry\":35.9,\"primary\":{\"text\":\"You have arrived\",\"components\":[{\"text\":\"You have arrived\",\"type\":\"text\"}],\"type\":\"arrive\",\"modifier\":\"straight\"}}],\"driving_side\":\"right\",\"weight\":30.299999999999997,\"intersections\":[{\"location\":[-77.172854,39.118129],\"bearings\":[30,135,225],\"entry\":[true,false,true],\"in\":1,\"out\":2},{\"location\":[-77.172928,39.11806],\"bearings\":[45,135,225],\"entry\":[false,true,true],\"in\":0,\"out\":2},{\"location\":[-77.173661,39.117375],\"bearings\":[45,135,225,315],\"entry\":[false,true,true,true],\"in\":0,\"out\":2},{\"location\":[-77.174286,39.116775],\"bearings\":[45,135,210,315],\"entry\":[false,true,true,true],\"in\":0,\"out\":2}]},{\"distance\":0.0,\"duration\":0.0,\"geometry\":\"ctnriA|hjerC\",\"name\":\"Ridgemont Avenue\",\"mode\":\"driving\",\"maneuver\":{\"location\":[-77.174431,39.116626],\"bearing_before\":217.0,\"bearing_after\":0.0,\"instruction\":\"You have arrived at your destination\",\"type\":\"arrive\"},\"voiceInstructions\":[],\"bannerInstructions\":[],\"driving_side\":\"right\",\"weight\":0.0,\"intersections\":[{\"location\":[-77.174431,39.116626],\"bearings\":[37],\"entry\":[true],\"in\":0}]}],\"annotation\":{\"distance\":[40.849356887575915,23.661880423724572,59.87164941284378,10.296915536884171,3.205874576820234,60.273008557948764,2.3864358993832364,17.46016181766605,68.79800385388833,88.43395015293287,9.983895520037525,52.8742250636807,37.71493911934564,8.436455982387672,45.47518366606794,3.5729842373683436,36.760837071667886,16.73586764101684,4.030230230473919],\"congestion\":[\"unknown\",\"heavy\",\"low\",\"unknown\",\"unknown\",\"low\",\"low\",\"unknown\",\"low\",\"low\",\"low\",\"low\",\"low\",\"low\",\"low\",\"low\",\"low\",\"low\",\"low\"]}}],\"routeOptions\":{\"baseUrl\":\"https://api.mapbox.com\",\"user\":\"mapbox\",\"profile\":\"driving-traffic\",\"coordinates\":[[-77.1692459,39.1162256],[-77.1744483,39.1166364]],\"alternatives\":true,\"language\":\"en\",\"bearings\":\";\",\"continue_straight\":true,\"roundabout_exits\":true,\"geometries\":\"polyline6\",\"overview\":\"full\",\"steps\":true,\"annotations\":\"congestion,distance\",\"voice_instructions\":true,\"banner_instructions\":true,\"voice_units\":\"imperial\",\"access_token\":\"YOUR_ACCESS_TOKEN_HERE\",\"uuid\":\"ckcaxjxr292qubeqa8ly2zc9e\"},\"voiceLocale\":\"en-US\"}],\"uuid\":\"ckcaxjxr292qubeqa8ly2zc9e\"}";

    DirectionsRoute routeFromResponse = DirectionsResponse.fromJson(response).routes().get(0);

    NavigationLauncherOptions.Builder optionsBuilder = NavigationLauncherOptions.builder()
      .shouldSimulateRoute(getShouldSimulateRouteFromSharedPreferences());
    CameraPosition initialPosition = new CameraPosition.Builder()
      .target(new LatLng(currentLocation.latitude(), currentLocation.longitude()))
      .zoom(INITIAL_ZOOM)
      .build();
    optionsBuilder.initialMapCameraPosition(initialPosition);
    optionsBuilder.directionsRoute(routeFromResponse);
    String offlinePath = obtainOfflinePath();
    if (!TextUtils.isEmpty(offlinePath)) {
      optionsBuilder.offlineRoutingTilesPath(offlinePath);
    }
    String offlineVersion = retrieveOfflineVersionFromPreferences();
    if (!offlineVersion.isEmpty()) {
      optionsBuilder.offlineRoutingTilesVersion(offlineVersion);
    }
    // TODO Testing dynamic offline
    /**
     * File downloadDirectory = Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_DOWNLOADS);
     * String databaseFilePath = downloadDirectory + "/" + "kingfarm.db";
     * String offlineStyleUrl = "mapbox://styles/mapbox/navigation-guidance-day-v4";
     * optionsBuilder.offlineMapOptions(new MapOfflineOptions(databaseFilePath, offlineStyleUrl));
     */
    NavigationLauncher.startNavigation(this, optionsBuilder.build());
  }
```

Keep in mind that the `DirectionsResponse` / `DirectionsRoute` should be generated using the same version of `mapbox-java`'s `MapboxDirections` service i.e. `v0.42.6` used `mapboxSdkServices` `4.9.0` 👀 https://github.com/mapbox/mapbox-navigation-android/blob/e232efd36700e4f5f3345bd76ad99cb28076bb1e/gradle/dependencies.gradle#L12 and we're currently using `5.3.0` which is a major version and may contain breaking changes.

Also noting here that `NavigationLauncher` won't be supported as part of the `1.0` UI SDK.

**Comment by Guardiola31337** [comment]
Where are we here @sansumbrella? Good to close?

**Comment by sansumbrella** [comment]
I'm now working with the 1.1.0-beta.7 release of the Navigation UI SDK and the 5.3.0 version of the Mapbox Services to [match the SDKs dependency](https://github.com/mapbox/mapbox-navigation-android/blob/release-1.1.0-beta.7/gradle/dependencies.gradle#L11). Unfortunately, I still can't get the application to run with JSON generated by the Mapbox Java services.

![image](https://user-images.githubusercontent.com/81553/89063406-232bf700-d336-11ea-8074-13e9fb8795fd.png)

How was the [JSON used in the repo example app](https://github.com/mapbox/mapbox-navigation-android/blob/release-1.1.0-beta.7/examples/src/main/java/com/mapbox/navigation/examples/ui/NavigationViewActivity.kt#L134-L140) generated? I am able to use that JSON to navigate. Using the following code to generate JSON that looks substantially similar to me somehow produces output that cannot be used to navigate.

<details>
<summary>Logging the MapboxDirections response as JSON</summary>
<pre>
    private fun logDirectionsJSON() {
        val origin = Point.fromLngLat(-77.0365, 38.9392)
        val destination = Point.fromLngLat(-76.9714, 38.9125)
        val client: MapboxDirections = MapboxDirections.builder()
            .waypoints(listOf(origin, destination))
            .overview(DirectionsCriteria.OVERVIEW_FULL)
            .profile(DirectionsCriteria.PROFILE_DRIVING)
            .language(Locale.forLanguageTag("en"))
            .continueStraight(false)
            .roundaboutExits(false)
            .voiceInstructions(true)
            .bannerInstructions(true)
            .voiceUnits(DirectionsCriteria.METRIC)
            .geometries(DirectionsCriteria.GEOMETRY_POLYLINE6)
            .accessToken(getString(R.string.MAPBOX_ACCESS_TOKEN))
            .build()

        client.enqueueCall(object: retrofit2.Callback<DirectionsResponse> {
            override fun onResponse(call: retrofit2.Call<DirectionsResponse>, response: retrofit2.Response<DirectionsResponse>) {
                if (response.body() == null) {
                    Log.e(TAG, "No routes found; set user and access token")
                    return
                } else if (response.body()!!.routes().size < 1) {
                    Log.e(TAG, "No routes found")
                    return
                }

                response.body()?.let {
                    // We then copy the JSON route from the console and paste it into the `useExistingRouteJSON` method
                    val route = it.routes()[0]
                    Log.d(TAG, route.toJson())
                }
            }

            override fun onFailure(call: retrofit2.Call<DirectionsResponse>, t: Throwable) {
                Log.e(TAG,"Error loading stuff ${t.message}")
            }
        })
    }
</pre>
</details>
<details>
<summary>Example JSON response from the logging</summary>
<pre>
{"routeIndex":"0","distance":9077.043,"duration":1316.064,"geometry":"ictgiAxz||qCvD}@d_@?pa@?xL?vN?vD?hB?nC?t@?vN?zP?lP?vH?dPNdbA?jA?fE?pV?`C?hC?xL?fY?bU?pCLjF?n]?xC?tE?vH?tO?rU?xB?lE?v^?dOM|J?`CLz@NzAOhB?|@N|D?tO?`C?xC?bj@OpWNtD?lE?fwANfSLxMMtD?fN?pC?fSOrdANbG?fH?lA?lYL|E?|c@?nC?rB?|Y?z@?|E?vC?dP?ha@?rA?xM?`GNlJ?lE?`C?`C?n]?zA?bB?rj@?tD?nO?bF?rF?vI?pB?jK?~C?hXNdJ?xL?vS?bL?`C?lE??_TFiMG_S?wc@?yW?eEFwM?}T?gD?sQ?iMDgD?aH?_|@E_J?mI?gY?oS?coA?qG?sG?mTDoS?oI?ya@Em^?{`@?{`@?m^Gse@FsFDib@FaH?iB?}@Fm^l@_J|DoS`I}^|DwMfD}J`CqHjKs[xQyj@hM{`@vDkLrKa\\zZy`ArL}^`BsFdFuOtJeZ|Jc[bAyCvC}I`CqH`Mk`@zAsElEyMd@iB|Ocf@`\\ucAvSco@n]_gAzKq\\~DyMrj@qdBxBaHnNgc@jAuDbGqRbAgDtEwNhGaRpRwm@pHkU`GqRt@gDbBML_@xMgc@pBiBnCm@fD?pMMjB?fXL]s[mEcQsF{UyBmJm@iCku@k{CuZqpAgSsy@aM_h@}I}^uEaR_YmiAwCiM_EuOaRiu@kPsp@w^sxA{d@wkBe@iBwIk`@gDkKyGwXmJ}_@gScz@_YyjAey@ygDs[}qAiRgx@u^ewAqB}JcBqHkAcFcAqGsA}JeAiMUiCe@aROuYUmUOiMGsEGiC?qHMeO|D{A~CuDbBeFbVkVhHiL|S}TfOeP`b@ed@|}@y`AbFsFzAsFvg@l_@|TrPtJ`HjFvCzFxCzAeFl@_]?gOFemA?yjA?aq@?cf@LsFFm@F{@FkBF{@jALhB^??","weight":1316.064,"weight_name":"routability","legs":[{"distance":9077.043,"duration":1316.064,"summary":"U Street Northwest, US 50","steps":[]}],"routeOptions":{"baseUrl":"https://api.mapbox.com","user":"mapbox","profile":"driving","coordinates":[[-77.0365,38.9392],[-76.9714,38.9125]],"language":"en","continue_straight":false,"roundabout_exits":false,"geometries":"polyline6","overview":"full","voice_instructions":true,"banner_instructions":true,"voice_units":"metric","access_token":"pk.eyJ1IjoiZGF2aWQtd2lja3MiLCJhIjoiY2tkNG5yZXZkMXoxcDMzcXljb3hlMmc1MCJ9.P3desUxQTk7Syv_LX6UkpA","uuid":"FhkR0pg3yNbmIqzNbY_99ZNXFe90VITVHgNGBEPYXexTebORYqEp6Q\u003d\u003d"}}
</pre>
</details>

**Comment by sansumbrella** [comment]
cc @abhishek1508, since you wrote the [example app](https://github.com/mapbox/mapbox-navigation-android/blob/release-1.1.0-beta.7/examples/src/main/java/com/mapbox/navigation/examples/ui/NavigationViewActivity.kt#L134-L140) that has working JSON route loading. Did it require using the Navigation SDK on Android to generate, or were you able to use Mapbox Java services? I'm not sure what step I'm missing since the Java services version seems to match across my implementation and the nav beta. Thanks!

**Comment by sansumbrella** [comment]
Thanks @Guardiola31337 for the help tracking down the issue. While I was using the correct version of the Java services to generate the route, I was missing a critical option in the settings in my custom implementation that the Navigation SDK sets by default (the steps = true, which is obvious now that I see it).

Here's a snippet for generating a route that worked for us today:
```kotlin
val origin = Point.fromLngLat(-77.0365, 38.9392)
val destination = Point.fromLngLat(-76.9714, 38.9125)
val client: MapboxDirections = MapboxDirections.builder()
    .waypoints(listOf(origin, destination))
    .overview(DirectionsCriteria.OVERVIEW_FULL)
    .profile(DirectionsCriteria.PROFILE_DRIVING)
    .steps(true)
    .annotations(listOf(DirectionsCriteria.ANNOTATION_CONGESTION, DirectionsCriteria.ANNOTATION_DISTANCE))
    .language(Locale.forLanguageTag("en"))
    .continueStraight(false)
    .roundaboutExits(false)
    .voiceInstructions(true)
    .bannerInstructions(true)
    .voiceUnits(DirectionsCriteria.METRIC)
    .geometries(DirectionsCriteria.GEOMETRY_POLYLINE6)
    .accessToken(getString(R.string.MAPBOX_ACCESS_TOKEN))
    .build()
```
