### ISSUE TITLE
Update SDK to use ACCESS_BACKGROUND_LOCATION

### ISSUE THREAD

**Issue by evabishchevich** [mapbox/mapbox-navigation-android#3276]
NavSDK doesn't request ACCESS_BACKGROUND_LOCATION. It would be nice to have a background location access to be able to update notification when apps are in background

**Comment by Guardiola31337** [comment]
Refs. https://github.com/mapbox/mapbox-events-android/issues/490

**Comment by Guardiola31337** [comment]
cc @nkukday
