### ISSUE TITLE
Android: No Snap To Route

### ISSUE THREAD

**Issue by Danny-James** [mapbox/mapbox-navigation-android#329]
I'm now compiling `0.7.0-SNAPSHOT`

When starting the Navigation UI it doesn't seem to be snapping to the route.

**See Images Below**

`Android 4.1.2 - Motorola TC55`
![pc_capture1](https://user-images.githubusercontent.com/32104383/31332757-8bfe1dce-acdf-11e7-90f3-ea08e988ff91.png)

Also the turn images on the Android 4.1.2 Device seem to be very bad quality.

`Android 8.0 - Google Pixel`
![screenshot_20171009-104631](https://user-images.githubusercontent.com/32104383/31332780-9f331066-acdf-11e7-8a96-feb75cda7d01.png)

**Comment by samvgorode** [comment]
@Danny-James does your `onProgressChange` rturn any data while navigation? I've stucked, I have no updates fo my location in this method.

**Comment by Danny-James** [comment]
After Much Investigate This Seems To Be Correct, As I'm Actually In The Building, Once I Move Closer To The Road It Does Snap.
