### ISSUE TITLE
Investigate re-route scenario

### ISSUE THREAD

**Issue by RingerJK** [mapbox/mapbox-navigation-android#3291]
Potential issue:

Reroute/off-route event is not invoked in case if puck is not on route(s) that was sent via `MapboxNavigation.setRoute()`. Potentially it prevents re-route because off-route is called once. 
Scenario:
1. move by turn by turn navigation
2. go off-route
3. `RerouteController` handler set a new route that is out of current location(it might happen if puck moves crossroad when route is fetching from `direction api`/`native` and go to wrong direction)
4. `Off-route Observer` is not called because puck is not actually returned to route 

PR that introduce `RerouteController` https://github.com/mapbox/mapbox-navigation-android/pull/3184

**Comment by Guardiola31337** [comment]
Where are we here @RingerJK? Could this be still an issue?

**Comment by RingerJK** [comment]
Seems that the scenario is not possible anymore, because every time when we set a new route, `offRoute` flag are set to `false` https://github.com/mapbox/mapbox-navigation-android/blob/94d886891aadee76b79f86b7c8db94fcac5c038e/libnavigation-core/src/main/java/com/mapbox/navigation/core/trip/session/MapboxTripSession.kt#L72-L83
We're good to close it
