### ISSUE TITLE
Audit public API

### ISSUE THREAD

**Issue by RingerJK** [mapbox/mapbox-navigation-android#3294]
Audit public API, everything should be changed via UI-thread(public properties, observers, etc.).

**Comment by LukasPaczos** [comment]
I went through a quick exercise for the core SDK in preparation for the stable release https://github.com/mapbox/mapbox-navigation-android/pull/3429.

We should do the same for the UI SDK in the next week or two, before the stable release. I'm happy to run with that as well, just wanted to split it in half.

/cc @mapbox/navigation-android @asinghal22

**Comment by LukasPaczos** [comment]
Here's the UI part - https://github.com/mapbox/mapbox-navigation-android/pull/3436.

**Comment by LukasPaczos** [comment]
Both PRs landed :tada:
