### ISSUE TITLE
VoiceInstruction issue

### ISSUE THREAD

**Issue by tkvalentine56** [mapbox/mapbox-navigation-android#3299]
**Android API:**
**Mapbox Navigation SDK version:**
**see attached file for detailed setup of application**
[MAPBOX_BUG_SUBMISSION_07JUL20.txt](https://github.com/mapbox/mapbox-navigation-android/files/4887052/MAPBOX_BUG_SUBMISSION_07JUL20.txt)

### Steps to trigger behavior

 1. catch the VoiceInstruction in the onNewVoiceInstruction() observer class
 2. modify the VoiceInstruction using:
	newAnnouncement = announcementBuilder.announcement(theNewAnnouncement)
			 .distanceAlongGeometry(voiceInstructions.distanceAlongGeometry())
			 .build();

 3. play the announcement with the speech player

### Expected behavior
Modified VoiceInstruction would be valid and played by the speech player

### Actual behavior
The VoiceInstruction that was modified played the original content of the VoiceInstruction

**A work-around solution**
Adding the ssmlAnnouncement() method call to the builder supplying the modified voice text
will build a useable modified VoiceInstruction object. This may have been the intended usage of the builder but that in not clear in documentation or usage.

	newAnnouncement = announcementBuilder.announcement(theAnnouncement)
			 .distanceAlongGeometry(voiceInstructions.distanceAlongGeometry())
			 //adding ssmlAnnouncement seems to have the voice modification working 30jun20
			 .ssmlAnnouncement(theAnnouncement)
			 .build();

**Comment by JunDai** [comment]
@tkvalentine56 - hey, thanks for reaching out to us.

btw, do you have any chance to checkout [this comment](https://github.com/mapbox/mapbox-navigation-android/issues/3238#issuecomment-651225614) from your previous ticket?

**Comment by JunDai** [comment]
> We are also experiencing two different voices speaking at the same time and have not been able to determine the cause.

Also, I noticed you mention this in the attached text file. I assume it's the same issue as you mentioned in this ticket? https://github.com/mapbox/mapbox-navigation-android/issues/3216#issuecomment-649710342 If so, just let you know that I am currently working on this issue.

**Comment by tkvalentine56** [comment]
I did try the suggestion in #3216 but still got the same incorrect results. The addition of the ssmlAnnouncement() method on the builder solved the problem.

**Comment by JunDai** [comment]
would you mind to show me how do you initialize the `announcementBuilder`? or any sample code would be appreciated so I can take a look what's the problem.

**Comment by tkvalentine56** [comment]
private VoiceInstructionsObserver myVoiceInstructionsObserver = new VoiceInstructionsObserver(){
		@Override
		public void onNewVoiceInstructions(@NotNull VoiceInstructions voiceInstructions){
			VoiceInstructions newAnnouncement = null;
			String theAnnouncement = voiceInstructions.announcement();
			logger.info("$$$ MAPBOX : ENTER $$$$$$$$$$$$$$$$$$$$$$$$$$$$ " +
						theAnnouncement);

                        String newSpeechText = "Rock-n-Roll will never die.";
                        //========THIS WORKS===================================
			newAnnouncement = announcementBuilder.announcement(newSpeechText )
                                                                 .distanceAlongGeometry(voiceInstructions.distanceAlongGeometry())
								 //adding ssmlAnnouncement seems to have the voice modification working 30jun20
								 .ssmlAnnouncement(newSpeechText )
								 .build();
//                        //========THIS DOES NOT WORK===================================
//			newAnnouncement = announcementBuilder.announcement(newSpeechText )
//                                                                 .distanceAlongGeometry(voiceInstructions.distanceAlongGeometry())
//								 .build();

			myNavigationSpeechPlayer.play(newAnnouncement);
			logger.info("$$$ MAPBOX : EXIT $$$$$$$$$$$$$$$$$$$$$$$$$$$$ ");
		}
	};

**Comment by JunDai** [comment]
@tkvalentine56 - I don't know where is the `announcementBuilder` and how it looks like. But would you mind to use this code snippet to try?

So **DO NOT** use your `announcementBuilder` and just use the `VoiceInstructions.builder()`.

```kotlin
    private val voiceInstructionsObserver = object : VoiceInstructionsObserver {
        override fun onNewVoiceInstructions(voiceInstructions: VoiceInstructions) {
            val newSpeechText = "Rock-n-Roll will never die."
            speechPlayer.play(VoiceInstructions.builder().announcement(newSpeechText).build())
        }
    }
```

This is from https://github.com/mapbox/mapbox-navigation-android/issues/3238#issuecomment-651225614

**Comment by JunDai** [comment]
hey @tkvalentine56, have you got any chance to try my sample code above? Feel free to comment if it still doesn't work.

**Comment by tkvalentine56** [comment]
I am modifying the voice instruction not creating an entirely new unrelated voice instruction see attached code snippet
[voice_instruction_code_snippet.txt](https://github.com/mapbox/mapbox-navigation-android/files/4932778/voice_instruction_code_snippet.txt)

**Comment by JunDai** [comment]
hey @tkvalentine56 - thanks for the code snippet.

I created a separate branch and am using your code snippet. It seems working for me. You could checkout the code here: https://github.com/mapbox/mapbox-navigation-android/blob/jd-add-instruction-view-activity-java-example/examples/src/main/java/com/mapbox/navigation/examples/core/InstructionViewActivityJava.java#L486-L534

The sample code I am using is almost same as yours. I removed the if condition `if(theAnnouncement.contains("\u00A0")){` since I don't find one test data can match it.
I also commented the 
```java
.distanceAlongGeometry(voiceInstructions.distanceAlongGeometry())
.ssmlAnnouncement(theAnnouncement)
```
when building the new announcement. It's working for me.

I am wondering if I am missing some setup in your activity? Would you mind to share with me the whole activity or a runnable example code which has this issue? So I can take a look and check what's wrong there?

Please feel free to checkout my sample code and let me know if it works or not.
Thanks

**Comment by JunDai** [comment]
> I have implemented your suggested changes and will road test to validate.

@tkvalentine56 - hey, have you got any chance to test your change?

**Comment by steventanwc** [comment]
Hi guys,

Do u know if I can use my own sound clip/file instead of using TTS?

**Comment by JunDai** [comment]
> Hi guys,
> 
> Do u know if I can use my own sound clip/file instead of using TTS?

@steventanwc - I don't think it's supported.

**Comment by tkvalentine56** [comment]
Road tested and appears to work as I have implemented in:

https://github.com/mapbox/mapbox-navigation-android/files/4932778/voice_instruction_code_snippet.txt

**Comment by JunDai** [comment]
> Road tested and appears to work as I have implemented in:
> 
> https://github.com/mapbox/mapbox-navigation-android/files/4932778/voice_instruction_code_snippet.txt

cool, thanks for confirming. 
I am closing this ticket now. Feel free to reach out to us if there is still issue around this.

cc: @tkvalentine56
