### ISSUE TITLE
BannerInstruction issue

### ISSUE THREAD

**Issue by tkvalentine56** [mapbox/mapbox-navigation-android#3300]
**Android API:**
**Mapbox Navigation SDK version:**
**see attached file for detailed setup of application**
[MAPBOX_BUG_SUBMISSION_07JUL20.txt](https://github.com/mapbox/mapbox-navigation-android/files/4887052/MAPBOX_BUG_SUBMISSION_07JUL20.txt)

### Steps to trigger behavior

 1. catch the BannerInstruction in the onNewBannerInstruction() observer class
 2. modify the BannerInstruction  using:
	newAnnouncement = announcementBuilder.announcement(theNewAnnouncement)
			 .distanceAlongGeometry(voiceInstructions.distanceAlongGeometry())
			 .build();

 3. update the display via myBannerInstructionView.updateBannerInstructionsWith(newBannerInstructions)

### Expected behavior
Modified BannerInstruction would be displayed

### Actual behavior
The BannerInstruction that was modified appears to not be displayed.

**NOTE**
I have not proven this hunch of what is likely happening but here is my observation on this issue:
I believe the the modification of the BannerInstruction is successful and that it is successfully being displayed in the BannerInstructionView component via myBannerInstructionView.updateBannerInstructionsWith(newBannerInstructions). So possibly other processes are updating the bannerInstructionView. There needs to be some management of who owns the bannerInstructionsView updating process if the application is registering custom listeners.

**Comment by JunDai** [comment]
> ### Steps to trigger behavior
> 1. catch the BannerInstruction in the onNewBannerInstruction() observer class
> 2. modify the BannerInstruction  using:
>    newAnnouncement = announcementBuilder.announcement(theNewAnnouncement)
>    .distanceAlongGeometry(voiceInstructions.distanceAlongGeometry())
>    .build();
> 3. update the display via myBannerInstructionView.updateBannerInstructionsWith(newBannerInstructions)

hey @tkvalentine56 - thanks for reaching out to us.

From your description in the `Steps` and the file `MAPBOX_BUG_SUBMISSION_07JUL20.txt`, I don't see how you generate the `BannerInstructions` instance. As you can see, the code is about the `voiceInstruction`.

Would you mind to show me how does your `onNewBannerInstruction()` implementation look like? Another question is are you using the `NavigationView` or just the `InstructionView` in your `MyMapboxNavigationActivity`?

I would be happy to check the issue once I get more informations. Please feel free to comment.

**Comment by tkvalentine56** [comment]
Sorry, about the code snippet mixup.

[banner_code_snippet.txt](https://github.com/mapbox/mapbox-navigation-android/files/4932718/banner_code_snippet.txt)

above is the actual code used to handle the BannerInstruction(s). This code strips the extra embedded text (created in the waynames supplied at route request) to display elsewhere. myBannerInstructionView is an instance of InstructionView.
onNewBannerInstructions calls cleanupBannerInstructions to return a truncated BannerInstruction to display.

**Comment by tkvalentine56** [comment]
This issue is really the same as #1224

**Comment by JunDai** [comment]
> Sorry, about the code snippet mixup.
> 
> [banner_code_snippet.txt](https://github.com/mapbox/mapbox-navigation-android/files/4932718/banner_code_snippet.txt)
> 
> above is the actual code used to handle the BannerInstruction(s). This code strips the extra embedded text (created in the waynames supplied at route request) to display elsewhere. myBannerInstructionView is an instance of InstructionView.
> onNewBannerInstructions calls cleanupBannerInstructions to return a truncated BannerInstruction to display.

@tkvalentine56 - got it, thanks for the info. We will check this.

**Comment by JunDai** [comment]
@tkvalentine56 - I checked your code. The reason that why your code doesn't work is complicated. We have a logic to set the bannerInstruction text within our Navigation UI SDK.
That logic relies on the `BannerInstructions's` primary banner text's `component` data. You could refer to the logic [here](https://github.com/mapbox/mapbox-navigation-android/blob/jd-add-instruction-view-activity-java-example/libnavigation-ui/src/main/java/com/mapbox/navigation/ui/instruction/AbbreviationCreator.java#L65) if you have interest in it.

I would suggest not to customize the data of it, it might bring some undefined behavior.

But if you really want to customize the bannerInstructionText, [this code](https://github.com/mapbox/mapbox-navigation-android/blob/jd-add-instruction-view-activity-java-example/examples/src/main/java/com/mapbox/navigation/examples/core/InstructionViewActivityJava.java#L562-L570) is a workaround of it. You need to modify the `component`'s text.

Please refer to the gif, you could see some of the banner instruction text has **Test;** at the end. That's added by the workaround mentioned above.

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/3918950/87834096-60748d00-c83e-11ea-8c49-f79eaa315b1e.gif)

**Comment by tkvalentine56** [comment]
Your 'component' based sample to modify banner
instructions seems to be successful as road tested.

The issue here is correct usage of the BannerInstruction object, its components and the usage of the builders to modify/build correctly. This is not apparent in the design of the BannerInstruction object (or documentation of the same).
As you stated in the suggested fix, you must access and manipulate the components of BannerInstruction not the primary, secondary or sub path of access. Just not clear this is the way to do it.

**Comment by JunDai** [comment]
Glad to hear that it somehow works.
You can refer the BannerInstructions design [here](https://docs.mapbox.com/api/navigation/#banner-instruction-object) for more details about its design.

Yeah, if you want to customize the banner text and/or the InstructionList text in terms of the Navigation UI SDK's InstructionView, you have to manipulate the `components` data of the BannerInstructions. That's the way how the SDK uses the data.

**Comment by JunDai** [comment]
@tkvalentine56 - I am closing this ticket. But feel free to let's know if you have more issues around the BannerInstructions and we can discuss.
