### ISSUE TITLE
Navigation Beta SDK backwards compatibility with Navigation UI SDK

### ISSUE THREAD

**Issue by cyber-gh** [mapbox/mapbox-navigation-android#3304]
I am looking to use Navigation UI SDK with the new Navigation Beta SDK.
Is it possible? Is there a Navigation UI Beta update perhaps?

Or should I implement my own Navigation UI components?

More precisely what I'm looking for is to use `com.mapbox.services.android.navigation.ui.v5.instruction.InstructionView`, but all the parameters are slightly different.

For example `instrucitonView.updateDistanceWith` requires an `com.mapbox.services.android.navigation.v5.routeprogress.RouteProgress!` but what I got from the Navigation Beta SDK is `com.mapbox.navigation.base.trip.model.RouteProgress!`

**Comment by Guardiola31337** [comment]
Hey @cyber-gh 👋 thanks for checking out the SDK 🙇‍♂️ 

You're right. For now, only Core SDK is available but we're working hard to get it released 🔜 Stay tuned!

In the meantime you can review the [developer documentation](https://docs.mapbox.com/android/beta/navigation/overview/#installation) to start building with the Mapbox core Navigation SDK v1.0 for Android and if you already use an older version of the Navigation SDK, check out [the migration guide](https://github.com/mapbox/mapbox-navigation-android/wiki/1.0-Navigation-SDK-Migration-Guide) to transition your project from the "legacy" core Navigation SDK to the 1.0 version and let us know if you have any questions or run into issues and please open tickets in https://github.com/mapbox/mapbox-navigation-android/issues/new and we will take it from there! We would love your feedback.

You can also look at the code under `libnavigation-ui` and try to implement yourself but as mentioned `1.0` compatible UI SDK is around the corner 🚀 

Thanks again!

cc @abhishek1508

**Comment by cyber-gh** [comment]
Do you have an estimated release date for the Navigation Beta UI SDK ?

**Comment by Guardiola31337** [comment]
@cyber-gh Sure! First RC was released two weeks ago. Latest release available is `rc.6` https://github.com/mapbox/mapbox-navigation-android/releases/tag/release_ui_1.0.0-rc.6_core_1.0.0-rc.6

We appreciate any feedback you might have so that we can address it before going stable, thanks!
