### ISSUE TITLE
 The cycling route includes sections where cycling is prohibited

### ISSUE THREAD

**Issue by Bter** [mapbox/mapbox-navigation-android#3311]
Platform: Android
mapbox-android-navigation-ui:0.42.6

During the planning of the cycling route, the results include the prohibition of cycling, how to solve this problem?
code show as below:
```jsx
NavigationRoute.Builder builder = NavigationRoute.builder(Context)
                                                 .accessToken(token)
                                                 .profile(DirectionsCriteria.PROFILE_CYCLING)
                                                 .origin(Point.fromLngLat(121.471842,25.049521))
                                                 .destination(Point.fromLngLat(121.45079,25.032533))
                                                 .build()
                                                 .getRoute();
```
<img src="https://user-images.githubusercontent.com/20014318/87004816-a0a98f00-c1f0-11ea-9378-26f230bd1d4d.png" width="300"/><img src="https://user-images.githubusercontent.com/20014318/87006180-d3ed1d80-c1f2-11ea-97a3-ef5809ebb7e7.png" width="300"/>

**Comment by Guardiola31337** [comment]
cc @mapbox/navigation-api @danpat @danpaz

**Comment by PureW** [comment]
It's a little hard to see exactly what street you are looking at, but if it is https://www.openstreetmap.org/way/232888055 then it's not marked as cycling forbidden in OpenStreetmap yet.

**Comment by Guardiola31337** [comment]
Thanks for following up @PureW 🙇‍♂️ 

Closing here as answered.

**Comment by Bter** [comment]
Thanks @PureW
