### ISSUE TITLE
Consolidate custom okhttp changes into common

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-navigation-android#3324]
Once we integrate this repository with Mapbox Maps SDK for Android v10.0.0, this repository should consolidate it's custom http stack into the okhttp library from common. Only 1 http stack can be registered through common and we should move towards standardizing both maps as nav requirements into the default implementation. 

cc @LukasPaczos

**Comment by LukasPaczos** [comment]
Awaiting the release of Nav Native with the Common SDK 7.1.

**Comment by Guardiola31337** [comment]
> Awaiting the release of Nav Native with the Common SDK 7.1.

That happened in https://github.com/mapbox/mapbox-navigation-android/pull/3582/files#diff-6512f838e273b79676cac5f72456127fR14 🎉 

Good to close here @LukasPaczos?
