### ISSUE TITLE
Add documentation on 1.0.0 navigation styling/theming and migration

### ISSUE THREAD

**Issue by carstenhag** [mapbox/mapbox-navigation-android#3330]
**Mapbox Navigation SDK version:** 1.0.0-rc2

### Steps to trigger behavior

 1. Visit beta docs
 2. See no customization/theming page :(
 3. Be sad because the app doesn't compile after migrating from 0.x to 1.0.0-rc2 because the styles are not found

### Expected behavior
There should be a page explaining all the theming possibilities. Also, it would be really helpful to have a migration guide for this.

### Actual behavior
There's no site for this, I think I have to dig into the views and look up the attrs by myself, which is pretty annoying.

**Comment by Guardiola31337** [comment]
Closing here in favor of https://github.com/mapbox/mapbox-navigation-android/issues/3502

As a heads up, worth mentioning that we're working on updating the UI documentation and the Migration guide and will definitely include a theming section describing this.

Thanks for checking out the SDK @carstenhag 

cc @abhishek1508 @langsmith @JunDai @cafesilencio
