### ISSUE TITLE
Failed to resolve: com.mapbox.mapboxsdk:mapbox-android-sdk:9.3.0-beta.1

### ISSUE THREAD

**Issue by tkvalentine56** [mapbox/mapbox-navigation-android#3332]
**Android API:**
        implementation 'com.mapbox.navigation:ui-v1:1.1.0-beta.7'
        implementation 'com.mapbox.navigation:router-offboard:1.1.0-beta.7'
        implementation 'com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v9:0.8.0'

**Mapbox Navigation SDK version:**
??? Embedded in above listed API components.

### Steps to trigger behavior

 1. Use above listed API components in project
 2. Sync/resync Gradle or rebuild project

### Expected behavior
Project is built successfully

### Actual behavior
Failed to resolve: com.mapbox.mapboxsdk:mapbox-android-sdk:9.3.0-beta.1

**Comment by LukasPaczos** [comment]
Hey @tkvalentine56, you can follow these refreshed instructions https://docs.mapbox.com/android/beta/navigation/overview/#install-the-navigation-sdk and add the below dependency for a preview of the newest UI and Core Nav SDKs:
```
implementation 'com.mapbox.navigation:core:1.0.0-rc.3' // for Nav Core SDK only
```
```
implementation 'com.mapbox.navigation:ui-v1:1.0.0-beta.1' // for Nav Core and UI SDKs
```

Let us know if it doesn't work for you!

**Comment by tkvalentine56** [comment]
Does not work:

Unable to resolve dependency for ':app@debugAndroidTest/compileClasspath':
Could not resolve com.mapbox.navigation:ui-v1:1.0.0-beta.1.

**Comment by LukasPaczos** [comment]
@tkvalentine56 did you recreate your token to include the new `DOWNLOADS:READ` scoped instead of `NAVIGATION:DOWNLOAD` (deprecated) as specified in the instructions?

**Comment by tkvalentine56** [comment]
why was this closed? I did not report on implementing your suggestion.

I followed the directions as you suggested in:

[https://docs.mapbox.com/android/beta/navigation/overview/#install-the-navigation-sdk](https://docs.mapbox.com/android/beta/navigation/overview/#install-the-navigation-sdk) and add the below dependency for a preview of the newest UI and Core Nav SDKs:

implementation 'com.mapbox.navigation:core:1.0.0-rc.3' // for Nav Core SDK only
implementation 'com.mapbox.navigation:ui-v1:1.0.0-beta.1' // for Nav Core and UI SDKs

and it did not work as it could not find 'com.mapbox.navigation:core:1.0.0-rc.3' or 'com.mapbox.navigation:ui-v1:1.0.0-beta.1'

I then did as you suggested in:

recreate your token to include the new DOWNLOADS:READ scoped instead of NAVIGATION:DOWNLOAD (deprecated) as specified in the instructions?

I was able to access 'com.mapbox.navigation:core:1.0.0-rc.3' but it could not find 'com.mapbox.navigation:ui-v1:1.0.0-beta.1'.
So I removed the reference to 'com.mapbox.navigation:ui-v1:1.0.0-beta.1' and the project was missing reference to the UI components.

I then switched back to using the starting components of:
implementation 'com.mapbox.navigation:ui-v1:1.1.0-beta.7'
implementation 'com.mapbox.navigation:router-offboard:1.1.0-beta.7'
implementation 'com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v9:0.8.0'

and the project resolved com.mapbox.mapboxsdk:mapbox-android-sdk:9.3.0-beta.1

To resolve I did then following:
1. Reconfigured my credentials using:
        A public access token: From your account's tokens page, you can either copy your default public token or click the Create a 
       token button to create a new public token.
       A secret access token with the DOWNLOADS:READ scope:
2. Adding this new repository endpoint:
allprojects {
    repositories {
        maven {
            url 'https://api.mapbox.com/downloads/v2/releases/maven'
            authentication {
                basic(BasicAuthentication)
            }
            credentials {
                username = "mapbox"
                // Use the secret token you stored in gradle.properties as the password
                password = project.properties['MAPBOX_DOWNLOADS_TOKEN'] ?: ""
            }
        }
    }
}

The directions at
[https://docs.mapbox.com/android/beta/navigation/overview/#install-the-navigation-sdk](https://docs.mapbox.com/android/beta/navigation/overview/#install-the-navigation-sdk) refers to implementing
'com.mapbox.navigation:core:1.0.0-rc.3' not the mapbox_collab repository components **_yet it appears that the
'com.mapbox.navigation:ui-v1:1.1.0-beta.7' component in mapbox_collab needs access to
url 'https://api.mapbox.com/downloads/v2/releases/maven'
to resolve com.mapbox.mapboxsdk:mapbox-android-sdk:9.3.0-beta.1_**

This is not documented to my knowledge and would likely seem to be an error of oversight to make a BETA component  have a dependency on a production component located in an external repository.
