### ISSUE TITLE
Expose the route line below layer ID as an option in NavigationViewOptions

### ISSUE THREAD

**Issue by cafesilencio** [mapbox/mapbox-navigation-android#3334]
As a response to #2561. The map route line belowLayerId should be exposed as an option in NavivationViewOptions so that users of NavigationView can specify the elevation of the route line.

**Comment by cafesilencio** [comment]
Just a note here, this is not a trivial effort. This option is available in other parts of the SDK.

Needs prioritization.

**Comment by Guardiola31337** [comment]
Where are we here @cafesilencio? Could you provide an update when you have a chance? 🙏

**Comment by cafesilencio** [comment]
I don't think this can be done in 1.x without breaking SemVer and as I commented before it would not be trivial. This is not an issue in the 2.0 API redesign.

**Comment by cafesilencio** [comment]
Since this issue is resolved in 2.x I'm closing this ticket.
