### ISSUE TITLE
Unable to build examples app - build instructions missing

### ISSUE THREAD

**Issue by carstenhag** [mapbox/mapbox-navigation-android#3349]
**Android API:**
**Mapbox Navigation SDK version:** tag `release_core_1.0.0-rc.2` of this repo

### Steps to trigger behavior

 1. Check out `release_core_1.0.0-rc.2` (found in an issue comment)
 2. Run gradle task examples/installDebug or `./gradlew examples:installDebug`
 3. Get "no authorization errors" due to Bintray credentials missing
 4. Have no clue how to continue, because there's no `BUILDING.md` in the repo or in the examples folder. The readme also doesn't contain anything about building the examples or the repo.

### Expected behavior
There is documentation on how to build the repo or at least the examples repo.

### Actual behavior
No documentation is available :(. No clue which bintray credentials I need.

```
FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':examples:compileDebugJavaWithJavac'.
> Could not resolve all task dependencies for configuration ':examples:debugCompileClasspath'.
   > Could not resolve com.mapbox.navigator:mapbox-navigation-native:13.0.2.
     Required by:
         project :examples > project :libnavigator
      > Could not resolve com.mapbox.navigator:mapbox-navigation-native:13.0.2.
         > Could not get resource 'https://mapbox.bintray.com/mapbox_collab/com/mapbox/navigator/mapbox-navigation-native/13.0.2/mapbox-navigation-native-13.0.2.pom'.
            > Username must not be null!
      > Could not resolve com.mapbox.navigator:mapbox-navigation-native:13.0.2.
         > Could not get resource 'https://mapbox.bintray.com/mapbox_private/com/mapbox/navigator/mapbox-navigation-native/13.0.2/mapbox-navigation-native-13.0.2.pom'.
            > Username must not be null!
      > Could not resolve com.mapbox.navigator:mapbox-navigation-native:13.0.2.
         > Could not get resource 'https://oss.jfrog.org/artifactory/oss-snapshot-local/com/mapbox/navigator/mapbox-navigation-native/13.0.2/mapbox-navigation-native-13.0.2.pom'.
            > Could not HEAD 'https://oss.jfrog.org/artifactory/oss-snapshot-local/com/mapbox/navigator/mapbox-navigation-native/13.0.2/mapbox-navigation-native-13.0.2.pom'. Received status code 409 from server: 
      > Could not resolve com.mapbox.navigator:mapbox-navigation-native:13.0.2.
         > Could not get resource 'https://mapbox.bintray.com/mapbox_internal/com/mapbox/navigator/mapbox-navigation-native/13.0.2/mapbox-navigation-native-13.0.2.pom'.
            > Username must not be null!
```

**Comment by kmadsen** [comment]
cc: @LukasPaczos @Guardiola31337 @zugaldia

**Comment by LukasPaczos** [comment]
Hey @carstenhag! We're in the process of migrating to a new distribution system (you can see some of the progress in https://github.com/mapbox/mapbox-navigation-android/pull/3353) across Mapbox projects, also the ones that we're depending on when building the Nav SDK. This means that as of now there's no straightforward way to clone and build the repo from source. Once the migration is finished in the next couple of days/weeks we'll make sure to update the docs accordingly. Let's keep this ticket open until then.

**Comment by LukasPaczos** [comment]
Currently blocked by https://github.com/mapbox/mapbox-navigation-android/pull/3370#issuecomment-663564293.
