### ISSUE TITLE
Performance issues in the navigation component of mapbox map for android

### ISSUE THREAD

**Issue by matheus511377** [mapbox/mapbox-navigation-android#3358]
I'm relatively new to MapBox, however, I'm having difficulties regarding the navigation component, I used the navigation example that they show on their website, but it runs with a lot of lag, very slowly, consuming 100% of the cpu from my Android device. Has anyone else been there?

![lag](https://user-images.githubusercontent.com/6319126/87907982-0e00bf80-ca3c-11ea-8023-1db57db633b7.gif)

**Comment by LukasPaczos** [comment]
Hey @matheus511377, thanks for reaching out! Are you using the `1.0.0+` components or legacy `0.43.x`?

**Comment by matheus511377** [comment]
Hey @LukasPaczos , sorry for the delay, I'm using it like this:

implementation 'com.mapbox.mapboxsdk:mapbox-android-sdk:9.3.0'
implementation 'com.mapbox.mapboxsdk:mapbox-android-navigation-ui:0.42.6'

**Comment by LukasPaczos** [comment]
Thanks @matheus511377! This is most likely a performance regression coming from the Maps SDK 9.3.0. We are preparing a patch release (9.3.1) that addresses the issue.

**Comment by matheus511377** [comment]
Okay, do you have any release predictions?

just for the record, before I was using sdk version 9.2 and had the same behavior.

I simply do this:

NavigationLauncherOptions options = NavigationLauncherOptions.builder()
.directionsRoute(route)
.shouldSimulateRoute(simulateRoute)
.build();
 
NavigationLauncher.startNavigation(this, options);

**Comment by matheus511377** [comment]
Hi, @LukasPaczos sorry to be bothering you, but you were the only one who answered, do you have a position on that?

**Comment by LukasPaczos** [comment]
Hey @matheus511377, could you retest with Maps SDK `9.3.1`?

**Comment by matheus511377** [comment]
Hello, thank you very much, it worked as it should.

I have one more problem, but for now there is no problem. I am Brazilian, and the translation of the navigation voice works directly, but when I need to leave the roundabout, he speaks the phrase in English. he says "exit to roundabout" instead of "saia da rotatória"

**Comment by LukasPaczos** [comment]
Happy to hear that the performance is restored!

Would you be able to follow up with the voice guidance issues in a separate ticket? Thank you!
