### ISSUE TITLE
Locations dropped after each reroute

### ISSUE THREAD

**Issue by ericrwolfe** [mapbox/mapbox-navigation-android#336]
Currently when a reroute occurs, navigation adds the current locations to the reroute event, and then resets the location buffer for the next event. 

In many cases, the locations for reroute/feedback events will overlap, so we should keep a running buffer of 40 locations and simply copy the locations (+ use a filter to split the array) when a reroute event is created so we don't drop locations.

cc @cammace

**Comment by ericrwolfe** [comment]
This is being addressed by #348.

**Comment by cammace** [comment]
https://github.com/mapbox/mapbox-navigation-android/pull/348 has been merged and will be in the 0.6.3 release.
