### ISSUE TITLE
feedbackId should not be empty

### ISSUE THREAD

**Issue by ericrwolfe** [mapbox/mapbox-navigation-android#338]
`feedbackId` currently is always set to an empty string `""`. We should always set this to a unique id. 

cc @cammace

**Comment by cammace** [comment]
@electrostat or @Guardiola31337 could you guys take a look at this?

cc: @zugaldia

**Comment by Guardiola31337** [comment]
Addressed in #352 👇
Assuming we want to create a new `feedbackId` on each navigation session and it should be different than the `sessionIdentifier`.

cc @cammace @ericrwolfe

**Comment by ericrwolfe** [comment]
@Guardiola31337 `feedbackId` would be unique to each feedback or reroute event, rather than unique to each navigation session. `sessionIdentifier` would be the only id that would stay the same across events in a navigation session.

**Comment by ericrwolfe** [comment]
Also, `feedbackId` should be generated in the nav sdk when the event is queued up, rather than as telem is sent off. As we implement the feedback UI, the `feedbackId` will need to be passed back to developers so that they can later update the feedback event with additional metadata. 

This is what the API currently looks like on iOS:
https://github.com/mapbox/mapbox-navigation-ios/blob/41860934843653fd6f7402219e6bb179482f71bd/MapboxCoreNavigation/RouteController.swift#L345-L380

cc @Guardiola31337

**Comment by Guardiola31337** [comment]
> `feedbackId` would be unique to each feedback or reroute event, rather than unique to each navigation session.

Reopening.

**Comment by Guardiola31337** [comment]
#359 addressed your comment @ericrwolfe 
Now should be working as expected.
