### ISSUE TITLE
Investigate status race condition when a new route is set

### ISSUE THREAD

**Issue by LukasPaczos** [mapbox/mapbox-navigation-android#3383]
Capturing a customer bug report:
> During stop guidance we are resting route by seting an empty list:
`mapboxNavigation.setRoutes(emptyList())`
even after that we are getting an off-route event:
`fun onOffRouteStateChanged(offRoute: Boolean)` (with value `true`)

> It's very hard to reproduce, but the idea is that off-route event should check if there is a route available before emitting an event

When we are getting a route, the navigator call is guarded by a mutex, but the delivery to the developer is done in unsynchronized coroutines:
https://github.com/mapbox/mapbox-navigation-android/blob/9e36a942558b38904389abe70b8c873bfbb89bad/libnavigation-core/src/main/java/com/mapbox/navigation/core/trip/session/MapboxTripSession.kt#L412-L419
also worth noting that `getNavigatorStatus` is run on a background thread, so there can be a chain of events:

1. `getStatus` called on a background thread and reports off-route
2. developer calls `setRoutes(empty)` on the main thread
3. status from `1.` is switched to the main thread and delivered to the developer

As you can see, there's a chance that we will deliver an outdated status to a developer _after_ they have cleared the route. There might be more of such cases lingering in this codebase. Possibly, we can cancel all of the pending status actions if the route is reset, or synchronize the coroutines in the `MapboxTripSession`.

/cc @korshaknn @Lebedinsky @RingerJK @kmadsen

**Comment by kmadsen** [comment]
sharing another idea - not sure if it is better than canceling requests. we could also ensure that the status.routeProgress route is equal to the tripSession route before triggering an offRoute event.
