### ISSUE TITLE
Route line disappears after lifecycle change

### ISSUE THREAD

**Issue by LukasPaczos** [mapbox/mapbox-navigation-android#3389]
Reproducible in the example:
![ezgif com-optimize (55)](https://user-images.githubusercontent.com/16925074/89183742-fbd46480-d597-11ea-9c3a-bd0f594fcf4f.gif)

/cc @abhishek1508 @cafesilencio

**Comment by cafesilencio** [comment]
This issue was resolved in PR #3399
