### ISSUE TITLE
Add NavigationSpeechPlayer functionality

### ISSUE THREAD

**Issue by tkvalentine56** [mapbox/mapbox-navigation-android#3396]
NavigationSpeechPlayer currently has minimal control, i.e. play or mute or offRoute.
It also allows multiple voicings to be played simultaneously.

Would be useful to be able to sequence the voicings to play one at a time (from a queue).
Would also be useful to access the queue to modify its content.

**Comment by JunDai** [comment]
> It also allows multiple voicings to be played simultaneously.

hey @tkvalentine56 - is this same as https://github.com/mapbox/mapbox-navigation-android/issues/3216#issuecomment-649710342 ?

Would you mind to share more information about which Navigation UI SDK version are you using and what you observed for this `multiple voicings to be played simultaneously` issue so we can take a look?

**Comment by tkvalentine56** [comment]
#3216 is part of my issue here. Was just noting that if we had access to a
queued list of voice information items we could better control them.

**Comment by JunDai** [comment]
> #3216 is part of my issue here. Was just noting that if we had access to a queued list of voice information items we could better control them.

The issue #3216 has been fixed and you should be able to verify it with our latest beta release.

Please refer https://github.com/mapbox/mapbox-navigation-android/issues/3332#issuecomment-667042565 to integrates the latest beta release.
