### ISSUE TITLE
Improve API related to hiding and showing routes and maneuver arrows

### ISSUE THREAD

**Issue by cafesilencio** [mapbox/mapbox-navigation-android#3398]
Referencing https://github.com/mapbox/1tap-android/issues/334. There has been some discussion around this API detail in the past.  Hiding the routes via NavigationMapboxMap will also implicitly hide the maneuver arrows. Yet a developer can draw a new route which will make the route visible but not the arrows as showRoute() must be called on NavigationMapboxMap in order to set the arrow visibility to visible. This isn't necessarily intuitive. In addition there have been cases in which customers have explicitly hidden the arrows for their own use cases so care must be taken not to automatically make them visible as well. 

Some discussion around this is warranted as well as any implementation changes that are decided on.

**Comment by Guardiola31337** [comment]
Where are we here @cafesilencio? Could you provide an update when you have a chance? 🙏

**Comment by Guardiola31337** [comment]
Where are we here? Any updates? @cafesilencio @abhishek1508

**Comment by cafesilencio** [comment]
In 2.x there are methods for hiding and showing routes and arrows separately and more explicitly.  Closing this issue.
