### ISSUE TITLE
Prevent abrupt re-routing / immediate u-turns

### ISSUE THREAD

**Issue by ericrwolfe** [mapbox/mapbox-navigation-android#34]
Occasionally during rerouting, the SDK will return a maneuver that's too close to the user's current location and can lead to a missed turn and frequent + repeated re-routing.

> If the user was driving 70km/h along a road and missed a left turn, the navigation SDK would trigger a re-route and receive a directions response requiring another left turn or U-turn almost immediately. At the high speed the user was traveling, the immediacy of the maneuver would be too much to act on, and the user would miss the turn and trigger another re-route, and so on.

As a first pass suggestion by @danpat, we can validate that a re-route is reasonable before presenting to the user:
> 1. Request the re-route and get back the new response from the Directions API.
> 2. Examine the first step. If it's not too quick, display the re-route to the user.
If it is "too quick" (threshold to be determined), use the intersections object to predict the driver's probable path past the "too quick turn", and request another route from the Directions API that starts somewhere past the "too quick" turn.

cc @cammace

**Comment by ericrwolfe** [comment]
Also related: #37

**Comment by ericrwolfe** [comment]
Initial re-routing improvements added in #44 via #37. We'll keep this open pending some further testing.

**Comment by mecoFarid** [comment]
@ericrwolfe If you have implemented navigation could you post code snippet (non-confidential parts), so I could implement it in my App. I'm unable to get it work as of problems listed #124 and #123. Thanks a lot.

**Comment by cammace** [comment]
I think we are safe to close here. @danesfeder and I have done a few test drives and haven't run into too many issues with rerouting, the issues we ran into were oftentimes edge cases that can be tracked in a different ticket. @ericrwolfe is there anything further actionable here?

**Comment by ericrwolfe** [comment]
Nope, I think we're good to close.
