### ISSUE TITLE
Always consider a maneuver as complete if distanceRemaining = 0

### ISSUE THREAD

**Issue by ericrwolfe** [mapbox/mapbox-navigation-android#341]
_Android version of https://github.com/mapbox/mapbox-navigation-ios/issues/698_

There are cases, particularly with roundabouts in Europe and tight sequences of turns, where the geometry of a maneuver might not match the actual path a car takes. 

For example, in the following case, the in-bearing and out-bearing of the `enter roundabout` maneuver would be `0` and `90` respectively, but the location bearings would never exceed 15-20° if the driver "cut" the corners.

<img src="https://user-images.githubusercontent.com/664805/31362560-fdbb7fbe-ad0d-11e7-9f92-0925f684694a.png" width="150">

The turn would never be considered complete, and the snapped location would get stuck before jumping ahead to the next maneuver just before rerouting.

cc @cammace

**Comment by ericrwolfe** [comment]
Somewhat related: https://github.com/mapbox/mapbox-navigation-android/issues/35

**Comment by cammace** [comment]
Thinking this ticket can be moved to 0.7.1 @ericrwolfe?

**Comment by danesfeder** [comment]
Closed by https://github.com/mapbox/mapbox-navigation-android/pull/773/
