### ISSUE TITLE
Backgroundcolor of next instruction

### ISSUE THREAD

**Issue by richterCLX** [mapbox/mapbox-navigation-android#3416]
**Android API:** 28
**Mapbox Navigation SDK version:** 0.42.4

How can i change the backgroundcolor of bottom next instruction banner? 

![image](https://user-images.githubusercontent.com/48920917/89507024-3de5ec00-d7cc-11ea-9ee3-257f7fef5861.png)

**Comment by Guardiola31337** [comment]
@JunDai Is this something feasible in `1.0`?

cc @abhishek1508

**Comment by abhishek1508** [comment]
It is feasible in `1.0` using this property
```
<item name="instructionViewSecondaryBackgroundColor">?attr/navigationViewSecondary</item>
```

cc @Guardiola31337

**Comment by JunDai** [comment]
in `1.0`, if you want to change the background color of the bottom subStepLayout, you can change this attr. This attr also change the background of turnLaneLayout and the instructionListView.
```xml
        <!-- Alternate background color for the dropdown list of upcoming steps -->
        <item name="instructionListViewBackgroundColor">
            @color/navigation_instruction_list_view_background
        </item>
```
