### ISSUE TITLE
Unable to resolve dependency for ':carbon@debug/compileClasspath': Could not resolve com.mapbox.maps:android:10.0.0-alpha.5.

### ISSUE THREAD

**Issue by KayHung** [mapbox/mapbox-navigation-android#3427]
Hi, I download mapbox-navigation-android-release_core_1.0.0-rc.1 and follow the README.md file.
But I still get some error.

Unable to resolve dependency for ':carbon@debug/compileClasspath': Could not resolve com.mapbox.maps:android:10.0.0-alpha.5
Unable to resolve dependency for ':carbon@debug/compileClasspath': Could not resolve com.mapbox.plugin:maps-style:10.0.0-alpha.5
Unable to resolve dependency for ':carbon@debug/compileClasspath': Could not resolve com.mapbox.plugin:maps-gesture:10.0.0-alpha.5
Unable to resolve dependency for ':carbon@debug/compileClasspath': Could not resolve com.mapbox.plugin:maps-compass:10.0.0-alpha.5
Unable to resolve dependency for ':carbon@debug/compileClasspath': Could not resolve com.mapbox.plugin:maps-logo:10.0.0-alpha.5
Unable to resolve dependency for ':carbon@debug/compileClasspath': Could not resolve com.mapbox.plugin:maps-attribution:10.0.0-alpha.5
Unable to resolve dependency for ':carbon@debugAndroidTest/compileClasspath': Could not resolve com.mapbox.maps:android:10.0.0-alpha.5
Unable to resolve dependency for ':carbon@debugAndroidTest/compileClasspath': Could not resolve com.mapbox.plugin:maps-style:10.0.0-alpha.5
Unable to resolve dependency for ':carbon@debugAndroidTest/compileClasspath': Could not resolve com.mapbox.plugin:maps-gesture:10.0.0-alpha.5
Unable to resolve dependency for ':carbon@debugAndroidTest/compileClasspath': Could not resolve com.mapbox.plugin:maps-compass:10.0.0-alpha.5
Unable to resolve dependency for ':carbon@debugAndroidTest/compileClasspath': Could not resolve com.mapbox.plugin:maps-logo:10.0.0-alpha.5
Unable to resolve dependency for ':carbon@debugAndroidTest/compileClasspath': Could not resolve com.mapbox.plugin:maps-attribution:10.0.0-alpha.5
Unable to resolve dependency for ':carbon@debugUnitTest/compileClasspath': Could not resolve com.mapbox.maps:android:10.0.0-alpha.5
Unable to resolve dependency for ':carbon@debugUnitTest/compileClasspath': Could not resolve com.mapbox.plugin:maps-style:10.0.0-alpha.5
Unable to resolve dependency for ':carbon@debugUnitTest/compileClasspath': Could not resolve com.mapbox.plugin:maps-gesture:10.0.0-alpha.5
Unable to resolve dependency for ':carbon@debugUnitTest/compileClasspath': Could not resolve com.mapbox.plugin:maps-compass:10.0.0-alpha.5
Unable to resolve dependency for ':carbon@debugUnitTest/compileClasspath': Could not resolve com.mapbox.plugin:maps-logo:10.0.0-alpha.5
Unable to resolve dependency for ':carbon@debugUnitTest/compileClasspath': Could not resolve com.mapbox.plugin:maps-attribution:10.0.0-alpha.5
Unable to resolve dependency for ':examples@debug/compileClasspath': Could not resolve com.squareup.okhttp3:okhttp:{strictly 3.12.10}
Unable to resolve dependency for ':examples@debug/compileClasspath': Could not resolve com.mapbox.navigator:mapbox-navigation-native:12.0.3
Unable to resolve dependency for ':examples@debug/compileClasspath': Could not resolve com.squareup.okhttp3:okhttp:3.12.0
Unable to resolve dependency for ':examples@debug/compileClasspath': Could not resolve com.squareup.okhttp3:okhttp:3.14.4
Unable to resolve dependency for ':examples@debug/compileClasspath': Could not resolve com.squareup.okhttp3:okhttp:3.12.10
Unable to resolve dependency for ':examples@debugAndroidTest/compileClasspath': Could not resolve com.squareup.okhttp3:okhttp:{strictly 3.12.10}
Unable to resolve dependency for ':examples@debugAndroidTest/compileClasspath': Could not resolve com.mapbox.navigator:mapbox-navigation-native:12.0.3
Unable to resolve dependency for ':examples@debugAndroidTest/compileClasspath': Could not resolve com.squareup.okhttp3:okhttp:3.12.0
Unable to resolve dependency for ':examples@debugAndroidTest/compileClasspath': Could not resolve com.squareup.okhttp3:okhttp:3.14.4
Unable to resolve dependency for ':examples@debugAndroidTest/compileClasspath': Could not resolve com.squareup.okhttp3:okhttp:3.12.10
Unable to resolve dependency for ':examples@debugUnitTest/compileClasspath': Could not resolve com.squareup.okhttp3:okhttp:{strictly 3.12.10}
Unable to resolve dependency for ':examples@debugUnitTest/compileClasspath': Could not resolve com.mapbox.navigator:mapbox-navigation-native:12.0.3
Unable to resolve dependency for ':examples@debugUnitTest/compileClasspath': Could not resolve com.squareup.okhttp3:okhttp:3.12.0
Unable to resolve dependency for ':examples@debugUnitTest/compileClasspath': Could not resolve com.squareup.okhttp3:okhttp:3.14.4
Unable to resolve dependency for ':examples@debugUnitTest/compileClasspath': Could not resolve com.squareup.okhttp3:okhttp:3.12.10
Unable to resolve dependency for ':libandroid-navigation@debug/compileClasspath': Could not resolve com.mapbox.navigator:mapbox-navigation-native:12.0.3
Unable to resolve dependency for ':libandroid-navigation@debugAndroidTest/compileClasspath': Could not resolve com.mapbox.navigator:mapbox-navigation-native:12.0.3
Unable to resolve dependency for ':libandroid-navigation@debugUnitTest/compileClasspath': Could not resolve com.mapbox.navigator:mapbox-navigation-native:12.0.3
Unable to resolve dependency for ':libdirections-onboard@debug/compileClasspath': Could not resolve com.mapbox.navigator:mapbox-navigation-native:12.0.3
Unable to resolve dependency for ':libdirections-onboard@debugAndroidTest/compileClasspath': Could not resolve com.mapbox.navigator:mapbox-navigation-native:12.0.3
Unable to resolve dependency for ':libdirections-onboard@debugUnitTest/compileClasspath': Could not resolve com.mapbox.navigator:mapbox-navigation-native:12.0.3
Unable to resolve dependency for ':libnavigation-core@debug/compileClasspath': Could not resolve com.mapbox.navigator:mapbox-navigation-native:12.0.3
Unable to resolve dependency for ':libnavigation-core@debugAndroidTest/compileClasspath': Could not resolve com.mapbox.navigator:mapbox-navigation-native:12.0.3
Unable to resolve dependency for ':libnavigation-core@debugUnitTest/compileClasspath': Could not resolve com.mapbox.navigator:mapbox-navigation-native:12.0.3
Unable to resolve dependency for ':libnavigator@debug/compileClasspath': Could not resolve com.mapbox.navigator:mapbox-navigation-native:12.0.3
Unable to resolve dependency for ':libnavigator@debugAndroidTest/compileClasspath': Could not resolve com.mapbox.navigator:mapbox-navigation-native:12.0.3
Unable to resolve dependency for ':libnavigator@debugUnitTest/compileClasspath': Could not resolve com.mapbox.navigator:mapbox-navigation-native:12.0.3
Unable to resolve dependency for ':libnavui-maps@debug/compileClasspath': Could not resolve com.mapbox.maps:android:10.0.0-alpha.5
Unable to resolve dependency for ':libnavui-maps@debug/compileClasspath': Could not resolve com.mapbox.plugin:maps-style:10.0.0-alpha.5
Unable to resolve dependency for ':libnavui-maps@debug/compileClasspath': Could not resolve com.mapbox.plugin:maps-gesture:10.0.0-alpha.5
Unable to resolve dependency for ':libnavui-maps@debug/compileClasspath': Could not resolve com.mapbox.plugin:maps-compass:10.0.0-alpha.5
Unable to resolve dependency for ':libnavui-maps@debug/compileClasspath': Could not resolve com.mapbox.plugin:maps-logo:10.0.0-alpha.5
Unable to resolve dependency for ':libnavui-maps@debug/compileClasspath': Could not resolve com.mapbox.plugin:maps-attribution:10.0.0-alpha.5
Unable to resolve dependency for ':libnavui-maps@debugAndroidTest/compileClasspath': Could not resolve com.mapbox.maps:android:10.0.0-alpha.5
Unable to resolve dependency for ':libnavui-maps@debugAndroidTest/compileClasspath': Could not resolve com.mapbox.plugin:maps-style:10.0.0-alpha.5
Unable to resolve dependency for ':libnavui-maps@debugAndroidTest/compileClasspath': Could not resolve com.mapbox.plugin:maps-gesture:10.0.0-alpha.5
Unable to resolve dependency for ':libnavui-maps@debugAndroidTest/compileClasspath': Could not resolve com.mapbox.plugin:maps-compass:10.0.0-alpha.5
Unable to resolve dependency for ':libnavui-maps@debugAndroidTest/compileClasspath': Could not resolve com.mapbox.plugin:maps-logo:10.0.0-alpha.5
Unable to resolve dependency for ':libnavui-maps@debugAndroidTest/compileClasspath': Could not resolve com.mapbox.plugin:maps-attribution:10.0.0-alpha.5
Unable to resolve dependency for ':libnavui-maps@debugUnitTest/compileClasspath': Could not resolve com.mapbox.maps:android:10.0.0-alpha.5
Unable to resolve dependency for ':libnavui-maps@debugUnitTest/compileClasspath': Could not resolve com.mapbox.plugin:maps-style:10.0.0-alpha.5
Unable to resolve dependency for ':libnavui-maps@debugUnitTest/compileClasspath': Could not resolve com.mapbox.plugin:maps-gesture:10.0.0-alpha.5
Unable to resolve dependency for ':libnavui-maps@debugUnitTest/compileClasspath': Could not resolve com.mapbox.plugin:maps-compass:10.0.0-alpha.5
Unable to resolve dependency for ':libnavui-maps@debugUnitTest/compileClasspath': Could not resolve com.mapbox.plugin:maps-logo:10.0.0-alpha.5
Unable to resolve dependency for ':libnavui-maps@debugUnitTest/compileClasspath': Could not resolve com.mapbox.plugin:maps-attribution:10.0.0-alpha.5

**Comment by LukasPaczos** [comment]
Hey @KayHung! Unfortunately, recent tags do not support building from source out-of-the-box. That said, we've _just_ resolved this in https://github.com/mapbox/mapbox-navigation-android/issues/3349 and https://github.com/mapbox/mapbox-navigation-android/pull/3370 so feel free to give `master` a shot.
