### ISSUE TITLE
ReplayHistoryActivity doesn't end the session when clicking on the back button

### ISSUE THREAD

**Issue by Guardiola31337** [mapbox/mapbox-navigation-android#3430]
`ReplayHistoryActivity` doesn't end the session when clicking on the back button - it needs to be explicitly stopped from the notification. It's inconsistent sometimes session is closed properly. Seems that we're leaking something in that example and the session is still active even if the `Activity` is `destroy`ed.

cc @kmadsen

**Comment by kmadsen** [comment]
🤔  is there an issue with `onDestroy`?

https://github.com/mapbox/mapbox-navigation-android/blob/c1dec92857469c8eb32a02fd1d1af5f0bdfaf641/examples/src/main/java/com/mapbox/navigation/examples/core/ReplayHistoryActivity.kt#L288
