### ISSUE TITLE
Mock Location Engine not informing Arrival Milestone

### ISSUE THREAD

**Issue by Snipedown** [mapbox/mapbox-navigation-android#345]
I'm not sure if this is important or if I am doing something wrong, but when I use the MockLocationEngine, when the puck reaches the destination it just sits there and never calls Arrival. However, if I change the arrival trigger in the DefaultMilestones to a large value, such as 

Trigger.lte(TriggerProperty.STEP_DISTANCE_REMAINING_METERS, 80)

it triggers the arrival milestone event. Is it possible I am doing something wrong, or does it have to do with the accuracy of the MockLocationEngine.

Thank you.

**Comment by cammace** [comment]
Are you using the default arrival Milestone with to unmodified settings? Could just be an issue with our mock location engine not actually completing to the last point (arrival) which causes it to not trigger.

**Comment by Snipedown** [comment]
@cammace 

Currently I am using the default milestones and not adding any of my own. I just figured I'd bring it up, but if it's not a major deal you can mark this as closed since increasing the trigger property works for me.

Thank you!

**Comment by danesfeder** [comment]
The default milestones have been removed from the core navigation logic.  

You can use the `LegStep` maneuver type to detect this if needed:
```
routeProgress.currentLegProgress().currentStep().maneuver().type().contains("arrive");
```
