### ISSUE TITLE
The Feedback "Road Closure" icon shows weird on particular device

### ISSUE THREAD

**Issue by JunDai** [mapbox/mapbox-navigation-android#3454]
**Android API:** Nexus 5 OS 6.0.1
**Mapbox Navigation SDK version:** 1.0

### Expected behavior
![image](https://user-images.githubusercontent.com/3918950/90539403-9d30ee00-e134-11ea-8561-7b7611cc8134.png)

### Actual behavior
![Screenshot_20200817-095101](https://user-images.githubusercontent.com/3918950/90537395-21ce3d00-e132-11ea-9abf-e8cae7330255.png)

**Comment by JunDai** [comment]
There is a **-** sign in the `Road Closure` icon, but on Nexus 5 with API 23, it doesn't show up.

**Comment by map-angela** [comment]
[Feedback_Icons.zip](https://github.com/mapbox/mapbox-navigation-android/files/5092086/Feedback_Icons.zip)
New set of feedback icons

**Comment by JunDai** [comment]
@LukasPaczos - we update the Feedback icons when fixing this issue. This is how the latest icons look like:
![image](https://user-images.githubusercontent.com/3918950/90664970-3c6ee780-e200-11ea-8609-b8eb1c6dd24d.png)

cc: @mapbox/1tap-android
