### ISSUE TITLE
Pause re-routes during arrival

### ISSUE THREAD

**Issue by kmadsen** [mapbox/mapbox-navigation-android#3455]
".., and after the Arrival at Waypoint is triggered, pause the off route detection (and stop the reroute) and pause updating route progress, until the navigateNextRouteLeg is called."

Our [RerouteController](https://github.com/mapbox/mapbox-navigation-android/blob/9c4759302f9a8271f9c78080471a38e9d43bdc4e/libnavigation-core/src/main/java/com/mapbox/navigation/core/reroute/RerouteController.kt#L31) provides a mechanism to interrupt a reroute. But what we will really need is a way to disable/enable reroutes.

@RingerJK @LukasPaczos @Guardiola31337

**Comment by RingerJK** [comment]
Do we need it to prevent off route detection when we have multiple waypoints?

**Comment by LukasPaczos** [comment]
Shouldn't this logic be handled by nav native and prevent reroutes when we're approaching/overshoot the destination a little bit until we switch the leg?

/cc @mskurydin @SiarheiFedartsou

**Comment by Guardiola31337** [comment]
If you have arrived NN should not send `OFF_ROUTE` anymore - currently NN should spam `COMPLETE` until a new route is set or reset it. If that's not the case seems an issue in NN. Noting also that we have issues with NN and the multiple waypoints use-case.

**Comment by kmadsen** [comment]
> Shouldn't this logic be handled by nav native and prevent reroutes when we're approaching/overshoot the destination a little bit until we switch the leg?
> If you have arrived NN should not send OFF_ROUTE anymore - currently NN should spam COMPLETE until a new route is set or reset it. If that's not the case seems an issue in NN. Noting also that we have issues with NN and the multiple waypoints use-case.

but it's the SDK that is requesting new routes when going off route. What if we added the ability to pause new route from being requested, even when going off route. We have the ability to interrupt reroutes, I'm not sure when anyone will actually need that.

**Comment by tkvalentine56** [comment]
Have upgraded to:

        implementation 'com.mapbox.navigation:ui:1.0.0-rc.6' // for Nav Core and UI SDKs
        implementation 'com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v9:0.8.0'

I am still experiencing the same route issues as described previously.
Also I believe this is closely related to, if not the same issue as reported in #3345 and #3298. #3345 accurately describes the issue that I am seeing repeated here.

The following file link is the Mapbox history output representing the reroute/off route/invalid route performance during a road test.

[MAPBOX_HISTORY.txt](https://github.com/mapbox/mapbox-navigation-android/files/5137849/MAPBOX_HISTORY.txt)

**Comment by Guardiola31337** [comment]
Is this still relevant @kmadsen?

**Comment by tkvalentine56** [comment]
Yes. Please refer to Sean OLeary for discussion about this issue with our dev team.

**Comment by kmadsen** [comment]
Yeah thanks for keeping it open, we haven't resolved this issue. It seems the solution could come from native or sdk.

But it seems we also want to [introduce an SDK api](https://github.com/mapbox/mapbox-navigation-android/blob/7f56d62164c226b1da499f99972a0e0c5c168030/libnavigation-core/src/main/java/com/mapbox/navigation/core/reroute/RerouteController.kt#L12), to be able to manually disable re-routes.

**Comment by kmadsen** [comment]
Commenting cause this is still relevant. Will add "needs estimate". It's possible should be sent to nav-native as per this comment https://github.com/mapbox/mapbox-navigation-android/issues/3455#issuecomment-676077367

**Comment by LukasPaczos** [comment]
Closing as the arrival experience was aligned with what Nav Native produces.
