### ISSUE TITLE
Unsure how to check whether instructions view is open/maximized or not - Missing or undocumented?

### ISSUE THREAD

**Issue by carstenhag** [mapbox/mapbox-navigation-android#3465]
**Android API:** 10
**Mapbox Navigation SDK version:** 1.0.0 rc/snapshot

    implementation 'com.mapbox.navigation:ui-v1:1.0.0-SNAPSHOT'
    implementation 'com.mapbox.navigation:core:1.0.0-rc.4'

### Steps to trigger behavior

 1. Embed MapboxMap in activity, start routing etc
 2. Tap on instructions banner
 3. Press hardware key button - activity is being closed. I would like to handle this on `onBackPressed`, but I need a getter on whether the instructions view is fullscreen shown or not.

### Expected behavior

There is a documented property/getter on whether the instructions view is shown (in fullscreen) or not. There probably is one, but I couldn't find it :D 

### Actual behavior

I can't find it inside MapView.java, MapboxNavigation.kt etc. Also I couldn't find it on https://docs.mapbox.com/android/beta/navigation/overview/manuever-instructions/.

**Comment by carstenhag** [comment]
Woops I found something, haven't tested it yet though. Would be nice if this were documented. 

```kt
       if (navigation_instructions_view.isShowingInstructionList) {
            navigation_instructions_view.handleBackPressed()
            return
        }
```

**Comment by LukasPaczos** [comment]
Hey @carstenhag, just `navigation_instructions_view.handleBackPressed()` should be enough as we're checking the visibility state internally as well.

We've also just added the docs to this method, it will be available in the next release:
https://github.com/mapbox/mapbox-navigation-android/blob/ed873e9e5538568b84d802edb48f7c9d3fef53c1/libnavigation-ui/src/main/java/com/mapbox/navigation/ui/instruction/InstructionView.java#L385-L391

Feel free to close the issue if the method is working as expected in your scenario.

**Comment by carstenhag** [comment]
Thanks for documenting it. I had to use this way in order not to call `super.onBackPressed()`.

```kt
    override fun onBackPressed() {
        if (navigation_instructions_view.isShowingInstructionList) {
            navigation_instructions_view.handleBackPressed()
            return
        }
        mapboxNavigation.stopTripSession()
        super.onBackPressed()
    }
```
