### ISSUE TITLE
InstructionView list/views not shown when maximized - Missing route update/setup?

### ISSUE THREAD

**Issue by carstenhag** [mapbox/mapbox-navigation-android#3466]
**Android API:** 29 / Android 10
**Mapbox Navigation SDK version:** 
`implementation 'com.mapbox.navigation:ui-v1:1.0.0-SNAPSHOT'`
`implementation 'com.mapbox.navigation:core:1.0.0-rc.4'`

### Steps to trigger behavior

 1. Setup Activity with MapView and InstructionView. Start navigation etc.
 2. Tap on minimized instruction view
 3. Instruction view opens/maximizes, but there's nothing in there

### Expected behavior

All relevant, upcoming instructions should be there.

### Actual behavior

Nothing is in the list except for the current instruction :D. Maybe my colleague and I didn't set up the view properly or forgot to register something? Used code is below.

![Bildschirmfoto 2020-08-19 um 15 18 42](https://user-images.githubusercontent.com/3776997/90640338-26791b00-e230-11ea-95ab-5f7c04e4946a.png)
![Bildschirmfoto 2020-08-19 um 15 19 52](https://user-images.githubusercontent.com/3776997/90640350-28db7500-e230-11ea-8a48-cc38fd3e2fd2.png)

```xml
    <com.mapbox.navigation.ui.instruction.InstructionView
        android:id="@+id/navigation_instructions_view"
        style="@style/mapbox_instruction"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toTopOf="parent"
        tools:background="@color/primary"
        tools:layout_height="150dp" />
```

```kt
  // MapboxNavigationActivity.kt

    private val routeProgressObserver = object : RouteProgressObserver {
        override fun onRouteProgressChanged(routeProgress: RouteProgress) {
            updateNavigationInfo(routeProgress)
            navigation_instructions_view.updateBannerInstructionsWith(routeProgress.bannerInstructions)
        }
    }

  // Also retrieving the feedback and sound buttons, but not doing anything else with it
```

**Comment by JunDai** [comment]
@carstenhag - hi, thanks for reaching out to us.

qq: are you able to reproduce this issue all the time? What's your implementation of the method `updateNavigationInfo(routeProgress)`? Do you also register the `bannerInstructionObserver`?

please refer to our [`InstructionViewActivity`](https://github.com/mapbox/mapbox-navigation-android/blob/master/examples/src/main/java/com/mapbox/navigation/examples/core/InstructionViewActivity.kt#L409-L419) example for how to integrate the `InstructionView` component.

```kotlin
    private val routeProgressObserver = object : RouteProgressObserver {
        override fun onRouteProgressChanged(routeProgress: RouteProgress) {
            instructionView.updateDistanceWith(routeProgress)
        }
    }

    private val bannerInstructionObserver = object : BannerInstructionsObserver {
        override fun onNewBannerInstructions(bannerInstructions: BannerInstructions) {
            instructionView.updateBannerInstructionsWith(bannerInstructions)
        }
    }
```

**Comment by carstenhag** [comment]
Thanks, I have had a look there, integrated a `bannerInstructionsObserver`, but it still shows up as empty.

```kt

    private val bannerInstructionsObserver = object : BannerInstructionsObserver {
        override fun onNewBannerInstructions(bannerInstructions: BannerInstructions) {
            navigation_instructions_view.updateBannerInstructionsWith(bannerInstructions)
        }
    }


//onStop
        mapboxNavigation.unregisterBannerInstructionsObserver(this.bannerInstructionsObserver)

// setup()
        navigation_map_view.getMapAsync {
            mapboxMap = it
            mapboxMap.setStyle(Style.MAPBOX_STREETS) { style ->
                setupMap(style)
                registerListeners()
            }
        }

    registerListeners() {
    // ...
        mapboxNavigation.registerBannerInstructionsObserver(this.bannerInstructionsObserver)
    }
```

```kt
    private fun updateNavigationInfo(routeProgress: RouteProgress) {
        routeProgress.currentLegProgress?.currentStepProgress?.step?.let {
            navigation_current_street.visibility = VISIBLE
            navigation_current_street.text = it.name()
        }
        // our custom navigation details view
        navigation_details_view.setDistance(formattingUtils.formatDistance(routeProgress.distanceRemaining.toInt()))
        navigation_details_view.setDuration(Duration(routeProgress.durationRemaining.toInt()).textShort)
        navigation_details_view.setETA(
            formattingUtils.formatHHmmString(Date(Date().time + (routeProgress.durationRemaining * 1000).toLong()))
        )
    }
```

**Comment by JunDai** [comment]
@carstenhag - do you call `instructionView.updateDistanceWith(routeProgress)` in the **routeProgressObserver**?

```kotlin
    private val routeProgressObserver = object : RouteProgressObserver {
        override fun onRouteProgressChanged(routeProgress: RouteProgress) {
            instructionView.updateDistanceWith(routeProgress)
        }
    }
```

**Comment by carstenhag** [comment]
Thanks, that fixed the issue! I looked into `updateDistanceWith()`'s documentation, and it says this:
```kt
  /**
   * Use this method inside a {@link RouteProgressObserver} to update this view.
   * <p>
   * This includes the distance remaining, instruction list, turn lanes, and next step information.
   *
   * @param routeProgress for route data used to populate the views
   */
```

In my opinion the method name does not really correspond to the documentation. It was quite unexpected for me that it also updates the instruction list etc (being called `updateDistance`). I thought that `updateBannerInstructionsWith` would be for just that.

**Comment by JunDai** [comment]
> In my opinion the method name does not really correspond to the documentation.

thanks for the feedback. We might revisit this in future.
