### ISSUE TITLE
Dokka 1.4.0

### ISSUE THREAD

**Issue by RingerJK** [mapbox/mapbox-navigation-android#3501]
[Dokka 1.4.0-rc has been released ](https://github.com/Kotlin/dokka/releases/tag/v1.4.0-rc). There're a few amazing things that aren't presented at previous version like _multi-modules support_, _search bar_ and _navigation tree_. You could see more at [the post](https://blog.jetbrains.com/kotlin/2020/08/dokka-preview-based-on-kotlin-1-4-0-rc/).

- [x] Remove documentation free modules(which has internal usage classes only) from api-refs page: `libtrip-notification`, `libnavigation-router` and `libnavigator` https://github.com/mapbox/mapbox-navigation-android/pull/3890

Require (re)create docs for following versions: 
- [x] 1.0.0 https://github.com/mapbox/mapbox-navigation-android/pull/4002;
- [x] 1.0.1 https://github.com/mapbox/mapbox-navigation-android/pull/4016;
- [x] 1.1.0 https://github.com/mapbox/mapbox-navigation-android/pull/4019;
- [x] 1.1.1 https://github.com/mapbox/mapbox-navigation-android/pull/4018;
- [x] 1.1.2 https://github.com/mapbox/mapbox-navigation-android/pull/4017;
- [x] 1.2.0 https://github.com/mapbox/mapbox-navigation-android/pull/4021;
- [x] 1.2.1 https://github.com/mapbox/mapbox-navigation-android/pull/4020;
- [x] 1.3.0 https://github.com/mapbox/mapbox-navigation-android/pull/4022;
- [x] 1.4.0 https://github.com/mapbox/mapbox-navigation-android/pull/4023;
~- [ ] 1.5.0-alpha.1 https://github.com/mapbox/mapbox-navigation-android/pull/4024;~ (legacy)
- [x] 1.5.0-alpha.2 https://github.com/mapbox/mapbox-navigation-android/pull/4049
~- [ ] 2.0.0-alpha.9 https://github.com/mapbox/mapbox-navigation-android/pull/4026;~ (legacy)
- [x] 2.0.0-alpha.10 https://github.com/mapbox/mapbox-navigation-android/pull/4039

**сс** @colleenmcginnis @mapbox/navigation-android

**Comment by RingerJK** [comment]
Caught from standup discussion: 
We're gonna make only one link to Navigation SDK API Documentation and not separate it on `UI` and `Others`(Core) like [it's making now](https://docs.mapbox.com/android/navigation/api-reference/) when we have 2 links for one version: `navigation` and `navigation-ui`. 

Pull request #3757

**cc** @asinghal22 @LukasPaczos

**Comment by asinghal22** [comment]
Yes - we don't want to separate UI and Core as two sdks. It should be a single Navigation SDK.

**Comment by RingerJK** [comment]
I'm gonna recreate [all api-docs](https://docs.mapbox.com/android/navigation/api-reference/ )starting with `1.0` based on **Dokka 1.4**

#### What we get in that case:
- the same style for all docs starting with 1.0;
- now docs separated by ui and non-ui which is not [what we want](https://github.com/mapbox/mapbox-navigation-android/issues/3501#issuecomment-728279060), so it would be easier to re-create docs with new version of dokka(supports multi-module out of the box) than re-setup legacy one;

#### What we need from docs-team:
For dokka generated docs: provide a way how to replace logo, change style to mapbox', and add header like `Navigation SDK for Android Reference (**VERSION**)`
- change API-reference page https://docs.mapbox.com/android/navigation/api-reference/ according [requirements](https://github.com/mapbox/mapbox-navigation-android/issues/3501#issuecomment-728279060): `Navigation SDK` is a single SDK, it shouldn't be separated on `UI` and `Core`

**cc** @danswick

**Comment by RingerJK** [comment]
Dokka creates multi-module docs, with entry file `-modules.html`(how it looks https://github.com/mapbox/mapbox-navigation-android/pull/3908). Can we stay with it as is or have to rename `-modules.html` -> `index.html`(as with the version of the previous docs)? If we need renaming it means we must handle internal links that actually link to `-modules.html`

/cc @danswick

**Comment by RingerJK** [comment]
> Dokka creates multi-module docs, with entry file `-modules.html`(how it looks #3908). Can we stay with it as is or have to rename `-modules.html` -> `index.html`(as with the version of the previous docs)? If we need renaming it means we must handle internal links that actually link to `-modules.html`
> 
> /cc @danswick

**Comment by RingerJK** [comment]
@colleenmcginnis all docs are landed 🎉 we should be good to migrate to new docs for `v1.0+`

**Comment by colleenmcginnis** [comment]
🎉  Thanks @RingerJK! I'll jump over the android-docs PR to double-check that all our links are good. 👍

**Comment by colleenmcginnis** [comment]
@RingerJK this should be all set! https://docs.mapbox.com/android/navigation/api-reference/ Let me know if you see any issues.
