### ISSUE TITLE
NavigationMapRoute now nullable, but it's unclear when and why it may be null

### ISSUE THREAD

**Issue by carstenhag** [mapbox/mapbox-navigation-android#3503]
**Mapbox Navigation SDK version:**
Before:
```
    implementation 'com.mapbox.navigation:ui-v1:1.0.0-SNAPSHOT'
    implementation 'com.mapbox.navigation:core:1.0.0-rc.4'
```
```kotlin
    private lateinit var navigationMapRoute: NavigationMapRoute

    navigationMapRoute = NavigationMapRoute
                .Builder(navigation_map_view, mapboxMap, this)
                .withStyle(R.style.mapbox_route)
                .build()
```

After:

```
    implementation 'com.mapbox.navigation:ui:1.0.0-rc.6'
    implementation 'com.mapbox.navigation:core:1.0.0-rc.6'
```

### Steps to trigger behavior

 1. Update to rc.6
 2. See error that `NavigationMapRoute?` is now returned, because `NavigationMapRoute.Builder.build()` is now marked as `@Nullable`.
 3. Try to find infos on how to handle the null case, but neither the class nor the `build()` documentations say anything about it.

### Expected behavior
Documentation is updated

### Actual behavior
Documentation is not updated

**Comment by Guardiola31337** [comment]
This is a great catch and a regression from https://github.com/mapbox/mapbox-navigation-android/pull/3436/commits/b884b5c0081dc39eb7625b2b6b2ac42963536653

We noticed some missing annotations when using the `Infer Nullity` tool https://github.com/mapbox/mapbox-navigation-android/pull/3436#discussion_r471558040 but we thought that the tool was working fine and it seems is not. Tested locally and it's inferring `@Nullable` for `NavigationMapRoute.Builder#build` which is wrong. Wondering why though 🤔 

Will keep investigating and report back here.

Thanks for reporting @carstenhag 🙇‍♂️ 

cc @LukasPaczos
