### ISSUE TITLE
InstructionView: onInstructionListVisibilityChanged inside showInstructionList is invoked too early 

### ISSUE THREAD

**Issue by P-Zenker** [mapbox/mapbox-navigation-android#3505]
**Android API: 29**
**Mapbox Navigation SDK version: 0.42.6**

I don't want the user to see the instructionListLayout.

### Steps to trigger behavior
 1. Navigation UI inside of a Fragment
 2. Add listener to hide the view (kotlin code)
```
instructionView.setInstructionListListener {
    if (it) {
    	instructionView.hideInstructionList()
    }
}
```
 3. Click on the InstructionView 

### Expected behavior
onInstructionListVisibilityChanged is called after the list view is set to visible

### Actual behavior
The listener is triggered a the beginning:
```
public void showInstructionList() {
    onInstructionListVisibilityChanged(true); // <----- Too early
    instructionLayout.requestFocus();
    beginDelayedListTransition();
    if (isLandscape()) {
      updateLandscapeConstraintsTo(R.layout.instruction_layout_alt);
    }
    instructionListLayout.setVisibility(VISIBLE);
  }
```

So I currently have to use a delay like this...
```
instructionView.setInstructionListListener {
    if (it) {
        instructionView.postDelayed({
            instructionView.hideInstructionList()
        }, 100)
    }
}
```

### Solution
onInstructionListVisibilityChanged should be called at the end of showInstructionList() (similar like in hideInstructionList())

**Comment by Guardiola31337** [comment]
@abhishek1508 could you check if this is an issue in `1.0`?

**Comment by Guardiola31337** [comment]
cc'ing @JunDai as you've been recently working on the instructions list.

**Comment by JunDai** [comment]
> cc'ing @JunDai as you've been recently working on the instructions list.

I am working on a fix of it.
