### ISSUE TITLE
Create no-op dependency to decrease app size (if mapbox not needed for specific brand)

### ISSUE THREAD

**Issue by carstenhag** [mapbox/mapbox-navigation-android#3517]
**Android API:** 10
**Mapbox Navigation SDK version:** 1.0.0-rc.6

### Steps to trigger behavior

 1. Include mixpanel dependency for all brands (currently not possible to only include it for 1 brand)
 2. All other brands now also contain the big mixpanel binaries

### Expected behavior
There's a noop library

### Actual behavior
There isn't any :D I could do this stuff all on my own, and this is how I did it for AppCenter and Instabug (following https://medium.com/@orhanobut/no-op-versions-for-dev-tools-b0a865934398), but for those I only had to create 2-3 classes. For Mapbox I would need to create tons of classes and likely also resources.

**Comment by carstenhag** [comment]
Also useful for when you include Mapbox as an option for AppCenter/testing builds but don't want to include it for production/release builds yet.

**Comment by Guardiola31337** [comment]
Hey @carstenhag thanks for reaching out 👋 

Could you explain in detail what you're trying to do? `no-op` flavors of libraries are normally exposed in development tools that help debugging (like LeakCanary and Stetho mentioned in the article). That's not the case for the Navigation SDK. What's your use-case? Why would you need that? Could you clarify?

**Comment by carstenhag** [comment]
Sure, can do. So we have one app codebase that has a GoogleMap (shame on us) and we use that for all 6 current brands of the app that we have.

As we are expanding our usecases and features, we are integrating the Mapbox SDKs (mainly Navigation) into the codebase. Currently we are mainly developing this new navigation usecase for one brand (so one customer). The other brands don't have the feature enabled and currently those brand's app consume larger app sizes even though it's not really needed for those.

It will still take more than a year for the other brands to get this feature, as it highly depends on external dependencies. If you still have a question, please ask :)

**Comment by Guardiola31337** [comment]
Thanks for clarifying @carstenhag

It seems from what I can tell that this is something that should be handled from the app side i.e. not an issue per se from the SDK. While providing a `no-op` flavor of the SDK would solve your issue we don't think is needed as the SDK is not a development tool.

BTW can't you control what dependencies you include / exclude from the build variants Gradle config? Just a suggestion but I think that'd solve your issue. See https://developer.android.com/studio/build/build-variants

Going ahead and closing here as answered and workaround suggested.

**Comment by carstenhag** [comment]
Yeah, I could include mapbox only for one specific brand. As the codebase references mapbox classes, it would fail to compile other brands, so it's not really viable.

Maybe this could be handled better with a separate module, but I'm not experienced with that yet. I understand you closing this, as it's probably not a wide-spread use case.

**Comment by Guardiola31337** [comment]
> Yeah, I could include mapbox only for one specific brand. As the codebase references mapbox classes, it would fail to compile other brands, so it's not really viable.

Don't know how your build variants config looks like but probably you can workaround it not including Mapbox dependencies in the main / common module. In any case, I'm curious, how's the `no-op` flavor of the SDK going to help you? If you'd include both as part of a brand module classes could also potentially clash, right? Sorry, I don't still see what's the SDK use case here.

**Comment by Guardiola31337** [comment]
I know the ultimate goal but as above-mentioned I wouldn't approach it this way. This could work for libraries that have a couple of classes as you're wrapping them in a separate module and re-implementing their functions as no-ops. For SDKs that'd be insane 😅 

In any case, the purpose of the libraries is different. AppCenter or Instabug are development tools that you may want to disable for some build types but that's not the case of the Navigation SDK as it's meant to be used in both debug / release builds.
