### ISSUE TITLE
Crash with NavigationMapRoute.addTraffic

### ISSUE THREAD

**Issue by davols** [mapbox/mapbox-navigation-android#353]
Noticed a crash in crashlytics.
We're running a version we are compiling ourselves. But checking `master` no changes from our branch and this repos master there are no changes between the two files (our `NavigationMapRoute.java` and the one in master here. 

```
Fatal Exception: java.lang.IndexOutOfBoundsException: Invalid index 1121, size is 1121
       at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
       at java.util.ArrayList.get(ArrayList.java:308)
       at com.mapbox.services.android.navigation.ui.v5.route.NavigationMapRoute.addTrafficToSource(SourceFile:2331)
```
Assuming it's proguard that messes with the linenumbers. Assuming it's
`   double[] endCoord = lineString.getCoordinates().get(i + 1).getCoordinates();` over at 
https://github.com/mapbox/mapbox-navigation-android/blob/master/libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/route/NavigationMapRoute.java#L331 which is the culprit.

As it's from crashlytics I have no clue on how to reproduce it. 

Edit: Got it at the office using `0.7.0-SNAPSHOT` as well.

**Comment by danesfeder** [comment]
Thanks @davols, we will look into this

@cammace Do you think https://github.com/mapbox/mapbox-navigation-android/blob/master/libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/route/NavigationMapRoute.java#L331 should be `(i - 1)` instead?

**Comment by ericrwolfe** [comment]
@bsudekum wasn't there a similar crash on iOS that was fixed?

**Comment by ericrwolfe** [comment]
@danesfeder here's the iOS guard that worked around this crash: https://github.com/mapbox/mapbox-navigation-ios/pull/696

Seems like a potential bug upstream in the directions API, but we should still guard against it.

**Comment by cammace** [comment]
The fix for this is in https://github.com/mapbox/mapbox-navigation-android/pull/384 and will be in the 0.6.3 release. Closing.
