### ISSUE TITLE
Offline TTS mixing up device language with english

### ISSUE THREAD

**Issue by carstenhag** [mapbox/mapbox-navigation-android#3574]
**Android API:** Samsung A70 and OnePlus 5 with both Android 10.
**Mapbox Navigation SDK version:**
```
    implementation 'com.mapbox.navigation:ui:1.0.0-rc.7'
    implementation 'com.mapbox.navigation:core:1.1.0-alpha.4' 
```
Using the 1.1.0 alpha due to #3554. I can't test previous versions of the SDK, as it crashes below that 😄 .

### Steps to trigger behavior

 1. Set device language to German (Germany) aka de-rDE. Both devices have 10-20 languages set, but de-rDE is at the 1st spot on both.
 2. Turn off Wifi, Mobile Data or any other internet connection
 3. Start navigation

### Expected behavior
Similar as with Online TTS, the Offline TTS should use the device language, in this case german, to provide instructions.

### Actual behavior
The Offline TTS' output is a mix between english and german. My guess: It has english texts but the voice is german. It sounds terrible :D. This occurs on both phones in similar ways. As you can hear though, the TTS engines are different.

Video/Sound about this bug at the
* OnePlus 5: https://youtu.be/fx8AIMumL3U
* Samsung A70: https://www.youtube.com/watch?v=HpfM3YfvaV8

**Comment by Guardiola31337** [comment]
Hey @carstenhag thanks for reaching out and report your issue.

Could you share your request setup / `RouteOptions` you're adding and the `DirectionsRoute` that you get / use when you have a chance? I can't tell any differences from the videos you shared (need to improve my German skills) 😅 

cc @JunDai

**Comment by carstenhag** [comment]
Sure! Route setup:

```kotlin
    private fun requestNavigationRoute() {
        val coordinates = mutableListOf<Point>()

        if (permissionService.isLocationPermissionGranted) {
            LocationEngineProvider.getBestLocationEngine(context).getLastLocation(object : LocationEngineCallback<LocationEngineResult> {
                override fun onSuccess(result: LocationEngineResult?) {
                    val lastLocation = result?.lastLocation
                    if (lastLocation != null) {
                        origin = Point.fromLngLat(lastLocation.longitude, lastLocation.latitude)
                        coordinates.add(origin)
                        coordinates.addAll(waypoints)
                        coordinates.add(destination)
                        currentMapBoxNavigation.requestRoutes(
                            RouteOptions.builder()
                                    .applyDefaultParams()
                                    .accessToken(ResourcesHelper.getString(R.string.mapbox_api_key))
                                    .coordinates(coordinates)
                                    .steps(true)
                                    .voiceInstructions(true)
                                    .bannerInstructions(true)
                                    .profile(DirectionsCriteria.PROFILE_DRIVING)
                                    .build(),
                            routesRequestCallback
                        )
                        return
                    }
                }

                override fun onFailure(exception: Exception) {
                    throw exception
                }
            })
        }
    }
```

---

SpeechPlayerProvider and NavigationSpeechPlayer setup;
```kotlin
        val cache = Cache(context.cacheDir, 1000)
        val voiceInstructionLoader = VoiceInstructionLoader(
            context, ResourcesHelper.getString(R.string.mapbox_api_key),
            cache
        )
        val speechPlayerProvider = SpeechPlayerProvider(
            context,
            ConfigurationCompat.getLocales(Resources.getSystem().configuration).get(0).toString(),
            true,
            voiceInstructionLoader
        )
        navigationSpeechPlayer = NavigationSpeechPlayer(speechPlayerProvider)
```

**Comment by Guardiola31337** [comment]
At a first glance I don't see you're overriding the `language` in the `RouteOptions` 👀 

https://github.com/mapbox/mapbox-java/blob/2733e034f33191a68d273fdd4b6b03fa5186be13/services-directions-models/src/main/java/com/mapbox/api/directions/v5/models/RouteOptions.java#L605-L613

You can also check the `DirectionsRoute` object that is retrieved by `requestRoutes`. Could you share that as well?

**Comment by carstenhag** [comment]
Wow that's way better now, haha. Setting the language option fixed it. 

In retrospect it makes a lot of sense, but for me it was still unexpected.

**Comment by Guardiola31337** [comment]
Thanks for the update and confirming it's fixed 🎉 

Good to close here then @carstenhag?

**Comment by carstenhag** [comment]
Would perhaps be good to document ;). Although this ticket will probably also be useful if Googles this.

**Comment by Guardiola31337** [comment]
Already documented in `RouteOptions` 🚀 

Thanks for checking out the SDK.

Closing here.
