### ISSUE TITLE
Missing required properties: distance duration

### ISSUE THREAD

**Issue by felixkrautschuk** [mapbox/mapbox-navigation-android#3583]
**Android API:** 9.4.0
**Mapbox Navigation SDK version:** 1.0.0-rc.8

### Steps to trigger behavior

 1. create default mapbox navigationOptions:
```
val navigationOptions = MapboxNavigation
    .defaultNavigationOptionsBuilder(this, accessToken)
    .build()
```
 2. try to create the MapboxNavigation instance
```
val mapboxNavigation = MapboxNavigation(navigationOptions)
```

### Expected behavior
MapboxNavigation instance should be correctly created.

### Actual behavior
java.lang.IllegalStateException: Missing required properties: distance duration

**Comment by Guardiola31337** [comment]
Hey @felixkrautschuk thanks for reaching out and report your issue.

I've just tested using the `BasicNavigationActivity` from the `examples` test app https://github.com/mapbox/mapbox-navigation-android/blob/7ba1b417e57d34ca3dc3bf4c24ac9c02dfa9aeab/examples/src/main/java/com/mapbox/navigation/examples/core/BasicNavigationActivity.kt#L78-L86 (commenting out `.locationEngine(getLocationEngine())` and the `apply`) and it's working fine 🤔 

Could you add some more information for reproducing the behavior you're describing or any other specifics around your setup? If there is any sample / pseudo code or stacktrace you can provide, that would be really helpful and it'll give us better insight into your implementation and what could be causing your problem.

**Comment by Guardiola31337** [comment]
Especially @felixkrautschuk could you share how you're building the `RouteOptions` needed for `MapboxNavigation#requestRoutes`?

**Comment by felixkrautschuk** [comment]
Hey @Guardiola31337 thank you for your quick response!

Unfortunately I cannot share any sample projects, as I am not developing a native Android app, but I try to integrate the Mapbox Navigation lib into our NativeScript project for Android and iOS and for Android it just worked fine for the version _mapbox-android-navigation-ui:0.42.6_ (we did not start yet with iOS), so it may not be a fundamental problem using this sdk in a NativeScript app.

Actually I am already stuck at the beginning, I only tried to follow this step of the docs:
https://docs.mapbox.com/android/beta/navigation/overview/#create-a-mapboxnavigation-object

So I have not created any route options yet.

**Comment by felixkrautschuk** [comment]
I can create the navigationOptions object. When I log it into the console, it looks like this:
<img width="1733" alt="Bildschirmfoto 2020-09-22 um 16 23 46" src="https://user-images.githubusercontent.com/6443021/93895515-33d26b00-fcf0-11ea-93bd-f91432f001eb.png">

But when I try to create the MapboxNavigation instance I get the error 
java.lang.IllegalStateException: Missing required properties: distance duration

**Comment by felixkrautschuk** [comment]
I faced this (https://github.com/mapbox/mapbox-navigation-android/issues/3293) issue with a similar error message some days ago and with just upgrading the navigation sdk version (no other changes in code) I get the error from this thread.

**Comment by felixkrautschuk** [comment]
@Guardiola31337 I have no idea why, but now it works on my side.

By an happy accident, I removed the _com.mapbox.mapboxsdk:mapbox-sdk-services:5.6.0_ dependency from my gradle config, so I got this:

```
dependencies {
    implementation 'com.mapbox.mapboxsdk:mapbox-android-sdk:9.4.0'

    implementation 'com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v9:0.9.0'

    implementation 'com.mapbox.mapboxsdk:mapbox-android-plugin-offline-v9:0.7.0'

    /* implementation 'com.mapbox.mapboxsdk:mapbox-sdk-services:5.6.0' */

    implementation 'com.mapbox.navigation:core:1.0.0-rc.8'
}
```

And now the MapboxNavigationInstance is created as expected and I can continue to build RouteOptions etc.

**Comment by Guardiola31337** [comment]
Thanks for the update @felixkrautschuk 

Yeah was digging myself here and was going to ask what version of `mapbox-sdk-services` and `mapbox-sdk-directions-models` were you using which BTW you don't need to include explicitly as they're pulled transitively when including `com.mapbox.navigation:core`.

Was also going to ask for more details and if you were dealing with any `DirectionsRoute` related work in parallel as that `IllegalStateException` could only happen when creating a `LegStep` or when using `MapMatchingMatching` as `distance` and `duration` are required fields.

Anyways, glad you figured it out.

Thanks for checking out the SDK!
