### ISSUE TITLE
Navigation session resets when the device is rotated

### ISSUE THREAD

**Issue by ericrwolfe** [mapbox/mapbox-navigation-android#361]
This causes duplicate metrics. We should figure out a way to persist the session state between device rotations.

cc @danesfeder @electrostat

**Comment by danesfeder** [comment]
`MapboxNavigation` will need some sort of cue that we are destroying from a configuration change (i.e. - rotation or theme change).  

Adding `MapboxNavigation#onSaveInstanceState()` would solve this, but would couple `MapboxNavigation` to only classes able to override `onSaveInstanceState()` which isn't great.  I can work out the architecture with @electrostat

**Comment by ericrwolfe** [comment]
Fixed with https://github.com/mapbox/mapbox-navigation-android/pull/540.
