### ISSUE TITLE
Routeline vanishing point incorrectly calculated when restoring from background

### ISSUE THREAD

**Issue by cafesilencio** [mapbox/mapbox-navigation-android#3615]
### Steps to trigger behavior

 1. Draw a route and start navigating with the vanishing route line enabled.
 2. After some time stop navigation.
 3. Draw a new route line.
 4. Put application in background.
 5. Restore app from background.

### Expected behavior
The route line should not display any vanished section since a new line was drawn but there was no navigation progress.

### Actual behavior
There is sometimes a section of the route line vanished.

**Comment by cafesilencio** [comment]
The issue was first noticed here:  https://github.com/mapbox/1tap-android/issues/593#issuecomment-702946893

**Comment by LukasPaczos** [comment]
https://github.com/mapbox/mapbox-navigation-android/pull/3616 landed, are we good to close here?

**Comment by cafesilencio** [comment]
This should have been resolved with https://github.com/mapbox/mapbox-navigation-android/pull/3616
