### ISSUE TITLE
Could not use com.mapbox.navigation:ui:1.0.0

### ISSUE THREAD

**Issue by peytonwupeixin** [mapbox/mapbox-navigation-android#3638]
**Android API:**
**Mapbox Navigation SDK version:com.mapbox.navigation:ui:1.0.0**

### Steps to trigger behavior

 When I update navigation ui to  com.mapbox.navigation:ui:1.0.0.I get the error below:
> Could not resolve all task dependencies for configuration ':app:navigation_demoDebugRuntimeClasspath'.
   > Could not find com.mapbox.navigator:mapbox-navigation-native:14.1.2.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/mapbox/navigator/mapbox-navigation-native/14.1.2/mapbox-navigation-native-14.1.2.pom
       - https://repo.maven.apache.org/maven2/com/mapbox/navigator/mapbox-navigation-native/14.1.2/mapbox-navigation-native-14.1.2.pom
       - https://jcenter.bintray.com/com/mapbox/navigator/mapbox-navigation-native/14.1.2/mapbox-navigation-native-14.1.2.pom
       - https://plugins.gradle.org/m2/com/mapbox/navigator/mapbox-navigation-native/14.1.2/mapbox-navigation-native-14.1.2.pom
       - https://api.mapbox.com/downloads/v2/releases/maven/com/mapbox/navigator/mapbox-navigation-native/14.1.2/mapbox-navigation-native-14.1.2.pom
       - https://api.mapbox.com/downloads/v2/snapshots/maven/com/mapbox/navigator/mapbox-navigation-native/14.1.2/mapbox-navigation-native-14.1.2.pom
     - https://mapbox.bintray.com/mapbox/com/mapbox/navigator/mapbox-navigation-native/14.1.2/mapbox-navigation-native-14.1.2.pom
       
     Required by:
         project :app > project :map_navigation_demo > project :map_navigation > com.mapbox.navigation:ui:1.0.0 > com.mapbox.navigation:core:1.0.0 > com.mapbox.navigation:navigator:1.0.0

**Comment by LukasPaczos** [comment]
Hey @peytonwupeixin, thanks for reaching out!

It's surprising that your build system tries to reach `mapbox-navigation-native:14.1.2`. The ` com.mapbox.navigation:ui:1.0.0` uses `mapbox-navigation-native:18.0.3`. Could you give us more information about your build script config or output of the dependencies list task?

**Comment by peytonwupeixin** [comment]
> Hey @peytonwupeixin, thanks for reaching out!
> 
> It's surprising that your build system tries to reach `mapbox-navigation-native:14.1.2`. The ` com.mapbox.navigation:ui:1.0.0` uses `mapbox-navigation-native:18.0.3`. Could you give us more information about your build script config or output of the dependencies list task?

This is my dependencies list file.
[release.txt](https://github.com/mapbox/mapbox-navigation-android/files/5354186/release.txt)

**Comment by peytonwupeixin** [comment]
I clean and rebuild the project.It go well.
Thank you very much for your prompt reply. I close this issue.
