### ISSUE TITLE
Clear voice instructions queue on a reroute

### ISSUE THREAD

**Issue by LukasPaczos** [mapbox/mapbox-navigation-android#3639]
Capturing from a user:
> I specifically ignored the instructions and kept driving. There were a lot of places on the road (u-turns) to correct. The voice instructions seemed to get into a queue and due to the quantity fell behind my driving. Would be nice if it knew to skip some and that would help catch up faster.

Ideally, we should clear the queue on each reroute to prevent outdated information from being provided to the user, or delaying the actionable messages.

/cc @abhishek1508 @asinghal22

**Comment by 1ec5** [comment]
This is needed for parity with the iOS navigation SDK, which implemented voice instruction interruption in mapbox/mapbox-navigation-ios#669 (in v0.8.2).
