### ISSUE TITLE
Snap heading to route line at start of route

### ISSUE THREAD

**Issue by ericrwolfe** [mapbox/mapbox-navigation-android#364]
When first starting navigation, the location puck and camera bearing match neither the route line or my current heading. It requires driving forward a second to kick in, but by then I’ve already made a u-turn because I’m confused about which way to start driving. 

While we evaluate the viability of #143, we should always start navigation with the puck + camera heading snapped to match that of the route line so that at a driver can start with confidence.

cc @danesfeder

**Comment by danesfeder** [comment]
First snapped location should always be following the route line, confirmed logic in #667
