### ISSUE TITLE
UI can get stuck on "Rerouting…" on bad cell connection

### ISSUE THREAD

**Issue by ericrwolfe** [mapbox/mapbox-navigation-android#365]
cc @danesfeder

**Comment by danesfeder** [comment]
In this scenario, we are off-route but don't have a new route to give to navigation.  Should we just hide the re-route UI and let the driver go-on without the new route?

**Comment by ericrwolfe** [comment]
Yeah, if the reroute fails we should just let the user continue driving with their old route line and turn banner still visible. We shouldn't even bother trying to reroute (thus show the reroute UI) unless there's an internet connection, but we can periodically try to reroute as the user continues to drive (currently every 50m) and the connection improves.

**Comment by ericrwolfe** [comment]
@danesfeder ran into this again this weekend and it made driving unusable after the UI got stuck. Even as I drove back into good cell service and I continued to follow the route line, the UI never returned back to normal and I had to close navigation.

**Comment by danesfeder** [comment]
We check for an internet connection before re-routing now #631
