### ISSUE TITLE
Allow drivers to set custom course tracking zoom level

### ISSUE THREAD

**Issue by ericrwolfe** [mapbox/mapbox-navigation-android#366]
If you try zooming out (two finger tap and drag up/down), the app immediately returns to the original zoom. 

We should allow zooming out while staying fixed on followWithCourse, and keeping the zoom level fixed at the user’s new setting.

cc @danesfeder

**Comment by akitchen** [comment]
This is unlocked by gesture handling changes LocationLayerPlugin v0.5.0
