### ISSUE TITLE
Update RouteAlertsActivity

### ISSUE THREAD

**Issue by korshaknn** [mapbox/mapbox-navigation-android#3669]
`mapbox-java 5.8.0-beta.2` contains fixes of `List<Incidents>` (moved from `LegStep` to `RouteLeg`)
It'd be great to update RouteAlertsActivity so that incidents are displayed / tested and ideally use a real route including all types of alerts (currently alerts are faked).

**Comment by RingerJK** [comment]
We also need update examples docs https://docs.mapbox.com/android/navigation/examples/route-alerts/

**Comment by LukasPaczos** [comment]
https://github.com/mapbox/mapbox-navigation-android/pull/3704 landed, closing here.
