### ISSUE TITLE
Mapbox SDK not downloading in example sample project

### ISSUE THREAD

**Issue by text4lilac** [mapbox/mapbox-navigation-android#3678]
**Android API: 30-Android11**
**Mapbox Navigation SDK version: 9.5.0**

### Steps to trigger behavior

 1.I have download an example demo code on this link to: https://github.com/mapbox/mapbox-navigation-android
 2.After code builds a secret token set in gradle.property or build.gradle file, it created in my mapbox account.
 3.And run demo execute build error ---->> Could not HEAD 'https://api.mapbox.com/downloads/v1/vision/android/maven/com/mapbox/gradle/plugins/sdk-registry/0.2.1/sdk-registry-0.2.1.pom'. Received status code 403 from server: Forbidden
Disable Gradle 'offline mode' and sync project
4. and click to show in the browser error is {"message":"Not Authorized - No Token"}
5. In my account set DOWNLOAD: READ  check secret key, but build project not download mapbox sdk.

### Expected behavior
Working demo proper with navigation.
### Actual behavior
to: https://github.com/mapbox/mapbox-navigation-android [ Link code not working me so explain above step for facing issues. ]

**Comment by LukasPaczos** [comment]
Hey @text4lilac! Which branch are you checking out when trying to build the examples project? There's currently no plugin that tries to reach `'https://api.mapbox.com/downloads/v1/` URL on `master`, all are pointing to `https://api.mapbox.com/downloads/v2/`. Have you see the documentation in https://github.com/mapbox/mapbox-navigation-android/blob/master/CONTRIBUTING.md?

**Comment by LukasPaczos** [comment]
Closing, please let us know if the above instructions were not enough to compile the project.
