### ISSUE TITLE
Update documentation for unknown traffic color override

### ISSUE THREAD

**Issue by cafesilencio** [mapbox/mapbox-navigation-android#3684]
Related to the work done in this PR https://github.com/mapbox/mapbox-navigation-android/pull/3672, documentation should be updated that explains the feature and how to use it.

For specified road classes, any section where the traffic is 'unknown' can be represented using the 'low' traffic congestion color rather than the 'unknown' traffic color.

**Comment by cafesilencio** [comment]
The PR for the documentation update is here: https://github.com/mapbox/android-docs/pull/1566

**Comment by LukasPaczos** [comment]
Closing as resolved.
