### ISSUE TITLE
Rotating after arrival causes a reroute

### ISSUE THREAD

**Issue by ericrwolfe** [mapbox/mapbox-navigation-android#370]
After arrival, rotating the device causes a reroute and starts navigation over again.

![screenshot_20171011-162632](https://user-images.githubusercontent.com/664805/31472805-aec5a594-aea5-11e7-9b24-cbcc48e3dab8.png)

cc @danesfeder

**Comment by ericrwolfe** [comment]
In fact, I've noticed rotation often causes reroutes during general navigation even before arrival.

**Comment by danesfeder** [comment]
No longer an issue after #667 - we stop listening for off-route events after an arrival of the final leg
