### ISSUE TITLE
Layers displayed behind roads style layer

### ISSUE THREAD

**Issue by Guardiola31337** [mapbox/mapbox-navigation-android#3700]
Route line is the more evident but it's happening with other layers too 👀 

![route_line_behind_roads_layer](https://user-images.githubusercontent.com/1668582/97357004-7cd98a00-186f-11eb-97d8-a5a544e9a638.png)

`ReplayActivity`

![layers_behind_roads_style_layer](https://user-images.githubusercontent.com/1668582/97357049-8d8a0000-186f-11eb-99f9-31043b1d8c9a.gif)

`NavigationViewActivity`

![layers_behind_roads_style_layer_navigation_view](https://user-images.githubusercontent.com/1668582/97357155-b7432700-186f-11eb-9500-2a6c1996f9a7.gif)

It seems a regression from https://github.com/mapbox/mapbox-navigation-android/pull/3687

cc @LukasPaczos @cafesilencio

**Comment by LukasPaczos** [comment]
Yes, noticed as well. Working on it now.
