### ISSUE TITLE
Add LegMilestone to go along with Step and Route Milestones

### ISSUE THREAD

**Issue by juanwall** [mapbox/mapbox-navigation-android#371]
I set a custom milestone when my navigation activity is first created. I have routes with multiple waypoints.

The custom milestone is called when the first waypoint is reached, but not for any other waypoints.

Is this expected behavior, or do I need to re-add the custom milestone after each time it's called?

**Comment by cammace** [comment]
Can you provide some code on how you are setting up the Milestone? I don't believe we currently have a `LegMilestone` implementation which sounds like something you are looking for. Shouldn't be too hard to create it if needed.

**Comment by johnwallco** [comment]
Sure, @cammace. The code below is in my activity's onCreate method: 

```
 navigation.addMilestone(new RouteMilestone.Builder()
                .setIdentifier(68876)
                .setTrigger(
                        Trigger.all(
                                Trigger.lte(TriggerProperty.STEP_DISTANCE_TOTAL_METERS, 350),
                                Trigger.eq(TriggerProperty.LAST_STEP, TriggerProperty.TRUE)
                        )
                ).build());
```
In the TriggerProperty.java class in the SDK, there is the following:

```
statementObjects.put(TriggerProperty.LAST_STEP,
      new Number[] {routeProgress.currentLegProgress().stepIndex(),
        (routeProgress.currentLeg().getSteps().size() - 2)});
```
Therefore, I thought I would just need to add the custom milestone once in the activity. 

But maybe I need to add it again after every waypoint is reached?

**Comment by cammace** [comment]
`new RouteMilestone.Builder()` means this will only ever get triggered once. Adding a `LegMilestone` would make the most sense here, changing the title of this ticket and using it to track progress on adding an implementation for this.

**Comment by johnwallco** [comment]
Thanks, @cammace. It works when they're added after each waypoint is reached, so I'll use that for now.

I'm looking forward to the feature.

**Comment by Guardiola31337** [comment]
Hey @juanwall 👋 thanks for checking out the SDK.

Want to note that milestones is not going to be a feature of the upcoming `1.0` SDK. Stay tuned for the upcoming beta release and let us know if you have any problems implementing OP's feature.

Closing here.

**Comment by Guardiola31337** [comment]
Hey @juanwall we've just released [`release_core_1.0.0-rc.1`](https://github.com/mapbox/mapbox-navigation-android/releases/tag/release_core_1.0.0-rc.1) 🎉 🚀 

Please review the [developer documentation](https://docs.mapbox.com/android/beta/navigation/overview/#installation) to start building with the Mapbox core Navigation SDK v1.0 for Android and if you already use an older version of the Navigation SDK, check out [the migration guide](https://github.com/mapbox/mapbox-navigation-android/wiki/1.0-Navigation-SDK-Migration-Guide) to transition your project from the "legacy" core Navigation SDK to the 1.0 version and let us know if you have any questions or run into issues and please open tickets in https://github.com/mapbox/mapbox-navigation-android/issues/new and we will take it from there! We would love your feedback.

Thanks again!
