### ISSUE TITLE
Location puck turns the wrong direction after device rotation

### ISSUE THREAD

**Issue by ericrwolfe** [mapbox/mapbox-navigation-android#372]
cc @danesfeder

**Comment by akitchen** [comment]
Fixed? /cc @danesfeder

**Comment by danesfeder** [comment]
This is no longer a bug with the navigation UI:
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/8434572/40251230-ba2ad7d0-5aa6-11e8-8a4b-87e46110b021.gif)
