### ISSUE TITLE
ERROR: Unable to resolve dependency for ':app@debugUnitTest/compileClasspath': Could not resolve com.mapbox.navigation:core:1.1.0

### ISSUE THREAD

**Issue by amalmadawa90** [mapbox/mapbox-navigation-android#3733]
HI,
I'M GETTING THIS ERROR WHEN I trying ti implement navigation ui 1.1.0

ERROR: Unable to resolve dependency for ':app@debugUnitTest/compileClasspath': Could not resolve com.mapbox.navigation:core:1.1.0

android studio version 3.6.1

**Comment by LukasPaczos** [comment]
Hey @amalmadawa90, did you setup your token as specified in https://docs.mapbox.com/android/navigation/overview/#install-the-navigation-sdk? I'm going to go ahead and close as a https://github.com/mapbox/mapbox-navigation-android/issues/3780 duplicate if your token setup is correct.
