### ISSUE TITLE
The puck in Replay History example uses magnetic heading from the phone rather than the bearing form the enhanced location

### ISSUE THREAD

**Issue by mskurydin** [mapbox/mapbox-navigation-android#3755]
**Android API:** 
**Mapbox Navigation SDK version:** commit hash d1c16c631

### Steps to trigger behavior

 1. Start replay history example
 2. Rotate the phone a bit to see that it affects the direction the puck is pointing

### Expected behavior

The puck should use the bearing from the enhanced location.

### Actual behavior

See the title.

Btw, the camera direction is tied to the correct bearing from the enhanced location.

**Comment by kmadsen** [comment]
@mskurydin thanks for reporting, have noticed this but didn't dig into it.

The location puck will use the magnetic heading for it's mode is set to COMPASS
https://docs.mapbox.com/archive/android/maps/api/9.4.0/
https://docs.mapbox.com/android/maps/overview/ui-settings/#compass  

We will be able to replay the compass history when we implement this feature https://github.com/mapbox/navigation-sdks/issues/511

Considering that is a feature and not a bug, I'm proposing a simpler change. Show the GPS location puck at all times in the history example. https://github.com/mapbox/mapbox-navigation-android/pull/3759
