### ISSUE TITLE
NPE when formatting date in the telemetry impl

### ISSUE THREAD

**Issue by LukasPaczos** [mapbox/mapbox-navigation-android#3765]
```
java.lang.NullPointerException: Attempt to invoke virtual method 'long java.util.Date.getTime()' on a null object reference
     FATAL EXCEPTION: main
Process: com.mapbox.onetap.app, PID: 13367
java.lang.NullPointerException: Attempt to invoke virtual method 'long java.util.Date.getTime()' on a null object reference
	at java.util.Calendar.setTime(Calendar.java:1749)
	at java.text.SimpleDateFormat.format(SimpleDateFormat.java:981)
	at java.text.SimpleDateFormat.format(SimpleDateFormat.java:974)
	at java.text.DateFormat.format(DateFormat.java:341)
	at com.mapbox.android.telemetry.l0.d(TelemetryUtils.java:1)
	at h.d.f.b.s.h.y(MapboxNavigationTelemetry.kt:11)
	at h.d.f.b.s.h.l(MapboxNavigationTelemetry.kt:1)
	at h.d.f.b.s.h$c.invoke(MapboxNavigationTelemetry.kt:8)
	at h.d.f.b.s.h.O(MapboxNavigationTelemetry.kt:6)
	at h.d.f.b.s.h.s(MapboxNavigationTelemetry.kt:1)
	at h.d.f.b.s.h.e(MapboxNavigationTelemetry.kt:9)
	at h.d.f.b.e.e(NavigationSession.kt:5)
	at h.d.f.b.e.i(NavigationSession.kt:4)
	at h.d.f.b.e.c(NavigationSession.kt:3)
	at h.d.f.b.e.a(NavigationSession.kt:3)
	at h.d.f.b.t.b.i.Z(MapboxTripSession.kt:5)
	at h.d.f.b.t.b.i.stop(MapboxTripSession.kt:7)
```

Caught by a robo test using `v1.2.0-rc.1`.

/cc @korshaknn @Guardiola31337

**Comment by korshaknn** [comment]
11-12 03:02:51.376: D/MAPBOX_TELEMETRY(13367): session state is IDLE
11-12 03:02:51.376: D/MAPBOX_TELEMETRY(13367): sessionStop
11-12 03:02:51.376: D/MAPBOX_TELEMETRY(13367): resetOriginalRoute
11-12 03:02:51.376: D/MAPBOX_TELEMETRY(13367): resetRouteProgress
11-12 03:02:51.376: D/MAPBOX_TELEMETRY(13367): trackFreeDrive STOP
11-12 03:02:51.376: D/MAPBOX_TELEMETRY(13367): createFreeDriveEvent
11-12 03:02:51.383: D/MAPBOX_TELEMETRY(13367): populateNavigationFreeDriveEvent
11-12 03:02:51.383: D/MAPBOX_TELEMETRY(13367): --------- beginning of crash
11-12 03:02:51.385: E/AndroidRuntime(13367): FATAL EXCEPTION: main
11-12 03:02:51.385: E/AndroidRuntime(13367): Process: com.mapbox.onetap.app, PID: 13367
11-12 03:02:51.385: E/AndroidRuntime(13367): java.lang.NullPointerException: Attempt to invoke virtual method 'long java.util.Date.getTime()' on a null object reference

**Comment by korshaknn** [comment]
what happens:
- when 1Tap is opened `FreeDrive` is started
- we need to track `FreeDriveStart` event
to create the event we need a location, we `wait` for it in a `while`  loop. But `onRawLocationChanged`  is not called.
so, we are in free drive, but without a location and our while loop is waiting for it. we can't send `FreeDriveStart`
- open `search` -> press `Navigate`
- session state changes from `FreeDrive` to `ActiveGuidance`
- we need to post `FreeDriveStop`  event. Now we have a location, because `onRawLocationChanged` was called after navigation started. But `FreeDriveStop` can't use some params, they are null, for example `sessionStartTime` .
- `crash`

**Comment by korshaknn** [comment]
we should change order in `MapboxNavigation.onDestroy`

when TripSession stops we need to handle it and send some pending events. But it can NOT be done, because we call
`MapboxNavigationTelemetry.unregisterListeners(this@MapboxNavigation)` before

**Comment by korshaknn** [comment]
looks like we have 2 known issues:
- occasional crash (no location passed to `onRawLocationChanged`)
- dropping events when destroying navigation
