### ISSUE TITLE
Route generation

### ISSUE THREAD

**Issue by palimad** [mapbox/mapbox-navigation-android#3767]
Hello, in your demos you use MapboxDirections.builder() and also mapboxNavigation.requestRoutes().

What is the difference between them? Thanks

**Comment by LukasPaczos** [comment]
Hey @palimad!

`MapboxDirections.builder()` directly uses our [Directions API ](https://docs.mapbox.com/help/glossary/directions-api/) to obtain the route which can later be used for turn-by-turn navigation with `MapboxNavigation#setRoutes`.

`MapboxNavigation.requestRoutes()` simplifies the process of creating and maintaining a request (the results are automatically used for turn-by-turn navigation) and also offers hybrid routing features. When internet connectivity is available, the SDK also uses `MapboxDirections` under the hood. But if there's no connectivity, it will try to generate the route on-device with the data that was cached during previous trips or with upcoming offline capabilities. The quality of online and offline routes is the same, besides the live traffic data that Directions API has access to and is not available when the device is offline.
