### ISSUE TITLE
Question about dead reckoning algorithms.

### ISSUE THREAD

**Issue by peytonwupeixin** [mapbox/mapbox-navigation-android#3779]
Hey guys,I have a quetion about the dead reckoning algorithms used in v1.0 and later.I will be grateful if you have time to answer it.
I wonder that how the SDK to confirm the speed, heading direction for estimating current location.
Does it only use these data from previous locations to estimate them or does it also refer to the real-time values ​​obtained by the sensors when the device has(eg. linear acceleration sensor  and magnetic field sensor)?
Dead reckoning is subject to cumulative errors. When GPS signals are unavailable(eg.surrounded by tall buildings, inside a tunnel),the previous data may have been estimated,and it would cause the errors more serious if only use previous data to estmate current location. I think that the result may be more accurate if we refer to the current real-time data to caculate it.

**Comment by mskurydin** [comment]
Currently, our Dead Reckoning algorithm is quite simple - it uses only the data from previous locations plus some heuristics and is intended primarily for tunnels. Sensor data (from IMU) is not used at the moment (the quality of the real-time data varies across different vendors and device models). However, we have plans to fuse sensor data in the future. We cannot provide the timeline for this at the moment.

**Comment by peytonwupeixin** [comment]
Copy,thanks a lot and I will close this issue.
