### ISSUE TITLE
Snap To Route just puts the point onto the nearest street 

### ISSUE THREAD

**Issue by kozyr** [mapbox/mapbox-navigation-android#378]
This should not be what happens there. GPS error can break this very, very quickly near tall buildings - downtown NY or Chicago.

**Comment by cammace** [comment]
Snap to route will only snap the user location to the route if the GPS location is within X meters away from the route line. This tolerance is customizable using MapboxNavigationOptions. Does this solve your issue or are you noticing a bug with this logic?

**Comment by kozyr** [comment]
No, I think there an issue with the logic. Imagine you have parallel streets A and B, and you're somewhere in downtown Chicago where GPS accuracy is bad (it's not uncommon to have accuracy as reported by Android LocationManager to be > 200). You're driving along street A, GPS gets two points A_1 and A_2 that are somewhere between A and B, but closer to street A. Then you get two more points, B_1 and B_2, which are closer to street B. At this point, you're still on street A, there's no way you could be on street B (as you haven't driven thru any streets connecting A and B). Then you get two more points, A_3 and A_4, and so on. 

How would current implementation be behaving when it gets points A_1, A_2, B_1, B_2, A_3 and A_4? The expected behavior is that all 6 points should be shown as movement along street A.

**Comment by kozyr** [comment]
And another scenario is this - you get points 
A_1, A_2, B_1, B_2, B_3, B_4 while traveling along street B the entire time. What would happen here?

**Comment by danesfeder** [comment]
Hey @kozyr 👋 urban canyons definitely present some serious issues with how we validate location updates (currently [we don't do much](https://github.com/mapbox/mapbox-navigation-android/blob/master/libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/NavigationService.java#L288-L296)).  

We are currently looking into this and testing with https://github.com/mapbox/mapbox-navigation-android/pull/690.  

You're right though, if the user is considered on-route (we don't snap if they are considered off-route) we could potentially snap to a nearby road in a city if it's close enough to the current road the user is traveling along.

**Comment by danesfeder** [comment]
Hey @kozyr with `0.20.0`, our snapping logic no longer snaps to the nearest street and rather only snaps to the route, which has proven more formidable in city / urban canyon settings.  Going to go ahead and close this. 

@kevinkreiser feel free to add any context you see fit here. Thanks!

**Comment by kevinkreiser** [comment]
Right so the current implementation is limited in what it can do by the information that it has. Currently the navigation has only your GPS locations and the loaded route in terms of geometry. When multiple geometries are very close to each other in the real world there are several factors which make guessing which one you are on pretty difficult.

- width of the road carriage (how many lanes for example)
- accuracy of the digitization is it drawn by the mappers in the right place
- accuracy of the GPS (urban reflections make for drift)
- z level or altitude accuracy

With the aforementioned information we have available at present we are making the best guess we can (it really is a guess). We are considering ways of improving this in the future by increasing the density of information we have during navigation and using statistical approaches for determining the most likely path that you've been traveling. We've not gotten started yet on this effort but its definitely on our radar.
