### ISSUE TITLE
Failed to resolve: com.mapbox.navigation:ui:1.1.0

### ISSUE THREAD

**Issue by karaipan** [mapbox/mapbox-navigation-android#3780]
**Android API:**
**Mapbox Navigation SDK version:**

### Steps to trigger behavior

 1. I just want to build with latest navigation library.
    My app already worked with previous version
  
`implementation 'com.mapbox.mapboxsdk:mapbox-android-navigation:0.42.6'
    implementation 'com.mapbox.mapboxsdk:mapbox-android-navigation-ui:0.42.6'
    implementation 'com.mapbox.mapboxsdk:mapbox-android-core:3.0.0'`

But when I tried to upgrade to 1.0 NavigationSDK, it always fails to resolve without any specific error.
`implementation 'com.mapbox.navigation:ui:1.1.0'`

I also rechecked my token, it also has download:read scope already.
Anything I can do to upgrade successfully?

Thank for your support.

**Comment by LukasPaczos** [comment]
Hey @karaipan, could you run `gradlew build -i` or any other command that will output build logs with more information and paste them here?

**Comment by karaipan** [comment]
Hi @LukasPaczos,
I'm so thankful for your support.
Here's the logs which printed. I'm look forward to hearing your advice.

`Creating configuration androidTestUtil
WARNING: DSL element 'android.dataBinding.enabled' is obsolete and has been replaced with 'android.buildFeatures.dataBinding'.
It will be removed in version 5.0 of the Android Gradle plugin.
All projects evaluated.
Analytics other plugin to proto: Unknown plugin type com.google.firebase.crashlytics.buildtools.gradle.CrashlyticsPlugin expected enum COM_GOOGLE_FIREBASE_CRASHLYTICS_BUILDTOOLS_GRADLE_CRASHLYTICSPLUGIN
Selected primary task 'build' from project :
Configuring Java sources compilation with source level 1.8 and target level 1.8.
Configuring Java sources compilation with source level 1.8 and target level 1.8.
Resource missing. [HTTP HEAD: https://dl.google.com/dl/android/maven2/com/mapbox/navigation/ui/1.1.0/ui-1.1.0.pom]
Resource missing. [HTTP HEAD: https://repo.jfrog.org/artifactory/libs-release-bintray/com/mapbox/navigation/ui/1.1.0/ui-1.1.0.pom?referrer]
Resource missing. [HTTP HEAD: https://mapbox.bintray.com/mapbox/com/mapbox/navigation/ui/1.1.0/ui-1.1.0.pom]
Resource missing. [HTTP HEAD: https://repo.maven.apache.org/maven2/com/mapbox/navigation/ui/1.1.0/ui-1.1.0.pom]
Resource missing. [HTTP HEAD: https://mapbox.bintray.com/mapbox/com/mapbox/navigation/ui/1.1.0/ui-1.1.0.pom]
Registered task dependencies: app:developDebugCompileClasspath
Starting dependency analysis

FAILURE: Build failed with an exception.
`

Thank you!

**Comment by LukasPaczos** [comment]
@karaipan I don't see your Gradle script requesting resources from our Maven repo. Did you configure your script according to https://docs.mapbox.com/android/navigation/overview/#install-the-navigation-sdk?

**Comment by karaipan** [comment]
@LukasPaczos 
I'm so sorry for late reply.
I found out reason and it's my mistake when I put authentication information in gradle file.
I just put buildscript tag only, instead of allprojects tag.
It works now, so you can close this ticket.
Thanks again for your support, and really sorry to take time from you.

**Comment by Guardiola31337** [comment]
Thanks for checking out the SDK @karaipan 

Closing as solved.
