### ISSUE TITLE
Restore locationEngine state to what user had before nav session

### ISSUE THREAD

**Issue by cammace** [mapbox/mapbox-navigation-android#38]
When a navigation session begins, we take the instance of the locationEngine passed in and force the updating to happen more frequently. After a nav session, the locationEngine is automatically set to a lower battery consumption settings but this isn't necessarily what the developer had before they started navigating. Perhaps this is an API we should include in locationEngine, thoughts @zugaldia?

**Comment by zugaldia** [comment]
How would the new API look like?

**Comment by danesfeder** [comment]
Given the new `LocationEngine` APIs added in #1615, I think this ticket is no longer relevant.  The state of the `LocationEngine` is now determined by the `LocationEngineRequest`.  

When navigation ends, we stop requesting updates and the developer would then have the ability to re-request in their code with a new `LocationEngineRequest` with the state (frequency, priority, etc.) they desire.  

Closing here as non-actionable, but feel free to post further thoughts.
