### ISSUE TITLE
Provide a way to pass in Navigation Options when starting navigation UI session

### ISSUE THREAD

**Issue by Danny-James** [mapbox/mapbox-navigation-android#380]
How would I pass through NavigationOptions when running the NavigationUI with the following code?

`NavigationLauncher.startNavigation(this, route, null, false);`

**Comment by cammace** [comment]
@danesfeder, assigning to you, I'm not seeing a way to pass in options either. We should allow it as an optional param inside startNavigation.

**Comment by Danny-James** [comment]
@danesfender this looks like it has now been included in the `0.7.1-SNAPSHOT` release however, is their going to be away to allow us to set the options shown below;

setMinimumHighAlertDistance
setMaximumDistanceOffRoute
setMaxTurnCompletionOffset

etc..

**Comment by cammace** [comment]
https://github.com/mapbox/mapbox-navigation-android/pull/515 hasn't been merged yet https://github.com/mapbox/mapbox-navigation-android/pull/515 thus, it isn't avaliable yet

**Comment by Danny-James** [comment]
@cammace No Problem 👍

**Comment by karim-ro** [comment]
Do you plan to add language to NavigationViewOptions in 0.7.1 ? When the phone is set to a non-english language it uses non-english TextToSpeech to speak english instructions.
