### ISSUE TITLE
RouteListener missing?

### ISSUE THREAD

**Issue by simon-the-shark** [mapbox/mapbox-navigation-android#3811]
The documentation mentions RouteListener with its allowRerouteFrom() and few other methods several times. (e.g. 
[here](https://docs.mapbox.com/android/navigation/overview/off-route/) or [here](https://docs.mapbox.com/android/navigation/overview/custom-routes/)). Nevertheless, I can't find where I should import this from. I searched [API reference](https://docs.mapbox.com/android/navigation/api-reference/) and even the code. My IDE can't manage to import or find this neither.

**Comment by simon-the-shark** [comment]
So I would like to know if it's still relevant API and if so, where I can import this from

**Comment by LukasPaczos** [comment]
Hey @simon-the-shark, thanks for reaching out. It looks like some of our legacy documentation slipped to v1.

`RouteListener` and `allowRerouteFrom` are not available in the v1, instead, you can use the `OffRouteObserver` as well as `RerouteController` to control the reroute experience (see `MapboxNavigation#setRerouteController`). We'll fix the docs up!

**Comment by simon-the-shark** [comment]
Can I use custom reroute controller with navigation view from UI framework?

**Comment by Guardiola31337** [comment]
Yes you can as you can retrieve the `MapboxNavigation` instance from `NavigationView#retrieveMapboxNavigation` and if you're not using the Drop-in UI but any other UI components you should have `MapboxNavigation` already, from which you can interact.

**Comment by simon-the-shark** [comment]
Great, thanks for your assistance

**Comment by Guardiola31337** [comment]
Thank you @simon-the-shark for checking out the SDK!

**Comment by LukasPaczos** [comment]
Docs are updated.
