### ISSUE TITLE
Blank NavigationView

### ISSUE THREAD

**Issue by aardvarkk** [mapbox/mapbox-navigation-android#3815]
**Android API:** 19 (also tried 21 and 28)
**Mapbox Navigation SDK version:** 1.2.0

### Steps to trigger behavior

 1. Followed the steps on https://docs.mapbox.com/android/navigation/overview/#install-the-navigation-sdk to install the navigation SDK
 2. Ran the resulting app both on an actual device and in the emulator

### Expected behavior

A route should be shown with directions and a map

### Actual behavior

An empty screen is shown:

![image](https://user-images.githubusercontent.com/1251092/100160560-b00a3b80-2e64-11eb-83fe-7e465ca2b500.png)

I see only two errors in the debug output:

```
E/ResolutionTunerAppList: Target file doesn't exist: system/vendor/etc/sf_resolution_tuner_app_list.xml
E/ion: ioctl c0044901 failed with code -1: Invalid argument
```

It seems like the "map ready" callback is never fired, but I don't see any error messages indicating what the problem might be. It looks like another user had a similar issue with version [1.1.0 here](https://github.com/mapbox/mapbox-navigation-android/issues/3660), but they didn't say what they did to fix the issue -- they just claimed it wasn't related to Mapbox. I'd appreciate some guidance or troubleshooting about what could be the problem here.

**Comment by Guardiola31337** [comment]
@aardvarkk thanks for reaching out 👋 

That sounds like the `mapbox_access_token` is missing. Could you double check that? Instructions are detailed in https://docs.mapbox.com/android/navigation/overview/#configure-credentials under `Configure your public token` section.

**Comment by aardvarkk** [comment]
Thanks for the response. I believe my public token is properly loaded -- I've got it in my `strings.xml` file, and it shows in the Android Studio IDE as a substituted value. See this screenshot for the start of the token:

![image](https://user-images.githubusercontent.com/1251092/100165721-d2ee1d00-2e6f-11eb-88ee-88fb8c941e5a.png)

Interestingly, though, if I empty out the contents of the key in `strings.xml` and just set it to `<string name="mapbox_access_token"></string>`, I get the exact same behaviour. So it does feel a bit like the string isn't being used or something?

**Comment by aardvarkk** [comment]
Is there any word on this? I've continued to mess around with the default navigation example but have yet to see anything except the empty view shown above. The only changes I've made from copy/pasting the example wholesale are to stop using the kotlinx support extensions thing, and instead use the databinding approach with `inflate` as Android Studio recommends (since the code in the example is deprecated).

**Comment by aardvarkk** [comment]
... welp, that was the problem. I reverted back to the "Kotlin Synthetics" method of grabbing the view and that seemed to work, so I'll see if I can figure out the proper way to transition to the binding/inflate style without breaking the example app.

**Comment by Guardiola31337** [comment]
Hey @aardvarkk 👋 

Did you have a chance to follow up? Are we good to close here?

**Comment by aardvarkk** [comment]
@Guardiola31337 This issue can be closed, thank you. You may want to look into adjusting the example nav app code so that it uses the non-deprecated style of view binding. It should now use Kotlin Data Binding instead of Synthetics in order to avoid deprecation warnings from Android Studio.

**Comment by Guardiola31337** [comment]
Hey @aardvarkk thanks for the update and glad you figured it out. BTW friendly reminder that PRs are more than welcome 😅 

It'd be awesome if you can submit a PR fixing this 💯 

Thanks again!
