### ISSUE TITLE
Cached feedback events require to have all "after" locations collected

### ISSUE THREAD

**Issue by LukasPaczos** [mapbox/mapbox-navigation-android#3817]
Refs https://github.com/mapbox/mapbox-navigation-android/pull/3724, https://github.com/mapbox/mapbox-navigation-android/pull/3758.

We currently require all "after event" location samples to be collected before we cache the event, which means that if an event is reported close to the destination and we don't have time to collect all samples, which means that cached feedback list will not contain the feedback element to provide additional details.
![ezgif com-optimize (96)](https://user-images.githubusercontent.com/16925074/100231360-338c6100-2f27-11eb-9307-f1aebd179551.gif)

/cc @Guardiola31337 @JunDai @shelkovin

**Comment by Guardiola31337** [comment]
Noting that this is only in the context of https://github.com/mapbox/mapbox-navigation-android/pull/3758 i.e. it may be a problem if the PR merges as is. In `master` this shouldn't be a problem as all the events from the queue are flushed when the session is closed. Actually 👇 

> Object "MapboxNavigationFeedbackCache" is never used

cc @JunDai

**Comment by LukasPaczos** [comment]
That's right, thanks for checking @Guardiola31337 :+1:
