### ISSUE TITLE
Convert Directions API JSON to DirectionsRoute object for Navigation

### ISSUE THREAD

**Issue by RadicalMonkey** [mapbox/mapbox-navigation-android#3885]
Hi,

We are planning on building our app using MapBox but we would like to do all the API requests on our backend and simply provide the directions to the app to be visualised using the Navigation SDK for Android. However I have not been able to find a way to convert the JSON response from your Direction API (https://docs.mapbox.com/api/navigation/directions/#use-http-post-to-retrieve-directions) to a DirectionsRoute object that can be passed to the Navigation SDK. Hopefully you can help me with this.

Thanks!

**Comment by mirecalu** [comment]
Same here ! 
I've forked the repo and updated `DirectionsRoute` but the `Navigator#setRoute` return null with my updated `DirectionRoute` class.

As @RadicalMonkey says, hopefully there is a way to convert the JSON response from your Direction API.

Thanks!

**Comment by RadicalMonkey** [comment]
Bump

**Comment by RadicalMonkey** [comment]
Happy New Year bump!

**Comment by nesfeder** [comment]
If you're using the [Java SDK](https://docs.mapbox.com/android/java/guides/), you can use [this](https://github.com/mapbox/mapbox-java/blob/master/services-directions-models/src/main/java/com/mapbox/api/directions/v5/models/DirectionsRoute.java#L168) method. 

Cheers 🍻

**Comment by RadicalMonkey** [comment]
Thank you! Thats just what I was looking for!

**Comment by RadicalMonkey** [comment]
@nesfeder  Also, is there an equivalent for iOS? Thanks :)
