### ISSUE TITLE
App crashes with error "Terminating with uncaught exception of type jni::PendingJavaException" for this direction JSON string

### ISSUE THREAD

**Issue by aryalprakash** [mapbox/mapbox-navigation-android#3886]
**Android API:**
10

**Mapbox Navigation SDK version:**
1.1.0

### Steps to trigger behavior

 1. Use direction JSON string from here: [Direction JSON string](https://gist.githubusercontent.com/aryalprakash/35521df10606f6f4e5c16f40b6dbc938/raw/6ba4927f84fc28d64d75d02077c4ea21335ac384/gistfile1.txt)
 2. Execute turn by turn navigation activity
 3.

### Expected behavior
Show turn by turn navigation

### Actual behavior
App crashes with error "Terminating with uncaught exception of type jni::PendingJavaException" 

What's wrong with this JSON?

**Comment by LukasPaczos** [comment]
Hey @aryalprakash, could you provide a little more detail wrt to how you parse the route and initialize the navigation? Code samples would be great so that we can try to reproduce the issue.
