### ISSUE TITLE
Update com.android.tools.build:gradle: 4.0.1 to com.android.tools.build:gradle:4.1.0

### ISSUE THREAD

**Issue by Vishal949** [mapbox/mapbox-navigation-android#3887]
**Android API:**
**Mapbox Navigation SDK version:**

### Expected behavior
Success fully builds the project. 

### Actual behavior
Cannot query the value of task ':libnavigation-core:generateDebugBuildConfig' property 'versionCode' because it has no value available

**Comment by LukasPaczos** [comment]
Hey @Vishal949, this is a known upstream issue - https://github.com/mapbox/android-sdk-versions-plugin/issues/29.

cc @alfwatt @mapbox/core-sdk

**Comment by LukasPaczos** [comment]
Resolved on latest `main`.
