### ISSUE TITLE
ERROR: Could not GET 'https://api.mapbox.com/downloads/v2/releases/maven/com/mapbox/gradle/plugins/sdk-registry/0.4.0/sdk-registry-0.4.0.pom'. Received status code 403 from server: Forbidden

### ISSUE THREAD

**Issue by fanwei930124** [mapbox/mapbox-navigation-android#3893]
**Android API:**
**Mapbox Navigation SDK version:**

### Steps to trigger behavior

 1.
 2.
 3.

**Comment by LukasPaczos** [comment]
Hey @fanwei930124, if you're trying to build the project from source and contribute, please make sure to read [CONTRIBUTING.md](https://github.com/mapbox/mapbox-navigation-android/blob/master/CONTRIBUTING.md) which explains how to configure credentials.
