### ISSUE TITLE
ERROR: Could not GET 'https://api.mapbox.com/downloads/v2/releases/maven/com/mapbox/gradle/plugins/sdk-registry/0.4.0/sdk-registry-0.4.0.pom'. Received status code 403 from server: Forbidden Enable Gradle 'offline mode' and sync project

### ISSUE THREAD

**Issue by fanwei930124** [mapbox/mapbox-navigation-android#3897]
Here is error，The master branch I pulled from github. The AS version is 3.4, the accesstoken is correct, but the compilation fails all the time. Report the above error

**Comment by fanwei930124** [comment]
1,   I hava add  <string name="SDK_REGISTRY_TOKEN">pk.eyJ1IjoiZmFud2VpOTMwMTI0IiwiYSI6ImNramNhdmRqND....  to examples/src/main/res/values/mapbox-access-token.xml
2,  I hava add SDK_REGISTRY_TOKEN=pk.eyJ1IjoiZmFud2VpOTMwMT...  to  gradle.properties;
3,  dependencies.gradle add  
      mapboxSdkRegistry  : '0.4.0',
      mapboxAccessToken  : '0.2.1',
4,  The following error occurred after compiling the project ：
     Could not resolve com.mapbox.gradle.plugins:sdk-registry:0.4.0.
         > Could not get resource 'https://api.mapbox.com/downloads/v2/releases/maven/com/mapbox/gradle/plugins/sdk-registry/0.4.0/sdk-registry-0.4.0.pom'.
            > Could not GET 'https://api.mapbox.com/downloads/v2/releases/maven/com/mapbox/gradle/plugins/sdk-registry/0.4.0/sdk-registry-0.4.0.pom'. Received status code 403 from server: Forbidden
   > Could not resolve com.mapbox.gradle.plugins:access-token:0.2.1.
5， Thank you so much for helping me solve these problems；

**Comment by fanwei930124** [comment]
please help me solove this question.Thank you very much

**Comment by fanwei930124** [comment]
in the source code
pluginVersion = [
  mapboxSdkRegistry : '0.4.0',
  mapboxAccessToken  :  '0.2.1'
]
why mapboxAccessToken is number? Didn't is apply access-token? Tks

**Comment by LukasPaczos** [comment]
Hey @fanwei930124, your regular access token (which you added `mapbox-access-token.xml`) is not the same token that you need to use to download the SDK. Please give https://docs.mapbox.com/android/navigation/guides/install/#configure-credentials a read on how to obtain the downloads token.

Closing as resolved, let us know if this doesn't resolve your issue.

**Comment by fanwei930124** [comment]
yes,Thank you very much.It solved my problem
