### ISSUE TITLE
Speed up the replay navigation sample

### ISSUE THREAD

**Issue by mirecalu** [mapbox/mapbox-navigation-android#3917]
Hi,

I was using the ReplayActivity in the sample in order to simulate a GPS navigation. 
The speed of my location updates is quite slow.

Is there a way to increase my speed during the simulation ?

**Comment by Guardiola31337** [comment]
Hey @mirecalu thanks for reaching out and report your question.

`MapboxReplayer` exposes `playbackSpeed` that allows you to configure the speed 👀 

https://github.com/mapbox/mapbox-navigation-android/blob/e3a0f8bc179146348ece98903b258ba6fc81e8ad/libnavigation-core/src/main/java/com/mapbox/navigation/core/replay/MapboxReplayer.kt#L97-L109

Closing as answered.
