### ISSUE TITLE
Top bar missing in night mode

### ISSUE THREAD

**Issue by cammace** [mapbox/mapbox-navigation-android#393]
Pretty sure the top bars suppose to be there...

<img src="https://user-images.githubusercontent.com/5652865/31698455-be14bbc6-b38b-11e7-94a6-15a8a7160386.png" width=360/>

cc: @danesfeder

**Comment by ericrwolfe** [comment]
@danesfeder any ideas on what would cause this? I didn't have this problem with night mode on a Nexus 5x.

**Comment by danesfeder** [comment]
@cammace @ericrwolfe this should be fixed with the banner work in #404
