### ISSUE TITLE
Remove context from DistanceFormatterOptions

### ISSUE THREAD

**Issue by LukasPaczos** [mapbox/mapbox-navigation-android#3939]
@kmadsen commented on [Thu Feb 04 2021](https://github.com/mapbox/mapbox-navigation-android-internal/issues/126)

Follow up ticket from multiple discussions here https://github.com/mapbox/mapbox-navigation-android-internal/pull/91

**Mapbox Navigation SDK version:** 2.x

MapboxDistanceFormatter needs to support automatic detection of Locale. It has been able to do this with a dependency on the [application context](https://github.com/mapbox/mapbox-navigation-android/blob/efdd9fa4ce9252f59061ac560e0646bb7e2ac840/libnavigation-core/src/main/java/com/mapbox/navigation/core/internal/formatter/MapboxDistanceFormatter.kt#L35)

We have been [moving the application context](https://github.com/mapbox/mapbox-navigation-android/pull/3227) dependency around and [desiring access to it from anywhere](https://github.com/mapbox/mapbox-navigation-android/issues/823)

This issue is to remove the context from `DistanceFormatterOptions` and still support the automatic detection of Locale.

---

@kmadsen commented on [Thu Feb 04 2021](https://github.com/mapbox/mapbox-navigation-android-internal/issues/126#issuecomment-773427330)

Also linking this issue so it has references to all the issues addressed around this https://github.com/mapbox/mapbox-navigation-android/issues/3016

**Comment by kmadsen** [comment]
This issue isn't improved by simply moving it out of the Options https://github.com/mapbox/mapbox-navigation-android/pull/4135#discussion_r616212535. 

The distance formatter uses the `context` to infer device locale, and uses the context to get the view resources (is it "miles", "مایل", or "マイル"). In other words, it is needed. 

Removing it is a broader discussion - the description on this ticket is still valid https://github.com/mapbox/mapbox-navigation-android/issues/3016
