### ISSUE TITLE
Expose newly available route alerts data

### ISSUE THREAD

**Issue by LukasPaczos** [mapbox/mapbox-navigation-android#3941]
@LukasPaczos commented on [Fri Jan 29 2021](https://github.com/mapbox/mapbox-navigation-android-internal/issues/112)

Refs https://github.com/mapbox/mapbox-navigation-android-internal/pull/111. With Nav Native `v40+` we have access to more data fields in route alerts, we should expose them on the platform side in future iterations.

**Comment by truburt** [comment]
@LukasPaczos , @korshaknn , is there anything we need to do, or this ticket is a dummy?

**Comment by LukasPaczos** [comment]
@korshaknn you've been working a lot with alerts recently, is there any tailwork or things to expose for us? Or are we good to close here for now?

**Comment by korshaknn** [comment]
@LukasPaczos what is `newly available route alerts data` ?

**Comment by SiarheiFedartsou** [comment]
:wave:
Tbh I don't remember that we added smth to route alerts since their introduction 6 month ago. If you have everything from [our API](https://github.com/mapbox/mapbox-navigation-native/blob/a801584a6cfea9d3eb668a50804d05ec6af2dace/bindings/navigator.mbg#L162) exposed it should be enough

**Comment by LukasPaczos** [comment]
Sounds good, closing then.
