### ISSUE TITLE
Setup transifex for new UI modules

### ISSUE THREAD

**Issue by LukasPaczos** [mapbox/mapbox-navigation-android#3944]
@LukasPaczos commented on [Wed Jan 27 2021](https://github.com/mapbox/mapbox-navigation-android-internal/issues/100)

The newly introduced UI modules do not have transifex set up. We should also look into transferring already translated strings from the legacy UI SDK project to the new ones if they match 1 to 1.

**Comment by zugaldia** [comment]
We've successfully upgraded to Transifex's Premium Plan and we're unblocked to move forward with this work.
