### ISSUE TITLE
Sound control button

### ISSUE THREAD

**Issue by LukasPaczos** [mapbox/mapbox-navigation-android#3947]
@LukasPaczos commented on [Tue Jan 26 2021](https://github.com/mapbox/mapbox-navigation-android-internal/issues/93)

Tracks the re-implementation of the sound control button available in the v1 into v2 - https://github.com/mapbox/mapbox-navigation-android/blob/master/libnavigation-ui/src/main/java/com/mapbox/navigation/ui/SoundButton.java.

We should follow the new API-View architecture and add appropriate unit and instrumentation tests.

@d-prukop are you considering any new designs for the sound control button?

/cc @abhishek1508 @Guardiola31337

**Comment by RingerJK** [comment]
https://github.com/mapbox/mapbox-navigation-android/pull/4219 is landed
