### ISSUE TITLE
Camera-Puck synchronization with keypoints

### ISSUE THREAD

**Issue by LukasPaczos** [mapbox/mapbox-navigation-android#3948]
@LukasPaczos commented on [Mon Jan 25 2021](https://github.com/mapbox/mapbox-navigation-android-internal/issues/92)

Location Puck and the Map Camera are animated independently but still should remain in a significant degree of synchronization when in the `FOLLOWING` mode during a turn-by-turn or free-drive experience. This creates a challenge when using keypoints generated by NN to make the puck "glued" to the road even during maneuvers. Even if we use the linear animation duration for both the puck and the camera, the puck will be animated on a curved path (origin -> intermediate maneuver points -> destination) while the camera is animated on a straight path (origin -> destination). This has the effect of the puck speeding up and slowing down in comparison to the camera's position:

https://user-images.githubusercontent.com/16925074/105748736-d28f0280-5f42-11eb-8306-6738c04d0785.mp4

Any ideas on how we can resolve this issue @d-prukop?

**Comment by d-prukop** [comment]
It seems like the camera location is animating smoothly. What drives the puck animation? Is it on a linear interpolator or eased? It should be linear. Is the vehicle location that's driving the puck position the same as the vehicle location that's going in to the camera for determining where the route line is sliced?

**Comment by LukasPaczos** [comment]
More context in https://github.com/mapbox/mapbox-navigation-android/issues/4140 and closing here in favor of continuing the discussion there.
