### ISSUE TITLE
Feature: Speed Limit

### ISSUE THREAD

**Issue by LukasPaczos** [mapbox/mapbox-navigation-android#3955]
@abhishek1508 commented on [Fri Jan 08 2021](https://github.com/mapbox/mapbox-navigation-android-internal/issues/61)

Show speed limit based on MUTCD/VIENNA convention.

---

@cafesilencio commented on [Wed Feb 03 2021](https://github.com/mapbox/mapbox-navigation-android-internal/issues/61#issuecomment-772733195)

Currently blocked by https://github.com/mapbox/mapbox-navigation-native/issues/2288. 
The work is done but can't be tested until the issue is resolved.

**Comment by cafesilencio** [comment]
One thing I'm confused about is what to do when a section of the route doesn't have speed limit data.  For a given route there are some roads that we have speed limit data for and some not.  

For example when testing I am on the freeway and the speed limit value showing is 55 but when I exit (in my testing area) the street I exit onto doesn't have any speed limit data so the UI still shows 55 which is incorrect. What should happen in this case? Should the UI element disappear when there is no speed limit data or should some other value display? Showing 0 mph in these cases doesn't make sense either.

cc @abhishek1508 @d-prukop @LukasPaczos

**Comment by abhishek1508** [comment]
I think the UI itself should completely disappear as you mentioned showing 0 doesn't make sense.

@cafesilencio

**Comment by cafesilencio** [comment]
So would the UI view be responsible for hiding itself when there is no value for the speed limit? It gets a little tricky because then the UI view has a mind of it's own rather than the developer controlling it.  Would it make more sense for that task to be left to the developer to check when the speed limit value coming from core is null and hide it themselves?

**Comment by LukasPaczos** [comment]
> Would it make more sense for that task to be left to the developer to check when the speed limit value coming from the core is null and hide it themselves?

This does make sense to me as long as we document it clearly. But in addition to that, would we be able to display something like a `?` when the limit is unknown? Just to make the View more robust and be able to handle all the cases. Then it's up to developers whether they want to show that `?` or hide the whole view.

**Comment by cafesilencio** [comment]
I think we should involve somebody from the design side on this question. Personally I wouldn't want to to see a "?" when driving. It would lower my confidence in the app. that i'm using. Where as if the ui element simply disappeared I probably wouldn't notice it as mostly my eyes would be on the road. Also it makes for a strange implementation that if the API class receives a null speedLimit it should then produce a value of 0 for the calculated speed limit value returned in the state and then the view class should interpret the 0 as a "?" for displaying on the screen.  

cc @d-prukop

**Comment by d-prukop** [comment]
I agree with @cafesilencio. I'd rather hide the view automatically and optionally show a "no-data" state. The double dashes works well for this.

cc @cafesilencio @abhishek1508 @1ec5
