### ISSUE TITLE
Release v0.1

### ISSUE THREAD

**Issue by zugaldia** [mapbox/mapbox-navigation-android#4]
In order to be able to release the first version of the Mapbox Navigation SDK for Android as a standalone project, the following things need to happen:

- [x] Land https://github.com/mapbox/mapbox-java/pull/439
- [x] Fix the fixture paths for OSRM text instructions tests
- [x] Land https://github.com/mapbox/mapbox-navigation-android/pull/1
- [x] Update to MAS _without navigation classes_ (this will let us build the Test App)
- [x] Add CI support https://github.com/mapbox/mapbox-navigation-android/issues/2 @Guardiola31337 
- [x] Add Maven functionality https://github.com/mapbox/mapbox-navigation-android/issues/3 @Guardiola31337 
- [x] Make this repository public
- [x] Publish to Maven @zugaldia
- [x] Add description and installation instructions to README @langsmith @cammace 

cc: @cammace @danesfeder

**Comment by zugaldia** [comment]
Thank @1ec5 , added the item to OP and made the repo public at the same time.

Once https://github.com/mapbox/mapbox-navigation-android/pull/1 landed, code is effectively moved. We're now getting ready for a Maven release.

**Comment by zugaldia** [comment]
@langsmith @cammace The Navigation SDK is now available on Maven. All that we need to do to close this ticket is to update the `README.md` file with a basic SDK description, link to [latest docs](https://www.mapbox.com/android-docs/mapbox-navigation/2.1.0/navigation/) (version should be updated to 0.1), and installation instructions.

The snippet to add to your `build.gradle` to consume this SDK is the following:

```
// Mapbox Navigation SDK for Android
compile('com.mapbox.mapboxsdk:mapbox-android-navigation:0.1.0@aar') {
    transitive = true
}
```

**Comment by langsmith** [comment]
Ok, I will make those changes @zugaldia

**Comment by cammace** [comment]
Noting here that similar to our services SDK, you don't have to include the transitive part in your gradle file.

```groovy
compile 'com.mapbox.mapboxsdk:mapbox-android-navigation:0.1.0'
```
works the same.

**Comment by cammace** [comment]
Look like the readme is up to date and v0.1 has been released, closing this ticket.
