### ISSUE TITLE
Throw exception when origin and destination positions are the same

### ISSUE THREAD

**Issue by cammace** [mapbox/mapbox-navigation-android#40]
Causing a crash on Firebase, temporarily fixed it in the testapp activity, this might need to be fixed in mapbox-java too @zugaldia?

**Comment by zugaldia** [comment]
@cammace yeah, could you please ticket it?

**Comment by cammace** [comment]
This is actually not an issue for navigation anymore when the navigation session starts with the same positions, it is treated as though you have instantly arrived (as it should 😄).
