### ISSUE TITLE
Move onProgressChange into NavigationService

### ISSUE THREAD

**Issue by Guardiola31337** [mapbox/mapbox-navigation-android#402]
Ticket to keep track of @ericrwolfe and @cammace discussion

> @cammace would it make sense to move the arrive event to `NavigationService` like the rest of the events? That way most of the current changes to this class could be self contained within `NavigationService`. @Guardiola31337 

> Don't immediately see any issue with moving the entire `onProgressChange` into NavigationService` to keep all the events in the same class. Though I think whichever path we take, we should only have 1 internal onProgressChange to keep things simple. Let's do this in a different PR and go ahead and merge this one?

https://github.com/mapbox/mapbox-navigation-android/pull/382#discussion_r145511481
https://github.com/mapbox/mapbox-navigation-android/pull/382#discussion_r145512851

**Comment by danesfeder** [comment]
This was fixed with #511 in favor of a dedicated metrics listener and removing any telem related logic from `NavigationService`
