### ISSUE TITLE
Cannot migrate to v2.0.0-alpha.10 tilesBaseUri

### ISSUE THREAD

**Issue by kmadsen** [mapbox/mapbox-navigation-android#4037]
**Mapbox Navigation SDK version:**  v2.0.0-alpha.10

### Steps to trigger behavior

It looks like tilesUri was intended to be a rename to tilesBaseUri, but it blocks an app from building the routing tile options https://github.com/mapbox/mapbox-navigation-android/pull/4032. cc: @LukasPaczos 

``` kotlin
val tilesUri = URI(get<PreLoadedSettings>().settings.routingTilesEndpoint.value)
val routingTilesOptions = RoutingTilesOptions.Builder()
    .tilesBaseUri(tilesUri)
    .tilesVersion(tilesVersion)
    .filePath(tilesDir)
    .build()
````
```
https://api.mapbox.com/route-tiles/v2/mapbox/driving-traffic
```

**Comment by kmadsen** [comment]
I'm checking further because, I'm not actually sure if the app is wrong or the options are wrong 🤔 

maybe it's supposed to be?
```
tilesBaseUir("https://api.mapbox.com")
path("route-tiles/v2/mapbox/driving-traffic")
```

**Comment by kmadsen** [comment]
Looking at the defaults here.. but i'm not sure how tilesDataset and tilesProfile are supposed to be here 🤔 
`https://api.mapbox.com/route-tiles/v2/mapbox/driving-traffic`

```
private var tilesBaseUri: URI = URI("https://api.mapbox.com")
private var tilesDataset: String = "mapbox"
private var tilesProfile: String = "driving-traffic"
private var tilesVersion: String = ""
```

**Comment by kmadsen** [comment]
cc: @korshaknn in case you know you already solved this

**Comment by LukasPaczos** [comment]
@kmadsen this is all documented in the options class:
https://github.com/mapbox/mapbox-navigation-android/blob/c7a740e04738abe3bb0c4e97422e6aa52cc36860/libnavigation-base/src/main/java/com/mapbox/navigation/base/options/RoutingTilesOptions.kt#L105-L143

and needs to be adjusted on the app side. Please reopen if you think we can improve the docs.

**Comment by kmadsen** [comment]
@LukasPaczos will you link to the docs? [The migration guide](https://github.com/mapbox/mapbox-navigation-android/wiki/2.0-Navigation-SDK-Migration-Guide#routing-tiles-configuration-aka-onbourdrouteroptions) doesn't have much

**Comment by kmadsen** [comment]
If you want to add the 1tap example to the docs that would probably be helpful for a reader: `https://api.mapbox.com/route-tiles/v2/mapbox/driving-traffic`

but will leave that up to you :)
