### ISSUE TITLE
Add bearing for each point in NavigationRoute

### ISSUE THREAD

**Issue by danesfeder** [mapbox/mapbox-navigation-android#407]
With MAS 3.0, if you don't provide a bearing for each `Point` added to a `NavigationRoute`, you'll get a failed response for the route.  

We should add a bearing to any `Point` that doesn't have one so the request still comes back successful.  It looks like this only happens if you add one bearing value to one `Point`, but not the rest of the `Point`s.  

cc @cammace

**Comment by ericrwolfe** [comment]
This has lead to a few temporary workarounds that should be fixed: 
* https://github.com/mapbox/mapbox-navigation-android/pull/408
* https://github.com/mapbox/mapbox-navigation-android/blob/79c9c4e023e04e8076d980872de7383c353ed89b/app/src/main/java/com/mapbox/services/android/navigation/testapp/activity/RerouteActivity.java#L160
