### ISSUE TITLE
ViewportDataSource doesn't guarantee to fit a point when in `FOLLOWING`

### ISSUE THREAD

**Issue by LukasPaczos** [mapbox/mapbox-navigation-android#4084]
**Mapbox Navigation SDK version:** 2.0.0-alpha.11

### Steps to trigger behavior

 1. Request `NavigationCamera` to `FOLLOWING`.
 2. Add a point with `MapboxViewportDataSource#additionalPointsToFrameForFollowing`.

### Expected behavior
All points added with `MapboxViewportDataSource#additionalPointsToFrameForFollowing` as well as the upcoming maneuver are visible.

### Actual behavior
The additional point or any route maneuver is not guaranteed to be shown. This is because we are using the current location point as the center of the camera (the first point is the current location):
https://github.com/mapbox/mapbox-navigation-android/blob/4f577ad6780c199a7c64a45d44781bdc09ac4d4c/libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/camera/data/MapboxNavigationViewportDataSource.kt#L748

and not the value produced by the `MapboxMap#cameraForCoordinates`:
https://github.com/mapbox/mapbox-navigation-android/blob/4f577ad6780c199a7c64a45d44781bdc09ac4d4c/libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/camera/data/MapboxNavigationViewportDataSource.kt#L782-L786

So the produced zoom level is for a different center coordinate than we are using, resulting in not all requested points being visible.

/cc @d-prukop

**Comment by d-prukop** [comment]
In following mode, while at max pitch, we lock the map center to the vehicle's location and place that centering screen location near the bottom. While approaching the maneuver the map will transition to 0º pitch and the map center will use the centroid of the points and additional points provided.

The intention would be to add `additionalPointsToFrameForFollowingNearManeuver`.

The use case would be adding POI for navigation context to the maneuver framing. For instance, adding the POI for a large store to use in addition to the street name for determining where to turn.
