### ISSUE TITLE
Run linter for each contribution

### ISSUE THREAD

**Issue by LukasPaczos** [mapbox/mapbox-navigation-android#4085]
This ticket tracks integrating a custom set of lint rules and executing them for each contribution. Refs https://developer.android.com/studio/write/lint.

/cc @mapbox/navigation-android

**Comment by RingerJK** [comment]
As a part of work, we can add a pre-commit hook: as [an instance for ktlint](https://medium.com/@alistair.cerio/android-ktlint-and-pre-commit-git-hook-5dd606e230a9)

**Comment by zugaldia** [comment]
Do we still need to consider this ticket a release blocking issue?

**Comment by LukasPaczos** [comment]
Yes. We currently package a lot of unused resources which should be removed, preferably before RC but can also be a target for GA.

**Comment by truburt** [comment]
The remaining part is to automate and move it to CI.
