### ISSUE TITLE
Indoor maps

### ISSUE THREAD

**Issue by chanduram** [mapbox/mapbox-navigation-android#410]
can i use this for indoor maps navigation.

**Comment by danesfeder** [comment]
Hey @chanduram, 
If you're using our core navigation library `libandroid-navigation`, you are able to use any style map you'd like using our Maps SDK https://www.mapbox.com/android-docs/map-sdk/overview/styling-map/.

If you're talking about our "drop-in UI", we are currently setting these map styles and don't offer the ability to provide your own style.  Stay tuned though, as we are looking to offer this functionality in the near future.

**Comment by cammace** [comment]
Nothing actionable here, closing.
