### ISSUE TITLE
Duplicate class error

### ISSUE THREAD

**Issue by ShalevCohen2112** [mapbox/mapbox-navigation-android#4103]
I need to use both the navigation and the search libraries and i receive an error while building the application

this is my implementation :
implementation "com.mapbox.navigation:ui:1.1.0"
implementation "com.mapbox.search:mapbox-search-android:1.0.0-beta.1"

this is the error:

Duplicate class com.mapbox.bindgen.ArrayUtils found in modules jetified-common-7.1.0-runtime (com.mapbox.common:common:7.1.0) and jetified-support-2.0 (com.mapbox.bindgen:support:2.0.0)
Duplicate class com.mapbox.bindgen.Expected found in modules jetified-common-7.1.0-runtime (com.mapbox.common:common:7.1.0) and jetified-support-2.0 (com.mapbox.bindgen:support:2.0.0)
Duplicate class com.mapbox.bindgen.ExpectedFactory found in modules jetified-common-7.1.0-runtime (com.mapbox.common:common:7.1.0) and jetified-support-2.0 (com.mapbox.bindgen:support:2.0.0)
Duplicate class com.mapbox.bindgen.HashMapKeyValueExtractor found in modules jetified-common-7.1.0-runtime (com.mapbox.common:common:7.1.0) and jetified-support-2.0 (com.mapbox.bindgen:support:2.0.0)
Duplicate class com.mapbox.bindgen.RecordUtils found in modules jetified-common-7.1.0-runtime (com.mapbox.common:common:7.1.0) and jetified-support-2.0 (com.mapbox.bindgen:support:2.0.0)
Duplicate class com.mapbox.bindgen.Size found in modules jetified-common-7.1.0-runtime (com.mapbox.common:common:7.1.0) and jetified-support-2.0 (com.mapbox.bindgen:support:2.0.0)
Duplicate class com.mapbox.bindgen.Value found in modules jetified-common-7.1.0-runtime (com.mapbox.common:common:7.1.0) and jetified-support-2.0 (com.mapbox.bindgen:support:2.0.0)

**Comment by LukasPaczos** [comment]
Hey @ShalevCohen2112, thanks for reaching out. This issue has been resolved, please upgrade your Navigation SDK and Search SDK dependencies to the latest.
