### ISSUE TITLE
NavigationRoute always retrieves driving-traffic profile

### ISSUE THREAD

**Issue by danesfeder** [mapbox/mapbox-navigation-android#411]
`.build()` in `NavigationRoute` will always set the profile for the directions request to `this.directionsBuilder.profile("driving-traffic");` - currently not able to fetch walking or biking directions.  

This was an oversight on my part making congestion changes. 

cc @ericrwolfe

**Comment by cammace** [comment]
I'll go ahead and fix this one up

**Comment by cammace** [comment]
Should have fixed this in https://github.com/mapbox/mapbox-navigation-android/pull/413
