### ISSUE TITLE
Investigate default rounding increment for MabpboxNavigation/DistanceFormatterOptions

### ISSUE THREAD

**Issue by cafesilencio** [mapbox/mapbox-navigation-android#4168]
As a follow up to https://github.com/mapbox/mapbox-navigation-android/issues/3982 and https://github.com/mapbox/mapbox-navigation-android/pull/4152 which made some changes to the shared distance formatter and also to trip progress so that the minimum distance displayed is either 5ft or 2m, some investigation should be done as to whether MabpboxNavigation/DistanceFormatterOptions should default to 5 or 2 for the rounding increment.  Currently it defaults to 50.

Since MabpboxNavigation is widely used it's unclear what side effects might occur by changing the rounding increment from 50 to some other value as a default.

Other components that are using the shared distance formatter may also need to configure themselves to use a rounding increment of 5 or 2 as a default.

**Comment by 1ec5** [comment]
On iOS, the rounding increment depends on the unit. That way optimizing the usability of a small-scale unit near a maneuver (not just an arrival maneuver) doesn’t adversely impact the usability of a large-scale unit away from a maneuver. We don’t want to distract users with overly precise distances, but we also want to provide more granularity than “0”.

https://github.com/mapbox/mapbox-navigation-ios/blob/dfee822d0fac24098371a3888503e5d00844e7cb/Sources/MapboxCoreNavigation/DistanceFormatter.swift#L28-L49

**Comment by kmadsen** [comment]
We also need a way to expose the rounding logic used, downstream.

https://android.googlesource.com/platform/frameworks/support/+/refs/heads/androidx-main/car/app/app/src/main/java/androidx/car/app/model/Distance.java#125
``` java
 * @param displayDistance the distance to display, in the units specified in {@code
 *                        displayUnit}. See {@link #getDisplayDistance()}
 * @param displayUnit     the unit of distance to use when displaying the value in {@code
 *                        displayUnit}. This should be one of the {@code UNIT_*} static
 *                        constants defined in this class. See {@link #getDisplayUnit()}
 * @throws IllegalArgumentException if {@code displayDistance} is negative
 */
@NonNull
public static Distance create(double displayDistance, @Unit int displayUnit)
```

**Comment by abhishek1508** [comment]
Closing this in favor of https://github.com/mapbox/mapbox-navigation-android/issues/5065
