### ISSUE TITLE
Reroute never appears if currentstep has only one geometry point

### ISSUE THREAD

**Issue by palto-ccadoret** [mapbox/mapbox-navigation-android#417]
Reroute never appears if current step has only one geometry point.

`https://github.com/mapbox/mapbox-navigation-android/blob/79c9c4e023e04e8076d980872de7383c353ed89b/libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/offroute/OffRouteDetector.java#L119`

TurfMisc.pointOnLine returns a point with infinity coordinates {type='Point', coordinates=Position [longitude=Infinity, latitude=Infinity, altitude=NaN]}

It leads to a NaN value for the computation of the distance. --> Reroute not detected

You could compute the distance between futurPosition and the geometry point in case of only one geometry point exists.

**Comment by palto-blubek** [comment]
It's hard to know if this issue is resolved, as it has a milestone of 0.7.1, which has been released.  Any idea?

**Comment by cammace** [comment]
[This PR](https://github.com/mapbox/mapbox-navigation-android/pull/422) adds code that specifically checks for this issue. Looking to get this merged today which should resolve the issue.
