### ISSUE TITLE
Cannot compile the test App

### ISSUE THREAD

**Issue by vincent-caron** [mapbox/mapbox-navigation-android#4186]
Hello,

I've downloaded the demo app to try the new SDK.

I've created my secret key and my key on the site.
I've put the secret key in the gradle.properties files.

But it always give me this error :

19:17	Gradle sync failed: Could not GET 'https://api.mapbox.com/downloads/v2/releases/maven/com/mapbox/gradle/plugins/sdk-registry/0.4.0/sdk-registry-0.4.0.pom'. Received status code 401 from server: Unauthorized
			Consult IDE log for more details (Help | Show Log) (4 s 694 ms)

I've tried to move the gradle.properties file around, but no luck.

Can you help me ?

Thanks 

Vincent

**Comment by LukasPaczos** [comment]
hey @vincent-caron, does your secret key have the `DOWNLOADS:READ` scope?

**Comment by vincent-caron** [comment]
@LukasPaczos , i've followed the installation on mapbox site step by step.
It means that the option DOWNLOADS:READ is checked.

I've tried also with all the options checked without success.

I'm on windows 10. I've put the secret key in the $USER_HOME/.gradle/gradle.properties file. No success also.

May there is something i'm missing. 

Thanks

**Comment by kasoleg** [comment]
I have the same problem in examples:
```
> Configure project :
Navigation Native version: 47.0.0

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'mapbox-navigation-android'.
> Could not resolve all artifacts for configuration ':classpath'.
   > Could not resolve com.mapbox.gradle.plugins:sdk-registry:0.4.0.
     Required by:
         project :
      > Could not resolve com.mapbox.gradle.plugins:sdk-registry:0.4.0.
         > Could not get resource 'https://api.mapbox.com/downloads/v2/releases/maven/com/mapbox/gradle/plugins/sdk-registry/0.4.0/sdk-registry-0.4.0.pom'.
            > Could not GET 'https://api.mapbox.com/downloads/v2/releases/maven/com/mapbox/gradle/plugins/sdk-registry/0.4.0/sdk-registry-0.4.0.pom'. Received status code 401 from server: Unauthorized
   > Could not resolve com.mapbox.gradle.plugins:access-token:0.2.1.
     Required by:
         project :
      > Could not resolve com.mapbox.gradle.plugins:access-token:0.2.1.
         > Could not get resource 'https://api.mapbox.com/downloads/v2/releases/maven/com/mapbox/gradle/plugins/access-token/0.2.1/access-token-0.2.1.pom'.
            > Could not GET 'https://api.mapbox.com/downloads/v2/releases/maven/com/mapbox/gradle/plugins/access-token/0.2.1/access-token-0.2.1.pom'. Received status code 401 from server: Unauthorized
   > Could not resolve com.mapbox.gradle.plugins:native-download:0.1.2.
     Required by:
         project :
      > Could not resolve com.mapbox.gradle.plugins:native-download:0.1.2.
         > Could not get resource 'https://api.mapbox.com/downloads/v2/releases/maven/com/mapbox/gradle/plugins/native-download/0.1.2/native-download-0.1.2.pom'.
            > Could not GET 'https://api.mapbox.com/downloads/v2/releases/maven/com/mapbox/gradle/plugins/native-download/0.1.2/native-download-0.1.2.pom'. Received status code 401 from server: Unauthorized

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
```
I've created token with DOWNLOADS:READ scope and put the secret key in gradle.properties as SDK_REGISTRY_TOKEN=secret_token
I've tried to put it in env variable.
Can you help me run examples, please?

**Comment by LukasPaczos** [comment]
@vincent-caron @kasoleg what if you put the token value inside of the project, in the `mapbox-navigation-android/gradle.properties` file or simply directly in https://github.com/mapbox/mapbox-navigation-android/blob/e19a2ad09aef3e4399fa9b9daba41b23634dd82d/build.gradle#L15 and https://github.com/mapbox/mapbox-navigation-android/blob/e19a2ad09aef3e4399fa9b9daba41b23634dd82d/build.gradle#L57? I'm trying to understand whether this is env issue or a project issue.

**Comment by vincent-caron** [comment]
i've solved my problem. 

In the official documentation of android navigation on the mapbox site, you have this : (installation part)

MAPBOX_DOWNLOADS_TOKEN=PASTE_YOUR_SECRET_TOKEN_HERE

That is not the good key to retrieve from the gradle.properties file.

So, it's the official documentation who is wrong or the example.

Vincent

**Comment by LukasPaczos** [comment]
This issue should now be resolved and you should be able to build the project without any modifications to the scripts.
