### ISSUE TITLE
Reroute causes infinite loop of departure announcements

### ISSUE THREAD

**Issue by ericrwolfe** [mapbox/mapbox-navigation-android#419]
Driving with the current test app works fine until a reroute occurs, then the app starts an infinite loop of audio announcements for the departure step: "Head north on CA-1", "Head north on CA-1", etc.

This same announcement continues to repeat even as you drive through multiple steps. Even if the app reroutes again, the app repeats the original announcement. The rest of the app functionality (banners) is unaffected by the bug, and you can continue to drive with the app on mute.

Steps to reproduce:
* Start a real drive
* Turn off route
* Listen for duplicate departure announcements

cc @cammace @danesfeder

**Comment by cammace** [comment]
Since nothing else gets affected but the voice announcements, this sounds like it is coming from the `ApiMilestone` class.

**Comment by ericrwolfe** [comment]
@cammace I do think @danesfeder enabled polly in my test build, so this should be easily reproduceable by adding a poolId to the test app and running the reroute activity.
