### ISSUE TITLE
Notification and MapboxManeuverView icons are different 

### ISSUE THREAD

**Issue by Guardiola31337** [mapbox/mapbox-navigation-android#4193]
Noticed that maneuver icons from the notification are different from the maneuver view ones 👀 

![maneuver_icons_different](https://user-images.githubusercontent.com/1668582/112860433-cf6adc80-9081-11eb-9aaf-520e361c8ab1.png)

![maneuver_icons_different_notification](https://user-images.githubusercontent.com/1668582/112860451-d2fe6380-9081-11eb-83a4-c5e175c7f162.png)

Noting that they used to be the same as we were drawing them at runtime in `1.x`.

cc @d-prukop @abhishek1508

**Comment by LukasPaczos** [comment]
Additional context in https://github.com/mapbox/mapbox-navigation-android/issues/4513.
