### ISSUE TITLE
Expose Extrusion building

### ISSUE THREAD

**Issue by RingerJK** [mapbox/mapbox-navigation-android#4196]
Nav SDK should provide if a building was highlighted or not.

Currently it's only assign `Expression` `id="0"` if a building is not found 
https://github.com/mapbox/mapbox-navigation-android/blob/dda24eabff393c89c7f6695db456aaaef2bb0870/libnavigation-ui/src/main/java/com/mapbox/navigation/ui/map/building/BuildingLayerSupport.kt#L51-L65
https://github.com/mapbox/mapbox-navigation-android/blob/dda24eabff393c89c7f6695db456aaaef2bb0870/libnavigation-ui/src/main/java/com/mapbox/navigation/ui/map/building/BuildingLayerSupport.kt#L86

cc @friendoye

**Comment by kmadsen** [comment]
I tried this over here https://github.com/mapbox/mapbox-navigation-android/pull/4078

But it's hard to figure out what exactly is wrong with the filter expression `.filter(eq(id(), string(literal(features)))`
The feature id is there, but it does not work

``` kotlin
private fun selectBuilding(point: Point) {
    mapboxMap.getStyle { style ->
        val screenCoordinate = mapboxMap.pixelForCoordinate(point)
        val queryOptions = RenderedQueryOptions(listOf("building"), null)

        mapboxMap.queryRenderedFeatures(screenCoordinate, queryOptions) { expected ->
            val queriedFeature: List<QueriedFeature> = expected.value ?: emptyList()
            if (queriedFeature.isNotEmpty()) {
                
                val layerId = "mapbox-building-highlight-layer"
                val features = queriedFeature.map { it.feature.id() }.firstOrNull() ?: "0"
                if (!style.styleLayerExists(layerId)) {
                    style.addLayer(
                        FillExtrusionLayer(layerId, "composite")
                            .sourceLayer("building")
                            .filter(eq(id(), string(literal(features)))) // Works without this line
                            .fillExtrusionColor(options.fillExtrusionColor)
                            .fillExtrusionOpacity(options.fillExtrusionOpacity)
                            .fillExtrusionBase(get("min-height"))
                            .fillExtrusionHeight(heightExpression())
                    )
                }
            }
        }
    }
}
```

**Comment by kmadsen** [comment]
Selecting the building is all working https://github.com/mapbox/mapbox-navigation-android/pull/4327

Have a couple ideas of what we could do here. @RingerJK is this ticket completed? Or is this asking for an update to one or more public interfaces?

**Comment by kmadsen** [comment]
https://github.com/mapbox/mapbox-maps-android/issues/235

Asking maps teams if they would provide a MapBuilding object that we could surface.

**Comment by kmadsen** [comment]
Here's a pull request that is looking to address this issue https://github.com/mapbox/mapbox-navigation-android/pull/4420

**Comment by kmadsen** [comment]
Considering this completed by https://github.com/mapbox/mapbox-navigation-android/pull/4420
