### ISSUE TITLE
Route line should support decoding from precision 5

### ISSUE THREAD

**Issue by LukasPaczos** [mapbox/mapbox-navigation-android#4231]
Refs https://github.com/mapbox/mapbox-navigation-android/blob/380c8cb2322b146460512a703e9fb8974bbd5e33/libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/internal/route/line/MapboxRouteLineUtils.kt#L503 and all the other places in the `RouteLineApi`. The API currently only supports routes that were encoded with precision 6, while it should support both precision 5 and precision 6.

**Comment by cafesilencio** [comment]
This issue has already been resolved. Closing.
