### ISSUE TITLE
Coalesce RouteLineApi draw calls

### ISSUE THREAD

**Issue by LukasPaczos** [mapbox/mapbox-navigation-android#4232]
Refs https://github.com/mapbox/mapbox-navigation-android/pull/4106#discussion_r603395707.

This tracks improvement to the `RouteLineApi` to cancel the ongoing job if a new one is scheduled as they currently run in the queue and wait for completion.

**Comment by cafesilencio** [comment]
Cancelling wasn't consistently reliable in my testing. I think we should first explore the actor strategy outlined in the kotlin documentation.  https://kotlinlang.org/docs/shared-mutable-state-and-concurrency.html#actors

**Comment by LukasPaczos** [comment]
I still think this is a worthy optimization. If there are multiple routes scheduled to be processed, and we already know that only one (the last) will persist, there's no reason to parse every route in-between. We should incorporate a coalescing model where the only the current (so that we don't starve the queue) and last route processing jobs run to completion, canceling everything in-between.

**Comment by cafesilencio** [comment]
Currently (on my device) a call to `setRoutes` with a primary and alternative routes across the U.S. takes 61ms.  That's an extreme case so real world routes take much less time.  I added a call to `cancel()` to the `setRoutes` method but I don't think adding more complexity in the form of a queuing system has any real world advantages.  Fetching routes takes much longer than the call to 'setRoutes'.

**Comment by cafesilencio** [comment]
Closing this as a result of the merge here: https://github.com/mapbox/mapbox-navigation-android/pull/5336
