### ISSUE TITLE
RoutesRequestCallback not triggered if there is no connection

### ISSUE THREAD

**Issue by awoisoak** [mapbox/mapbox-navigation-android#4234]
**Android API:** 11
**Mapbox Navigation SDK version:** core:2.0.0-SNAPSHOT

### Steps to trigger behavior

 1. Set airplane mode to make sure no connection is available
 2. Request a route (make sure is not cached by the SDK) with `mapboxNavigation#requestRoutes` passing a `RoutesRequestCallback`

### Expected behavior
`RoutesRequestCallback#onRoutesRequestFailure` is called as the route could not be calculated.

### Actual behavior
None of `RoutesRequestCallback` methods is triggered (neither any exception is thrown by `mapboxNavigation#requestRoutes`)  so there is no way to know the request failed.

**Comment by LukasPaczos** [comment]
Hey @awoisoak, I'm unable to reproduce using `2.0.0-beta.6`, could you retry on that latest version?

**Comment by awoisoak** [comment]
@LukasPaczos  I just checked last version and it works as expected now (`onRoutesRequestFailure` is called), thanks!

**Comment by LukasPaczos** [comment]
Great to hear!
