### ISSUE TITLE
Status Code 403 : Forbidden

### ISSUE THREAD

**Issue by sohail-niazi** [mapbox/mapbox-navigation-android#4255]
Hi, I am using mapbox sdk in android for over a year now. But today suddenly my project start fail on build. It shows forbidden on all libraries involved in mapbox sdk. Following is the error: 

> Could not determine the dependencies of task ':app:compileDebugAidl'.
> Could not resolve all task dependencies for configuration ':app:debugCompileClasspath'.
   > Could not resolve com.mapbox.vision:mapbox-android-vision:0.13.0.
     Required by:
         project :app
      > Could not resolve com.mapbox.vision:mapbox-android-vision:0.13.0.
         > Could not get resource 'https://api.mapbox.com/downloads/v1/navigation/android/maven/com/mapbox/vision/mapbox-android-vision/0.13.0/mapbox-android-vision-0.13.0.pom'.
            > Could not GET 'https://api.mapbox.com/downloads/v1/navigation/android/maven/com/mapbox/vision/mapbox-android-vision/0.13.0/mapbox-android-vision-0.13.0.pom'. Received status code 403 from server: Forbidden
      > Could not resolve com.mapbox.vision:mapbox-android-vision:0.13.0.
         > Could not get resource 'https://mapbox.bintray.com/mapbox/com/mapbox/vision/mapbox-android-vision/0.13.0/mapbox-android-vision-0.13.0.pom'.
            > Could not GET 'https://mapbox.bintray.com/mapbox/com/mapbox/vision/mapbox-android-vision/0.13.0/mapbox-android-vision-0.13.0.pom'. Received status code 403 from server: Forbidden
   > Could not resolve com.mapbox.vision:mapbox-android-vision-ar:0.13.0.
     Required by:
         project :app
      > Could not resolve com.mapbox.vision:mapbox-android-vision-ar:0.13.0.
         > Could not get resource 'https://api.mapbox.com/downloads/v1/navigation/android/maven/com/mapbox/vision/mapbox-android-vision-ar/0.13.0/mapbox-android-vision-ar-0.13.0.pom'.
            > Could not GET 'https://api.mapbox.com/downloads/v1/navigation/android/maven/com/mapbox/vision/mapbox-android-vision-ar/0.13.0/mapbox-android-vision-ar-0.13.0.pom'. Received status code 403 from server: Forbidden
      > Could not resolve com.mapbox.vision:mapbox-android-vision-ar:0.13.0.
         > Could not get resource 'https://mapbox.bintray.com/mapbox/com/mapbox/vision/mapbox-android-vision-ar/0.13.0/mapbox-android-vision-ar-0.13.0.pom'.
            > Could not GET 'https://mapbox.bintray.com/mapbox/com/mapbox/vision/mapbox-android-vision-ar/0.13.0/mapbox-android-vision-ar-0.13.0.pom'. Received status code 403 from server: Forbidden
   > Could not resolve com.google.android.gms:play-services-basement:[15.0.1,16.0.0).
     Required by:
         project :app > com.google.android.gms:play-services-vision:15.0.2
         project :app > com.google.android.gms:play-services-maps:15.0.1
         project :app > com.google.android.gms:play-services-location:15.0.1
         project :app > com.google.android.gms:play-services-vision-common:15.0.2
         project :app > com.google.android.gms:play-services-places-placereport:15.0.1
         project :app > com.google.android.gms:play-services-clearcut:15.0.1
         project :app > com.google.android.gms:play-services-phenotype:15.0.1
      > Failed to list versions for com.google.android.gms:play-services-basement.
         > Unable to load Maven meta-data from https://api.mapbox.com/downloads/v1/navigation/android/maven/com/google/android/gms/play-services-basement/maven-metadata.xml.
            > Could not get resource 'https://api.mapbox.com/downloads/v1/navigation/android/maven/com/google/android/gms/play-services-basement/maven-metadata.xml'.
               > Could not GET 'https://api.mapbox.com/downloads/v1/navigation/android/maven/com/google/android/gms/play-services-basement/maven-metadata.xml'. Received status code 403 from server: Forbidden
      > Failed to list versions for com.google.android.gms:play-services-basement.
         > Unable to load Maven meta-data from https://mapbox.bintray.com/mapbox/com/google/android/gms/play-services-basement/maven-metadata.xml.
            > Could not get resource 'https://mapbox.bintray.com/mapbox/com/google/android/gms/play-services-basement/maven-metadata.xml'.
               > Could not GET 'https://mapbox.bintray.com/mapbox/com/google/android/gms/play-services-basement/maven-metadata.xml'. Received status code 403 from server: Forbidden
   > Could not resolve com.google.android.gms:play-services-tasks:[15.0.1,16.0.0).
     Required by:
         project :app > com.google.android.gms:play-services-location:15.0.1
         project :app > com.google.android.gms:play-services-clearcut:15.0.1
         project :app > com.google.android.gms:play-services-phenotype:15.0.1
      > Failed to list versions for com.google.android.gms:play-services-tasks.
         > Unable to load Maven meta-data from https://api.mapbox.com/downloads/v1/navigation/android/maven/com/google/android/gms/play-services-tasks/maven-metadata.xml.
            > Could not get resource 'https://api.mapbox.com/downloads/v1/navigation/android/maven/com/google/android/gms/play-services-tasks/maven-metadata.xml'.
               > Could not GET 'https://api.mapbox.com/downloads/v1/navigation/android/maven/com/google/android/gms/play-services-tasks/maven-metadata.xml'. Received status code 403 from server: Forbidden
      > Failed to list versions for com.google.android.gms:play-services-tasks.
         > Unable to load Maven meta-data from https://mapbox.bintray.com/mapbox/com/google/android/gms/play-services-tasks/maven-metadata.xml.
            > Could not get resource 'https://mapbox.bintray.com/mapbox/com/google/android/gms/play-services-tasks/maven-metadata.xml'.
               > Could not GET 'https://mapbox.bintray.com/mapbox/com/google/android/gms/play-services-tasks/maven-metadata.xml'. Received status code 403 from server: Forbidden
   > Could not resolve com.google.android.gms:play-services-ads-identifier:[15.0.0, 16.0.99].
     Required by:
         project :app > com.onesignal:OneSignal:3.13.0
      > Failed to list versions for com.google.android.gms:play-services-ads-identifier.
         > Unable to load Maven meta-data from https://api.mapbox.com/downloads/v1/navigation/android/maven/com/google/android/gms/play-services-ads-identifier/maven-metadata.xml.
            > Could not get resource 'https://api.mapbox.com/downloads/v1/navigation/android/maven/com/google/android/gms/play-services-ads-identifier/maven-metadata.xml'.
               > Could not GET 'https://api.mapbox.com/downloads/v1/navigation/android/maven/com/google/android/gms/play-services-ads-identifier/maven-metadata.xml'. Received status code 403 from server: Forbidden
      > Failed to list versions for com.google.android.gms:play-services-ads-identifier.
         > Unable to load Maven meta-data from https://mapbox.bintray.com/mapbox/com/google/android/gms/play-services-ads-identifier/maven-metadata.xml.
            > Could not get resource 'https://mapbox.bintray.com/mapbox/com/google/android/gms/play-services-ads-identifier/maven-metadata.xml'.
               > Could not GET 'https://mapbox.bintray.com/mapbox/com/google/android/gms/play-services-ads-identifier/maven-metadata.xml'. Received status code 403 from server: Forbidden
   > Could not resolve com.google.android.gms:play-services-basement:[15.0.1].
     Required by:
         project :app > com.google.android.gms:play-services-flags:15.0.1
      > Failed to list versions for com.google.android.gms:play-services-basement.
         > Unable to load Maven meta-data from https://api.mapbox.com/downloads/v1/navigation/android/maven/com/google/android/gms/play-services-basement/maven-metadata.xml.
            > Could not get resource 'https://api.mapbox.com/downloads/v1/navigation/android/maven/com/google/android/gms/play-services-basement/maven-metadata.xml'.
               > Could not GET 'https://api.mapbox.com/downloads/v1/navigation/android/maven/com/google/android/gms/play-services-basement/maven-metadata.xml'. Received status code 403 from server: Forbidden
      > Failed to list versions for com.google.android.gms:play-services-basement.
         > Unable to load Maven meta-data from https://mapbox.bintray.com/mapbox/com/google/android/gms/play-services-basement/maven-metadata.xml.
            > Could not get resource 'https://mapbox.bintray.com/mapbox/com/google/android/gms/play-services-basement/maven-metadata.xml'.
               > Could not GET 'https://mapbox.bintray.com/mapbox/com/google/android/gms/play-services-basement/maven-metadata.xml'. Received status code 403 from server: Forbidden
               
I am using following code in files

project/build.gradle:

`allprojects {
    repositories {
        maven { url "http://dl.bintray.com/populov/maven" }
        mavenCentral()
        jcenter()
        maven {
            url 'https://maven.google.com/'
            name 'Google'
        }
        maven { url 'https://jitpack.io' }
        google()

        maven {
            url 'https://api.mapbox.com/downloads/v1/vision/android/maven'
            authentication {
                basic(BasicAuthentication)
            }
            credentials {
                username project.properties['mapboxMavenUser'] ?: ""
                password project.properties['mapboxMavenToken'] ?: ""
            }
        }
    }
}`

Android follwing are the mapbox dependencies I am using:

   ` implementation 'com.mapbox.mapboxsdk:mapbox-android-sdk:9.2.0'
    implementation 'com.mapbox.mapboxsdk:mapbox-android-navigation:0.42.6'
    implementation 'com.mapbox.mapboxsdk:mapbox-android-navigation-ui:0.42.6'
    implementation 'com.mapbox.mapboxsdk:mapbox-android-plugin-building-v9:0.7.0'
    implementation "com.mapbox.vision:mapbox-android-vision:0.13.0"
    implementation "com.mapbox.vision:mapbox-android-vision-ar:0.13.0"
    implementation "com.mapbox.mapboxsdk:mapbox-android-core:1.3.0"`

**Comment by LukasPaczos** [comment]
Hey @sohail-niazi, this is probably due to the Bintray sunsetting and scheduled brownouts - https://status.bintray.com/incidents/4mzph0y8l6hk.

All of the actively maintained versions of the Mapbox SDKs have been migrated to Mapbox's maven repository, you can read more about the necessary configuration, for example, in the [Navigation SDK documentation](https://docs.mapbox.com/android/navigation/guides/install/). You're still using Navigation SDK `0.42.6` which is hosted on Maven Central, but also not actively supported, so we recommend upgrading.

That said, in your situation, the culprit seems to be the `mapbox-android-vision:0.13.0` which is still backed by Bintray. @mapbox/vision-mobile do we have a plan to move the Vision artifacts to Mapbox's service and the `downloads/v2` APIs?

**Comment by AliAkberAakash** [comment]
I'm getting the same response with MapBox Navigation UI SDK. here is my gradle :
`allprojects {
    repositories {
        google()
        jcenter()
        mavenCentral()

        maven {
            url 'https://api.mapbox.com/downloads/v2/releases/maven'
            authentication {
                basic(BasicAuthentication)
            }
            credentials {
                // Do not change the username below.
                // This should always be `mapbox` (not your username).
                username = 'mapbox'
                // Use the secret token you stored in gradle.properties as the password
                password = "my secret key"
                       
            }
        }
    }
}`

I put my secret key directly to check if there was some problem reading it from environment variable.

**Comment by sohail-niazi** [comment]
Thanks for reply, After I updated my google gms libraries to latest version, this issue was gone. And now it also works fine with old versions. I will update my mapbox dependencies. Thanks again

**Comment by LukasPaczos** [comment]
@AliAkberAakash does your secret token have the `DOWNLOADS:READ` scope enabled?

**Comment by AliAkberAakash** [comment]
I cant find a DOWNLOADS:READ option whenI'm trying to edit the key, I have dataset, styles, fonts, vision all set to read.

**Comment by AliAkberAakash** [comment]
I have created a new token, this time I enabled the DOWNLOADS:READ scope. but now I'm facing another issue. I cant copy it from my dashboard, I only see "Secret Token" written where the token should be.

**Comment by AliAkberAakash** [comment]
I was able to solve it thanks! I didn't know I can only copy the token once.

**Comment by LukasPaczos** [comment]
Glad that it works for you now!

**Comment by sohail-niazi** [comment]
@LukasPaczos I just downloaded android studio in new laptop and started receiving this error again. My Mapbox Key is valid and there is no code change...

```

> Could not resolve all task dependencies for configuration ':app:debugCompileClasspath'.
   > Could not resolve com.mapbox.vision:mapbox-android-vision:0.13.0.
     Required by:
         project :app
      > Could not resolve com.mapbox.vision:mapbox-android-vision:0.13.0.
         > Could not get resource 'https://api.mapbox.com/downloads/v1/vision/android/maven/com/mapbox/vision/mapbox-android-vision/0.13.0/mapbox-android-vision-0.13.0.pom'.
            > Could not GET 'https://api.mapbox.com/downloads/v1/vision/android/maven/com/mapbox/vision/mapbox-android-vision/0.13.0/mapbox-android-vision-0.13.0.pom'. Received status code 403 from server: Forbidden
      > Could not resolve com.mapbox.vision:mapbox-android-vision:0.13.0.
         > Could not get resource 'https://mapbox.bintray.com/mapbox/com/mapbox/vision/mapbox-android-vision/0.13.0/mapbox-android-vision-0.13.0.pom'.
            > Could not GET 'https://mapbox.bintray.com/mapbox/com/mapbox/vision/mapbox-android-vision/0.13.0/mapbox-android-vision-0.13.0.pom'. Received status code 403 from server: Forbidden
   > Could not resolve com.mapbox.vision:mapbox-android-vision-ar:0.13.0.
     Required by:
         project :app
      > Could not resolve com.mapbox.vision:mapbox-android-vision-ar:0.13.0.
         > Could not get resource 'https://api.mapbox.com/downloads/v1/vision/android/maven/com/mapbox/vision/mapbox-android-vision-ar/0.13.0/mapbox-android-vision-ar-0.13.0.pom'.
            > Could not GET 'https://api.mapbox.com/downloads/v1/vision/android/maven/com/mapbox/vision/mapbox-android-vision-ar/0.13.0/mapbox-android-vision-ar-0.13.0.pom'. Received status code 403 from server: Forbidden
      > Could not resolve com.mapbox.vision:mapbox-android-vision-ar:0.13.0.
         > Could not get resource 'https://mapbox.bintray.com/mapbox/com/mapbox/vision/mapbox-android-vision-ar/0.13.0/mapbox-android-vision-ar-0.13.0.pom'.
            > Could not GET 'https://mapbox.bintray.com/mapbox/com/mapbox/vision/mapbox-android-vision-ar/0.13.0/mapbox-android-vision-ar-0.13.0.pom'. Received status code 403 from server: Forbidden
   > Could not resolve com.mapbox.navigator:mapbox-navigation-native:7.0.0.
     Required by:
         project :app > com.mapbox.mapboxsdk:mapbox-android-navigation:0.42.6
      > Could not resolve com.mapbox.navigator:mapbox-navigation-native:7.0.0.
         > Could not get resource 'https://mapbox.bintray.com/mapbox/com/mapbox/navigator/mapbox-navigation-native/7.0.0/mapbox-navigation-native-7.0.0.pom'.
            > Could not GET 'https://mapbox.bintray.com/mapbox/com/mapbox/navigator/mapbox-navigation-native/7.0.0/mapbox-navigation-native-7.0.0.pom'. Received status code 403 from server: Forbidden
 

```

**Comment by zenyagami** [comment]
I still have the same issue with 
```
Could not HEAD 'https://mapbox.bintray.com/mapbox/com/mapbox/base/common/0.5.0/common-0.5.0.aar'. Received status code 403 from server: Forbidden
```
I created several tokens with the download option and does not work
any way to fix this?

**Comment by jyotykumari63** [comment]
> I have created a new token, this time I enabled the DOWNLOADS:READ scope. but now I'm facing another issue. I cant copy it from my dashboard, I only see "Secret Token" written where the token should be.

It worked for me!
