### ISSUE TITLE
VoiceInstructions with wrong unit

### ISSUE THREAD

**Issue by P-Zenker** [mapbox/mapbox-navigation-android#426]
Hey,

if I use the LegStep.voiceInstructions there is one issue:
`VoiceInstructions{distanceAlongGeometry=176.4, announcement=In 600 Fuß, leicht links abbiegen auf An der Untertrave, ssmlAnnouncement=...`

The distanceAlongGeometry is in meter, but the voice instruction in feed ("Fuß"). 

I don't know if it is a issue or not, but do you need the comma after the unit for a correct spoken voice instruction? If not it could be used directly as a text instruction too (in german there is no comma after the unit). Otherwise I just escape this char.

**Comment by danesfeder** [comment]
Added in #500, the `voiceUnit` param in the request should properly fix thishttps://github.com/mapbox/mapbox-navigation-android/blob/master/libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/NavigationRoute.java#L368
