### ISSUE TITLE
Maneuver directions incorrect

### ISSUE THREAD

**Issue by sandyscoffable** [mapbox/mapbox-navigation-android#4270]
**Android API:** 30
**Mapbox Navigation SDK version:** 2.0.0-beta.5

### Steps to trigger behavior

 1. Clone this project (I'm using commit: a773c3833fa037bd3b64b33b5df34a524b9e4658 )
 1. Fix up the `example` app in this project (this involves about an hour of faff sorting out build/gradle problems etc as there is no top level `build.gradle`). Activity code should be unchanged.
 1. Choose "Turn by Turn navigation"
 1. Plot a route around a roundabout

### Expected behavior

The turn icon should represent the maneuver that's about to be made

### Actual behavior

The icon is incorrect, e.g (from the app that I'm developing)
<img src="https://user-images.githubusercontent.com/20515901/114885483-97dc8e00-9dfe-11eb-984c-ecf390c70f0f.png" width="320" />

It's telling me to go hard right instead of left.

Here is a video of it happening in the mapbox demo app:
https://drive.google.com/file/d/1V2PLxOXc6ZTQXleAgbP9eIt4-d_DxrWI/view?usp=sharing

**Comment by sandyscoffable** [comment]
I expect this is an issue like "you drive on the left", or "you're in the northern hemisphere". 

However, I would expect the Mapbox SDK to figure this out for me though as it knows where I am.

**Comment by Guardiola31337** [comment]
@abhishek1508 could you take a look into this when you have a chance? 🙏

**Comment by abhishek1508** [comment]
Roundabout angles are a known issue and we are working on it.

cc @kshehadeh @jyrigo @Guardiola31337 @sandyscoffable

**Comment by sandyscoffable** [comment]
Thanks 👍

**Comment by Guardiola31337** [comment]
Hey @sandyscoffable thanks for reaching out and report your issue.

Could you share your requests setup / `RouteOptions` you're adding and the `DirectionsRoute`s that you get / use when you have a chance?

**Comment by sandyscoffable** [comment]
RouteOptions:

```kotlin
// "driving-traffic" profile only permitted for up to 3 waypoints ... Mapbox limitation
val profile = if (mapWaypoints.size > 3) {
    DirectionsCriteria.PROFILE_DRIVING
} else {
    DirectionsCriteria.PROFILE_DRIVING_TRAFFIC
}

MapboxNavigationProvider.retrieve().requestRoutes(
    routeOptions = RouteOptions.builder()
        .applyDefaultParams()
        .accessToken(getString(R.string.mapbox_access_token))
        .coordinates(mapWaypoints)
        .alternatives(false)
        .profile(profile)
        .build()
```

The mapWaypoints for the route in the above test are:
```json
[
{"type":"Point","coordinates":[-3.6292705,55.9777849]}, 
{"type":"Point","coordinates":[-3.623885,55.970025]}, 
{"type":"Point","coordinates":[-3.604824,55.970977]}, 
{"type":"Point","coordinates":[-3.580145,55.980174]}
]
```

**Comment by sandyscoffable** [comment]
Also, please note that normal turns (i.e turns **_not_** on roundabouts) are _sometimes_ affected. Here is an example from a road test that I did on Friday:
<img src="https://user-images.githubusercontent.com/20515901/115276421-e493d200-a13a-11eb-99d6-890749c9a6ae.jpg" width="320" />

**Comment by sandyscoffable** [comment]
An example from this morning. I was mocking points with this one. This bug does happen all the time.
<img src="https://user-images.githubusercontent.com/20515901/115362721-bbfeed00-a1b9-11eb-8337-801107f9f7a0.jpg" width="320" />

**Comment by sandyscoffable** [comment]
Still happens in `2.0.0-beta.7`

**Comment by abhishek1508** [comment]
@sandyscoffable 
Can you please share the coordinate pairs for one such route where you see incorrect turn icons other than roundabouts.

**Comment by sandyscoffable** [comment]
@abhishek1508 : see a few posts above

**Comment by sandyscoffable** [comment]
Ah wait ... not roundabouts ... 2s

**Comment by sandyscoffable** [comment]
Ok, fix your location at:
```
55.9718772,-3.6271411
```

Then run the Mapbox "Turn by Turn" example, and repeat the instructions in this video:
https://drive.google.com/file/d/19PNJ68qTE3SkMfpOuE1QEQSnvaCljpkV/view?usp=sharing

While the Turn by Turn example uses a "replayer", this happens for me out on the road as well.

**Comment by sandyscoffable** [comment]
That scenario reliably reproduces the issue

**Comment by sandyscoffable** [comment]
FYI: I went for a drive yesterday, and saw the wrong turn issue a few times. Interestingly, the voice instructions were correct, so perhaps the issue seems to be in the UI components related to the ManeuverView?

**Comment by sandyscoffable** [comment]
Thanks @abhishek1508 - This issue seems to have been resolved in `beta.11` 👍

**Comment by sandyscoffable** [comment]
After a road test, I'm afraid to say this isn't fixed. I think whatever you've done is better for turns, but roundabouts still appear broken.

![Screenshot_20210524-134251_Scoffable Driver App](https://user-images.githubusercontent.com/20515901/119363082-52389e00-bca5-11eb-8f77-14ebd238b215.jpg)
![Screenshot_20210524-144449_Scoffable Driver App](https://user-images.githubusercontent.com/20515901/119363087-5369cb00-bca5-11eb-900d-dc7910c47743.jpg)
![Screenshot_20210524-143748_Scoffable Driver App](https://user-images.githubusercontent.com/20515901/119363091-54026180-bca5-11eb-821a-7ce995c951f5.jpg)

Can you re-open this issue?

**Comment by abhishek1508** [comment]
@sandyscoffable 
As I mentioned above roundabouts is a known issue on the directions API where the Nav SDK receives incorrect turn angle values at times. 

I would like to request you to close this issue and open a new one with specific mention to roundabouts. This issue was targeted towards turn instructions being incorrect that has been already fixed. 

cc @LukasPaczos

**Comment by sandyscoffable** [comment]
Ok, will do 👍 . Sorry, it's all the same area to me (same area of visible functionality etc etc).

**Comment by abhishek1508** [comment]
@sandyscoffable Thank you. Closing in favor of https://github.com/mapbox/mapbox-navigation-android/issues/4440
