### ISSUE TITLE
Changelog verification does not work

### ISSUE THREAD

**Issue by kmadsen** [mapbox/mapbox-navigation-android#4299]
After recycling the `GITHUB_ACCESS_TOKEN`, the one place it is used in this repository is changelog verification.

We tried to use the key that is considered refreshed, but it did not work. Considering this not top priority, creating this ticket to remember that it should be fixed.

cc: @LukasPaczos @Guardiola31337

**Comment by LukasPaczos** [comment]
As mentioned in other threads on the same topic - I'd love to explore https://platform.mapbox.com/developer-experience/ci-systems/overview/github-ci-apps/ to get the token.
