### ISSUE TITLE
Configurable styling of active and subsequent legs on route

### ISSUE THREAD

**Issue by sandyscoffable** [mapbox/mapbox-navigation-android#4303]
This is a feature request, spawned after some discussion on https://github.com/mapbox/mapbox-navigation-android/issues/4285

### Steps to trigger behavior

 1. Create a route with many stops (e.g a normal looking delivery itinerary), where the route doubles back and goes round the same roundabouts etc

### Expected behavior

- Current leg should be easily distinguishable from subsequent legs via styling
- Vanishing route line should work

E.g
<img src="https://user-images.githubusercontent.com/20515901/115742884-04b8d080-a389-11eb-874e-b945cdfb48a9.png" width="300" />

### Actual behavior

It's difficult to see where to go where you are navigating as roundabouts are solid blue etc (this isn't the best example of the issue, but hopefully you get the idea):
<img src="https://user-images.githubusercontent.com/20515901/115743007-25812600-a389-11eb-9da5-e3a78591f053.png" width="300" />

In the meantime, I've knocked together a solution using GradientLine to get what I want, but I've had to compromise on the Vanishing Route Line feature which I've had to disable.

**Comment by 1ec5** [comment]
Related: mapbox/mapbox-navigation-ios#2678.

**Comment by cafesilencio** [comment]
@sandyscoffable FYI this feature has been prioritized and is currently under development.

**Comment by cafesilencio** [comment]
This feature was implemented with the merge of PR https://github.com/mapbox/mapbox-navigation-android/pull/4489/. The feature will be available in the next beta release.
