### ISSUE TITLE
Integrate firebase crashlytics into instrumentation tests

### ISSUE THREAD

**Issue by kmadsen** [mapbox/mapbox-navigation-android#4305]
The crash is caught by instrumentation tests but is still obfuscated, as it only shows up in TestLab. The instrumentation-tests would need to integrate firebase plugin and the mapbox native-download plugin. This will also add ~5 minutes to the build time. We would want to optimize it with the ui-robo-tests jobs

https://console.firebase.google.com/u/0/project/mapbox-navigation-android/testlab/histories/bh.54eb2dd57e959221/matrices/7355777522870432581/executions/bs.664972ed8eebb8af

![Screen Shot 2021-04-22 at 11 23 13 AM](https://user-images.githubusercontent.com/3021882/115766738-27cd8b00-a35d-11eb-82c2-5e585112bccc.png)

### When it works for instrumentation tests it will show up in the Firebase Crashlytics Console

https://github.com/mapbox/mapbox-navigation-android/pull/4304#issuecomment-825097483

**Comment by LukasPaczos** [comment]
Alternative idea - instead of using crashlytics, we could download the logs whenever a job fails and symbolicate the traces ourselves using CLI stacking the tombstone against `.so` files.

**Comment by kmadsen** [comment]
> Alternative idea - instead of using crashlytics, we could download the logs whenever a job fails and symbolicate the traces ourselves using CLI stacking the tombstone against .so files.

Linking the epic for how navigation handles native crashes https://github.com/mapbox/navigation-sdks/issues/908

One of the possible items is `Create a mapbox-ndk-stack CLI tool that allows us to debug issues locally`

I've made a little progress on this idea but it does have some more work. Left the details in a ticket https://github.com/mapbox/navigation-sdks/issues/1082.

Our conclusions are that we would rather pursue local command line tools for this, so let's close this issue in favor of issues/1082
