### ISSUE TITLE
Off Route ArrayIndexOutOfBounds in calculateRemainingWaypointNames

### ISSUE THREAD

**Issue by Doug910** [mapbox/mapbox-navigation-android#4314]
App running on Android 9 on a Samsung J5, targetSdkVersion 29.

mapbox-android-navigation-ui:0.42.6
mapbox-android-plugin-locationlayer:0.6.0

Note: On a simulated navigation or if I stay driving on the route there are no problems.

### Steps to trigger behavior
 1. Create a driving route with origin, 3 way points and destination.
 2. Set waypoint name string to ";start route a00001;end route a00001;start route a00002;end route a00002"
 3. Start navigation then drive off route before the first way point,
 4. Happens every time, easy to reproduce.

### Expected behavior
New route generated and navigation continues.

### Actual behavior
Crashes when trying to calculate remaining waypoint names and copy the strings:

java.lang.ArrayIndexOutOfBoundsException: src.length=5 srcPos=19 dst.length=4 dstPos=0 length=-14
java.lang.System.arraycopy(Native Method)
java.util.Arrays.copyOfRange(Arrays.java:3413)
java.util.Arrays.copyOfRange(Arrays.java:3369)
com.mapbox.services.android.navigation.v5.utils.RouteUtils.calculateRemainingWaypointNames(RouteUtils.java:100)
com.mapbox.services.android.navigation.v5.route.RouteFetcher.addWaypointNames(RouteFetcher.java:182)
com.mapbox.services.android.navigation.v5.route.RouteFetcher.buildRequestFrom(RouteFetcher.java:135)
com.mapbox.services.android.navigation.ui.v5.NavigationViewRouter.findRouteFrom(NavigationViewRouter.java:80)
com.mapbox.services.android.navigation.ui.v5.NavigationViewModel.handleOffRouteEvent(NavigationViewModel.java:540)
com.mapbox.services.android.navigation.ui.v5.NavigationViewModel.access$100(NavigationViewModel.java:54)
com.mapbox.services.android.navigation.ui.v5.NavigationViewModel$1.userOffRoute(NavigationViewModel.java:423)
com.mapbox.services.android.navigation.v5.navigation.NavigationEventDispatcher.onUserOffRoute(NavigationEventDispatcher.java:171)
com.mapbox.services.android.navigation.v5.navigation.RouteProcessorThreadListener.onUserOffRoute(RouteProcessorThreadListener.java:57)
com.mapbox.services.android.navigation.v5.navigation.RouteProcessorRunnable$1.run(RouteProcessorRunnable.java:149)
android.os.Handler.handleCallback(Handler.java:873)
android.os.Handler.dispatchMessage(Handler.java:99)
android.os.Looper.loop(Looper.java:216)
android.app.ActivityThread.main(ActivityThread.java:7266)
java.lang.reflect.Method.invoke(Native Method)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:975)

**Comment by LukasPaczos** [comment]
Hey @Doug910, unfortunately, the `v0.x` versions of the Navigation SDKs are not supported anymore. Please check out https://docs.mapbox.com/android/navigation/guides/ and our migration guides in the wiki - https://github.com/mapbox/mapbox-navigation-android/wiki.

**Comment by Doug910** [comment]
Hi Lukas, That is disappointing, since 0.42.6 only came out a year ago. I would switch to 1.0.0 but the 10 active user limit is way too low, if I do 4 test builds and run each on simulator and a couple of phones, I have blown my free monthly limit already, so not practical for development.

**Comment by LukasPaczos** [comment]
Thanks for this feedback @Doug910 and sorry to hear that you are blocked. We are actively working on improving the pricing to allow for a better developer experience before apps go public. Unfortunately, nothing that we can share just yet.

cc @AhmerKhan1 @jyrigo @zugaldia @truburt
