### ISSUE TITLE
Convert SAM interfaces into Functional (SAM) interfaces

### ISSUE THREAD

**Issue by Guardiola31337** [mapbox/mapbox-navigation-android#4319]
Audit codebase and convert any SAM interfaces into [Functional (SAM) interfaces](https://kotlinlang.org/docs/fun-interfaces.html#sam-conversions) (`fun interface`) to make the code more concise and readable by using [lambda expressions](https://kotlinlang.org/docs/lambdas.html#lambda-expressions-and-anonymous-functions).

cc @pablisco @mapbox/navigation-android

**Comment by zugaldia** [comment]
Would those changes be considered breaking API (SEMVER major) changes?

**Comment by Guardiola31337** [comment]
Need to investigate further (probably yes). In any case, was assuming working on this prior to going GA as we're still have time to break the APIs 😬
