### ISSUE TITLE
Glitchy animation on sound button

### ISSUE THREAD

**Issue by sandyscoffable** [mapbox/mapbox-navigation-android#4326]
**Android API:** 30
**Mapbox Navigation SDK version:** 2.0.0-beta.7

### Steps to trigger behavior

 1. Trigger animation on a real device, e.g do something like:
 ```kotlin
        viewModel.navSpeechEnabled.observe(viewLifecycleOwner) {
            if (it == true) {
                Log.i(TAG, "Unmuting speech")
                binding.soundButton?.unmuteAndExtend(1500)
            } else {
                Log.i(TAG, "Muting speech")
                binding.soundButton?.muteAndExtend(1500)
                speechAPI.cancel()
                voiceInstructionsPlayer?.clear()
            }
        }
 ```

### Expected behavior

Button slide effect should be smooth

### Actual behavior

The last part of the button retraction animation appears to "jump"

https://user-images.githubusercontent.com/20515901/116252053-20482080-a767-11eb-894b-d21f7f5113ab.mp4

### Misc

This is really minor vs some of the other issues I've raised (e.g instructions telling the driver to go left instead of right).
For now I'm not going to use the animation.

**Comment by Guardiola31337** [comment]
cc'ing @RingerJK @abhishek1508 for visibility

**Comment by Guardiola31337** [comment]
Hey @sandyscoffable is this still reproducible with latest versions of the SDK? For reference, latest available (as of today) is [Mapbox Navigation SDK `2.0.0-beta.18`](https://github.com/mapbox/mapbox-navigation-android/releases/tag/v2.0.0-beta.18).

cc @RingerJK @abhishek1508
