### ISSUE TITLE
Add vector LaneView assets

### ISSUE THREAD

**Issue by ericrwolfe** [mapbox/mapbox-navigation-android#433]
Tail work to https://github.com/mapbox/mapbox-navigation-android/pull/362:

- [ ] Add LaneStyleKit and LaneView.
- [ ] Remove all usages of the old manuever views, i.e. in the NavigationNotification.
- [ ] Remove all vector drawables.

cc @danesfeder

**Comment by danesfeder** [comment]
Added in #466
