### ISSUE TITLE
Verify whether route source has been initialized before updating it

### ISSUE THREAD

**Issue by LukasPaczos** [mapbox/mapbox-navigation-android#4331]
We're trying to update the restricted route source even if the feature is disabled, which means that the source was not initialized in the first place:
https://github.com/mapbox/mapbox-navigation-android/blob/838e80fdc93360cceba0d03589c09e13d6c20e11/libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/route/line/api/MapboxRouteLineView.kt#L100-L104

This results in an unavoidable error log that can be misleading:
```
E/StyleSourcePlugin: Get source mapbox-restricted-road-source failed: Source mapbox-restricted-road-source is not in style
```

We should if-check whether the feature is enabled or whether the source exists before trying to update it. Let's also verify that this doesn't happen for other layers.

cc @cafesilencio

**Comment by cafesilencio** [comment]
Restricted road indication is now part of the traffic line so there is no longer a separate layer source. Closing this.
