### ISSUE TITLE
AnimatorListener should be called when camera transition is already in progress

### ISSUE THREAD

**Issue by LukasPaczos** [mapbox/mapbox-navigation-android#4341]
When `NavigationCamera#request[state]` methods are called and we're already transitioning, the method just returns and leaves the potentially provided `AnimatorListener` without a callback. Example:
https://github.com/mapbox/mapbox-navigation-android/blob/354689d14d6fb08b5c562e87a5849af3257e31c9/libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/camera/NavigationCamera.kt#L167-L168

We should consider calling some method of the callback or add it to the list of callbacks to invoke when the transition finishes.

**Comment by Zayankovsky** [comment]
@LukasPaczos, shouldn't we cancel current animation, even if we are already transitioning to requested state? The user could provide new transition options that would require faster animation completion, while the current animation may be slower.

**Comment by LukasPaczos** [comment]
@Zayankovsky great point, agreed :+1:

**Comment by Zayankovsky** [comment]
@LukasPaczos, maybe we should replace `AnimatorListener` with some lambda or functional interface, so that we are not forced to use `Animator` for implementing camera transitions. Since `AnimatorListener` methods require passing an `Animator` instance, we are forced to create one even if camera is already in the required state.

**Comment by LukasPaczos** [comment]
I don't have a strong opinion here - passing the animator reference is nice because it gives visibility into the underlying transition, however, I haven't come across a concrete use case for this yet.

Do you have an idea of how the alternative interface would look like?

**Comment by Zayankovsky** [comment]
Something like that:
```kotlin
class NavigationCamera {

    fun interface TransitionEndListener {
        fun onTransitionEnd(isCanceled: Boolean)
    }

    fun requestNavigationCameraToFollowing(
        stateTransitionOptions: NavigationCameraTransitionOptions = DEFAULT_STATE_TRANSITION_OPT,
        frameTransitionOptions: NavigationCameraTransitionOptions = DEFAULT_FRAME_TRANSITION_OPT,
        transitionEndListener: TransitionEndListener? = null,
    ) {
        // implementation
    }
}
```

**Comment by LukasPaczos** [comment]
LGTM, I don't see a specific use case for all the started/paused/etc animator callbacks so there might be no need to overcomplicate the setup. We can re-expose some form of those callbacks in the future if the need be.
