### ISSUE TITLE
Freely position the first point (user location) in the viewport padding

### ISSUE THREAD

**Issue by LukasPaczos** [mapbox/mapbox-navigation-android#4347]
This tracks the ability to be able to freely position the first point in the framed geometry list (typically the user location puck) inside of the provided viewport following padding. Now, the first point is always placed centered horizontally on the bottom edge of the padding.

This might be possible by the `MapboxNavigationViewportDataSource` accepting an offset from the center of the padding where that first geometry point should be rendered (and using the vanishing point manipulation). This needs prototyping and understanding whether it will be possible to execute with the currently available Map SDK APIs.

cc @d-prukop @MaximAlien

**Comment by tomaszrybakiewicz** [comment]
Blocked by https://github.com/mapbox/mapbox-gl-native-internal/issues/2135

**Comment by zugaldia** [comment]
> Blocked by https://github.com/mapbox/mapbox-gl-native-internal/issues/2135

This now landed, work continues on https://github.com/mapbox/mapbox-navigation-android/pull/5875.
