### ISSUE TITLE
Add ability to override PlayerAttributes properties

### ISSUE THREAD

**Issue by VitaminPSG** [mapbox/mapbox-navigation-android#4368]
In the current implementation of PlayerAttributes, it is possible to override the settings to configure the player and audio focus directly, which can lead to a violation of the internal logic.

It is necessary to enable the user to configure the player and focus attributes, without access to resources.

**Android API:** 22+
**Mapbox Navigation SDK version:** v2-beta

**Comment by Guardiola31337** [comment]
Refs. https://github.com/mapbox/mapbox-navigation-android/issues/4374
