### ISSUE TITLE
Method lineWidth not found when creating NavigationMapRoute

### ISSUE THREAD

**Issue by cammace** [mapbox/mapbox-navigation-android#437]
_Originally ticketed in Mapbox Java by @turey_

**Platform:**
LG-H871
Android 7.0

**Mapbox Services version:**
    compile('com.mapbox.mapboxsdk:mapbox-android-sdk:5.2.0-beta.1@aar') {
        transitive=true
    }
    compile 'com.mapbox.mapboxsdk:mapbox-android-services:2.3.0-SNAPSHOT'
    compile 'com.mapbox.mapboxsdk:mapbox-android-navigation:0.7.0-SNAPSHOT'
    compile ('com.mapbox.mapboxsdk:mapbox-android-navigation-ui:0.7.0-SNAPSHOT') {
        transitive = true
    }

### Steps to trigger behavior

 1. Create the app described in https://www.mapbox.com/help/android-navigation-sdk/
 2. Run the app.
 3. Click on the map.

### Expected behavior
The pin will appear on the map and a route will be drawn to it.

### Actual behavior
E/AndroidRuntime: FATAL EXCEPTION: main
java.lang.NoSuchMethodError: No static method lineWidth(Lcom/mapbox/mapboxsdk/style/functions/CameraFunction;)Lcom/mapbox/mapboxsdk/style/layers/PropertyValue; in class Lcom/mapbox/mapboxsdk/style/layers/PropertyFactory; or its super classes (declaration of 'com.mapbox.mapboxsdk.style.layers.PropertyFactory' appears in /data/app/com.hall.thomas.test-2/split_lib_dependencies_apk.apk:classes19.dex)
at com.mapbox.services.android.navigation.ui.v5.route.NavigationMapRoute.addNavigationRouteLayer(NavigationMapRoute.java:371)
at com.mapbox.services.android.navigation.ui.v5.route.NavigationMapRoute.initialize(NavigationMapRoute.java:179)
at com.mapbox.services.android.navigation.ui.v5.route.NavigationMapRoute.<init>(NavigationMapRoute.java:156)
at com.mapbox.services.android.navigation.ui.v5.route.NavigationMapRoute.<init>(NavigationMapRoute.java:135)

**Comment by kuja2007** [comment]
The same issue on my side

**Comment by Danny-James** [comment]
I have this same issue.

**Comment by kuja2007** [comment]
Hi guys,

Do you need additional data to reproduce this issue? 
If yes please let me know.

**Comment by kuja2007** [comment]
Simple fix.
If you include class "NavigationMapRoute" locally to the project issue is fixed.

**Comment by Danny-James** [comment]
@cammace Any News On This? As I'm Unable To Continue Development Until This Issue Is Resolved.

**Comment by rheng001** [comment]
Facing same issue as well

**Comment by cammace** [comment]
As @kuja2007 mentioned, this seems to be a mistake in the documentation rather than a bug existing in the codebase since running the testapp doesn't show this crash. Please review your code and if you are still having issues, please provide a way for me to reproduce the crash.

**Comment by kotdroidZero** [comment]
How can we use NavigationMapRoute class with OpenStreetMap instead of MapBox in android?
