### ISSUE TITLE
Audit codebase and integrate `sealed interface`s 

### ISSUE THREAD

**Issue by Guardiola31337** [mapbox/mapbox-navigation-android#4374]
https://blog.jetbrains.com/kotlin/2021/05/kotlin-1-5-0-released/ was released and integrated in https://github.com/mapbox/mapbox-navigation-android/pull/4318 `1.5.0` includes support for `sealed interface`s 🎉 

This is a long-awaited feature for SDK / library builders and we should take advantage of it before the SDK goes GA to prevent any breaking changes in the future.

This ticket tracks auditing the code and updating it to use `sealed interface`s when appropriate.

On the topic this is a really great reading https://zsmb.co/sealed-goodies-coming-in-kotlin-1-5/ by @zsmb13

cc @mapbox/navigation-android

**Comment by Guardiola31337** [comment]
@zugaldia 
> Could you say more about the advantages of using sealed interfaces for Nav SDK?

> Why is this useful? Because it allows you to expose interfaces from a module (or library, if you will) which its clients won’t be able to implement. These kinds of non-user-implementable interfaces are great: you can still use interfaces to hide concrete implementation classes in your module, but don’t run the risk of someone trying to reimplement your interface.

> I find that most of the time, this is what I want an interface to behave like in the first place. I don’t want multiple implementations of it, especially not by clients of my code, I just want to hide the concrete classes that implement it.

**Comment by zugaldia** [comment]
Thanks @Guardiola31337 - what are examples of sealed interfaces that we're planning to (not) expose in Nav SDK?

**Comment by Guardiola31337** [comment]
@zugaldia 
> what are examples of sealed interfaces that we're planning to (not) expose in Nav SDK?

In general, the problem with `sealed class`es was that you couldn't design around them because any changes in the future would cause breaking SemVer e.g. https://github.com/mapbox/mapbox-navigation-android/pull/4224#discussion_r607134506 ("forced" to use `enum`), https://github.com/mapbox/mapbox-navigation-android/pull/3980#discussion_r593441115, https://github.com/mapbox/mapbox-navigation-android/pull/3582#discussion_r493927711, https://github.com/mapbox/mapbox-navigation-android/pull/2853 (we moved away of this implementation because wasn't going to be extensible in the future without breaking SemVer), https://github.com/mapbox/mapbox-navigation-android/pull/2689#discussion_r402557516, https://github.com/mapbox/mapbox-navigation-android/pull/4365#pullrequestreview-654638785 and from a past discussion around `SoundButtonState`:

> Do you have any ideas on how to design the state so it can be extended in the future? `sealed class`es will break SemVer if a new state is needed.
>
> I know this https://github.com/Kotlin/KEEP/issues/226 would solve our problem but unfortunately is not going to be available until Kotlin 1.5 release.

**Comment by LukasPaczos** [comment]
@Guardiola31337 sealed interfaces would exhibit the same issues for us as the seal classes did - we wouldn't be able to add new, public implementation of a sealed interface without considering it a breaking change in cases where an instance of that interface is returned by our APIs. This type of change would break exhaustive `when` implementations and is no different than sealed classes case.

I do see value in sealed interfaces in general - I can imagine a feature that has 2 (or N) variants that developers can choose from, and only those variants, nothing custom. This is a very powerful tool that lets us write interfaces that are more driven towards our opinionated implementations, but I don't think we currently have an API that could immediately benefit from it. Something to keep in mind when we build new things though.

**Comment by Guardiola31337** [comment]
> sealed interfaces would exhibit the same issues for us as the seal classes did - we wouldn't be able to add new, public implementation of a sealed interface without considering it a breaking change in cases where an instance of that interface is returned by our APIs. This type of change would break exhaustive `when` implementations and is no different than sealed classes case.

RE: Breaking SemVer

Although that's right for the exhaustive `when` statements part and exposing a whole new class in the hierarchy, it's not entirely true when it comes to adding features to existing restricted types, as `sealed interface`s should also be able to have `internal` members and therefore we could theoretically use this to add members to an interface that should not be public API, but we want to access them within our own modules which would allow us to extend the capabilities of the already defined `sealed class` implementations.

**Comment by Guardiola31337** [comment]
> it's not entirely true when it comes to adding features to existing restricted types, as `sealed interface`s should also be able to have `internal` members and therefore we could theoretically use this to add members to an interface that should not be public API, but we want to access them within our own modules which would allow us to extend the capabilities of the already defined `sealed class` implementations.

This is actually also feasible for public APIs added to the `sealed interface` (without breaking SemVer as opposed to regular `interface`s) as the implementations are handled internally 💃 

For example:

```kotlin
sealed interface Hand {
    val fingers: List<Finger>
    fun moveUp(finger: Finger, level: Int)
}

fun getLeftHand(): Hand { return Left() }

fun getRightHand(): Hand { return Right() }

class Finger

internal class Left : Hand {
    override val fingers: List<Finger> = emptyList()
    override fun moveUp(finger: Finger, level: Int) {}
}

internal class Right : Hand {
    override val fingers: List<Finger> = emptyList()
    override fun moveUp(finger: Finger, level: Int) {}
}
```

Client code:

```kotlin
// ...
val hand = when (val left: Hand = getLeftHand()) {
    is Left -> {
        left.moveUp(Finger(), 3)
    }
    is Right -> {}
}
// ...
```

Later we can freely add `fun moveDown(finger: Finger, level: Int)` to `Hand` and the client code doesn't break:

```kotlin
sealed interface Hand {
    // ...
    fun moveDown(finger: Finger, level: Int)
}

internal class Left : Hand {
    // ...
    override fun moveDown(finger: Finger, level: Int) {}
}

internal class Right : Hand {
    // ...
    override fun moveDown(finger: Finger, level: Int) {}
}
```

🎉

**Comment by truburt** [comment]
We formed a guideline for future feature work, closing this ticket as established.
