### ISSUE TITLE
Terminating with uncaught exception of type jni::PendingJavaException Fatal signal 6 (SIGABRT)

### ISSUE THREAD

**Issue by ibnekhan** [mapbox/mapbox-navigation-android#438]
Whenever i launched navigation activity my app crashed with this log.

E/libc++abi: terminating with uncaught exception of type jni::PendingJavaException
                                                                            --------- beginning of crash
 A/libc: Fatal signal 6 (SIGABRT), code -6 in tid 27977 (carpooltoschool)
debuggerd: handling request: pid=27977 uid=10237 gid=10237 tid=27977

**Comment by DerGav** [comment]
I'm getting a similar error following [this tutorial](https://www.mapbox.com/help/android-navigation-sdk/#getting-started)

**Comment by konskons5** [comment]
same issue here. Any solution?

**Comment by konskons5** [comment]
Made it work by:

    compile('com.mapbox.mapboxsdk:mapbox-android-sdk:5.1.4@aar') { transitive=true }
    compile 'com.mapbox.mapboxsdk:mapbox-android-navigation:0.6.3'
    compile ('com.mapbox.mapboxsdk:mapbox-android-navigation-ui:0.6.1') {
        exclude group: 'android.arch.core'
        transitive = true
    }

**Comment by Victorgf87** [comment]
Thank you, @konskons5 it worked for me!

**Comment by konskons5** [comment]
I'd like to use 0.7.0 though. Any solution how to make it work?

**Comment by tobrun** [comment]
using `com.mapbox.mapboxsdk:mapbox-android-sdk:5.2.0@aar` should work with `0.7.0`

**Comment by konskons5** [comment]
I get following errors: 

Error:Failed to resolve: com.mapbox.mapboxsdk:mapbox-java-services-directions:3.0.0-SNAPSHOT

Error:Failed to resolve: com.mapbox.mapboxsdk:mapbox-java-services-turf:3.0.0-SNAPSHOT

:/

**Comment by tobrun** [comment]
Have you added this [line](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/android/build.gradle#L14) to resolve SNAPSHOT dependencies?

**Comment by konskons5** [comment]
I forgot! Thank you so much!!

**Comment by Alamgir** [comment]
@tobrun I've also got this issue with the following gradle dependencies:

```
    implementation 'com.mapbox.mapboxsdk:mapbox-android-sdk:5.2.0@aar'
    implementation 'com.mapbox.mapboxsdk:mapbox-android-services:2.2.9'
    implementation 'com.mapbox.mapboxsdk:mapbox-android-navigation:0.7.0@aar'
    implementation 'com.mapbox.mapboxsdk:mapbox-android-plugin-traffic:0.3.0'
    implementation 'com.mapbox.mapboxsdk:mapbox-android-plugin-locationlayer:0.2.0'
    implementation ('com.mapbox.mapboxsdk:mapbox-android-navigation-ui:0.7.0@aar') {
        transitive = true
    }
```

You should also know that I'm extending the MapView class but am calling all appropriate lifecycle methods on it already. The map appears to render it's beige FrameLayout but then crashes

**Comment by danesfeder** [comment]
Feel free to open if this is still found with > `0.7.1`

**Comment by mf-mindcrewtech** [comment]
@danesfeder I am getting same error

My added libraries ::

implementation 'com.mapbox.mapboxsdk:mapbox-android-sdk:6.4.0'
implementation 'com.mapbox.mapboxsdk:mapbox-android-plugin-locationlayer:0.7.1'
implementation 'com.mapbox.mapboxsdk:mapbox-android-plugin-building:0.1.0'
implementation 'com.mapbox.mapboxsdk:mapbox-android-navigation:0.18.0'
implementation 'com.mapbox.mapboxsdk:mapbox-android-plugin-places:0.2.1'
implementation ('com.mapbox.mapboxsdk:mapbox-android-navigation-ui:0.18.0') {
transitive = true
}

**Comment by Tsabary** [comment]
I'm getting the same error. Mapbox has just been through major updates and the advice here doesn't quite work for me (maybe it needs some modifications I don't know how to do.

Anyway to solve this now?

I'm only using these dependencies at the moment:

    implementation 'com.mapbox.mapboxsdk:mapbox-android-sdk:7.2.0'
    implementation 'com.mapbox.mapboxsdk:mapbox-android-plugin-locationlayer:0.5.0'

**Comment by paulsUsername** [comment]
I am getting this error too.

**Comment by danielnogueiradti** [comment]
I am getting this error too.

**Comment by tobrun** [comment]
@danielnogueiradti @paulsUsername would you be able to create a new ticket and add the stacktrace and the underlying used maps and navigation versions? Thank you for reaching out

**Comment by Madhavaggarwals** [comment]
I tried the same method, but startup is failing.!? what should I do.

**Comment by tworkool** [comment]
The error occured for me when converting a vector asset into a Bitmap with BitmapFactory. The problem there was that the drawable was a vector asset and not an image. When using a .png the error was resolved! But I realized I had the same Exception later when setting a geojson source with same source ID twice. Maybe that helps.

**Comment by Aimness** [comment]
Hi. I have the same problem:
E/libc++abi: terminating with uncaught exception of type jni::PendingJavaException
A/libc: Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 20545 (OnlineFileSourc), pid 20405 (d.myapplication)
I am following this tutorial and I did everything exactly the same as there.
Here is what i have in my build.gradle:
implementation ('com.mapbox.mapboxsdk:mapbox-android-sdk:9.6.1')
{ transitive=true }
implementation 'com.mapbox.mapboxsdk:mapbox-sdk-services:5.8.0'
implementation ('com.mapbox.mapboxsdk:mapbox-android-navigation-ui:0.42.6')
{
exclude group: 'android.arch.core'
transitive = true
}
implementation 'com.mapbox.mapboxsdk:mapbox-android-plugin-locationlayer:0.11.0'

**Comment by bilalnasir9** [comment]
// mapbox dependencies in build.gradle(Module level)

    implementation 'com.mapbox.mapboxsdk:mapbox-android-sdk:9.6.1'
    implementation 'com.mapbox.mapboxsdk:mapbox-android-plugin-traffic-v9:0.10.0'
    implementation 'com.mapbox.mapboxsdk:mapbox-android-plugin-places-v9:0.12.0'
    implementation 'com.mapbox.mapboxsdk:mapbox-android-navigation-ui:0.42.6'

//  I was facing same problem but after adding below lines along with above code solved my problem
    // in Android studio (Arctic Fox)

    implementation ('com.mapbox.maps:android:10.1.0'){
        exclude group: 'group_name', module: 'module_name'
    }

**Comment by sgogolowski** [comment]
> @Aimness do you find a solution? I also have the following error: E/libc++abi: terminating with uncaught exception of type jni::PendingJavaException A/libc: Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 16064 (OnlineFileSourc), pid 15758 (e.myapplication)

hey @Aimness I am having this issue in my Xamarin.Android application. Did you ever get this resolved?

**Comment by fatihmerickoc** [comment]
GUYS I AM HAVING THE SAME PROBLEM WITH MY FLUTER APP, ANY HELP?
