### ISSUE TITLE
Add marker to map

### ISSUE THREAD

**Issue by abhishek1508** [mapbox/mapbox-navigation-android#4389]
**Android API:** 21 above
**Mapbox Navigation SDK version:** v2.0.0-beta.10

In order to draw a marker at a point on the Map, a user using the Navigation SDK v2.0 would have to do the following:

```
/* ----- Utility functions ----- */
private fun bitmapFromDrawableRes(context: Context, @DrawableRes resourceId: Int) =
convertDrawableToBitmap(AppCompatResources.getDrawable(context, resourceId))
 
private fun convertDrawableToBitmap(sourceDrawable: Drawable?): Bitmap? {
    if (sourceDrawable == null) {
        return null
    }
    return if (sourceDrawable is BitmapDrawable) {
        sourceDrawable.bitmap
    } else {
        // copying drawable object to not manipulate on the same reference
        val constantState = sourceDrawable.constantState ?: return null
        val drawable = constantState.newDrawable().mutate()
        val bitmap: Bitmap = Bitmap.createBitmap(
            drawable.intrinsicWidth, drawable.intrinsicHeight,
            Bitmap.Config.ARGB_8888
        )
        val canvas = Canvas(bitmap)
        drawable.setBounds(0, 0, canvas.width, canvas.height)
        drawable.draw(canvas)
        bitmap
    }
}

fun addAnnotation(point: Point) {
    var mapViewUi = findViewById<MapView>(R.id.mapView)
    bitmapFromDrawableRes(
        this@MainActivity,
        R.drawable.red_marker
    )?.let {
        val annotationPlugin = mapViewUi.annotations
        val pointAnnotationManager = annotationPlugin.createPointAnnotationManager(mapViewUi)
        val pointAnnotationOptions: PointAnnotationOptions = PointAnnotationOptions()
            .withPoint(point)
            .withIconImage(it)
        pointAnnotationManager.create(pointAnnotationOptions)
    }
}
```
I feel this is lot to do just to add a marker to set up a basic navigation. Even though a major chunk of this portion is converting `Drawable` to `Bitmap`, I feel we should expose API's in `libnavui-maps` that can take a `Point` and a `Drawable` and return a `Bitmap` containing a marker.
What do you think?

cc @mapbox/navigation-android @colleenmcginnis @zugaldia @truburt

**Comment by LukasPaczos** [comment]
I think this is more of a feature request for the Maps SDK team to expose an option that accepts a drawable (or the utility functions you're mentioning here @abhishek1508). I remember we used to support this in the legacy annotation plugin, is there a plan to bring this functionality back @mapbox/maps-android?

**Comment by abhishek1508** [comment]
> I think this is more of a feature request for the Maps SDK team to expose an option that accepts a drawable (or the utility functions you're mentioning here @abhishek1508)

I like the idea, but if we consider a basic turn by turn navigation, there is already a huge amount of setup that a developer needs to do. Can we support this meanwhile @mapbox/maps-android decides on supporting this or not?

cc @LukasPaczos

**Comment by LukasPaczos** [comment]
If Maps SDK does end up exposing this feature, we won't be able to remove the duplicate in the Nav SDK for the duration of v2.

This sounds like a simple enough feature to land directly in the Maps SDK, especially since it has nothing to do with the Navigation domain.

@abhishek1508 if you think that would enhance the dev experience, feel free to contribute the changes directly to the Maps SDK!

**Comment by abhishek1508** [comment]
Ok sounds good. Closing this here.
