### ISSUE TITLE
Is turn-by-turn Navigation with multiple waypoints working in a non-simulation mode?

### ISSUE THREAD

**Issue by josephquzhou** [mapbox/mapbox-navigation-android#439]
It seems to me that turn-by-turn navigation with multiple waypoints only works in simulation mode. Whenever I switch to the non-simulation mode all waypoints are removed.

**Comment by josephquzhou** [comment]
After some further study the code I think, in a non-simulation mode,  NavigationLauncher can take an initial route with waypoints for navigation. But it will soon reroute without waypoints. Is it a bug?

**Comment by josephquzhou** [comment]
Confirmed by Mapbox. NavigationLauncher doesn't support waypoints at the moment.

**Comment by Danny-James** [comment]
Why has this been closed? Should this not be a feature request, it's important NavigationLauncher.startNavigation should allow waypoints for my case.

I was under the impression adding a route with waypoints to the Navigation Launcher works. @tobrun can you confirm this?

**Comment by Danny-James** [comment]
@tobrun is their a way to turn off rerouting I'm developing a routing application where a Crane needs to stay on a specific route signed off by the authorities so if the waypoints don't stay (I use waypoints to navigate around low tunnels/weak bridges) can we prevent rerouting with NavigationLauncher?

**Comment by josephquzhou** [comment]
I agree NavigationLauncher should support waypoints in a non-simulation mode. 

The reason I closed this discussion was because my original question was just to ask whether this feature exists or not.

**Comment by tobrun** [comment]
@Danny-James i'm not involved in the development of the nav sdk so I'm unable to answer.

cc @cammace @danesfeder

**Comment by Danny-James** [comment]
Sorry @tobrun I was supposed to tag @cammace I mixed the two of you up.

**Comment by Danny-James** [comment]
@cammace could you take a look at the above [comment](https://github.com/mapbox/mapbox-navigation-android/issues/439#issuecomment-340909797) please.

**Comment by cammace** [comment]
https://github.com/mapbox/mapbox-navigation-android/pull/515 should allow for setting `reroute` to false.
