### ISSUE TITLE
Document RouteLineApi's requirements and constraints

### ISSUE THREAD

**Issue by LukasPaczos** [mapbox/mapbox-navigation-android#4394]
The `MappboxRouteLineApi` requires a specific set of data to be available in order to operate properly (display traffic, vanish the route line, etc). We should refactor the documentation to reflect this. Especially that specific route annotations have to be in the response or that the indicator position needs to be provided for the vanishing feature to work. We also need to fix links and update examples in the class docs.

cc @cafesilencio

**Comment by LukasPaczos** [comment]
We might also want to add logs when a feature stops working because it doesn't have enough data (like traffic not showing up because there's no `DISTANCE` or `CONGESTION` annotation).

**Comment by cafesilencio** [comment]
This can be added to the route line narrative documentation which is tracked here: https://github.com/mapbox/android-docs/pull/1713

**Comment by LukasPaczos** [comment]
Sounds good :+1: Let's make sure to update inline docs as well though.

**Comment by cafesilencio** [comment]
The inline documentation was completed with this PR: https://github.com/mapbox/mapbox-navigation-android/pull/4447
