### ISSUE TITLE
Remove/change `MapboxRouteLineApi#updateToPrimaryRoute`

### ISSUE THREAD

**Issue by LukasPaczos** [mapbox/mapbox-navigation-android#4400]
Cutting this ticket to start a little bit of discussion around the ergonomics of selecting alternative routes to clean them up before we go stable. The goal is not to change the implementation details, just polish the public API surface.

Now the `MapboxRouteLineApi` exposes:
1. `setRoutes`, which accepts a list of routes where "the first route in the collection will be considered the primary route and any additional routes will be alternate routes".
2. `updateToPrimaryRoute`, which "updates which route is identified as the primary route".

As you can tell we have 2 APIs that do a very similar thing, re-arrange which route lines are treated as primary and which are the alternatives.

In a typical, recommended setup developers also use the `RoutesObserver` as a source of truth for routes. This observer is triggered by `MapboxNavigation#setRoutes` and developers (and our examples) use this to draw the routes:
```kotlin
private val routesObserver: RoutesObserver = object : RoutesObserver {
    override fun onRoutesChanged(routes: List<DirectionsRoute>) {
        val routeLines = routes.map { RouteLine(it, null) }
        routeLineApi.setRoutes(
            routeLines,
            object : MapboxNavigationConsumer<Expected<RouteSetValue, RouteLineError>> {
                override fun accept(value: Expected<RouteSetValue, RouteLineError>) {
                    mapboxMap.getStyle()?.apply {
                        routeLineView.renderRouteDrawData(this, value)
                    }
                }
            }
        )
    }
}
```

This can create a little bit of confusion when we introduce a concept of selecting an alternative route which happens via `MapboxRouteLineApi#findClosestRoute` and is used like this:
1. Call `MapboxRouteLineApi#findClosestRoute` to identify whether an alternative was clicked.
2. If it was, call `MapboxRouteLineApi#updateToPrimaryRoute` to change **visuals only**, this has no effect on guidance.
3. Then call `MapboxNavigation#setRoutes` to actually tell the guidance engine that a new route is the primary one.
4. Calling `MapboxNavigation#setRoutes` triggers the above `RoutesObserver` again, duplicating the visual update.

The `MapboxRouteLineApi#updateToPrimaryRoute` looks redundant in this whole flow. If developers rely on the `RoutesObserver` as the source of truth (which we recommend), they could simply call `MapboxNavigation#setRoutes` from the `MapboxRouteLineApi#findClosestRoute` callback. If they don't, they could directly call `MapboxRouteLineApi#setRoutes` from the `MapboxRouteLineApi#findClosestRoute` callback.

Even our examples need to have lengthy comments to explain why the result of `MapboxRouteLineApi#updateToPrimaryRoute` should effectively be ignored:
https://github.com/mapbox/mapbox-navigation-android/blob/bc1dce0cb8cba9ea8c8efc40bd8d65d5350a9d23/examples/src/main/java/com/mapbox/navigation/examples/core/MapboxRouteLineAndArrowActivity.kt#L302-L322

That's what's motivating me to propose removing this method altogether or refactoring it into a utility function that changes the indices of routes list to make the selected one the primary (move it to index 0):
```kotlin
fun List<DirectionsRoute>.updatePrimaryRoute(route: DirectionsRoute): List<DirectionsRoute> {
    return this.filter { it != route }.toMutableList().also {
        // todo check if the provided route was even here to begin with
        it.add(0, route)
    }
}
```

which can be used like this:
```kotlin
val updatedRoutesList = routeLineApi.getRoutes().updatePrimaryRoute(selectedRoute)

mapboxNavigation.setRoutes(updatedRoutesList)
or
val updateState = routeLineApi.setRoutes(updatedRoutesList)
routeLineView.render(updateState)
```

Any thoughts on this @mapbox/navigation-android?

**Comment by cafesilencio** [comment]
I've been thinking about this same issue on occasion. Your proposal makes sense to me.
