### ISSUE TITLE
Expose non-cancelling `MapboxSpeechApi` versions

### ISSUE THREAD

**Issue by Guardiola31337** [mapbox/mapbox-navigation-android#4403]
Follow up from https://github.com/mapbox/mapbox-navigation-android/pull/4362

> In the current implementation (`MapboxSpeechApi`), there is no way to download multiple files at the same time.
>
>> We should discuss how we want to tackle this as there are other features (`Api`s) already having the same issue. For instance `MapboxManeuverApi`. On the contrary, we're currently supporting it for `MapboxJunctionApi` and `MapboxSignboardApi` (only `cancelAll`).
>>
>> I'd say we should consolidate these and implement something similar to `MapboxJunctionApi` and `MapboxSignboardApi` for `MapboxSpeechApi` and `MapboxManeuverApi` and add support for canceling by request to `MapboxJunctionApi` and `MapboxSignboardApi` for consistency.

cc @mapbox/navigation-android @VitaminPSG

**Comment by zugaldia** [comment]
@Guardiola31337 is this ticket still relevant? If so, considering it's a release blocker we should prioritize its work. Or does it depend on https://github.com/mapbox/mapbox-navigation-android/issues/4432?

**Comment by Guardiola31337** [comment]
> Or does it depend on #4432?

Yes it does. We should adopt the same approach in `MapboxSpeechApi` taken in https://github.com/mapbox/mapbox-navigation-android/pull/4482 for the `MapboxManeuverApi`.

**Comment by zugaldia** [comment]
https://github.com/mapbox/mapbox-navigation-android/issues/4432 has now landed and we should be unblocked to continue here.

**Comment by abhishek1508** [comment]
The title of this ticket is quite confusing. I am still not sure if we need to do anything more in maneuver API. Can we rename the title of this issue please?
cc @zugaldia @Guardiola31337

**Comment by zugaldia** [comment]
One more release blocker down!
