### ISSUE TITLE
Expose API for the route overview list use-case

### ISSUE THREAD

**Issue by Guardiola31337** [mapbox/mapbox-navigation-android#4404]
There is no drop-in component for route overview list. Currently, it is inside [`MapboxManeuverApi`](https://github.com/mapbox/mapbox-navigation-android/blob/main/libnavui-maneuver/src/main/java/com/mapbox/navigation/ui/maneuver/api/MapboxManeuverApi.kt) / [`MapboxManeuverView`](https://github.com/mapbox/mapbox-navigation-android/blob/main/libnavui-maneuver/src/main/java/com/mapbox/navigation/ui/maneuver/view/MapboxManeuverView.kt) and requires `RouteProgress` to display. This ticket track progress of exposing a new API for the route overview list use-case.

cc @mapbox/navigation-android @mapbox/navigation-ios

**Comment by LukasPaczos** [comment]
Can this ticket be considered resolved now @Guardiola31337 @abhishek1508? It feels like we are covering this use case after recent refactors.

**Comment by Guardiola31337** [comment]
Yeah I'd say so, we also are keeping track of tail-work in https://github.com/mapbox/mapbox-navigation-android/issues/4620 👍
