### ISSUE TITLE
Race condition in the RouteRefreshController

### ISSUE THREAD

**Issue by LukasPaczos** [mapbox/mapbox-navigation-android#4409]
If a route refresh is in progress and a new route is set, the result of the refresh will override that new route.

The refresh should be canceled when `MapboxNavigation#setRoutes` is called.

cc @mapbox/navigation-android

**Comment by kmadsen** [comment]
Worth thinking about this at a higher level. The current route is maintained in 3 places

- (DirectionsSession.routes)[https://github.com/mapbox/mapbox-navigation-android/blob/e3a0f8bc179146348ece98903b258ba6fc81e8ad/libnavigation-core/src/main/java/com/mapbox/navigation/core/directions/session/DirectionsSession.kt#L16]
- (TripSession.route)[https://github.com/mapbox/mapbox-navigation-android/blob/e3a0f8bc179146348ece98903b258ba6fc81e8ad/libnavigation-core/src/main/java/com/mapbox/navigation/core/trip/session/TripSession.kt#L13]
- (MapboxNativeNavigatorImpl.route)[https://github.com/mapbox/mapbox-navigation-android/blob/e3a0f8bc179146348ece98903b258ba6fc81e8ad/libnavigator/src/main/java/com/mapbox/navigation/navigator/internal/MapboxNativeNavigatorImpl.kt#L69]

We have some custom logic for interrupting requests in the [MapboxRerouteController](https://github.com/mapbox/mapbox-navigation-android/blob/e3a0f8bc179146348ece98903b258ba6fc81e8ad/libnavigation-core/src/main/java/com/mapbox/navigation/core/reroute/MapboxRerouteController.kt#L85-L96)

And we'll need to address the same issue in everything that requests modifications on the route. (Route refresh, alternative routes, ...)

Will think about it some over here https://github.com/mapbox/mapbox-navigation-android/pull/4375

**Comment by kmadsen** [comment]
In this case, it would be better if it wasn't up to the `RouteRefreshController`. 

It's the [HybridRouterHandler](https://github.com/mapbox/mapbox-navigation-android/blob/e3a0f8bc179146348ece98903b258ba6fc81e8ad/libnavigation-router/src/main/java/com/mapbox/navigation/route/internal/hybrid/HybridRouterHandler.kt#L139-L170) that is telling the controller that the route has been refreshed. 

@LukasPaczos it seems better to fix this in the `HybridRouterHandler`

**Comment by zugaldia** [comment]
Did https://github.com/mapbox/mapbox-navigation-android/pull/4375 improve this situation in any way?

**Comment by kmadsen** [comment]
> Did #4375 improve this situation in any way?

No it addressed the issue in RouteAlternativesController. I spent a little time digging, but also wanted to merge #4375 so we can re-use some of the instrumentation-testing tools.
