### ISSUE TITLE
Evaluate options to refactor base data models from builders to internal factories

### ISSUE THREAD

**Issue by LukasPaczos** [mapbox/mapbox-navigation-android#4414]
Refs https://github.com/mapbox/mapbox-navigation-android/pull/4364#issuecomment-834653945.

We should go through the data models found in the `base` module and verify which of those are actually just data transfer objects that only make sense to be created by the SDK. In these cases, we should refactor the class from a public builder pattern to an internal factory. The first candidate that comes to mind is the `RouteProgress` object.

cc @mapbox/navigation-android

**Comment by kmadsen** [comment]
https://github.com/mapbox/mapbox-navigation-android/issues/4492

This may help us with creating tests around native object providers.
