### ISSUE TITLE
Should expose libnavui-resources

### ISSUE THREAD

**Issue by abhishek1508** [mapbox/mapbox-navigation-android#4422]
Cutting this ticket to start discussion on whether `libnavigation-android` should expose libnavui-resources. This module specifies various resources used by other modules throughout the UI components such as `colors.xml`, `dimensions.xml` etc. 

I don't think this is required to be exposed publicly as it is only used internally within other modules.

Thoughts @mapbox/navigation-android

**Comment by LukasPaczos** [comment]
I agree that we shouldn't expose this module, it doesn't seem to contain any values that developers could or should take advantage of.

**Comment by zugaldia** [comment]
If we agree that we shouldn't expose it, should we close this ticket? Or is the goal to hide it because it's already exposed? If the latter, we should prioritize this work considering it's a release blocker.

**Comment by LukasPaczos** [comment]
It's the latter that needs to be addressed.
