### ISSUE TITLE
Duplicate maneuver in upcoming maneuver list

### ISSUE THREAD

**Issue by abhishek1508** [mapbox/mapbox-navigation-android#4430]
<img src="https://user-images.githubusercontent.com/9770186/119108315-b1947500-ba3d-11eb-889f-fe39d540eba7.png" width="300"/>

I would like to take a moment and explain what exactly is happening. Looking deeper you would find that this is how directions response is structured. Duplicate maneuver in the upcoming maneuver list is something that originates from directions response.

Look at this URL:
https://api.mapbox.com/directions/v5/mapbox/driving-traffic/-121.981985,37.529766;-121.985686,37.523983?access_token=<**YOUR_ACCESS_TOKEN**>&geometries=polyline6&overview=full&steps=true&continue_straight=true&annotations=congestion%2Cmaxspeed%2Cspeed%2Cduration%2Cdistance%2Cclosure&language=en&roundabout_exits=true&banner_instructions=true&enable_refresh=true

A part of the response from the above route request is shown below. 

```
"steps": [
    {},
    {},
    {
	"intersections": [],
	"bannerInstructions": [
	    {
                "sub": {},
		"primary": {
		    "components": [
		        {
		            "type": "text",
			    "text": "Spry Common"
		        }
		    ],
		    "type": "turn",
		    "modifier": "right",
		    "text": "Spry Common"
	        },
		"distanceAlongGeometry": 109
	    }
	],
	"speedLimitUnit": "mph",
	"maneuver": {},
	"speedLimitSign": "mutcd",
	"name": "Marietta Drive",
	"weight_typical": 20.715,
	"duration_typical": 14.268,
	"duration": 14.268,
	"distance": 109,
	"driving_side": "right",
	"weight": 20.715,
	"mode": "driving",
	"geometry": "sjiqfAxwltgF~LmZlLsXbBaDTcF"
    },
    {
	"intersections": [],
	"bannerInstructions": [
            {
		"sub": {},
		"primary": {
		    "components": [
			{
			    "type": "text",
		            "text": "Spry Common"
		        }
	            ],
		    "type": "turn",
		    "modifier": "right",
		    "text": "Spry Common"
		},
		"distanceAlongGeometry": 23
	    }
	],
	"speedLimitUnit": "mph",
	"maneuver": {},
        "speedLimitSign": "mutcd",
	"name": "Spry Common",
	"weight_typical": 19.033,
	"duration_typical": 13.126,
	"duration": 13.126,
	"distance": 23,
	"driving_side": "right",
	"weight": 19.033,
	"mode": "driving",
	"geometry": "kkhqfApvjtgFxB`D`DvE"
    },
    {},
    {},
    {}
```

Looking at the section of response shown above, you would notice that the `Street` > `Spry Common` is emitted twice in 2 consecutive steps. 1st time with `distanceAlongGeometry` value of 109 and next time with `distanceAlongGeometry` value of 23. 

Navigation SDK Android v2.0 currently goes through all the steps in the route response. It reads the `bannerInstructions` object and parses it into a `Maneuver` object which can be directly rendered onto any UI because `Maneuver` holds the data in primitive data type transitively. The Nav SDK Android v2.0 doesn't add any additional logic to modify the list, but display the information from directions response as is. In the scenario explained above, what you are seeing are 2 same instructions with different total step distance values. 

However, we are aware of this behavior and are in talks to add some additional logic to filter out the list in a way so that it doesn't display duplicate instructions. 

### Expected behavior
Mapbox Navigation SDK Android v2.0 should not display duplicate maneuvers in upcoming maneuver list.

### Actual behavior
Mapbox Navigation SDK Android v2.0 displays duplicate maneuvers in upcoming maneuver list.

This is a good example of inconsistency between iOS/Android platform implementations. Is this something that should probably be handled by NavNative cc @etl @zugaldia @jyrigo @AhmerKhan1 @mapbox/navigation-android

**Comment by Guardiola31337** [comment]
cc'ing @mapbox/navigation-ios @1ec5 for visibility

**Comment by Guardiola31337** [comment]
Refs. https://github.com/mapbox/mapbox-navigation-android/issues/4404

**Comment by abhishek1508** [comment]
Refs. #4564 
Closing the other one @Guardiola31337
