### ISSUE TITLE
Change the maneuver API signature

### ISSUE THREAD

**Issue by abhishek1508** [mapbox/mapbox-navigation-android#4432]
### What do we have now?

`MapboxManeuverApi` supports multiple API mentioned below

```
fun getManeuver(callback: ManeuverCallback)

fun getStepDistanceRemaining(callback: StepDistanceRemainingCallback)

fun getUpcomingManeuverList(callback: UpcomingManeuverListCallback)
```

Looking at the API's above, it is observed that all API's are asynchronous in nature as the results are obtained via callback.

#### Possible limitations

* The maneuver state can change in between requesting the maneuvers and getting them like when we go off route
* There is noticeable delay between when the maneuver data is requested and when it is rendered because the logic internally requests route shield and then converts it into `Bitmap`

### Proposal

The proposal are as follows:
* Change the signature of API to make them synchronous. 
   ```
    fun getManeuver(): Maneuver

    fun getStepDistanceRemaining(): Double

    fun getUpcomingManeuverList(): List<Maneuver>
    ```
* Navigation SDK won't request the route shields but return them in the form of a URL and allow clients to request them.
* Expose another API that would take this URL for route shield, request it and return a `Bitmap`. This API would be unto the client to use, or they can have their own rendering engine that would be responsible to request the image in `.svg` format and convert it to `Bitmap`.

#### Advantages
* Their won't be any possibility of maneuver state being stale and will always reflect accurate data.
* There won't be any delay in receiving the data, because the SDK won't be making network requests to fetch the route shields.

**_Note: The route shields are received in the form of `SVG`. Any client requesting the route shields using the URL passed, would have to integrate a 3rd party rendering library that would convert `SVG` to `Bitmap` at runtime._**

cc @mapbox/navigation-android @Guardiola31337 @LukasPaczos

**Comment by Guardiola31337** [comment]
Refs. https://github.com/mapbox/mapbox-navigation-android/issues/4404

**Comment by abhishek1508** [comment]
After discussing internally with @LukasPaczos following are the changes that will be incorporated:

* Change the API definition of `MapboxManeuverApi` but they would still remain asynchronous.
* Reveal an API that would allow you to pass a `DirectionRoute`. Based on the route the `MapboxManeuverApi` will maintain a state of the instruction list.
* MapboxManeuverApi will fetch route shields by default. However, it will also expose an option that would allow you to specify if you don't want Mapbox to download the route shields.
* MapboxManeuverApi will return you a route shield url that would allow you to fetch the route shield using your own logic if need be.
* MapboxManeuverApi will render the freeway/highway name and a separate callback will be exposed that would allow you to fetch the route shields.
