### ISSUE TITLE
MapboxMapMatching i get a error

### ISSUE THREAD

**Issue by rayo3199** [mapbox/mapbox-navigation-android#4438]
**Android API: androidx
**Mapbox Navigation SDK version:0.42.6

Steps to trigger behavior
1.I need to generate custom routes and login with those points but it gives me an error

This is my code 

 MapboxMapMatching.builder()
                    .accessToken(getString(R.string.token))
                    .coordinates(stops)
                    .steps(true)
                    .voiceInstructions(true)
                    .bannerInstructions(true)
                    .profile(DirectionsCriteria.PROFILE_DRIVING)
                    .overview(DirectionsCriteria.OVERVIEW_FULL)
                    
                    .build().enqueueCall(new Callback<MapMatchingResponse>() {
                @SuppressLint("WrongConstant")
                @Override
                public void onResponse(Call<MapMatchingResponse> call, Response<MapMatchingResponse> response) {
                    if (response.body() == null) {
                        Toast.makeText(getApplicationContext(),"error",Toast.LENGTH_LONG).show();
                        return;
                    }

                    if (response.isSuccessful()) {
                        currentRoute = response.body().matchings().get(0).toDirectionRoute();
                    }
                    
                    NavigationLauncherOptions options = NavigationLauncherOptions.builder()
                            .directionsRoute(currentRoute)
                            .shouldSimulateRoute(true)
                            .build();

                    NavigationLauncher.startNavigation(navegacionOptimizada
                            .this, options);

                }

                @Override
                public void onFailure(Call<MapMatchingResponse> call, Throwable t) {

                }
            });

and yhe error is this 

java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.Object java.util.List.get(int)' on a null object reference
        at com.example.descubremadrid.navegacionOptimizada$2.onResponse(navegacionOptimizada.java:174)

help me please

**Comment by rayo3199** [comment]
Please, can you help me 

I don´t know where the error is

**Comment by rayo3199** [comment]
@danesfeder  can you help me please?

**Comment by rayo3199** [comment]
the problem is giving me in this section

DirectionsRoute currentRoute = response.body().matchings().get(0).toDirectionRoute();

                            NavigationLauncherOptions options = NavigationLauncherOptions.builder()
                                    .directionsRoute(currentRoute)
                                    .shouldSimulateRoute(true)
                                    .build();

                            NavigationLauncher.startNavigation(Mapboxnavigation.this, options);


does not convert the route well

**Comment by rayo3199** [comment]
@zugaldia

**Comment by rayo3199** [comment]
I have also added these two more things in mapmaching that I have seen in some places but it still does not go and the same error
.voiceUnits("metric")
                .language("sp-SP")

**Comment by zugaldia** [comment]
Thanks for the report. Navigation SDK 0.42.6 is no longer actively maintained, we recommend you switch to Nav SDK [v1](https://docs.mapbox.com/android/navigation/guides/) or [v2](https://docs.mapbox.com/android/beta/navigation/guides/) and re-test this scenario. For additional help, please [contact the support team](https://docs.mapbox.com/help/) at Mapbox.
