### ISSUE TITLE
Incorrect directions presented for roundabouts

### ISSUE THREAD

**Issue by sandyscoffable** [mapbox/mapbox-navigation-android#4440]
Android API: 30
Mapbox Navigation SDK version: 2.0.0-beta.11

**Steps to trigger behavior**
1. Start "Turn by Turn navigation"
2. Plot a route around a roundabout

**Expected behavior**
The turn icon should represent the maneuver that's about to be made

**Actual behavior**
The icon in the top bar is incorrect. These were real world road tests (i.e I wasn't mocking locations). 
It's also worth noting that the speech directions were correct.

Here's some screenshots I managed to grab:
<img width="120" src="https://user-images.githubusercontent.com/20515901/119367810-3edc0180-bcaa-11eb-9390-999d763b26f0.jpg" />
<img width="120" src="https://user-images.githubusercontent.com/20515901/119367815-3f749800-bcaa-11eb-9581-dc9a201da36e.jpg" />
<img width="120" src="https://user-images.githubusercontent.com/20515901/119367804-3e436b00-bcaa-11eb-8cdf-d3ba6e23cbc4.jpg" />

**Comment by sandyscoffable** [comment]
This issue originates from https://github.com/mapbox/mapbox-navigation-android/issues/4270, but I was asked to raise a new issue specifically for roundabouts.

**Comment by abhishek1508** [comment]
Thanks @sandyscoffable 
If possible for you it would be great to share coordinate pair for any of the route above

**Comment by sandyscoffable** [comment]
If I navigate from:
* lat: 55.897528 lng: -3.607295 
to
* lat: 55.890805 lng: -3.623160

Using driving directions, both roundabouts on this small stretch have incorrect directions.
<img width="320" src="https://user-images.githubusercontent.com/20515901/119379697-b5cbc700-bcb7-11eb-9a15-0ca2754f50e3.jpg" />
<img width="320" src="https://user-images.githubusercontent.com/20515901/119379700-b6645d80-bcb7-11eb-96b7-316fcb4c88b6.jpg" />

**Comment by Guardiola31337** [comment]
Hey @sandyscoffable could you please take a screenshot of these instructions with the notification visible? Trying to check if there are any differences between banner and notification. Thanks in advance!

**Comment by sandyscoffable** [comment]
Just to say thanks very much @abhishek1508 , @LukasPaczos - `beta.12` has fixed this issue 💪

**Comment by Guardiola31337** [comment]
Noting that I run into another roundabout issue in https://github.com/mapbox/mapbox-navigation-android/pull/4419#issuecomment-851924272

History file is attached to the ticket but the coordinates of the route are `[[-3.7120423,40.3960153],[-3.7133527,40.4007539]]`

cc @abhishek1508

**Comment by LukasPaczos** [comment]
Could you cut a new ticket @Guardiola31337 so that this doesn't get lost?

**Comment by Guardiola31337** [comment]
> Could you cut a new ticket @Guardiola31337 so that this doesn't get lost?

Sure thing https://github.com/mapbox/mapbox-navigation-android/issues/4466
