### ISSUE TITLE
Evaluate options to avoid waiting for minimum time intervals during instrumentation tests

### ISSUE THREAD

**Issue by LukasPaczos** [mapbox/mapbox-navigation-android#4455]
Some of our features like route refresh or route alternatives have default minimum intervals that when used with small instrumentation tests unnecessarily increase the execution time while we're mostly idle.

We should find a way to speed those up with clever internal implementation mechanics and parallelization (Test Orchestrator and [Firebase sharding](https://firebase.google.com/docs/test-lab/android/instrumentation-test#sharding)).

Refs https://github.com/mapbox/mapbox-navigation-android/pull/4427#discussion_r639929315.

cc @mapbox/navigation-android

**Comment by LukasPaczos** [comment]
I like that idea :+1: Run the checks for release builds and disable for debug builds.

**Comment by kmadsen** [comment]
Run times of the tests are not easily seen on firebase main page, but can be found here
[Firebase](https://console.firebase.google.com/u/0/project/mapbox-navigation-android/testlab/histories/bh.54eb2dd57e959221/matrices/4817286562165934952/executions/bs.7aaba363465e33f2) > [Test Results](https://console.cloud.google.com/storage/browser/test-lab-052kt7ra614ai-hjrc98wu2tksc/2021-05-27_14:19:00.837491_RutZ/walleye-28-de-landscape?authuser=0) > [test_result_1.xml](https://console.cloud.google.com/storage/browser/_details/test-lab-052kt7ra614ai-hjrc98wu2tksc/2021-05-27_14:19:00.837491_RutZ/walleye-28-de-landscape/test_result_1.xml?authuser=0)
```

<testsuite name="" tests="9" failures="0" errors="0" skipped="0" time="78.918" timestamp="2021-05-27T14:31:51" hostname="localhost">
<properties/>
<testcase time="4.514" name="reroute_completes" classname="com.mapbox.navigation.instrumentation_tests.core.CoreRerouteTest"/>
<testcase time="11.393" name="expect_faster_route_alternatives" classname="com.mapbox.navigation.instrumentation_tests.core.RouteAlternativesTest"/>
<testcase time="31.116" name="expect_route_refresh_to_update_traffic_annotations" classname="com.mapbox.navigation.instrumentation_tests.core.RouteRefreshTest"/>
<testcase time="11.41" name="route_completes" classname="com.mapbox.navigation.instrumentation_tests.core.SanityCoreRouteTes"/>
<testcase time="15.067" name="route_completes" classname="com.mapbox.navigation.instrumentation_tests.ui.SanityUiRouteTest"/>
<testcase time="1.531" name="selectAlternateRoute" classname="com.mapbox.navigation.instrumentation_tests.ui.routeline.AlternativeRouteSelectionTest"/>
<testcase time="1.379" name="multipleSetRouteCall_longAndShortRouteTest" classname="com.mapbox.navigation.instrumentation_tests.ui.routeline.SetRouteOrderTest"/>
<testcase time="1.179" name="clearRoutesTest" classname="com.mapbox.navigation.instrumentation_tests.ui.routeline.SetRouteOrderTest"/>
<testcase time="1.329" name="multipleSetRouteCall_longAndShortRouteSameConsumerTest" classname="com.mapbox.navigation.instrumentation_tests.ui.routeline.SetRouteOrderTest"/>
</testsuite>
```

**Comment by Guardiola31337** [comment]
Refs. https://github.com/mapbox/mapbox-navigation-android/pull/4904

cc @abhishek1508

**Comment by Guardiola31337** [comment]
cc'ing @VysotskiVadim for visibility

**Comment by VysotskiVadim** [comment]
> cc'ing @VysotskiVadim for visibility

Thanks. I've already sped-up the route refresh test by a workaround based on reflection: https://github.com/mapbox/mapbox-navigation-android/blob/main/instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/core/RouteRefreshTest.kt#L86

It doesn't seem that `expect_initial_alternative_route_removed_after_navigating_past` depends on route alternative interval as it completes in 4 seconds.

@LukasPaczos , are you okay to close the ticket?

**Comment by LukasPaczos** [comment]
Since cutting the ticket I couldn't find a clearer, non-invasive way of overriding the defaults besides reflection, so I guess we can close this ticket.

Test parallelization would be good topic to keep in the back of our heads though, in case the instrumentation tests become the longest CI job at any time.

cc @MrSwimmer for visibility
