### ISSUE TITLE
Incorrect roundabout icons

### ISSUE THREAD

**Issue by Guardiola31337** [mapbox/mapbox-navigation-android#4466]
Capturing from https://github.com/mapbox/mapbox-navigation-android/issues/4440#issuecomment-852063122

> Noting that I run into another roundabout issue in https://github.com/mapbox/mapbox-navigation-android/pull/4419#issuecomment-851924272
>
> History file is attached to the ticket but the coordinates of the route are `[[-3.7120423,40.3960153],[-3.7133527,40.4007539]]`
>
> cc @abhishek1508 

Noting that the icon is incorrect for both the banner and the notification.

**Comment by Guardiola31337** [comment]
Request URL 👇 

`https://api.mapbox.com/directions/v5/mapbox/driving-traffic/-3.713149,40.396539;-3.713126,40.400995?access_token=<YOUR_MAPBOX_ACCESS>&geometries=polyline6&overview=full&steps=true&continue_straight=true&annotations=congestion%2Cmaxspeed%2Cspeed%2Cduration%2Cdistance%2Cclosure&language=en&roundabout_exits=true&voice_instructions=true&banner_instructions=true&voice_units=imperial&enable_refresh=true`

**Comment by Guardiola31337** [comment]
Further details https://github.com/mapbox/mapbox-navigation-android/issues/4517

cc @abhishek1508 @LukasPaczos

**Comment by abhishek1508** [comment]
This is fixed.

![Screenshot_1643048576](https://user-images.githubusercontent.com/9770186/150841980-3e189148-853a-4f15-822d-8c39967523f0.png)
