### ISSUE TITLE
MockLocationEngine better handle Android lifecycle

### ISSUE THREAD

**Issue by cammace** [mapbox/mapbox-navigation-android#447]
_Originally ticketed in https://github.com/mapbox/mapbox-java/issues/497 by @danesfeder_

Currently if you deactivate the MockLocationEngine (like on config change) you need a DirectionsRoute and user Position to re-activate and start sending updates again. If we can handle this within the class itself, dealing with state changes would be much easier

**Comment by danesfeder** [comment]
Closing as stale with the `ReplayRouteLocationEngine` cc @Guardiola31337
