### ISSUE TITLE
Writing unit test for native function interactions

### ISSUE THREAD

**Issue by kmadsen** [mapbox/mapbox-navigation-android#4492]
https://github.com/mockk/mockk/issues/639

Found this issue because there are tricky lifecycle issues worth testing, specifically for testing history recording interfaces https://github.com/mapbox/mapbox-navigation-android/pull/4488

The solution we are agreeing on, is to create wrapper classes for the navigation SDK. Which are then provided through factory functions. This way we can properly mock the native functions.

It seems more we are getting more interfaces like this, because the latest upgrade is causing issues https://github.com/mapbox/mapbox-navigation-android/pull/4518

## Discussion

If this is something we need for every interaction with nav-native and native libraries. We should discuss, covering this with code generation. Because the nav-native classes are indeed, code generated.

What we did for the history recorder, was with full [instrumentation_tests](https://github.com/mapbox/mapbox-navigation-android/blob/15bf16ad7229dd8d1b9d39647625d002a07ce9ce/instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/core/MapboxHistoryTest.kt#L149-L153). But we should still be able to test with JUnit, which makes code generation an ideal solution

**Comment by kmadsen** [comment]
I'm starting a list here, of classes that need a pattern here for testing

- MapboxNativeNavigatorImpl (many native classes have their wrapper functions start here)
- MapboxHistoryReader
- RoadObjectsStore

Examples to build on top of
 - GraphAccessor
 - MapboxOnboardRouterTest
 - TilesetDescriptorFactory

**Comment by kmadsen** [comment]
We're discussing a log for when `HistoryRecorderHandle.build` returns null. When we build a wrapper class for `HistoryRecorderHandle`

This may be an appropriate place to put this kind of error log

**Comment by kmadsen** [comment]
cc: @mskurydin @SiarheiFedartsou @tobrun 

Wondering if you guys have created a solution for this already. The native interfaces are already code generated, so maybe we can generate non-native interface for objects like these.

For example:
``` kotlin
// This file is generated and will be overwritten automatically.

package com.mapbox.navigator;

import androidx.annotation.NonNull;
import com.mapbox.geojson.Geometry;

/** can be returned from Route Alerts API */
public class RouteAlertLocation {

    protected long peer;

    protected RouteAlertLocation(long peer) {
        this.peer = peer;
    }

    /** raw shape */
    @NonNull
    public native Geometry getShape(); < == cannot be mocked with mockk

    protected native void finalize() throws Throwable;

}
```

**Comment by LukasPaczos** [comment]
@kmadsen this is already practiced in other projects for the generated classes to have companion interfaces.

For example:
```java
public interface RouteAlertLocationInterface {
  Geometry getShape();
}
```
and then:
```java
public class RouteAlertLocation {

    protected long peer;

    protected RouteAlertLocation(long peer) {
        this.peer = peer;
    }

    /** raw shape */
    @NonNull
    public native Geometry getShape();
    protected native void finalize() throws Throwable;
}
```

The SDK would program only against the interface which would make it possible to mock.

This can be achieved by adding the `extract_interface` bindgen argument for java targets which will generate a companion Java `interface` for every Java `class`.

**Comment by tobrun** [comment]
:+1: on above, this should the standard way of working.

I do want to call out an additional configuration to work around using native components in JVM unit tests, more concretely in cases where you are using static methods on bindgen classes. We can't fix this with using a java interface. With using Shadow configurations from roboelectric, you can work around this. 

For example, if your code uses Logger from common SDK, it will crash with an unsatisfiedlinkerror. To fix this, we used a [ShadowLogger](https://github.com/mapbox/mapbox-maps-android/blob/main/sdk/src/test/java/com/mapbox/common/ShadowLogger.java) implementation, which is configured through an [annotation](https://github.com/mapbox/mapbox-maps-android/blob/main/sdk/src/test/java/com/mapbox/maps/MapControllerTest.kt#L22-L24).

**Comment by kmadsen** [comment]
`extract_interface` was exactly what I was hoping for. That way we aren't manually adding these interfaces to everything. Thanks @LukasPaczos for adding the codegen parameter, I'm assuming we'll have everything we need in the next native release.

Also thanks @tobrun for the other issue we would need a something like `ShadowLogger`. 

Closing this issue as we'll have what we need to update the tests
