### ISSUE TITLE
mapbox 5.2 alpha freeze when changing fragment

### ISSUE THREAD

**Issue by no-body** [mapbox/mapbox-navigation-android#450]
Hi everyone, 

I'm using a mapbox on an Android App and I have some bugs when I switch to my mapboxfragment and then I go back or go to another fragment quickly.

I have override all Lifecycle methods, but this seems doesn't change anythings.
In addition, I have no logs about this freeze..

I get this error:
activitymanager 
Reason: Input dispatching timed out (Waiting to send key event because the focused window has not finished processing all of the input events that were previously delivered to it.  Outbound queue length: 0.  Wait queue length: 4.)

Some info:
        minSdkVersion 20
        targetSdkVersion 22
       compile('com.mapbox.mapboxsdk:mapbox-android-sdk:5.2.0-beta.2@aar')

Do you have any idea to fix it ?
Thanks for your answer.

**Comment by P-Zenker** [comment]
I had the same issue. My workaround is a flag which indicates, if the Map is ready or not. If not, I don't allow `super.onBackPressed();` inside `@Override public void onBackPressed() { ... } `.
But this clearly doesn't fix the issue ;)

**Comment by danesfeder** [comment]
This looks to be an issue with the Maps SDK.  Can you please try to reproduce with `5.2.0` (non-beta) and if the issue persists, raise an issue in https://github.com/mapbox/mapbox-gl-native/issues?  Thanks!  

cc @tobrun

**Comment by dgadelha** [comment]
Just in case someone also ends up here trying to find a fix, try this: https://github.com/mapbox/mapbox-gl-native/issues/10809
