### ISSUE TITLE
Re-routing while in OnNavigationReady in android

### ISSUE THREAD

**Issue by developergirl53** [mapbox/mapbox-navigation-android#4504]
How to use re routing feature of mapBoxNavActivity

In onNavigationReady I want to implement re- routing feature by getting new waypoint always so I want to get the new route while doing navigation on map dynamically evertime.

When the waypoint list change again the re-routing should happen.

**Comment by LukasPaczos** [comment]
Hey @developergirl53 this repository is for bug reports and feature requests. Feel free to reach out to https://www.mapbox.com/support if need any additional assistance.
