### ISSUE TITLE
Align trip notification and maneuver view rendering

### ISSUE THREAD

**Issue by LukasPaczos** [mapbox/mapbox-navigation-android#4513]
Currently `MapboxTripNotification` uses paint code to draw the maneuver arrows, while the `MapboxManeuverView` uses predefined resources. This not only is unnecessary duplication, but we also currently count the paint code generated classes (~2k lines and many more instructions) into our code coverage metric, unnecessarily negatively impacting it.

cc @mapbox/navigation-android

**Comment by Guardiola31337** [comment]
Duplicate of https://github.com/mapbox/mapbox-navigation-android/issues/4193 https://github.com/mapbox/mapbox-navigation-android/issues/1697?

**Comment by LukasPaczos** [comment]
Closing in favor of https://github.com/mapbox/mapbox-navigation-android/issues/4193.
