### ISSUE TITLE
Roundabouts instructions and icons are back to front

### ISSUE THREAD

**Issue by clinkadink** [mapbox/mapbox-navigation-android#4517]
**Android API:** 28
**Mapbox Navigation SDK version:** 
com.mapbox.navigation:android:2.0.0-beta.12
com.mapbox.search:mapbox-search-android-ui:1.0.0-beta.14
com.mapbox.maps:android:10.0.0-beta.21

I am using the latest Android Navigation SDK (v2) here in the UK. I have copied/pasted the example located [here](https://docs.mapbox.com/android/beta/navigation/examples/basic/).

The roundabout icons and instructions are incorrect. See screenshot below. This example shows the problem that happens every day. The route line is turning left, taking the first exit off the roundabout, but the instruction and icon states that I must turn right, and take the last exit of the roundabout.

Is there a setting somewhere that I have missed to tell Mapbox that I drive on the left of the road, and not the right (which is default I assume)? I have seen `drivingMode` and tried setting this to 'left', but it makes no difference, the icons/instructions are still wrong. 

Note: I do recall seeing this issue raised here a couple of years back, but I thought it was resolved.

Is this a bug or is this my fault? 🤷‍♂️

### Steps to trigger behavior

 1. Develop app with latest Android Navigation SDK v2
 2. Install in Android head unit in car
 3. Drive through roundabouts and become totally confused

### Expected behavior
The instructions and icons match the route line and are correct

### Actual behavior
The instructions and icons are the opposite of the route line and are incorrect

![image](https://user-images.githubusercontent.com/33834551/122388544-e2e26100-cf67-11eb-8886-0f6bea57017c.png)

**Comment by Guardiola31337** [comment]
Hey @clinkadink thanks for reaching out and report your issue.

We're looking into this in https://github.com/mapbox/mapbox-navigation-android/issues/4466

Closing as duplicated.
