### ISSUE TITLE
Changing tooltip texts in ready components

### ISSUE THREAD

**Issue by Artur512** [mapbox/mapbox-navigation-android#4524]
Please add possibility to change tooltip texts in ready to use components:
MapboxSoundButton
MapboxRecenterButton
MapboxRouteOverviewButton

**Comment by Guardiola31337** [comment]
Hey @Zayankovsky as you recently worked on https://github.com/mapbox/mapbox-navigation-android/pull/4697 could you take a look at this when you have a chance? 🙏

**Comment by Zayankovsky** [comment]
@Artur512, with the next beta there will be a new optional argument `text` in `showTextAndExtend`, `muteAndExtend` and `unmuteAndExtend` functions, which allows you to show custom text, when the view is in the extended mode.
