### ISSUE TITLE
Add more code examples to Electronic Horizon docs

### ISSUE THREAD

**Issue by 0v3rt1r3d** [mapbox/mapbox-navigation-android#4550]
We have multiple customers who already want to use Ehorizon API, but we have no way to provide a great code example. There is the [doc](https://docs.mapbox.com/android/navigation/guides/electronic-horizon/), but it's not exhaustible. We have already written a code example of android sdk usage [here](https://docs.google.com/document/d/1p69oWyIy8MoQahSxQYRGm9_HEY0Q6p0FnKlKkduAcQs/edit), could you add it to your docs or maybe you have an example in your repo and the snippet could be added there?

**Comment by 0v3rt1r3d** [comment]
cc @LukasPaczos

**Comment by korshaknn** [comment]
@0v3rt1r3d we have updated docs for EH_v3/v4 https://docs.mapbox.com/android/beta/navigation/guides/electronic-horizon/
also, there is a PR with some additions/fixes https://github.com/mapbox/android-docs/pull/1744

I think we should not provide some complex example how to use EH, just separate small use-cases
- start/stop EH observing
- add custom objects
- how to work with objects store / graph accessor
- get upcoming road objects

**Comment by korshaknn** [comment]
EHorizon docs have been updated, code snippets have been added. 
Closing for now, let's reopen if need to add more docs
