### ISSUE TITLE
Mapbox navigation failing to produce route progress

### ISSUE THREAD

**Issue by shikoko** [mapbox/mapbox-navigation-android#4574]
We have a custom view that handles all the UI operations regarding the mapbox implementation.
That custom view is being wrapped by a fragment that handles all the necessary navigation events.
We have hidden all the mapbox navigation listeners in a repository pattern. We listen to those to update the UI and send route progress to our backend. This setup works only once despite us calling stop and destroy methods as described in the documentation.
When we launch the fragment the second time, we only get route changes and banner instructions, we don't get the enhanced location nor route progress updates anymore.
But when we do get them, the map is frozen. From time to time, randomly, we get all the updates we need and the map behaves just fine.

**Android API:** 10.0.0-rc.1
**Mapbox Navigation SDK version:** 2.0.0-beta.15

### Steps to trigger behavior

 1. Launch a navigation fragment
 2. Start navigated drive
 3. Call stop navigation
 4. Close the fragment
 5. Open the fragment
 6. Start a navigated drive

### Expected behavior
Mapbox sends us the enhanced location and other updates. MapView renders the route

### Actual behavior
No enhanced location updates being received. MapView is frozen

**Comment by cafesilencio** [comment]
@shikoko Can you please indicate when in your fragment's lifecycle you are registering the `LocationObserver` as well as the `RouteProgressObserver` with `MapboxNavigation`. Better yet, if possible can you post your fragment's source here omitting anything that would be private to your organization?

**Comment by shikoko** [comment]
I've actually managed to fix the issue. It appears that once you call destroy on Mapbox, there's no way back. You have to recreate all the dependencies for it to work properly.

**Comment by cafesilencio** [comment]
Thanks for the update. I'm going to close this issue.
