### ISSUE TITLE
NavigationTripNotification has been excluded from build but a correct alternative was not provided.

### ISSUE THREAD

**Issue by nasmuris** [mapbox/mapbox-navigation-android#4596]
Hello, I'm trying to migrate from v0.42.6 to newest stable release but when calling
```
NavigationOptions.Builder navigationOptions = new NavigationOptions.Builder(reactContext);
navigationOptions.accessToken(options.accessToken);
navigation = new MapboxNavigation(navigationOptions.build());
```
I'm receiving following exception:

> NavigationTripNotification has been excluded from build but a correct alternative was not provided.
Make sure that:
> - Your custom module implements com.mapbox.navigation.base.trip.notification.TripNotification.
> - Your custom module class is annotated with @MapboxModule(MapboxModuleType.NavigationTripNotification).
> - You've provided a `ModuleProvider` instance to Mapbox_TripNotificationModuleConfiguration#setModuleProvider before initializing the library,
  unless `enableConfiguration` flag is set to false and your implementation has a public, non-arg constructor or is a Kotlin object.

I'm have no idea why should TripNotification be excluded

```
implementation "com.mapbox.navigation:core:1.6.1" // the same with navigation:ui
implementation 'com.mapbox.mapboxsdk:mapbox-sdk-turf:5.8.0'
```
**Mapbox Navigation SDK version: 1.6.1**

**Comment by LukasPaczos** [comment]
Hey @nasmuris @sjd753, sorry for a late reply!

Whenever you run into an invalid module exception, there should be logged attempts at different creation methods for a module - one of these stacks will have the underlying reason.

If you are still running into this issue, please create a new ticket and share that full log of right before the exception is thrown, thanks!

**Comment by Buthrakaur** [comment]
I was fighting this issue after an update from 0.42.6 to 1.6.2 and realized it's just about missing `distanceFormatter` in `NavigationOptions` - the error message is unfortunately totally confusing :( This piece of code works well:

```
            Locale locale = ContextEx.inferDeviceLocale(reactContext);
            String unitType = LocaleEx.getUnitTypeForLocale(locale);
            MapboxDistanceFormatter distanceFormatter = new MapboxDistanceFormatter.Builder(reactContext)
                    .unitType(unitType)
                    .roundingIncrement(1)
                    .locale(locale)
                    .build();

            NavigationOptions opt = new NavigationOptions.Builder(reactContext)
                    .accessToken(navigationnOptions.accessToken)
                    .isFromNavigationUi(false)
                    .distanceFormatter(distanceFormatter)
                    .build();
```
