### ISSUE TITLE
Add default params to TripProgressUpdateFormatter.Builder

### ISSUE THREAD

**Issue by korshaknn** [mapbox/mapbox-navigation-android#4598]
We should add default formatters to `TripProgressUpdateFormatter.Builder`
so, if there is no need to change default behaviour, formatter is constructed with
`val formatter = TripProgressUpdateFormatter.Builder().build()`

**Comment by Zayankovsky** [comment]
Seems like it already works that way, since we create default formatters in `build` method, if some of them were not provided.

**Comment by truburt** [comment]
Done.
