### ISSUE TITLE
Simulation Route can't be complete

### ISSUE THREAD

**Issue by KayHung** [mapbox/mapbox-navigation-android#4599]
Simulation Route can't be complete, it can't reach the target point.

I run this example
https://github.com/mapbox/mapbox-navigation-android/blob/main/examples/src/main/java/com/mapbox/navigation/examples/core/MapboxCustomStyleActivity.kt

I make a long distance route and start simulation, 
but after a while, the car position suddenly go back to start point and restart the simulation route.
The screen show the toast message, Could not find the RouteLeg.

**Mapbox Navigation SDK version:**
'com.mapbox.navigation:android:2.0.0-beta.17'

**Comment by cafesilencio** [comment]
The simulator is a testing tool and doesn't often handle long routes with the same accuracy as actually navigating a route. Do you have a use case that requires simulating a long route?

**Comment by KayHung** [comment]
@cafesilencio 
In Navigation Sdk v1, it can simulating a long route.
Why it can't be simulate a long route in navigation sdk v2?
I use it for a long time test.

**Comment by cafesilencio** [comment]
@kmadsen Do you have any details you can share?

**Comment by LukasPaczos** [comment]
This is a problem with the example itself, the example resets the simulation whenever a route changes:
https://github.com/mapbox/mapbox-navigation-android/blob/d06b8e65eacaf4e4b2838cd09634b58a6697d29f/examples/src/main/java/com/mapbox/navigation/examples/core/MapboxCustomStyleActivity.kt#L160

and the route change can be triggered by a route refresh (that updates congestion and other annotations) that happens every ~5 minutes. Tweaking your example to not restart the simulation on each route change but only when the route is actually different (see `DirectionsRoute#isSameRoute()`) should fix the problem.

Closing but please let us know if that didn't help.

**Comment by KayHung** [comment]
@LukasPaczos 
I set enableRefresh(false) when simulate route, is this a right way to fix this problem?

**Comment by LukasPaczos** [comment]
That works as well but if you'd like to keep the refresh ability, I recommend the above suggestion.
