### ISSUE TITLE
Add testapp activity using Lost Location

### ISSUE THREAD

**Issue by cammace** [mapbox/mapbox-navigation-android#46]
Currently, the navigation example in the testapps using mock location engine, a separate activity should be created using the LOST location provider.

**Comment by olheimer** [comment]
There is a documentation: https://www.mapbox.com/android-docs/navigation/latest/getting-started/
But unfortuanetley for me it doesn't work.
After calling the LocationEngine with activate it seems to request/receive location updates. But when I call endNavigation() in onDestroy (the navigation is runnning in a Service) the locationEngine does not quit requesting location updates (GPS notfication icon in the status bar is still on).

**Comment by cammace** [comment]
Sounds like the same issue that's being reported in https://github.com/mapbox/mapbox-gl-native/issues/9068. If I recall, this is an issue on Mapzen's end.

**Comment by cammace** [comment]
With the Navigation UI work, we now have a testapp activity which can either use mock location or LOST. Closing.
