### ISSUE TITLE
The maneuver icon to indicate "turn sharp left" shows a right arrow 

### ISSUE THREAD

**Issue by palto-blubek** [mapbox/mapbox-navigation-android#461]
This icon:
https://github.com/mapbox/mapbox-navigation-android/blob/master/libandroid-navigation/src/main/res/drawable/ic_maneuver_turn_75_left.xml
Is used in `ManeuverMap` to mean turn sharp left.  
But the drawing actually is a sharp **right** icon (actually it is the same as `ic_maneuver_turn_75`).

**Comment by danesfeder** [comment]
@palto-blubek Can you confirm this is fixed with #445?

**Comment by danesfeder** [comment]
Closed with #445
