### ISSUE TITLE
Nav SDK 2.0 example not working

### ISSUE THREAD

**Issue by 32Vache** [mapbox/mapbox-navigation-android#4619]
The example at https://docs.mapbox.com/android/beta/navigation/examples/basic/ for Nav SDK 2.0 does not work. After following the installation instructions, i just copy pasted the MainActivity.kt code and a whole lot of errors appear an android studio

import com.mapbox.navigation.ui.base.model.Expected "Unresolved refrence Expected" which causes all "Excepted" in the code like is Expected.Success to error.

Same behaviour for
import com.mapbox.navigation.ui.maneuver.api.StepDistanceRemainingCallback
import com.mapbox.navigation.ui.maneuver.api.UpcomingManeuverListCallback
import com.mapbox.navigation.ui.maneuver.model.StepDistanceError

Im not super good at kotlin so sorry if i'm missing something.

I have correctly added dependencies in build.gradle

    implementation "com.mapbox.navigation:android:2.0.0-beta.18"
    implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-android:1.4.2'

Running build just errors with Unresolved refrence Expected

**Comment by Fritoo** [comment]
@abhishek1508 This still appears to be occurring in `2.0.0-beta.20`. Any ideas what we can do?

**Comment by abhishek1508** [comment]
@Fritoo @32Vache Sorry for the delay but the example is now updated. It is using the latest `2.0.0-beta.21`.

**Comment by 32Vache** [comment]
Hello, been testing the example with beta22 and it works perfectly
![](https://user-images.githubusercontent.com/42336759/129609473-a5823f39-068a-49c2-a312-02920bebb7f2.jpg)
