### ISSUE TITLE
Route Fresh Controller shouldn't log RouteRefresh warnings where there is no active route

### ISSUE THREAD

**Issue by dudeuter** [mapbox/mapbox-navigation-android#4625]
**Android API: 29**
**Mapbox Navigation SDK version: beta19**

### Steps to trigger behavior
mapboxNavigation.setRoutes(listOf())
wait for route refresh

### Expected behavior
nothing

### Actual behavior
logs warning
```
2021-07-15 19:10:37.813 13452-13452/com.mapbox.navigation.examples W/MbxRouteRefreshController: The route is not qualified for route refresh feature.
    See com.mapbox.navigation.base.extensions.supportsRouteRefresh
    extension for details.
    null
```

The offending logic:

https://github.com/mapbox/mapbox-navigation-android/blob/350dbfd764ad2d989d26bd088bb37ae6bdbd31c4/libnavigation-core/src/main/java/com/mapbox/navigation/core/routerefresh/RouteRefreshController.kt#L67-L92

either, the route refresh controller shouldn't be called without an active route, or the warning should be guarded by `RouteOptions#supportsRouteRefresh` as the purpose of this warning seems to help users who are trying to refresh active routes that don't support route refresh. 

this seems like a one-liner

fyi @LukasPaczos

**Comment by Zayankovsky** [comment]
Fixed in #4655.
