### ISSUE TITLE
Maneuver icons for roundabout are smaller than the other ones

### ISSUE THREAD

**Issue by palto-blubek** [mapbox/mapbox-navigation-android#463]
We are using `ManeuverUtils.getManeuverResource()` to show the maneuver icon to the user.

For some reason, these icons don't all have the same sizes, for instance,

https://github.com/mapbox/mapbox-navigation-android/blob/master/libandroid-navigation/src/main/res/drawable/ic_maneuver_turn_0.xml : 50dp * 50dp

https://github.com/mapbox/mapbox-navigation-android/blob/master/libandroid-navigation/src/main/res/drawable/ic_maneuver_roundabout_slight_right.xml : 20dp * 20dp

**Comment by danesfeder** [comment]
@palto-blubek Our icons were not ideal or optimized as you've found - in https://github.com/mapbox/mapbox-navigation-android/pull/445 we've included a custom `ManeuverView` that draws each icon dynamically and should scale to the width / height you set.

**Comment by cammace** [comment]
#445 has been merged, should we still fix the drawable @danesfeder or are we safe to close here?

**Comment by danesfeder** [comment]
Should be fixed with #445
