### ISSUE TITLE
Telemetry cancel event is triggered for completed routes

### ISSUE THREAD

**Issue by kmadsen** [mapbox/mapbox-navigation-android#4633]
mapbox-navigation-android/1.5.1

top left: depart 05:31
middle: arrive  05:36
right: cancel 06:09

![Screen Shot 2021-07-16 at 12 16 02 PM](https://user-images.githubusercontent.com/3021882/125999881-c2797a21-30b5-428f-9a5d-02bb91e4044c.png)

The cancel event does not account for arrival. 

https://github.com/mapbox/mapbox-navigation-android/blob/350dbfd764ad2d989d26bd088bb37ae6bdbd31c4/libnavigation-core/src/main/java/com/mapbox/navigation/core/telemetry/MapboxNavigationTelemetry.kt#L507-L518

**Comment by RingerJK** [comment]
For this version snapshot code, Telemetry triggers `cancel event` when the SDK switches from ActiveGuidance to FreeDrive or Idle state, it's not happening with the current Telemetry version
