### ISSUE TITLE
Couldn't able to import classes for mapbox navigation

### ISSUE THREAD

**Issue by tmanasa96** [mapbox/mapbox-navigation-android#4654]
**Android API:**
**Mapbox Navigation SDK version:**

### Steps to trigger behavior

 1. I was trying to run the mapbox navigation 
 
 2. But unfortunately i was not able to import 2 classes. 
     i.  import com.mapbox.navigation.base.extensions.applyDefaultNavigationOptions
     ii. import com.mapbox.navigation.base.extensions.applyLanguageAndVoiceUnitOptions

 3.These are my gradle dependencies:
       i.  implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-android:1.5.0'
       ii. implementation "com.mapbox.navigation:android:2.0.0-beta.9"

### Expected behavior

I have tried adding mapbox navigation dependencies from https://github.com/mapbox/mapbox-navigation-android/blob/main/gradle/dependencies.gradle
 but this is not helping to solve my problem.

**Comment by LukasPaczos** [comment]
The extensions you listed were only added in [`v2.0.0-beta.10`](https://github.com/mapbox/mapbox-navigation-android/releases/tag/v2.0.0-beta.10). Please try that or a later version.
