### ISSUE TITLE
OnMapLoadError: STYLE: Failed to load style: HTTP status code 401

### ISSUE THREAD

**Issue by yiwenzhang666999** [mapbox/mapbox-navigation-android#4668]
hi,When I run the example（https://github.com/mapbox/mapbox-navigation-android/tree/main/examples）, it runs successfully, but the map does not display. The following error is reported. Do I need to set the style of the map?
 
<img width="690" alt="1" src="https://user-images.githubusercontent.com/31643589/127124364-c9d2fd58-4aa5-46e9-b2d0-5b2db8b0fc86.png">

<img width="235" alt="2" src="https://user-images.githubusercontent.com/31643589/127124503-6aa72a4b-a09a-42f5-abed-548b7d23529f.png">

**Comment by cafesilencio** [comment]
This may be the result of not setting the map access token. For the examples look for a file in the res/values folder of the examples module called mapbox_access_token.xml and put your access token in the mapbox_access_token element.  If you don't have this file create it as it is used by the examples.

```
<?xml version="1.0" encoding="utf-8"?>
    <resources xmlns:tools="http://schemas.android.com/tools">
    <string name="mapbox_access_token" translatable="false" tools:ignore="UnusedResources">TokenHere</string>
</resources>
```

**Comment by yiwenzhang666999** [comment]
@cafesilencio After I set mapbox_ access_ The token map is displayed normally. Thank you very much
