### ISSUE TITLE
Selecting a leg programatically when starting navigation

### ISSUE THREAD

**Issue by samcrawford** [mapbox/mapbox-navigation-android#4681]
I'm using Mapbox Navigation 1.6.1 and sometimes users want to start navigation mid-way through a multi-leg route. In such cases, I would like to advance them to a specific leg programatically.

It looks like this is possible in the iOS navigation SDK, as per https://github.com/mapbox/mapbox-navigation-ios/issues/2641

It also looks like it was previously possible in Android in a much earlier SDK, with MapboxNavigation.updateRouteLegIndex(), which was introduced in https://github.com/mapbox/mapbox-navigation-android/pull/1643. But I don't think that exists any more.

Is there any way to achieve the functionality I describe?

**Comment by samcrawford** [comment]
It looks like you can call MapboxNavigation.navigateNextRouteLeg() repeatedly until you get to the leg you want. This doesn't have a great user experience though if you have many legs and want to start at one of the later ones. The screen jumps through all of the legs' starting points.

In an ideal world, we'd be able to pass in a starting leg index with the navigation options.

**Comment by Guardiola31337** [comment]
@kmadsen could you share your thoughts here when you have a chance? 🙏

**Comment by kmadsen** [comment]
> I'm using Mapbox Navigation 1.6.1 and sometimes users want to start navigation mid-way through a multi-leg route. In such cases, I would like to advance them to a specific leg programatically.

How exactly does this happen for you? Also how do you know what index you should be on? Ideally we could start the route on the index you are navigating.

**Comment by Zayankovsky** [comment]
@samcrawford with the next release you will be able to provide a starting leg index this way:
```kotlin
mapboxNavigation.setRoutes(routes, initialLegIndex = 2)
```

**Comment by samcrawford** [comment]
Awesome, thanks!
