### ISSUE TITLE
URGENT:  Mapbox-navigation-native-7.0.0.aar missing from bintray

### ISSUE THREAD

**Issue by Android-AutoErrors** [mapbox/mapbox-navigation-android#4682]
@LukasPaczos 

We spent 2 years building our apps using Mapbox SDK and were using the below library. It is no more there. Please provide a new location and what changes we need to specify. We went through ALL of your comments related to this but it is not clear.

https://mapbox.bintray.com/mapbox/com/mapbox/navigator/mapbox-navigation-native/7.0.0/mapbox-navigation-native-7.0.0.aar

**Comment by LukasPaczos** [comment]
Hey @Android-AutoErrors, thanks for using Mapbox!

All the needed instructions are captured in https://github.com/mapbox/mapbox-navigation-android/issues/4533#issuecomment-880672321 and the [v0.42.6](https://github.com/mapbox/mapbox-navigation-android/releases/tag/v0.42.6) tag.
