### ISSUE TITLE
The color for MapboxSoundButton and MapboxRecenterButton

### ISSUE THREAD

**Issue by alexviet** [mapbox/mapbox-navigation-android#4685]
**Mapbox Navigation SDK version:** 2.0.0-beta.20

### Issue description
I have the style of MapboxSoundButton (the same MapboxRecenterButton) only change sound button, it does not change the background of MapboxSoundButton View. How can I change it?

![image](https://user-images.githubusercontent.com/70317810/128113815-c3d8dfd5-cec2-41ab-9681-bb67bae88d3e.png)

**Comment by Zayankovsky** [comment]
@alexviet, with the next beta you will be able to provide custom background as well as define your own text color this way:
```xml
<com.mapbox.navigation.ui.voice.view.MapboxSoundButton
    android:id="@+id/soundButton"
    android:layout_width="wrap_content"
    android:layout_height="wrap_content"
    app:soundButtonBackground="@drawable/bg_black_circle"
    app:soundButtonTextColor="@color/white" />
```
The same applied to `MapboxRecenterButton` and `MapboxRouteOverviewButton`.
