### ISSUE TITLE
How can I add infowindow on the route line?

### ISSUE THREAD

**Issue by KayHung** [mapbox/mapbox-navigation-android#4690]
How can I add infowindow on the route line?
![image](https://user-images.githubusercontent.com/66655517/128690611-ad0143f3-92bd-4c85-a899-7f6afbd10819.png)

**Mapbox Navigation SDK version:Mapbox Navigation SDK 2.0.0-beta.19**

**Comment by LukasPaczos** [comment]
@KayHung unfortunately, the Navigation SDK does not support any info windows by default yet, however, this is a feature that we do plan to introduce eventually. For the time being, you can use the Maps SDK's [symbol layer](https://docs.mapbox.com/mapbox-gl-js/style-spec/layers/#symbol) directly, see an example [here](https://github.com/mapbox/mapbox-maps-android/blob/android-v10.0.0-rc.5/app/src/main/java/com/mapbox/maps/testapp/examples/RuntimeStylingActivity.kt).

**Comment by KayHung** [comment]
I see this at website.
https://www.mapbox.com/blog/taking-your-navigation-to-the-next-level

Does the Navigation SDK support info window now?

![未命名](https://user-images.githubusercontent.com/66655517/132808073-d2e91bad-61d0-4fdc-b1f6-c3e1359f0a0e.png)

**Comment by LukasPaczos** [comment]
Hey @KayHung as metnioned above, this is possible to do with Maps SDK and symbol layers today. There's no out-of-the-box component in the Navigation SDK to create those layers automatically yet, this is something that we're planning as a future utility in the Nav SDK v2 series.

cc @jyrigo @AhmerKhan1 @abhishek1508
