### ISSUE TITLE
PredictiveCacheController loads volatile sources

### ISSUE THREAD

**Issue by zeac** [mapbox/mapbox-navigation-android#4707]
**Android API:**
API 30
**Mapbox Navigation SDK version:**
2.0.0-beta.22

### Steps to trigger behavior
 1. Set MapView style with traffic enabled. 
 2. Enable PredictiveCacheController
 3. Build and set a route to MapboxNavigation

### Expected behavior
Only non-volatile tiles are loaded by PredictiveCacheController.

### Actual behavior
Offline tilepacks for traffic-v2 are requested.

**Comment by korshaknn** [comment]
@zeac hey! how do you set a map instance to the cache controller?

**Comment by zeac** [comment]
> @zeac hey! how do you set a map instance to the cache controller?

Yes. I reproduced this with qa-test-app/MapboxRouteLineActivity by changing the style to `Style.TRAFFIC_NIGHT`. After that i see requests like `https://api.mapbox.com/tilepack/v1/mapbox.mapbox-traffic-v1/11/327/717/11-14.mtp` in the sniffer.

**Comment by korshaknn** [comment]
@zeac you can filter what sources you need to cache
```kotlin
fun createMapControllers(
        map: MapboxMap,
        sourceIdsToCache: List<String> = emptyList()
    )
```

check how do you call `createMapControllers()` in `MapboxRouteLineActivity `. Do you provide any list?
if not, as docs say, all available sources will be cached.

/**
     * Create cache controllers for a map instance.
     * Call when a new map instance is available.
     *
     * @param map an instance of [MapboxMap]
     * @param sourceIdsToCache a list of sources to cache.
     * Source id's should look like "mapbox://mapbox.satellite", "mapbox://mapbox.mapbox-terrain-v2".
     * The system only supports source hosted on Mapbox Services which URL starts with "mapbox://".
     * If no ids are passed all available style sources will be cached.
     */

**Comment by korshaknn** [comment]
@zeac so, if you expect
> Only non-volatile tiles are loaded by PredictiveCacheController.

you need provide them 

```kotlin
createMapControllers(map, listOf("non-volatile tiles"))
```

**Comment by zeac** [comment]
Oh, i expected that only eligible sources will be cached by default. Can we have such logic in `PredictiveCacheController`? I would prefer to keep list of sources in the style only.

**Comment by korshaknn** [comment]
@zeac what do you mean by `eligible`? we have 2 options:
- cache all style sources (default behaviour)
- provide a list of sources to cache

**Comment by zeac** [comment]
> @zeac what do you mean by `eligible`? we have 2 options:
> 
> * cache all style sources (default behaviour)
> * provide a list of sources to cache

All mapbox-hosted, vector or raster, non-volatile style sources.

**Comment by korshaknn** [comment]
@zeac right now there are  2 options
- cache all sources (default)
- cache only passed sources

should we filter somehow sources with dynamic data (like traffic) not to cache them? or we should cache?
cc @LukasPaczos @Guardiola31337

**Comment by Guardiola31337** [comment]
@kkaefer what do you think? ☝️

**Comment by kkaefer** [comment]
I think we should filter volatile sources. Volatile sources are usually valid only for a few minutes, so predictively caching traffic for a location that is a few kilometers or more away (like predictive cache does) isn't sensible.

**Comment by korshaknn** [comment]
how we can filter them? 
do we now exactly how they can be named?

`traffic` what else?

@Guardiola31337 @kkaefer

**Comment by zeac** [comment]
I was told that `getStyleSourceProperties()` contains `volatile` key for such sources, but i didn't find it.

**Comment by tobrun** [comment]
I got a style json from @korshaknn for a style using: `mapbox://mapbox.bmw-traffic-v2`
`mapbox://mapbox.auto-v1` and `mapbox.mapbox-terrain-v2`. None of them are using the optional [volatile style-spec configuration](https://docs.mapbox.com/mapbox-gl-js/style-spec/sources/#vector-volatile). That @zeac isn't able to find a volatile key is expected behavior. 

Either there is a disconnect in using the term volatile (eg. tiles that have a short expiration date) or we need to update the style definition to include `volatile=true`.

**Comment by korshaknn** [comment]
> I think we should filter volatile sources. Volatile sources are usually valid only for a few minutes, so predictively caching traffic for a location that is a few kilometers or more away (like predictive cache does) isn't sensible.

@kkaefer 
should it be done by default by CommonSDK (right now or as a future improvement)?
or NavSDK should filter volatile sources and create cache controllers for non-volatile only?

cc @LukasPaczos

**Comment by pozdnyakov** [comment]
> or NavSDK should filter volatile sources and create cache controllers for non-volatile only?

That should be done in `TilesetDescriptor` implementation - the volatile sources/tilesets shall be filtered out. One option could be re-using the tileset descriptors created by the Maps Offline API.

**Comment by korshaknn** [comment]
@pozdnyakov have some questions
- is there a way to get tileset descriptors created by the Maps Offline API? 
at the moment we get `TileStore` from maps with
```
val tileStore = map.getResourceOptions().tileStore
```
and pass the tileStore to NavigationNative to create cache controllers


- should we pass `tilesetDescriptors` + `tileStore` to NavigationNative side? so they will create cache controllers for valid sources only?

**Comment by pozdnyakov** [comment]
> is there a way to get tileset descriptors created by the Maps Offline API?

Could you fetch them from the Maps `OfflineManager` (smth. like
```
val tilesetDescriptor = offlineManager.createTilesetDescriptor(
  TilesetDescriptorOptions.Builder()
    .styleURI(Style.OUTDOORS)
    .minZoom(0)
    .maxZoom(16)
    .build()
)
```
) and then pass the descriptors along with the `tileStore` to the `PredictiveCacheController` ?

**Comment by korshaknn** [comment]
@pozdnyakov `OfflineManager` is built with `ResourceOptions`, I guess it should be built on customer side, not SDK.
We can add `OfflineManager` to `PredictiveCacheController` constructor.
and change NN API to pass `tilesetDescriptor`
cc @LukasPaczos @Guardiola31337 @mskurydin

**Comment by Guardiola31337** [comment]
Hey @kkaefer and @mskurydin could you help with above questions? 🙏

**Comment by mskurydin** [comment]
It's worth considering the creation of the predictive cache using a tileset descriptor directly.
We will check how complicated it is (there was some WIP on this previously).

**Comment by kkaefer** [comment]
Yeah, I think we should switch over to Tileset Descriptors so that the SDK doesn't have to worry about filtering these and can leverage GL Native/Maps SDK to create these.

**Comment by korshaknn** [comment]
@kkaefer at the moment on SDK side we iterate over style sources to get `tileVariants`. And we create `PredictiveCacheController` for each `tileVariant` using NN API. 
If we pass `tilesetDescriptor` to NN, there will be no need to create controllers for each `tileVariant`, right?

**Comment by kkaefer** [comment]
Yep, that's right.

**Comment by DmitryAk** [comment]
> > is there a way to get tileset descriptors created by the Maps Offline API?
> 
> Could you fetch them from the Maps `OfflineManager` (smth. like
> 
> ```
> val tilesetDescriptor = offlineManager.createTilesetDescriptor(
>   TilesetDescriptorOptions.Builder()
>     .styleURI(Style.OUTDOORS)
>     .minZoom(0)
>     .maxZoom(16)
>     .build()
> )
> ```
> 
> ) and then pass the descriptors along with the `tileStore` to the `PredictiveCacheController` ?

@pozdnyakov Is it possible to filter-out volatile sources/tilesets in another way (without re-using the tiles descriptors created by the Maps Offline API)? Maybe we can find another solution?

TilesetDescriptor instance can be in `unresolved` state - so in general case NavNative cannot create completed PredictiveCacheController by TilesetDescriptor - we must wait until it is resolved to know the data domain (Maps or Navigation). This requires asynchronous `CreatePredictiveCache` introducing, which can be not very convenient to use. Also currently one PredictiveCacheController operates on one dataset, one version, in one data domain (Maps or Navigation). But a TilesetDescriptor can be resolved with several datasets/versions from different data domains. So the only more-or-less simple way is to introduce a new method to asynchronously create a list of PredictiveCacheControllers by TilesetDescriptor. Otherwise it is required to redesign PredictiveCacheController. I’m not sure this is the best option. WDYT?

**Comment by pozdnyakov** [comment]
> @pozdnyakov Is it possible to filter-out volatile sources/tilesets in another way (without re-using the tiles descriptors created by the Maps Offline API)?

Otherwise, you need to repeat the functionality of Maps Offline API which does not look like an optimal way and it can also get inconsistent. 
> This requires asynchronous CreatePredictiveCache introducing, which can be not very convenient to use. Also currently one PredictiveCacheController operates on one dataset, one version, in one data domain (Maps or Navigation).

@DmitryAk could you guide me to the code so that I could give a better advice on it?
