### ISSUE TITLE
Start trip session without starting a foreground service

### ISSUE THREAD

**Issue by LukasPaczos** [mapbox/mapbox-navigation-android#4715]
In certain scenarios or on specific hardware, running a foreground service, which is normally key to be able to receive location updates even when the app is minimized, might not be desirable. We can expose a
```kotlin
fun startTripSession(withTripService = true)
```

and when the flag is set to `false`, the Navigation SDK should not run and maintain a service leaving it to the discretion of the integrating code.

**Comment by abhishek1508** [comment]
This is how `MapboxNavigation.startTripSession()` function looks like
```
fun startTripSession() {
    tripSession.start()
    notificationChannelField?.let {
        monitorNotificationActionButton(it.get(null) as ReceiveChannel<NotificationAction>)
    }
}
```

When `tripsession.start()` is invoked following happens
```
override fun start() {
    if (state == TripSessionState.STARTED) {
        return
    }
    navigator.addNavigatorObserver(navigatorObserver)
    tripService.startService()
    startLocationUpdates()
    state = TripSessionState.STARTED
}
```

As mentioned in the description, it makes sense if we comment out `tripService.startService()` then the service should not start and hence no notification. However, after spending 4 hours I was able to find out that's not the case. Even with just commenting out this line of code and running an example the notification is shown for both free drive session and active trip session. The actual lines that spins up the notification even without starting the service is below:

```
MapboxTripNotification

init {
    /* 
        applicationContext.getSystemService(Context.NOTIFICATION_SERVICE)
            ?.let { notificationService ->
                notificationManager = notificationService as NotificationManager
            } ?: throw (IllegalStateException("Unable to create a NotificationManager"))
    */

    pendingOpenIntent = createPendingOpenIntent(applicationContext)
    pendingCloseIntent = createPendingCloseIntent(applicationContext)
    notificationView = MapboxTripNotificationView(applicationContext)

    notificationView.buildRemoteViews(pendingCloseIntent)
    //createNotificationChannel()
}
```

Hence we need to make sure the lines above are not executed if the user does not want to start a service and see a notification. Looking at it further, it doesn't makes sense why we would even want to instantiate `TripService` and `TripNotification` if we don't want to see them. The solution I am proposing is to add an option to `NavigationOptions` - `startServiceAndShowNotification()` with default value set to `true`. If set to false, `MapboxNavigation` would not instantiate the `MapboxTripService` and hence no `MapboxTripNotification`.

Downside of this approach is once the user creates a `NavigationOptions` and passes it to `MapboxNavigation(navigationOptions)` there is no other way to change the options again.

/cc @LukasPaczos

**Comment by LukasPaczos** [comment]
> Even with just commenting out this line of code and running an example the notification is shown for both free drive session and active trip session. The actual lines that spins up the notification even without starting the service is below: []

The notification actually shows up because we end up updating it in `MapboxTripSession#updateRouteProgress`. This diff removes the notification entirely, and this is where the state checks would have to be in order to have dynamic service starts/stops:
```diff
diff --git a/libnavigation-core/src/main/java/com/mapbox/navigation/core/trip/session/MapboxTripSession.kt b/libnavigation-core/src/main/java/com/mapbox/navigation/core/trip/session/MapboxTripSession.kt
index fd2f283bf..38cf2f033 100644
--- a/libnavigation-core/src/main/java/com/mapbox/navigation/core/trip/session/MapboxTripSession.kt
+++ b/libnavigation-core/src/main/java/com/mapbox/navigation/core/trip/session/MapboxTripSession.kt
@@ -196,7 +196,7 @@ internal class MapboxTripSession(
             return
         }
         navigator.addNavigatorObserver(navigatorObserver)
-        tripService.startService()
+        // tripService.startService()
         startLocationUpdates()
         state = TripSessionState.STARTED
     }
@@ -596,7 +596,7 @@ internal class MapboxTripSession(
         shouldTriggerBannerInstructionsObserver: Boolean
     ) {
         routeProgress = progress
-        tripService.updateNotification(buildTripNotificationState(progress))
+        // tripService.updateNotification(buildTripNotificationState(progress))
         progress?.let { progress ->
             routeProgressObservers.forEach { it.onRouteProgressChanged(progress) }
             if (shouldTriggerBannerInstructionsObserver) {
```

We could optimize the service and notification instances to be lazily initialized so that we're not instantiating them when not needed.

I think this might be a better approach because this allows for building a cleaner "preview" experience. When a user first opens the navigation app, we can start a session without the service, we don't need background updates after all. After they request the route and go into the "navigation" experience, we can then start the service and show the notification. This type of experience is not possible right now, and would require recreation of `MapboxNavigation` when looking at the proposal from https://github.com/mapbox/mapbox-navigation-android/pull/4730.

**Comment by abhishek1508** [comment]
If commenting out tripService. updateNotification() doesn't show the notification, I am down for it as I don't like the options approach since then you cannot make the API dynamic.
