### ISSUE TITLE
Expose a reusable route geometry cache

### ISSUE THREAD

**Issue by LukasPaczos** [mapbox/mapbox-navigation-android#4720]
In many places across the SDK we are taking the `DirectionsRoute` reference and decoding the polyline geometries of the whole route and each step into `LineString`s or `Point` arrays.

Developers interacting with the Nav SDK need to often perform the exact same decoding process which unnecessarily wastes resources.

We already do have an `LruCache`-based implementation internally that's used only in the route line module and reuses route geometry references - https://github.com/mapbox/mapbox-navigation-android/blob/v2.0.0-beta.22/libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/util/CacheResultUtils.kt.

We should narrow down the scope of possible elements to be cached, move implementation to the `base` module and expose it so that all of our internal modules, as well as the integrating apps, could share the burden of decoding the route geometries.

Possible API surface that currently comes to mind:
```
DirectionsRoute.completeGeometryToLinestring() : LineString
DirectionsRoute.completeGeometryToPoints(): List<Point>
DirectionsRoute.stepsGeometryToLinestring() : List<List<LineString>> // nested array of legs(steps(line string))
DirectionsRoute.stepsGeometryToPoints():  List<List<List<Point>>> // nested array of legs(steps(points))
```

The cache size should potentially be fixed and I'd propose caching up to 3 results for each of the API methods for now (reasoning - one slot for the primary route and two for alternatives, which is the most common use-case).

cc @mapbox/navigation-android

**Comment by cafesilencio** [comment]
I think CacheUtils can stay generic and we can create type specific utilizations like `MapboxRouteLineUtils::decodeRoute`. The variations you suggest above can be derivatives of this and similar implementations to avoid re-inventing the wheel.

**Comment by LukasPaczos** [comment]
Agreed :+1: The underlying, internal part can remain as generic as we need it to, just the public APIs should probably be narrowed down.

**Comment by LukasPaczos** [comment]
We also need to make sure that the public APIs are reasonably accessible from both Java and Kotlin.
