### ISSUE TITLE
Implement recent gradient support for dashed line layers for restricted roads.

### ISSUE THREAD

**Issue by cafesilencio** [mapbox/mapbox-navigation-android#4724]
There were some recent modifications by the GL team that support applying a gradient to a dashed line layer.  This will improve the way restricted roads are represented on the route line. This feature has already been implemented but customer feedback indicated it was unsatisfactory in its appearance.  Taking advantage of this recent development by the GL team will allow for utilizing the benefits of the dashed line layer (like scaling) as well as utilize the gradient feature for displaying only the restricted sections of a route and properly "vanishing" the restricted section during navigation.

**Comment by LukasPaczos** [comment]
@cafesilencio should this be considered a release blocker? Are you anticipating any breaking changes in the implementation?

**Comment by cafesilencio** [comment]
I"m not anticipating any breaking changes from maps just a bug fix for the zooming issue.  My work breaks semver.

**Comment by LukasPaczos** [comment]
This means that we need to merge https://github.com/mapbox/mapbox-navigation-android/pull/4773 before the release candidate :+1: 

cc @abhishek1508

**Comment by LukasPaczos** [comment]
Also, I just merged https://github.com/mapbox/mapbox-navigation-android/pull/4789. Does that unblock your work with restricted roads as well, could you verify?

**Comment by cafesilencio** [comment]
I"m not really blocked. I think my PR can get merged in as soon as all the feedback has been addressed and somebody is satisfied that it's ready to be merged.  I expect this PR to get merged in soon. After that it's a matter of waiting for the fix from maps which you already have a work around for.
