### ISSUE TITLE
Native observer can miss events

### ISSUE THREAD

**Issue by LukasPaczos** [mapbox/mapbox-navigation-android#4727]
We are subscribing the `NavigatorObserver` in the `MapboxTripSession` only when the `start()` function is called. This means that in situations where, for example, a route is set _before_ the session is started, all of the events produced by Nav Native while the route is set (including banner instructions updates) are going to be dropped by the Nav SDK.

We should look into refactoring `MapboxTripSession` to always register the `NavigatorObserver` when `MapboxTripSession` is initialized to make sure that we're not dropping any events, and make sure that the events are not propagated further if the session is stopped. Then, when a session is started, we should send all of the accumulated latest information (including observer calls).

cc @mapbox/navigation-android

**Comment by RingerJK** [comment]
One of the options might be not to set a route to NN, till a trip session is started, we might set a route just after subscribe on `NavigatorObserver` events

https://github.com/mapbox/mapbox-navigation-android/blob/31a397d6939e01109950a5149cf07f865a76cc05/libnavigation-core/src/main/java/com/mapbox/navigation/core/trip/session/MapboxTripSession.kt#L186-L198

**Comment by LukasPaczos** [comment]
This is an interesting idea - we might need to do a tiny bit more maintenance on our side, but at least we won't need to cache event results between when the nav SDK trip session is stopped/started because there will be no events.

cc @korshaknn

**Comment by Guardiola31337** [comment]
Noting that I'm lately missing the very first voice instruction and it seems definitely related to OP.
