### ISSUE TITLE
If navigation is cancelled when the voice guidance is still announcing, the volume of the music is not restored

### ISSUE THREAD

**Issue by Guardiola31337** [mapbox/mapbox-navigation-android#4763]
**Android API:** 
**Mapbox Navigation SDK version:** `2.0.0-beta.19`

### Steps to reproduce

1. Test nav app on a mobile phone, when there is music playing at the same time.
2. Start the navigation and wait for the announcement of voice guidance
3. Cancel the navigation during the announcement of voice guidance

### Expected behavior
The volume of the music should be reduced when the navigation voice guidance starts, and then the volume will be restored after the voice guidance ends or cancelled. 

### Actual behavior

However, if the navigation is cancelled when the voice guidance is still announcing, the volume of the music will not be restored. It seems that AudioFocus was not released.

cc @VitaminPSG

**Comment by LukasPaczos** [comment]
@Guardiola31337 should we treat it as a release blocker? @n-frolov any updates on the issue?

**Comment by Guardiola31337** [comment]
I think it should be included as part of RC.

**Comment by n-frolov** [comment]
Reproduced as described in 1tap (not on the first try). Starting the navigation again and getting another voice instruction resets the music volume back.
