### ISSUE TITLE
Improve time to first `RouteProgress` update

### ISSUE THREAD

**Issue by LukasPaczos** [mapbox/mapbox-navigation-android#4769]
In https://github.com/mapbox/mapbox-navigation-android/pull/4755 we fixed a race condition that sometimes delivered a `RouteProgress` that had a context of the old route reference, while the new route was already set. This was due to the async nature of the route setting process.

With this change, we also delayed the time to the first `RouteProgress` update because we need to wait for _the next_ location update after completing the route setting process to emit the first `RouteProgress` update. We should use the `Navigator.getStatus` method to immediately process the latest available status update once the route setting process completes.

cc @mapbox/navigation-android

**Comment by korshaknn** [comment]
discussed with NN team. 
right now they have some issues with scheduler and we might receive `onStatus` updates with the old route even when `setRoute()` is finished. they are working to fix it.

but even if it is fixed, we can't use direct call `getStatus()` after `setRoute()` is finished. It might return invalid status (for the old route). And we need to wait for `onStatus` callback, we can't remove the delay.

cc @LukasPaczos @DmitryAk @mskurydin

**Comment by LukasPaczos** [comment]
> we can't use direct call getStatus() after setRoute() is finished

Is this considered working as expected? It sounds like a bug.

**Comment by LukasPaczos** [comment]
Looks like migrating to an async route setter might allow us to fix the issue once and for all, even if the direct `Navigator.getStatus` does not work as we'd need it to.

**Comment by zugaldia** [comment]
@korshaknn @LukasPaczos can we resume the work on this ticket? I believe that the async route setter (setRouteAsync) is now available within NN.

**Comment by korshaknn** [comment]
@zugaldia async router setter is integrated in https://github.com/mapbox/mapbox-navigation-android/pull/4881
cc @LukasPaczos

**Comment by truburt** [comment]
@korshaknn , @Zayankovsky , is it something that you have already addressed in #4915 ? What's the next step?

**Comment by korshaknn** [comment]
@truburt the only thing we can do on SDK side - use new async NN methods, they should work faster and as a result we should receive a route progress update also faster. It was integrated in #4881
