### ISSUE TITLE
ANR/Crash on Android 8 when notification is not enabled

### ISSUE THREAD

**Issue by BoD** [mapbox/mapbox-navigation-android#485]
On Android 8, if you use `startForegroundService`, you must also call `startForeground` with a notification within 5 seconds, otherwise you get an ANR - and a crash when the service stops.
( https://developer.android.com/about/versions/oreo/background.html#services )

This is done in `NavigationService` [[1]](https://github.com/mapbox/mapbox-navigation-android/blob/master/libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/NavigationService.java#L117), but *only* if the notification is enabled [[2]](https://github.com/mapbox/mapbox-navigation-android/blob/master/libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/NavigationService.java#L100).

We do not want the notification in our app, therefore the ANR+crash will happen for all users on Oreo devices.

Note that this will happen, even if your project targets Android 7 or less.

**Comment by palto-blubek** [comment]
Hi!  I'm sorry to nag, but has anyone seen this issue?  

As this crash happens consistently, I think it should have a high priority (also, it is easy to reproduce and the cause is clear).

Thanks a lot.

**Comment by danesfeder** [comment]
Hey @palto-blubek, you are getting this crash with the notification disabled?

**Comment by palto-blubek** [comment]
That's correct @danesfeder .  This happens because when calling `startForegroundService` you *must* show a notification.

**Comment by danesfeder** [comment]
@palto-blubek So are you trying to implement the SDK without a notification at all?  It is my understanding that if you implemented your own notification (to replace ours), this crash would be fixed.

**Comment by palto-blubek** [comment]
We currently wish not to use the SDK's notification (which is the reason we call `.enableNotification(false)` on `MapboxNavigationOptions`.

We actually show our own notification currently, but this is not enough to avoid this crash.  Even if a notification is shown, the rule is that if `startForegroundService` is called to start a Service, then `startForeground` must be called on this same service, passing a notification.

I'm not sure a simple fix is possible without altering the API.  

Correct me if I'm wrong, but currently there is no way to provide our own notification or customize the default one?  Maybe there could be an API for the user to provide their notification?

**Comment by danesfeder** [comment]
@palto-blubek Yeah you are correct on all points here.  We would technically be able to provide a way to customize the API to allow anyone to pass a custom notification, but this is not available at this time.  

> Note that this will happen, even if your project targets Android 7 or less.

You see this crash with devices < Android O + notification disabled?  For APIs less than O, we start the service without calling `startForegroundService`:
https://github.com/mapbox/mapbox-navigation-android/blob/master/libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/MapboxNavigation.java#L363

**Comment by palto-blubek** [comment]
No, sorry I wasn't clear.  We only see the crash on Android O devices.   What I meant is that our app targets api level 25.  Sometimes new Android behaviors are only enabled for apps that target the level in which the changes have been introduced - which is why I wanted to mentioned this.

**Comment by danesfeder** [comment]
Oh okay no problem, I see now.  I will work with the rest of the team to prioritize this.  Our notification in general has some bugs that need to be addressed (including this).  I will update this ticket with prioritization once we determine where it lands in our queue of work.  

I appreciate the clarification and you pointing this issue out.

**Comment by palto-blubek** [comment]
Just a followup.  To avoid the crash we're going to enable the notification.  But the texts are in english only and the units are imperial only.

**Comment by danesfeder** [comment]
@palto-blubek Once https://github.com/mapbox/mapbox-navigation-android/pull/564 lands, you'll be unblocked here for Android O
