### ISSUE TITLE
ThreadController when used by standalone components

### ISSUE THREAD

**Issue by LukasPaczos** [mapbox/mapbox-navigation-android#4853]
Refs https://github.com/mapbox/mapbox-navigation-android/pull/4816#issuecomment-922948108.

A lot of components in the SDK rely on the `ThreadController` object to provide coroutine scopes for children jobs to run.

Some of the components also rely on `MapboxNavigation#onDestroy` call that cleans up the `ThreadController` children jobs to avoid leaks.

However, if a component is standalone, it can have a different lifecycle than `MapboxNavigation` which can cause various types of leaks and issues. For example, `ThreadController#init` called from the `MapboxNavigation` constructor:
https://github.com/mapbox/mapbox-navigation-android/blob/d5f2041a7ee3ea8001a0762b91c91ed2e9792752/libnavigation-util/src/main/java/com/mapbox/navigation/utils/internal/ThreadController.kt#L62-L65

overrides parent jobs. So if there was a coroutine running via `ThreadController` and only then `MapboxNavigation` was created, calling `MapboxNavigation#onDestroy` would not cancel the previously running coroutine, nor should it, but some components expect it.

I think destroying `MapboxNavigation` should cancel only the coroutines tied to the `MapboxNavigation` object's lifecycle, and each standalone component should have its own cancellation method.

cc @mapbox/navigation-android

**Comment by cafesilencio** [comment]
If lifecycle is the issue we're addressing then we should consider these components having their own thread pool rather than relying on `ThreaController` which is static.  If we don't want a component to be dependent on cancel being called on `MapboxNavigation` then likewise calling cancel on `MapboxNavigation` shouldn't cancel the coroutines in standalone components.

**Comment by cafesilencio** [comment]
An alternative to the ThreadController was merged in [here](https://github.com/mapbox/mapbox-navigation-android/pull/4911). The route line related components were updated to take advantage of it. There may be other components that should be modified as well.  I"m not sure of the total scope of this issue. Some clarification is needed.

**Comment by Guardiola31337** [comment]
Dropping https://github.com/mapbox/mapbox-navigation-android/pull/4921 here for reference cc @Zayankovsky
