### ISSUE TITLE
Offroute issue

### ISSUE THREAD

**Issue by guraymumun94** [mapbox/mapbox-navigation-android#486]
The problem is at navigation.addOffRouteListener(this):

    @Override
    public void userOffRoute(Location location) {
    myLocation = location;
    myLocationPosition = Point.fromLngLat(location.getLongitude(), location.getLatitude());

    navigationRouteBuilder.origin(myLocationPosition);
    navigationRouteBuilder.destination(destination);

    navigationRouteBuilder.build().getRoute(new Callback<DirectionsResponse>() {
        @Override
        public void onResponse(Call<DirectionsResponse> call, retrofit2.Response<DirectionsResponse> response) {
            if (response.body() != null) {
                if (response.body().routes().size() > 0) {
                    currentRoute = response.body().routes().get(0);
                    navigationMapRoute.removeRoute();
                    navigationMapRoute.addRoute(currentRoute);

                    LegStep step = currentRoute.legs().get(0).steps().get(1);
                    instruction.setText(step.maneuver().instruction());
                    setManeuverIcon(step.maneuver().type(), step.maneuver().modifier(), step.maneuver().instruction());
                    nextStepName.setText(step.name());
                    distanceToNextStep.setText(formatDistance(currentRoute.legs().get(0).steps().get(0).distance()));

                    duration.setText(formatDuration(currentRoute.duration()));
                    allDistance.setText(formatDistance(currentRoute.distance()));
                    endTime.setText(new SimpleDateFormat("hh:mm a").format(new Date((long) (new Date().getTime() + (currentRoute.duration() * 1000)))));

                    navigation.startNavigation(currentRoute);
                    recentre();
                    Speech.getInstance().say(step.maneuver().instruction());
                }
            }
        }

        @Override
        public void onFailure(Call<DirectionsResponse> call, Throwable t) {
            Log.d("OFF ROUTE FAILURE", t.getLocalizedMessage());
        }
    });
}

navigationRouteBuilder.build().getRoute() not calling onResponse(), but onFailure() and t.getLocalizedMessage() is: 
OFF ROUTE FAILURE: **Too many coordinates; maximum number of coordinates is 3.** 
How can I resolve this so navigationBuilder calls onResponse and draw new correct route on map?

build.gradle:

compile 'com.mapbox.mapboxsdk:mapbox-android-services:2.2.8'
compile('com.mapbox.mapboxsdk:mapbox-android-sdk:5.2.0-SNAPSHOT@aar') 
{
    transitive = true
}
compile 'com.mapbox.mapboxsdk:mapbox-android-navigation:0.7.0-SNAPSHOT'

**Comment by danesfeder** [comment]
Hey @guraymumun94 it looks like you're storing your `navigationRouteBuilder` as a field in this class - if this is the same builder that you used to make your original route request (to start navigation), adding another `origin` and `destination` in an off route scenario will cause you to go over our 3 coordinate max.  

I'd recommend creating a new builder for each request.  This can also be made more clear on our end by clearing the coordinate values for origin and destination when you reset them like you're doing here. 

cc: @cammace

**Comment by guraymumun94** [comment]
OK, Problem is solved with new NavigationRouteBuilder object in the userOffRoute method, but now it's not working again. Why?

implementation 'com.mapbox.mapboxsdk:mapbox-android-services:2.3.0-SNAPSHOT'
    implementation('com.mapbox.mapboxsdk:mapbox-android-sdk:5.2.0-SNAPSHOT@aar') {
        transitive = true
    }
    implementation 'com.mapbox.mapboxsdk:mapbox-android-navigation:0.7.1-SNAPSHOT'
    implementation('com.mapbox.mapboxsdk:mapbox-android-navigation-ui:0.7.1-SNAPSHOT@aar') {
        transitive = true
    }

**Comment by guraymumun94** [comment]
Problem is solved with using 0.7.0 instead of 0.7.1

**Comment by cammace** [comment]
NavigationRoute is just a wrapper class around `MapboxDirections`, when building an instance, everytime you set a new origin or destination,[it overrides](https://github.com/mapbox/mapbox-java/blob/master/services-directions/src/main/java/com/mapbox/directions/v5/MapboxDirections.java#L402) its previous value. We do add a bearing value to the list which might be causing issues ( https://github.com/mapbox/mapbox-navigation-android/blob/master/libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/NavigationRoute.java#L168 ) but you say you are now creating a new NavigationRoute eachtime the user goes off-route which should resolve all these issues.
