### ISSUE TITLE
VisionReplayManager.create always gives me an error -Android

### ISSUE THREAD

**Issue by Lijo0989** [mapbox/mapbox-navigation-android#4879]
When i try to create VisionReplayManager using existing session data, it always shows error as below

09-22 12:55:27.604 855 855 D MediaBufferGroup: creating MemoryDealer
09-22 12:55:27.623 3784 3852 E MediaProvider: Couldn't find file: /storage/emulated/10/Movies/session/gps.bin
09-22 12:55:27.634 3784 3932 E MediaProvider: Couldn't find file: /storage/emulated/10/Movies/session/motion.bin
09-22 12:55:27.639 3784 3851 E MediaProvider: Couldn't find file: /storage/emulated/10/Movies/session/frames.bin
09-22 12:55:27.643 3784 3852 E MediaProvider: Couldn't find file: /storage/emulated/10/Movies/session/device.bin
09-22 12:55:27.648 3784 3932 E MediaProvider: Couldn't find file: /storage/emulated/10/Movies/session/camera.bin
09-22 12:55:27.653 3784 3851 E MediaProvider: Couldn't find file: /storage/emulated/10/Movies/session/heading.bin
09-22 12:55:27.659 3784 3852 E MediaProvider: Couldn't find file: /storage/emulated/10/Movies/session/road_description.bin
09-22 12:55:27.665 3784 3932 E MediaProvider: Couldn't find file: /storage/emulated/10/Movies/session/detections.bin
09-22 12:55:27.670 3784 3851 E MediaProvider: Couldn't find file: /storage/emulated/10/Movies/session/signs.bin
Expected behavior

it should start replaying based on the recorded session.
Actual behavior

app crashes

**Comment by LukasPaczos** [comment]
Hey, this repository tracks Mapbox Navigation SDK. Feel free to reach out [to our support](https://support.mapbox.com/hc/en-us) if you have questions about the Vision SDK.
