### ISSUE TITLE
Investigate logging and other possible causes of ANR when updating vanishing route line.

### ISSUE THREAD

**Issue by cafesilencio** [mapbox/mapbox-navigation-android#4882]
An ANR condition was reported during the `updateTraveledRouteLine` process of the vanishing route line. It appears it may be caused by the logging that gets done [here](https://github.com/mapbox/mapbox-navigation-android/blob/666acdf5f0d962e2b40f5d3f48ce1e727dcd7e03/libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/route/line/api/VanishingRouteLine.kt#L119-L132).

We should definitely simplify the log but also look into when this condition could occur in the first place and how we can optimize it. Possibly it might happen when a route is changed due the async jobs running.

**Comment by cafesilencio** [comment]
@LukasPaczos I am able to trigger the logging by creating a long route and during navigation I change to a different route.  One idea would be to change the log level to debug instead of the current error level.  This logging message probably has little value to the average developer under normal circumstances.  wdyt?

**Comment by LukasPaczos** [comment]
I agree, this check is our internal safeguard, not an error that should be addressed by developers :+1: 

This also means that we keep trying to update the vanishing point while the data is clearly invalid, can we synchronize these async jobs to avoid this?

**Comment by cafesilencio** [comment]
I"ll start by changing the logging level and investigate the bigger picture as you suggest.
