### ISSUE TITLE
Crash (NullPointerException) in VoiceInstructionMilestone

### ISSUE THREAD

**Issue by palto-blubek** [mapbox/mapbox-navigation-android#489]
We are in the process of trying out `com.mapbox.mapboxsdk:mapbox-android-navigation:0.7.0-SNAPSHOT`

We encounter this crash:
```
Process: com.less.line.integration.debug, PID: 20455
java.lang.NullPointerException: Attempt to invoke virtual method 'double java.lang.Double.doubleValue()' on a null object reference
   at com.mapbox.services.android.navigation.v5.milestone.VoiceInstructionMilestone.shouldBeVoiced(VoiceInstructionMilestone.java:81)
   at com.mapbox.services.android.navigation.v5.milestone.VoiceInstructionMilestone.isOccurring(VoiceInstructionMilestone.java:27)
   at com.mapbox.services.android.navigation.v5.navigation.NavigationHelper.checkMilestones(NavigationHelper.java:171)
   at com.mapbox.services.android.navigation.v5.navigation.NavigationEngine.handleRequest(NavigationEngine.java:70)
   at com.mapbox.services.android.navigation.v5.navigation.NavigationEngine.handleMessage(NavigationEngine.java:62)
   at android.os.Handler.dispatchMessage(Handler.java:98)
   at android.os.Looper.loop(Looper.java:154)
   at android.os.HandlerThread.run(HandlerThread.java:61)
```

And indeed, when I add a breakpoint and inspect this line [[1]](https://github.com/mapbox/mapbox-navigation-android/blob/master/libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/milestone/VoiceInstructionMilestone.java#L81) I see that `voice.distanceAlongGeometry()` is `null`.

This is indeed `null` in the response returned by the MapBox backend as you can see with this request (please replace ACCESSTOKEN by a valid access token):

`curl -H 'User-Agent: TODO Linux/3.10.0+ (i686)' -H 'Host: api.mapbox.com' --compressed 'https://api.mapbox.com/directions/v5/mapbox/driving-traffic/2.297517,48.885333;2.29751,48.885323?access_token=ACCESSTOKEN&alternatives=false&geometries=polyline6&overview=full&steps=true&annotations=duration,distance&language=fr&voice_instructions=true'`

An extract of the response is:
```
				"voiceInstructions": [{
					"distanceAlongGeometry": null,
					"announcement": "Rouler vers l'ouest sur Place du Maréchal Juin then vous êtes arrivés à votre destination",
					"ssmlAnnouncement": "<speak><amazon:effect name=\"drc\"><prosody rate=\"1.08\">Rouler vers l'ouest sur Place du Maréchal Juin then vous êtes arrivés à votre destination</prosody></amazon:effect></speak>"
				}]
```

Notice the `"distanceAlongGeometry": null,`.

**Comment by danesfeder** [comment]
Hey @palto-blubek, thanks for raising this issue - we are currently working on a fix upstream in our directions API.  The `distanceAlongGeometry` should pass a number (in this case 0).

**Comment by palto-blubek** [comment]
Thanks for replying.  Is there a public issue for this so we can follow it?

Also, I've just submitted another issue related to the voice instructions/directions API here: https://github.com/mapbox/mapbox-navigation-android/issues/498

**Comment by danesfeder** [comment]
@palto-blubek the fix has been merged upstream and I'll close this ticket when it's deployed.  (should be today / tomorrow)

**Comment by palto-blubek** [comment]
Any update on this?

**Comment by danesfeder** [comment]
@palto-blubek Unfortunately, ran into some delays on the deploy for this.  Will keep you updated - looking like early next week at this point.

**Comment by danpat** [comment]
We've rolled out the server-side fix for this.  The request above is now returning the exepcted `0` value for `distanceAlongGeometry`.

```
                     "voiceInstructions" : [
                        {
                           "announcement" : "Rouler vers l’ouest sur Place du Maréchal Juin, puis vous êtes arrivés à votre destination",
                           "ssmlAnnouncement" : "<speak><amazon:effect name=\"drc\"><prosody rate=\"1.08\">Rouler vers l’ouest sur Place du Maréchal Juin, puis vous êtes arrivés à votre destination</prosody></amazon:effect></speak>",
                           "distanceAlongGeometry" : 0
                        }
                     ],
```
