### ISSUE TITLE
RerouteState.Failed doesn't come when the error encountered

### ISSUE THREAD

**Issue by alexzatsepin** [mapbox/mapbox-navigation-android#4910]
In Maps+ we have bad user experience if the network error is encountered during the reroute request. How the problem looks you can see on this video. Also, I've attached full logs where you can see timestamps of how often reroute requests are made.

[long_time_reroute.txt](https://github.com/mapbox/mapbox-navigation-android/files/7237886/long_time_reroute.txt)

https://user-images.githubusercontent.com/8442156/134948493-4581b47c-4b07-406a-837e-8f568d5e3587.mp4

**Android API:** Android 11
**Device:** samsung galaxy tab s5e
**Mapbox Navigation SDK version:** 2.0.0-rc.1

### Steps to trigger behavior

 1. Build the route and start navigation
 2. Mock the any route through Lockito/Android emulator or another GPS simulator and start navigation there.
 3. Catch any `GET /directions/v5/mapbox/driving-traffic/` reroute request and abort him, another words simulate request failure by any method you have. I've used Charles proxy and breakpoints mechanism.
 4. After that the puck can continue to drive for long time until the next reroute request is done.
 5. When the request is aborted/failed the Maps+ app doesn't get failed reroute state via reroute controller observer:
  ```
   @ExperimentalCoroutinesApi
    suspend operator fun invoke(): Flow<RerouteState> = conflatedCallbackFlow {
        val rerouteObserver = RerouteController.RerouteStateObserver { rerouteState -> trySendBlocking(rerouteState) }
        mapboxNavigation.getRerouteController()?.registerRerouteStateObserver(rerouteObserver)
        awaitClose { mapboxNavigation.getRerouteController()?.unregisterRerouteStateObserver(rerouteObserver) }
    }
```

**Expected behavior**: the nav sdk should propagate the failed state to the client through reroute observer callback or handle retry policy internally. 

**Actual behavior**: the failed state doesn't go to the client. The puck drives without route line until the next reroute request is encountered. But it can be done after minutes (see video and logs please). 

Seems like the next reroute was executed when I touched the map. Would be ideally if Navigation SDK implements the retry policy internally. But as a quick solution the fix the `RerouteState.Failed` will be good for us. **Important note:** the next reroute will be done, it's a fact, but when exactly it's happened I couldn't clarify. cc @korshaknn

**Comment by korshaknn** [comment]
@alexzatsepin do you receive other states with the observer (success/idle/etc.)?

**Comment by alexzatsepin** [comment]
@korshaknn Yes, I do. You can filter out those states by "DebugReroute" tag in the log file which I've attached to this issue.

**Comment by alexzatsepin** [comment]
Closing this issue. After deep investigation we confirmed that Failed state comes as expected, i.e. when both routers are failed(Offboard and Onboard). @korshaknn @Guardiola31337 thanks for your help.
