### ISSUE TITLE
Voice instructions are incorrectly translated (mixed english / other language) and with imperial units

### ISSUE THREAD

**Issue by palto-blubek** [mapbox/mapbox-navigation-android#498]
Starting from v0.7.0 (and v0.10.0 on iOS, if I'm not mistaken), the voice instructions come from the Mapbox backend.

Unfortunately, the texts returned are mixed with english and the language requested. For instance, this call:

```
curl -H 'User-Agent: TODO Linux/3.10.0+ (i686)' -H 'Host: api.mapbox.com' --compressed 'https://api.mapbox.com/directions/v5/mapbox/driving-traffic/2.343983,48.876167;2.34972,48.887216?access_token=ACCESS_TOKEN&alternatives=false&geometries=polyline6&overview=full&steps=true&annotations=duration,distance&language=fr&voice_instructions=true'```
```
(replace ACCESS_TOKEN by a valid one)

returns sentences like this:

- "**Head** le nord-est on Rue Cadet **for 0.5 mile**"
- "**In** 600 pieds, tourner à droite sur Rue de Dunkerque"
- "Tourner à droite sur Rue de Dunkerque"
- "Tourner à gauche sur Rue Pierre Brossolette **then** vous êtes arrivés à votre destination"

I've put in bold pieces that are in english...

Also notice that the units are in the imperial system, but in France we need the metric system.

This issue blocks us from using this version right now.

Also, is there an API in the SDK to actually customize these strings, in case we would like to phrase things differently?  And also is there a way to choose the distances at which these voice milestones are triggered?

**Comment by danesfeder** [comment]
@palto-blubek looking into the mixed languages issue.  There is a query param for imperial v. metric: `voice_units` which should address the issue with the imperial distances you're seeing.

**Comment by palto-blubek** [comment]
Thanks for replying.  I do not see this argument in `MapboxDirections.Builder` (at least, in version `3.0.0-SNAPSHOT` that `0.7.0` depends on).

**Comment by danesfeder** [comment]
@palto-blubek Yeah, we weren't exposing this, but it was just added in https://github.com/mapbox/mapbox-java/commit/a4ef7b2. Once the new `SPANSHOT` builds you should refresh the dependency and see this.

**Comment by danpat** [comment]
Translations for `language=fr` have been updated, this request now contains:

```
"instruction" : "Rouler vers le nord-est sur Rue Cadet",
"instruction" : "Tourner à droite sur Boulevard de Rochechouart",
"instruction" : "Tourner à droite sur Rue Myrha",
"instruction" : "Tourner à gauche sur Boulevard Barbès",
"instruction" : "Vous êtes arrivés à votre destination, sur la droite",
```

```
"announcement" : "Rouler vers le nord-est sur Rue Cadet sur 0.5 mile",
"announcement" : "Dans 800 pieds, tourner à droite sur Boulevard de Rochechouart",
"announcement" : "Tourner à droite sur Boulevard de Rochechouart",
"announcement" : "Dans 0.25 mile, tourner à droite sur Rue Myrha",
"announcement" : "Tourner à droite sur Rue Myrha, puis tourner à gauche sur Boulevard Barbès",
"announcement" : "Tourner à gauche sur Boulevard Barbès, puis vous arriverez à votre destination, sur la droite",
"announcement" : "Vous êtes arrivés à votre destination, sur la droite"
```

also note that when the `voice_units=metric` parameter is available in the SDK, you should be able to see the following:

```
"announcement" : "Rouler vers le nord-est sur Rue Cadet sur 800 mètres",
"announcement" : "Dans 200 mètres, tourner à droite sur Boulevard de Rochechouart",
"announcement" : "Tourner à droite sur Boulevard de Rochechouart",
"announcement" : "Dans 400 mètres, tourner à droite sur Rue Myrha",
"announcement" : "Tourner à droite sur Rue Myrha, puis tourner à gauche sur Boulevard Barbès",
"announcement" : "Tourner à gauche sur Boulevard Barbès, puis vous arriverez à votre destination, sur la droite",
"announcement" : "Vous êtes arrivés à votre destination, sur la droite",
```

(I simply added `&voice_units=metric` to the example URL above)

@danesfeder I'm not sure whether to close this now, or wait until the `voice_units` parameter is properly exposed in the SDK - I'll hand this back to you.

**Comment by palto-blubek** [comment]
Thank you, confirming it looks good on our side.

**Comment by danesfeder** [comment]
Thanks for the update here @danpat and @palto-blubek for bringing this to us.
