### ISSUE TITLE
There is no object available to pass DirectionsResponse waypoints

### ISSUE THREAD

**Issue by kmadsen** [mapbox/mapbox-navigation-android#5000]
**Mapbox Navigation SDK version:** 2.0.0 also does not pass waypoints to nav-native
**Mapbox Navigation SDK version:** 2.1.0 (unreleased as of writing)

Introduced here https://github.com/mapbox/mapbox-navigation-android/pull/4892

### Example values of coordinates and waypoints when requesting a route on 2.1

```
Request coordinates
"coordinates":"-122.2750609,37.8052055;-122.2778329,37.8174339"
```
```
Server Response waypoints
  waypoints[
    {
      name=Jefferson Street,
      rawLocation=[-122.275111,37.805225]
    },
    {
      name=26th Street,
      rawLocation=[-122.277781, 37.81758]
    }
]
```

```
Set route to native
 setRoute {"waypoints":[{"location":[-122.2750609,37.8052055]},{"location":[-122.2778329,37.8174339]}],
```

Notice that the route is being set with the route options rather than the waypoints. But the waypoints are also not saved in the DirectionsRoute or the RouteOptions.

https://github.com/mapbox/mapbox-navigation-android/blob/81599a1aaf162f831d9e5af0e70fcbf25f6cdb5b/libnavigator/src/main/java/com/mapbox/navigation/navigator/internal/MapboxNativeNavigatorImpl.kt#L223-L230

### 2.0.0+ requires a list of routes
``` kotlin
MapboxNavigation.requestRoutes { routes: List<DirectionsRoute>
  MapboxNavigation.setRoutes(routes)
}
```

https://github.com/mapbox/mapbox-navigation-android/blob/81599a1aaf162f831d9e5af0e70fcbf25f6cdb5b/libnavigation-core/src/main/java/com/mapbox/navigation/core/MapboxNavigation.kt#L591-L596

https://github.com/mapbox/mapbox-navigation-android/blob/81599a1aaf162f831d9e5af0e70fcbf25f6cdb5b/libnavigation-core/src/main/java/com/mapbox/navigation/core/MapboxNavigation.kt#L620

**Comment by LukasPaczos** [comment]
Closing in favor of https://github.com/mapbox/navigation-sdks/issues/1229.
