### ISSUE TITLE
maximizeViewableGeometryWhenPitchZero cannot be used with a constrained zoom level

### ISSUE THREAD

**Issue by Christophe668** [mapbox/mapbox-navigation-android#5055]
**Mapbox Navigation SDK version:** 2.0

### Steps to trigger behavior
If we want to strictly make the camera follow the user to a specific zoom level, let's say 19, we run into issues where the camera is zoomed to the entire leg but not taking into account the user's location.

``` 
viewportDataSource.options.followingFrameOptions.maxZoom = ZoomLevel.DETAILS_19
viewportDataSource.options.followingFrameOptions.minZoom = ZoomLevel.DETAILS_19
```
Same behavior was observed when using this method
```
viewportDataSource.followingZoomPropertyOverride(ZoomLevel.DETAILS_19)
```

### Actual behavior

| No override  | Options set or overriden|
| ------------- | ------------- |
| <img width="336" alt="Screenshot 2021-10-28 at 14 20 53" src="https://user-images.githubusercontent.com/1552554/139254110-cea87b37-fe49-40c3-a6b7-608417012528.png">  | <img width="344" alt="Screenshot 2021-10-28 at 14 20 58" src="https://user-images.githubusercontent.com/1552554/139254150-0e7e669c-3496-465f-973c-882bf2f79697.png">  |

### Expected behavior
When overriding the options or the zoom property override, we should include the user location at least ideally and try to focus on the current leg as much as possible.

Our goal would be to have the zoom level at 19 and titled at 65° for instance and still display the current legs as much as possible to help the user see where he needs to go. 
This would be perfect when biking.

| Without tilting | With tilting |
| ------------- | ------------- |
| <img width="324" alt="Screenshot 2021-10-28 at 14 36 24" src="https://user-images.githubusercontent.com/1552554/139256456-6963268c-8752-4a36-88e3-6bd55f6dbfd9.png"> | <img width="336" alt="Screenshot 2021-10-28 at 14 37 48" src="https://user-images.githubusercontent.com/1552554/139256570-ed0dde88-afbc-477b-b4a6-74a72c664267.png"> |

Does that make sense?

**Comment by Christophe668** [comment]
```
		viewportDataSource.options.followingFrameOptions.defaultPitch = 65.0
		viewportDataSource.options.followingFrameOptions.minZoom = ZoomLevel.DETAILS_19
```
Here are some additional data to illustrate.

In this video, you can see when arriving close to the next leg (the roundabout), it tries to zoom, but the `defaultPitch` and the `minZoom` are ignored.


https://user-images.githubusercontent.com/1552554/139911441-4262f479-39b7-49fd-a4fc-b8d72f1d1352.mp4



As you can see on the video, it represents almost the same as the behavior shown in the screenshots above.
Hope this helps!

**Comment by LukasPaczos** [comment]
Hey @Christophe668, thanks for reporting the issue!

Unfortunately, a limited zoom level does not currently work with the `maximizeViewableGeometryWhenPitchZero` feature. If you need to limit zoom level, this feature has to be disabled:
```
viewportDataSource.options.followingFrameOptions.maximizeViewableGeometryWhenPitchZero = false
```

We're also tracking another feature that might be helpful in your scenario, which is freely positioning the puck user location in the padding - https://github.com/mapbox/mapbox-navigation-android/issues/4347.
