### ISSUE TITLE
Unify Distance Formatter throughout the SDK

### ISSUE THREAD

**Issue by abhishek1508** [mapbox/mapbox-navigation-android#5065]
Mapbox Navigation SDK `v2.0.0` supports an interface `DistanceFormatter` that returns a `distance` in the form of `SpannableString`. The advantage of this return type is that the value is returned in the form of `distance + distance_unit`(12 mi or 12km) which makes it easy to directly render the value on the screen. However, there may or may not be customers or other SDK's(Android Auto) that might want to have a different system of concatenation or logical calculations to be performed on top of the distance value. Android Auto for example needs the raw distance value and since that is not supported through our SDK, they have to write their own DistanceFormatter.

The proposal in this ticket is to:
- [ ] Update or expose a distance formatter that can emit a complex object consisting of:
   ```
   class Distance( val distance: Double, val unit: String)
   ```
- [ ] Define a standard rounding increment system across different views that use the DistanceFormatter. For ex: TripProgress uses a rounding increment of 5 or 2 vs Maneuver uses a rounding increment of 50.

Refs: https://github.com/mapbox/mapbox-navigation-android/issues/4168 and https://github.com/mapbox/mapbox-navigation-android/issues/4168#issuecomment-956566753

/cc @mapbox/navigation-android  @mapbox/navigation-ios @jyrigo @AhmerKhan1 @zugaldia @truburt

**Comment by cafesilencio** [comment]
Implementation merged into main.
