### ISSUE TITLE
When there are multiple shields in a step, only the first shield is used for all occurrences

### ISSUE THREAD

**Issue by abhishek1508** [mapbox/mapbox-navigation-android#5067]
**Android API: >21**
**Mapbox Navigation SDK version: v2.0.0** 

Refs https://github.com/mapbox/1tap-android/issues/1283#issuecomment-958205466

For routes that have instructions such that there is more than 1 shield and are different, `ManeuverView` always renders the 1st shield for all the other shields in that instruction. For every instruction, we assign an `id`. Based on the `id` we maintain a map `shieldMap<String, RouteShield?>`. Since the instruction contains multiple road shields but one id, the road shields get overwritten. We should probably change the implementation to `shieldMap<String, List<RoadShield>>`.

/cc @LukasPaczos @zugaldia

**Comment by LukasPaczos** [comment]
This is fixed with the new shields APIs available in v2.2.0.
