### ISSUE TITLE
Custom InfoWindow appears only on 2nd launch on Android 6,7,8

### ISSUE THREAD

**Issue by dotPilot** [mapbox/mapbox-navigation-android#508]
I customized InfoWindow and set it in onMapReady()
`mMapboxMap.setInfoWindowAdapter(new PoiInfoWindowAdapter());`
Adapter:
`public class PoiInfoWindowAdapter implements MapboxMap.InfoWindowAdapter {

    @Nullable
    @Override
    public View getInfoWindow(@NonNull Marker marker) {
        View infoWindow = LayoutInflater.from(mContext).inflate(R.layout.info_window, null);
        ....
        return infoWindow;
    }
}`
but at very first launch of my app InfoWindows appear as default on:
Nokia 6 (Android 7.1.1) 
Lenovo TB3-850M (Android 6.0)
Nexus 5X (Android 8.0)
On further launches it appears costomized as expected
With Samsung Android 5 works fine.
Mapbox SDK:
`compile('com.mapbox.mapboxsdk:mapbox-android-sdk:5.1.2@aar') {
        transitive = true
    }`

**Comment by danesfeder** [comment]
Thanks for the feedback @dotPilot.  @tobrun I believe this is a Maps SDK issue, should I move it to the gl-native repo?

**Comment by tobrun** [comment]
Yes, follow issue created in https://github.com/mapbox/mapbox-gl-native/issues/10510
