### ISSUE TITLE
Release 0.7.0 Gradle Compile issues

### ISSUE THREAD

**Issue by rheng001** [mapbox/mapbox-navigation-android#509]
Hi' I'm trying to update my project to the recent 0.7.0 release and I'm getting gradle build errors. Here is the gradle I'm building with.

`compile('com.mapbox.mapboxsdk:mapbox-android-sdk:5.2.0-beta.3@aar') {
        transitive=true
    }`
`compile 'com.mapbox.mapboxsdk:mapbox-android-navigation:0.7.0'`
`compile ('com.mapbox.mapboxsdk:mapbox-android-navigation-ui:0.7.0') {
        transitive = true
    }`

The errors I'm getting is 

> Error:Failed to resolve: com.mapbox.mapboxsdk:mapbox-java-services-directions:3.0.0-SNAPSHOT
> Error:Failed to resolve: com.mapbox.mapboxsdk:mapbox-java-services-turf:3.0.0-SNAPSHOT

**Comment by wedi** [comment]
It took a while to figure out. You need add
`maven { url "http://oss.sonatype.org/content/repositories/snapshots/" }`
to your repositories as the failing artifacts are only available there...

**Comment by rheng001** [comment]
@wedi 

Thanks! That solved the problem. Makes sense now. :)

**Comment by danesfeder** [comment]
@wedi @rheng001 Sorry about this - you shouldn't have to compile our snapshot repo.  Working on fixing this and doing a `0.7.1` release

**Comment by MehdiFal** [comment]
@danesfeder is it a viable option when going to prod? if it's not, what would be the alternative?
Thanks.
