### ISSUE TITLE
NavigationLauncher not working, no instructions or zoom to location

### ISSUE THREAD

**Issue by csjames** [mapbox/mapbox-navigation-android#510]
I have added NavigationActivity to my manifest to solve crash due to not being able to find class
     <activity android:name="com.mapbox.services.android.navigation.ui.v5.NavigationActivity"/>

but when I launch the NavigationActivity using the NavigationLauncher with the following example code

` Point origin = Point.fromLngLat(-77.03613, 38.90992);
									Point destination = Point.fromLngLat(-77.07458, 38.90894);

									// Pass in your Amazon Polly pool id for speech synthesis using Amazon Polly
									// Set to null to use the default Android speech synthesizer
									String awsPoolId = null;

									// This will animate the application to simulate a driver following the route
									boolean simulateRoute = true;

									// Call this method with Context from within an Activity
									NavigationLauncher.startNavigation(StartActivity.this, origin, destination, awsPoolId, simulateRoute); `

I only get a blank looking activity with no route or instructions. 

![screenshot_20171116-173338](https://user-images.githubusercontent.com/12152421/32909024-50ff9306-cafd-11e7-93ff-3a0a7d782043.png)

**Comment by danesfeder** [comment]
@csjames looking into this - which dependency for the `navigation-ui` are you compiling?

**Comment by csjames** [comment]
It was some sort of compiler/gradle issue. I am working on quite an old application which had some legacy gradle/manifest entries. Once I migrated the code to a fresh application it worked fine. Thanks for your time!
