### ISSUE TITLE
Failed to resolve: com.mapbox.navigation:android:2.0.1

### ISSUE THREAD

**Issue by szyrelle290612** [mapbox/mapbox-navigation-android#5110]
anyone can help me 
ive got issue 
![image](https://user-images.githubusercontent.com/67720919/141672536-d7eeb819-6b04-4b5f-a4a4-4d441ebb80bd.png)
when i tried include 
dependencies com.mapbox.navigation:android:2.0.1 i encounter this error
advance thanks

**Comment by abhishek1508** [comment]
Hi @szyrelle290612 Can you please confirm if you were able to follow the [installation](https://docs.mapbox.com/android/navigation/guides/get-started/install/) steps from our documentation?

**Comment by szyrelle290612** [comment]
yes i follow the instruction

**Comment by abhishek1508** [comment]
Sounds good. Would it be possible for you to share you root level and app level build gradle files?

**Comment by szyrelle290612** [comment]
// Top-level build file where you can add configuration options common to all sub-projects/modules.
buildscript {
    repositories {
        google()
        mavenCentral()
        jcenter()
        maven { url 'https://plugins.gradle.org/m2' }
        maven {
            url 'https://api.mapbox.com/downloads/v2/releases/maven'
            authentication {
                basic(BasicAuthentication)
            }
            credentials {
                username = "mapbox"
                password = "pk  .eyJ1Ijoic3p5cmVsbGUyOTA2IiwiYSI6ImNrdnpqbG1wazBwaXQyeG5vdHNjZmxxd2QifQ.ZVA27aMBmocKSrHZfLwe9w"
            }
        }
    }
    dependencies {
        classpath "com.android.tools.build:gradle:7.0.3"

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}
task clean(type: Delete) {
    delete rootProject.buildDir

**Comment by szyrelle290612** [comment]
plugins {
    id 'com.android.application'
}

android {
    compileSdk 31

    defaultConfig {
        applicationId "com.example.myapplication"
        minSdk 26
        targetSdk 31
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.3.1'
    implementation 'com.google.android.material:material:1.4.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.1'
    implementation 'com.mapbox.navigation:android:1.0.0'
    testImplementation 'junit:junit:4.+'
    androidTestImplementation 'androidx.test.ext:junit:1.1.3'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.4.0'

}

**Comment by pjleonard37** [comment]
Hi @szyrelle290612 - 

We recently updated the installation instructions in [our documentation](https://docs.mapbox.com/android/navigation/guides/get-started/install/#add-the-dependency) to account for changes in recent versions of Android Studio and Gradle. Can you try again with those instructions to see if your issue is resolved?

**Comment by szyrelle290612** [comment]
issue is solve thanks a lot
