### ISSUE TITLE
RouteAlternativesObserver#onRouteAlternatives always reports Onboard as source

### ISSUE THREAD

**Issue by LukasPaczos** [mapbox/mapbox-navigation-android#5127]
`RouteAlternativesObserver#onRouteAlternatives` always reports `RouterOrigin` as `Onboard` even if the results are coming from the offboard router. The next release of Nav Native (v81?) will contain an indication which route is new in the list of routes and knowing it's origin, we'll be able to assign the correct value to the callback.

cc @kmadsen

**Comment by dudeuter** [comment]
@LukasPaczos I've actually never seen anything but `Onboard` get reported from `RouterOrigin` 😕

**Comment by LukasPaczos** [comment]
@dudeuter are you saying that `MapboxNavigation#getRoutes` always reports `Onboard` for you?

**Comment by dudeuter** [comment]
@LukasPaczos That's what I've observed when I was troubleshooting offline recently on GA. I toggled the Reachability and they both returned `Onboard` this was before I knew about the fallback to online behavior, but even then I would have expected `Offboard` for both.

**Comment by LukasPaczos** [comment]
If there's no connection and the route is generated offline, the expected origin is `Onboard`. Unless I'm missing something?

`Onboard` router generates a route _offline_ while `Offboard` router generates a route _online_, in case that's the source of confusion.

**Comment by dudeuter** [comment]
@LukasPaczos Yes, but this was the case where I was forcing the SDK to default to the API, so I would have expected `Offboard`

**Comment by LukasPaczos** [comment]
@dudeuter so in you scenario you had disabled internet access on your device and called:
```
OfflineSwitch.getInstance().isMapboxStackConnected = true
```
do I understand correctly? And you would expect the request to fail instead of returning an `Onboard` route?

Asking because when I normally request a route with internet access I do get the `origin == Offboard`. There's also a possibility that you've been sending a request that failed for the Directions API but succeeded in the fallback onboard Valhalla version (for some reason, we've seen these happen occasionally since the implementations are not fully on par).

**Comment by dudeuter** [comment]
Correct, I was trying to test time spend waiting on the API before falling back to the `Onboard` router. In my case, I'd actually deleted all of my navigation tiles, so I was expecting to get an exception.

With the device disconnected, and `OfflineSwitch.getInstance().isMapboxStackConnected = true` I'd get the exception, with `OfflineSwitch.getInstance().isMapboxStackConnected = false` I'd get an API response with `Onboard` as the origin.

Although this was on GA, and there's probably a good chance it's been fixed in `2.1.x`

**Comment by LukasPaczos** [comment]
Thanks @dudeuter, considering what we discussed above as fixed/not reproducible in 2.1 and the original issue (with alternatives) is going to be fixed in https://github.com/mapbox/mapbox-navigation-android/pull/5167.

**Comment by dudeuter** [comment]
I'll reopen if I run into any issues with `RouterOrigin`

**Comment by LukasPaczos** [comment]
Let's no close just yet, the alternatives do currently report only `onboard` which will be fixed in https://github.com/mapbox/mapbox-navigation-android/pull/5167.
