### ISSUE TITLE
[Android : DropInUI] Alternative route selection support for NavigationView

### ISSUE THREAD

**Issue by cafesilencio** [mapbox/mapbox-navigation-android#5161]
When using the NavigationView a user should be able to click on an alternative route and that route should become the primary route. The map should get updated to reflect a change in the primary route as well as `MapboxNavigation` getting updated. After an alternative route has been selected and navigation begins the puck should follow the selected route.

**Comment by 1ec5** [comment]
Tracking this feature on iOS in mapbox/mapbox-navigation-ios#3598.
