### ISSUE TITLE
Use a fragment for drop-in UI or a least have the user provide their own LifecycleOwner for NavigationView

### ISSUE THREAD

**Issue by Zayankovsky** [mapbox/mapbox-navigation-android#5162]
Current approach assumes that the `context` passed to the `NavigationView` is an instance of `FragmentActivity` and `LifecycleOwner`, which is very fragile and limiting. For example, setting a theme to the root view is enough to break this, as the `context` will be an instance of `ContextThemeWrapper` and the cast will not succeed. Also this approach makes a rather dangerous assumption, that the view lives as long as the activity that hosts it. Which is not the case even in our testing app, where we use fragments and the map is not displayed, unless the user logs in. 
So we should at least have the user provide their own `LifecycleOwner`, which will make setup a little more complicated. Otherwise it will be very easy to create a leak. For example the user removes a fragment that hosts the view, but the activity is still active, so the navigation continues to work, when it shouldn't. Also with views it is possible to add and remove them at any time without using fragments at all, in which case the user will have to create a custom `LifecycleOwner` to match that flow. So it becomes the user's responsibility to provide a correct `LifecycleOwner`. 
Another solution is to provide a fragment, e.g. `NavigationFragment`. Fragments have their own lifecycle, so the user won't have to provide anything. The user will be able to add and remove the fragment at any time and its lifecycle will handle it accordingly, so the navigation will work only when the fragment is added. Using fragments is as easy as the views, it doesn't matter whether fragments are used for the rest of application or not. For the case when the map is displayed as long as activity lives, the user is able to add the fragment with just several lines in xml layout, which is the same with views. This idea will also play nicely with `MapboxNavigationApp`, which is being introduced in #5112, as the fragment can attach its lifecycle to it automatically. 
Implementing such `NavigationFragment` is also easy, for the first iteration we can just wrap `NavigationView`, inject fragment's lifecycle into it and act as a proxy. Also it will allow the user to still use `NavigationView` instead, if for some reason they can't use fragments (I can't imagine what reason that might be). For the second iteration we may move logic from the view to the fragment, if needed. 
cc @mapbox/navigation-android

**Comment by LukasPaczos** [comment]
Thanks for raising this @Zayankovsky!

> For example, setting a theme to the root view is enough to break this, as the context will be an instance of ContextThemeWrapper and the cast will not succeed.

We've been working around this in the past by unwrapping the context until we got the one we wanted and we should do the same here. Great catch!

> Also this approach makes a rather dangerous assumption, that the view lives as long as the activity that hosts it. Which is not the case even in our testing app, where we use fragments and the map is not displayed, unless the user logs in.

This is true but I don't think that applies to the `context` reference. The hosting `activity` will always live longer than the `NavigationView` so we are not at risk of leaking anything. The risk here is the `LifecycleOwner` and I definitely agree that we don't want to use the `Activity` as the `LifecycleOwner`.

I wouldn't want to give up the flexibility of working just with views, there might be dependencies on this approach that we're not aware of, I think we can provide the support for both raw view-based setup and well as fragment setup here.

We need to distinguish two things:
 - The lifecycle of the scope which we use to run coroutines in the `NavigationView`. **This lifecycle should be tied to the view itself**. I think that we should create our own internal `NavigationViewLifecycle` for this which is controlled by the `onAttachedToWindow` and `onDetachedFromWindow` calls. This will make sure that internal coroutines that interact with the view are only running when the view is attached.
 - The lifecycle of the `ViewModelStoreOwner` which provides us `ViewModel`s for all the components. By default, i think we can use the `Activity` reference. We will waste some memory when holding state of `ViewModel`s for cases where `NavigationView` is in a detached fragment but I feel like it's fine. Then, we can expose a method to set your own reference for the `ViewModelStoreOwner` in case your `NavigationView` runs in a fragment and you do want to narrow down the scope. And lastly, we can expose the proposed `NavigationViewFragment` to set this `ViewModelStoreOwner` automatically.

What do you think @Zayankovsky?

**Comment by abhishek1508** [comment]
I am not sure if exposing both a View and a Fragment is the right thing to do and needed. There hasn't been any customer requests asking for Navigation view to be a fragment instead.  Advantages of a custom view is that if someone has a very simple application with activities, they can just simply attach the Navigation view and be done with it. If someone has a more complex setup with fragments, they can wrap the navigation view inside the fragment and use it. 

I would also like to point out that if we expose a fragment as well as a view, I would not be in favor of hosting the same code in fragment as in the view. In that case, we would then have to maintain 2 files that do exactly the same and we run at a risk where they might differ in implementations if someone forgets to fix a bug in one but not another. 

To mitigate this I would advocate for using Navigation view inside the Navigation View Fragment. That way the implementation will live only in one place and fragment would just be a wrapper. 

We could probably also have an example where we show how to wrap the navigation view inside a fragment and attach the fragment in the activity. That way we have something tangible and customers can directly copy paste. We could later move the example to the SDK if we see customers are rather interested in fragment.

Wdyt?
@Zayankovsky @LukasPaczos

**Comment by Zayankovsky** [comment]
> The lifecycle of the scope which we use to run coroutines in the `NavigationView`. **This lifecycle should be tied to the view itself**. I think that we should create our own internal `NavigationViewLifecycle` for this which is controlled by the `onAttachedToWindow` and `onDetachedFromWindow` calls. This will make sure that internal coroutines that interact with the view are only running when the view is attached.

I think this will actually work. And in case someone wraps the view with a `Fragment`, this custom lifecycle should give us what we need, because the methods you mentioned will be called when the fragment is added and removed. So we will probably won't have to provide the fragment at all.
I still think implementing a `Fragment` would be a cleaner approach, but I understand your concerns that this solution might not work for someone. So I'm fine with your idea, as it seems it will allow us to cancel all background work, when the view is removed, which was my main point here. 

> I would also like to point out that if we expose a fragment as well as a view, I would not be in favor of hosting the same code in fragment as in the view. In that case, we would then have to maintain 2 files that do exactly the same and we run at a risk where they might differ in implementations if someone forgets to fix a bug in one but not another.

I completely agree with you, I actually mentioned that in the description as one of the ideas, how could the fragment look like.

**Comment by LukasPaczos** [comment]
Sounds like we are aligned. The next steps that I see in terms of priority:
1. In the `NavigationView` remove the `LifecycleOwner` reference that is based on the hosting `Activity`. Introduce a custom `LifecycleOwner` that is based on `View#onAttachedToWindow` and `View#onDetachedFromWindow` calls. Use that owner across `NavigationView` for scheduling coroutines.
2. Expose a `NavigationViewFragment` that wraps `NavigationView`. (optional)
3. Add a `NavigationViewFragmentExample` that either wraps `NavigationView` in a fragment or uses the `NavigationViewFragment` directly if we opted to expose it.

**Comment by Zayankovsky** [comment]
I'd like to add that with fragments we would have an advantage of handling configuration changes naturally. We could follow MVVM pattern, which would allow us not to cancel coroutines when a view is recreated in this case. And I'm not sure we can achieve the same with a lifecycle based on `View#onAttachedToWindow` and `View#onDetachedFromWindow` calls.

**Comment by kmadsen** [comment]
> In the NavigationView remove the LifecycleOwner reference that is based on the hosting Activity. Introduce a custom LifecycleOwner that is based on View#onAttachedToWindow and View#onDetachedFromWindow calls. Use that owner across NavigationView for scheduling coroutines.

> And I'm not sure we can achieve the same with a lifecycle based on View#onAttachedToWindow and View#onDetachedFromWindow calls.

Also unsure if we should introduce another lifecycle owner that is based on View#onAttachedToWindow and View#onDetachedFromWindow calls. That may not work for handling configuration changes. But am in agreement with the conversations. I can see a us having a NavigationFragment that could be used instead of NavigationView.

But I still really agree with this point "I wouldn't want to give up the flexibility of working just with views". We could try making NavigationView automatically detect it's LifecycleOwner from activity or fragment.

**Comment by kmadsen** [comment]
Something wrong with the DropInRoutesInteractor is there is no connection to the Lifecycle though. It would be nice to make it so [findRoute is connected to a LifecycleOwner](https://github.com/mapbox/mapbox-navigation-android/blob/1baebacd9d64981c0bfcf20f9eb13f3ffe2e4d10/qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/lifecycle/DropInRoutesInteractor.kt#L107)

**Comment by Zayankovsky** [comment]
> But I still really agree with this point "I wouldn't want to give up the flexibility of working just with views". We could try making NavigationView automatically detect it's LifecycleOwner from activity or fragment.

What do you mean? I don't think views have access to any `LifecycleOwner` or `Lifecycle`, unless developer provides it manually, which was one of my suggestions here.

**Comment by Ilya-Gazman-2** [comment]
@LukasPaczos, you are building life cycle boundaries based on coroutines. It will help you to optimize for CPU. However, you may still run into memory leaks and invalid state situations if you are not adequately scoping the initialization process.

One of the biggest pain points we are having today with v1.61 is `NavigationView` calling to `NavigationViewModel.onDestroy`. This approach breaks when navigating between fragments, as you may get `onViewCreated` calls of a new fragment before the old one called `onViewDestroyed`(See sample project [here](https://github.com/Ilya-Gazman-2/view_test)).

@LukasPaczos please tell me where are you planning to manage the shared state(`NavigationViewModel` in v1.61), and when will it be initialized and recycled? Ideally, I would expect it to be self-contained. Initialized in the constructor and recycled in [ViewModel.onClear](https://developer.android.com/reference/android/arch/lifecycle/ViewModel#oncleared). This way whether it is injected in a view/fragment or Activity it will be scoped to its own life cycle.

**Comment by LukasPaczos** [comment]
Hey @Ilya-Gazman-2, thanks for the input!

We are currently looking into implementing 3 lifecycle-aware components in the new `NavigationView`:
- First scoped to the view itself which runs coroutines that interact with view elements (collect flows from `ViewModel`s to update visible data).
- Second scoped to a hosting Activity/Fragment that holds `ViewModel`s that serve the data. Since the state is stored in the `ViewModel`, we can handle the configuration changes well even if the view-scoped coroutines are canceled during recreation (I think this also answers your question above @kmadsen).
- Third scoped for the whole app/activity (depending on use case) that holds onto the underlying `MapboxNavigation` (check out the early preview of [`core.lifecycle`](https://github.com/mapbox/mapbox-navigation-android/tree/main/libnavigation-core/src/main/java/com/mapbox/navigation/core/lifecycle) that handles this).

This might evolve as we implement more of these components.

@Zayankovsky wrt
> [...] with fragments [...] We could follow MVVM pattern, which would allow us not to cancel coroutines when a view is recreated in this case.

When a fragment goes through a configuration state change, the lifecycle is `stopped` and then `started` which would stop ongoing coroutines and restart them after configuration change, which I believe is the same end result as we would get, isn't it? Something worth verifying though.

**Comment by Zayankovsky** [comment]
> When a fragment goes through a configuration state change, the lifecycle is `stopped` and then `started` which would stop ongoing coroutines and restart them after configuration change, which I believe is the same end result as we would get, isn't it? Something worth verifying though.

@LukasPaczos what do you mean by restarting coroutines after configuration change? 
With a fragment it will be possible, for example, to keep a route request alive while a screen is rotated and show the result in a new view, which is a better user experience. With a view it seems that we will be forced to cancel the request in onDetachedFromWindow and the best we can do is to remember this fact, so that we will be able to start this request again in a new view.

**Comment by abhishek1508** [comment]
Why would we even make a n/w request via the view in the first place? This sounds wrong to me and should probably happen via the view model.

**Comment by Zayankovsky** [comment]
> Why would we even make a n/w request via the view in the first place? This sounds wrong to me and should probably happen via the view model.

We want to cancel the request when the view is removed from the activity, because otherwise it is a leak. Which means the request has to be canceled when `onDetachedFromWindow` is called. I'm afraid there's no other way. We can't scope the request to a view model, because there's no such thing as view model tied to a view. `ViewModelStoreOwner` is implemented only by activities and fragments.

**Comment by LukasPaczos** [comment]
> With a view it seems that we will be forced to cancel the request in onDetachedFromWindow and the best we can do is to remember this fact, so that we will be able to start this request again in a new view.

In this situation we will only cancel a coroutine that listens to result flow from the `ViewModel`. A view should never make a request by itself.

> We want to cancel the request when the view is removed from the activity, because otherwise it is a leak. [...] We can't scope the request to a view model, because there's no such thing as view model tied to a view. ViewModelStoreOwner is implemented only by activities and fragments.

I don't fully agree with this. In my opinion we can encapsulate data operations and business logic in a `ViewModel` scoped to a parent fragment/activity. In a situation when a view is used by itself, there might be situations where we would waste some memory (until parent lifecycle is destroyed) by keeping a `ViewModel` alive for a `NavigationView` that will never come back. I wouldn't call this a leak, it's still a valid state in cases the view does come back. Developers can always wrap that `NavigationView` in a fragment (or we can provide that impl as mentioned in https://github.com/mapbox/mapbox-navigation-android/issues/5162#issuecomment-984849987) to achieve a tighter lifecycle and memory management.

This way developers can choose which approach they'd like to use. We can be transparent and clear about pros/cons or side effects in the docs.

**Comment by Zayankovsky** [comment]
Thanks @LukasPaczos I finally understand your idea. I have only one question. What do you think of using MapboxNavigation lifecycle (as @kmadsen suggested) instead of a ViewModel scoped to an activity/fragment? This way we can also handle configuration changes and developers can already control this lifecycle by calling necessary `attach` functions. And we won't have to provide an extra setting in NavigationView for a tighter memory management.

**Comment by LukasPaczos** [comment]
This is interesting. Should we couple the UI state with the `MapboxNavigation` though? We'd effectively do that if we used the same lifecycle. I feel like that might be unnecessary and the UI state should be managed separately with the appropriate view and activity/fragment scopes.

I imagine use cases like Android Auto (where the hosting app is closed while AA still runs) or apps with multiple screens (like automotive) where `MapboxNavigation` is shared between multiple view hierarchies and we might want to avoid bundling the state of a long gone hierarchy in the same lifecycle.

**Comment by kmadsen** [comment]
> Should we couple the UI state with the MapboxNavigation though? We'd effectively do that if we used the same lifecycle. I feel like that might be unnecessary and the UI state should be managed separately with the appropriate view and activity/fragment scopes.

Not coupling the UI state with MapboxNavigation, coupling **navigation** state with MapboxNavigation. For example, if you request a route, the request should not be canceled when you change screen orientation or connect/disconnect from android auto.

**Comment by LukasPaczos** [comment]
In the current state of https://github.com/mapbox/mapbox-navigation-android/pull/5332, a route request would not be canceled when the device changes configuration as the request would be running in the `ViewModel` scope. And since later the request is maintained by the `MapboxNavigation` which is bound to the app lifecycle, I think we have what we need to share that navigation state (via `MapboxNavigation`) between Activities and Android Auto. If we'd need to share data beyond what's in scope of `MapboxNavigation`, that's a different story and would require an additional data/state storage layer. We can definitely consider that when a use case shows up.

**Comment by kmadsen** [comment]
There may still be an issue if it is scoped to ViewModel. ViewModels are not in scope for Android Auto. So I think the navigation states like route request, it will need to be attached to the `MapboxNavigationApp.lifecycleOwner`

The issue may not be easy to reproduce, so this is technically speaking 🤔
