### ISSUE TITLE
Update MapboxTripNotification implementation

### ISSUE THREAD

**Issue by axti** [mapbox/mapbox-navigation-android#5172]
### In order to improve notifications behaviour and to be aligned with latest Android changes my suggestions:

 1. Instead of `NotificationCompat.PRIORITY_MAX` for notification priority use default priority or what is a better suit. Max priority doesn’t fit because it is designed for user attention and input. 
 2. Maybe it will be better to change current expanded view with action buttons to the standard [notification actions](https://developer.android.com/guide/topics/ui/notifiers/notifications#Actions) 
 3. Change category of notification from `NotificationCompat.CATEGORY_SERVICE` to `CATEGORY_NAVIGATION` since it is better suits for our use case:  _map turn-by-turn navigation_.
 4. Likely in **Free Drive Session** state we don't need to update notification continuously, since nothing changed in the notification perspective. For this my suggestion is to add check current state and new state inside `updateNotification(state: TripNotificationState)` but it could be other solution as well. Probable we can change `TripNotificationFreeState` from `class` to `object`.  

cc @Zayankovsky @LukasPaczos

**Comment by axti** [comment]
Might be we can add  [CarAppExtender](https://developer.android.com/training/cars/apps/navigation?hl=vi#turn-by-turn-notifications) to be compatible with car head unit notifications.

**Comment by Zayankovsky** [comment]
> 2. Maybe it will be better to change current expanded view with action buttons to the standard [notification actions](https://developer.android.com/guide/topics/ui/notifiers/notifications#Actions)

Seems like it is not possible unless we stop using a custom layout for the notification.

**Comment by Guardiola31337** [comment]
@lawsonkight could you chime in here when you have a chance and provide your thoughts from a UX / UI perspective?

**Comment by Zayankovsky** [comment]
Here you can see the difference between using custom layout and using standard one:
| Custom layout  | Standard layout |
| ------------- | ------------- |
| ![old_active_exp_31](https://user-images.githubusercontent.com/2395284/150017047-2800b397-a376-47a4-91d8-829d42729334.png) | ![new_active_exp_31](https://user-images.githubusercontent.com/2395284/150017036-48b3882b-2e12-4f68-a251-2e70af4da6eb.png) |
| ![old_active_exp](https://user-images.githubusercontent.com/2395284/150017049-d7364fdd-a8a6-46f1-b258-533d4d3e90e8.png) | ![new_active_exp](https://user-images.githubusercontent.com/2395284/150017044-485fd466-230a-4f97-81da-d52a7f3c5cd7.png) |

The main differences are that with the standard layout maneuver icon is located on the right side and on some devices it is not possible to change background color. Also implementation of the standard layout is easier to support, e.g. with it we wouldn't have issues on Android 12, that we recently had with the custom layout.
