### ISSUE TITLE
InstructionView.show() method doesn't work in 0.7.0

### ISSUE THREAD

**Issue by josephquzhou** [mapbox/mapbox-navigation-android#518]
@danesfeder Hi can you help me with this. After upgraded to 0.7.0 my InstructionView's show() method does't work any more. Thanks!

**Comment by danesfeder** [comment]
Hey @josephquzhou yeah I'm sorry we actually removed the `show()` method and animation in `0.7.0`.  You would be able to recreate it pretty easily though.  Just like hiding / showing any view - just bind the view and load / start the animation.  https://stackoverflow.com/questions/19765938/show-and-hide-a-view-with-a-slide-up-down-animation

**Comment by danesfeder** [comment]
Closing, as this method no longer exists for `InstructionView`
