### ISSUE TITLE
Incomplete StepDistance equals() method

### ISSUE THREAD

**Issue by yuryybk** [mapbox/mapbox-navigation-android#5187]
`StepDistance` doesn't take `distanceRemaining` into account inside the `equals()`
For some maneuver list comparisons it leads to an incorrect result.

/cc @abhishek1508

**Comment by abhishek1508** [comment]
@yuryybk Thanks for reporting the issue. Can you explain a bit more as to what kind of incorrect results are you seeing with use cases and sample route?

**Comment by yuryybk** [comment]
@abhishek1508 It is valid for any route if we try to make a deep comparison of the two maneuvers lists implicitly (in our case we would like to avoid redundant updates with help of the `distinctUntilChanged()` from `Kotlin Flow`)

**See the example below:**

The remaining distance for the top maneuver should be changed when the car moves closer to the maneuver. But we would like to avoid UI updates on every `RouteProgress` (as it rebuilds maneuver list too) and trigger UI re-layout only when the maneuver list is changed.

So with the current `StepDistance.equals()` implementation and applied deep comparison `distinctUntilChanged()` on our side this value is constant all the time.

<img width="1281" alt="image" src="https://user-images.githubusercontent.com/7085270/145390986-64d610bb-e1f3-4799-98d8-b43f9da3aca3.png">
