### ISSUE TITLE
Incorrect maneuver point for the last maneuver?

### ISSUE THREAD

**Issue by yuryybk** [mapbox/mapbox-navigation-android#5188]
Does it look like `ManeuverProcessor` takes the first step point instead of the last point as maneuver point for the last step in the leg?
https://github.com/mapbox/mapbox-navigation-android/blob/v2.2.0-alpha.1/libnavui-maneuver/src/main/java/com/mapbox/navigation/ui/maneuver/ManeuverProcessor.kt#L193

It could lead to incorrect camera position when the last maneuver is selected in maneuver the list for the overview.

/cc @abhishek1508

**Comment by abhishek1508** [comment]
For any given route(ex)
https://api.mapbox.com/directions/v5/mapbox/driving-traffic/-121.9819743,37.5297611;-121.9770517,37.5295998?access_token=<your_access_token>&geometries=polyline6&overview=full&steps=true&layers=0;&continue_straight=true&annotations=congestion_numeric,maxspeed,speed,duration,distance,closure&language=en&roundabout_exits=true&voice_instructions=true&banner_instructions=true&voice_units=imperial&enable_refresh=true

The route above has 6 steps with the last step pointing to the destination.
As per the logic in `ManeuverProcessor`

```
val stepIntersections = if (stepIndex == steps.lastIndex) {
    steps[stepIndex].intersections()
} else {
    steps[stepIndex + 1].intersections()
}
ifNonNull(
    steps[stepIndex].bannerInstructions(),
    stepIntersections
) { bannerInstruction, intersections ->
        val maneuverPoint = intersections.first().location()
}
```

`maneuverPoint` points to the first point for the next maneuver and not the current maneuver. For the last step, as there are no more steps, `maneuverPoint` points to the only point in the current maneuver. From a logical standpoint, this seems correct to me. I would like to understand the use case where you are probably seeing issues in the app.

/cc @yuryybk

**Comment by yuryybk** [comment]
@abhishek1508

The user scenario is related to the tapping on the maneuver in the maneuver list and moving the camera to the maneuver point to show the required maneuver. This question was from a logical assumption, but I didn't take into account that the last maneuver point is the destination point. So current implementation should be fine in this case.

**Comment by abhishek1508** [comment]
@yuryybk Okay that's great. Can you close this issue in that case?
