### ISSUE TITLE
Add async callback for requestFocus / abandonFocus

### ISSUE THREAD

**Issue by VitaminPSG** [mapbox/mapbox-navigation-android#5228]
AudioFocusDelegate returns sync callback for requestFocus/abandonFocus Because of what there is no way to implement `AUDIOFOCUS_REQUEST_DELAYED`

**Comment by Guardiola31337** [comment]
Hey @VitaminPSG now that https://github.com/mapbox/mapbox-navigation-android/pull/5652 landed, are we good here? If so, feel free to close this yourself when you have a chance 🙇‍♂️

**Comment by Guardiola31337** [comment]
cc @abhishek1508

**Comment by VitaminPSG** [comment]
I guess the issue that focus granted with delay, when guidance starts immediately

**Comment by abhishek1508** [comment]
@VitaminPSG Is this ticket good to be closed?

**Comment by VitaminPSG** [comment]
Yes, we can close it.
