### ISSUE TITLE
Received status code 401 from server: Unauthorized

### ISSUE THREAD

**Issue by shanmugaraj-raj** [mapbox/mapbox-navigation-android#5230]
Could not GET 'https://api.mapbox.com/downloads/v2/releases/maven/com/mapbox/navigation/android/2.0.2/android-2.0.2.pom'. Received status code 401 from server: Unauthorized
Disable Gradle 'offline mode' and sync project

Getting 401 unauthorized after adding navigation dependency
I've followed the steps given in the documents

**Comment by cafesilencio** [comment]
Can you double check your **secret token** has the `Downloads:Read` permission?

**Comment by shanmugaraj-raj** [comment]
yes @cafesilencio I have checked it. Till now I'm getting same 401 Unauthorized

**Comment by Zayankovsky** [comment]
@shanmugaraj-raj please make sure you followed every step of the [installation guide](https://docs.mapbox.com/android/navigation/guides/get-started/install/):
1. Specified your secret token (not public one) in global `gradle.properties`:
```gradle
MAPBOX_DOWNLOADS_TOKEN=your_secret_token_with_downloads_read_permission
```
2. Used the token in your project-level `build.gradle` when configuring repositories:
```gradle
allprojects {
    repositories {
        google()
        mavenCentral()
        maven {
              url 'https://api.mapbox.com/downloads/v2/releases/maven'
              authentication {
                  basic(BasicAuthentication)
              }
              credentials {
                  username = "mapbox"
                  password = project.properties['MAPBOX_DOWNLOADS_TOKEN'] ?: ""
              }
          }
    }
}
```
If you're still having problems then I will have to take a look at your project setup to help you further.

**Comment by shanmugaraj-raj** [comment]
@Zayankovsky I have followed the steps of installation guide 
1)  Added the secret token in gradle.properties (In both global and project module)

Global Properties :
    systemProp.https.proxyHost=
    systemProp.http.proxyHost=
    systemProp.https.proxyPort=
    systemProp.http.proxyPort=

    MAPBOX_DOWNLOADS_TOKEN=secret token

Project Properties :
    org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
    android.useAndroidX=true
    android.enableJetifier=true
    kotlin.code.style=official

    MAPBOX_DOWNLOADS_TOKEN=secret token
    
2) Configurations added in settings.gradle because I'm using Android Studio Arctic Fox | 2020.3.1 Patch 3

  dependencyResolutionManagement 
  {
     repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
     repositories
     {
        google()
        mavenCentral()
        maven
        {
            url 'https://api.mapbox.com/downloads/v2/releases/maven'
            authentication
            {
                basic(BasicAuthentication)
            }
            credentials
            {
                username = "mapbox"
                password = System.getenv('MAPBOX_DOWNLOADS_TOKEN') ?: ""
             }
        }
     }
  }
  rootProject.name = "MapBox_Example"
  include ':app'


Same problem exists now also

**Comment by Zayankovsky** [comment]
@shanmugaraj-raj sorry, there is an error in the guide. You can either configure repositories in `build.gradle` and remove `dependencyResolutionManagement` block from `settings.gradle` (as recommended for **Android Studio less than Arctic Fox (2020.3.1) and Gradle less than v6.0**) or replace
```gradle
password = System.getenv('MAPBOX_DOWNLOADS_TOKEN') ?: ""
```
with
```gradle
password = MAPBOX_DOWNLOADS_TOKEN
```

**Comment by shanmugaraj-raj** [comment]
@Zayankovsky Thanks, Its worked

**Comment by CPaaSAPI** [comment]
> 

No Such Permission present

**Comment by crnogorac-luka** [comment]
Unresolved reference: basic

**Comment by crnogorac-luka** [comment]
Function invocation 'BasicAuthentication(...)' expected
No value passed for parameter 'function'

**Comment by hokimtam** [comment]
thanks, my token missing download:read
