### ISSUE TITLE
Request: Vehicle Weight Limits

### ISSUE THREAD

**Issue by Danny-James** [mapbox/mapbox-navigation-android#528]
Would it be possible to pass through an optional vehicle weight limit which would then impact on the DirectionsRoute returned, this would help with Trucks and Large Vehicles where the Navigation is trying to take me down very small side streets.

This could then possibly prevent the vehicle from going down streets where their are weak bridges/low tunnels if the height is also passed through?

Regards.

**Comment by ericrwolfe** [comment]
Thanks for the feature request @Danny-James! This is helpful context and this is a problem our directions team is thinking about, but we don't have a concrete timeline for this specific type of routing support. We'll update this ticket if this changes in the future.
