### ISSUE TITLE
Request: Display Speed Limits 

### ISSUE THREAD

**Issue by Danny-James** [mapbox/mapbox-navigation-android#529]
Would it be possible to display the max speed limit of the road the user is currently navigating on?

See Example Below;
![screenshot_211](https://user-images.githubusercontent.com/32104383/33127663-51206da0-cf81-11e7-8f24-2d6e70bd8fad.jpg)

**Comment by ericrwolfe** [comment]
@Danny-James Thanks for the feedback. Our Directions API doesn't currently support this. We'll update this ticket if this changes in the future.

**Comment by Danny-James** [comment]
@ericrwolfe to we have anything in the pipeline to include this? I think it will be a great feature.

**Comment by Jlavatai** [comment]
I would also like this information!

**Comment by 1ec5** [comment]
There is some low-level support for speed limit data via the `maxspeed` annotation, which was implemented in mapbox/mapbox-java#772 and mapbox/mapbox-java#777. However, it’d be up to your application to display the speed limit in a custom UI. There’s also no guarantee about [the comprehensiveness of speed limit data](https://taginfo.openstreetmap.org/keys/maxspeed#map).

https://github.com/mapbox/mapbox-navigation-android/blob/2387ad585dcdd5b2849aed8aa53fd2e4fe3ea666/libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/routeprogress/CurrentLegAnnotation.java#L77-L86
