### ISSUE TITLE
The first voice instruction doesn't come to the client app

### ISSUE THREAD

**Issue by alexzatsepin** [mapbox/mapbox-navigation-android#5309]
## Case description and the observed behavior

STR:
1. Build the route close to the first maneuver

## Expected behavior
The first maneuver voice instruction should be played

## Actual behavior
Sometimes, if the route is built first time after the clean app install, the first maneuver is played, but too often, especially if you end the previous route and build the new one, the first voice instruction is missed because it doesn't come to `VoiceInstructionsObserver`.

## Notes / preliminary analysis
Seems like the [method](https://github.com/mapbox/mapbox-navigation-native/blob/2737fbf91d2f83fd90b1d153b6d379f88f819980/src/mapbox/navigation/instruction_manager.cpp#L59) considers that there is no need to create a new voice instruction for that case.

## History logs with reproduced issue
[2021-12-09T10-40-40Z_b336f950-aad8-4a2d-851d-aab8062925b8.pbf.gz](https://github.com/mapbox/mapbox-navigation-native/files/7684660/2021-12-09T10-40-40Z_b336f950-aad8-4a2d-851d-aab8062925b8.pbf.gz)
[2021-12-09T10-36-32Z_b351c74f-0f60-4b88-a173-23b71e5a7dcf.pbf.gz](https://github.com/mapbox/mapbox-navigation-native/files/7684662/2021-12-09T10-36-32Z_b351c74f-0f60-4b88-a173-23b71e5a7dcf.pbf.gz)
[2021-12-09T10-31-58Z_fbd9d145-86a9-4e63-abef-c80003d33bda.pbf.gz](https://github.com/mapbox/mapbox-navigation-native/files/7684663/2021-12-09T10-31-58Z_fbd9d145-86a9-4e63-abef-c80003d33bda.pbf.gz)

https://user-images.githubusercontent.com/8442156/145388998-05593187-1617-4784-91e6-db764cbbd986.mp4

## Environment
Android 11, Samsung galaxy s5e

- Nav sdk version: 2.1.0-rc.2

- Platform: Android, the issue reproduced on [this sample (Turn by turn)](https://github.com/mapbox/mapbox-navigation-android/blob/main/examples/src/main/java/com/mapbox/navigation/examples/core/MapboxNavigationActivity.kt) 

- Application:  Maps +, sample from Nav sdk

- Positioning signal source: doesn't matter. Reproduced on real location from the tablet and on the mock location by Lockito

**Comment by alexzatsepin** [comment]
This issue is produced by [this investigation](https://github.com/mapbox/mapbox-navigation-native/issues/4870).

**Comment by alexzatsepin** [comment]
The client app doesn't get the first voice instruction because of this skipping:

<img width="1274" alt="Снимок экрана 2021-12-22 в 19 32 02" src="https://user-images.githubusercontent.com/8442156/147124829-e3f113b4-db0f-458b-bd9d-d1431f5c46e2.png">

It leads to missing the first instruction at all, since **nav native** send voice instructions just once.

**Comment by korshaknn** [comment]
as said in the comments we skip RouteProgress, BannerInstructions, isOffRoute state updates `while setting a new route`
it means that we get `onStatus` update `before` we finished setting a route.
@DmitryAk could you please verify that NN calls `onStatus` only after `SetRouteCallback::run` . Might you have any thread race?

**Comment by DmitryAk** [comment]
@korshaknn `onStatus` callbacks are executed after the `setRoute` callback. I can assist with this issue reproducing.

**Comment by korshaknn** [comment]
@DmitryAk could you please provide timestamps of method calls on your side? so we will understand how much time a coroutine on our side has to wake up and finish

**Comment by DmitryAk** [comment]
@korshaknn these are the logged messages describing the sequence (if you need any clarification - just let me know):

> 2021-12-24 11:46:11.683 31491-31565/com.mapbox.navigation.examples E/nav-native: Schedule setRoute() callback
> 2021-12-24 11:46:11.684 31491-31491/com.mapbox.navigation.examples E/nav-native: Execute setRoute() callback
> 2021-12-24 11:46:11.714 31491-31565/com.mapbox.navigation.examples E/nav-native: Schedule onStatus() callback with SetRoute origin
> 2021-12-24 11:46:11.731 31491-31491/com.mapbox.navigation.examples E/nav-native: Execute onStatus() callback with SetRoute origin

**Comment by AntonBaikou** [comment]
@korshaknn is there any updates about this issue?

**Comment by LukasPaczos** [comment]
Resolved in https://github.com/mapbox/mapbox-navigation-android/pull/5807.
