### ISSUE TITLE
CacheResultUtils holds DirectionsRoute even there is no active route in MapboxNavigation.

### ISSUE THREAD

**Issue by zeac** [mapbox/mapbox-navigation-android#5311]
**Android API:**
**Mapbox Navigation SDK version:** 2.2.0-alpha.1

### Steps to trigger behavior

 1. Start navigation with any route
 2. Call to `MapboxNavigation.setRoutes(emptyList())

### Expected behavior
DirectionsRoute is quite heavy object. It would be better to get rid of any reference to them.

**Comment by LukasPaczos** [comment]
https://github.com/mapbox/mapbox-navigation-android/pull/5544 landed.
