### ISSUE TITLE
404. That’s an error. https://dl.google.com/dl/android/maven2/com/github/mukeshsolanki/android-otpview-pinview/2.1.0/android-otpview-pinview-2.1.0.pom

### ISSUE THREAD

**Issue by ShivaniChandel** [mapbox/mapbox-navigation-android#5371]
**Android API:**
**Mapbox Navigation SDK version:**

### Steps to trigger behavior

 1. 
 2.
 3.

**Comment by LukasPaczos** [comment]
Hey @ShivaniChandel, is this related to the Mapbox Navigation SDK?
