### ISSUE TITLE
Rerouting : At least two coordinates are required to render a route line

### ISSUE THREAD

**Issue by Christophe668** [mapbox/mapbox-navigation-android#5377]
**Android API:** 
**Mapbox Navigation SDK version:** 2.2.0-rc.1

Hi, 

On version 2.2.0-rc.1, the rerouting doesn't crash anymore (this issue seemed to be fixed https://github.com/mapbox/mapbox-navigation-android/issues/5214) 
Unfortunately, the routes after a rerouting are not drawn (see pictures below)
Can this be related to this warning? `The route geometry contained less than two coordinates. At least two coordinates are required to render a route line.`

Here are my RouteOptions :
```RouteOptions.builder()
			.applyDefaultNavigationOptions()
			.applyLanguageAndVoiceUnitOptions(ctx)
			.coordinates(start.toPoint(), null, end.toPoint())
			.profile(DirectionsCriteria.PROFILE_CYCLING)
			.overview(DirectionsCriteria.OVERVIEW_FALSE)
			.build()
```

here's what I do after a rerouting coming from `registerRoutesObserver` :
```		routeLineApi.setRoutes(newRoutes) { routeLineView.renderRouteDrawData(style, it) }```

### Steps to trigger behavior

1. Set a route
![Screenshot_20220118-163703](https://user-images.githubusercontent.com/1552554/149969299-d9a3144a-5e50-4fe1-a6ae-4227dcca63ea.jpg)

2. Force a rerouting : 
![Screenshot_20220118-163710](https://user-images.githubusercontent.com/1552554/149969256-12781706-0357-4d50-a009-0e1384778796.jpg)

3: Logs 
```
2022-01-18 16:37:06.497 1287-11336/bike.cowboy.app.debug I/nav-native: Directions Service: Get route request: https://api.mapbox.com/directions/v5/mapbox/cycling/4.3946185,50.8358901;4.379351,50.834826?access_token=****27CA&geometries=polyline6&overview=false&steps=true&bearings=144.2485046,90;&continue_straight=true&annotations=congestion_numeric,maxspeed,closure,speed,duration,distance&language=en&roundabout_exits=true&voice_instructions=true&banner_instructions=true&voice_units=imperial&enable_refresh=true
2022-01-18 16:37:06.582 1287-11466/bike.cowboy.app.debug I/nav-native: Directions Service: Get route response: {"message":"annotations value must be one of duration, distance, speed, maxspeed, congestion","code":"InvalidInput"} with code 422
2022-01-18 16:37:06.582 1287-11334/bike.cowboy.app.debug I/nav-native: Onboard router: Get route request: https://api.mapbox.com/directions/v5/mapbox/cycling/4.3946185,50.8358901;4.379351,50.834826?access_token=****27CA&geometries=polyline6&overview=false&steps=true&bearings=144.2485046,90;&continue_straight=true&annotations=congestion_numeric,maxspeed,closure,speed,duration,distance&language=en&roundabout_exits=true&voice_instructions=true&banner_instructions=true&voice_units=imperial&enable_refresh=true

2022-01-18 16:37:06.890 1287-1287/bike.cowboy.app.debug E/MbxRouteLineView: The route geometry contained less than two coordinates. At least two coordinates are required to render a route line.
```

**Comment by cafesilencio** [comment]
> 2022-01-18 16:37:06.582 1287-11466/bike.cowboy.app.debug I/nav-native: Directions Service: Get route response: {"message":"annotations value must be one of duration, distance, speed, maxspeed, congestion","code":"InvalidInput"} with code 422

This looks like the root of the issue. Looking at the last URL in your previous post it has profile = cycling and the annotations includles `congestion_numeric`.  This annotation is meant to used with the traffic profile and won't work with the cycling profile.  For cycling it should be `congestion`.

https://api.mapbox.com/directions/v5/mapbox/cycling/4.3946185%2C50.8358901%3B4.379351%2C50.834826?alternatives=true&annotations=distance%2Cduration%2Cspeed%2Ccongestion_numeric&continue_straight=true&geometries=polyline6&language=en&overview=full&steps=true&access_token=someToken

vs

https://api.mapbox.com/directions/v5/mapbox/cycling/4.3946185%2C50.8358901%3B4.379351%2C50.834826?alternatives=true&annotations=distance%2Cduration%2Cspeed%2Ccongestion&continue_straight=true&geometries=polyline6&language=en&overview=full&steps=true&access_token=someToken

If you paste these into a browser you'll see the first one returns an error. The only difference between the URL's being congestion_numeric vs congestion.

Resolving this may resolve the issue you're experiencing.

**Comment by Christophe668** [comment]
Thank you, I tried again today and indeed I don't have the warning anymore.
Although to route is till not drawing despite `routeLineApi.setRoutes(newRoutes) { routeLineView.renderRouteDrawData(style, it) }
` being called

I have those messages in the logs if it helps 
```
2022-01-21 12:18:52.323 7156-29890/bike.cowboy.app.debug I/nav-native: Waypoints were not passed to setRoute. Trying to restore it from route itself.

2022-01-21 12:18:52.323 7156-29890/bike.cowboy.app.debug W/nav-native: Cannot find via_waypoints in passed route. On-board waypoints matching will be used.

```

**Comment by Christophe668** [comment]
It seems that this line is messing up with the drawing of the rerouting. 
```			
.overview(DirectionsCriteria.OVERVIEW_FALSE)
```

Removing this line solves the issue.

Do you know what is happening?

**Comment by cafesilencio** [comment]
`.overview(DirectionsCriteria.OVERVIEW_FALSE)` explicitly excludes the geometry of the route which is needed in order to draw the route.  

`.applyDefaultNavigationOptions(DirectionsCriteria.PROFILE_CYCLING)` will default to full geometry.

**Comment by mubugvi** [comment]
I **resolve** this issue by adding this line for each **profile**        

-  .applyDefaultNavigationOptions(DirectionsCriteria.PROFILE_DRIVING)
-  .applyDefaultNavigationOptions(DirectionsCriteria.PROFILE_CYCLING)
-  .applyDefaultNavigationOptions(DirectionsCriteria.PROFILE_WALKING)


Here is my **mapboxNavigation.requestRoutes** method

    ```
private fun findRoute(profile: String) {
        val currentLocation = navigationLocationProvider.lastLocation
        val bearing = currentLocation?.bearing?.toDouble() ?: 45.0
        val originPoint = originPoint ?: return
        val destination = destinationPoint ?: return

        Log.d("RouteDebug", "Origin: $originPoint, Destination: $destination")

        mapboxNavigation.requestRoutes(
                RouteOptions.builder()
                    .applyDefaultNavigationOptions(profile)
                    .applyLanguageAndVoiceUnitOptions(this)
                    .coordinatesList(listOf(originPoint, destination))
                    .profile(profile)

                    .bearingsList(
                        listOf(
                            Bearing.builder()
                                .angle(bearing)
                                .degrees(45.0)
                                .build(),
                            null
                        )
                    )
                    .build(),


            object : RouterCallback {
                override fun onRoutesReady(
                    routes: List<DirectionsRoute>,
                    routerOrigin: RouterOrigin
                ){
                    setRouteAndStartNavigation(routes)
                }

                override fun onFailure(reasons: List<RouterFailure>, routeOptions: RouteOptions) {
                    reasons.forEach { reason ->
                        Log.e("RouteFailure", "Reason: ${reason.message}")
                    }
                    runOnUiThread {
                        finish()
                        Toast.makeText(
                            this@TurnbyturnActivity,
                            "Failed to find route",
                            Toast.LENGTH_SHORT
                        ).show()
                    }
                }

                override fun onCanceled(routeOptions: RouteOptions, routerOrigin: RouterOrigin) {
                    runOnUiThread {
                        finish()
                        Toast.makeText(
                            this@TurnbyturnActivity,
                            "Route request canceled",
                            Toast.LENGTH_SHORT
                        ).show()
                    }
                }
            }
        )
    }
```
