### ISSUE TITLE
Add options to configure origin/destination icons.

### ISSUE THREAD

**Issue by abhishek1508** [mapbox/mapbox-navigation-android#5389]
[`MapboxRouteLayerProvider`](https://github.com/mapbox/mapbox-navigation-android/blob/v2.1.1/libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/route/line/MapboxRouteLayerProvider.kt#L247-L272) is responsible to provide all the layers necessary for the functioning of a route line along with an origin/destination icon. Currently as can be seen in the implementation attached, the codebase adds some icon related properties based on the values SDK thinks is good enough. However, the implementation is missing some of the properties like `iconAnchor` and `iconOffset`. Also, there are possibilities that a customer might want to configure the values for all the properties related to icons.

We should expose these properties as options in the SDK thereby allowing customers to specify additional icon property values, opposed to the current behavior, where they can only specify the drawable for origin/destination icon pair.

One of the customer issue is attached [here](https://github.com/mapbox/navigation-sdks/issues/1398)

/cc @mapbox/navigation-android @mapbox/navigation-ios

**Comment by 762caliber** [comment]
Hi @abhishek1508 ,



Good Day.

May we have some updates on this please.

We like to know if this Feature request (RFE) will be considered or not,

and if yes, please provide a time line.


Best,
Colin Tan

cc @bentruscello , @venkat-b-1983 , @OttyLab

**Comment by cafesilencio** [comment]
@762caliber There is a pull request under review here: https://github.com/mapbox/mapbox-navigation-android/pull/5409.

**Comment by 762caliber** [comment]
Hi @abhishek1508 ,



I see this in #5409:

Merging is blocked
Merging can be performed automatically with 1 approving review.


Best,
Colin Tan

**Comment by abhishek1508** [comment]
@762caliber I think we have already provided NCS with a solution that would unblock them while we work on a longer term solution. I would like to understand the urgency of this as we would like to get in a solution that is well thought of and as I see we are still under code review.

cc @zugaldia

**Comment by 762caliber** [comment]
@zugaldia ,


The aim is to know which version of code is this planned / will this be implemented ( as a long term solution ).

We will set the customer's expectations accordingly.


Best,
Colin Tan

cc @bentruscello , @venkat-b-1983 , @OttyLab

**Comment by abhishek1508** [comment]
> @zugaldia ,
> 
> 
> The aim is to know which version of code is this planned / will this be implemented ( as a long term solution ).
> 
> We will set the customer's expectations accordingly.
> 
> 
> Best,
> Colin Tan
> 
> cc @bentruscello , @venkat-b-1983 , @OttyLab 
> 
> 
> 
> 

This will be available in this weeks release 2.3.0-alpha.2.
