### ISSUE TITLE
How I can set navigation follow by GPS tracking. 

### ISSUE THREAD

**Issue by trinhvanminh2009** [mapbox/mapbox-navigation-android#541]
I have the problem. The icon inside map Navigation Mapbox autoruns, not follow my GPS. I want my phone tracking by GPS and the icon navigation follow my location.

**Comment by Danny-James** [comment]
@trinhvanminh2009  Set `shouldSimulateRoute = false`, this can be done in the following way:

```
NavigationViewOptions.Builder optionsBuilder = NavigationViewOptions.builder() 
       .unitType(NavigationUnitType.TYPE_IMPERIAL) 
       .shouldSimulateRoute(shouldSimulateRoute); 

     if (route != null) { 
       optionsBuilder.directionsRoute(route); 
       NavigationLauncher.startNavigation(this, optionsBuilder.build()); 
     } 
```

**Comment by danesfeder** [comment]
@trinhvanminh2009 Yep thanks @Danny-James!  That's your solution above ^ you just need to set that boolean to false (which is the default in the `builder()` as well).

**Comment by trinhvanminh2009** [comment]
Thank you guys so much!

**Comment by danesfeder** [comment]
@trinhvanminh2009 let me know if you still have trouble with this, thanks - closing for now

**Comment by trinhvanminh2009** [comment]
@danesfeder I have the problem when I tried it. 
1. I compiled `  compile 'com.mapbox.mapboxsdk:mapbox-android-navigation:0.7.1-SNAPSHOT'
  compile 'com.mapbox.mapboxsdk:mapbox-android-navigation:0.7.0'`
2. NavigationViewOptions not found. 
3. Where to put these code (Example: onRunning, onProgressChange,.. etc )
Sorry I'm beginner using Mapbox
