### ISSUE TITLE
Replayer restart fix

### ISSUE THREAD

**Issue by korshaknn** [mapbox/mapbox-navigation-android#5419]
`Replayer` should not restart on route refresh/alternatives update

when refreshed route leg is not equal the old route leg, `ReplayProgressObserver::onRouteLegChanged` is called and we seek replayer to the first instruction of a new leg.

also we need to test it when we switch from the primary route to alternative

**Comment by kmadsen** [comment]
@korshaknn will you update this title to be "Add support for simulating alternative routes". The simulator at this point is designed to handle a single route. ReplayProgressObserver added support for waypoints. Make sure, that the changes to support alternative routes will continue to support waypoints.

Also take a look at the discussion in https://github.com/mapbox/mapbox-navigation-android/pull/5274. It would be nice to clean up events that have been played.

**Comment by korshaknn** [comment]
actually, it changes, not critical, but some values are different, so, `equals` method works as expected, for example take a look at 2 legs:
[legs.zip](https://github.com/mapbox/mapbox-navigation-android/files/7959469/legs.zip)

mostly the are the same, there are some minor differences in `annotations`, check the screenshots (in the zip).
