### ISSUE TITLE
Pass requestIdentifier to metrics

### ISSUE THREAD

**Issue by ericrwolfe** [mapbox/mapbox-navigation-android#545]
Now that MAS exposes the directions request identifier (uuid), we need to pass this off to our metrics events as `requestIdentifier` and `originalRequestIdentifier`.

cc @cammace @danesfeder @drboyer

**Comment by cammace** [comment]
Note that this is currently blocked by https://github.com/mapbox/mapbox-java/issues/668

**Comment by cammace** [comment]
mapbox/mapbox-java#668 has been fixed and this is now unblocked.

**Comment by cammace** [comment]
https://github.com/mapbox/mapbox-navigation-android/pull/550/files#diff-733123be2c829f809339b109270cae0dR147 looks to include the UUID info in the metrics. Not sure if we want to pass in `""` when the value is null (which should never happen) or `null` as in a JsonObjectNull? If the former, this tickets safe to close.

**Comment by danesfeder** [comment]
Landed in #550

**Comment by ericrwolfe** [comment]
Looks like `originalRequestIdentifier` is being set correctly, but `requestIdentifier` in the json payloads is still always set to `null`. @danesfeder Can we look back into this?

cc @srividyacb

**Comment by danesfeder** [comment]
Fixed with #585
