### ISSUE TITLE
Flaky `CoreRerouteTest#reroute_completes` test

### ISSUE THREAD

**Issue by Guardiola31337** [mapbox/mapbox-navigation-android#5452]
Capturing from https://github.com/mapbox/mapbox-navigation-android/pull/5431#issuecomment-1026151883

```
01-31 10:46:31.411: E/TestRunner(21017): failed: reroute_completes(com.mapbox.navigation.instrumentation_tests.core.CoreRerouteTest)
01-31 10:46:31.411: E/TestRunner(21017): ----- begin exception -----
01-31 10:46:31.412: E/TestRunner(21017): java.lang.RuntimeException: java.util.concurrent.ExecutionException: androidx.test.espresso.IdlingResourceTimeoutException: Wait for [RouteProgressStateIdlingResource] to become idle timed out
01-31 10:46:31.412: E/TestRunner(21017): 	at androidx.test.espresso.Espresso.onIdle(Espresso.java:15)
01-31 10:46:31.412: E/TestRunner(21017): 	at androidx.test.espresso.Espresso.onIdle(Espresso.java:1)
01-31 10:46:31.412: E/TestRunner(21017): 	at com.mapbox.navigation.instrumentation_tests.core.CoreRerouteTest$reroute_completes$4.invoke(CoreRerouteTest.kt:172)
01-31 10:46:31.412: E/TestRunner(21017): 	at com.mapbox.navigation.instrumentation_tests.core.CoreRerouteTest$reroute_completes$4.invoke(CoreRerouteTest.kt:171)
01-31 10:46:31.412: E/TestRunner(21017): 	at com.mapbox.navigation.instrumentation_tests.utils.history.MapboxHistoryTestRule.stopRecordingOnCrash(MapboxHistoryTestRule.kt:59)
01-31 10:46:31.412: E/TestRunner(21017): 	at com.mapbox.navigation.instrumentation_tests.core.CoreRerouteTest.reroute_completes(CoreRerouteTest.kt:171)
01-31 10:46:31.412: E/TestRunner(21017): 	at java.lang.reflect.Method.invoke(Native Method)
01-31 10:46:31.412: E/TestRunner(21017): 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
01-31 10:46:31.412: E/TestRunner(21017): 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
01-31 10:46:31.412: E/TestRunner(21017): 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
01-31 10:46:31.412: E/TestRunner(21017): 	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
01-31 10:46:31.412: E/TestRunner(21017): 	at androidx.test.internal.runner.junit4.statement.RunBefores.evaluate(RunBefores.java:80)
01-31 10:46:31.412: E/TestRunner(21017): 	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
01-31 10:46:31.412: E/TestRunner(21017): 	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
01-31 10:46:31.412: E/TestRunner(21017): 	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
01-31 10:46:31.412: E/TestRunner(21017): 	at androidx.test.rule.GrantPermissionRule$RequestPermissionStatement.evaluate(GrantPermissionRule.java:134)
01-31 10:46:31.412: E/TestRunner(21017): 	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
01-31 10:46:31.412: E/TestRunner(21017): 	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
01-31 10:46:31.412: E/TestRunner(21017): 	at com.adevinta.android.barista.rule.cleardata.ClearDatabaseRule$apply$1.evaluate(ClearDatabaseRule.kt:31)
01-31 10:46:31.412: E/TestRunner(21017): 	at com.adevinta.android.barista.rule.cleardata.ClearPreferencesRule$1.evaluate(ClearPreferencesRule.java:26)
01-31 10:46:31.412: E/TestRunner(21017): 	at com.adevinta.android.barista.rule.cleardata.ClearFilesRule$apply$1.evaluate(ClearFilesRule.kt:25)
01-31 10:46:31.412: E/TestRunner(21017): 	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
01-31 10:46:31.412: E/TestRunner(21017): 	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
01-31 10:46:31.412: E/TestRunner(21017): 	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
01-31 10:46:31.412: E/TestRunner(21017): 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
01-31 10:46:31.412: E/TestRunner(21017): 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
01-31 10:46:31.412: E/TestRunner(21017): 	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
01-31 10:46:31.412: E/TestRunner(21017): 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
01-31 10:46:31.412: E/TestRunner(21017): 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
01-31 10:46:31.412: E/TestRunner(21017): 	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
01-31 10:46:31.412: E/TestRunner(21017): 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
01-31 10:46:31.412: E/TestRunner(21017): 	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
01-31 10:46:31.412: E/TestRunner(21017): 	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
01-31 10:46:31.412: E/TestRunner(21017): 	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
01-31 10:46:31.412: E/TestRunner(21017): 	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
01-31 10:46:31.412: E/TestRunner(21017): 	at org.junit.runners.Suite.runChild(Suite.java:128)
01-31 10:46:31.412: E/TestRunner(21017): 	at org.junit.runners.Suite.runChild(Suite.java:27)
01-31 10:46:31.412: E/TestRunner(21017): 	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
01-31 10:46:31.412: E/TestRunner(21017): 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
01-31 10:46:31.412: E/TestRunner(21017): 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
01-31 10:46:31.412: E/TestRunner(21017): 	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
01-31 10:46:31.412: E/TestRunner(21017): 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
01-31 10:46:31.412: E/TestRunner(21017): 	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
01-31 10:46:31.412: E/TestRunner(21017): 	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
01-31 10:46:31.412: E/TestRunner(21017): 	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
01-31 10:46:31.412: E/TestRunner(21017): 	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
01-31 10:46:31.412: E/TestRunner(21017): 	at androidx.test.internal.runner.TestExecutor.execute(TestExecutor.java:56)
01-31 10:46:31.412: E/TestRunner(21017): 	at androidx.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:444)
01-31 10:46:31.412: E/TestRunner(21017): 	at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2196)
01-31 10:46:31.412: E/TestRunner(21017): Caused by: java.util.concurrent.ExecutionException: androidx.test.espresso.Idlin
```

> Apparently NN didn't sent the `OFF_ROUTE` event:
>
>```
>01-31 10:46:31.124: E/DEBUG(21017): no off route history path=/data/user/0/com.mapbox.navigation.instrumentation_tests/files/mbx_nav/history/2022-01-31T18-46-04Z_beee1863-f27b-4d84-9ec7-070d6b233d39.pbf.gz
>```
>
>Attaching the history file for further analysis [2022-01-31_18_44_54.973188_LXJN_flame-29-de-landscape_artifacts_sdcard_Download_mapbox_test_reroute_completes_2022-01-31T18-46-04Z_beee1863-f27b-4d84-9ec7-070d6b233d39.pbf.gz](https://github.com/mapbox/mapbox-navigation-android/files/7973814/2022-01-31_18_44_54.973188_LXJN_flame-29-de-landscape_artifacts_sdcard_Download_mapbox_test_reroute_completes_2022-01-31T18-46-04Z_beee1863-f27b-4d84-9ec7-070d6b233d39.pbf.gz) cc @mapbox/navnative 

It failed again in https://github.com/mapbox/mapbox-navigation-android/pull/5449 https://app.circleci.com/pipelines/github/mapbox/mapbox-navigation-android/16346/workflows/7d41518a-cb6e-448c-8aa6-2770cc7ff2da/jobs/72456 https://console.firebase.google.com/u/1/project/mapbox-navigation-android/testlab/histories/bh.54eb2dd57e959221/matrices/9009211239467314706/executions/bs.1ce5bc48ab4fe15f/testcases/1

cc @kmadsen @mapbox/navnative

**Comment by Guardiola31337** [comment]
Again as part of https://github.com/mapbox/mapbox-navigation-android/pull/5457 https://app.circleci.com/pipelines/github/mapbox/mapbox-navigation-android/16411/workflows/e64f081c-c4a7-4388-8136-48b3b7bae2f7/jobs/72854 https://console.firebase.google.com/u/1/project/mapbox-navigation-android/testlab/histories/bh.54eb2dd57e959221/matrices/7654022931198673838/executions/bs.8fa81a7e85116967/testcases/1

Sharing the history file for reference [2022-02-11_15_41_03.829102_LApO_hammerhead-23-fr-portrait_artifacts_sdcard_Download_mapbox_test_reroute_completes_2022-02-11T15-43-38Z_0986fa73-d5c6-4c41-80c5-fa6a078e1ed6.pbf.gz](https://github.com/mapbox/mapbox-navigation-android/files/8049985/2022-02-11_15_41_03.829102_LApO_hammerhead-23-fr-portrait_artifacts_sdcard_Download_mapbox_test_reroute_completes_2022-02-11T15-43-38Z_0986fa73-d5c6-4c41-80c5-fa6a078e1ed6.pbf.gz)

**Comment by mskurydin** [comment]
The root cause seems clear. There is a jump to 220m in the test. We filter a couple of locations, but when we acknowledge we jumped far, we enter the off-road mode in fallback.

![image](https://user-images.githubusercontent.com/199848/153634472-fdf56e46-e694-4558-a714-c258ba3d413e.png)

This is a rather artificial case though. We recently introduced the off-road indication for the fallback mode as well (we see no tiles are used in the test; this is fallback).

cc @buevichd @SiarheiFedartsou

**Comment by Guardiola31337** [comment]
Still trying to figure out how we can prevent the ingestion of those weird off-locations.

cc @VysotskiVadim @korshaknn

**Comment by mskurydin** [comment]
Note, it's most likely not the off location that causes the issue. Even without this jump, your 220m jump will result in an off-road situation here (and thus no `complete` or `offRoute` states)

**Comment by SiarheiFedartsou** [comment]
Fake edge is 500m, i.e. even with this 220m jump we should have go off route

**Comment by Guardiola31337** [comment]
Updating the fixture https://github.com/mapbox/mapbox-navigation-android/pull/5457/commits/0494fd1947bafa69b756209a22eca3cb20a075ff fixed the issue 💃 

@mskurydin @SiarheiFedartsou could you speak more about what did it change? I'm also wondering how we can prevent these regressions in the future. Should we update the fixtures from time to time? How often? 🤔

**Comment by buevichd** [comment]
> @mskurydin @SiarheiFedartsou could you speak more about what did it change? I'm also wondering how we can prevent these regressions in the future. Should we update the fixtures from time to time? How often? 🤔

The changes were done in [this ticket](https://github.com/mapbox/mapbox-navigation-native/issues/5204).

The main change is that before in we always think we are on road when we are in Fallback mode (that sounds weird, but still). 

Now we can go offRoad in Fallback, but in this case we never go offRoute. It's expected behaviour because you don't need a new route if you drove off the road for some time.

The main issue is that in Fallback mode we can not differ real off road and just moving to a road outside the current route. This should be differ by "fish bone edges" which are coming in setRoute. Seems updated fixture is containing those "fish bone edges".

I don't think you need to update the fixtures from time to time.

**Comment by buevichd** [comment]
BTW there is route changes from your commit, which is needed to make correct "fish bone edges":
<img width="633" alt="Screenshot 2022-02-15 at 14 36 29" src="https://user-images.githubusercontent.com/20580572/154055016-8a558cb6-37cf-4a8e-be37-bbc09ccfe3f9.png">

**Comment by Guardiola31337** [comment]
Thanks for clarifying @buevichd 

Closing as fixed.
