### ISSUE TITLE
Navigation Multiple Routes

### ISSUE THREAD

**Issue by ritup22** [mapbox/mapbox-navigation-android#546]
I want to have multiple routes on map of navigation view also, is this possible in Mapbix currently like google map shows?

**Comment by danesfeder** [comment]
@ritup22 Unfortunately, we currently don't offer this capability for the turn-by-turn navigation UI.  The `NavigationMapRoute` now does support multiple routes, so you'd be able to build something with our core SDK and custom views.

**Comment by ritup22** [comment]
Thanks for reply

I NavigationMapRoute provides but still with my custom views I am not able to select route runtime & also not all the functionality like re-routing re-calculating route is coming & working as per turn by turn navigation

**Comment by Guardiola31337** [comment]
Hey 👋 @ritup22 Thanks for reaching out and report your question.

> is this possible in Mapbix currently like google map shows

Could you clarify here? Do you mean selectable alternative routes while navigating?

**Comment by danesfeder** [comment]
Hey @ritup22 👋 this is technically possible now with the `NavigationView`:

```
    navigationView.retrieveNavigationMapboxMap().showAlternativeRoutes(true);
    navigationView.retrieveNavigationMapboxMap().setOnRouteSelectionChangeListener(directionsRoute -> {
      startNavigation(directionsRoute);
    });
``` 

Thanks for the feedback and checking out the SDK!  Closing as finished here.

**Comment by danesfeder** [comment]
Re-opening because when `NavigationView#startNavigation` is called, we will only draw the one passed, removing the alternatives.  This solution would only work prior to navigating - sorry for the confusion @ritup22

**Comment by Guardiola31337** [comment]
@abhishek1508 is this still an issue in the `1.0` UI SDK?

cc @cafesilencio

**Comment by abhishek1508** [comment]
Let's verify
cc @JunDai @cafesilencio @langsmith

**Comment by abhishek1508** [comment]
We don't support this feature. It's not an issue. Closing it now and we can reopen if we decide to execute it as a feature.
cc @Guardiola31337
