### ISSUE TITLE
Caused by: org.gradle.api.internal.artifacts.ivyservice.DefaultLenientConfiguration$ArtifactResolveException: Could not resolve all files for configuration ':libnavigation-base:debugCompileClasspath'.

### ISSUE THREAD

**Issue by ranjansigdel** [mapbox/mapbox-navigation-android#5547]
**Android API:**
**Mapbox Navigation SDK version:**

### Steps to trigger behavior

 1.
 2.
 3.

**Comment by LukasPaczos** [comment]
Hey @ranjansigdel, where you trying to build the project from source and encountered this error?

Please feel free to open a new ticket with more information.
