### ISSUE TITLE
Default milestone identifier is always one. Is it correct? 

### ISSUE THREAD

**Issue by josephquzhou** [mapbox/mapbox-navigation-android#556]
According to documents there are several types of default milestones. Why their identifiers are always one?

**Comment by danesfeder** [comment]
Hey @josephquzhou, our docs will be be updated this week as those default milestones have been removed - we have one milestone https://github.com/mapbox/mapbox-navigation-android/blob/master/libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/milestone/VoiceInstructionMilestone.java that fires for each voice instruction given along the route.  

You can add your own `Milestone`s to trigger at any time during the route progression though.  Check out our docs on how to do this: https://www.mapbox.com/android-docs/navigation/overview/milestones/#building-a-custom-milestone
