### ISSUE TITLE
[Question] Can onNewLocationMatcherResult return enhanced location for walking profile

### ISSUE THREAD

**Issue by ohcheung** [mapbox/mapbox-navigation-android#5596]
**Mapbox Navigation SDK version:**  2.3

Hi, I am using LocationObserver to listen to location updates, I would like to know if onNewLocationMatcherResult can return enhanced location for different profile (e.g. walking), or is it limited to driving profile only?

I tried setting the tileProfiles to "walking" in RoutingTileOptions and pass it to NavigationOptions like this:

```
RoutingTilesOptions routingTilesOptions = new RoutingTilesOptions.Builder()
                .tilesProfile("walking")
                .filePath(getApplicationContext().getCacheDir())
                .build();

        navigationOptions = new NavigationOptions.Builder(this)
                .accessToken(ACCESS_TOKEN)
                .routingTilesOptions(routingTilesOptions)
                .build();

        mapboxNavigation = MapboxNavigationProvider.create(navigationOptions);
        mapboxNavigation.startTripSession(false);
```

But the route returned seems to be snapped to nearest road (using driving profile). It doesn't map to nearby sidewalks. Is this the correct way to do it?

If it doesn't support other profiles, is using the Map Matching API the best alternative to accomplish this?

Thank you!

### Expected behavior
After setting "walking" in tilesProfile, onNewLocationMatcherResult will return enhanced location that is snapped to nearest sidewalk. 

### Actual behavior
Enhanced location returns nearest road.

**Comment by mskurydin** [comment]
At the moment, pedestrian navigation works only when a route is set (built with a `walking` profile). In this case, we shall return enhanced locations that are matched to the route. The routing tile options are used only for auto navigation profiles right now.

**Comment by ohcheung** [comment]
hi @Guardiola31337 , I couldn't find the page (it returned 404)

thanks for the clarification @mskurydin
