### ISSUE TITLE
DirectionRoute could not resolved

### ISSUE THREAD

**Issue by chean5143** [mapbox/mapbox-navigation-android#561]
I had included below compile into dependency.

    compile 'com.mapbox.mapboxsdk:mapbox-android-navigation:0.7.1-SNAPSHOT'
    compile ('com.mapbox.mapboxsdk:mapbox-android-navigation-ui:0.7.1-SNAPSHOT') {
        transitive = true
    }

Just morning my code is still working, now suddenly it said DirectionRoute could not resolved when I import

> import com.mapbox.directions.v5.models.DirectionsRoute;

**Comment by chean5143** [comment]
I have solved the problem by changing the import
`import com.mapbox.api.directions.v5.models.DirectionsRoute`

However, below 3 statements of code still in error due to 
`import com.mapbox.directions.v5.models.DirectionsRoute` cannot be applied to `import com.mapbox.api.directions.v5.models.DirectionsRoute`



1. 

`navigationMapRoute.addRoutes(response.body().routes())` 

2.
```
NavigationViewOptions.Builder optionsBuilder = NavigationViewOptions.builder()
                .unitType(NavigationUnitType.TYPE_IMPERIAL)
                .shouldSimulateRoute(simulateRoute);
        optionsBuilder.directionsRoute(route);
        NavigationViewOptions options = optionsBuilder.build();
```

3.
```
editor.putString(NavigationConstants.NAVIGATION_VIEW_ROUTE_KEY, new GsonBuilder()
                .registerTypeAdapterFactory(DirectionsAdapterFactory.create()).create().toJson(options.directionsRoute()));
```

**Comment by kirtan-inexture** [comment]
@chean5143 How did you solved it?

**Comment by chean5143** [comment]
I just restarted Android Studio then it worked.
