### ISSUE TITLE
Enable snapping to closure for the origin of the re-route by default

### ISSUE THREAD

**Issue by LukasPaczos** [mapbox/mapbox-navigation-android#5664]
There are situations where a user can intentionally turn into, or start a route from an edge that is marked a `closed`. In these situations, the router would continuously try to reroute the user until they leave the closed edge.

However, we could trust or map-matcher more and always allow for snapping to closures for the origin of the route which would prevent continuous reroutes and only attempt to drives us out of the closer as soon as possible.

cc @dudeuter

**Comment by LukasPaczos** [comment]
cc @mskurydin

**Comment by mskurydin** [comment]
It's more of a question of whether the routing engine allows starting from such edges. We pass a coordinate of the origin (potentially, with some additional data). Potentially,

**Comment by LukasPaczos** [comment]
Yes, this is exactly the param we'd want to use for the first waypoint of the route.

**Comment by dudeuter** [comment]
@mskurydin For devices with precached tiles prior to a closure, I'm assuming nav-native will happily match to them. But do the nav-native tiles contain closures, and if so will enhanced location avoid closures?

**Comment by LukasPaczos** [comment]
Circling back to this ticket, @browndp08 @stari4ek should Nav SDKs default to including the origin of the route in `snapping_include_closures`?

> do we already imply that the expected default behavior of a route request is to start at the current location of the vehicle?

We don't for the initial route request, we do for reroutes though, and we have a utility on the way that would pick the current vehicle's location automatically also for initial requests - https://github.com/mapbox/mapbox-navigation-android/pull/5427.

**Comment by browndp08** [comment]
Great slack convo on this https://mapbox.slack.com/archives/C01BNUNRET0/p1652857645714569

>snapping_include_closures=true  makes sense for auto case, when starting waypoint is the current position of the car. so we can have good enough confidence in it (and better gps and bearing from car also helps here).
but in general - it does not fit to the use case when user plan trip by selecting point on the map or using search

From @stari4ek

**Comment by LukasPaczos** [comment]
Capturing from the team discussion, renaming the ticket to track the change to our re-route controller to apply `snapping_include_closures=true` for the origin of each re-route request. The default request can remain as is.
