### ISSUE TITLE
Expose navigation listeners while using drop-in UI

### ISSUE THREAD

**Issue by ericrwolfe** [mapbox/mapbox-navigation-android#567]
On iOS, developers can listen in on core navigation lifecycle events while using the drop-in UI (NavigationView), such as arrivals, reroutes, feedback events, etc:
* https://www.mapbox.com/mapbox-navigation-ios/navigation/0.11.0/Protocols/NavigationViewControllerDelegate.html
* https://www.mapbox.com/mapbox-navigation-ios/navigation/0.11.0/Protocols/RouteControllerDelegate.html

Currently, Android developers can implement custom navigation and hook up the default Navigation SDK UI components manually for similar functionality (https://www.mapbox.com/android-docs/navigation/overview/navigation-ui/#custom-views).

However, we should make this easier for developers and add expose these callbacks for use with the Android SDK's drop-in UI.

cc @mapbox/navigation-android @stephenlambe @brsbl

**Comment by danesfeder** [comment]
@ericrwolfe do you mind creating a list of listeners you'd like to add for `0.8.0`?  

We can always expand these in later releases as needed. Thanks!

**Comment by ericrwolfe** [comment]
@danesfeder @devotaaabel Here are the main events developers should be able to hook into while using the NavigationView.

General lifecycle:
- location/routeProgress did update
- did arrive at waypoint
- did cancel/exit navigation

Reroute lifecycle:
- should reroute
- will reroute
- did reroute
- did fail to reroute

Feedback:
- did open feedback UI
- did cancel feedback UI
- did send feedback

**Comment by ericrwolfe** [comment]
This landed in https://github.com/mapbox/mapbox-navigation-android/pull/614 (SDK v0.8.0) 🎉
