### ISSUE TITLE
Integrate new trim offset feature for vanishing route line

### ISSUE THREAD

**Issue by cafesilencio** [mapbox/mapbox-navigation-android#5673]
A new feature has been added by the GL team for use in the vanishing route line feature.  It is more performant than the current method used in the SDK.  The SDK will need to be modified to take advantage of this new feature.  Since the feature doesn't support coloring the line behind the puck as the SDK does, additional layers will need to be added to preserve the appearance currently available in the SDK.  There are options in the SDK for coloring the route line and the casing line behind the puck.

**Comment by 1ec5** [comment]
mapbox/mapbox-navigation-ios#3818 tracks the corresponding work on iOS.

**Comment by cafesilencio** [comment]
It looks like the maps team is targeting version 10.5 for this feature (at least on Android).
