### ISSUE TITLE
Route lines flash on alternative routes refresh/switch

### ISSUE THREAD

**Issue by LukasPaczos** [mapbox/mapbox-navigation-android#5687]
Refs https://github.com/mapbox/mapbox-navigation-android/pull/5653.

As you can see in this video:

https://user-images.githubusercontent.com/16925074/161552830-9ba6dda9-6abe-40c6-88db-3dd9f9149fe4.mp4

The alternative routes briefly flash their whole, unvanished geometry when they are refreshed on manually switched. We should look into optimizing the route line implementation to prevent this flash.

**Comment by LukasPaczos** [comment]
The issue has been partially addressed by https://github.com/mapbox/mapbox-navigation-android/pull/5859 where routes do not flash when automatically recomputed but reopening to track changes needed in https://github.com/mapbox/mapbox-navigation-native/issues/5893 to resolve an occasional flash of the alternative geometry as the route is manually switched.

**Comment by abhishek1508** [comment]
Closing this ticket as https://github.com/mapbox/mapbox-navigation-native/issues/5893 has been fixed and released in NN `v107.0.0`
