### ISSUE TITLE
MockLocationEngine and setLocationSource 

### ISSUE THREAD

**Issue by PatrickZenker** [mapbox/mapbox-navigation-android#57]
Hey,
I'm using your pretty cool MockLocationEngine from the demo project. I noticed that the myLocationEnabled state is resettet after the LocationEngine is set (@ mapbox-android-navigation:0.2.0). 

If I use only this code, the myLocation-Dot at the map doesn't move (even if I had set myLocationEnabled to true and MyLocationTracking.TRACKING_FOLLOW).
`mapboxMap.setLocationSource(mockLocationEngine);`

With the additional line
`mapboxMap.setMyLocationEnabled(true);`
everything work well.

But: In both cases the onMyLocationChange-Listener receives the update from MockLocationEngine

**Comment by Grsmto** [comment]
Hi,
I'm not sure to understand your problem but it seems to be coming from the Map SDK, so it's not related to this repository but more to [this one](https://github.com/mapbox/mapbox-gl-native/).
Thanks!

**Comment by cammace** [comment]
I'm not sure I understand your issue, but I have a setup using both the Mapbox Map, Mock location, and Navigation SDK [here](https://github.com/mapbox/mapbox-navigation-android/blob/master/navigation/app/src/main/java/com/mapbox/services/android/navigation/testapp/activity/MockLocationEngine.java). Closing issue but if you still are having issues, happy to help.
