### ISSUE TITLE
Implement slight turn completion heuristic

### ISSUE THREAD

**Issue by ericrwolfe** [mapbox/mapbox-navigation-android#578]
Android version of https://github.com/mapbox/mapbox-navigation-ios/pull/378, supersedes https://github.com/mapbox/mapbox-navigation-android/issues/35.

Maneuver completion is triggered prematurely along off ramps, continue steps, and other steps where the in and out bearing are approximately the same.

From the iOS implementation:
> For slight turns like on/off ramps, this falls apart quickly since the user's course is easily within x degrees of the exit heading.

> This PR looks at the difference between the initial and exit heading. If their difference is less than x degrees, then don't rely on the exit heading check. Instead, rely on their snapped distance from the maneuver location. Once the user is at or moving away from the maneuver location, their snapped distance will always be zero. If it's zero, increment the step.

cc @cammace @danesfeder @bsudekum

**Comment by danesfeder** [comment]
@ericrwolfe is this the roundabout / on ramp off-route issue or unrelated?

**Comment by ericrwolfe** [comment]
This is unrelated to roundabouts and off-routes. Instead, this is related to voice announcements happening ~50m before where they should because we think the maneuver is complete, when in reality the user has only just entered the maneuver radius. 

We currently mark the maneuver as complete at the red dot, and should instead consider the maneuver complete at the black dot:
![image](https://user-images.githubusercontent.com/664805/33915349-a6592696-df57-11e7-8ff2-8dc3aa524a4f.png)

If a driver were to be waiting at traffic light between the red and black dot, we would have already announced the "completion"/"new step" voice announcement telling the driver to "Continue on X for Y miles".

**Comment by brsbl** [comment]
Closed by https://github.com/mapbox/mapbox-navigation-android/pull/667
