### ISSUE TITLE
Custom styling for alternative routes not working.

### ISSUE THREAD

**Issue by cafesilencio** [mapbox/mapbox-navigation-android#5791]
There is a route line feature where by a developer can color the alternative routes differently based on a provided identifier.  If for example a route is set on the `MapboxRouteLineApi` with an identifier of "foobar" and a `RouteStyleDescriptor` is added to the `MapboxRouteLineOptions` with the same identifier and a color then the specified route (when an alternative route) should take on the specified color on the map.

This feature currently isn't working. It's possibly a regression introduced by the trim-offset feature recently implemented for the vanishing route line.

**Comment by LukasPaczos** [comment]
Adding a release blocker label until we full understand the impact and next steps.

**Comment by LukasPaczos** [comment]
@cafesilencio in this case it looks like we need to incorporate `RouteStyleDescriptor` settings into the functions that generate expressions for the deviation offset in https://github.com/mapbox/mapbox-navigation-android/blob/b1220190bc2d5fc30ad0751030c58f3426b73166/libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/route/line/api/MapboxRouteLineApi.kt#L1233-L1271
