### ISSUE TITLE
[Android Auto] Integrate maps widgets for current road label

### ISSUE THREAD

**Issue by kmadsen** [mapbox/mapbox-navigation-android#5794]
Similar to this issue https://github.com/mapbox/mapbox-navigation-android/issues/5793

Considering this ticket separate because there is a different framework for rendering the road label.

The `RoadLabelRenderer` will fit a road label text onto a Bitmap. For this ticket, instead of using the surfacelayer from android auto; try using the widget api. An example is here https://github.com/mapbox/mapbox-maps-android/tree/main/extension-androidauto/src/main/java/com/mapbox/maps/extension/androidauto/widgets

Try deleting the surfacelayer module and then adding the functionality back with the new widget api.
https://github.com/mapbox/mapbox-navigation-android/tree/main/libnavui-androidauto/src/main/java/com/mapbox/androidauto/surfacelayer

**Comment by Zayankovsky** [comment]
Blocked by mapbox/mapbox-maps-android#1531.
