### ISSUE TITLE
Additional route calculation parameter

### ISSUE THREAD

**Issue by PatrickZenker** [mapbox/mapbox-navigation-android#58]
Hey,

is there a plan to add different route calculation parameters?
For example: 
- car
- bicycle
- pedestrian

- fastes route
- shortest route

- language (for maneuver instructions)

Best regards,
Patrick

**Comment by Grsmto** [comment]
This will be supported once #63 is merged.

**Comment by PatrickZenker** [comment]
Yeah, a part of this is duplicate. But is there a roadmap / schedule - especially for multiple language support?
