### ISSUE TITLE
MockLocationEngine & onProgressChange

### ISSUE THREAD

**Issue by Niduank** [mapbox/mapbox-navigation-android#580]
I report a bug when using MockLocationEngine->setRoute to simulate a navigation.
Look at my log : 

First navigation :
12-08 13:33:11.259 32363-32363/ E/MapboxActivity: onProgressChange
12-08 13:33:12.252 32363-32363/ E/MapboxActivity: onProgressChange
12-08 13:33:13.230 32363-32363/ E/MapboxActivity: onProgressChange
12-08 13:33:14.247 32363-32363/ E/MapboxActivity: onProgressChange 
onProgressChange is called once by second.

Second navigation : (second setRoute())
12-08 13:33:29.313 32363-32363/ E/MapboxActivity: onProgressChange
12-08 13:33:29.414 32363-32363/ E/MapboxActivity: onProgressChange
12-08 13:33:30.309 32363-32363/ E/MapboxActivity: onProgressChange
12-08 13:33:30.408 32363-32363/ E/MapboxActivity: onProgressChange
12-08 13:33:31.297 32363-32363/ E/MapboxActivity: onProgressChange
12-08 13:33:31.408 32363-32363/ E/MapboxActivity: onProgressChange
As you can see onProgressChange is called twice by second.

Third navigation : (third setRoute())
onProgressChange is called three times by second.

Device info : Samsung galaxy s7 - Android 7.0
Versions of SDK used : 
implementation('com.mapbox.mapboxsdk:mapbox-android-sdk:5.2.0@aar') {
        transitive = true
    }
implementation 'com.mapbox.mapboxsdk:mapbox-android-navigation:0.7.0'
implementation('com.mapbox.mapboxsdk:mapbox-android-navigation-ui:0.7.0') {
        transitive = true
    }
implementation 'com.mapbox.mapboxsdk:mapbox-android-plugin-locationlayer:0.2.0'

**Comment by danesfeder** [comment]
This will need to be addressed in conjunction with #447

**Comment by danesfeder** [comment]
This was closed with #1039
