### ISSUE TITLE
Bug LocationLayerPlugin in navigation

### ISSUE THREAD

**Issue by vladgheorghe** [mapbox/mapbox-navigation-android#581]
Greetings, I have noticed a bug related to the location layer plugin while in navigation. For now at least we have determined that this bug is on all Vodafone Smart Prime 6 devices (over one thousand devices). 

At all times: the location layer does not animate fluidly on the map.

While in navigation: the location layer sometimes dissapears (it's still there if you zoom in or out) or gets left behind going off-screen even if the navigation camera animates and moves accordingly to the device's location.

I am posting a video recording of the bug, maybe it will be of more help visually in determining the problem. 

Video found [here](https://youtu.be/KHL7kfOwNac)

![whatsapp image 2017-12-10 at 22 52 15](https://user-images.githubusercontent.com/13194727/33809775-c07aec8e-de04-11e7-8c8c-292cc73afa78.jpeg)

**Comment by danesfeder** [comment]
@vladgheorghe thanks for the feedback - I'm going to move this ticket over to https://github.com/mapbox/mapbox-plugins-android where the `LocationLayerPlugin` is worked:
https://github.com/mapbox/mapbox-plugins-android/issues/215
