### ISSUE TITLE
Android Studio is unable to access viewBinding

### ISSUE THREAD

**Issue by abhishek1508** [mapbox/mapbox-navigation-android#5839]
Lately, I have observed that Android Studio hasn't been able to access `viewBinding` and errors out with the following message:
```
Cannot access 'android.viewbinding.ViewBinding' which is a supertype of 'com.mapbox.navigation.dropin.databinding.MapboxNavigationViewLayoutBinding'. Check your module classpath for missing or conflicting dependencies
```
![Screen Shot 2022-05-19 at 4 35 25 PM](https://user-images.githubusercontent.com/9770186/169421167-80dbb1b3-119f-4917-8654-2aa15babaab8.png)

The fix for this issue is to add this dependency to the any modules with the error message above.

```
implementation 'com.android.databinding:viewbinding:4.0.1'
```

/cc @mapbox/navigation-android

**Comment by KoAn39** [comment]
Hi.

Thank You.

I also encountered this error and the fix worked for me as well.

_(Android Studio Chipmunk | 2021.2.1
Build #AI-212.5712.43.2112.8512546, built on April 28, 2022
Runtime version: 11.0.12+7-b1504.28-7817840 amd64
VM: OpenJDK 64-Bit Server VM by Oracle Corporation
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 1280M
Cores: 4
Registry: external.system.auto.import.disabled=true
Non-Bundled Plugins: org.jetbrains.kotlin (212-1.6.21-release-334-AS5457.46))_

**Comment by Zanozaroom** [comment]
Wow! I spent so many time when tried to find why my binding don't want to work. Only Your answer helped me with my problem.

**Comment by kananbashir** [comment]
This also worked for me, but I am curious, is it proper way to fix this issue? Why it happens?

**Comment by kassiosilva** [comment]
Hey guys, I had the same problem. What worked best for me was going to `files > Sync Project with Gradle files`. Once synchronized, the binding worked correctly.
