### ISSUE TITLE
Route Line for Primary Route is not displayed in Route Preview mode

### ISSUE THREAD

**Issue by abhishek1508** [mapbox/mapbox-navigation-android#5843]
#### Expected behavior
As a user I expect to see Route Line for Main Route in Route Preview mode

#### Actual behavior
Now in app Route Line for Main Route in Route Preview mode, only for Alternative Routes (if it exists)

#### Steps to trigger behavior
1. Create a Route. Make sure that in Route Preview mode main Route Line will be highlighted with a a blue color and Alternative Route Line (if any) in highlighted with a grey color;
2. Arrive to a destination point and tap "X" button on Arrival Feedback window;
3. Create a Route;
4. Make sure that Route Line will not be displayed for Main Route (blue color) in Route Preview mode, only in will be displayed for Alternative Route (grey color).

**Comment by cafesilencio** [comment]
This is a bug in the trim-offset feature, the GL team needs to look at this.

**Comment by cafesilencio** [comment]
The issue for the GL team is here: https://github.com/mapbox/mapbox-gl-native/issues/16644
