### ISSUE TITLE
User should not be re-routed automatically due to lack of GPS updates when known to be on the current route

### ISSUE THREAD

**Issue by ericrwolfe** [mapbox/mapbox-navigation-android#586]
Android version of https://github.com/mapbox/mapbox-navigation-ios/pull/910.

If an off-route is detected, we should check if the user is close to any future step along the route before triggering a reroute request. In some cases like tunnels, parking lots, or certain types of road geometries, the user might actually still be along their intended route (just a few steps ahead), and we shouldn't confuse them by changing the route suddenly.

cc @mapbox/navigation-android

**Comment by akitchen** [comment]
Please research potential performance impact before proceeding with implementation.

A good first pass might be to limit the advance decoding to a fixed number of meters along the route, for example.

**Comment by danesfeder** [comment]
This should be good-to-go with `navigation-native` integration in `0.20.0` 🎉
