### ISSUE TITLE
Prefetch audio instructions

### ISSUE THREAD

**Issue by ericrwolfe** [mapbox/mapbox-navigation-android#587]
Android version of https://github.com/mapbox/mapbox-navigation-ios/pull/724

After each maneuver, we should prefetch the next set of instructions (and potentially more if a set of instructions are close together) to prevent latency from Polly requests or falling back to the default voice if out of cell service.

cc @cammace @danesfeder @bsudekum

**Comment by Guardiola31337** [comment]
I guess OP will be addressed after https://github.com/mapbox/mapbox-navigation-android/pull/751 lands. Could you confirm @devotaaabel?

**Comment by Guardiola31337** [comment]
#751 has landed 🎉

Are we good to close here @devotaaabel?

**Comment by danesfeder** [comment]
Going to close this unless @devotaaabel has any objections
