### ISSUE TITLE
Failed Polly requests should fall back to system audio

### ISSUE THREAD

**Issue by ericrwolfe** [mapbox/mapbox-navigation-android#588]
Related: pre-fetching voice audio https://github.com/mapbox/mapbox-navigation-android/issues/587

Right now, if a driver enters an area without cell connection, navigation will not play any audio until cell connection returns. If this happens many miles later, all of the voice announcements that had been passed will be played all at once. 

We should time out any polly requests taking longer than [5 seconds](https://github.com/mapbox/mapbox-navigation-ios/blob/9047a41dca57f99a08e3452a9a114dcec52f743b/MapboxNavigation/PollyVoiceController.swift#L33), and fall back to the system voice if the audio request fails.

cc @mapbox/navigation-android

**Comment by Guardiola31337** [comment]
I guess OP will be addressed after https://github.com/mapbox/mapbox-navigation-android/pull/751 lands. Could you confirm @devotaaabel?

**Comment by devotaaabel** [comment]
This is addressed in #751.

**Comment by Guardiola31337** [comment]
@devotaaabel Great to hear, thanks for the update.

**Comment by Guardiola31337** [comment]
#751 has landed 🎉

Closing here.
