### ISSUE TITLE
androidauto emulator fails to start

### ISSUE THREAD

**Issue by LukasPaczos** [mapbox/mapbox-navigation-android#5880]
Our `androidauto-test` CI job sometimes hangs on the "Wait for the emulator to start" step, for example, https://app.circleci.com/pipelines/github/mapbox/mapbox-navigation-android/18440/workflows/9f801840-15e2-408c-915f-600532400462/jobs/85880 (waited for ~1.5hr and had to cancel).

cc @kmadsen

**Comment by kmadsen** [comment]
Thanks! This is probably something CircleCi can address

Opened a ticket here, not sure if you can see https://support.circleci.com/hc/en-us/requests/111038

**Comment by LukasPaczos** [comment]
Reopening, now we see - https://app.circleci.com/pipelines/github/mapbox/mapbox-navigation-android/19779/workflows/d5f475f5-fedd-4d95-9481-104c7886a7ad/jobs/97086:
```
com.android.builder.testing.api.DeviceException: No online devices found.
```

**Comment by Guardiola31337** [comment]
+1 https://app.circleci.com/pipelines/github/mapbox/mapbox-navigation-android/19778/workflows/cdd8a109-d9e0-4a74-895a-f0f6d77c38c2/jobs/97085

**Comment by kmadsen** [comment]
Also ran into it again here https://github.com/mapbox/mapbox-navigation-android/pull/6225

https://app.circleci.com/pipelines/github/mapbox/mapbox-navigation-android/20044/workflows/40384e38-56c1-4756-8c2b-401b13b82535/jobs/99204

I've also re-opened the CircleCi issue ticket

**Comment by kmadsen** [comment]
The suggestion from circle ci didn't work https://app.circleci.com/pipelines/github/mapbox/mapbox-navigation-android/20220/workflows/000b045d-83fe-4c50-bc78-449b21f4e52c/jobs/100664

They just suggested this one https://support.circleci.com/hc/en-us/articles/360043994872-How-To-Record-a-Job-s-Memory-Usage
