### ISSUE TITLE
Language setting for maneuver instructions

### ISSUE THREAD

**Issue by PatrickZenker** [mapbox/mapbox-navigation-android#59]
Hey,

is there a way to get instructions in another language? If not, do you plan to include it?

Best regards,
Patrick

**Comment by Grsmto** [comment]
Hi patrick, there is already an issue about that I think: #28 !

**Comment by PatrickZenker** [comment]
You are right, sry :)

**Comment by PatrickZenker** [comment]
No, this is only for App strings. Not directly for maneuver instructions
