### ISSUE TITLE
NavigationCamera is flying across the map on every re-load

### ISSUE THREAD

**Issue by kmadsen** [mapbox/mapbox-navigation-android#5920]
There were not changes to android auto camera here, but the behavior has changed.

This seems like the likely cause https://github.com/mapbox/mapbox-navigation-android/pull/5871

https://user-images.githubusercontent.com/3021882/173161384-1d06fc8d-7152-43ff-aef0-5c468bd5ba97.mov

**Comment by kmadsen** [comment]
Referencing a previous discussion where we identified an API that would not cause the initial transition https://github.com/mapbox/mapbox-navigation-android/issues/4679

**Comment by abhishek1508** [comment]
```
override fun transitionFromLowZoomToHighZoom(
        cameraOptions: CameraOptions,
        transitionOptions: NavigationCameraTransitionOptions
    ): AnimatorSet {
        val pluginImpl: CameraAnimationsPluginImpl? = cameraPlugin as? CameraAnimationsPluginImpl

        return ifNonNull(pluginImpl) {
            flyFromLowZoomToHighZoom(cameraOptions, it, transitionOptions)
        } ?: fromLowZoomToHighZoom(cameraOptions, transitionOptions)
    }
```
This is the cause where it always executed `fly` animation. We need this fly transition whenever the map is panned/zoomed and user wants to return to following mode. We also need this fly transition to following mode when target center and  current center are not the same. However, we don't want the fly transition to happen upon initial map loading. Should we add something like:

```
fun requestNavigationCameraToFollowing(
        stateTransitionOptionsBlock: ((NavigationCameraTransitionOptions.Builder).() -> Unit),
        frameTransitionOptionsBlock: ((NavigationCameraTransitionOptions.Builder).() -> Unit),
        transitionEndListener: TransitionEndListener? = null,
        initialTransition = false
)
```
And the end user can pass true if it's initial transition

cc @LukasPaczos @kmadsen

**Comment by kmadsen** [comment]
https://github.com/mapbox/mapbox-navigation-android/blob/74f1ccf1a172c7b067942fdba3b5ac14df9c8c4d/libnavui-androidauto/src/main/java/com/mapbox/androidauto/car/navigation/CarNavigationCamera.kt#L72-L91

>  And the end user can pass true if it's initial transition. I am also thinking would it be possible for the end user to determine if a particular call to requestToFollowing() is an initial call or subsequent call?

That is what is being done, it seems this "zero duration transition" should not trigger a flyTo
