### ISSUE TITLE
`routeRefreshesWorksAfterSettingsNewRoutes` `RouteRefreshTest` is flaky

### ISSUE THREAD

**Issue by Guardiola31337** [mapbox/mapbox-navigation-android#5931]
`routeRefreshesWorksAfterSettingsNewRoutes` `RouteRefreshTest` started failing lately.

https://console.firebase.google.com/u/0/project/mapbox-navigation-android/testlab/histories/bh.54eb2dd57e959221/matrices/6962616463417849262/executions/bs.b502afcf97feafee/testcases/11

Refs. https://github.com/mapbox/mapbox-navigation-android/pull/5912#issuecomment-1156631648 https://github.com/mapbox/mapbox-navigation-android/pull/5925#issuecomment-1156627810 https://github.com/mapbox/mapbox-navigation-android/pull/5927#issuecomment-1156889425

cc'ing @VysotskiVadim @RingerJK for visibility

**Comment by truburt** [comment]
As a quick workaround, we can first do https://github.com/mapbox/mapbox-navigation-android/issues/5975 .

**Comment by Guardiola31337** [comment]
Noting that this is still happening after bumping NN `108.0.1` https://github.com/mapbox/mapbox-navigation-android/pull/6034

https://console.firebase.google.com/u/0/project/mapbox-navigation-android/testlab/histories/bh.54eb2dd57e959221/matrices/6419413382454071959/executions/bs.d245768dd5d522f4/testcases/10
