### ISSUE TITLE
Use the same `HistoryRecorderHandle` instance everywhere

### ISSUE THREAD

**Issue by Guardiola31337** [mapbox/mapbox-navigation-android#5932]
While testing we noticed that `getRoutes` events from NN (hybrid router should generate those now) are not included as part of the history files. This is because the history recorder for the navigator is a different instance from the one we pass to the router, we create each separately https://github.com/mapbox/mapbox-navigation-android/blob/550f18f1bfc8516f703b2d1fc332e28af2c46983/libnavigator/src/main/java/com/mapbox/navigation/navigator/internal/NavigatorLoader.kt#L42-L49 https://github.com/mapbox/mapbox-navigation-android/blob/550f18f1bfc8516f703b2d1fc332e28af2c46983/libnavigator/src/main/java/com/mapbox/navigation/navigator/internal/NavigatorLoader.kt#L75-L82 

We should make sure that the same history recorder instance is used everywhere.

cc'ing @mskurydin @mapbox/navigation-ios for visibility

**Comment by 1ec5** [comment]
On iOS, this is now being tracked as part of an overhaul of the history recording interface: https://github.com/mapbox/navigation-sdks/issues/1797#issuecomment-1156546250.
