### ISSUE TITLE
Handle errors produced by Native Navigator in setRoutes method

### ISSUE THREAD

**Issue by dzinad** [mapbox/mapbox-navigation-android#5945]
Now when `MapboxNavigation#setRoutes` method is called the routes are first passed to Native Navigator and then to all the `RouteObserver`s.
https://github.com/mapbox/mapbox-navigation-android/issues/5686#issuecomment-1161695132
However, Native Navigator can fail routes handing with an error and that error will be ignored and callbacks will be called with invalid routes. The only way to know that something went wrong is now to read the logs.
At least we should stop dispatching invalid routes to callbacks. We should also look if there's something else ww shouldn't do with invalid routes.

**Comment by VysotskiVadim** [comment]
PR https://github.com/mapbox/mapbox-navigation-android/pull/5946
