### ISSUE TITLE
Android Drop-In UI : Support transparent system bars in Drop-In UI

### ISSUE THREAD

**Issue by Zayankovsky** [mapbox/mapbox-navigation-android#5952]
#### Actual implementation of Drop-In UI in full screen

|<img src="https://user-images.githubusercontent.com/2395284/175084343-58da222f-85c5-463d-a361-269878ff3598.png" width="250" />|<img src="https://user-images.githubusercontent.com/2395284/175084362-ede037b6-0441-4263-b932-881a32975c46.png" width="250" />|

Note that speed limit view, action buttons, maneuver view, road name view, info panel content and Mapbox logo are partially obscured by system bars. In order to avoid these overlaps the views should observe window insets and update their margins accordingly, so that the UI looks like this:

#### Expected implementation
|<img src="https://user-images.githubusercontent.com/2395284/175086376-5669577c-a153-40f6-b308-b933516ce0f2.png" width="250" />|<img src="https://user-images.githubusercontent.com/2395284/175086393-afdc923a-73f9-4a0a-a7f4-a080a5fdac65.png" width="250" />|

This documentation describes how to implement this behavior: https://developer.android.com/training/gestures/edge-to-edge. 

Even though some users might want to support full screen and would want Drop-In UI to support this behavior, not all users would have this requirement. So, the implementation should be such that Drop-In UI adjusts itself if there is a need to have opaque status and navigation bars.

**Comment by Zayankovsky** [comment]
@tomaszrybakiewicz don't forget about landscape mode, with it the navigation bar may be located on the left or right side of the screen.

**Comment by tomaszrybakiewicz** [comment]
@Zayankovsky Good call. Completely forgot about landscape.
