### ISSUE TITLE
Android Drop-In UI : NavigationView APIs improvements

### ISSUE THREAD

**Issue by Zayankovsky** [mapbox/mapbox-navigation-android#5953]
1. `NavigationViewListener` functions have typos, e.g. `onDestinationPreviewStared`. 
2. `NavigationViewApi.setDestination` doesn't  properly enable Destination Preview state. You have to additionally call `SharedApp.store.dispatch(NavigationStateAction.Update(NavigationState.DestinationPreview))`, which is located in the `internal` package. `setRoutes` functions likely have the same issue. 
3. Need a way to properly cancel active guidance and return to free drive state. At the moment it has to be implemented this way:
```kotlin

SharedApp.store.dispatch(RoutesAction.SetRoutes(emptyList()))
SharedApp.store.dispatch(DestinationAction.SetDestination(null))
SharedApp.store.dispatch(NavigationStateAction.Update(NavigationState.FreeDrive))
```

**Comment by abhishek1508** [comment]
Closing in favor of https://github.com/mapbox/navigation-sdks/issues/1911
