### ISSUE TITLE
Allow info panel content injection in Drop-In UI during Free Drive state

### ISSUE THREAD

**Issue by Zayankovsky** [mapbox/mapbox-navigation-android#5955]
This can be used to inject Search UI or Feedback UI. The bottom sheet should support states like expanded, collapsed and hidden. Drop-In UI should offset road name view and update camera paddings depending on the injected content dimensions.

**Comment by Zayankovsky** [comment]
@abhishek1508 is this the same as #5980?

**Comment by abhishek1508** [comment]
Yep closing this.
