### ISSUE TITLE
when i getting route information using 

### ISSUE THREAD

**Issue by nileshinfograins** [mapbox/mapbox-navigation-android#596]
When geting route information using :- 
NavigationRoute.builder().accessToken(Mapbox.getAccessToken()).origin(origin).destination(destination).build().getRoute(new Callback<DirectionsResponse>() {
            @Override
            public void onResponse(@NonNull Call<DirectionsResponse> call, @NonNull Response<DirectionsResponse> response) {
                Log.e(TAG, "Response code ======> " + response.code());
                Log.e(TAG, "Response toString ======> " + response.toString());
                if (response.body() == null) {
                    Log.e(TAG, "No routes found, make sure you set the right user and access token.");
                    return;
                } else if (response.body().routes().size() < 1) {
                    Log.e(TAG, "No routes found");
                    return;
                }
                currentRoute = response.body().routes().get(0);
                // Draw the route on the map
                if (navigationMapRoute != null) {
                    navigationMapRoute.removeRoute();
                } else {
                    MapboxNavigation navigation = new MapboxNavigation(mContext, MapboxConstants.MAP_TOKEN);
                    navigationMapRoute = new NavigationMapRoute(navigation, mapView, mapboxMap);
                }

                navigationMapRoute.addRoute(currentRoute);
                button.setEnabled(true);
                button.setBackgroundColor(getResources().getColor(R.color.blue));
            }

            @Override
            public void onFailure(@NonNull Call<DirectionsResponse> call, @NonNull Throwable throwable) {
                Log.e(TAG, "Error: " + throwable.getMessage());
            }
        });

response.toString(); is giving me response :- Response{protocol=http/1.1, code=200, message=OK, url=http://localhost/}
and i'm not able to get route details and not able to start navigation with out any route and instructions.

**Comment by danesfeder** [comment]
@nileshinfograins thanks for the feedback - are you able to determine at which point the code above fails?

**Comment by danesfeder** [comment]
Hey @nileshinfograins I'm not able to determine your issue with the details provided.  Feel free to open this ticket again if you're able to provide some more information surrounding your issue.
