### ISSUE TITLE
Route line trail layer trim offsets are reset erroneously.

### ISSUE THREAD

**Issue by cafesilencio** [mapbox/mapbox-navigation-android#5981]
When rendering routes the `MapboxRouteLineView` class is resetting the trim-offest for the trail layers.  This shouldn't happen.  

### Steps to trigger behavior

 1. Set the `routeLineTraveledColor` and `routeLineTraveledCasingColor` colors in the `RouteLineColorResources` builder. 
 2. During navigation make one or more calls to set the routes in the `MapboxRouteLineApi` class and render the result
 3. Notice that the line behind the puck disappears at the puck's location at the point where the set routes call was made.

### Expected behavior
The trail layers should be intact.

### Actual behavior
The trail layers are disappearing.

https://user-images.githubusercontent.com/2249818/176579402-f85b4f69-9391-4cad-b69c-83986bcc6496.mp4

**Comment by Guardiola31337** [comment]
Closing here as https://github.com/mapbox/mapbox-navigation-android/pull/5982 landed 🚀
