### ISSUE TITLE
Refactor InstructionView 

### ISSUE THREAD

**Issue by danesfeder** [mapbox/mapbox-navigation-android#599]
With the addition of the "then step", secondary text, and directions list, the [InstructionView](https://github.com/mapbox/mapbox-navigation-android/blob/master/libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/instruction/InstructionView.java) grew, turning into a "god class".  The view should be refactored with unit / instrumentation tests added.

cc @ericrwolfe

**Comment by akitchen** [comment]
Closed pending a new refactor plan for the InstructionView and related view classes, partially in pursuit of addressing https://github.com/mapbox/mapbox-navigation-android/issues/1672
