### ISSUE TITLE
Jittery location puck animation

### ISSUE THREAD

**Issue by ericrwolfe** [mapbox/mapbox-navigation-android#600]
The animation of the location puck along the route line can be jittery on certain devices, especially those with older hardware.

![2017-12-15 09_54_59](https://user-images.githubusercontent.com/664805/34054055-1b0fd3ae-e17e-11e7-9ff4-a9b04e535748.gif)

@danesfeder is going to do some CPU profiling and dig in more, but we suspect this could be related to the runtime-styling based location puck not being performant with the Maps SDK.

@tobrun @zugaldia any thoughts on how best to debug this? 

cc @willwhite

**Comment by tobrun** [comment]
I wouldn't spend too much time profiling this. We need to change the way navigation mode works in location layer. We need to take the same approach as iOS, when navigating we need to replace the runtime-style setup with a fixed ImageView at the bottom. Besides a better user experience but this also improves battery consumption as we don't waste cpu cycles animating something in place. This issue has been ticketed in https://github.com/mapbox/mapbox-plugins-android/issues/179 and I would love to see this landing with the upcoming 0.3.0 release https://github.com/mapbox/mapbox-plugins-android/issues/149

cc @cammace

**Comment by devotaaabel** [comment]
See https://github.com/mapbox/mapbox-plugins-android/issues/215
