### ISSUE TITLE
Android Drop-In UI: reset SharedApp state when MapboxNavigation is destroyed

### ISSUE THREAD

**Issue by Zayankovsky** [mapbox/mapbox-navigation-android#6000]
`SharedApp` is a singleton, which can outlive `MapboxNavigation`. So when `MapboxNavigation` is created again it will be in Free Drive state, but `SharedApp` may be in Active Navigation state, since that was the state when `MapboxNavigation` was destroyed. That causes views to display empty data. 
The issue can be easily reproduced by enabling Don't keep activities setting in Developer options on your phone, starting navigation and then putting the app into background. This destroys all of the app's activities, which causes `MapboxNavigation` to be destroyed as well, but the process still lives. When you return to the app activity will be recreated along with a fresh instance of `MapboxNavigation`, but `SharedApp` will preserve its state.

**Comment by Guardiola31337** [comment]
https://user-images.githubusercontent.com/1668582/176965950-7c78b016-f1d6-4d6b-83ad-e67d1b905ae4.mp4
