### ISSUE TITLE
Android Drop-In UI: Customer should be able to modify RouteOptions 

### ISSUE THREAD

**Issue by korshaknn** [mapbox/mapbox-navigation-android#6017]
At the moment there is no way to modify `RouteOptions` used to fetch routes, but customer should be able to do it.
some customisation examples:
- driving profile
- exclude list
- include list
- language (different from locale)
- account (user)

**Comment by abhishek1508** [comment]
We already expose an API `navigationView.api.setRoutes(options: RouteOptions)`. This allows end users to inform the Drop-In UI to fetch the route using the `options` supplied and set it to `mapboxNavigation`. I guess I am not clear on the exact user flow. Can you describe a step-by-step user flow that makes the requirement more clear?

@korshaknn

**Comment by korshaknn** [comment]
@abhishek1508 btw, at the moment we have the next logic
- long tap `once` -> fetch a route to the destination -> coordinates = (origin, destination)
- long tap `twice` -> take previous destination ^^ and use it as a waypoint to a new route. coordinates = (origin, destination_step_1, destination)
- and so on

check the video (there is a bug, we don't move the destination pin to the last waypoint)

https://user-images.githubusercontent.com/14282440/177952549-ae1127f8-1099-40cb-b295-d426ff9efbce.mp4
