### ISSUE TITLE
Zoom default level back by one

### ISSUE THREAD

**Issue by ericrwolfe** [mapbox/mapbox-navigation-android#602]
As a first step in implementing https://github.com/mapbox/mapbox-navigation-android/issues/601, we should be able to easily set custom zoom levels in navigation.

As a quick win, we should zoom the default camera out by one zoom level for parity with the default camera on iOS. 

cc @mapbox/navigation-android

**Comment by vladgheorghe** [comment]
How about an option for the camera to toggle automatic zooming depending on the speed at which the device is navigating ?
