### ISSUE TITLE
Do not initiate billable active guidance session if primary route failed to be set

### ISSUE THREAD

**Issue by LukasPaczos** [mapbox/mapbox-navigation-android#6023]
Tracks synchronizing the `NavigationSession` state with actual state of `RoutesObserver`. More information in https://github.com/mapbox/mapbox-navigation-android/pull/5946/files#r915785454 and https://github.com/mapbox/mapbox-navigation-android/pull/5938#discussion_r915770292.

cc @dzinad @RingerJK @VysotskiVadim

**Comment by dzinad** [comment]
I wonder if we can move `navigationSession.setRoutes` to be called after `tripSession.setRoutes`.
Technically is changes the state and notifies the `NavigationSessionStateObserver`s. As I understand it, we don't say anywhere if the routes will already be set when we invoke `NavigationSessionStateObserver` callback methods. So it should be safe to move. WDYT?

**Comment by LukasPaczos** [comment]
Fixed in https://github.com/mapbox/mapbox-navigation-android/pull/6074.
