### ISSUE TITLE
`RouteLineLayersTest` `instrumentation-tests` failing `WorkerThreadException`

### ISSUE THREAD

**Issue by Guardiola31337** [mapbox/mapbox-navigation-android#6035]
As mentioned in https://github.com/mapbox/mapbox-navigation-android/pull/6034#issuecomment-1179328007 `RouteLineLayersTest`s are failing due to:

```
com.mapbox.maps.exception.WorkerThreadException: The exception that is thrown when an application attempts to
perform a map operation on a worker thread.
at com.mapbox.maps.ThreadChecker.throwIfNotMainThread(ThreadChecker.kt:88)
at com.mapbox.maps.MapboxMap.checkNativeMap(MapboxMap.kt:1771)
at com.mapbox.maps.MapboxMap.checkNativeMap$default(MapboxMap.kt:1769)
at com.mapbox.maps.MapboxMap.getStyle(MapboxMap.kt:373)
at com.mapbox.navigation.instrumentation_tests.ui.routeline.RouteLineLayersTest.updateLayerElevationTest(RouteLineLayersTest.kt:176)
```

https://console.firebase.google.com/u/0/project/mapbox-navigation-android/testlab

cc @cafesilencio

**Comment by cafesilencio** [comment]
> at com.mapbox.maps.MapboxMap.getStyle(MapboxMap.kt:373)

The call to getStyle is not performed on any specific thread in this test.  It's called in the main test body.

**Comment by dzinad** [comment]
> The call to getStyle is not performed on any specific thread in this test. It's called in the main test body.

Maybe we should just use `sdkTest` for all tests that interact with API that's supposed to be called from the main thread (it's practically all the API as far as I can see)?

**Comment by cafesilencio** [comment]
This file hasn't changed since mid-june. If it suddenly started failing something about our environment changed. Never the less I added an annotation to run the tests on the UI thread and created a PR.

**Comment by cafesilencio** [comment]
Closing via #6054
