### ISSUE TITLE
User should see an upcoming maneuver arrow on the route line

### ISSUE THREAD

**Issue by ericrwolfe** [mapbox/mapbox-navigation-android#604]
Similar to the one on iOS:
![img_0420](https://user-images.githubusercontent.com/664805/34054954-f6f201be-e181-11e7-8329-14194e2939a6.jpg)

iOS creates a line segment 30m before and after the maneuver point, and then [adds this arrow shaft as a runtime styling layer](https://github.com/mapbox/mapbox-navigation-ios/blob/9a2517e832dc2a64f38e46d73357306214ea5288/MapboxNavigation/NavigationMapView.swift#L624-L778). 

The arrowhead is [a white triangle](https://github.com/mapbox/mapbox-navigation-ios/blob/master/MapboxNavigation/Resources/Assets.xcassets/triangle.imageset/triangle.pdf) that is add as a symbol layer and rotated based on the bearing of the maneuver.

cc @mapbox/navigation-android @frederoni @bsudekum

**Comment by Guardiola31337** [comment]
> iOS OP implementation 👀 https://github.com/mapbox/mapbox-navigation-ios/blob/master/MapboxNavigation/NavigationMapView.swift#L586

Revisit when Boba expressions get released (👀 https://github.com/mapbox/mapbox-navigation-ios/pull/1076)

**Comment by Guardiola31337** [comment]
Capturing @1ec5 comment
> We only draw it on the upcoming step, but yeah. The arrow consists of a shaft (line feature + line layer) and an arrowhead (point feature + symbol layer), plus a shaft casing (line feature + line layer) and arrowhead casing (point feature + symbol layer). The geometry code there ensures the arrow hugs the intersection.
The casing layer is slightly thinner than the route line, yes.

**Comment by akitchen** [comment]
Note the relationship to https://github.com/mapbox/mapbox-navigation-android/issues/704 -- further refactoring is probably needed in order to address these two tickets.

**Comment by Guardiola31337** [comment]
Capturing @frederoni's comments
> the shaft is sliced 30 meters before and 30 meters after the `RouteStep`’s `maneuverCoordinate` using turf’s `trimmed()` function https://github.com/mapbox/turf-swift/blob/master/Sources/Turf/Turf.swift#L210

> the direction is calculated from the second last to the very last coordinate in the shaft using turf’s `direction(to:)` https://github.com/mapbox/turf-swift/blob/master/Sources/Turf/Turf.swift#L36

> symbol.coordinate = shaft.coordinates.last

> the arrow is a static image, anchored horizontally and vertically center on the shaft.coordinates.last

**Comment by Guardiola31337** [comment]
Equivalent Android Turf methods:

- `trimmed()` 👉 `turf-line-slice-along` (Still not ported to Java 👀 https://github.com/mapbox/mapbox-java/blob/master/docs/turf-port.md) cc @osana 
- `direction(to:)` 👉 [`TurfMeasurement#bearing(Point, Point)`](https://github.com/mapbox/mapbox-java/blob/master/services-turf/src/main/java/com/mapbox/turf/TurfMeasurement.java#L31-L53)

For reference, here’s the magic decoder ring 👉 https://github.com/mapbox/turf-swift#available-functionality (thanks @1ec5 🙏)
