### ISSUE TITLE
Setting a custom location puck should be easier

### ISSUE THREAD

**Issue by ericrwolfe** [mapbox/mapbox-navigation-android#605]
Currently, it requires a custom init of LocationLayerPlugin with new style.

cc @cammace @danesfeder

**Comment by danesfeder** [comment]
@ericrwolfe is this specific to the drop-in UI?

**Comment by ericrwolfe** [comment]
The NavigationView. 

The LocationLayerPlugin init method (where you'd normally define the style), is hidden within this init function, so to customize, I think you'd need to subclass + override this function in NavigationView:
https://github.com/mapbox/mapbox-navigation-android/blob/7ea236b29cdba3591212af305975a3972d1fcf37/libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/NavigationView.java#L387-L391

Would be nice if developers could customize the puck without needing to do this, for example if the NavigationView could look for a custom puck image in the navigation theme.

**Comment by danesfeder** [comment]
Yeah setting it in the `NavigationView` theme then initializing the plugin with the provided theme would be pretty straightforward.  We already do the same deal for the `NavgationMapRoute`:

https://github.com/mapbox/mapbox-navigation-android/blob/master/libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/NavigationView.java#L371
