### ISSUE TITLE
RoutesObserver docs and behaviour are inconsistent

### ISSUE THREAD

**Issue by dzinad** [mapbox/mapbox-navigation-android#6066]
There are two possible issues:
1. [The docs say](https://github.com/mapbox/mapbox-navigation-android/blob/f1be7dbc4cbc0f3339c3c0cca1d2bbb9da1b2398/libnavigation-core/src/main/java/com/mapbox/navigation/core/directions/session/RoutesObserver.kt#L13-L21) that the `onRoutesChanged` will be invoked when the routes change. In reality this observer is sticky: it [will be triggered with current routes](https://github.com/mapbox/mapbox-navigation-android/blob/f1be7dbc4cbc0f3339c3c0cca1d2bbb9da1b2398/libnavigation-core/src/main/java/com/mapbox/navigation/core/directions/session/MapboxDirectionsSession.kt#L125).
2. The observer will not be triggered with current routes if there are no routes. Meaning we don't distinguish the initial state from the state when the routes were intentionally cleared.

The question is: who's wrong and is it OK to treat empty routes differently? It may cause not-so-obvious issues when using flows, like [here](https://github.com/mapbox/mapbox-navigation-android/pull/6052) for example.

cc @mapbox/navigation-android

**Comment by RingerJK** [comment]
I think the very first state doesn't have to be set (like empty routes), then if routes were set to empty outside (for instance by the application) it should be spread

```kotlin
/**
     * Registers [RoutesObserver]. Updated on each change of [routes]
     */
    override fun registerRoutesObserver(routesObserver: RoutesObserver) {
        routesObservers.add(routesObserver)
        if (routes.isNotEmpty()) {
            routesObserver.onRoutesChanged(RoutesUpdatedResult(routes, routesUpdateReason))
        }
    }
```

should be replaced smth like

```kotlin
private var routesHasBeenInited = false // also `routesHasBeenInited+routes` can be replaced by Delegate 

 override var routes: List<NavigationRoute> = emptyList()
        private set {
          ...
          routesHasBeenInited = true
        }

/**
     * Registers [RoutesObserver]. Updated on each change of [routes]
     */
    override fun registerRoutesObserver(routesObserver: RoutesObserver) {
        routesObservers.add(routesObserver)
        if (routesHasBeenInited) {
            routesObserver.onRoutesChanged(RoutesUpdatedResult(routes, routesUpdateReason))
        }
    }
```
```

**Comment by LukasPaczos** [comment]
The first one is expected, that's how we design most of our observer (following a reactive pattern familiar from things like `LiveData`), docs could be improved though. The second one can certainly be adjusted but at the same time we'd have to go through the rest of stateful observers and see which would need the same behavioral improvement. Most of them are backed by `null`s so they automatically behave this way, we could try something similar for the routes backing field as well.

**Comment by dzinad** [comment]
PR about docs: https://github.com/mapbox/mapbox-navigation-android/pull/6092

**Comment by dzinad** [comment]
Other sticky observers: `RerouteStateObserver`, `BannerInstructionsObserver`, `LocationObserver`, `NavigationSessionStateObserver `, `OffRouteObserver`, `RoadObjectsOnRouteObserver`, `RouteProgressObserver`, `TripSessionStateObserver`, `EHorizonObserver`.

**Comment by dzinad** [comment]
PR about `RoutesObserver`: #6097.

**Comment by LukasPaczos** [comment]
Thanks for the analysis @dzinad!
