### ISSUE TITLE
Reroute drops waypoints in new route

### ISSUE THREAD

**Issue by konskons5** [mapbox/mapbox-navigation-android#609]
I want to navigate along a route with 2 additional waypoints. All goes well until a reroute event occurs. Unfortunately the newly generated route does not contain these waypoints anymore. The new route leads straight to the destination ignoring the waypoints.

Bug occurs using: 

```
compile('com.mapbox.mapboxsdk:mapbox-android-sdk:5.2.1@aar') {
 transitive=true 
}
compile 'com.mapbox.mapboxsdk:mapbox-android-navigation:0.8.0-beta.1'
compile ('com.mapbox.mapboxsdk:mapbox-android-navigation-ui:0.8.0-beta.1') {
 transitive = true
}
```

```
NavigationViewOptions options = NavigationViewOptions.builder()
                .shouldSimulateRoute(shouldSimulateRoute)
                .directionsRoute(route)
                .directionsProfile(DirectionsCriteria.PROFILE_DRIVING)
                .build();

        if (route != null) {
            NavigationLauncher.startNavigation(this, options);
        }
```

**Comment by danesfeder** [comment]
@konskons5 thanks for the feedback.  At this time, the "turn-by-turn-UI" that is shown when using `NavigationLauncher` does not support multiple waypoints, only an origin / destination.  Stay tuned, as waypoint support is something we are looking to integrate.

**Comment by konskons5** [comment]
@danesfeder thanks for the info. Waypoint support is crucial for my app. Can you give me an idea, when it will be supported? I hope, I do not need to change to a different navigation-ui provider as I really like your work.

**Comment by danesfeder** [comment]
@konskons5 We don't have a specific timeline for this in regards to the UI, but I will update this ticket as soon as the work comes into the pipeline.  It's a matter cacheing the waypoints (and removing them as you arrive at each) along the `DirectionsRoute` as was outlined in https://github.com/mapbox/mapbox-navigation-android/pull/630

**Comment by Danny-James** [comment]
@danesfeder do we have the ability to turn off rerouting with the new NavigationOptions? as this can be a work around for the timebeing?

**Comment by Danny-James** [comment]
@danesfeder any chance of an update on turning off re-routing within `NavigationOptions`?

**Comment by Danny-James** [comment]
@danesfeder good job!! .. will the ability to turn off re routing be in the v10.0 release? the Boolean navigation option you spoke about.

**Comment by danesfeder** [comment]
@Danny-James Are you using `NavigationView` implementation or `NavigationLauncher`?  I think we talked before and you converted to the `View`?  If so, you can pass `MapboxNavigationOptions` with `enableOffRouteDetection(false)` to `NavigationViewOptions#navigationOptions` before you call `NavigationView#startNavigation`

**Comment by Danny-James** [comment]
@danesfender I didn't end up converting to the view as I need to get this version of the app out I'm well over due, so once this is out and working I plan on moving to the `NavigationView` as i'll have more time to understand how to implement this.

**Comment by palimad** [comment]
How to control rerouting and off-route functionality (e.g. snapping to roads) with current APIs?
