### ISSUE TITLE
Map crashing when closing background app

### ISSUE THREAD

**Issue by rheng001** [mapbox/mapbox-navigation-android#615]
Hi, I seem to be getting this error every time I load the map and then close the app via closing background apps in my phone. When I would go back to reopen the app I would get a white screen that just hangs there for a few seconds and then crashes and closes the app. Afterwards however when I reopen the app it loads back as normal.  I have implemented the mapbox map via a **fragment**. My guess is that after loading the map when closing the app via background apps it does not shutdown the mapbox service properly. Here's a short 50 sec clip demo

![bug_gif](https://user-images.githubusercontent.com/14899915/34239267-07857988-e5bb-11e7-9357-b10bba259d7a.gif)

> 12-18 21:10:31.853 1605-2530/? E/WifiScanningService: Got invalid work source request: WorkSource{} from ClientInfo[uid=10020]
12-18 21:10:33.144 879-1131/? E/qti_sensorhub_hal: slocationCore::sendUserData enabled(1)
12-18 21:10:36.531 1605-1907/? E/ActivityManager: ANR in ucr.ucrmap
                                                  PID: 23023
                                                  Reason: executing service ucr.ucrmap/com.mapbox.services.android.telemetry.service.TelemetryService
                                                  Load: 10.3 / 11.18 / 10.84
                                                  CPU usage from 64789ms to 0ms ago (2017-12-18 21:09:27.081 to 2017-12-18 21:10:31.869):
                                                    21% 1605/system_server: 10% user + 10% kernel / faults: 21392 minor 702 major
                                                    12% 714/surfaceflinger: 5.1% user + 7.6% kernel / faults: 436 minor 5 major
                                                    10% 21214/com.google.android.youtube: 6.4% user + 3.9% kernel / faults: 1427 minor 93 major
                                                    5.4% 862/adbd: 1.1% user + 4.3% kernel / faults: 1627 minor
                                                    2.6% 597/logd: 0.8% user + 1.8% kernel / faults: 704 minor 57 major
                                                    1.7% 365/cfinteractive: 0% user + 1.7% kernel
                                                    1.6% 2669/com.android.systemui: 1% user + 0.6% kernel / faults: 3618 minor 20 major
                                                    1.5% 22166/kworker/u8:3: 0% user + 1.5% kernel
                                                    1.4% 12840/kworker/u8:14: 0% user + 1.4% kernel
                                                    1.4% 16001/logcat: 0.7% user + 0.6% kernel / faults: 23 minor
                                                    1.2% 32327/wpa_supplicant: 0% user + 1.2% kernel / faults: 53 minor
                                                    1.1% 133/kswapd0: 0% user + 1.1% kernel
                                                    1.1% 18907/kworker/u8:0: 0% user + 1.1% kernel
                                                    1% 7360/com.cleanmaster.security:DefendService: 0.2% user + 0.8% kernel / faults: 649 minor 60 major
                                                    1% 2616/com.android.phone: 0.3% user + 0.6% kernel / faults: 538 minor 5 major
                                                    0.7% 11118/com.facebook.orca: 0.2% user + 0.5% kernel / faults: 6042 minor 3844 major
                                                    0.8% 32008/kworker/u8:5: 0% user + 0.8% kernel
                                                    0.8% 7/rcu_preempt: 0% user + 0.8% kernel
                                                    0.8% 22272/mdss_fb0: 0% user + 0.8% kernel
                                                    0.7% 4124/com.google.android.gms.persistent: 0.3% user + 0.3% kernel / faults: 6164 minor 603 major
                                                    0.6% 3/ksoftirqd/0: 0% user + 0.6% kernel
                                                    0.6% 425/msm-core:sampli: 0% user + 0.6% kernel
                                                    0.5% 16045/perfd: 0.1% user + 0.3% kernel / faults: 28 minor
                                                    0.4% 12/ksoftirqd/1: 0% user + 0.4% kernel
                                                    0.4% 20731/kworker/0:0: 0% user + 0.4% kernel
                                                    0.3% 4708/com.sec.android.app.launcher: 0.2% user + 0.1% kernel / faults: 6105 minor 35 major
                                                    0.4% 21462/kworker/0:1: 0% user + 0.4% kernel
                                                    0.3% 9590/com.devexpert.weather: 0.2% user + 0.1% kernel / faults: 2143 minor 8 major
                                                    0.3% 41/smem_native_rpm: 0% user + 0.3% kernel
                                                    0.3% 29874/com.samsung.oh: 0.1% user + 0.1% kernel / faults: 1419 minor 20 major
                                                    0.3% 17364/com.tmobile.pr.mytmobile: 0% user + 0.2% kernel / faults: 4191 minor 3802 major
                                                    0.3% 712/servicemanager: 0% user + 0.2% kernel / faults: 9 minor
                                                    0.2% 3606/com.sec.android.emergencymode.service: 0.1% user + 0.1% kernel / faults: 155 minor 6 major
                                                    0.2% 22489/kworker/0:4: 0% user + 0.2% kernel
                                                    0.2% 2923/com.sec.imsservice: 0.1% user + 0.1% kernel / faults: 359 minor 4 major
                                                    0.2% 6743/kworker/1:3: 0% user + 0.2% kernel
                                                    0.2% 16/ksoftirqd/2: 0% user + 0.2% kernel
                                                    0.1% 1//init: 0.1% user + 0% kernel / faults: 39 minor
                                                    0.1% 897/zygote64: 0% user + 0.1% kernel / faults: 851 minor
                                                    0.1% 21556/net.zedge.android:remote: 0% user + 0.1% kernel / faults: 1079 minor 76 major
                                                    0.1% 20/ksoftirqd/3: 0% user + 0.1% kernel
                                                    0.1% 18153/com.reddit.frontpage: 0% user + 0% kernel / faults: 2029 minor 262 major
                                                    0.1% 1069/qmuxd: 0% user + 0.1% kernel / faults: 84 minor
                                                    0.1% 90/system: 0% user + 0.1% kernel
                                                    0.1% 14507/kworker/1:5: 0% user + 0.1% kernel
                                                    0.1% 908/rild: 0% user + 0.1% kernel / faults: 86 minor
                                                    0.1% 3125/com.sec.epdg: 0% user + 0% kernel / faults: 439 minor 3 major
                                                    0.1% 3823/irq/18-408000.q: 0% user + 0.1% kernel
                                                    0% 13333/com.samsung.android.spay: 0% user + 0% kernel / faults: 699 minor 18 major
                                                    0.1% 21304/com.amazon.mShop.android: 0% user + 0% kernel / faults: 129 minor 2 major
                                                    0% 3804/iod: 0% user + 0% kernel / faults: 7 minor
                                                    0% 5324/com.google.android.gms: 0% user + 0% kernel / faults: 608 minor 6 major
                                                    0% 6901/com.sec.spp.push: 0% user + 0% kernel / faults: 81 minor 2 major
                                                    0% 8/rcu_sched: 0% user + 0% kernel
                                                    0% 711/lmkd: 0% user + 0% kernel / faults: 1 minor
                                                    0% 1009/netd: 0% user + 0% kernel / faults: 447 minor 3 major
                                                    0% 2629/com.android.bluetooth: 0% user + 0% kernel / faults: 251 minor 9 major
                                                    0% 4431/com.android.nfc: 0% user + 0% kernel / faults: 61

**Comment by danesfeder** [comment]
Thanks for bringing this to us @rheng001, we will look into it.  @Guardiola31337 @electrostat have either of you run into something like this with the telemetry library?

**Comment by danesfeder** [comment]
@rheng001 Also, which version of the navigation SDK are you using?

**Comment by rheng001** [comment]
@danesfeder 

This is what I'm currently using. However the problem still arises even if I'm using the **0.7.1** versions.

`compile('com.mapbox.mapboxsdk:mapbox-android-sdk:5.2.1@aar') { transitive = true }`
`compile 'com.mapbox.mapboxsdk:mapbox-android-navigation:0.8.0-beta.1'`
`compile ('com.mapbox.mapboxsdk:mapbox-android-navigation-ui:0.8.0-beta.1') {
        transitive = true
    }`

**Comment by Jose4gg** [comment]
@rheng001 Do you have any updates on this?

**Comment by rheng001** [comment]
@Jose4gg No same problem. Are you facing the same problem?

**Comment by Jose4gg** [comment]
Yes, I'm using react-native-mapbox-gl which wrap this library, but same, same issue.

**Comment by danesfeder** [comment]
@rheng001 Are you using our react library as well?  Having trouble deciphering that stack trace other than the fact it's being caused by `TelemetryService`.  Also, are you using our `navigation-ui` library at all?  It seems this is an issue in our Maps SDK (not related to navigation).

**Comment by danesfeder** [comment]
Can you try https://github.com/mapbox/mapbox-gl-native/issues/10809#issuecomment-354536693 and see if that helps?

**Comment by rheng001** [comment]
@danesfeder That fixed it! Such a simple mistake but it makes sense now. Thanks.
