### ISSUE TITLE
Use mutex to simplify CurrentIndicesSnapshotProvider

### ISSUE THREAD

**Issue by dzinad** [mapbox/mapbox-navigation-android#6182]
Follow up from https://github.com/mapbox/mapbox-navigation-android/pull/6115#discussion_r945553296.
The main idea is to use `mutex.withLock` instead of freeze + unfreeze and use the same mutex in `onRoutesProgressUpdate` inside `CurrentIndicesSnapshotProvider` to forbid updates while the state is in use.

**Comment by RingerJK** [comment]
@dzinad this issue is in review. Should be `not started`?

**Comment by dzinad** [comment]
Why? There's a PR open. :)
