### ISSUE TITLE
Puck zooming issue while ending the navigation

### ISSUE THREAD

**Issue by Sridhar261990** [mapbox/mapbox-navigation-android#6197]
I am using Drop-In UI to write my navigation application. If I just start navigation from my current location and cancel it immediately then the puck behaves weird. It goes all the way to the destination and comes back to my current location within seconds. 

**I am using implementation 'com.mapbox.navigation:ui-app:2.7.0-rc.1'
    implementation 'com.mapbox.navigation:ui-dropin:2.7.0-rc.1'**

### Steps to trigger behavior

 1. Select the destination which is 20km away from current position
 2. Either start the navigation by using replay session or realtime navigation
 3. End the navigation by tapping the x button.

**Comment by abhishek1508** [comment]
@Sridhar261990 Can you confirm if this is still reproducible?

**Comment by Sridhar261990** [comment]
@abhishek1508 Since we are closing the screen when we end the navigation. This is not required. So I am closing this ticket.
