### ISSUE TITLE
Android Drop-In UI : Allow to override back press button

### ISSUE THREAD

**Issue by Sridhar261990** [mapbox/mapbox-navigation-android#6198]
Hello, I am using DropInUi navigationView for my application. To any destination, I will show the preview initially to the users and then I have a start button to start navigation. If I press hardware back button when I am in preview state then the onBackpressed is not working. 

**implementation 'com.mapbox.navigation:ui-app:2.7.0-rc.1'
   implementation 'com.mapbox.navigation:ui-dropin:2.7.0-rc.1'**

### Steps to trigger behavior

 1. Select or drop any destination
 2. set the routes to preview state by using the below code.
 binding.navigationView.api.setPreviewRoutes(routes)
                    SharedApp.store.dispatch(NavigationStateAction.Update(NavigationState.RoutePreview))
                    setInfoForPreview(routes)
 3. And click the hardware back button. It is not working as expected.

**Comment by abhishek1508** [comment]
This is fixed and will be available with `v2.8.0-beta.3`. 
@Sridhar261990

**Comment by Sridhar261990** [comment]
Is v2.8.0-beta.3 applicable for both  dropInUi and navigation:ui?

**Comment by Sridhar261990** [comment]
Hi @abhishek1508 , I am getting some import errors if I apply beta.3 for both dropinUi and navigation:ui.

**Comment by abhishek1508** [comment]
My bad it will be available in `v2.8.0-beta.2` which will be released today or tomorrow. I will let you know

**Comment by Sridhar261990** [comment]
Thank you @abhishek1508.

**Comment by abhishek1508** [comment]
@Sridhar261990 v2.8.0-beta.2 was released. You can pick it up and test overriding back press. 

I would request to close this issue if the problem is fixed.

**Comment by Sridhar261990** [comment]
@abhishek1508 setRoutes and setPreviewRoutes are not available. Do you provide any alternate to set the preview and routes?

**Comment by abhishek1508** [comment]
> @abhishek1508 setRoutes and setPreviewRoutes are not available. Do you provide any alternate to set the preview and routes?

@Sridhar261990 Now you don't need to use `SharedApp.` functions. You can directly use `navigationView.api.startPreviewRoutes()` and `navigationView.api.startAvtiveGuidance()`

**Comment by Sridhar261990** [comment]
The onBackpressed is not working  as expected. It is working like as before. I have updated the dependencies like below.

implementation 'com.mapbox.navigation:ui-app:2.8.0-beta.2'
implementation 'com.mapbox.navigation:ui-dropin:2.8.0-beta.2'

The onBackPressed triggers only in the third click.

**Comment by Sridhar261990** [comment]
Hi @abhishek1508. Did I miss anything?

**Comment by abhishek1508** [comment]
> Hi @abhishek1508. Did I miss anything?

Let me get back to you on this.

**Comment by abhishek1508** [comment]
@Sridhar261990 I have been trying to reproduce the problem you mentioned, but overriding back press is working fine for me. Please take a look at https://github.com/mapbox/mapbox-navigation-android/blob/main/qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/view/customnavview/MapboxNavigationViewCustomizedActivity.kt#L565-L595 which demonstrates how back press should be handled. I would recommend to debug and see how the first 2 back press events are being handled. Let me know if you need more help.

**Comment by Sridhar261990** [comment]
Thank you @abhishek1508 . It is working fine.
