### ISSUE TITLE
Maneuver Instructions list is not showing in DropInUI

### ISSUE THREAD

**Issue by Sridhar261990** [mapbox/mapbox-navigation-android#6199]
Hello, The Maneuver instructions list are not showing when I tap the Maneuver instruction at the top of the navigationView.

** implementation 'com.mapbox.navigation:ui-app:2.7.0-rc.1'
    implementation 'com.mapbox.navigation:ui-dropin:2.7.0-rc.1'**

### Steps to trigger behavior

 1. Start the navigation to any location.
 2. We can see the Maneuver instructions at the top, infoPanel at the bottom and other views like max speed,recenter,sound Icons.
 3. Tap the Maneuver instructions and it is not showing in the maneuver list.

**Comment by abhishek1508** [comment]
Hi @Sridhar261990 
Please bump the dependency to `v2.8.0-aplha.3` and it should be available. Closing this ticket.
