### ISSUE TITLE
Android Drop-In UI : Is it possible to customize the action in end navigation(x) click 

### ISSUE THREAD

**Issue by Sridhar261990** [mapbox/mapbox-navigation-android#6201]
I want to finish the activity or do some action when the user tap the end navigation. Currently it is ending the navigation and shows the puck in the current location

**implementation 'com.mapbox.navigation:ui-app:2.8.0-alpha.3'
    implementation 'com.mapbox.navigation:ui-dropin:2.8.0-alpha.3'**

### Steps to trigger behavior

 1. Start the navigation to any location
 2. End the navigation by tapping the (X) button
 3. It is ending the navigation and showing the puck in current location

**Comment by abhishek1508** [comment]
@Sridhar261990 At the moment it's not possible to intercept end navigation button click. We will pick this up in the next few weeks. Until then, you would have to create your own custom `InfoPanelHeaderBinder` which would contain a `TripProgressView` and `EndNavigation` button. Since now you would be adding your own end navigation button, you will have control on what happens when you click on it.

**Comment by Sridhar261990** [comment]
Thank you @abhishek1508. I have done that by writing my own InfoPanelHeaderBinder.

**Comment by abhishek1508** [comment]
That's great @Sridhar261990 
I will however let this be open because this is a functionality that we want to provide so that you don't have to override the entire `InfoPanelHeaderBinder`

**Comment by abhishek1508** [comment]
@Sridhar261990 With release `v2.8.0-rc.1` now you can just inject your own `End navigation button` to info panel without creating your own `InfoPanelHeaderBinder` to control on click on the button. 
Release it already available and you can find the example [here](https://github.com/mapbox/mapbox-navigation-android/blob/main/qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/view/customnavview/MapboxNavigationViewCustomizedActivity.kt#L535-L544)

cc @Zayankovsky

**Comment by Sridhar261990** [comment]
Thank you @abhishek1508.
