### ISSUE TITLE
Changelog verification is no longer working for libnavui-androidauto

### ISSUE THREAD

**Issue by kmadsen** [mapbox/mapbox-navigation-android#6220]
## Description

Here are a couple pull requests that I added changelogs to but they are failing

https://github.com/mapbox/mapbox-navigation-android/pull/6219
https://github.com/mapbox/mapbox-navigation-android/pull/6211

Here's a quick link to a circleci

https://app.circleci.com/pipelines/github/mapbox/mapbox-navigation-android/19991/workflows/34e77188-169c-4922-a7d1-a603fd0273ba/jobs/98859

This was a all working before. Looks like there was a regression, potentially from this one https://github.com/mapbox/mapbox-navigation-android/pull/6083

cc: [dzinad](https://github.com/dzinad)

**Comment by kmadsen** [comment]
Am i putting in the changelog incorrectly now? The error logs appear to have read the `libnavui-androidauot/CHANGELOG.md` but still failed 🤔 

```
Validating that changelog entry is provided in the CHANGELOG.md...
[ddlog] diff: diff --git a/libnavui-androidauto/CHANGELOG.md b/libnavui-androidauto/CHANGELOG.md
index 17ce440b9aa..e56232787e1 100644
--- a/libnavui-androidauto/CHANGELOG.md
+++ b/libnavui-androidauto/CHANGELOG.md
@@ -5,6 +5,7 @@ Mapbox welcomes participation and contributions from everyone.
 ## Unreleased
 #### Features
 #### Bug fixes and improvements
+- Removed `MapboxNavigation` from `CarNavigationCamera` and `CarRouteLine` constructors. [#6219](https://github.com/******/******-navigation-android/pull/6219)
 
 ## androidauto-v0.8.0 - Aug 18, 2022
```

**Comment by dzinad** [comment]
Oh, I was not aware that there are 2 changelog files and the same script is used to check them.

**Comment by kmadsen** [comment]
Resolved by https://github.com/mapbox/mapbox-navigation-android/pull/6221
