### ISSUE TITLE
Issue of mapping NN `BannerComponentSubType`

### ISSUE THREAD

**Issue by RingerJK** [mapbox/mapbox-navigation-android#6238]
Issue of mapping NN `BannerComponentSubType`. It must be mapped to the particular value, avoiding just taking the name of `enum's item`

https://github.com/mapbox/mapbox-navigation-android/blob/9073234c2978c019980ca606b16fa0d3ff37f85b/libnavigation-core/src/main/java/com/mapbox/navigation/core/navigator/NavigatorMapper.kt#L251

**Comment by LukasPaczos** [comment]
Fixed in https://github.com/mapbox/mapbox-navigation-android/pull/6239.

**Comment by RingerJK** [comment]
then let's close the issue
