### ISSUE TITLE
NavigationView can draw route just once time.

### ISSUE THREAD

**Issue by slm** [mapbox/mapbox-navigation-android#624]
What kind of issue is this?
 - [X] Question. 
 Navigation SDK Version : 0.8.0
 MapBox Sdk       : 5.2.1
 MapboxServices : 2.2.9
 MapboxSdkServices: 3.0.0-beta.1
 LocationLayerPlugin: '0.2.0'

NavigationView can draw route just once time. I used navigationView in a fragment in [there](https://gist.github.com/slm/b78d15e203660b78bad2b31e171224d3).
I set route before show that fragment in activity with that setNavigation in [that](https://gist.github.com/slm/4184b5bb00e13dadcf44699d88f8171d) class.

 getRoute    
```
  Point origin = Point.fromLngLat(last_location.getLongitude(),last_location.getLatitude());
        Point destination = Point.fromLngLat(location.getLongitude(), location.getLatitude());
        NavigationRoute.builder()
                    .accessToken(Mapbox.getAccessToken())
                    .origin(origin)
                    .destination(destination)
                    .build()
                    .getRoute(this);
...
 @Override
    public void onResponse(Call<DirectionsResponse> call, Response<DirectionsResponse> response) {
        hideCalculatingDialog();
        if (response.body() != null) {
            if (response.body().routes().size() > 0) {

                DirectionsRoute route = response.body().routes().get(0);
                NavigationViewOptions.Builder optionsBuilder = NavigationViewOptions.builder();
                optionsBuilder.directionsRoute(route);
                optionsBuilder.navigationOptions(
                        MapboxNavigationOptions.builder()
                        .enableNotification(false)
                                .build());

                routeListener.onRouteCalculated(optionsBuilder.build());

            }
        }
    }
```  

I add fragment in activity like that.
```
@Override
public void onRouteCalculated(NavigationViewOptions options) {
     NavigationUtils.setNavigation(this,options);
    getSupportFragmentManager()
         .beginTransaction()
         .remove(navigationFragment) // that navigationFragment use mapbox
         .commitAllowingStateLoss();
    FragmentTransaction transaction = getSupportFragmentManager().beginTransaction();
    transaction.add(R.id.navigation_fragment_container, new 
    MapboxRouteNavigationFragment(),"NavigationRoute");
    transaction.commitAllowingStateLoss();
}
```

**Comment by danesfeder** [comment]
Hey @slm is the issue here that you'd like to draw alternative routes in addition to the route being traveled when you begin navigation with `NavigationView`?

**Comment by slm** [comment]
No. I try to explain an example:
1-) I call setNavigation method(It's same NavigationLauncher.startNavigation but don't start activity) with route options from my location to B city. And show navigationview inside of fragment.

2-) After ı remove fragment from activity. And call setNavigation method again with route options my location to Z city.(I checked route options its correct)  And show navigationview fragment. But navigation view show route from my location to B city.(First showed route) It's must be my location to Z city.

**Comment by danesfeder** [comment]
@slm It looks like this may be an issue with your `SharedPreferences` being updated correctly the second time before you commit the `Fragment` again (just my hunch).  

Can you verify that the _second_ time the fragment is being added, the `DirectionsRoute` is the correct one here https://gist.github.com/slm/b78d15e203660b78bad2b31e171224d3#file-gistfile1-txt-L127?

**Comment by slm** [comment]
@danesfeder I checked that issue a lot of times.
```
First request DirectionsRoute: {"distance":11951.7,"duration":1264.7,"geometry":"elyehAujyyr@U_@iKeP}Uy]....
Second request {"distance":3231.9,"duration":432.3,"geometry":"elyehAujyyr@U_@iKeP}Uy]eJr....
```
these route completely different. Map must show second route. But it's show first route.
I tried to `commit` instead of `apply` with `SharedPreferences`. `apply` runs asynchronous. But it could not fix this error.

**Comment by danesfeder** [comment]
@slm It looks like this was an error involving the route extraction on our side.  Once #640 lands, please see if your issue is resolved using the `0.8.1-SNAPSHOT` cc @devotaaabel

**Comment by slm** [comment]
I tested. Its works. Thank you.👍  But there a little bug. The first route marker is still visible.
<img width="370" alt="screen shot 2018-01-11 at 22 42 03" src="https://user-images.githubusercontent.com/5596316/34843929-ef62daa4-f720-11e7-82b3-fc49cc87f7ce.png">

**Comment by danesfeder** [comment]
@slm Yeah we found that as well and will be addressed in https://github.com/mapbox/mapbox-navigation-android/pull/641/ (we will clear existing markers on `NavigationView#startNavigation`)

**Comment by danesfeder** [comment]
Closing this as the original issue was solved.   Feel free to open any other issues as you run into them @slm.  Thanks again for the feedback here.
