### ISSUE TITLE
Android Drop-In UI: Camera issues

### ISSUE THREAD

**Issue by Zayankovsky** [mapbox/mapbox-navigation-android#6251]
1. ~~Camera pitch does not change to zero before a maneuver, if reroute happened before that~~ (fixed in #6283):

https://user-images.githubusercontent.com/71784588/184895086-10386fc0-f321-432b-8f7b-514a2367ca92.mp4

2. Camera returns to user location when going from route preview to destination preview:

https://user-images.githubusercontent.com/71784588/185092723-6910d4d9-02f7-4af8-a13b-a5c8411ae01a.mp4

3. Camera unnecessarily moves from location puck to destination and back after you cancel the trip:

https://user-images.githubusercontent.com/71784588/185176129-5a67094d-2815-46db-bf04-accacbde8565.mp4

4.  ~~Following camera is not working properly after a reroute~~ (fixed in #6283):

https://user-images.githubusercontent.com/71784588/187438409-9b586ea6-1599-4a11-9484-9d39a69008eb.mp4

**Comment by EricGeiler** [comment]
I can confirm the same from my testing.

**Comment by Zayankovsky** [comment]
5. Overview camera in route preview has unwanted pitch, if view recreated (e.g. due to screen rotation) before that while camera was in the Following state. This causes the route to be partially hidden by the info panel:

https://user-images.githubusercontent.com/2395284/187880799-94eeb129-56d1-4ab2-a311-b745064683f9.mp4

**Comment by EricGeiler** [comment]
@Zayankovsky Thanks for posting these issues, I was also going to do the same before i saw this the other day, as I have seen a few of these issues during my testing.  nice catch!  #1 thru 4 are biggy blockers for our users.  We don't enable rotation on our map, so I can't speak to #5.

cc: @Sridhar261990

**Comment by Zayankovsky** [comment]
6. Camera should return to the user location when going from destination preview to free drive:

https://user-images.githubusercontent.com/71784588/185088679-21a097f5-a87d-4430-a910-253dc61e2c3e.mp4

**Comment by Zayankovsky** [comment]
@abhishek1508 switching to an alternative route forces camera state to become following, is this intentional?

**Comment by Zayankovsky** [comment]
7. Rerouting or switching to an alternative route forces camera state to become following:

https://user-images.githubusercontent.com/71784588/184887405-bbd8a3b7-a83f-43cc-9344-48ce9dc050dd.mp4

https://user-images.githubusercontent.com/71784588/187956111-2b854002-038d-4b4b-9f7e-26b53b79261b.mp4

**Comment by EricGeiler** [comment]
@Zayankovsky amazing work!  thank you very much!

**Comment by Zayankovsky** [comment]
@EricGeiler all these issues should be fixed in Nav SDK version `2.8.0-beta.3`, which is going to be available this week.

**Comment by EricGeiler** [comment]
@Zayankovsky Thank you very much for your hard work!  
cc: @sridhar261990
