### ISSUE TITLE
Does mapbox use mapzen?

### ISSUE THREAD

**Issue by antoniokranjcina** [mapbox/mapbox-navigation-android#6279]
Hello,
I have tried to update the project SDK version from 30 to 33. For 31+ versions android requires explicit value for android:exported be defined. However, after resolving all update related problems, android studio won't build the app and it shows following error:

```
'/app/build/outputs/apk/debug/app-debug.apk'
Installation failed due to: 'Failed to commit install session 61810440 with command cmd package install-commit 61810440. Error: INSTALL_PARSE_FAILED_MANIFEST_MALFORMED: Failed parse during installPackageLI: /data/app/vmdl61810440.tmp/base.apk (at Binary XML file line #585): com.mapzen.android.lost.internal.GeofencingIntentService: Targeting S+ (version 31 and above) requires that an explicit value for android:exported be defined when intent filters are present'
Retry
Failed to launch an application on all devices
```
Since I don't use this library in the project I was talking about above, this limits me to SDK version 30. My question here is if mapbox uses it?

**Comment by cafesilencio** [comment]
cc @mapbox/maps-android

**Comment by kiryldz** [comment]
@antoniokranjcina we do not use this dependency from what I see. Could you run something like:
```
./gradlew :app:dependencies | grep mapzen
```
it should show where does it come from, perhaps from some other dependency you're using apart from Mapbox?

**Comment by antoniokranjcina** [comment]
@kiryldz Seems like mapbox-android-ui is using it:
![MicrosoftTeams-image](https://user-images.githubusercontent.com/54414989/190133914-6a17bf61-73a0-44a3-b6b2-66ddf903f95a.png)
Can we expect this issue to be resolved?

**Comment by kiryldz** [comment]
@antoniokranjcina that looks like the Nav SDK v1 to me, tagging @mapbox/navigation-android to have their 👀

**Comment by RingerJK** [comment]
@antoniokranjcina what does the version of Nav SDK you use?

**Comment by antoniokranjcina** [comment]
@RingerJK I'm not sure how is Nav SDK related to this android-ui. However, we use 2.6.0 version for navigation and 10.6.0 for maps. Our problem is that we use android-ui which uses mapzen under the hood.

**Comment by RingerJK** [comment]
@antoniokranjcina The dependency `mapzen` comes from [mapbox-java v2.2.10](from https://github.com/mapbox/mapbox-java/blob/v2.2.10/mapbox/libandroid-ui/gradle.properties) ([ref2](https://github.com/mapbox/mapbox-java/blob/v2.2.10/mapbox/dependencies.gradle#L40)) which is legacy and doesn't uses in Nav SDK version [2.6.0](https://github.com/mapbox/mapbox-navigation-android/releases/tag/v2.6.0) (see Mapbox Java v6.6.0). So probably this dependency comes from something outside or you added one manually. Could you check where this dependency(`mapbox-java v2.2.10`) is come from?
