### ISSUE TITLE
Feature Request - NavigationView - Use smaller increments for rounding small distances

### ISSUE THREAD

**Issue by davols** [mapbox/mapbox-navigation-android#628]
Small feature request.

After testing a bunch with the NavigationView, it seems that it always will round to 50 meters regardless of the distance left. This feels quite weird when the distance to the upcoming step is less than 100m. 

At first I thought about the idea to have 25 meter intervals, but in iOS it seems to be even lower increments. Maybe use the same setup with rounding and the intervals as in iOS?

Semi related: https://github.com/mapbox/mapbox-navigation-ios/issues/681

**Comment by danesfeder** [comment]
Hey @davols, we are going to be working on our distance formatter in the coming weeks.  We are mainly going to be focused on localization but I can also look into adding some customization in regard to what you're pointing out here.   I'll be sure to update this ticket as the work progresses.
