### ISSUE TITLE
Allow to remove or replace the destination marker

### ISSUE THREAD

**Issue by Sridhar261990** [mapbox/mapbox-navigation-android#6282]
Hi, I am using DropInUI in our application. I want to use our own custom icon in the destination point instead of using the default marker. Please provide a way to add our own custom marker.

**implementation 'com.mapbox.navigation:ui-app:2.8.0-beta.2'
implementation 'com.mapbox.navigation:ui-dropin:2.8.0-beta.2'**

**Comment by EricGeiler** [comment]
I've been advised by Sridhar, that we cannot Hide the default destination marker, nor can we change the default destination marker.  I was hoping to use a sprite image from our style, but I'm also okay with a .png being provided via res.

I'd really like to a see a solution for this.  Either hide your default marker, so we can use a annotation to display our custom destination marker, or allow us the ability to change the default marker.

![image](https://user-images.githubusercontent.com/61550186/188940603-e49be049-a9db-4365-81a4-14c612c8a397.png)

I want to use the checkered flag, not the default oversized blue marker.

**Comment by abhishek1508** [comment]
@Sridhar261990 I told you that this feature is not available today with Drop-In UI. However, I was mistaken.

@EricGeiler 
Drop-In UI at the moment does not allow to remove the destination marker, but you can replace the existing marker. An example to do this is already available [here](https://github.com/mapbox/mapbox-navigation-android-examples/blob/main/app-preview/src/main/java/com/mapbox/navigation/examples/preview/dropinui/CustomRuntimeStylingActivity.kt#L68)

Please close this ticket once you confirm that you are able to replace the default destination marker.

**Comment by EricGeiler** [comment]
@abhishek1508 You da Man!  Thank you so much!
