### ISSUE TITLE
[Drop-In] Android - Info Panels can be expanded on Route Overview ?

### ISSUE THREAD

**Issue by EricGeiler** [mapbox/mapbox-navigation-android#6289]
*** In attempts to reproduce this on video, I think I discovered another issue**** 

I'm a non-dev posting a potential bug, it can be reproduced via the step noted in this ticket.
Any lat/long coordinates can be used to replicate the issue.
Video of this ticket is provided at the very bottom of this post.

Mobile Platform: Android 10
OS Build: 8A.0.8-13-10.0.0-11.22.00
Hardware: Sonim XP8

implementation 'com.mapbox.navigation:ui-app:2.8.0-beta.2'
implementation 'com.mapbox.navigation:ui-dropin:2.8.0-beta.2'

### Steps to trigger behavior

 1. Start Nav (by default your on the route overview screen)
 2. I accidentally swiped up on the screen and noticed our custom info panel was displayed but partially hidden behind what I beleive to be the route overview info panel.

### Expected behavior

1. IMO, info panel should not be accessible from this route overview screen, as the user has no idea that pull up capabilities exist at this portion of the app, no drawer / slider visible... only way a user would pull up panel on this screen would be by mistake.

### Actual behavior

See video.

https://user-images.githubusercontent.com/61550186/189179832-4b736057-6ed3-402f-9920-0746bdf24f86.mp4

**Comment by EricGeiler** [comment]
FYI... just to add clarity to this ticket, we have NOT yet implemented #6277

**Comment by abhishek1508** [comment]
@EricGeiler Thanks for reporting the issue. 

This looks like an implementation issue in the application. I would like to find out how are you overlaying the additional view at bottom that displays route overview information with start navigation button.

**Comment by EricGeiler** [comment]
@abhishek1508  I wish I knew the techie details, I'm deferring this to @sridhar261990 Please provide the necessary info to resolve this implementation issue.

**Comment by Sridhar261990** [comment]
@abhishek1508 I have fixed this issue in app level. @EricGeiler Can you please close this ticket?
