### ISSUE TITLE
Android Drop-In UI: How to use snappingIncludeClosures and snappingIncludeStaticClosures in our application?

### ISSUE THREAD

**Issue by Sridhar261990** [mapbox/mapbox-navigation-android#6332]
Hello all, I am using DropInUi in our application and I want to use snappingIncludeClosures  and snappingIncludeStaticClosures.  The description for the snappingIncludeClosures from the documentation is - A semicolon-separated list of booleans affecting snapping of coordinate locations to road segments. If true, road segments closed due to live-traffic closures will be considered for snapping. If false, they will not be considered for snapping. If provided, the number of snapping_include_closures must be the same as the number of coordinates. However, you can skip a coordinate and show its position in the list with the ; separator. If unspecified, this paramter defaults to false. Should I pass the boolean values with comma separated? The description is bit confusing. We want to achieve something like below first image instead of second image.

![snap1](https://user-images.githubusercontent.com/95765713/190376733-d394b174-288b-40a6-8c89-b9a10fe0a216.PNG)
![snap2](https://user-images.githubusercontent.com/95765713/190376759-fac28358-ff23-4d65-a31d-8078a706b177.PNG)

Request for the first image is -https://api.mapbox.com/directions/v5/mapbox/driving/-79.775735%2C44.067486%3B-79.746525%2C44.074092?alternatives=true&annotations=distance%2Cduration%2Cspeed%2Ccongestion&geometries=polyline6&language=en&overview=full&steps=true&access_token=xxxxxxxx

Request for second image is -https://api.mapbox.com/directions/v5/mapbox/driving-traffic/-79.775735%2C44.067486%3B-79.746525%2C44.074092?alternatives=true&annotations=distance%2Cduration%2Cspeed%2Ccongestion&geometries=polyline6&language=en&overview=full&steps=true&access_token=xxxxxxxx

We are expecting to see the result of first image if we use snappingIncludeClosures with profile - driving-traffic. Right now we are getting the result like second image with driving-traffic profile.

**Mapbox Navigation SDK version:     implementation 'com.mapbox.navigation:ui-app:2.8.0-beta.3'
    implementation 'com.mapbox.navigation:ui-dropin:2.8.0-beta.3'**

**Comment by Sridhar261990** [comment]
@EricGeiler

**Comment by abhishek1508** [comment]
@Sridhar261990 Thanks for creating the issue. Are you making the route request using Drop-In UI or outside Drop-In UI?

**Comment by Sridhar261990** [comment]
@abhishek1508  I am making the request as below.

 RouteOptions.builder()
                .applyDefaultNavigationOptions()
                .applyLanguageAndVoiceUnitOptions(this.applicationContext)
                .coordinatesList(listOf(origin, destination))
                .alternatives(true)
                .baseUrl(Constants.BASE_API_URL)
                .user(Constants.MAPBOX_USER)
                .maxHeight(1.6)
                .maxWeight(2.5)
                .maxWidth(1.9)
//                .snappingIncludeClosures("true")
//                .snappingIncludeStaticClosures("true")
                .exclude(DirectionsCriteria.EXCLUDE_TOLL)
                .voiceInstructions(true)
                .bannerInstructions(true)
                .continueStraight(true)
                .alternatives(true)
                .annotationsList(annotations)
                .roundaboutExits(true)
                .overview("full")
                .steps(true)
                .build()

**Comment by abhishek1508** [comment]
@Sridhar261990 If you take a look at the arguments of `snappingIncludeClosures` you will notice that it is not `boolean`. Same applies to `snappingIncludeStaticClosures`.

<img width="675" alt="Screen Shot 2022-09-15 at 4 09 45 PM" src="https://user-images.githubusercontent.com/9770186/190383742-fa96a7ea-7b79-45bc-9324-6ea08708d2dd.png">

In your case, you can do the following

```
RouteOptions.builder()
.applyDefaultNavigationOptions()
.applyLanguageAndVoiceUnitOptions(this.applicationContext)
.coordinatesList(listOf(origin, destination))
.alternatives(true)
.baseUrl(Constants.BASE_API_URL)
.user(Constants.MAPBOX_USER)
.maxHeight(1.6)
.maxWeight(2.5)
.maxWidth(1.9)
.snappingIncludeClosures(listOf(true, true)) // if you want both coordinates to be considered for snapping
.snappingIncludeStaticClosures(listOf(true, true)) // if you want both coordinates to be considered for snapping
.exclude(DirectionsCriteria.EXCLUDE_TOLL)
.voiceInstructions(true)
.bannerInstructions(true)
.continueStraight(true)
.alternatives(true)
.annotationsList(annotations)
.roundaboutExits(true)
.overview("full")
.steps(true)
.build()
```

**Comment by EricGeiler** [comment]
Operational / Business case is the following;

Driver is navigated to a location where the way leading to the lat/long is marked as closed or under construction.  Access us signed and noted as local traffic only.  The construction contractors in is required to maintain 1 lane open for local access during business hours etc.  

The driver will attempt to enter the construction zone to access the local business or home to complete the delivery.  Once the driver has completed the delivery at the house within the construction zone, the driver then re-starts his navigation to proceed to his next stop.  With snapping to closures I'm hoping to have the driver route start on the new nav trip start at this current location within the construction way/road/driveway etc..... however currently the nav starts at either end of the construction zone, snapping to the closest non-closed road.

![image](https://user-images.githubusercontent.com/61550186/190385065-c6e8a7ed-f8d1-4086-b5f4-95600cf87406.png)

https://www.newtecumseth.ca/en/news/7th-line-road-reconstruction-and-temporary-road-closure.aspx

Our drivers daily complete order pickups or delivery from restricted/closed roads.

**Comment by Sridhar261990** [comment]
Thank you @abhishek1508. I thought in a same way. But I am not very sure. Thank you again. I will try that and update you.

**Comment by Sridhar261990** [comment]
@abhishek1508  I have tried the below possibilities.
 .snappingIncludeClosures(listOf(true, true).toString())
 .snappingIncludeClosures(listOf(true, true).toString())

 .snappingIncludeClosures("true,true")
 .snappingIncludeClosures("true,true")

 .snappingIncludeClosures("true;true")
 .snappingIncludeClosures("true;true")

I am always getting failure with message - snapping_include_closures must be either empty, 'true' or 'false', one entry per coordinate, separated by ';'

Please correct me If I am doing anything wrong.

**Comment by Sridhar261990** [comment]
Hi @abhishek1508 , This is working fine.
          .snappingIncludeClosuresList(listOf(true, true))
          .snappingIncludeStaticClosuresList(listOf(true, true))

**Comment by abhishek1508** [comment]
I would appreciate if you could close this ticket given the original issue is resolved. 
@Sridhar261990
