### ISSUE TITLE
[Question] How can i hide alert view and feedback?

### ISSUE THREAD

**Issue by darkwizzard** [mapbox/mapbox-navigation-android#634]
Hello, i need to hide the "Report Problem" alert and the feedbacks. There is a work around for do that? Thanks.

**Comment by danesfeder** [comment]
Hey @darkwizzard - we currently don't provide a way to show / hide the UI components.  We are looking to add boolean flags in `NavigationViewOptions` or something of this nature to do this eventually.  But unfortunately, we don't have a set timeline for this work at the moment.

**Comment by Danny-James** [comment]
@danesfeder this is something I would also like, Hiding of Feedback buttons, audio button etc.

**Comment by danesfeder** [comment]
@Danny-James are you using `NavigationLauncher`?

**Comment by Danny-James** [comment]
Yes Mate, `NavigationLauncher.startNavigation();`

**Comment by danesfeder** [comment]
@Danny-James I haven't created the boolean options to hide / show these just yet unfortunately.  But, if you used `NavigationView` like we do in `NavigationActivity` https://github.com/mapbox/mapbox-navigation-android/blob/master/libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/NavigationActivity.java 

you can do it now by binding `View feedbackFab = findViewById(R.id.feedbackFab);` then just set the visibility to `GONE`

**Comment by Danny-James** [comment]
@danesfeder so would I have to create all my own activities with this and wouldn't be able to use the navigation UI?

**Comment by danesfeder** [comment]
`NavigationLauncher` eventually launches `NavigationActivity` (inflates `NavigationView`) but limits the amount of customization you can do.  If you include / inflate `NavigationView` in your own `Activity` modeled after the `NavigationActivity` you'll have a lot more options as far as customization.  Like hiding the feedback button.

**Comment by Danny-James** [comment]
No Problem, So If I Create The NavigationActivity Like You Referenced I Will Basically Have The Acitivty When Calling `NavigationLauncher.startNavigation();`, or is their more to it than that?

**Comment by danesfeder** [comment]
This isn't in our work pipeline right now but it's a pretty simple PR.  I'll see if I can sneak it into our next release

**Comment by Danny-James** [comment]
@danesfeder thanks buddy.

**Comment by danesfeder** [comment]
Update here:

This is currently possible when using the `NavigationView` in your `Activity` or `Fragment`.  

Once the layout is set and you have used `findViewById` to find the `NavigationView` in your layout, you can also find the feedback or sound FABs and hide their visibility:
```
  @Override
  public void onNavigationReady(boolean isRunning) {
    navigationView.startNavigation(options);
    navigationView.findViewById(R.id.feedbackFab).setVisibility(View.GONE);
  }
```
_Note:_ this must be done in `onNavigationReady` and after `NavigationView#startNavigation` is called - the `View` initializes them to `VISIBLE` so, if done prior, your changes will be overridden. 

This is currently _not_ possible when using `NavigationLauncher`.  Because we automatically create an `Activity` for you, you don't have access to the reference of `NavigationView` to add this logic.

We realize this isn't straightforward and the point of this ticket is to add APIs to `NavigationView` that will streamline this process.  For example, `NavigationViewOptions#hideFeedback(true)` / `NavigationLauncherOptions#hideFeedback(true)`

**Comment by cmahopper** [comment]
@danesfeder Thanks, good idea for the feedback button.
I have noticed that when you go off route sometimes, an AlertView pops up that says "Report a problem". Tapping on this brings up the Feedback Sheet as well. Can we hide this AlertView too in some way? It seems to set its own visibility to Visible whenever it is shown, so I'm not sure if the same trick can be used here.

**Comment by danesfeder** [comment]
@cmahopper the `AlertView` should be fine if you set it to `GONE` as well.  It does set its own visibility, but will only show if the current visibility is set to `INVISIBLE` https://github.com/mapbox/mapbox-navigation-android/blob/master/libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/alert/AlertView.java#L79-L94

**Comment by cmahopper** [comment]
@danesfeder Wonderful, thanks!

**Comment by danesfeder** [comment]
This landed with #1251 🚀

**Comment by emilefleming** [comment]
Does #1251 now make it possible to hide the feedback or sound buttons when using NavigationLauncher?

**Comment by sjd753** [comment]
For those who use kotlin 

 val feedbackFab = mapNavigationView?.findViewById<FloatingActionButton>(R.id.feedbackFab)
 feedbackFab?.hide()

as setVisibility isn't available for the button out the the library bounds!! Happy coding!!! :+1:

**Comment by kanhaiyhacker** [comment]
> @cmahopper the `AlertView` should be fine if you set it to `GONE` as well. It does set its own visibility, but will only show if the current visibility is set to `INVISIBLE` https://github.com/mapbox/mapbox-navigation-android/blob/master/libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/alert/AlertView.java#L79-L94

it is not working and hiding "report problem" alert when off route.

**Comment by jrodiz** [comment]
@kanhaiyhacker 

    navigationView.retrieveAlertView().setVisibility(View.GONE);
