### ISSUE TITLE
Android Drop-In UI: Is it possible to play voice instruction of incident when we are nearby the incident?

### ISSUE THREAD

**Issue by Sridhar261990** [mapbox/mapbox-navigation-android#6359]
Hello Team, I am using DropInUi for my application. I want to play the voice instruction when the driver is nearing the incident. I am getting incident information from the upcomingIncident.roadObject. Can I play the incident description by using the voice instructions?

  implementation 'com.mapbox.navigation:ui-app:2.8.0-rc.2'
  implementation 'com.mapbox.navigation:ui-dropin:2.8.0-rc.2'

**Comment by Guardiola31337** [comment]
Hey @Sridhar261990 thanks for reaching out and report your question.

Yeah, you can play custom voice instructions. You can find an example on how to implement it in [`MapboxVoiceActivity`](https://github.com/mapbox/mapbox-navigation-android/blob/main/examples/src/main/java/com/mapbox/navigation/examples/core/MapboxVoiceActivity.kt) from the [`examples`](https://github.com/mapbox/mapbox-navigation-android/tree/main/examples) test app 👀 

https://github.com/mapbox/mapbox-navigation-android/blob/c862ce68aa0f06ccf79e6a7c72d433626d5593b3/examples/src/main/java/com/mapbox/navigation/examples/core/MapboxVoiceActivity.kt#L294-L299

Please take a look at it and let us know if you have any follow-up questions.

Thanks for checking out the SDK.

**Comment by EricGeiler** [comment]
@Guardiola31337 Thanks for the input Pablo, your opinions are always valued,  you've helped us a lot over the years.

@abhishek1508 This would be a "nice to have feature" but its far from blocking any releases on our end.  My main concern is that the incident data I'm seeing in Canada isn't exactly short descriptions... I'm leary of having a driver try and read that qty of text while driving.... hence the feature request for audio.

Here are some of the shorter examples i've personally run into... both times I have travelling on roads with posted speed limits of 100 km/h, so I waited until I was stopped before looking ahead on the map to read incident text.  not sure i want drivers to be reading this text while in motion at those speeds... 
![image](https://user-images.githubusercontent.com/61550186/191273524-ca771c83-13c4-456e-90cb-4ac7b88d9961.png)

**Comment by abhishek1508** [comment]
@EricGeiler Thanks for the detailed explanation. We will evaluate this request and come up with updates when we have a solution ready.

**Comment by EricGeiler** [comment]
> @EricGeiler Thanks for the detailed explanation. We will evaluate this request and come up with updates when we have a solution ready.

Thank you for the update!  Hopefully its a useful suggestion!

**Comment by Sridhar261990** [comment]
Hi @abhishek1508, May I know the status of this feature request?

**Comment by abhishek1508** [comment]
> @abhishek1508 This would be a "nice to have feature" but its far from blocking any releases on our end.

@Sridhar261990 Can you share the priority of this issue? I was under the impression that it is not launch blocking and hence we haven't picked it up yet. However, needless to say this is still something we are tracking and is under our radar.

**Comment by Sridhar261990** [comment]
@abhishek1508 It is not blocking. I am just curious to know when this feature will be available.

**Comment by EricGeiler** [comment]
@abhishek1508 its a nice to have feature I'd like to include in our follow up release to drivers, its NOT blocking our initial release.

**Comment by abhishek1508** [comment]
@EricGeiler Thanks for clarifying. We will update the ticket once we have a working solution.

**Comment by EricGeiler** [comment]
Lets call it Oct 20-31th time frame as a ball park.  
Getting a 2.8.0-release from @Sridhar261990  today, gonna run with that fleet wide for a couple of weeks, then attempt a move to 2.9.0+

**Comment by abhishek1508** [comment]
This has been addressed https://github.com/mapbox/mapbox-navigation-android/pull/6475 and was released as a part of [v2.9.0-beta.3](https://github.com/mapbox/mapbox-navigation-android/releases)

cc @EricGeiler @Sridhar261990

**Comment by abhishek1508** [comment]
Closing as this issue has been resolved and feature delivered.
