### ISSUE TITLE
Options

### ISSUE THREAD

**Issue by aliumujib** [mapbox/mapbox-navigation-android#64]
Hello,
Is there a drop in controller that can has been implemented for android just like the one in the iOS repository here? https://github.com/mapbox/mapbox-navigation-ios

I would like to use map box and I just want to know if there is already one in the works before I start doing any heavy lifting.

**Comment by cammace** [comment]
On Android, this will be part of our plugin system. Track https://github.com/mapbox/mapbox-plugins-android/issues/12 to follow the latest progress.
