### ISSUE TITLE
[Bug report] Simple navigation app crashes

### ISSUE THREAD

**Issue by SaeedIsa90** [mapbox/mapbox-navigation-android#649]
Hi Guys,

I'm trying to do a very simple navigation app, but it crashed and not starting up due to this error:
Error:(40, 35) error: method startNavigation in class NavigationLauncher cannot be applied to given types;
required: Activity,NavigationViewOptions
found: MainActivity,Position,Position,String,boolean
reason: actual and formal argument lists differ in length

My gradle file:
apply plugin: 'com.android.application'
`
android {
    compileSdkVersion 26
    defaultConfig {
        applicationId "com.androiddevelopments.saeedisa.navigationex"
        minSdkVersion 19
        targetSdkVersion 26
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}
repositories {
    mavenCentral()
}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    compile 'com.android.support:appcompat-v7:26.1.0'
    compile 'com.android.support.constraint:constraint-layout:1.0.2'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.1'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.1'

    compile ('com.mapbox.mapboxsdk:mapbox-android-sdk:5.3.1') {
        transitive=true
    }
    compile 'com.mapbox.mapboxsdk:mapbox-android-navigation:0.7.1'
    compile ('com.mapbox.mapboxsdk:mapbox-android-navigation-ui:0.7.1') {
        transitive = true
    }
}
`
I also tried using implementation instead of compile. also tried version 5.3.1@aar
I just copied stuff from here: https://www.mapbox.com/help/android-navigation-sdk/#install-the-navigation-sdk

but it did not work, can anyone please tell me what am I doing wrong ? or help me solving this issue please?

Thanks,
Saeed

**Comment by danesfeder** [comment]
Hey @SaeedIsa90, sorry for the confusion here - https://www.mapbox.com/help/android-navigation-sdk/#install-the-navigation-sdk is a little out of date and we are working on updating it asap.  

Launching the UI now looks like this and our latest release is `0.8.0` https://www.mapbox.com/android-docs/navigation/overview/navigation-ui/#launch-the-navigation-ui

**Comment by SaeedIsa90** [comment]
Hi @danesfeder,Thanks I will give it a try, but as I see you don't support turn-by-turn navigation in my area (Israel), when will you ? is there any estimated time ? or an plans to ?

Thanks,
