### ISSUE TITLE
Test App fails to run any of the activities other than MainActivity.

### ISSUE THREAD

**Issue by graemebates** [mapbox/mapbox-navigation-android#65]
I'm having issues running the test application. OnCreate in each activity fails to load when setting the view.

setContentView(R.layout.activity_navigation_activity);

android.view.InflateException: Binary XML file line #12: Binary XML file line #12: Error inflating class com.mapbox.mapboxsdk.maps.MapView

I'm at a loss to what the issue is, as I'm running the entire project cloned. 

Thanks for any help!

**Comment by cammace** [comment]
Like @aliumujib mentioned, the full log would be useful. It sounds like you are missing the access token. Can you make sure your Mapbox access tokens inside the `developer-config.xml` file:

![screen shot 2017-05-31 at 11 39 29 am](https://cloud.githubusercontent.com/assets/5652865/26640526/f4a6f90a-45f5-11e7-8650-2296a235d191.png)

**Comment by cammace** [comment]
Going ahead and closing this issue, feel free to comment back if you are still having issues and I can reopen.
