### ISSUE TITLE
Android Drop-In UI: Drop-In UI Examples not working in Android Studio

### ISSUE THREAD

**Issue by ArdsGold** [mapbox/mapbox-navigation-android#6623]
![image](https://user-images.githubusercontent.com/114910999/202633875-a9299761-11f3-44c2-819d-418f7cf5350f.png)

**Mapbox Navigation SDK version: 2.9.1**

### Steps to trigger behavior

Copy and paste the example found at https://docs.mapbox.com/android/navigation/guides/drop-in-ui/customize-drop-in-ui/#customize-options and change the names of activities and layouts in the code.

### Expected behavior

The code should not give an error in Android Studio.

### Actual behavior

 Using the code from the Drop-In UI documentation gives me the error "not enough information to infer type variable T".
 
 
![image](https://user-images.githubusercontent.com/114910999/202641354-8e500b86-85ee-409d-81f8-8a3d48e16b47.png)

**Comment by abhishek1508** [comment]
@ArdsGold Thank you for reporting the issue. We will fix it in our public docs. Please modify the line from
```
findViewById(R.id.navigationView).customizeViewOptions {
```
to
```
findViewById<NavigationView>(R.id.navigationView).customizeViewOptions {
```

**Comment by abhishek1508** [comment]
The code snippets have been fixed in public docs. Closing the issue.
