### ISSUE TITLE
Android Drop-In UI: Changing Routing Profile

### ISSUE THREAD

**Issue by ArdsGold** [mapbox/mapbox-navigation-android#6637]
Hello everyone,

First of all, I am thankful to Mr. @abhishek1508 in resolving my issue the other day regarding a part of the Drop-In UI's documentation, thank you very much. With all that said, I wonder if it is possible to change the Drop-In UI's Routing Profile, as it was documented in [here](https://docs.mapbox.com/android/navigation/guides/ui-components/route-line/#request-routes-with-the-right-data) that it is indeed possible to request routes with different criteria, like the Cycling Profile for example, because I think it would be a great idea for people who are planning to create a navigation system for other vehicles/profiles while being able to program with ease as beginners.

Apologies for my english.

**Comment by abhishek1508** [comment]
Thank you for the question @ArdsGold 

Yes it is possible to change the routing profile using `Drop-In UI`. You can use the following API to set the `RouteOptionsInterceptor` to build your own routing option
```
findViewById<NavigationView>(R.id.navigationView).setRouteOptionsInterceptor {
    // your `RouteOptions.Builder`
}
```

**Comment by abhishek1508** [comment]
Closing the issue as the question posted in OP has been answered.
