### ISSUE TITLE
[Bug] Can't compile release with proguard

### ISSUE THREAD

**Issue by darkwizzard** [mapbox/mapbox-navigation-android#666]
Hello, I'm trying make a release with proguard but i can't build it success, the error: 

![imagen](https://user-images.githubusercontent.com/5554787/35366910-867f4b5a-015a-11e8-8202-aee2d77a2ff8.png)

How can i get it work?

Thanks.

**Comment by danesfeder** [comment]
This looks like an issue with your `build.gradle` - not sure how to help you here.
