### ISSUE TITLE
SensorManager: unregisterListener :: 14, MPL Rotation Vector

### ISSUE THREAD

**Issue by nafis042** [mapbox/mapbox-navigation-android#671]
When I first press the  start navigation button with or without simulation route, it shows me this:
D/SensorManager: unregisterListener :: 14, MPL Rotation Vector, 
the app doesnot crash. It just initializes view and stays that way.

![27535332_2001922499824602_310233552_o](https://user-images.githubusercontent.com/26213218/35457168-33d49b86-0302-11e8-8130-e2bc81c5a29b.png)

after i go back and press navigation button then it starts fine. And it happens every time I launch app.

**Comment by danesfeder** [comment]
@nafis042 Thanks for bringing this to us - to confirm, this is with Navigation SDK `0.9.0`?  Also, does it only happen with dark-mode enabled like in the screenshot?  Thanks!

**Comment by nafis042** [comment]
I have cloned master branch of the repository and yes it only happens in AppCompatDelegate.MODE_NIGHT_AUTO. other modes seem to work fine

**Comment by rheng001** [comment]
I have the same issue as well.

**Comment by danesfeder** [comment]
Found the issue and pending fix with https://github.com/mapbox/mapbox-navigation-android/pull/683.  This was not related to the sensor manager originally mentioned.
