### ISSUE TITLE
Outdated location layer plugin code in MockNavigationActivity

### ISSUE THREAD

**Issue by langsmith** [mapbox/mapbox-navigation-android#673]
The test app's `MockNavigationActivity` has outdated code for the location layer plugin. Not hard to fix, but just making a ticket for future tracking. Low priority

**Comment by langsmith** [comment]
![screen shot 2018-01-26 at 2 14 09 pm](https://user-images.githubusercontent.com/4394910/35462971-3b334f62-02a3-11e8-858c-b17fc97925e9.png)
![screen shot 2018-01-26 at 2 14 02 pm](https://user-images.githubusercontent.com/4394910/35462972-3b525416-02a3-11e8-964b-536385cb2802.png)
![screen shot 2018-01-26 at 2 13 57 pm](https://user-images.githubusercontent.com/4394910/35462973-3b698a46-02a3-11e8-826b-ce2d6f002ad5.png)

**Comment by danesfeder** [comment]
Being worked in #697

**Comment by danesfeder** [comment]
Closed with #697
