### ISSUE TITLE
DropIn UI camera slightly offset to right when device is landscape

### ISSUE THREAD

**Issue by andrewharvey** [mapbox/mapbox-navigation-android#6744]
**Android API:** 32
**Mapbox Navigation SDK version:** 9.2.5 (drop in UI)

### Steps to trigger behavior

 1. Using a dropin.NavigationView
 2. Rotate device into landscape
 3. Start navigation

### Expected behavior

camera view to be more centered within the panels

### Actual behavior

camera view slightly to the right. It's fine in device portrait mode, only appears in landscape mode.

![Mapbox Navigation View Landscape](https://user-images.githubusercontent.com/117278/207513276-9064b2d0-a915-46c5-8eaa-9298479d320f.png)

**Comment by abhishek1508** [comment]
Thank you for reporting the issue @andrewharvey 
We merged a fix for it today https://github.com/mapbox/mapbox-navigation-android/pull/6730 and would be available with the next release. 

Closing this as done.
