### ISSUE TITLE
Navigation gets stuck sometimes at start

### ISSUE THREAD

**Issue by briandilley** [mapbox/mapbox-navigation-android#676]
Sometimes the navigation seems to get stuck at start.  I'm able to back out and the UI is responsive, it just doesn't navigate:

![Image of Crash](https://i.imgur.com/yfSNzcP.png)

And just to show that it's not only a problem with short routes:

![Image of Crash](https://i.imgur.com/p21Getc.png)

If i leave it long enough it eventually crashes, but never with anything interesting in the logs.  I did notice this in the logs (quite a lot) when it's sitting there stuck:

```
01-28 14:45:46.440   734  1680 E LocSvc_ApiV02: reportGnssMeasurementData:3497]: there is no valid SV measurements
01-28 14:45:46.440   734  1680 E LocSvc_ApiV02: reportGnssMeasurementData:3516]: There is no GNSS measurement.
01-28 14:45:47.441   734  1680 E LocSvc_ApiV02: reportGnssMeasurementData:3497]: there is no valid SV measurements
01-28 14:45:47.441   734  1680 E LocSvc_ApiV02: reportGnssMeasurementData:3516]: There is no GNSS measurement.
01-28 14:45:48.441   734  1680 E LocSvc_ApiV02: reportGnssMeasurementData:3497]: there is no valid SV measurements
01-28 14:45:48.441   734  1680 E LocSvc_ApiV02: reportGnssMeasurementData:3516]: There is no GNSS measurement.
01-28 14:45:49.441   734  1680 E LocSvc_ApiV02: reportGnssMeasurementData:3497]: there is no valid SV measurements
01-28 14:45:49.441   734  1680 E LocSvc_ApiV02: reportGnssMeasurementData:3516]: There is no GNSS measurement.
01-28 14:45:50.439   734  1680 E LocSvc_ApiV02: reportGnssMeasurementData:3497]: there is no valid SV measurements
01-28 14:45:50.439   734  1680 E LocSvc_ApiV02: reportGnssMeasurementData:3516]: There is no GNSS measurement.
01-28 14:45:51.438   734  1680 E LocSvc_ApiV02: reportGnssMeasurementData:3497]: there is no valid SV measurements
01-28 14:45:51.438   734  1680 E LocSvc_ApiV02: reportGnssMeasurementData:3516]: There is no GNSS measurement.
01-28 14:45:52.438   734  1680 E LocSvc_ApiV02: reportGnssMeasurementData:3497]: there is no valid SV measurements
01-28 14:45:52.438   734  1680 E LocSvc_ApiV02: reportGnssMeasurementData:3516]: There is no GNSS measurement.
```

**Comment by danesfeder** [comment]
Thanks for bringing this to us @briandilley -- I've also noticed the navigation UI sometimes fails to initialize properly if we have a weak / or no GPS signal.  I'll dig into this further - appreciate the logs and observations.

**Comment by danesfeder** [comment]
@briandilley Hey Brian, do you think this is related to #675?  Or an issue with the GPS not firing up properly.  Trying to dig into this a bit more

**Comment by danesfeder** [comment]
@briandilley do you mind retesting this with the `0.12.0` release we are going to push today?

**Comment by danielawde9** [comment]
Got same issue navigation stuck trued to use the new release 0.12.0 gave compiling error ill paste the error in a few minutes

**Comment by danesfeder** [comment]
Hey @danielawde9 - if you have the error described in our release notes https://github.com/mapbox/mapbox-navigation-android/releases/tag/0.12.0, please follow the instructions to update to Java 8, thanks!

**Comment by briandilley** [comment]
I'll do another release with it today

**Comment by briandilley** [comment]
![screen shot 2018-04-07 at 2 14 40 pm](https://user-images.githubusercontent.com/1068495/38460423-3e6d8834-3a6e-11e8-9f2b-98aec49a7c4c.png)

I'm not able to upgrade because it seems that you're using some java 8 language features somewhere.

**Comment by danesfeder** [comment]
Hey @briandilley, yeah we began some usage of Java 8 in `0.12.0` - check out the release notes if you run into any other trouble https://github.com/mapbox/mapbox-navigation-android/releases/tag/0.12.0

**Comment by danesfeder** [comment]
Hey @briandilley, I'm going to go ahead and close this - if you are still able to produce with our latest release, please feel free to re-open and we will investigate further together.  Thanks!

**Comment by navdeepg** [comment]
Hey Team,

I am on version 0.22.0 and still face this issue sometime. Especially if I am in the building when the navigation view gets initialized.  It starts working if I reinitialize it while moving. Please let me know if i can do something about this.

Thanks,
Navdeep

**Comment by danesfeder** [comment]
Hey @navdeepg we recently saw some issues with the `LocationEngine`s we were using with `NavigationView` - seeing a delay in initial updates as the location service "warmed up".

Can you retest with the code from [`FusedLocationEngine`](https://github.com/mapbox/mapbox-navigation-android/blob/master/app/src/main/java/com/mapbox/services/android/navigation/testapp/activity/location/FusedLocationEngine.java)?  This is using the latest fused location provider from Google and has proved more reliable.  You can give it to the `NavigationView` with `NavigationViewOptions#locationEngine(LocationEngine)`

The upstream library we use for location services, `location-core`, has just been updated so this should no longer be an issue when we pull in those changes (hopefully ASAP).  Thanks!
