### ISSUE TITLE
NavigationView cancelBtn doesn't close navigationView and navigation notification

### ISSUE THREAD

**Issue by m-harisqurashi** [mapbox/mapbox-navigation-android#677]
While using `NavigationView` if we cancel navigation it does't work as expected. It doesn't cancel/hide the `NavigationView` and neither stops the foreground notification.

```
cancelBtn.setOnClickListener(new View.OnClickListener() {
      @Override
      public void onClick(View view) {
        navigationPresenter.onCancelBtnClick();
        navigationViewEventDispatcher.onCancelNavigation();
      }
    });
```

It should hide/close the `NavigationView` and should call the (same) method call sequence inside `onDestroy ` so that Navigation foreground notification and view close.

  ```
public void onDestroy() {
    mapView.onDestroy();
    navigationViewModel.onDestroy();
    InstructionLoader.getInstance().shutdown();
  }
```

**Comment by danesfeder** [comment]
Hey @m-harisqurashi, how are you using the navigation UI?  With `NavigationLauncher`?

**Comment by m-harisqurashi** [comment]
We are using `NavigationView.startNavigation(navigationViewOptions)` with build number 0.9.0.

**Comment by danesfeder** [comment]
@m-harisqurashi Are you calling `NavigationView#onDestroy`?  In the `Fragment` or `Activity` that's inflating it?

**Comment by m-harisqurashi** [comment]
Yes i'm but problem is that when i click on `NavigatonView`'s cancel button, it does nothing but when i destroy Fragment t works fine. Problem is that when we click on cancel button it only calls `onNavigationFinished `and `onNivigatonCanceled `.

**Comment by m-harisqurashi** [comment]
@danesfeder any update on this issue?

**Comment by nsuryanarayanareddyn** [comment]
I am also facing same issue. I can able to hide this button.

**Comment by danesfeder** [comment]
With the `NavigationView` implementation, you must add a [`NavigationListener`](https://github.com/mapbox/mapbox-navigation-android/blob/master/libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/NavigationActivity.java#L77) to the `NavigationViewOptions` prior to `NavigationView#startNavigation`

https://github.com/mapbox/mapbox-navigation-android/blob/master/libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/NavigationActivity.java#L89-L91

This listener will let you hook into when this `X` button is clicked and you can choose to do as you wish.  In this case, it sounds like `Activity#finish`

**Comment by nsuryanarayanareddyn** [comment]
Thank you, the cancel button works well...

**Comment by m-harisqurashi** [comment]
@danesfeder `cancelBtn` works well but if we implement callbacks in `Activity `and `Fragment` but it doesn't close ongoing notification and navigation voice playback. 
It should do the following
```
mapView.onDestroy();
navigationViewModel.onDestroy();
InstructionLoader.getInstance().shutdown();
```

**Comment by danesfeder** [comment]
@m-harisqurashi are you calling? https://github.com/mapbox/mapbox-navigation-android/blob/master/libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/NavigationActivity.java#L68-L72

**Comment by m-harisqurashi** [comment]
Its works fine for the first time, when i try to start navigation with same `NavigationView` it does nothing.

**Comment by m-harisqurashi** [comment]
@danesfeder any update on this issue, this is critical for our project

**Comment by danesfeder** [comment]
@m-harisqurashi your `Activity` or `Fragment` that inflates the `NavigationView` needs to implement `NavigationListener` and then you need to pass the listener to `NavigationViewOptions` when you call `NavigationView#startNavigation`

We do this in the `NavigationActivity` that is used with `NavigationLauncher`:
-  https://github.com/mapbox/mapbox-navigation-android/blob/master/libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/NavigationActivity.java#L25
- https://github.com/mapbox/mapbox-navigation-android/blob/master/libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/NavigationActivity.java#L88-L103
-  https://github.com/mapbox/mapbox-navigation-android/blob/master/libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/NavigationActivity.java#L77-L84

**Comment by m-harisqurashi** [comment]
Let me tell your our `NavigationView` implementation. We've added a `NavigationView` as a view component in our Fragment. We want to start Navigation by clicking on navigation button, for any reason user can close this navigation so we are closing/destroying `NavigationView` whereas our `Fragment` remains opens. Here when we try to release `NavigationView `via `NavigationListener` app crashes naively. And for some reason if app doesn't crash and we try to start navigation again app definitely crashes as we are using already added and later destroyed our `NavigationView`.

@danesfeder you are right in your comment for issue #675.

**Comment by danesfeder** [comment]
@m-harisqurashi Going to close this as it sounds like this issue is not related to the OP can be now tracked with #675.  Please feel to reopen if you feel otherwise.
