### ISSUE TITLE
Localize banners

### ISSUE THREAD

**Issue by cammace** [mapbox/mapbox-navigation-android#692]
_Originally opened by @daniel-j-h_

Similar to our units _always_ being in miles and feet at the moment, our banners always assume we're in the US. Check out the screenshots below from a route I took over the weekend in germany, the Mapillary dashcam images and the OpenStreetMap data.

Here is the motorway junction node with the ref you see in the screenshow below:
http://www.openstreetmap.org/node/249160021

And this is the way splitting off at the motorway junction from which we use the destination information:
http://www.openstreetmap.org/way/23083649

Here's how that looks like in app:

![screenshot_20171125-142402](https://user-images.githubusercontent.com/527241/33264747-2d6ddd2e-d36f-11e7-94b8-47541bdfb82c.jpg)

And here's a good dash cam imagery sequence of what you will actually see:

https://www.mapillary.com/app/?lat=49.55441880000001&lng=10.992495700000063&z=17&focus=photo&pKey=JwqfISTS2BrpUpa33SBpoQ

Note how you will see the exit number `35` once but then never again:

![map05](https://user-images.githubusercontent.com/527241/33265871-abd15a02-d373-11e7-8214-2d15ef1c1567.png)

![map04](https://user-images.githubusercontent.com/527241/33265838-77386010-d373-11e7-9035-b019c9d94aee.png)

![map06](https://user-images.githubusercontent.com/527241/33265901-bd092e58-d373-11e7-8c07-2cfa57f06a7f.png)

![map07](https://user-images.githubusercontent.com/527241/33265946-eb62d254-d373-11e7-86ef-d065dcbaec0b.png)

![map08](https://user-images.githubusercontent.com/527241/33265950-ee7c9e48-d373-11e7-9310-55ff616e196e.png)

For this navigation and particular route I can see two issues:
- We should not use exit numbers as prominent reference for an exit in Germany. Exit numbers in Germany don't work like exit numbers in the US.
- Why do we show the next instruction and _the one after it_ when I still have 30 miles to drive? Should we tell the user to continue for 30 miles here and then only a couple miles before the exit switch to the instructions you can see in the screenshot above?

**Comment by danesfeder** [comment]
This should be improved now that:
- Banners instructions come from the API 
- The "then" banner shows only with 70 seconds remaining on a step also opened #696 
- And you can change the units in the UI :)

**Comment by daniel-j-h** [comment]
Yay thank you! 🎉
