### ISSUE TITLE
DropInUi : Custom voice player plays different voice

### ISSUE THREAD

**Issue by Sridhar261990** [mapbox/mapbox-navigation-android#6934]
Hello Team,

I am using mapbox DropInUI in my app. I have used the below line of code to play the custom information.

`binding.navigationView.api.getCurrentVoiceInstructionsPlayer()?.play(
                SpeechAnnouncement.Builder("This is a test voice instruction").build()
            ) {
                // no op
            }`

As I am only sending the text message, the play method consider that as as a TextToSpeech. I think because of that I am getting a sharp voice instead of normal voice. I tried debugging when mapbox plays a normal instruction and it has media file along with the announcement,ssmlAnnouncement and distanceAlongGeometry. Is this possible I can play the custom messages in the same default way?

Please check it and let me know how to solve this.

https://user-images.githubusercontent.com/95765713/217604257-63f669d3-b7bd-4cd8-a784-9ab7fcf9f430.mp4

** implementation 'com.mapbox.navigation:ui-app:2.10.1'
    implementation 'com.mapbox.navigation:ui-dropin:2.10.1'**
.

**Comment by EricGeiler** [comment]
pretty sure Sridhar is referring to the default TTS voice player as the "sharp pitched voice" or low-bandwidth speech synth.

1.  Requirement is that we announce incidents as the driver approaches the incident from `mapbox.mapbox-incidents-v2-beta` by using the "Description" property value as the text to pass to the speech player.

2. Requirement is that we announce route violations obtained via below beta access we have been provided, I've asked @Sridhar261990 to pass the `message` value to the speech player as well.

![image](https://user-images.githubusercontent.com/61550186/217641645-f7d28d18-b0b5-4336-b876-e194ab68a210.png)


I'd really like to hear these announced in the same high-bandwidth voice used within Mapbox.

**Comment by Sridhar261990** [comment]
Hi Team, Do we have any update?

**Comment by EricGeiler** [comment]
@Guardiola31337 Are you the mapbox speech / voice guru? I see you've worked on some voice related pr's previously.  If you aren't the right guru can you tag someone to assist my developer pls n thx.

**Comment by EricGeiler** [comment]
@abhishek1508 Can I get a quick response to point us in the right direction for this issue we are facing?

**Comment by dzinad** [comment]
While the feature is in private beta, there is no support from the NavSDK side.
However, if you know the moment when you want to play the instruction, you can do the following:
```
    private val speechCallback =
        MapboxNavigationConsumer<Expected<SpeechError, SpeechValue>> { expected ->
            expected.fold(
                { _ -> },
                { value ->
                    voiceInstructionsPlayer.play(
                        value.announcement,
                        voiceInstructionsPlayerCallback
                    )
                }
            )
        }
    ...        
    speechApi.generate(
        VoiceInstructions.builder().announcement("My message").build(),
        speechCallback
    )
```
So you may basically use the same mechanism as with voice instructions. The difference is that you have to create the `VoiceInstructions` object yourself. Therefore you probably won't be able to pass an ssml announcement, but you can try it our with regular text announcement.
With this approach the following things will happen:
1. NavSDK receives `speechApi.generate` invocation;
2. NavSDK tries to download the corresponding file;
3. It invokes the speechCallback with the download result;
4. You play the result via `MapboxVoiceInstructionsPlayer`: either a file, if it was downloaded successfully, or a TTS engine (the sharp-pitched voice you don't like), if it failed.

Just keep in mind that the underlying network request will be done once you invoke `speechApi.generate`. If the connectivity is low, it may take a while.

**Comment by EricGeiler** [comment]
@dzinad Thank you for the info!!!! I'll make sure @Sridhar261990 sees this and does his best to make it work the way I'm hoping it will.
