### ISSUE TITLE
Zooming out shows end of the world

### ISSUE THREAD

**Issue by cammace** [mapbox/mapbox-navigation-android#698]
_Originally reported by @daniel-j-h_

OnePlus 3T

Zooming out shows the end of the world - we probably should pan around. At the same time when zooming out that far and starting navigation the screen flickers really heavily because it's zooming in really fast.

![screenshot_20171030-122134](https://user-images.githubusercontent.com/527241/32188347-ed43dfc0-bd7d-11e7-8fa1-cd221f7499b9.jpg)

**Comment by danesfeder** [comment]
Fixed with #679
