### ISSUE TITLE
Navigation notification should show correct information and end navigation when tapped

### ISSUE THREAD

**Issue by Guardiola31337** [mapbox/mapbox-navigation-android#713]
- We should revisit/refactor [`MapboxNavigationNotification`](https://github.com/mapbox/mapbox-navigation-android/blob/master/libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/MapboxNavigationNotification.java) (a foreground service like [`NavigationService`](https://github.com/mapbox/mapbox-navigation-android/blob/master/libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/NavigationService.java)  must provide a notification for the status bar) which in some situations is displaying nothing (note 👇 before expanding the notification) and also there are some functionalities (e.g. `END NAVIGATION`) not working 👀

![nav-service-notification](https://user-images.githubusercontent.com/1668582/36443867-42c2513e-167a-11e8-89bc-1b91432063b9.gif)

cc/ @danesfeder @devotaaabel

**Comment by Guardiola31337** [comment]
Remember to take into account https://github.com/mapbox/mapbox-navigation-android/pull/805#pullrequestreview-107394570
> One thing that's we also have to look at here is `MapboxNavigationNotification` which also uses `TimeUtils#formatArrivalTime`. We might have to move the `timeFormatType` to `MapboxNavigationOptions` so it can be used for both the core + UI libraries. The notification is currently created in the core library for the `NavigationService`

and https://github.com/mapbox/mapbox-navigation-android/pull/805#issuecomment-376819342
> Yeah, I noticed as well. BTW I think we should do that (consolidate `TimeUtils#formatArrivalTime` and `TimeUtils#formatTime` methods and use only one of them across the SDK) when we tackle https://github.com/mapbox/mapbox-navigation-android/issues/713 i.e. in a different PR.

when tackling OP.

**Comment by Danny-James** [comment]
@Guardiola31337 May I Ask How You Have The Speed Limit Showing, This is a Feature I Requested A While Back, For This To Be Available In `NavigationLauncher` #529

**Comment by devotaaabel** [comment]
Also, I believe there should be behavior when clicking the whole notification, i.e., reopening the app.
