### ISSUE TITLE
Clean test app examples

### ISSUE THREAD

**Issue by Guardiola31337** [mapbox/mapbox-navigation-android#714]
Found some issues in the test `app` examples that would be great to fix 👀

- The [layout](https://github.com/mapbox/mapbox-navigation-android/blob/master/app/src/main/res/layout/activity_navigation_view.xml#L22-L52) located at the top of the [`NavigationViewActivity`](https://github.com/mapbox/mapbox-navigation-android/blob/master/app/src/main/java/com/mapbox/services/android/navigation/testapp/activity/navigationui/NavigationViewActivity.java) hides the compass when rotating the map 👀

![compas-hidden](https://user-images.githubusercontent.com/1668582/36445985-20bb7434-1680-11e8-9111-fcb92c13106a.png)

- The `Snackbar` shown when [`MockNavigationActivity`](https://github.com/mapbox/mapbox-navigation-android/blob/master/app/src/main/java/com/mapbox/services/android/navigation/testapp/activity/MockNavigationActivity.java) is launched hides the FAB momentarily 👀

![fab-hidden-snackbar](https://user-images.githubusercontent.com/1668582/36446196-de5f3d4a-1680-11e8-9fad-19fa4549813a.png)

- It's not clear what is the functionality behind the `X` FAB included in [`NavigationMapRouteActivity`](https://github.com/mapbox/mapbox-navigation-android/blob/master/app/src/main/java/com/mapbox/services/android/navigation/testapp/activity/navigationui/NavigationMapRouteActivity.java) 👀

- The `SummaryBottomSheet` animation gets stopped when a gesture occurs which makes the animation feels jumpy in those cases 👀

![summary-animation-jumpy](https://user-images.githubusercontent.com/1668582/36447719-7f877ae4-1685-11e8-8e9e-d14e78aaa7b7.gif)

- Found some leaks reported by [LeakCanary](https://github.com/square/leakcanary) which should be fixed.

cc/ @danesfeder @devotaaabel

**Comment by Guardiola31337** [comment]
- `NavigationViewActivity` (name) isn't very descriptive because it doesn't actually inflate a `NavigationView` it uses `NavigationLauncher`.

**Comment by Guardiola31337** [comment]
> - The `SummaryBottomSheet` animation gets stopped when a gesture occurs which makes the animation feels jumpy in those cases 👀

![summary-animation-jumpy](https://user-images.githubusercontent.com/1668582/36447719-7f877ae4-1685-11e8-8e9e-d14e78aaa7b7.gif)

It's fixed in https://github.com/mapbox/mapbox-navigation-android/pull/959/commits/4213ed62f0cb127bcf40c6138d59776394920131 thanks to the new gestures library 🎉 

cc @LukasPaczos

**Comment by Guardiola31337** [comment]
> It's fixed in https://github.com/mapbox/mapbox-navigation-android/pull/959/commits/4213ed62f0cb127bcf40c6138d59776394920131 thanks to the new gestures library 🎉 

![summary_bottom_sheet_animation_fixed](https://user-images.githubusercontent.com/1668582/40509999-8d1ab7ac-5f9b-11e8-8cde-a1e73a0ea331.gif)

**Comment by devotaaabel** [comment]
See comments on #965 for more issues

**Comment by devotaaabel** [comment]
- I think this is an issue as well? Should the banner height be the same the whole width?
![device-2018-06-01-144826](https://user-images.githubusercontent.com/14295757/40858147-5d02e84e-65ab-11e8-9ec1-86709e2b7d62.png)

- Recenter button doesn't hide when instruction view is showing
![device-2018-06-01-145146](https://user-images.githubusercontent.com/14295757/40858182-809b5b7e-65ab-11e8-9366-7bcf7f7420f0.png)

**Comment by danesfeder** [comment]
This was tackled in multiple PRs, thanks @devotaaabel!

**Comment by danesfeder** [comment]
@Guardiola31337 pointed out not all of these are tackled - reopening.
