### ISSUE TITLE
NavigationActivity not found error while launching navigation from activity.

### ISSUE THREAD

**Issue by vishalkharat** [mapbox/mapbox-navigation-android#716]
While launching NavigationLauncher from Activity its throwing following error:

E/AndroidRuntime: FATAL EXCEPTION: main
                                                           Process: com.testapp, PID: 24590
                                                           android.content.ActivityNotFoundException: Unable to find explicit activity class {com.testapp/com.mapbox.services.android.navigation.ui.v5.NavigationActivity}; have you declared this activity in your AndroidManifest.xml?
                                                               at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1896)
                                                               at android.app.Instrumentation.execStartActivity(Instrumentation.java:1590)
                                                               at android.app.Activity.startActivityForResult(Activity.java:3972)
                                                               at android.support.v4.app.BaseFragmentActivityApi16.startActivityForResult(BaseFragmentActivityApi16.java:54)
                                                               at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:67)
                                                               at android.app.Activity.startActivityForResult(Activity.java:3924)
                                                               at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:732)
                                                               at android.app.Activity.startActivity(Activity.java:4267)
                                                               at android.app.Activity.startActivity(Activity.java:4235)
                                                               at com.mapbox.services.android.navigation.ui.v5.NavigationLauncher.startNavigation(NavigationLauncher.java:57)
                                                               at com.testapp.views.activities.MapboxActivity$1$2.onClick(MapboxActivity.java:141)
                                                               at android.view.View.performClick(View.java:5268)
                                                               at android.view.View$PerformClick.run(View.java:21550)
                                                               at android.os.Handler.handleCallback(Handler.java:822)
                                                               at android.os.Handler.dispatchMessage(Handler.java:104)
                                                               at android.os.Looper.loop(Looper.java:207)
                                                               at android.app.ActivityThread.main(ActivityThread.java:5811)
                                                               at java.lang.reflect.Method.invoke(Native Method)
                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:791)
                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:681)

**build.gradle**

compile ('com.mapbox.mapboxsdk:mapbox-android-sdk:5.4.1@aar'){
        transitive=true
    }
    compile ('com.mapbox.mapboxsdk:mapbox-android-geocoder:1.0.0@aar'){
        transitive=true
    }
    compile 'com.mapbox.mapboxsdk:mapbox-android-navigation:0.9.0'
    compile ('com.mapbox.mapboxsdk:mapbox-android-navigation-ui:0.9.0') {
        transitive = true
    }

**Comment by danesfeder** [comment]
Hey @vishalkharat, do you mind sharing a code snippet where you are using `NavigationActivity`?

**Comment by vishalkharat** [comment]
NavigationLauncher.startNavigation(MapboxActivity.this, options);
using above code in following Activity on button click event

public class MapboxActivity extends AppCompatActivity implements LocationEngineListener, PermissionsListener {

    private MapView mapView;

    // variables for adding location layer
    private MapboxMap map;
    private PermissionsManager permissionsManager;
    private LocationLayerPlugin locationPlugin;
    private LocationEngine locationEngine;
    private Location originLocation;

    // variables for adding a marker
    private Marker destinationMarker;
    private LatLng originCoord;
    private LatLng destinationCoord;

    // variables for calculating and drawing a route
    private Point originPosition;
    private Point destinationPosition;
    private DirectionsRoute currentRoute;
    private static final String TAG = "DirectionsActivity";
    private NavigationMapRoute navigationMapRoute;

    private Button button;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        Mapbox.getInstance(this, "pk.eyJ1IjoiZ2lyaXNoMTIzNCIsImEiOiJjamRmaXA4bDEwOGx3MnhtbTlyeHE2MG5vIn0.SSFQrHjzH4L4OqsegEr7-Q");
        setContentView(R.layout.activity_main);
        mapView = (MapView) findViewById(R.id.mapView);
        mapView.onCreate(savedInstanceState);
        // Add user location to the map
        mapView.getMapAsync(new OnMapReadyCallback() {
            @Override
            public void onMapReady(final MapboxMap mapboxMap) {
                map = mapboxMap;
                enableLocationPlugin();
                if(originLocation != null) {
                    originCoord = new LatLng(originLocation.getLatitude(), originLocation.getLongitude());
                }
                Log.d("onMapReady", "onMapReady");

                map.addOnMapClickListener(new MapboxMap.OnMapClickListener() {
                    @Override
                    public void onMapClick(@NonNull LatLng point) {

                        if (destinationMarker != null) {
                            mapboxMap.removeMarker(destinationMarker);
                        }

                        destinationCoord = point;

                        destinationMarker = mapboxMap.addMarker(new MarkerOptions()
                                .position(destinationCoord)
                        );

                        destinationPosition = Point.fromLngLat(destinationCoord.getLongitude(), destinationCoord.getLatitude());
                        if(originLocation != null) {
                            originCoord = new LatLng(originLocation.getLatitude(), originLocation.getLongitude());
                        }
                        originPosition = Point.fromLngLat(originCoord.getLongitude(), originCoord.getLatitude());
                        getRoute(originPosition, destinationPosition);
                        button.setEnabled(true);
                        button.setBackgroundColor(Color.parseColor("#ffffff"));
                    }

                });
                button = findViewById(R.id.startButton);
                button.setOnClickListener(new View.OnClickListener() {
                    public void onClick(View v) {
                        Point origin = originPosition;
                        Point destination = destinationPosition;

                        // Pass in your Amazon Polly pool id for speech synthesis using Amazon Polly
                        // Set to null to use the default Android speech synthesizer
                        String awsPoolId = null;

                        boolean simulateRoute = true;

                        NavigationViewOptions options = NavigationViewOptions.builder()
                                .origin(origin)
                                .destination(destination)
                                .awsPoolId(awsPoolId)
                                .shouldSimulateRoute(simulateRoute)
                                .build();

                        // Call this method with Context from within an Activity
                        NavigationLauncher.startNavigation(MapboxActivity.this, options);
                    }
                });
            }
        });

    }

    @Override
    protected void onActivityResult(int requestCode, int resultCode, Intent data) {
        super.onActivityResult(requestCode, resultCode, data);
    }

    private void getRoute(Point origin, Point destination) {
        NavigationRoute.builder()
                .accessToken(Mapbox.getAccessToken())
                .origin(origin)
                .destination(destination)
                .build()
                .getRoute(new Callback<DirectionsResponse>() {
                    @Override
                    public void onResponse(Call<DirectionsResponse> call, Response<DirectionsResponse> response) {
                        // You can get the generic HTTP info about the response
                        Log.d(TAG, "Response code: " + response.code());
                        if (response.body() == null) {
                            Log.e(TAG, "No routes found, make sure you set the right user and access token.");
                            return;
                        } else if (response.body().routes().size() < 1) {
                            Log.e(TAG, "No routes found");
                            return;
                        }

                        currentRoute = response.body().routes().get(0);

                        // Draw the route on the map
                        if (navigationMapRoute != null) {
                            navigationMapRoute.removeRoute();
                        } else {
                            navigationMapRoute = new NavigationMapRoute(null, mapView, map, R.style.NavigationMapRoute);
                        }
                        navigationMapRoute.addRoute(currentRoute);
                    }

                    @Override
                    public void onFailure(Call<DirectionsResponse> call, Throwable throwable) {
                        Log.e(TAG, "Error: " + throwable.getMessage());
                    }
                });
    }


    @SuppressWarnings({"MissingPermission"})
    private void enableLocationPlugin() {
        // Check if permissions are enabled and if not request
        if (PermissionsManager.areLocationPermissionsGranted(this)) {
            // Create an instance of LOST location engine
            initializeLocationEngine();

            locationPlugin = new LocationLayerPlugin(mapView, map, locationEngine);
            locationPlugin.setLocationLayerEnabled(LocationLayerMode.TRACKING);
        } else {
            permissionsManager = new PermissionsManager(this);
            permissionsManager.requestLocationPermissions(this);
        }
    }

    @SuppressWarnings({"MissingPermission"})
    private void initializeLocationEngine() {
//        locationEngine = new LostLocationEngine(MapboxActivity.this);
        locationEngine = new GoogleLocationEngine(MapboxActivity.this);
        locationEngine.setPriority(LocationEnginePriority.HIGH_ACCURACY);
        locationEngine.activate();

        Location lastLocation = locationEngine.getLastLocation();
        if (lastLocation != null) {
            originLocation = lastLocation;
            setCameraPosition(lastLocation);
        } else {
            locationEngine.addLocationEngineListener(this);
        }
    }

    private void setCameraPosition(Location location) {
        map.animateCamera(CameraUpdateFactory.newLatLngZoom(
                new LatLng(location.getLatitude(), location.getLongitude()), 13));
    }

    @Override
    public void onRequestPermissionsResult(int requestCode, @NonNull String[] permissions, @NonNull int[] grantResults) {
        permissionsManager.onRequestPermissionsResult(requestCode, permissions, grantResults);
    }

    @Override
    public void onExplanationNeeded(List<String> permissionsToExplain) {

    }

    @Override
    public void onPermissionResult(boolean granted) {
        if (granted) {
            enableLocationPlugin();
        } else {
            finish();
        }
    }

    @Override
    @SuppressWarnings({"MissingPermission"})
    public void onConnected() {
        locationEngine.requestLocationUpdates();
    }

    @Override
    public void onLocationChanged(Location location) {
        if (location != null) {
            Toast.makeText(this, "onLocationChanged", Toast.LENGTH_SHORT).show();
            originLocation = location;
            setCameraPosition(location);
            locationEngine.removeLocationEngineListener(this);
        }
    }

    @Override
    @SuppressWarnings({"MissingPermission"})
    protected void onStart() {
        super.onStart();
        if (locationEngine != null) {
            locationEngine.requestLocationUpdates();
        }
        if (locationPlugin != null) {
            locationPlugin.onStart();
        }
        mapView.onStart();
    }

    @Override
    protected void onStop() {
        super.onStop();
        if (locationEngine != null) {
            locationEngine.removeLocationUpdates();
        }
        if (locationPlugin != null) {
            locationPlugin.onStop();
        }
        mapView.onStop();
    }

    @Override
    protected void onDestroy() {
        super.onDestroy();
        mapView.onDestroy();
        if (locationEngine != null) {
            locationEngine.deactivate();
        }
    }

    @Override
    public void onLowMemory() {
        super.onLowMemory();
        mapView.onLowMemory();
    }

    @Override
    protected void onResume() {
        super.onResume();
        mapView.onResume();
    }

    @Override
    protected void onPause() {
        super.onPause();
        mapView.onPause();
    }

    @Override
    protected void onSaveInstanceState(Bundle outState) {
        super.onSaveInstanceState(outState);
        mapView.onSaveInstanceState(outState);
    }
}

**Comment by danesfeder** [comment]
Hey @vishalkharat, unfortunately I'm not able to discern your issue from the code snippets provided.  If you're able to narrow down the exact cause of your issue within our SDK, please feel free to open another ticket. Thanks!
