### ISSUE TITLE
MapBox navigation dependency failed to resolve in kotlin

### ISSUE THREAD

**Issue by ehtshamaziz** [mapbox/mapbox-navigation-android#7198]
I try to sync my mapbox navigation dependency but it give me following error:
Failed to resolve: com.mapbox.navigator:mapbox-navigation-native:6.2.1

I have tried many version but it still gives same error.
By adding the following dependency 
   implementation ('com.mapbox.mapboxsdk:mapbox-android-navigation:0.20.0'){
        exclude group: 'com.mapbox.navigator'
    }

it gives resolve the issue but when i start the navigation using  "NavigationLauncher.startNavigation(this, navigationLauncherOptions) " my app crashes and gives me "Failed resolution of: Lcom/mapbox/navigator/Navigator;".

**Comment by DzmitryFomchyn** [comment]
@ehtshamaziz the latest Navigation SDK version is https://github.com/mapbox/mapbox-navigation-android/releases/tag/v2.13.1, and Maps SDK version https://github.com/mapbox/mapbox-maps-android/releases/tag/v10.13.0

Use these versions.
