### ISSUE TITLE
NavigationCamera package private ??

### ISSUE THREAD

**Issue by vladgheorghe** [mapbox/mapbox-navigation-android#725]
I just checked out the new 0.10.0 release and I have noticed that NavigationCamera is now package private. This breaks my build as I have a custom implementation of the sdk where the user can choose when to lock the camera in navigation, am I missing something ? Modified [here](https://github.com/mapbox/mapbox-navigation-android/commit/860f270d87bb565177c15becfacea7b237874525)

**Comment by danesfeder** [comment]
@vladgheorghe Yeah, this was on us.  https://github.com/mapbox/mapbox-navigation-android/pull/679 will land this week and make it `public` again and I'm planning a `0.10.1` patch release before the week is over.  Sorry about that!

**Comment by danesfeder** [comment]
Closed with #679
