### ISSUE TITLE
Custom NavigationView cancelBtn doesn't close navigationView and not translated expected arrival time

### ISSUE THREAD

**Issue by nsuryanarayanareddyn** [mapbox/mapbox-navigation-android#727]
Hello Team,

I am implementing turn by turn navigation in one of our project and I am using NavigationView with an Activity. When I click on cancel button it does not close the activity.

please find the attached screen shot.
![navigationview_close](https://user-images.githubusercontent.com/4735046/36841058-1449ac2c-1d6d-11e8-9c4b-86f7e32dff09.png)

I would like to support for multiple languages, the expected arrival time is not translated. I would like to support for Italian Language.

Code I am using in my  @activity:
  ImageButton mClose = (ImageButton) findViewById( R.id.cancelBtn );
 mClose.setOnClickListener( new View.OnClickListener() {
            @Override
            public void onClick(View view) {
             finish();
            }
        } );
  Thanks in advance....

@danesfeder @langsmith

**Comment by danesfeder** [comment]
@nsuryanarayanareddyn Please see https://github.com/mapbox/mapbox-navigation-android/issues/677#issuecomment-369605916 regarding the the cancel button not closing the view. 

As far at the ETA localization, we do need to provide an option for 12 / 24hr time display if that's what you mean?  In this case it would read `16:04`?

**Comment by nsuryanarayanareddyn** [comment]
@danesfeder  Hi Thank you for your reply , yes I am looking out 24hr time format. When can we expect this change.

Thanks in advance...

**Comment by danesfeder** [comment]
Thanks @nsuryanarayanareddyn.  This isn't in our immediate pipeline of work, but I opened a ticket to begin tracking the work:
https://github.com/mapbox/mapbox-navigation-android/issues/740
