### ISSUE TITLE
Voice instructions not translating as per device language  

### ISSUE THREAD

**Issue by nsuryanarayanareddyn** [mapbox/mapbox-navigation-android#736]
Hello Team,

I am building turn by turn navigation app and I need to provide for different countries. The voice instructions are not translating as per device language. 

Here I am passing Locale 
  NavigationViewOptions.Builder optionsBuilder = NavigationViewOptions.builder()
                                .shouldSimulateRoute( simulateRoute );
                        optionsBuilder.directionsRoute( currentRoute );
                        optionsBuilder.navigationOptions( options1 );
                        optionsBuilder.awsPoolId( null );
                        if (MainActivity.getUserLang().equalsIgnoreCase( "en" )) {
                            optionsBuilder.directionsLanguage( Locale.ENGLISH );
                        } else if (MainActivity.getUserLang().equalsIgnoreCase( "fr" )) {
                            optionsBuilder.directionsLanguage( Locale.FRENCH );
                        } else if (MainActivity.getUserLang().equalsIgnoreCase( "es" )) {
                            optionsBuilder.directionsLanguage( Locale.FRANCE );
                        } else if (MainActivity.getUserLang().equalsIgnoreCase( "de" )) {
                            optionsBuilder.directionsLanguage( Locale.GERMAN );
                        } else if (MainActivity.getUserLang().equalsIgnoreCase( "id" )) {
                            optionsBuilder.directionsLanguage( Locale.ITALIAN );
                        } else {
                            optionsBuilder.directionsLanguage( Locale.ENGLISH );
                        }

                        optionsBuilder.navigationListener( CaraMapsNavigation.this );

                        navigationView.startNavigation( optionsBuilder.build() );
if I change my device language the voice instructions does not playing.
could you please suggest me , If I am missing any configuration.
Thanks in advance..

 

@danesfeder 
@Yuffster

**Comment by danesfeder** [comment]
Hey @nsuryanarayanareddyn, which version of the SDK are you using?  In `0.10.0`, the `Locale` for the instruction pronunciation is actually done with `MapboxNavigationOptions#locale`, sorry for the confusion here. 

@devotaaabel can you confirm this is the issue here?  I believe you removed `NavigationViewOptions#directionsLanguage` in your instruction locale work.

**Comment by nsuryanarayanareddyn** [comment]
Hello @danesfeder  Thank you for your quick reply, I am using 0.9.0 and setting the locale as bellow.

 NavigationViewOptions.Builder optionsBuilder = NavigationViewOptions.builder()
                                .shouldSimulateRoute( simulateRoute );
                        optionsBuilder.directionsRoute( currentRoute );
                        optionsBuilder.navigationOptions( options1 );
                        optionsBuilder.awsPoolId( null );
                        if (MainActivity.getUserLang().equalsIgnoreCase( "en" )) {
                            optionsBuilder.directionsLanguage( Locale.ENGLISH );
                        } else if (MainActivity.getUserLang().equalsIgnoreCase( "fr" )) {
                            optionsBuilder.directionsLanguage( Locale.FRENCH );
                        } else if (MainActivity.getUserLang().equalsIgnoreCase( "es" )) {
                            optionsBuilder.directionsLanguage( Locale.FRANCE );
                        } else if (MainActivity.getUserLang().equalsIgnoreCase( "de" )) {
                            optionsBuilder.directionsLanguage( Locale.GERMAN );
                        } else if (MainActivity.getUserLang().equalsIgnoreCase( "id" )) {
                            optionsBuilder.directionsLanguage( Locale.ITALIAN );
                        } else {
                            optionsBuilder.directionsLanguage( Locale.ENGLISH );
                        }

                        optionsBuilder.navigationListener( CaraMapsNavigation.this );


                        navigationView.startNavigation( optionsBuilder.build() );

I tried to change SDK to  0.10.0 Here  NavigationViewOptions#directionsLanguage is not available.
plese suggest me...

**Comment by danesfeder** [comment]
@nsuryanarayanareddyn yes in `0.10.0` you can use `MapboxNavigationOptions#locale` and then pass it to `NavigationViewOptions#navigationOptions`:

```
MapboxNavigationOptions.Builder navigationOptions = MapboxNavigationOptions.builder();
if (MainActivity.getUserLang().equalsIgnoreCase( "en" )) {
    navigationOptions.locale( Locale.ENGLISH );
} else if (MainActivity.getUserLang().equalsIgnoreCase( "fr" )) {
    navigationOptions.locale( Locale.FRENCH );
} else if (MainActivity.getUserLang().equalsIgnoreCase( "es" )) {
    navigationOptions.locale( Locale.FRANCE );
} 

...

NavigationViewOptions.Builder optionsBuilder = NavigationViewOptions.builder()
.shouldSimulateRoute( simulateRoute );
optionsBuilder.directionsRoute( currentRoute );
optionsBuilder.navigationOptions( navigationOptions.build() );
```

Let me know if you have more questions 👍

**Comment by Xgamefactory** [comment]
in current version (0.19.0) there is no locale property anymore 
so many old examples out there even https://www.mapbox.com/android-docs/navigation/overview/navigation-ui/ examples not updated very messy.
