### ISSUE TITLE
exclude method does not work for highway's -- while drawing route

### ISSUE THREAD

**Issue by nsuryanarayanareddyn** [mapbox/mapbox-navigation-android#737]
Hi Team,

While I am drawing route , I need to provide an option to user to avoid toll and highway. The exclude method works well in case of toll , but if I pass exclude parameter as "highway" I am getting the following error message.

failed to draw route: java.lang.Throwable: exclude value must be one of  toll, motorway, ferry
bellow code I am using 
 NavigationRoute.builder()
                .accessToken( Mapbox.getAccessToken() )
                .origin( origin )
                .exclude( mExclude )
                .language( locale )
                .destination( destination )
                .build()
mExclude is the parameter I will pass as per user selection like toll/highway.

please suggest me if I am missing any info.
Thanks in advance.....
@danesfeder

**Comment by danesfeder** [comment]
Hey @nsuryanarayanareddyn, the exclude `String` that you're looking for here is https://github.com/mapbox/mapbox-java/blob/master/services-directions/src/main/java/com/mapbox/api/directions/v5/DirectionsCriteria.java#L130.  That will exclude highways while fetching the route

**Comment by kiskunk** [comment]
> Hey @nsuryanarayanareddyn, the exclude `String` that you're looking for here is https://github.com/mapbox/mapbox-java/blob/master/services-directions/src/main/java/com/mapbox/api/directions/v5/DirectionsCriteria.java#L130. That will exclude highways while fetching the route

For me using exclude toll just excludes everything else (alternatives) and leaves highway on. also can exclude be used multiple times? I mean I would like to exclude toll ways and ferrys at the same time?

**Comment by elFallino** [comment]
In Europe there are a lot of toll roads (in Germany, Austria and Swiss called "Maut").
People often want to exclude toll roads when possible. Some may also want to exclude motorways as well.
The app I am using MapBox for is made for electric vehicles and many users want to avoid both, toll roads and motorways.
I hope you can find a way to offer combinations of all excludes.
