### ISSUE TITLE
NavigationViewOptions with .awsPoolId("cognito-id") not working

### ISSUE THREAD

**Issue by baversjo** [mapbox/mapbox-navigation-android#742]
I'm using `com.mapbox.mapboxsdk:mapbox-android-navigation-ui:0.11.0-SNAPSHOT` (as I couldn't get 0.10.0 to work due to the okhttp issue).
I'm launching a separate navigation activity using `NavigationLauncher.startNavigation`.
When I specify `.awsPoolId(null)`, I can hear the default android voice instructions fine (in contrary to #735 ). 
However, when I specify the pool id `.awsPoolId("us-east-1:59...")` I setup in AWS, I no longer hear any instructions. I see these messages in the console about Cognito:

```
03-07 13:50:10.460 8402-10879/com.smrtsystems.mobile D/CognitoCachingCredentialsProvider: Loading credentials from SharedPreferences
03-07 13:50:10.460 8402-10879/com.smrtsystems.mobile D/CognitoCachingCredentialsProvider: No valid credentials found in SharedPreferences
03-07 13:50:10.467 8402-10879/com.smrtsystems.mobile I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
03-07 13:50:10.470 8402-10879/com.smrtsystems.mobile I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
03-07 13:50:10.473 8402-8402/com.smrtsystems.mobile W/art: Attempt to remove non-JNI local reference, dumping thread
03-07 13:50:10.505 8402-8402/com.smrtsystems.mobile D/TextView: setTypeface with style : 0
03-07 13:50:10.528 8402-8402/com.smrtsystems.mobile D/TextView: setTypeface with style : 0
03-07 13:50:10.549 8402-8402/com.smrtsystems.mobile D/TextView: setTypeface with style : 0
03-07 13:50:10.568 8402-8402/com.smrtsystems.mobile D/TextView: setTypeface with style : 0
03-07 13:50:10.580 8402-10879/com.smrtsystems.mobile D/CognitoCachingCredentialsProvider: Identity id is changed
03-07 13:50:10.580 8402-10879/com.smrtsystems.mobile D/CognitoCachingCredentialsProvider: Saving identity id to SharedPreferences
03-07 13:50:10.581 8402-10879/com.smrtsystems.mobile D/CognitoCachingCredentialsProvider: Clearing credentials from SharedPreferences
03-07 13:50:10.586 8402-10879/com.smrtsystems.mobile I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
```
 I've ensured the unauthenticated IAM role Cognito setup has the `AmazonPollyFullAccess` attached.
Any ideas what I'm doing wrong? I see some recent work in this area (#729), is it possible that 0.11 is broken?

**Comment by danesfeder** [comment]
@baversjo Yeah this looks like an issue with the permission of your IAM identity.  I'd check out https://docs.aws.amazon.com/polly/latest/dg/using-identity-based-policies.html and see if you have everything set up correctly for your AWS account.

**Comment by baversjo** [comment]
1 character copy paste typo of key caused this. Sigh.. Thanks @danesfeder

**Comment by danesfeder** [comment]
@baversjo ahh the worst - no problem, thanks for checking out the SDK!
