### ISSUE TITLE
onProgressChange not working

### ISSUE THREAD

**Issue by danesfeder** [mapbox/mapbox-navigation-android#752]
Copied from: https://github.com/mapbox/mapbox-java/issues/745

I have an onProgressChange method that just isn't getting called when my progress is is changing.
This is my code:
`        @Override
        public void onProgressChange (Location location, RouteProgress routeProgress){
            Toast.makeText(getBaseContext(), "Progress changing ", Toast.LENGTH_SHORT).show();
            Toast.makeText(getBaseContext(), "Distance remaining: " + stepDistanceRemaining, Toast.LENGTH_SHORT).show();
            if (stepDistanceRemaining < 50) {
                Log.i(TAG, "NextStepComing");
                sendManeuver(routeProgress);
            }
        }
` 
While troubleshooting i also found that the onLocationChanged method isn't working either.

**Comment by A1ecm** [comment]
I just have this method written. Is that nog enough? Do I have to call it somewhere? I'm using version 5.5.0

**Comment by A1ecm** [comment]
Im also using 'com.mapbox.mapboxsdk:mapbox-android-navigation:0.11.0'

**Comment by danesfeder** [comment]
@A1ecm can you post a code snippet of how you are using the SDK? Thanks!

**Comment by A1ecm** [comment]
I'm just using the standard route and navigation building found in the tutorial:

`

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        Log.i(TAG, "Creating app" + stepDistanceRemaining);
        Mapbox.getInstance(this, "pk.eyJ1IjoiYTFlYyIsImEiOiJjamVhMTJudXoxOGk0MnFudGV2Z3NnMGpwIn0.p9G0Ejx0EGALsmAOJt4ICQ");
        setContentView(R.layout.activity_main);
        mapView = (MapView) findViewById(R.id.mapView);
        mapView.onCreate(savedInstanceState);
        mapView.getMapAsync(new OnMapReadyCallback() {
            @Override
            public void onMapReady(final MapboxMap mapboxMap) {
                map = mapboxMap;
                enableLocationPlugin();
                originCoord = new LatLng(originLocation.getLatitude(), originLocation.getLongitude());


                mapboxMap.addOnMapClickListener(new MapboxMap.OnMapClickListener() {
                    @Override
                    public void onMapClick(@NonNull LatLng point) {

                        if (destinationMarker != null) {
                            mapboxMap.removeMarker(destinationMarker);
                        }

                        destinationCoord = point;

                        destinationMarker = mapboxMap.addMarker(new MarkerOptions()
                                .position(destinationCoord)
                        );
                        destinationPosition = Point.fromLngLat(destinationCoord.getLongitude(), destinationCoord.getLatitude());
                        originPosition = Point.fromLngLat(originCoord.getLongitude(), originCoord.getLatitude());
                        getRoute(originPosition, destinationPosition);
                        button.setEnabled(true);
                        button.setBackgroundResource(R.color.mapboxBlue);

                    };
                });
                button = findViewById(R.id.startButton);
                button.setOnClickListener(new View.OnClickListener() {
                    public void onClick(View v) {
                        Point origin = originPosition;
                        Point destination = destinationPosition;

                        // Pass in your Amazon Polly pool id for speech synthesis using Amazon Polly
                        // Set to null to use the default Android speech synthesizer
                        String awsPoolId = null;

                        boolean simulateRoute = false;

                        NavigationViewOptions options = NavigationViewOptions.builder()
                                .directionsProfile(DirectionsCriteria.PROFILE_CYCLING)
                                .origin(origin)
                                .destination(destination)
                                .awsPoolId(awsPoolId)
                                .shouldSimulateRoute(simulateRoute)
                                .build();

                        // Call this method with Context from within an Activity
                        NavigationLauncher.startNavigation(MainActivity.this, options);
                        Toast.makeText(getBaseContext(), "creating nav " + stepDistanceRemaining, Toast.LENGTH_SHORT).show();

                    }
                });
            };
        });
    }

    private void getRoute(Point origin, Point destination) {
        NavigationRoute.builder()
                .accessToken(Mapbox.getAccessToken())
                .origin(origin)
                .destination(destination)
                .profile(DirectionsCriteria.PROFILE_CYCLING)
                .build()
                .getRoute(new Callback<DirectionsResponse>() {
                    @Override
                    public void onResponse(Call<DirectionsResponse> call, Response<DirectionsResponse> response) {
                        // You can get the generic HTTP info about the response
                        Log.d(TAG, "Response code: " + response.code());
                        if (response.body() == null) {
                            Log.e(TAG, "No routes found, make sure you set the right user and access token.");
                            return;
                        } else if (response.body().routes().size() < 1) {
                            Log.e(TAG, "No routes found");
                            return;
                        }

                        currentRoute = response.body().routes().get(0);

                        // Draw the route on the map
                        if (navigationMapRoute != null) {
                            navigationMapRoute.removeRoute();
                        } else {
                            navigationMapRoute = new NavigationMapRoute(null, mapView, map, R.style.NavigationMapRoute);
                        }
                        navigationMapRoute.addRoute(currentRoute);
                        Log.i(TAG, "Creating route" + stepDistanceRemaining);
                    }

                    @Override
                    public void onFailure(Call<DirectionsResponse> call, Throwable throwable) {
                        Log.e(TAG, "Error: " + throwable.getMessage());
                    }
                });
    }`

**Comment by A1ecm** [comment]
After that i have some initialization and onStart etc classes. And after that i call the onProgressChange method.

**Comment by A1ecm** [comment]
Any progress on a possible answer?

**Comment by Guardiola31337** [comment]
Hey @A1ecm 👋 thanks for reaching out and report your problem.

> Any progress on a possible answer?

This should be fixed by https://github.com/mapbox/mapbox-navigation-android/pull/782 and it'll be included in the next release.

**Comment by Guardiola31337** [comment]
#782 has been merged. @A1ecm feel free to retest once that lands. Thanks for reaching out. Closing.
