### ISSUE TITLE
Android-navigation 0.11.0 crash when trying a second navigation

### ISSUE THREAD

**Issue by Niduank** [mapbox/mapbox-navigation-android#757]
Hi,

Actually, I think Mapbox Navigation SDK was developed in order to do only one navigation.

In my app, when first navigation is over, I launch a second navigation at user's destination.

I have this crash :

`
Fatal Exception: java.util.ConcurrentModificationException
       at java.util.ArrayList$Itr.next(ArrayList.java:831)
       at com.mapbox.services.android.navigation.v5.navigation.NavigationEventDispatcher.onProgressChange(NavigationEventDispatcher.java:156)
       at com.mapbox.services.android.navigation.v5.navigation.NavigationService.onNewRouteProgress(NavigationService.java:114)
       at com.mapbox.services.android.navigation.v5.navigation.NavigationEngine$1.run(NavigationEngine.java:123)
       at android.os.Handler.handleCallback(Handler.java:751)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6776)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
`

Here is my function which reinitialize viewmodels for each different navigation :

        navigationViewModel.getNavigation().endNavigation();
        navigationViewModel.initializeNavigationOptions(getApplicationContext(), mapboxNavigationOptions);
        navigationViewModel.setMuted(true);
        initCamera();
        initNavigationEventDispatcher();
        setupListeners();

        NavigationViewOptions options = NavigationViewOptions.builder()
                .directionsRoute(directionRoute)
                .progressChangeListener(_progressChangeListener)
                .milestoneEventListener(_milestoneListener)
                .navigationListener(_navigationListener)
                .routeListener(_routeListener)
                .navigationOptions(mapboxNavigationOptions)
                .build();

        if (SIMULATION_MODE) {
            locationViewModel.updateShouldSimulateRoute(SIMULATION_MODE);
        }

        initLifecycleObservers();
        routeViewModel.extractRouteOptions(options);

       private void setupListeners() {
        navigationViewEventDispatcher.setLocalPositionListener(this);
        navigationViewEventDispatcher.setFeedbackListener(navigationViewOptions.feedbackListener());
        navigationViewEventDispatcher.setNavigationListener(navigationViewOptions.navigationListener());
        navigationViewEventDispatcher.setRouteListener(navigationViewOptions.routeListener());
        navigationViewEventDispatcher.setBottomSheetCallback(navigationViewOptions.bottomSheetCallback());
        if (navigationViewOptions.progressChangeListener() != null) {
            navigationViewModel.getNavigation().addProgressChangeListener(navigationViewOptions.progressChangeListener());
        }

        if (navigationViewOptions.milestoneEventListener() != null) {
            navigationViewModel.getNavigation().addMilestoneEventListener(navigationViewOptions.milestoneEventListener());
        }
    }

     private void initLifecycleObservers() {
        try {
            this.getLifecycle().addObserver(locationLayer);
            this.getLifecycle().addObserver(locationViewModel);
        } catch (ClassCastException exception) {
            throw new ClassCastException("Please ensure that the provided Context is a valid LifecycleOwner");
        }
    }
`

**Comment by MehdiFal** [comment]
@Niduank I'm not sure about the exception but I found out a few months ago that it only work with 1 navigation session.
The hack I did, was basically to restart the activity with the new address passed.

**Comment by danesfeder** [comment]
Hey @Niduank @MehdiFal thanks for the feedback.  We queued up a fix for this in https://github.com/mapbox/mapbox-navigation-android/pull/762
