### ISSUE TITLE
Change Default Destination marker in - NavigationView

### ISSUE THREAD

**Issue by nsuryanarayanareddyn** [mapbox/mapbox-navigation-android#759]
Dear Team,

I am developing trun by turn navigation by using NavigationView in an Activity, it works well.

I would like to change the destination marker with our own icon, I am unable to change it.

could you please suggest me how can we change it. please check the attached screen.
![destination_marker](https://user-images.githubusercontent.com/4735046/37462275-61ef65b0-2877-11e8-96cd-b028d9952c4b.png)

@danesfeder 
@Yuffster

**Comment by Niduank** [comment]
Hi @nsuryanarayanareddyn 
Maybe you have to implement NavigationContract.View functions
```java
    /**
     * Creates a marker based on the
     * {@link Point} destination coordinate.
     *
     * @param position where the marker should be placed
     */
    @Override
    public void addMarker(Point position) {
       mapboxMap.addMarker(flagMarkerOptions.setPosition(new LatLng(getDestinationLocation().getLatitude(), getDestinationLocation().getLongitude())));
    }
```

**Comment by danesfeder** [comment]
Queued up a PR for this #763

**Comment by nsuryanarayanareddyn** [comment]
@Niduank any example ?

**Comment by Niduank** [comment]
@nsuryanarayanareddyn 
In your application, when you use NavigationView in your activity, you are using viewModels right ?
So you have to instantiate `NavigationPresenter` which take `NavigationContract.View` in parameter : 
```java
private void subscribeViewModels() {
        NavigationPresenter navigationPresenter = new NavigationPresenter(this);
        NavigationViewSubscriber subscriber = new NavigationViewSubscriber(navigationPresenter, navigationViewEventDispatcher);
        subscriber.subscribe(this, locationViewModel, routeViewModel, navigationViewModel);
    }
```

You can override in implementing `NavigationContract.View` the `addMarker(Point position)` function.
