### ISSUE TITLE
Cordova: NavigationLauncher vs MapboxNavigation

### ISSUE THREAD

**Issue by baversjo** [mapbox/mapbox-navigation-android#770]
We're currently evaluating mapbox navigation in our cordova app by using the NavigationLauncher.startNavigation
method.
We've gathered feedback from our drivers out on the road, and have some things I believe we need to "tweak" in order for them to accept changing to mapbox internal navigation.
With the NavigationLauncher.startNavigation method, I'm unsure how to achieve below things. I probably need to integrate with `MapboxNavigation` instead of `NavigationLauncher`. But I'm unsure if this can be done with Cordova, which is why I'm asking if it can be done with `NavigationLauncher`. If not, can it be done with `MapboxNavigation` instead? 

1. Is there a way to make an API call to download offline maps around a coordinate? I've seen this advertised but I've been unable to find an API for it in your docs.
2. Is there a way to swap the location provider to Google Play Services?
3. If the internet is poor, or if you're submitting invalid coordinates (for example coordinates in two different countries)  mapbox currently shows a blank blue map. It would be nice if an error was shown. Maybe there's an error callback I'm not handling?

Thank you for any help you can provide here..

**Comment by danesfeder** [comment]
Hey @baversjo, `NavigationLauncher` is definitely the easiest way to integrate the SDK into your app, but it does limit the amount of customization you can give the SDK / possible tweaks you may need for your use case.

1. _Not_ achievable with `NavigationLauncher` - unfortunately there is no customization around offline tiles / maps with the current `NavigationLauncher` setup.  

2. _Achievable_ with `NavigationLauncher` -- if you import the Google Location dependency:
`implementation 'com.google.android.gms:play-services-location:11.8.0'`  The `NavigationView` will initialize with a `GoogleLocationEngine` which will provide GPS updates from Google Play Services.

3.  This is a great point.  We currently don't offer a callback for an error when fetching the route with two coordinates on startup of the UI.  Would you mind opening a separate ticket for this and we will get it into our pipeline of work?

**Comment by baversjo** [comment]
@danesfeder Thank you so much for your reply! I created a new ticket for handling errors better #774. 

About offline maps, the `NavigationLauncher` will still cache a city gradually, correct? If a driver is driving around the same areas week after week, is it likely maps will already be cached when launching a new navigation? Also, even with a fully offline loaded city, do you require an internet connection to create the route plan, or can that also happen offline? Lastly, say I did a full integration using `MapboxNavigation`, would I then just call `offlineManager.createOfflineRegion` and `MapboxNavigation` would automatically use the offline region?

**Comment by danesfeder** [comment]
@baversjo 

>  is it likely maps will already be cached when launching a new navigation?

I'm not entirely sure what kind of caching strategy the Maps SDK uses / how long tiles remained cached.  This would be a better questions for https://github.com/mapbox/mapbox-gl-native

> Also, even with a fully offline loaded city, do you require an internet connection to create the route plan, or can that also happen offline? 

You would still need a connection for fetching the route.  We currently don't offer any type of offline routing engine. 

> Lastly, say I did a full integration using MapboxNavigation, would I then just call offlineManager.createOfflineRegion and MapboxNavigation would automatically use the offline region?

To be clear, `MapboxNavigation` is part of `libandroid-navigation` (as opposed to `libandroid-navigation-ui`) and doesn't actually require a map to run.  However you use the map in conjunction with the navigation logic provided by `MapboxNavigation` is up to you.

**Comment by baversjo** [comment]
Thank you for your answers :)

**Comment by siddmegadeth** [comment]
@baversjo if possibe can you share cordova plugins for turn by turn navigation. it would be great if it can be brought to public domain or private domain(paid) so that it can be taken forward.

Please suggest
