### ISSUE TITLE
OnRouteSelectionChangeListener.onNewPrimaryRouteSelected not called for first route

### ISSUE THREAD

**Issue by skienzl** [mapbox/mapbox-navigation-android#771]
onNewPrimaryRouteSelected is not called if you select the first route in the directionsRoutes list

I think it is because a wrong check in this line:
[NavigationMapRoute.java#L681](https://github.com/mapbox/mapbox-navigation-android/blob/00824584fa7db5e7a3687b646efe01c45df23f98/libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/route/NavigationMapRoute.java#L681)

`primaryRouteIndex > 0` should be `primaryRouteIndex >= 0 `

**Comment by danesfeder** [comment]
@skienzl great catch here, thanks! Queued up https://github.com/mapbox/mapbox-navigation-android/pull/772 to fix
