### ISSUE TITLE
NavigationLauncher: Tell user if could not init navigation

### ISSUE THREAD

**Issue by baversjo** [mapbox/mapbox-navigation-android#774]
I've seen two cases where there's no good indication to the user that navigation failed to init.
Normally, you see a blue map for a split second before navigation can start. In the two cases I've found where it cannot initialize, this blue map stays on screen with no indication to the user that map failed to initiate. The two cases are:

- Upon routing failure (e.g Coordinates are in different continents of the world)
- Maps couldn't download. Say you don't have a stable internet connection. It seems there's no "timeout" to download the maps. Also, I would suggest maybe having a spinner to indicate maps are downloading?

**Comment by Guardiola31337** [comment]
Is this something we still want to implement in `1.0` @mapbox/navigation-android?

Refs. https://github.com/mapbox/mapbox-navigation-android/issues/3034

cc @Lebedinsky

**Comment by zugaldia** [comment]
Probably not necessary if NavigationLauncher is moving to examples.

**Comment by Guardiola31337** [comment]
Wondering about the feature itself not from where is implemented.

cc @abhishek1508 @asinghal22

**Comment by LukasPaczos** [comment]
Closing as stale.
