### ISSUE TITLE
Mapbox navigation - walking profil

### ISSUE THREAD

**Issue by ChibaniImad** [mapbox/mapbox-navigation-android#779]
Hello everyone,
  I use options.directionsProfile(DirectionsCriteria.PROFILE_WALKING) but the route is not a path for walking profile. can anyone help me ?
Here is my code

NavigationViewOptions.Builder options = NavigationViewOptions.builder();
options.origin(origin);
options.destination(destination);
options.awsPoolId(awsPoolId);
options.shouldSimulateRoute(simulateRoute);
options.directionsProfile(DirectionsCriteria.PROFILE_WALKING);
NavigationLauncher.startNavigation(this, options.build());

**Comment by A1ecm** [comment]
I have the same problem with cycling. When it draws the route it the cycling profile works, but when i start the navigation it goes back to driving.

**Comment by danesfeder** [comment]
Hey @ChibaniImad @A1ecm - this looks like a regression in our profile code.  I will look into this today.  Thank you for your patience.
