### ISSUE TITLE
Location Updates

### ISSUE THREAD

**Issue by jethro-yard8** [mapbox/mapbox-navigation-android#787]
I have replicated the navigation tutorial in my application as a starting point, this uses the navigation launcher. However i need to be able to listen for location updates and update my position in real time. 

Judging by what i have read in a few posts this is not possible with navigation launcher and only navigation view? What is the correct way to implement this? Do i need to still have a mapview in my activity or can i use the navigationview on its own? Will i need two separate activities?

**Comment by danesfeder** [comment]
Hey @jethro-yard8 

> Judging by what i have read in a few posts this is not possible with navigation launcher and only navigation view?

Yes you're correct.  Our [`NavigationActivity`](https://github.com/mapbox/mapbox-navigation-android/blob/master/libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/NavigationActivity.java) is what ultimately starts when you use `NavigationLauncher` and serves as a good example of how to inflate the `NavigationView` in your own `Activity`.

**Comment by A1ecm** [comment]
Hi @jethro-yard8 i saw your comment on my ask issue thread.
Here is my code if that helps:

`protected void onCreate(final Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        Mapbox.getInstance(this, "pk.eyJ1IjoiYTFlYyIsImEiOiJjamVhMTJudXoxOGk0MnFudGV2Z3NnMGpwIn0.p9G0Ejx0EGALsmAOJt4ICQ");
        setContentView(R.layout.activity_main);
        mapView = (MapView) findViewById(R.id.mapView);
        mapView.onCreate(savedInstanceState);
        mapView.getMapAsync(new OnMapReadyCallback() {
            @Override
            public void onMapReady(final MapboxMap mapboxMap) {
                map = mapboxMap;
                enableLocationPlugin();
                originCoord = new LatLng(originLocation.getLatitude(), originLocation.getLongitude());

                mapboxMap.addOnMapClickListener(new MapboxMap.OnMapClickListener() {
                    @Override
                    public void onMapClick(@NonNull LatLng point) {

                        if (destinationMarker != null) {
                            mapboxMap.removeMarker(destinationMarker);
                        }

                        destinationCoord = point;

                        destinationMarker = mapboxMap.addMarker(new MarkerOptions()
                                .position(destinationCoord)
                        );
                        destinationPosition = Point.fromLngLat(destinationCoord.getLongitude(), destinationCoord.getLatitude());
                        originPosition = Point.fromLngLat(originCoord.getLongitude(), originCoord.getLatitude());
                        getRoute(originPosition, destinationPosition);
                        button.setEnabled(true);
                        button.setBackgroundResource(R.color.mapboxBlue);

                    };
                });
                button = findViewById(R.id.startButton);
                button.setOnClickListener(new View.OnClickListener() {
                    public void onClick(View v) {
                        setContentView(R.layout.activity_navigation);
                        navigationView = findViewById(R.id.navigationView);
                        navigationView.onCreate(savedInstanceState);
                        navigationView.getNavigationAsync(new OnNavigationReadyCallback() {
                            @Override
                            public void onNavigationReady() {
                                Point origin = originPosition;
                                Point destination = destinationPosition;

                                String awsPoolId = null;

                                boolean simulateRoute = false;

                                MapboxNavigationOptions navigationOptions = MapboxNavigationOptions.builder()
                                        .unitType(NavigationUnitType.TYPE_METRIC)
                                        .build();

                                NavigationViewOptions options = NavigationViewOptions.builder()
                                        .navigationOptions(navigationOptions)
                                        .directionsProfile(DirectionsCriteria.PROFILE_CYCLING)
                                        .progressChangeListener(MainActivity.this)
                                        .origin(origin)
                                        .destination(destination)
                                        .awsPoolId(awsPoolId)
                                        .shouldSimulateRoute(simulateRoute)
                                        .build();

                                navigationView.startNavigation(options);


                            }
                            @Override
                            public void onNavigationFinished() {

                                finish();
                            }

                        });
                    }
                });
            };
        });
    }

    private void getRoute(Point origin, Point destination) {
        NavigationRoute.builder()
                .accessToken(Mapbox.getAccessToken())
                .origin(origin)
                .destination(destination)
                .profile(DirectionsCriteria.PROFILE_CYCLING)
                .build()
                .getRoute(new Callback<DirectionsResponse>() {
                    @Override
                    public void onResponse(Call<DirectionsResponse> call, Response<DirectionsResponse> response) {
                        // You can get the generic HTTP info about the response
                        Log.d(TAG, "Response code: " + response.code());
                        if (response.body() == null) {
                            Log.e(TAG, "No routes found, make sure you set the right user and access token.");
                            return;
                        } else if (response.body().routes().size() < 1) {
                            Log.e(TAG, "No routes found");
                            return;
                        }

                        currentRoute = response.body().routes().get(0);

                        // Draw the route on the map
                        if (navigationMapRoute != null) {
                            navigationMapRoute.removeRoute();
                        } else {
                            navigationMapRoute = new NavigationMapRoute(null, mapView, map, R.style.NavigationMapRoute);
                        }
                        navigationMapRoute.addRoute(currentRoute);
                        Log.i(TAG, "Creating route" + stepDistanceRemaining);
                    }

                    @Override
                    public void onFailure(Call<DirectionsResponse> call, Throwable throwable) {
                        Log.e(TAG, "Error: " + throwable.getMessage());
                    }
                });
    }`

I did it all in my MainActivity.

**Comment by jethro-yard8** [comment]
Thanks @A1ecm but what does your activity_main.xml look like? How are you defining navigationView?

**Comment by jethro-yard8** [comment]
Thanks @A1ecm did you go and create all the methods listed here in your NavigationActivity and activity_navigation.xml?  https://www.mapbox.com/android-docs/navigation/overview/navigation-ui/#navigationview

**Comment by A1ecm** [comment]
No i did it all, in my MainActivity, didn't change activity_main.xml when i changed from navigationlauncher to navigationview.

**Comment by jethro-yard8** [comment]
Okay i see but i have two errors with your solution: 

navigationView.onCreate(savedInstanceState);  - Says savedInstanceState is accessed from inner class and should be declared final

My .progressChangeListener(MapsActivity.this) doesnt work but only works if i cast it to .progressChangeListener((ProgressChangeListener) MapsActivity.this) but im not sure if this will cause an issue? @danesfeder

**Comment by jethro-yard8** [comment]
I resolved my issue, now i just need to work on the route updates and track when the route has finished. Thanks
