### ISSUE TITLE
LocationEngine: services.android.telemetry vs core.location

### ISSUE THREAD

**Issue by P-Zenker** [mapbox/mapbox-navigation-android#790]
Hey,

I use my own navigation logic. After updating from **5.5.0** to **com.mapbox.mapboxsdk:mapbox-android-sdk:6.0.0-beta.4** (and **com.mapbox.mapboxsdk:mapbox-android-navigation:0.12.0-SNAPSHOT**) I've got the following error while **mapboxNavigation.setLocationEngine**:
(com.mapbox.services.android.telemetry.location.LocationEngine) in MapboxNavigation cannot be applied to (com.mapbox.android.core.location.LocationEngine).

Why do those libraries use different location engines?

**Comment by Guardiola31337** [comment]
Hey @P-Zenker 👋thanks for reaching out and report your question.

`mapbox-android-sdk:6.0.0-beta.4` depends on `mapbox-android-telemetry:3.0.0-beta.2` and as you can 👀 both are betas and major version releases which means that they could bring (like in this case) breaking changes.

Noting here that pre-releases are intended to gather early feedback on the new APIs and to detect any potential issues (you can report them 😉) but they are not intended for production apps.

That being said, we're working on bringing the latest versions of the SDKs/libraries that `mapbox-android-navigation` depends on here 👉 https://github.com/mapbox/mapbox-navigation-android/pull/697

So for now, I'd recommend you to stick to `mapbox-android-sdk:5.5.0` version until https://github.com/mapbox/mapbox-navigation-android/pull/697 lands and a new version of `mapbox-android-navigation` is available.

Let us know if you have any other questions! Closing this as answered.
