### ISSUE TITLE
Location Engine Bugs

### ISSUE THREAD

**Issue by jethro-yard8** [mapbox/mapbox-navigation-android#793]
I'm experiencing a weird issue with retrieving the current location which is proving to be very unreliable. My location tends to be placed in a default location in the middle of the country which is far away from where i currently am. See logs below:

**NOTE: I have noticed that when it does this, my location radius changes to be bigger than my country, where as when it receives the correct location, my location radius is normal.**

![photo_2018-03-22_11-12-35](https://user-images.githubusercontent.com/6702147/37761370-264678dc-2dc2-11e8-8f1f-8741dc1feb06.jpg)

`03-22 10:52:54.824 11338-11338/com.test.application E/-------: Enabling Location Plugin
03-22 10:52:54.824 11338-11338/com.test.application E/-------: PERMISSION GRANTED INIT
03-22 10:52:54.824 11338-11338/com.test.application E/-------: ACTIVATING LOCATION
03-22 10:52:54.826 11338-11338/com.test.application E/Last Location: Location[network -29,000000,24,000000 acc=912124 et=+14h5m28s382ms alt=0.0 vel=0.0 bear=81.0 {Bundle[mParcelledData.dataSize=144]}]
03-22 10:52:54.827 11338-11338/com.test.application E/-------: LOCATION NOT NULL, LAST LOCATION ORIGIN: Location[network -29,000000,24,000000 acc=912124 et=+14h5m28s382ms alt=0.0 vel=0.0 bear=81.0 {Bundle[mParcelledData.dataSize=144]}]
03-22 10:52:54.840 11338-11338/com.test.application E/-------: Origin CoordLatLng [latitude=-29.0, longitude=24.0, altitude=0.0]`

However sometimes it does correctly get my location and returns the correct details.

Other times i experience this issue where it doesn't even return a location:

`03-22 10:56:13.864 12986-12986/com.test.application E/-------: Enabling Location Plugin
03-22 10:56:13.864 12986-12986/com.test.application E/-------: PERMISSION GRANTED INIT
03-22 10:56:13.865 12986-12986/com.test.application E/-------: ACTIVATING LOCATION`

Here are is my build.gradle file:

`apply plugin: 'com.android.application'

android {
    compileSdkVersion 27
    defaultConfig {
        applicationId "com.test.application"
        minSdkVersion 15
        targetSdkVersion 27
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
        multiDexEnabled true
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation('com.mapbox.mapboxsdk:mapbox-android-sdk:5.5.0@aar') {
        transitive = true
    }
    implementation 'com.mapbox.mapboxsdk:mapbox-android-navigation:0.11.1'
    implementation('com.mapbox.mapboxsdk:mapbox-android-navigation-ui:0.11.1') {
        transitive = true
    }
    //noinspection GradleCompatible
    implementation "com.android.support:appcompat-v7:${supportLibVersion}"
    implementation 'android.arch.lifecycle:extensions:1.1.0'
    implementation 'com.android.support:design:27.1.0'
    implementation 'com.android.support.constraint:constraint-layout:1.0.2'
    implementation 'com.google.code.gson:gson:2.8.2'
    implementation 'com.android.volley:volley:1.1.0'
    implementation 'com.android.support:recyclerview-v7:27.1.0'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.1'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.1'
    debugImplementation 'com.squareup.leakcanary:leakcanary-android:1.5.4'
    releaseImplementation 'com.squareup.leakcanary:leakcanary-android-no-op:1.5.4'
    compile "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
}
`
My location code: 

`    @SuppressWarnings({"MissingPermission"})
    private void enableLocationPlugin() {

        // Check if permissions are enabled and if not request
        if (PermissionsManager.areLocationPermissionsGranted(this)) {
            // Create an instance of LOST location engine
            Log.e("-------", "PERMISSION GRANTED INIT");
            initializeLocationEngine();
            locationPlugin = new LocationLayerPlugin(mapView, map, locationEngine);
            locationPlugin.setLocationLayerEnabled(LocationLayerMode.NAVIGATION);
        } else {
            Log.e("-------", "PERMISSION NOT GRANTED");
            permissionsManager = new PermissionsManager(this);
            permissionsManager.requestLocationPermissions(this);
        }
    }

    @SuppressWarnings({"MissingPermission"})
    private void initializeLocationEngine() {
        locationEngine = new LostLocationEngine(MapsActivity.this);
        locationEngine.setPriority(LocationEnginePriority.HIGH_ACCURACY);
        Log.e("-------", "ACTIVATING LOCATION");
        locationEngine.activate();
        Location lastLocation = locationEngine.getLastLocation();

        Log.e("Last Location", lastLocation.toString());
        if (lastLocation != null) {
            originLocation = lastLocation;
            setCameraPosition(lastLocation);
            Log.e("-------", "LOCATION NOT NULL, LAST LOCATION ORIGIN: " + originLocation.toString());
        } else {
            Log.e("-------", "LOCATION NULL, ADDING LISTENER");

            locationEngine.addLocationEngineListener(this);
        }
    }`

Other than that my code remains the same as the code in the navigation turn by turn tutorial for receiving location, i am also making use of navigationview instead of navigation launcher.

Would it be better to some how use the google api client? As i need close to 100% accuracy.

**EDIT: I downloaded the mapbox demo application and it too places me in the middle of South Africa.**

**Comment by danesfeder** [comment]
>  i switched to using the Google API client to retrieve my location which is working great

Quoted from https://github.com/mapbox/mapbox-navigation-android/issues/796#issue-307986547 this looks good to close
