### ISSUE TITLE
[Question] - NavigationUI Re-Route

### ISSUE THREAD

**Issue by Danny-James** [mapbox/mapbox-navigation-android#794]
@danesfeder Did the ability to turn off re-routing get put into any of the latest versions? I believe a `Boolean` value was going to be added to the `NavigationOptions` to turn re-routing on and off.

**Comment by danesfeder** [comment]
@Danny-James I know you've been waiting on that for a while, just added in https://github.com/mapbox/mapbox-navigation-android/pull/782/commits/65cc2ef62584c0db28cb3ed2a3d3ff0879c54a50

Sorry for the delay!

**Comment by Danny-James** [comment]
@danesfeder when will this be available in a stable release? - thanks very much for this 👍

**Comment by danesfeder** [comment]
@Danny-James keep an 👁 out for our next release (`0.12.0`) happening in the coming week or so.  Will close this ticket when the PR lands

**Comment by Danny-James** [comment]
@danesfeder nice one man!
