### ISSUE TITLE
InstructionList flashes intermittently during reroute

### ISSUE THREAD

**Issue by danesfeder** [mapbox/mapbox-navigation-android#800]
In certain scenarios, the list of instructions (accessible by clicking the top banner), will flash when a reroute occurs while navigating.  We do have a UI treatment to show a rerouting state, but showing / hiding the list is not part of this.  Some other view is triggering this:

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/8434572/37845070-f443ecf0-2e9f-11e8-84e2-189d3a51e612.gif)

**Comment by Guardiola31337** [comment]
Noticed OP when running the [`EmbeddedNavigationActivity`](https://github.com/mapbox/mapbox-navigation-android/blob/master/app/src/main/java/com/mapbox/services/android/navigation/testapp/activity/navigationui/EmbeddedNavigationActivity.java) example from the test app 👀 

![embedded_activity_flashing_issue](https://user-images.githubusercontent.com/1668582/41232855-f3ebf230-6d87-11e8-8258-ef39e9659308.gif)

**Comment by danesfeder** [comment]
I think this may also be related to https://github.com/mapbox/mapbox-navigation-android/pull/959#issuecomment-394819272

Noting that this may be related to our use of `TransitionManager` + `DefaultItemAnimator` at the same time.  See possible related convo 👀 https://github.com/airbnb/epoxy/issues/405

**Comment by Guardiola31337** [comment]
Noticed OP when running the [`DualNavigationMapActivity`](https://github.com/mapbox/mapbox-navigation-android/blob/master/app/src/main/java/com/mapbox/services/android/navigation/testapp/activity/navigationui/DualNavigationMapActivity.java) example from the test app 👀

![flashing_issue](https://user-images.githubusercontent.com/1668582/42391018-32c35f28-814e-11e8-8806-cfbcaa42a294.gif)
