### ISSUE TITLE
NavigationView in Activity

### ISSUE THREAD

**Issue by jethro-2018** [mapbox/mapbox-navigation-android#809]
Two separate questions:

1) How can i set the interval for location updates in Activity#onProgressChange? 

This doesn't do anything: locationEngine.setInterval(5000);

2) How can i properly destroy NavigationView in an Activity? After having NavigationView running, going back to my recycler view my UI is unresponsive. I tried calling navigationView.onDestroy(); in my Activity#onDestroy(); method but that did not solve it.

**Comment by danesfeder** [comment]
Hey @jethro-2018, 

1.  If this is in regard to the `LocationEngine` we use for `NavigationView`, we currently don't expose APIs to customize the parameters of the location engine.  ([setup here](https://github.com/mapbox/mapbox-navigation-android/blob/master/libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/location/LocationViewModel.java#L101-L106)).  It's currently set to fire every second if the device is receiving valid updates.

2.  Are you using the cancel button to close the `NavigationView`?  If so, you need to include all the lifecycle methods to ensure it is shut down properly.  If you aren't already https://www.mapbox.com/android-docs/navigation/overview/navigation-ui/#navigationview.  This is to ensure the map is properly shut down.  

In the future, please direct these kinds of questions to https://stackoverflow.com/questions/tagged/mapbox, as this is not an immediately actionable issue for logs, code snippets, etc.

**Comment by jethro-2018** [comment]
Yes it is the same LocationEngine, is there no way i can get around this? As i can't send the data every second to our API.

Those life cycle methods have been implemented and i am still experiencing the same issue.
