### ISSUE TITLE
Remove Android-apt dependency

### ISSUE THREAD

**Issue by Grsmto** [mapbox/mapbox-navigation-android#81]
Hi,
It seems like Android-apt dependency has been added in [this commit](https://github.com/mapbox/mapbox-navigation-android/commit/0af5c85c1a90a35b590a00b0102b085ecd341af1).
From what we can read on [their doc](https://bitbucket.org/hvisser/android-apt/wiki/Migration), the lib is now deprecated (and will be breaking change with Gradle 3.0). For such a new project I think it would be good to keep it "future-proof"?

Thanks!

**Comment by cammace** [comment]
Thanks for linking me to the docs, autoValues docs still say to use `apt` instead of `annotationProcessor`. I've made the fix and removed the dependency in #92

**Comment by Grsmto** [comment]
😅

Awesome, can't wait to see the Navigation UI module!
