### ISSUE TITLE
Add NavigationView#endNavigation to end sessions

### ISSUE THREAD

**Issue by danesfeder** [mapbox/mapbox-navigation-android#813]
Currently, using `NavigationView` there isn't any way for developers to end navigation in their `Fragment` or `Activity`.  They currently must rely on users clicking the `X` button in the UI.  Should they choose to want to end navigation explicitly for the user, we need to add a method to `NavigationView` allow them to do so.

Capturing from: https://github.com/mapbox/mapbox-navigation-android/pull/806#issuecomment-376319825 and https://github.com/mapbox/mapbox-navigation-android/pull/806#issuecomment-377692064

**Comment by m-harisqurashi** [comment]
`NavigationView.finishNavigationView()` simply calls `NavigationListener.onNavigationFinished()`. It doesn't stop voice navigation instruction and ongoing/foreground `Notification`. Inside `finishNavigationView()` we should call `NavigationViewModel.deactivateInstructionPlayer()` to close instruction player and a way to clear ongoing Notification.

**Comment by danesfeder** [comment]
@m-harisqurashi Yeah that's correct.  The solution for this ticket will be adding a completely new method that completes the shutdown behavior you just described.

**Comment by m-harisqurashi** [comment]
@danesfeder, any update on this issue? When you guys will add this feature on latest version? Your response is highly appreciated.

**Comment by Guardiola31337** [comment]
Hey @m-harisqurashi we're moving this issue in #959 
We are working quickly to get it out as soon as possible. Stay tuned!
