### ISSUE TITLE
Move OSRM-text-instructions to independent repo

### ISSUE THREAD

**Issue by cammace** [mapbox/mapbox-navigation-android#82]
Similar to Swift, https://github.com/Project-OSRM/osrm-text-instructions.swift the Java equivalent should live in its own repo for easier maintaining. 

cc: @mapbox/navigation @freenerd

**Comment by 1ec5** [comment]
For reference, we put the Swift port in a separate repository because iOS package managers (Carthage in particular, but also potentially SPM in the future) lack support for monorepos, preferring the modularity that comes with a one-to-one relationship between packages and repositories.

**Comment by zugaldia** [comment]
@1ec5 thanks for pointing this out. On Android we don't have that restriction so it could be a folder withing https://github.com/Project-OSRM/osrm-text-instructions. That way we wouldn't need to [manually copy](https://github.com/mapbox/mapbox-navigation-android/blob/master/Makefile#L1-L8) fixtures and translations, but I'll defer to @freenerd to decide the best location.

**Comment by cammace** [comment]
@zugaldia @ericrwolfe should I hold off on moving OSRM over (and remove from 0.4.0 milestone) since we aren't sure if we still need it?

**Comment by ericrwolfe** [comment]
I don't see moving this as a high priority item right now, so we should remove from 0.4.0 and we can revisit later.

That being said, OSRM text instructions will remain around for the time being, so I'll defer to @zugaldia on the best end approach.

**Comment by zugaldia** [comment]
Agreed on punting here if this isn't a priority right now. I'll assign it to myself and take care of it at a later milestone.

**Comment by 1ec5** [comment]
At some point, we’ll need to bring this Java port of OSRM Text Instructions up to date with the JavaScript and Swift versions. To facilitate that merge, we’ll need to know roughly which commit to osrm-text-instructions the Java port and its text fixtures are currently based on. The code was originally ported in mapbox/mapbox-java#374, which would’ve been shortly before [v0.2.0](https://github.com/Project-OSRM/osrm-text-instructions/releases/tag/v0.2.0).
