### ISSUE TITLE
Allow global static access to app context

### ISSUE THREAD

**Issue by devotaaabel** [mapbox/mapbox-navigation-android#823]
There's a lot of different use cases for having access to context globally in the SDK. We could do something similar to what they do in the telemetry library.

**Comment by Guardiola31337** [comment]
Is this something we still want to consider in `1.0` @mapbox/navigation-android?

cc @kmadsen

**Comment by kmadsen** [comment]
OH yeah I totally think we should do this. I thought I was the only one.

https://github.com/mapbox/mapbox-navigation-android/pull/3071/files#diff-f104da15d8909da5bcb1f24fae3d746eR63
^ Let's move it here

The MapboxDistanceFormatter is one interface I came across that would benefit
https://github.com/mapbox/mapbox-navigation-android/issues/3016
