### ISSUE TITLE
Native application crash when use NavigationView.onDestroy() inside fragment

### ISSUE THREAD

**Issue by m-harisqurashi** [mapbox/mapbox-navigation-android#830]
My application crashes every time i tries to cancel navigation via `cancelBtn` using `NavigationView.onDestroy()`.

I don't want to kill my `Activity` and/or `Fragment`, only needed to cancel `NavigationView` either by removing from view hierarchy or releasing its resources without removing from view hierarchy. Most importantly any user can start navigation with same `NavigationView` reference.

I tried with dynamically creating `NavigationView` for new navigation request but i still get this.

Only get this log:
```
google-breakpad: ### ### ### ### ### ### ### ### ### ### ### ### ###
google-breakpad: Chrome build fingerprint:
google-breakpad: 1.1.032618
google-breakpad: 32
google-breakpad: ### ### ### ### ### ### ### ### ### ### ### ### ###
libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x10020 in tid 9945 (com.package.name), pid 9945 (com.package.name)
```

**Comment by danesfeder** [comment]
@m-harisqurashi what are you calling inside of the cancel btn callback?

**Comment by m-harisqurashi** [comment]
I'm calling `NavigationView.onDestroy`, but if i use `NavigationView.finishNavigationView` it does nothing.

**Comment by Guardiola31337** [comment]
Hey @m-harisqurashi 👋 thanks for reaching out and report your problem.

We're working on a way to end navigation without finishing the whole view (which I believe is what you are trying to do).

In any case, could you share the symbolicated stack trace?

We can get a bit more details about the crash by switching the Android Monitor from "Show Only Selected Application" to "No Filters" in Android Studio. This will give the full C++ error, which will make troubleshooting this easier. Here's what it looks like in Android Studio:

![no_filters_as](https://cloud.githubusercontent.com/assets/64527/20661404/4ad9391c-b557-11e6-84de-5c9a214a9975.png)

cc @danesfeder

**Comment by Guardiola31337** [comment]
This is being tracked in https://github.com/mapbox/mapbox-navigation-android/issues/813

Closing as duplicated.
