### ISSUE TITLE
User should see themselves progress through tunnel when GPS is weak or nonexistent

### ISSUE THREAD

**Issue by akitchen** [mapbox/mapbox-navigation-android#835]
Goal: relative feature parity w/iOS:
 - Night mode when entering a tunnel (based on road segment attributes)
 - Continuing simulated progress along route if lack of decent GPS
 - Switching back to appropriate Day/Night mode when exiting tunnel (i.e. at night we would still be in night mode)

Look for opportunities to deliver incrementally in smaller pieces. Consider multiple PRs or a larger PR which we merge more than once.

Things to do:
 - [x] Evaluate `inTunnel` value of `NavigationStatus` response object
 - [ ] ~Include an option in `NavigationUIOptions` to allow developers to conditionally control tunnel mode~
   - [ ] ~Requires exposing a callback to notify upon entering/exiting a tunnel~

See https://github.com/mapbox/mapbox-navigation-android/pull/1392#issuecomment-427094945 for further details on why ☝️ is not needed anymore

 - [x] Forward-project the user's position based on calculated/projected position 
   - [x] Possible threading changes to allow driving the navigator without location updates (#1265)
   - [x] Pass current date into navigator to retrieve projected position

This landed as part of https://github.com/mapbox/mapbox-navigation-android/pull/1336 and https://github.com/mapbox/mapbox-navigation-android/pull/1354

**Comment by akitchen** [comment]
Updated/groomed OP with @Guardiola31337 in order to keep up-to-date

**Comment by akitchen** [comment]
Updated/groomed OP with @Guardiola31337 in order to keep up-to-date

**Comment by danesfeder** [comment]
> pass future date into navigator to retrieve projected position

Noting here that this is not how the `Navigator#getStatus` API is setup - we can continually pass in the current date/time in a loop and `Navigator` will begin to provide projected latlngs if we stop providing `FixLocation` updates via `Navigator#updateLocation`
