### ISSUE TITLE
Developers can add/user can see the current way name under the location puck.

### ISSUE THREAD

**Issue by akitchen** [mapbox/mapbox-navigation-android#836]
Unlocked by upcoming release of LocationLayerPlugin (v0.5.0)

Also consult iOS codebase for logic used to get the way name

References:

 - https://github.com/mapbox/mapbox-navigation-ios/issues/1269

**Comment by danesfeder** [comment]
Street name under location puck:
![img_2d032b960bd7-1](https://user-images.githubusercontent.com/8434572/38508790-1f9419ba-3bee-11e8-9e33-21e80026a46c.jpg)

This work should also include a public API that will allow developers to override the text that populates the run-time styling, should they choose to do so.
