### ISSUE TITLE
Question: Option To Hide Sound and Feedback Buttons In NavigationLauncher

### ISSUE THREAD

**Issue by Danny-James** [mapbox/mapbox-navigation-android#840]
Do we know when the ability to hide the Sound and Feedback buttons whilst using the `NavigationLauncher` will be available?

**Comment by Guardiola31337** [comment]
Hey @Danny-James 👋 Thanks for your question.

This is being tracked in https://github.com/mapbox/mapbox-navigation-android/issues/634

Closing here as duplicate.

Let us know if you have any other feature requests or if you find any bugs.

**Comment by vijaykishan312** [comment]
navigationView.findViewById(R.id.feedbackFab).setVisibility(View.GONE);

**Comment by vijaykishan312** [comment]
> Do we know when the ability to hide the Sound and Feedback buttons whilst using the `NavigationLauncher` will be available?

navigationView.findViewById(R.id.feedbackFab).setVisibility(View.GONE);

in overwridemethod of onNavigationReady.
