### ISSUE TITLE
Notifcation Issue: Blank Notification and No Click Recognised

### ISSUE THREAD

**Issue by Danny-James** [mapbox/mapbox-navigation-android#841]
When running the `NavigationLauncher` this creates a notification, however this notification seems to be Blank, if the app is running in the backround and I click the notification it doesn't resume the Application.

**OS Version Tested**
```
Android OS: 4.12
Android OS: 7.0
```

**Gradle Configuration**
```java
    implementation 'com.mapbox.mapboxsdk:mapbox-android-plugin-traffic:0.3.0'
    implementation('com.mapbox.mapboxsdk:mapbox-android-navigation-ui:0.12.0') {
        transitive = true
        changing = true
    }
```

**Launching Navigation**
```java
// Generate Navigation Options
NavigationLauncherOptions.Builder navOptions = NavigationLauncherOptions.builder()
         .directionsRoute(currentRoute)
         .enableOffRouteDetection(false)
         .directionsProfile(DirectionsCriteria.PROFILE_DRIVING)
         .locale(Locale.UK)
         .unitType(NavigationUnitType.TYPE_IMPERIAL);

// Launch Navigation UI.
NavigationLauncher.startNavigation(ActivityNavigationMap.this, navOptions.build());
```

**Screenshots of Issue**

![screenshot_20180410-114542 1](https://user-images.githubusercontent.com/32104383/38555293-2026240a-3cb5-11e8-9529-83c5cc03c1c6.png)

![screenshot_20180410-114551 1](https://user-images.githubusercontent.com/32104383/38555297-279f9266-3cb5-11e8-9de2-ae2dfaf91b99.png)

![screenshot_20180410-114614 1](https://user-images.githubusercontent.com/32104383/38555318-34f3eba6-3cb5-11e8-9ad7-da5756f87bb2.png)

**Comment by Danny-James** [comment]
Possibly Same Issue As #713  Do We Have An ETA on When This Will Be Fixed?

**Comment by Guardiola31337** [comment]
Hey @Danny-James 👋 Thanks for your reaching out and report your issue.

As you mentioned this is being tracked in #713 and it's under our radar.

Closing here as duplicate.

Let us know if you have any other feature requests or if you find any bugs.
