### ISSUE TITLE
Navigaton UI: NavigationLauncher Opens but puck does not move

### ISSUE THREAD

**Issue by Danny-James** [mapbox/mapbox-navigation-android#847]
I'm now running `navigation-ui-12.0` since upgrading to this version my Navigation no longer works, I pass a route through to the UI but when starting i get the first voice instruction but the puck does not move.

If i go back in the app and pass in another route the route starts from where i have driven too but same again i get the first voice instruction but again the puck does not move.

**Device**
```
Samsung Galaxy S8 - Android OS: 7.0
```

I have an activity which shows a MapView and a preview of the route drawn onto the map using `NavigationMapRoute`. I then have a FAB button which when clicked passes the route through to `NavigationLauncher.startNavigation(this, route)`

Does the `NavigationLauncher` use the `LocationEngine` I have setup in the Route Preview activity before I launch the `NavigationUI`

**Location Setup**
```java
@SuppressWarnings({"MissingPermission"})
    private void enableLocationPlugin() {

        //locationEngine = new LocationEngineProvider(this).obtainBestLocationEngineAvailable();
        locationEngine = GoogleLocationEngine.getLocationEngine(this);
        locationEngine.setPriority(LocationEnginePriority.HIGH_ACCURACY);
        locationEngine.setFastestInterval(1000);
        locationEngine.setInterval(0);
        locationEngine.activate();

        locationEngine.requestLocationUpdates();
        Location lastloc = locationEngine.getLastLocation();
        if(lastloc == null) {
            Log.e(TAG, "No Location Found, Add LocationEngineListener.");
            locationEngine.addLocationEngineListener(this);
        }else{
            Log.d(TAG, "Last Location Found.");
            Log.d(TAG, "Last Location: " + lastloc.toString());
            currentPosition = Point.fromLngLat(lastloc.getLongitude(), lastloc.getLatitude());
            lastLocation = lastloc;
        }

        // Setup LocationLayerPlugin To Show Current Location Icon.
        locationLayer = new LocationLayerPlugin(mapView, mapboxMap, locationEngine);
        locationLayer.setLocationLayerEnabled(LocationLayerMode.COMPASS);

        // addObserver
        getLifecycle().addObserver(locationLayer);

        buildRoute();
    }
```

**Starting Navigation UI**
```java
if (currentPosition != null) {
            if (currentRoute != null) {
                String awsPoolID = "eu-west-1_********b"; //Not In Use.
                Log.d(TAG, "Start Navigation UI");

                // Generate Navigation Options
                NavigationLauncherOptions.Builder navOptions = NavigationLauncherOptions.builder()
                        .directionsRoute(currentRoute)
                        .enableOffRouteDetection(false)
                        .directionsProfile(DirectionsCriteria.PROFILE_DRIVING)
                        .locale(Locale.UK)
                        .unitType(NavigationUnitType.TYPE_IMPERIAL);

                // Launch Navigation UI.
                NavigationLauncher.startNavigation(ActivityNavigationMap.this, navOptions.build());

            }else{
                Log.e(TAG, "currentRoute is NULL");
            }
        } else {
            // Create Dialog To Allow User To Acknowledge Location Issue.
            new AlertDialog.Builder(this)
                    .setTitle("Location Problem")
                    .setMessage("The application is unable to find your location, please close this dialog and touch the white location icon and try again.")
                    .setCancelable(false)
                    .setPositiveButton("Close", new DialogInterface.OnClickListener() {
                        public void onClick(DialogInterface dialog, int id) {
                            dialog.dismiss();
                        }
                    })
                    .show();
            Log.d(TAG, "Display No Location Dialog.");
        }
```

**Comment by danesfeder** [comment]
@Danny-James I just tried our test app with your `NavigationLauncherOptions`.  I wasn't stuck per say, but I think the issue you're seeing has to do with disabling off-route detection.  See below (these are with your options):

With off-route detection disabled (your current options):
![ezgif com-video-to-gif 1](https://user-images.githubusercontent.com/8434572/38679119-e71bbec2-3e30-11e8-8634-11648c01a64b.gif)

With off-route detection and snap-to-route both disabled:
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/8434572/38679168-090b0948-3e31-11e8-8f08-47fa92bc52fd.gif)

The gotcha here is we haven't exposed the ability to disable snap-to-route from `NavigationLauncherOptions`.  I will look into PR'ing this.  I will say, I think using `NavigationView` in your own `Activity` will help you out a lot here.  You gain advanced customization that it sounds like you're looking for (access to all `MapboxNavigationOptions`) versus the limited customization offered by `NavigationLauncher`.

**Comment by Danny-James** [comment]
@danesfeder Is it a large task to converting from NavigationLauncher to NavigationView? I'm passed my release date by quite a bit now and was aiming to have the app released for testing this week.

The puck for me is not moving at all it's just staying at the start, could this be something to do with my LocationEngine or does the NavigationLauncher create it's own locationEngine on start?

**Comment by danesfeder** [comment]
@Danny-James one thing I see is when you call `locationEngine.requestLocationUpdates();` This should be done in `LocationEngineListener#onConnected` - I see you're only adding the listener if there isn't a last location

**Comment by Danny-James** [comment]
@danesfeder I got this method from one of the examples on this github see [here](https://github.com/mapbox/mapbox-android-demo/blob/master/MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/plugins/LocationPluginActivity.java)

Are you saying the only time i should call the following `locationEngine.requestLocationUpdates();` is `onConnected` what if the locationEngine does not have a Location? I thought calling `locationEngine.requestLocationUpdates();` would ask the `LocationEngine` to pull a new location? is this incorrect.

Currently I am calling `locationEngine.requestLocationUpdates();`

```java
// Add the mapView lifecycle to the activity's lifecycle methods
    @SuppressWarnings({"MissingPermission"})
    @Override
    public void onConnected() {
        Log.d(TAG, "requestLocationUpdates();");
        locationEngine.requestLocationUpdates();
    }

@SuppressWarnings({"MissingPermission"})
    @Override
    protected void onStart() {
        super.onStart();
        mapView.onStart();

        if (locationEngine != null) {
            locationEngine.requestLocationUpdates();
            locationEngine.addLocationEngineListener(this);
        }
    }

@Override
    protected void onStop() {
        super.onStop();
        mapView.onStop();

        if (locationEngine != null) {
            locationEngine.removeLocationEngineListener(this);
            locationEngine.removeLocationUpdates();
        }

    }

fabLocation.setOnClickListener(new View.OnClickListener() {
            @SuppressWarnings({"MissingPermission"})
            @Override
            public void onClick(View view) {
                //Get Location onDemand.
                Log.d(TAG, "Location FAB Clicked.");
                if (locationEngine.getLastLocation() != null) {
                    requestedLocation = true;
                    if (!compareLocation(locationEngine.getLastLocation(), lastLocation)){
                        // Location Has Changed Find New Location.
                        Log.d(TAG, "Get Last Location");
                        locationEngine.requestLocationUpdates();
                        lastLocation = locationEngine.getLastLocation();
                        onLocationChanged(lastLocation);
                    }else{
                        // Location Hasn't Changed Animate Camera To Current Position.
                        Log.d(TAG, "Location Hasn't Changed");
                        onLocationFound(lastLocation);
                    }
                }
            }
        });

@SuppressWarnings({"MissingPermission"})
    private void enableLocationPlugin() {

        //locationEngine = new LocationEngineProvider(this).obtainBestLocationEngineAvailable();
        locationEngine = GoogleLocationEngine.getLocationEngine(this);
        locationEngine.setPriority(LocationEnginePriority.HIGH_ACCURACY);
        locationEngine.setFastestInterval(1000);
        locationEngine.setInterval(0);
        locationEngine.activate();

        locationEngine.requestLocationUpdates();
        Location lastloc = locationEngine.getLastLocation();
        if(lastloc == null) {
            Log.e(TAG, "No Location Found, Add LocationEngineListener.");
            locationEngine.addLocationEngineListener(this);
        }else{
            Log.d(TAG, "Last Location Found.");
            Log.d(TAG, "Last Location: " + lastloc.toString());
            currentPosition = Point.fromLngLat(lastloc.getLongitude(), lastloc.getLatitude());
            lastLocation = lastloc;
        }

        // Setup LocationLayerPlugin To Show Current Location Icon.
        locationLayer = new LocationLayerPlugin(mapView, mapboxMap, locationEngine);
        locationLayer.setLocationLayerEnabled(LocationLayerMode.COMPASS);

        // addObserver
        getLifecycle().addObserver(locationLayer);

        buildRoute();
    }

```

So as you can see i am calling `locationEngine.requestLocationUpdates();` in the following lifecycle methods, `onConnected`, `onStart`, and `locationEngine.removeLocationUpdates()` in the `onStop`

I'm also calling `locationEngine.requestLocationUpdates();` in my LocationFAB and after the LocationEngine is created.

**Comment by danesfeder** [comment]
A good example is the `LocationViewModel` we use for the UI https://github.com/mapbox/mapbox-navigation-android/blob/master/libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/location/LocationViewModel.java

`LocationEngine#activate` will call `onConnected` once the API connection is properly established and then you can start requesting updates

**Comment by Danny-James** [comment]
@danesfeder should i only request updates in the `onConnected`?  So not in the `onStart`, Also am i correct in the `onStop` to removeUpdates and RemoveListener?

I deactivate the locationEngine in onDestroy is this correct?

**Comment by danesfeder** [comment]
> should i only request updates in the onConnected
@Danny-James yes ^

Yeah how you handle the app lifecycle is up to you.  In `LocationViewModel` we don't stop listening to updates because we still need them in the background (if a user has turned their screen off, but still want voice announcements).  

Removing and re-adding the listener may make more sense for you.  But not deactivating the whole engine.

**Comment by Danny-James** [comment]
@danesfeder below are my Lifecycle Methods now, I only call `requestLocationUpdates` on the `onConnected` and i also only attach the Listener `onConnected` is this the correct way of doing things.

```java
// Add the mapView lifecycle to the activity's lifecycle methods
    @SuppressWarnings({"MissingPermission"})
    @Override
    public void onConnected() {
        Log.d(TAG, "requestLocationUpdates();");
        locationEngine.requestLocationUpdates();
        locationEngine.addLocationEngineListener(this);
    }

    @SuppressWarnings({"MissingPermission"})
    @Override
    public void onResume() {
        super.onResume();
        mapView.onResume();
    }


    @SuppressWarnings({"MissingPermission"})
    @Override
    protected void onStart() {
        super.onStart();
        mapView.onStart();

        /*
        if (locationEngine != null) {
            locationEngine.requestLocationUpdates();
            locationEngine.addLocationEngineListener(this);
        }
        */
    }

    @Override
    protected void onStop() {
        super.onStop();
        mapView.onStop();

        if (locationEngine != null) {
            locationEngine.removeLocationEngineListener(this);
            locationEngine.removeLocationUpdates();
            //locationEngine.deactivate();
        }

    }

    @Override
    public void onPause() {
        super.onPause();
        mapView.onPause();
    }

    @Override
    public void onLowMemory() {
        super.onLowMemory();
        mapView.onLowMemory();
    }

    @Override
    protected void onDestroy() {
        super.onDestroy();
        mapView.onDestroy();

        if (locationEngine != null) {
            locationEngine.deactivate();
        }
    }

    @Override
    protected void onSaveInstanceState(Bundle outState) {
        super.onSaveInstanceState(outState);
        mapView.onSaveInstanceState(outState);
    }
```

**Comment by Danny-James** [comment]
@danesfeder I've come across another issue, can i ask the `locationEngine.addLocationEngineListener(this);` when this pushes an updated location, should this call the overiding method `onLocationChanged`, basically I have the following.

```java
@Override
    public void onLocationChanged(Location location) {
        if (location != null) {
            // Set Current Position.
            currentPosition = Point.fromLngLat(location.getLongitude(), location.getLatitude());

            // Check If Existing Route Is Plotted And Remove.
            if (navigationMapRoute == null) {
                // Check If Route Has Been Plotted, If Not ReBuild Route.
                // After New Location Has Been Found.
                buildRoute();
                // If navigationMapRoute has already been created, this means
                // the route has been successfully built.
            }

            Log.d(TAG, "Set currentPosition: " + currentPosition.toString());

            // forceLocationUpdate on Location Layer.
            if (locationLayer != null) {
                Log.d(TAG, "forceLocationUpdate");
                //locationLayer.forceLocationUpdate(location);
            }

            onLocationFound(location);
        }else{
            Log.e(TAG, "Location is NULL");
        }
    }
```
I've checked and the onLocationChanged method is never being called unless I call it manually.

I have the LocationFAB which can be clicked to refresh the user's location which in turn calls onLocationChanged with the New Location, if i don't press this my route does not build, which would mean the onLocationChanged is not being called.

Their must be a location because if their wasn't when i pressed the LocationFAB which called onLocationChanged Manually the route would not build.

**Comment by danesfeder** [comment]
```public void onConnected() {
        Log.d(TAG, "requestLocationUpdates();");
        locationEngine.requestLocationUpdates();
        locationEngine.addLocationEngineListener(this);
    }```

`onConnected` is part of `LocationEngineListener`, so it will never be called because you're adding the listener in the listener itself - does that make sense?

**Comment by Danny-James** [comment]
I understand, where do you recommend this being added? sorry to bother you about this.

**Comment by danesfeder** [comment]
in the constructor or in onCreate - listener should be added, then `activate()` should be called https://github.com/mapbox/mapbox-navigation-android/blob/master/libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/location/LocationViewModel.java#L35

**Comment by Danny-James** [comment]
@danesfeder Great News! .. that has now fixed my issue, like i said i will test the NavUI again on my way home on multiple devices and report back tomorrow. Cheers for you help.

**Comment by danesfeder** [comment]
@Danny-James happy to help - glad it's resolved.  Yeah the snap config is targeted for `0.13.0` which is on track for early next week release

**Comment by Danny-James** [comment]
@danesfeder do you think the PR will solve my issue where the puck doesn't move at all?

**Comment by danesfeder** [comment]
@Danny-James yeah I think you should disable snapping too

**Comment by Danny-James** [comment]
@danesfeder so because snapping is currently on in `v12` that's why my puck is not moving? 

is this change available in the `SNAPSHOT` yet?

**Comment by danesfeder** [comment]
@Danny-James that was my hunch, also hoping your fixes for your location engine code help here.  We have our own location engine logic as you saw, but the engines are shared singletons so you could've been affecting ours somehow.  And yes the snapshot was updated `14:50:38 UTC`

**Comment by Danny-James** [comment]
@danesfeder I did the test on my way home using the following devices:

```
Samsung Galaxy S8: Android 8.0
Samsung Galaxy S6 Edge: Android 7.0
Motorola TC55: Android 4.1.2
```

All Devices Opened The Route In Navigation UI but when i started to drive the puck just stayed still, did not move, if i exit the Navigation UI and reopen with the same route the puck will show where i currently am (new start location) but again not move.

**Comment by danesfeder** [comment]
@Danny-James with snapping disabled?  Using the `SNAPSHOT`?

**Comment by Danny-James** [comment]
@danesfeder Sorry to confuse you, no i've just recompiled my app with the snapshot so will update you on Monday with the results 👍

**Comment by danesfeder** [comment]
Thanks @Danny-James - cheers 👍

**Comment by Danny-James** [comment]
@danesfeder I'm now using the SNAPSHOT for `v13`, I've tried with 3 different devices and the Navigation will not move, I have `OffRouteDetection` and `SnapToRoute` Turned Off.

I'm going to remove them from my `NavigationOptions` and see if it then works to rule out any issues with the options.

**Comment by Danny-James** [comment]
@danesfeder I've tested again this morning with `OffRouteDetection` and `SnapToRoute` Taken out of my NavigationOptions and the puck is still not moving.

Have you any ideas on this?

**Comment by Danny-James** [comment]
@danesfeder thanks for getting back to me, I'll try this and update you, I really appreciate your help. 👍

**Comment by Danny-James** [comment]
@danesfeder i'm using `v13-SNAPSHOT` but I seem to be getting the following error when compiling:

```
Unexpected inputs: ImmutableJarInput{name=com.mapbox.mapboxsdk:mapbox-android-sdk:5.5.0, file=S:\Development\AndroidStudioProjects\RouteInfo\RouteInfo-V2\app\build\intermediates\transforms\desugar\debug\24.jar, contentTypes=CLASSES, scopes=EXTERNAL_LIBRARIES, status=REMOVED}
```

Does this mean anything to you?

**Comment by danesfeder** [comment]
I would try cleaning, probably a caching issue - we updated the Maps SDK yesterday #865
