### ISSUE TITLE
Walking navigation

### ISSUE THREAD

**Issue by graemebates** [mapbox/mapbox-navigation-android#85]
Hi there, 

I'm not sure where to ask this but I was wondering whether the navigation API can be used for non-driving navigation.

Thanks,
Graeme

**Comment by Grsmto** [comment]
Yes it supports every navigation type that the Direction API supports.

**Comment by graemebates** [comment]
Is the way to configure it:

`navigation.getMapboxNavigationOptions().setDirectionsProfile(DirectionsCriteria.PROFILE_WALKING);`?

**Comment by Grsmto** [comment]
Not sure, but this should work:
```
MapboxNavigationOptions options = new MapboxNavigationOptions();
options.setDirectionsProfile(DirectionsCriteria.PROFILE_WALKING);
navigation = new MapboxNavigation(this, Mapbox.getAccessToken(), options);
```

**Comment by graemebates** [comment]
Wow that makes a lot more sense. Do you know if it will affect how the map decides to draw routes as well? From my understanding the navigation object acts as a wrapper for Directions API calls, so if its configured for walking, it should return a walking route right?

**Comment by Grsmto** [comment]
Yes that's right. Under the hood, this library is just calling the same function as the Direction SDK to retrieve the route.

**Comment by errazkisibawaih** [comment]
Hello everyone,
I have the same issue , I use options.directionsProfile(DirectionsCriteria.PROFILE_WALKING) but the route is not a path for walking profite.
Here is my code 
> 
NavigationViewOptions.Builder options = NavigationViewOptions.builder();
        options.origin(origin);
        options.destination(destination);
        options.awsPoolId(awsPoolId);
        options.shouldSimulateRoute(simulateRoute);
        options.directionsProfile(DirectionsCriteria.PROFILE_WALKING);
NavigationLauncher.startNavigation(this, options.build());
>

**Comment by dmp5658** [comment]
Having the exact same issue as errazkisibawaih

**Comment by danesfeder** [comment]
Hey @errazkisibawaih @dmp5658 - please follow #779 for updates on this issue.
