### ISSUE TITLE
Incorrect path shown in the map

### ISSUE THREAD

**Issue by srinath2468** [mapbox/mapbox-navigation-android#86]
![prob](https://user-images.githubusercontent.com/25114497/27221518-eb7bd606-5299-11e7-96d2-87def3643551.png)

@tobrun 

I am relatively new to app development and mapbox. As you can see above, the polyline does not indicate the exact route for navigation. Is there any way i can increase the number of coordinates so that the route becomes more accurate?

**Comment by srinath2468** [comment]
As you can see above, the polyline does not indicate the exact route for navigation. Is there any way i can increase the number of coordinates so that the route becomes more accurate?

**Comment by davols** [comment]
What is your call to get the route? If you use The MapboxDirections client you might be missing
`.setOverview(DirectionsCriteria.OVERVIEW_FULL)`

**Comment by tobrun** [comment]
cc @cammace

**Comment by srinath2468** [comment]
@davols  it worked! 
@tobrun @cammace 
thank you so much

On a totally unrelated note. I am using Mapbox' geocoding widget to get the latitude and longitude of my destination. Most of the locations present in india does not show up in Mapbox's widget so is there any integration that can be done between a google geocoder and mapbox' geocoder?

**Comment by cammace** [comment]
if you use `MapboxNavigation.getRoute()` you shouldn't run into this issue since it handles the directions request for you. We do not offer any out of the box solutions for integrating Google's geocoder with the Mapbox Geocoder.
