### ISSUE TITLE
Bump Architecture Components version to avoid building conflict issues

### ISSUE THREAD

**Issue by Guardiola31337** [mapbox/mapbox-navigation-android#864]
When testing https://github.com/mapbox/mapbox-navigation-android/pull/697 noticed some building conflicts with the latest version of LLP 👀
```
* What went wrong:
Execution failed for task ':app:preDebugBuild'.
> Android dependency 'android.arch.lifecycle:runtime' has different version for the compile (1.0.3) and runtime (1.1.1) classpath. You should manually set the same version via DependencyResolution
```

We aren't using the latest version of Architecture Components `1.1.1` (LLP included that version in https://github.com/mapbox/mapbox-plugins-android/pull/419) so in order to avoid them when we add any new LLP version we should bump the Architecture Components version in the Nav side as well.

**Comment by Guardiola31337** [comment]
Noting here that even bumping [`lifecycle`](https://github.com/mapbox/mapbox-navigation-android/blob/master/gradle/dependencies.gradle#L32) version to `1.1.1` the conflict mentioned in OP is still present. Apparently `com.android.support:support-annotations:27.0.2` includes `android.arch.lifecycle:runtime:1.0.3` which is incompatible with version `1.1.1` (breaking SemVer?) 👀
```
+--- com.android.support:support-core-utils:27.0.2
|         |    |         |    +--- com.android.support:support-annotations:27.0.2
|         |    |         |    \--- com.android.support:support-compat:27.0.2
|         |    |         |         +--- com.android.support:support-annotations:27.0.2
|         |    |         |         \--- android.arch.lifecycle:runtime:1.0.3 -> 1.1.1
|         |    |         |              +--- android.arch.lifecycle:common:1.1.1
|         |    |         |              |    \--- com.android.support:support-annotations:26.1.0 -> 27.0.2
|         |    |         |              +--- android.arch.core:common:1.1.1
|         |    |         |              |    \--- com.android.support:support-annotations:26.1.0 -> 27.0.2
|         |    |         |              \--- com.android.support:support-annotations:26.1.0 -> 27.0.2
```
For now, we'd need to explicitly include `android.arch.lifecycle:extensions:1.1.1` in the app's `build.gradle` file to force use `android.arch.lifecycle:runtime:1.1.1` and avoid the building conflicts. I already tested the workaround and it worked.

👀 https://github.com/mozilla-mobile/focus-android/issues/1615

**Comment by danesfeder** [comment]
@Guardiola31337 should we update our support library version?  Is there anything blocking us from updating?

**Comment by LukasPaczos** [comment]
@Guardiola31337 Just run into this myself and noting here that lifecycle components `1.1.1` bring [no significant changes](https://developer.android.com/jetpack/docs/release-notes#march_21_2018) so if it's blocking you in any way, you can safely use `1.1.0`.

**Comment by Guardiola31337** [comment]
> Just run into this myself and noting here that lifecycle components `1.1.1` bring [no significant changes](https://developer.android.com/jetpack/docs/release-notes#march_21_2018) so if it's blocking you in any way, you can safely use `1.1.0`.

Nah, not blocking, it's in the test app 👀
> For now, we'd need to explicitly include `android.arch.lifecycle:extensions:1.1.1` in the app's `build.gradle` file to force use `android.arch.lifecycle:runtime:1.1.1` and avoid the building conflicts.

BTW in that case, in order to avoid having to explicitly exclude `1.1.1` and force `1.1.0` version, IMO it should be done upstream in the LLP.

**Comment by Guardiola31337** [comment]
Both the Nav SDK (👀 https://github.com/mapbox/mapbox-navigation-android/pull/697/files#diff-6512f838e273b79676cac5f72456127fR32) and LLP (https://github.com/mapbox/mapbox-plugins-android/commit/9d1c682eb35f520372251ab4c2fad529439b25e8#diff-6512f838e273b79676cac5f72456127fR31) now use `1.1.1` version.

Closing here.

**Comment by mookyjan** [comment]
I have also same problem when using version implementation "android.arch.lifecycle:reactivestreams:1.1.1" with 27.1.1 but when i downgrade the dependency of lifecyle to implementation "android.arch.lifecycle:reactivestreams:1.1.0" then it works fine.
