### ISSUE TITLE
Android Navigation route get ssl error

### ISSUE THREAD

**Issue by kobe8ouchao** [mapbox/mapbox-navigation-android#867]
**Android API:**
**Mapbox Navigation SDK version:**

### Steps to trigger behavior

 1. request route api in Navigation 
 2. logcat show Failed to load sprite: failed to connect ssl Failed to load source traffic: SSL handshake timed out
 I think maybe the SSL timeour, we are in China, what is problem?

**Comment by danesfeder** [comment]
Hey @kobe8ouchao, thanks for checking out the SDK.  This is actually a possible issue with our directions API / Java services library.  Going to move this ticket there for better tracking purposes.

**Comment by danesfeder** [comment]
@kobe8ouchao can you try using a VPN to get a global geoip? 

cc @chriswu42

**Comment by kobe8ouchao** [comment]
Thank you for your reply. I have used a VPN to connect Navigation Service, but sometimes working well, sometimes failing, the throwable message is java.net.SocketTimeoutException: SSL handshake timed out.

**Comment by chriswu42** [comment]
@kobe8ouchao to guarantee stable services from inside China please reach out to our sales team to get access to our `api.mapbox.cn` endpoints. We cannot guarantee stability with `api.mapbox.com` from inside China due to regulations around the Great Firewall.
