### ISSUE TITLE
Question: Re-Joining Route

### ISSUE THREAD

**Issue by Danny-James** [mapbox/mapbox-navigation-android#872]
**Information**
If I have a route plotted and start the Navigation UI with `OffRouteDetection` and `SnapToRoute` Turned `OFF` say if I am already half way through the route and I want to join the route in say the middle will the Navigation know about this and just continue?

You may get a better understanding of what I mean by looking at the below screenshot.

**Screenshot**
![screenshot_20180420-103251_route info 1](https://user-images.githubusercontent.com/32104383/39044167-f0b6b9b0-447e-11e8-939d-513a8a88ba65.jpg)

As you can see above I'm near `Standish`, however the route start is near `Leyland` and route is going `South` down the `M6`, I can join the `M6` in `Standish`, if I do this will the Navigation allow me to join and give me the correct instructions to continue?

**Comment by danesfeder** [comment]
@Danny-James have you tested this works?  I've tested on my end and confirmed that correct processing resumes when the location updates return to the route.  Would like you to double check on your end as well though.

**Comment by Danny-James** [comment]
@danesfeder as you can see I started the route like the screenshot, I haven't been on the route at this point, are you saying this should work?

As you can see I have waypoints, what should happen should the Navigation know that I'm on the route and discard anything previous to where I join the route?

Or do I need to start at the beginning of the route? My main reason for this is if my users go off route and re-join the route further down the Navigation should understand this and begin giving instructions from where they join.

**Comment by Danny-James** [comment]
@danesfeder I gave this a try on my way home, how I tested was plot a route from my work to home, but only start the NavigationUI when I got half way, I expected it to begin giving me directions, I was travelling along the route correctly.

However, I only received the first instruction as if I was still at the start of the route.

**Comment by Danny-James** [comment]
@danesfeder I've had one of our users who is testing our application report an issue, the user had an issue with his device when he was 30 miles into his journey, he had to pull over reload the app and start the navigation again, we have a Start Location and a Destination so when the user restarted the app 30 miles in it was giving him instructions for the start point, how can we have this so it knows you are already on the route so it can continue?

This would also work for when they go off route and then re-join further along the route or re-join the route further back - is their a way the Navigation UI can give the relevant instructions?

**Comment by Danny-James** [comment]
@danesfeder any news on speaking with your team on this?

I've had allot of reports from our testers about this issue.

**Comment by danesfeder** [comment]
@Danny-James is there a specific reason that you have both snapping and off-route detection disabled?  These are two main features of the SDK and I'm curious as to why you feel they aren't needed.

**Comment by Danny-James** [comment]
@danesfeder The reason for this we are a Crane Hire company and the cranes are only allowed to travel down an authorised route, the authorities will approve the route a few days before the scheduled travel date, it is important the crane stays on the approved route and if they happen to go off this route we do not want the navigation to automatically re calculate as the drivers will follow this, this is the reason for setting `enableOffRouteDetection` to `FALSE`.

And I believe I have `snapToRoute` set to `FALSE` to allow the navigation to go off route.

We have routes from one depot to another however some drivers will use this route and pick it up halfway through the route so this is where we need the navigation to know if the user is already on route so it can continue, if you need more explanation on this point let me know.

**Comment by Danny-James** [comment]
@danesfeder do you have an update on this please?

**Comment by Danny-James** [comment]
Own Logic Created, Calculate Distance From Current Locations to Each Point in Navigation And Start From Closest Point.
