### ISSUE TITLE
Question: Route Plotting

### ISSUE THREAD

**Issue by Danny-James** [mapbox/mapbox-navigation-android#873]
**Question**

We use a 3rd party piece of software which uses `Google Maps` to plot a route, we then extract the `Origin`, `Destination` and `Waypoints` from the `Google Maps` we then pass these via an API to the Application I have been developing.

We originally was passing the `Google Maps` route to `Google Maps Application` which would then plot the route the same. However, we came across an issue with `Waypoints`, you had to touch the screen to Continue when you got to a Waypoint (Which is illegal in the UK) where we wanted it to auto continue as we was using waypoint to direct our users around things (Road Closures, Low Tunnels, Weak Bridges).

So that's how I got to using `MapBox`, however because the route which is plotted on `Google Maps` using the 3rd Party Software this route is authorised by the Local Authorities and therefore, the route cannot change.

I've come across an instance when testing which may help you understand, the image below show's the route plotted by `Google Maps (Blue)` and The Difference with `MapBox Route (Red)`.

![mapplot](https://user-images.githubusercontent.com/32104383/39049372-c160a7c2-4490-11e8-9ef5-f21da3013169.png)

Is their anything I can do so it plots the same as Google or as close as possible, or anything you can recommend? 

Thanks.

**Comment by Danny-James** [comment]
@danesfender I'm going to try and pull out the geoJSON from the routes plotted on our 3rd Party Software, hopefully this will contain lots of GPS Coordinates and then I can pass these into the MapMatching which can then be converted to a directions route.

Do you think this could work?

**Comment by danesfeder** [comment]
@Danny-James yeah, you just need to make sure it's under the 100 waypoint (current max) of the MapMatching api?

**Comment by danesfeder** [comment]
@Danny-James No unfortunately not.  Also, fair warning, I'd be wary of doing this.  Google has restrictions surrounding using their data on maps that also aren't theirs.  I'd double check with your 3rd party software provider that this is okay.

**Comment by Danny-James** [comment]
@danesfeder Yes, I will check with the 3rd Party - You can close this issue as it was only opened to ask questions I believe I have found a possible solution.

Thanks Again.

**Comment by danesfeder** [comment]
No problem, thanks @Danny-James

**Comment by Danny-James** [comment]
@danesfeder Please see #1019 would you be able to assist?
