### ISSUE TITLE
Detect a type of maneuver?

### ISSUE THREAD

**Issue by atomike-toxic** [mapbox/mapbox-navigation-android#874]
I would like to check a condition when the route indicates to turn left or right. I use mapbox as a navigation SDK.

In their technical documentation, he tells us that we can use StepManeuver object:

Example:

```
{
  "bearing_before": 299,
  "bearing_after": 202,
  "type": "turn",
  "modifier": "left",
  "location": [
    13.424671,
    52.508812
  ],
  "instruction": "Turn left onto Adalbertstraße"
}
```
What interests me is the value "modifier" which can be associated with "left" or "right".

So I would like to create a condition "if turn left then [...]" and "if turn right then [...]". But I do not know if this is possible and I do not know how to do it, thank you very much for your help.

**Comment by danesfeder** [comment]
Hey @atomike-toxic this is definitely possible and you can do it by adding a [`ProgressChangeListener`](https://www.mapbox.com/android-docs/navigation/overview/route-progress/#on-progress-change).  

You can access the upcoming maneuver via:
```
RouteProgress#currentLegProgress()#upcomingStep()#manevuer()
```
This will return a `StepManeuver` object with the data you are looking for.  

Also, in the future, if you have any other questions like this, please head over to https://stackoverflow.com/questions/tagged/mapbox.  We use the repo issues to track bugs / new features.  Thanks a lot!

**Comment by atomike-toxic** [comment]
Thank you very much !
I will try this ;)
