### ISSUE TITLE
Bug: Waypoint Visual/Voice Instruction Issue

### ISSUE THREAD

**Issue by Danny-James** [mapbox/mapbox-navigation-android#876]
I've been testing the Navigation UI with Waypoints, and their seems to be an issue with Visual and Voice instructions, once you pass a waypoint the last instruction before the waypoint continually shows and no more voice instructions are given.

**Device**
```
Google Pixel XL - Android: 8.1.0
```

**Gradle**
```java
implementation('com.mapbox.mapboxsdk:mapbox-android-navigation-ui:0.13.0-SNAPSHOT') {
        transitive = true
        changing = true
    }
```

**Navigation Options**
```java
NavigationLauncherOptions.Builder navOptions = NavigationLauncherOptions.builder()
	.directionsRoute(currentRoute)
	.directionsProfile(DirectionsCriteria.PROFILE_DRIVING)
	.locale(Locale.UK)
	.unitType(NavigationUnitType.TYPE_IMPERIAL)
	.enableOffRouteDetection(false)
	.snapToRoute(false);
```

**Screenshot**
![screenshot_20180423-122053](https://user-images.githubusercontent.com/32104383/39131554-3df8d780-46ff-11e8-8755-7b759cb3e206.png)

As you can see with the screenshot, I was instructed to turn left which I did but then I did not receive any other instructions.

**Comment by danesfeder** [comment]
Hey @Danny-James, this bug is a result of #872.  It looks like route processing is not resuming when re-joining the route.  

Let's use #872 to track the fix - thanks for reporting!
