### ISSUE TITLE
cannot resolve method setLocationSource

### ISSUE THREAD

**Issue by bindu623** [mapbox/mapbox-navigation-android#88]
In MockNavigationActivity.java,inside method onMapReady(),I am getting error in this line
        locationEngine = new MockLocationEngine();
        mapboxMap.setLocationSource(locationEngine);
It is saying "cannot resolve method setLocationSource"
I am using same gradle dependencies as mentioned in documents.
Kindly help to resolve this issue

**Comment by cammace** [comment]
Can you try switching the Map SDK version to 5.1.0-beta.4 and see if it resolves the issue?

**Comment by bindu623** [comment]
I have  changed sdk  to-com.mapbox.mapboxsdk:mapbox-android-sdk:5.1.0-beta.4@aar
it is showing error-
Error:Could not find com.mapzen.android:lost:3.0.1-20170607.212149-4.
Required by:
    MapboxApp:app:unspecified > com.mapbox.mapboxsdk:mapbox-android-sdk:5.1.0-beta.4@aar

**Comment by cammace** [comment]
```java
// Mapbox Maps SDK
compile ('com.mapbox.mapboxsdk:mapbox-android-sdk:5.1.0-beta.4@aar') {
    transitive = true
    exclude module: 'lost'
    exclude module: 'mapbox-java-geojson'
    exclude module: 'mapbox-android-telemetry'
}
```

**Comment by bindu623** [comment]
This solution worked.Thanks a lot for your help.
