### ISSUE TITLE
app_name is overwrite by libandroid-navigation

### ISSUE THREAD

**Issue by ben-j69** [mapbox/mapbox-navigation-android#883]
Hello,

the values in differents folders like "values-fr" are taking priority on the values of my app, the result is that in french my android app is now called "SDK de navigation Mapbox pour Android" because my app_name value is replaced by the on in libandroid-navigation

**Android API:16
**Mapbox Navigation SDK version:0.12.0

### Steps to trigger behavior

 1.Integrate mapbox navigation
 2.Build the project
 3.Start the app

### Expected behavior
My app should have its own name from app_name

### Actual behavior
app_name from libandroid-navigation is taking priority

**Comment by danesfeder** [comment]
Hey @ben-j69, yeah it looks like we are storing our test application label `String` `app_name` in the core library which is incorrect.  

We can adjust this on our side - but while we work on this, would a simple fix on your end be changing the name of the `String` resource?  That way there is no conflict.  From `app_name` to `your_app_name` or something like that.
