### ISSUE TITLE
Korean translation

### ISSUE THREAD

**Issue by tan-tran-ea** [mapbox/mapbox-navigation-android#888]
Hi team,

I have translated all strings into Korean (ko)

https://www.transifex.com/mapbox/mapbox-gl-native/language/ko/
https://www.transifex.com/mapbox/mapbox-navigation-sdk-for-android/language/ko/
https://www.transifex.com/mapbox/mapbox-navigation-ios/language/ko/

Also I have translated all OSRM strings: 
https://github.com/Project-OSRM/osrm-text-instructions/issues/241

Please help me review and let me know if I need to change anything
Hopefully the translation will be merged soon

Thanks.

**Comment by danesfeder** [comment]
Hey @tan-tran-ea, thanks for the work here!  I pulled in the new translations from Transifex in #889.  If you want to take a look and see if it checks out, that would be great.

**Comment by 1ec5** [comment]
I pulled your translations of OSRM Text Instructions into Project-OSRM/osrm-text-instructions#243. Please have a look at that as well. Thanks!

**Comment by tan-tran-ea** [comment]
Thanks @danesfeder , @1ec5 

Also please help me pull the translations for Mapbox Navigation iOS and Mapbox GJ Native. I have translated all strings (excluded sample app)

Thanks so much

**Comment by 1ec5** [comment]
> Also please help me pull the translations for Mapbox Navigation iOS and Mapbox GJ Native. I have translated all strings (excluded sample app)

Thanks, pulling these translations in mapbox/mapbox-navigation-ios#1346 and mapbox/mapbox-gl-native#11792. Note that, although Project-OSRM/osrm-text-instructions#243 has been merged, we’ll need to release OSRMTI and deploy it as part of the Directions API before you’ll be able to receive instructions in Korean.
