### ISSUE TITLE
Crash due to class naming collision in 0.12.0

### ISSUE THREAD

**Issue by tonyc10** [mapbox/mapbox-navigation-android#897]
**Android API: 27**
**Mapbox Navigation SDK version: 0.12.0 **

Hi —

I’m seeing a bug in the code of your new navigation libraries, with different versions of a class called FeatureCollection.  One version is  `com.mapbox.services.commons.geojson.FeatureCollection`
The other is `com.mapbox.geojson.FeatureCollection`

The class `MapUtils`  (`com.mapbox.services.android.navigation.ui.v5.utils`) gets it mixed-up.

On line 43 it instantiates GeoJsonSource, 

`new GeoJsonSource(sourceId, collection, routeGeoJsonOptions);`

Where collection is a `com.mapbox.services.commons.geojson.FeatureCollection`
However, `GeoJsonSource`, expects a `com.mapbox.geojson.FeatureCollection.`

This is causing a crash in my app, while I am trying to get NavigationMapRoute.addRoute( :DirectionsRoute) to draw a route for me.

I am using the following map-box libraries:

implementation 'com.mapbox.mapboxsdk:mapbox-android-sdk:6.0.1'
implementation 'com.mapbox.mapboxsdk:mapbox-android-navigation:0.12.0'
implementation ('com.mapbox.mapboxsdk:mapbox-android-navigation-ui:0.12.0') {
    transitive = true
}
implementation 'com.mapbox.mapboxsdk:mapbox-android-plugin-locationlayer:0.5.0'
implementation 'com.mapbox.mapboxsdk:mapbox-android-plugin-traffic:0.4.0'
implementation ('com.mapbox.mapboxsdk:mapbox-android-geocoder:1.0.0@aar'){
    transitive=true
}

Any ideas?

**Comment by Guardiola31337** [comment]
Hey @tonyc10 👋 thanks for reaching out and report your problem.

This should be fixed now (#697 landed last week) and it'll be available in the next release. In the meantime, could you please retest this using `0.13.0-SNAPSHOT` and report back if it's still an issue?

Following you can find installation instructions for `SNAPSHOT`s:

```java
repositories {
    jcenter()
    maven { url "http://oss.sonatype.org/content/repositories/snapshots/" }
    // ...
}

dependencies {
    // ...
    implementation 'com.mapbox.mapboxsdk:mapbox-android-navigation:0.13.0-SNAPSHOT'
    implementation 'com.mapbox.mapboxsdk:mapbox-android-navigation-ui:0.13.0-SNAPSHOT'
    // ...
}
```

Thanks again!

**Comment by tonyc10** [comment]
Yes -- This issue is fixed for me in 0.13.0-SNAPSHOT.
Thanks!

**Comment by Guardiola31337** [comment]
@tonyc10 glad to hear, thanks for the update!

It'll be included in the next release. We'll keep you posted.

Closing here.

**Comment by tonyc10** [comment]
Hi Pablo,

You recently referred to not receiving any voice instructions when starting
to use 0.13.0  (
https://github.com/mapbox/mapbox-navigation-android/issues/750)

How did you resolve that?  I also am not seeing (hearing) any voice since
I've moved up to 0.13.0

Tony

**Comment by Guardiola31337** [comment]
Hey @tonyc10 👋 thanks for reaching out and report your problem.

This is being tracked in https://github.com/mapbox/mapbox-navigation-android/issues/922

Could you add some more information for reproducing the issue (minimal example) or any other specifics around your test setup in that ticket? Do you have some more information on used device? If there is any sample or pseudo code you can provide that would be really helpful.
