### ISSUE TITLE
JVMTI error

### ISSUE THREAD

**Issue by vladgheorghe** [mapbox/mapbox-navigation-android#900]
On the latest version of 0.13.0-SNAPSHOT I am seeing a spam of these errors in logcat and the app sometimes crashes randomly without any stracktrace.

E/StudioProfiler: JVMTI error: 15(JVMTI_ERROR_THREAD_NOT_ALIVE)
I/chatty: uid=10197(ro.ascendnet.android.startaxi.taximetrist) Thread-164 identical 5 lines

**Comment by danesfeder** [comment]
Hey @vladgheorghe, the crash you're describing here, does it seems related to #901?  Can you provide logs with more detail than the one you provided here? 

@tobrun @LukasPaczos have either of you seen a log like this before?

**Comment by Guardiola31337** [comment]
Hey 👋 @vladgheorghe thank you for reaching out and reporting your problem.

It seems the same issue as #901 could you confirm please?

BTW, could you add some more information for reproducing the crash (minimal example) or any other specifics around your test setup? Do you have some more information on used device and Android version? If there is any sample or pseudo code you can provide, that would also be helpful.

**Comment by vladgheorghe** [comment]
Unfortunately I haven't seen this issue in the last days but it does not seem to be to 901

**Comment by Guardiola31337** [comment]
Hey @vladgheorghe if you experience OP again feel free to open a new ticket or reopening this one. Thanks!

Closing here.

**Comment by monashri** [comment]
With these below spam of error logs , app gets crashed often .
**E/StudioProfiler: JVMTI error: 15(JVMTI_ERROR_THREAD_NOT_ALIVE)**
  
Am using below dependencies 
   ` api 'com.mapbox.mapboxsdk:mapbox-android-sdk:6.1.1'
     api 'com.mapbox.mapboxsdk:mapbox-android-plugin-locationlayer:0.5.2'
     api 'com.mapbox.mapboxsdk:mapbox-android-plugin-cluster-utils:0.4.0'`

Any specific reason behind it ?  Anyone else faced the same ?

**Comment by keitoro** [comment]
I am seeing the same error when just running the mapView without anything running on the map. It wasn't there a few hours ago. The map doesn't crash. I am getting this error log when running the emulator.

**Comment by danesfeder** [comment]
Are either of these errors related to the Navigation SDK?  If you feel they are related to the Maps SDK, feel free to open a new ticket in https://github.com/mapbox/mapbox-gl-native/issues/new 

Thanks!

**Comment by P-Zenker** [comment]
Good question if this is a mabox-gl-native issue.

Android API: 26 (Samsung A6)
Mapbox Navigation SDK version: 0.18.0

I only show the mapbox map view and it doesn't matter if I grant location permissions or not to the app. On a Google Nexus 5 with API 25 everything is fine.

But if I run the Mapbox Demo app there are no logs. 

```
09-07 15:42:29.425 24160-25281/... E/StudioProfiler: JVMTI error: 15(JVMTI_ERROR_THREAD_NOT_ALIVE) 
09-07 15:42:29.425 24160-25280/... E/StudioProfiler: JVMTI error: 15(JVMTI_ERROR_THREAD_NOT_ALIVE) 
09-07 15:42:29.425 24160-25281/... E/StudioProfiler: JVMTI error: 15(JVMTI_ERROR_THREAD_NOT_ALIVE) 
09-07 15:42:29.426 24160-25280/... E/StudioProfiler: JVMTI error: 15(JVMTI_ERROR_THREAD_NOT_ALIVE) 
09-07 15:42:29.447 24160-25282/... E/StudioProfiler: JVMTI error: 15(JVMTI_ERROR_THREAD_NOT_ALIVE) 
09-07 15:42:29.447 24160-25282/... E/StudioProfiler: JVMTI error: 15(JVMTI_ERROR_THREAD_NOT_ALIVE) 
09-07 15:42:29.449 24160-25279/... E/StudioProfiler: JVMTI error: 15(JVMTI_ERROR_THREAD_NOT_ALIVE) 
09-07 15:42:29.450 24160-25279/... E/StudioProfiler: JVMTI error: 15(JVMTI_ERROR_THREAD_NOT_ALIVE) 
09-07 15:42:29.451 24160-25281/... E/StudioProfiler: JVMTI error: 15(JVMTI_ERROR_THREAD_NOT_ALIVE) 
09-07 15:42:29.452 24160-25281/... E/StudioProfiler: JVMTI error: 15(JVMTI_ERROR_THREAD_NOT_ALIVE) 
09-07 15:42:29.452 24160-25280/... E/StudioProfiler: JVMTI error: 15(JVMTI_ERROR_THREAD_NOT_ALIVE) 
09-07 15:42:29.452 24160-25280/... E/StudioProfiler: JVMTI error: 15(JVMTI_ERROR_THREAD_NOT_ALIVE) 
09-07 15:42:29.453 24160-25282/... E/StudioProfiler: JVMTI error: 15(JVMTI_ERROR_THREAD_NOT_ALIVE) 
    JVMTI error: 15(JVMTI_ERROR_THREAD_NOT_ALIVE) 
09-07 15:42:29.453 24160-25279/... E/StudioProfiler: JVMTI error: 15(JVMTI_ERROR_THREAD_NOT_ALIVE) 
09-07 15:42:29.453 24160-25282/... E/StudioProfiler: JVMTI error: 15(JVMTI_ERROR_THREAD_NOT_ALIVE) 
09-07 15:42:29.453 24160-25279/... E/StudioProfiler: JVMTI error: 15(JVMTI_ERROR_THREAD_NOT_ALIVE) 
09-07 15:42:29.453 24160-25282/... E/StudioProfiler: JVMTI error: 15(JVMTI_ERROR_THREAD_NOT_ALIVE) 
09-07 15:42:29.453 24160-25279/... E/StudioProfiler: JVMTI error: 15(JVMTI_ERROR_THREAD_NOT_ALIVE) 
09-07 15:42:29.453 24160-25282/... E/StudioProfiler: JVMTI error: 15(JVMTI_ERROR_THREAD_NOT_ALIVE) 
```

**Comment by xzxedu** [comment]
I have the same problem, any idea how to fix it?
here is my dependencies:

android {
    compileSdkVersion 27
    defaultConfig {
        applicationId "com.example.xzx.coinz"
        minSdkVersion 25
        targetSdkVersion 27
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions{
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation"org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    implementation 'com.android.support:appcompat-v7:27.1.1'
    implementation'com.android.support:animated-vector-drawable:27.1.1'
    implementation'com.android.support:cardview-v7:27.1.1'
    implementation 'com.android.support.constraint:constraint-layout:1.1.3'
    implementation 'com.android.support:design:27.1.1'
    implementation'com.google.android.gms:play-services-location:15.0.1'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.2'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'
    //mapbox dependencies
    implementation'com.mapbox.mapboxsdk:mapbox-android-sdk:6.7.1'
    implementation'com.mapbox.mapboxsdk:mapbox-android-plugin-locationlayer:0.11.0'
}

**Comment by bacarPereira** [comment]
I'm facing the same problem but this error only appears when I run the Profiler in Android Studio and if I'm in an Activity or Fragment with mapView.
<img width="532" alt="Captura de ecrã 2021-06-08, às 22 54 51" src="https://user-images.githubusercontent.com/43761389/121262796-9a161280-c8ac-11eb-9347-e8affbec26a5.png">
