### ISSUE TITLE
ProgressListener After destination reached

### ISSUE THREAD

**Issue by bliveinhack** [mapbox/mapbox-navigation-android#902]
Hello,

we are using Navigatoin SDK for routing a start & destination locations.
now the situations is after reaching at destinations .  we need to go ahead . let's say for another 3 miles. so the progressListener is not working as expected. 
- provided Rerouting is off.
- off route detection is on.

```
navigation.addProgressChangeListener(new ProgressChangeListener() {
  @Override
  public void onProgressChange(Location location, RouteProgress routeProgress) {
               // We still need this listener to fire when we are going forward with destination address. 
  }
});
```

 let us know if we are missing something.

**Comment by danesfeder** [comment]
Hey @bliveinhack - I'm not completely following your question here.  Are you saying the `ProgressChangeListener` is not firing after you have arrived at your destination and you would like to continue to receive `Location` updates regardless?
