### ISSUE TITLE
Feature Request: Overlay arrows on turn-by-turn navigation

### ISSUE THREAD

**Issue by richjhart** [mapbox/mapbox-navigation-android#906]
**Mapbox Navigation SDK version:** 0.12.0

The iOS turn-by-turn navigation currently overlays an arrow on the map indicating the next turn.

It would be great if Android did this too. Would it be possible to get an indication of if/when this might happen (to decide if it's worth investing the time overlaying my own image/polygon)?

**Comment by Guardiola31337** [comment]
Hey @richjhart 👋 thanks for reaching out and report your question.

There's already a ticket tracking this 👀 https://github.com/mapbox/mapbox-navigation-android/issues/604 and we're actively working on it to make it happen soon. Hopefully it'll be included in the next release version so I'd say that it's not worth investing time from your side.

Closing as answered.
