### ISSUE TITLE
MapboxTelemetry.optLocationOut crashes

### ISSUE THREAD

**Issue by vladgheorghe** [mapbox/mapbox-navigation-android#919]
Hello, starting with 0.13 release we've started seeing a few of these crashes, sharing the crash report here

http://crashes.to/s/2ce1b0a6a7f

**Comment by danesfeder** [comment]
Hey @vladgheorghe, thanks for bringing this to us - we are going to take a look on our side and get back to you here.  

cc @electrostat @Guardiola31337 @zugaldia for telem visibility

**Comment by Guardiola31337** [comment]
Hey @vladgheorghe 👋 thanks for reaching out and report your problem.

This should be fixed now (https://github.com/mapbox/mapbox-events-android/pull/136 landed) and it'll be included in the next release. In the meantime, could you please retest this including `mapbox-android-telemetry:3.2.0-SNAPSHOT` explicitly and report back if it's still an issue?

Following you can find installation instructions for `SNAPSHOT`s:

```java
repositories {
    jcenter()
    maven { url "http://oss.sonatype.org/content/repositories/snapshots/" }
    // ...
}

dependencies {
    // ...
    implementation 'com.mapbox.mapboxsdk:mapbox-android-navigation:0.13.0'
    implementation 'com.mapbox.mapboxsdk:mapbox-android-navigation-ui:0.13.0'
    // ...
    implementation 'com.mapbox.mapboxsdk:mapbox-android-telemetry:3.2.0-SNAPSHOT'
    // ...
}
```

Thanks again!

**Comment by vladgheorghe** [comment]
Hello @Guardiola31337, we're going to going distribute a beta build with this modification and come back with a reply however it might take a while as the crash is pretty rare.

**Comment by Guardiola31337** [comment]
@vladgheorghe awesome! Keep us posted. Thanks again.

**Comment by Guardiola31337** [comment]
Hey @vladgheorghe if you experience OP again feel free to open a new ticket or reopening this one. Thanks!

Closing here.
