### ISSUE TITLE
Arrival event should be keyed off of arrival instructions from the server

### ISSUE THREAD

**Issue by akitchen** [mapbox/mapbox-navigation-android#926]
Per @danesfeder we currently use a hardcoded arrival distance of 40m

Let's please remove this in favor of the arrival instructions provided by the server, which has been adjusted to 10 seconds. Removing this hardcoding will give us better platform symmetry and allow this heuristic to be adjusted in one place in the future.

**Comment by coxchapman** [comment]
@akitchen when you say 
>in favor of the arrival instructions provided by the server, which has been adjusted to 10 seconds.
Do you mean that we will throw an arrival event as soon as a user is within a 10-second duration of a location?

**Comment by akitchen** [comment]
> Do you mean that we will throw an arrival event as soon as a user is within a 10-second duration of a location?

Yes, and this is determined by the guidance we receive from the server, which could be subject to change or customization.
