### ISSUE TITLE
Keep sources in memory

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-navigation-android#928]
When looking into https://github.com/mapbox/mapbox-gl-native/issues/11843. I'm noticing the following in [MapUtils](https://github.com/mapbox/mapbox-navigation-android/blob/d339f623aac301722ac32239276f189641c1bf6c/libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/utils/MapUtils.java):

```java
  public static void updateMapSourceFromFeatureCollection(@NonNull MapboxMap mapboxMap,
                                                          @Nullable FeatureCollection collection,
                                                          @NonNull String sourceId) {
    if (collection == null) {
      collection = FeatureCollection.fromFeatures(new Feature[] {});
    }

    GeoJsonSource source = mapboxMap.getSourceAs(sourceId);
    if (source == null) {
      GeoJsonOptions routeGeoJsonOptions = new GeoJsonOptions().withMaxZoom(16);
      GeoJsonSource routeSource = new GeoJsonSource(sourceId, collection, routeGeoJsonOptions);
      mapboxMap.addSource(routeSource);
    } else {
      source.setGeoJson(collection);
    }
  }
```

With every update we are getting the source from MapboxMap, this is an expensive task which requires to go through JNI to C++ an back. Instead of creating new instances with getSourceAs we should cache the value of the source.

**Comment by tobrun** [comment]
The idea here is to keep sources/layers in memory and reload them when a new style has been loaded (map change event).

**Comment by rishabhsri20** [comment]
Any solution for this freeze? Happens with me when starting a navigation.

**Comment by danesfeder** [comment]
Hey @rishabhsri20, this ticket is "next up" for our pipeline of work - stay tuned for updates as we update this ticket once work begins.  Thank you for your patience!

**Comment by danesfeder** [comment]
@LukasPaczos I recall having a brief discussion about this during #1387 - we would get some performance wins by not using the `MapUtil` as Tobrun mentioned

**Comment by tobrun** [comment]
@danesfeder since v7.0.0 this is optimised under the hood, if you can `Style#getSource(id)` it will return a cached source if available (same goes for layers). 

```java
  @Nullable
  public Source getSource(String id) {
    validateState("getSource");
    Source source = sources.get(id);
    if (source == null) {
      source = nativeMapView.getSource(id);
    }
    return source;
  }
```

Don't think this issue is actionable anymore.

**Comment by danesfeder** [comment]
Awesome thanks for the clarification here @tobrun, closing with #1615
