### ISSUE TITLE
Turn by Turn Navigation marker not updated?

### ISSUE THREAD

**Issue by Meerz** [mapbox/mapbox-navigation-android#933]
hi i facing an issue when i start navigation the navigation marker is not move or no movement with our location
 NavigationViewOptions options = NavigationViewOptions.builder()
                .origin(origin)
                .destination(destination)
                .navigationListener(this)
                .navigationOptions(navigationOptions)
                .directionsProfile(DirectionsCriteria.PROFILE_DRIVING)
                .build();
        navigationView.startNavigation(options);

**Comment by danesfeder** [comment]
Hey @Meerz, unfortunately, I'm not able to see the issue from the code snippet you've provided here.  In the future, please direct these implementation questions to https://stackoverflow.com/questions/tagged/mapbox.  We keep an eye on those questions as well and it helps bring visibility to other developers that may be facing similar issues.  Thanks!
