### ISSUE TITLE
How to set annotations on Mapbox with Navigation SDK?

### ISSUE THREAD

**Issue by geolyth** [mapbox/mapbox-navigation-android#94]
Hi,
I already read Mapbox Android Navigation SDK documentation but I don't understand if when I use it I can also put annotations on the same map.

Thank you,
Fabio

**Comment by cammace** [comment]
The navigation SDK currently doesn't offer annotation to directly place on top of a map, this would require a dependency on the Map SDK. Instead, we provide the geometry and necessary `Position` objects that can be used to draw on the map (this is currently done manually). 

In the near future, we will be releasing a navigation UI SDK which handles these situations for you. You can follow progress on this project inside https://github.com/mapbox/mapbox-navigation-android/pull/92.
