### ISSUE TITLE
Perform an action when a turn is indicated on the navigation

### ISSUE THREAD

**Issue by artyonline** [mapbox/mapbox-navigation-android#940]
**Android API:**
**Mapbox Navigation SDK version : 0.11.1**

What I'm trying to achieve is pass a signal to my Bluetooth IoT device whenever a turn is indicated during the navigation. Is there a method to be called or any indication to be used when the navigation is indicating turning point.

I have created an MapboxNavigationOptions object and then changed userLocationSnapDistance to increase the accuracy of the signal timing when being sent. 

I just want to know if there is any possible way to get an indication when we've reached a turning point. Thanks in advance and sorry if this is a silly question. I'm on a deadline for my university project.

**Comment by artyonline** [comment]
@danesfeder  could you please take a loot at my problem here if it's not trouble

**Comment by Guardiola31337** [comment]
Hey @artyonline 👋 thanks for reaching out and report your question.

I guess that `ProgressChangeListener` is what you're looking for. For further information you can check the documentation 👉 https://www.mapbox.com/android-docs/navigation/overview/route-progress/

In any case, this issue tracker is only for bug reports with test cases and feature requests. In the future, please direct these kind of questions to https://stackoverflow.com/questions/tagged/mapbox. We keep an eye on those questions as well and it helps bring visibility to other developers that may be facing similar issues. Thanks again!
