### ISSUE TITLE
Mapbox Navigation leaving traces of route behind

### ISSUE THREAD

**Issue by lorenzhahaha** [mapbox/mapbox-navigation-android#941]
This is just a question. Is it possible to make the traces of route left behind to be removed while moving? Like the origin point is following the current location of the user. Correct me if I'm wrong. Thanks!

**Comment by danesfeder** [comment]
Hey @lorenzhahaha, yeah I know what you mean - we've been thinking about this as well (https://github.com/mapbox/mapbox-navigation-android/issues/892).  The feature doesn't currently exist, but please follow that ticket to see when it lands.  Thanks for checking out the SDK!
