### ISSUE TITLE
Ability to add 'approaches' to NavigationRoute.Builder

### ISSUE THREAD

**Issue by Alamgir** [mapbox/mapbox-navigation-android#949]
Was hoping there are plans to add the ability to set `approaches` much like the current `bearings`. The REST api supports the ability to designate between `unrestricted` and `curb`, but `MapboxDirections.Builder` has no such support.

Reference:
https://www.mapbox.com/api-documentation/#retrieve-directions

**Comment by Guardiola31337** [comment]
Hey @Alamgir 👋 thanks for reaching out.

Yeah, first this will happen in https://github.com/mapbox/mapbox-java/issues/820

Then, we will update the `NavigationRoute` (wraps `MapboxDirections` in the Nav SDK) code to make it available.

**Comment by Guardiola31337** [comment]
Hey @Alamgir 👋 friendly reminder that #996 landed and it's available since version `0.15.0` of the SDK (we have also released `0.16.0-beta.1` afterwards).

Thanks for bringing this to us!

**Comment by Alamgir** [comment]
@Guardiola31337 thx for this!!
