### ISSUE TITLE
Add route overview button

### ISSUE THREAD

**Issue by brsbl** [mapbox/mapbox-navigation-android#950]
We should add a route overview button to the navigation UI. Zooming out to see an overview of the full route and then zooming back in is a very common action when using turn-by-turn navigation. Adding this feature makes it a lot safer for a user to do this while driving.

Here's what it looks like on iOS:
<img src="https://user-images.githubusercontent.com/19296229/40213150-cd1e86a0-5a08-11e8-9d47-23c2592c1fb0.png" height="650">

cc @mapbox/navigation-android

**Comment by Cjballard** [comment]
@danesfeder @brsbl Here are two versions of that mocked up using the current route preview icon - the first, integrating the preview button more with the trip tray (more like Google) and introducing a third action button.

![preview](https://user-images.githubusercontent.com/7535952/40272780-522fa8c8-5b81-11e8-90a6-4f3ee49b4cc6.png)

I think I prefer having it integrated into the trip tray, as it saves some map space and feels more where a user would expect to preview the current route they're on. Thoughts?
