### ISSUE TITLE
Feature Request: Allow Custom Location Engines

### ISSUE THREAD

**Issue by richjhart** [mapbox/mapbox-navigation-android#957]
As far as I can tell, currently the only options for the LocationEngine are using real GPS, or the default simulator.

It is possible to create a new Location Engine, extending com.mapbox.android.core.location.LocationEngine, but there doesn't seem to be a way to set the LocationEngine from outside the library. While in general, these two are enough, there are circumstances where setting our own would be very useful.

I don't think this would be a big change - I think mainly just a change to the LocationEngineConductor, to deactivate the old LocationEngine, set the new one, and activate it.

Ideally, it would also be good if there was an easy way to "transfer" the existing listeners (add them from the old one to the new one), but that can't currently be done directly by the LocationEngineConductor because the "locationListeners" in LocationEngine is protected.

On that note, it would also be good to be able to add a listener to the Location Engine - there are times when having the raw location is important for the UI, rather than the filtered location received in the ProgressChangeListener.

**Comment by danesfeder** [comment]
Hey @richjhart, yeah I think these are great ideas.  To summarize, this feature work would include:

1. Adding the ability to pass a custom `LocationEngine` through `NavigationViewOptions` to be activated in the `LocationEngineConductor` in favor of our defaults.  

2.  Adding a `LocationEngineListener` to `NavigationViewOptions` or creating a new listener that only passes raw `Location` updates and doesn't worry about the `LocationEngineListener#onConnected` callback.  This listener will be added to the conductor and pass raw updates.  

I'll note that both of these would only be available through the `NavigationView` implementation (not with `NavigationLauncher`) - @richjhart I believe you're already using this implementation as we've discussed using it with the Map Matching API.

**Comment by richjhart** [comment]
@danesfeder Thanks for the quick reply.

And yes, your summary looks exactly right. And yes I'm already using NavigationView (in a Fragment, rather than directly in an Activity, but I assume that shouldn't make any difference). And yes passing both in to the NavigationViewOptions would be perfect for us.

Note that currently we use reflection and do this (which obviously we'd much prefer to get rid of as soon as possible!), and there is a circumstance where we switch the LocationEngine during navigation, but that isn't necessary and I can see that it would be easier to just do it at the start, so whatever is quickest works for us! (if I had the time, I'd look at making the change myself)
