### ISSUE TITLE
Feature Request: Allow Navigation to start along the route

### ISSUE THREAD

**Issue by richjhart** [mapbox/mapbox-navigation-android#958]
As per the issues discussed in #875, it be useful if it was possible to include an initial leg/step in a startNavigation call. I would assume the best place would be in the NavigationViewOptions, along with the directionsRoute.

As noted, it's actually possible to do this with Reflection, effectively repeatedly calling a modified version of "buildNewRouteProgress()" and the associated functions, which doesn't check any conditions and always advances, until the leg/step is correct. As a result - I again don't think this would be a difficult change, but I'd be very surprised if there wasn't a more efficient way to do it.

@danesfeder Note I'm just raising this to separate it from the other conversation on #875. Not sure if you saw the message where it did fail to work as hoped once we were further from the start, as the other Map Matching issues took over a bit.

**Comment by danesfeder** [comment]
Hey @richjhart 👋 this should be unlocked with `0.20.0` - we no longer decode the route on a step-by-step basis.  If you start providing locations that are in the middle of the route you provided, we should return `RouteProgress` updates reflecting that progress along the route.

**Comment by richjhart** [comment]
@danesfeder I take it this is a fundamental change to how the route progress is done? While this is certainly useful for jumping ahead when we need to, unfortunately it basically breaks our app - because we do circular loops, rather than one-way trips. So now it's very possible for it to think the user is at the end of the loop when they've just started.

**Comment by danesfeder** [comment]
> because we do circular loops, rather than one-way trips. So now it's very possible for it to think the user is at the end of the loop when they've just started

@richjhart Let's make sure I'm following correctly here.  You have a `DirectionsRoute` that is a loop, with the end of the route coming back to the beginning?  

cc @kevinkreiser for some extra 👀 on this issue here

**Comment by richjhart** [comment]
@danesfeder Yes that's correct. I understand that wouldn't be a usual use case (though not unheard of). Basically it actually worked quite conveniently for us that by default it wouldn't automatically skip very far ahead along the route (we did allow skipping ahead a short distance under certain circumstances, but we could provide protection against it happening when we didn't want it to).

I'm looking at the code to see if there's a way we can work with it, but for now we'll need to stick with 0.19.0, which obviously isn't ideal as I don't want to get too far behind, and would mean we miss out on any other new features.

**Comment by richjhart** [comment]
@danesfeder I see that the progress is now handled by native functions. One option I'm looking at - for long term - is setting a couple of the navigation points as waypoints - as I assume the navigation wouldn't be allowed to skip past those?

This brings back the issue we have in #875 where we would need "invisible" or "via" waypoints to prevent extra arrival notifications. (We'd also have to be careful in case the user missed the waypoint by a small amount, in which case the navigation then wouldn't be able to skip past it, but we might be able to work around that).

Is there any likelihood that "via waypoints" are likely to be implemented (working out where to focus my efforts at the moment). If my earlier assumption is true (the navigation isn't allowed to skip past a waypoint), then I assume it should only be a backend change, allowing it to generate instructions and banners as though the waypoint isn't there.

**Comment by kevinkreiser** [comment]
@richjhart thats right. the navigation is on a leg by leg basis. if you have multiple way points in your loop, then it will only allow you to snap to a point along the first leg (if that is the  leg you are currently navigating against).
