### ISSUE TITLE
Mapbox Telemetry and GDPR

### ISSUE THREAD

**Issue by kozyr** [mapbox/mapbox-navigation-android#963]
I've noticed that the default  config of the Android Nav SDK periodically sends out Telemetry events back to Mapbox:
```
D/TelemetryClient: Sending POST to https://events.mapbox.com/events/v2...
```
The events have user locations and session IDs. Is that possible to disable this or somehow control the information that's being sent? With GDPR coming up soon, I can see this as being an issue  for some of the clients who'd want to use the SDK.

**Comment by kozyr** [comment]
@zugaldia This approach goes against GDPR though - you're enabling the tracking and then asking the user to opt-out. GDPR says you should be asking the user to opt-in, and providing a way to opt-out only if they do opt-in. 

As part of your events, you're receiving user IP and user locations - and user IP is personal data.

**Comment by zugaldia** [comment]
> For me it seems like the telemetry policy is in breach of the GDPR when it comes to “concent must be freely given”? Please correct me if i am wrong.

This is not correct.  The developer is responsible for seeking the end user's express consent, both for the collection of data generally (if the app does that) and for the sharing of collected location data with Mapbox.  If the end user declines to consent to _either_ of these issues, the maps would continue to work.  We do not require that developers turn off our service if they are unable to get consent from their end users, we just require that they seek the consent and turn off telemetry if the end user does not grant it.

**Comment by Stavanger75** [comment]
Hi @zugaldia ,

That is good news. Glad to be wrong. 
I tested with this code, but it will only be disabled the next time app is opened.

 TelemetryEnabler.updateTelemetryState(TelemetryEnabler.State.DISABLED);

Do you have a recomended way to disable Telemetry ?

**Comment by pamartineza** [comment]
@zugaldia as a developer updating apps for GDPR compliance, I'm afraid the current state of the SDK is not GDPR compliant. Telemetry must be disabled until I request the user for consent to share data with third party services. 

Apps including any kind of "anlytics", "ads", "crashlytics", (like Firebase, Admob...) etc, must after install (or update) show a GDPR notice to users asking consent to share personal data to third party services, we as developers have to store this consent, gdpr text, and date, and then activate if necessary Telemetry and other third party data consumers.

**Comment by pamartineza** [comment]
@zugaldia I'm not sure if I understand the proposed flow:

First thing, show consent notice, then if I users doesn't provide consent, I have to initialize Mapbox SDK to be able to see maps, which in turn enables telemetry, and then disable telemetry?

**Comment by zugaldia** [comment]
@pamartineza that's correct - because of the thresholds included with the telemetry SDK (180 events or 180 seconds) that flows guarantees no information will leave the device if the user doesn't provide consent.

In parallel, we're looking at ways to make this process smoother and more performant. If you have any feedback or suggestions on how to improve it, please do open a ticket on https://github.com/mapbox/mapbox-gl-native/issues/new and tag me for follow up. Thanks!

**Comment by Stavanger75** [comment]
@zugaldia thanks for the information.

**Comment by pamartineza** [comment]
@zugaldia a bit "hacky" but it should work
