### ISSUE TITLE
RTL not working consistently

### ISSUE THREAD

**Issue by Guardiola31337** [mapbox/mapbox-navigation-android#993]
Noticed that banner instructions were not properly aligned (RTL) while testing using Hebrew (RTL) as device language:

![shield_ca_35](https://user-images.githubusercontent.com/1668582/40982657-13f65290-68de-11e8-90e7-096cd0e0aa6b.png)

![shield_not_showing_sub_banner](https://user-images.githubusercontent.com/1668582/40982696-2e30a6ba-68de-11e8-8e9f-dfa5ecca05ef.png)

Above scenarios look even weirder because the sub banner in the first screenshot looks aligned to the right with Hebrew text, but then to the left with English text (second screenshot).

Noting that landscape layout has different constraints and apparently is working fine 👀 

![rtl_rotation](https://user-images.githubusercontent.com/1668582/40983552-3ac53b82-68e0-11e8-8fc8-8b80c24536dd.gif)

**Comment by Guardiola31337** [comment]
@abhishek1508 is this still an issue in the `1.0` UI SDK?

I believe so, so the question here would be, is this something we want to prioritize?

cc @JunDai

**Comment by abhishek1508** [comment]
Let's verify
cc @JunDai @cafesilencio @langsmith

**Comment by langsmith** [comment]
@Guardiola31337 , 👇 is my understanding of what it should look like. Does this match what you expected?

<img width="380" alt="Screen Shot 2020-08-10 at 6 01 18 PM" src="https://user-images.githubusercontent.com/4394910/89845554-af5acd00-db33-11ea-8900-99ff14b6a45f.png">


<img width="400" alt="Screen Shot 2020-08-10 at 6 01 08 PM" src="https://user-images.githubusercontent.com/4394910/89845550-ae29a000-db33-11ea-86c4-5a5e7f3a1eea.png">

**Comment by Guardiola31337** [comment]
@langsmith 
> 👇 is my understanding of what it should look like. Does this match what you expected?

Yeah :shipit:

**Comment by langsmith** [comment]
> Yeah :shipit:

Sorry to get your hopes up, but the images above are photoshopped 😆 . 

@abhishek1508 and I synced about our mutual work on this ticket. I think I might have a working fix though, which is a combination of our changes. Looking good so far on my personal device.
