### ISSUE TITLE
Map style didn't change to Dark/Night mode

### ISSUE THREAD

**Issue by Guardiola31337** [mapbox/mapbox-navigation-android#994]
Noticed this while testing:

![night_mode_not_working](https://user-images.githubusercontent.com/1668582/40983889-e1cf9dfa-68e0-11e8-8a96-d4ad49ec8d7a.png)

Map style didn't change to Dark/Night mode whereas the rest of the UI did. Noting that it happened right at 10pm.

**Comment by danesfeder** [comment]
Tracking as possible regression from https://github.com/mapbox/mapbox-navigation-android/pull/939
