### ISSUE TITLE
Can we add certain customised markers in navigation view

### ISSUE THREAD

**Issue by Bharathjh614** [mapbox/mapbox-navigation-android#999]
Now i am able to add marker while navigation for few coordinates using navigationView.addMarker(Point.fromLngLat(longitude, latitude));
by this default destination marker will be added in the coordinates but i need to add custom markers there since navigationView.addMarker( new Markeroptions()) cannot be used in navigation view may i know how to add custom markers while navigation

**Comment by danesfeder** [comment]
Hey @Bharathjh614, in `0.14.0`, there is `NavigationView#getMapboxMap()` that returns a `MapboxMap` and will give you full access to add markers of your choice after `OnNavigationReadyCallback` is triggered.  

Thanks for checking out the SDK!

**Comment by Bharathjh614** [comment]
Hey @danesfeder i used as suggested by you which is producing java null pointer exception
  Icon icon = IconFactory.getInstance(NavigationActivity.this)
             .fromResource(R.mipmap.ic_action_green_bike);
      
navigationView.getMapboxMap(map.addMarker(new MarkerOptions()
         .position(new LatLng(latitude, longitude))
          .icon(icon)  ));
  java.lang.NullPointerException: Attempt to invoke virtual method 'com.mapbox.mapboxsdk.annotations.Marker com.mapbox.mapboxsdk.maps.MapboxMap.addMarker(com.mapbox.mapboxsdk.annotations.MarkerOptions)' on a null object reference

this is the error i am getting as soon as the navigation starts

**Comment by danesfeder** [comment]
I've answered your question in #1008

**Comment by JaninaMattes** [comment]
@Bharathjh614 I am trying to figure out how to add a couple of custom markers to my navigation view. I am quite new to MapBox and I am using NavigationLauncher to start the navigation. Could you give me some more information on how you added your markers and which steps it takes?

**Comment by Bharathjh614** [comment]
@JaninaMattes here is the code to add custom markers in navigation view open **navigation activity** file in **navigation-ui** library 

```
 marker =      navigationView.getMapboxMap().addMarker(new MarkerOptions()
                        .position(new LatLng(latitude, longitude))
                        .icon(icon)
                );
```

**Comment by JaninaMattes** [comment]
Thank you a lot for your help. Just a short question, as my main issue is
how to puzzle it all together. I so far understand each component, but not
how they work together in this specific case. Do you use your
NavigationActivity as MainActivity from where you place all markers, which
means in this case I would only have NavigationView and wouldn't directly
use MapView as it is wrapped by NavigationView? Or do I have to implement
anything else?

Currently I am implementing a MainActivity only within which I use MapView
and MapBoxMap with NavigationLauncher. If I don't use NavigationLauncher to
be able to add custom markers whilst turn-by-turn navigation how could I do
that? Do you have any example or github repo.



Am Mo., 5. Nov. 2018 um 20:20 Uhr schrieb Bharathjh614 <
notifications@github.com>:
